### ISSUE TITLE
Security for remote access

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#10]
Single access tokens or password or ?

**Comment by fonsp** [comment]
I added instructions for setting up an SSH tunnel on the README (which is secure), that should be enough for now.

**Comment by Ellipse0934** [comment]
It would be useful to have a password page similar to jupyter-nb. When running Pluto inside a container in a random cluster machine it's not feasible to get a link or to pass an access key back to the user, neither is it feasible to have no security at all.  A password page would avoid this altogether. 
Maybe consider reopening this issue ?

**Comment by fonsp** [comment]
For those setups we recommend that you **build on top of an existing authentication system**, like an authenticated nginx forward proxy or JupyterLab, and set `require_secret_for_access=false`. (This is [not disabling all security](https://github.com/fonsp/Pluto.jl/blob/master/src/Configuration.jl#L21).)
