### ISSUE TITLE
Custom latex preamble

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#101]
I'm not sure if this is something Pluto is responsible for but: Is it possible to add LaTeX packages that one then can use in LaTeX code in markdown Strings?

Concretely I would like to have the physics package available in my equations in Markdown.

**Comment by fonsp** [comment]
Pluto uses MathJax to add LaTeX math support to markdown. This is not a regular *TeX distribution (those wouldn't work well inside a HTML document rendered in the browser), and it only supports the small subset of TeX commands that can be used in math mode. 

Some popular TeX extensions have been ported to MathJax, and [`physics` happens to be one of them](http://docs.mathjax.org/en/latest/input/tex/extensions/index.html). You should be able to [import it in Pluto (or any MathJax environment) using `\require{physics}`](http://docs.mathjax.org/en/latest/input/tex/extensions.html#loading-extensions-at-run-time) but this seems to be broken.

I got it to work with a very strange order of loading the page without `\require`, then adding it, then re-evalling the cell twice 😑 The MathJax source code is compiled, so it's hard to track this down

**Comment by fonsp** [comment]
I solved it by preloading all extensions by default, including `physics`. This turned out to cost much less than I thought - `1.8MB` compared to `1.6MB`. 

You still need to write `md"$\require{physics}$"` at the top of your document  to be able to use it. (It has to be _above the other LaTeX cells_: it's not reactive 🙈.)

**Comment by fonsp** [comment]
Can you confirm that it also works for you?

**Comment by karlwessel** [comment]
Not right now immediately, sorry. But thanks a lot already for testing this out (what i probably also could have found out myself...i guess)!

**Comment by karlwessel** [comment]
Works nicely! Thanks!

**Comment by i-walker** [comment]
Is there a tutorial or a why to do this ? 
It doesn't render extra extensions in my case with 

![Screenshot 2024-03-27 at 20 15 46](https://github.com/fonsp/Pluto.jl/assets/46971368/330efb52-8807-48c8-b3c4-b1c7c9968cde)
