### ISSUE TITLE
Pluto  Cells Grouping

### ISSUE THREAD

**Issue by MKAbdElrahman** [fonsp/Pluto.jl#1012]
It would be great if we allowed cells grouping. This will allow us to shrink and expand sections of the notebook.  Also,  allows us to split the notebook  into slides and have interactive presentations.

**Comment by fonsp** [comment]
Thanks for the tip! Can you post this to our suggestion box instead? https://github.com/fonsp/Pluto.jl/issues/182

If you would like to discuss the _underlying issue_, and not just the feature request itself, consider opening a Discussion (https://github.com/fonsp/Pluto.jl/discussions), but first look at the existing issues and discussions for similar topics.
