### ISSUE TITLE
Disable "Open" button on main menu when nothing is typed

### ISSUE THREAD

**Issue by digital-carver** [fonsp/Pluto.jl#1013]
Is the Open button below "Open from file:" in the Pluto welcome page supposed to open the OS File manager window to allow us to choose? 

* If so, it doesn't do anything on my system - Firefox 86 on Linux KDE. Clicking the button does nothing, no errors on the console either. 
* If it's not intended to open a browsable file manager window, then the button should probably be shown disabled until there is some text in the "Enter path or URL" textbox. Though, actually opening a file manager window would be much more convenient, so adding that functionality would be the preferred solution in case it isn't already there. 

(Also, this part should probably be a separate issue, but perhaps the "notebook = " kwarg should be mentioned in the `Pluto.run` help doc, as that feels like an option that would also count as common (I found it thanks to coming across [this issue](https://github.com/fonsp/Pluto.jl/issues/936) that mentions it). And despite the text saying "For the full list, see the Pluto.Configuration module.", there isn't an easily accessible list of options in the module, since it's split in multiple places and not very obvious. Perhaps a docstring in that module listing all the options would be helpful. Let me know if this is something worth opening a separate issue for.)

**Comment by fonsp** [comment]
Can you remove the second issue and consider posting it separately?

**Comment by fonsp** [comment]
Thanks for the report, the button is not supposed to work when nothing is typed. Also see #833.

**Comment by HirumalPriyashan** [comment]
@fonsp I think we can close this issue since https://github.com/fonsp/Pluto.jl/pull/2020 is merged.

**Comment by fonsp** [comment]
Thanks!
