### ISSUE TITLE
Bold headers not working in Chrome

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1018]
Chrome:

![image](https://user-images.githubusercontent.com/6933510/112020668-d305dd00-8b30-11eb-8d04-3af2977f2428.png)

Firefox:

![Schermafbeelding 2021-03-22 om 17 05 42](https://user-images.githubusercontent.com/6933510/112020681-d6996400-8b30-11eb-985a-2c2f0dcaa8d6.png)

**Comment by shubhangi013** [comment]
Hey! I'm new to contributing to Pluto, I'd like to work on this issue. Could you tell me the steps by which I can reproduce it?
