### ISSUE TITLE
Firefox can't connect to Pluto after a day

### ISSUE THREAD

**Issue by ThatcherC** [fonsp/Pluto.jl#1025]
I'm having an issue with Pluto in Firefox on Linux, which I think might be connected to #848 and #859. I usually start up Pluto with
```
import Pluto
Pluto.run(require_secret_for_access=false, require_secret_for_open_links=false)
```
This runs well for awhile (at least one day, sometimes a few days) and then at some point I'm seemingly unable to connect to the Pluto server to make a new notebook. Interestingly, though, notebooks that were running already still work fine, except that I see a repeated error in the web console:

![Screenshot from 2021-03-25 14-04-59](https://user-images.githubusercontent.com/2112477/112521685-2ff0d580-8d73-11eb-8761-4eef92791703.png)

I am running:
- Firefox 86
- Ubuntu 20.04
- Julia 1.5.3

I don't see any errors in the Julia shell where I'm running Pluto (except errors from my own code). Here's what I see in the Firefox web console when I start a new notebook from the Pluto instance that had been running fine for a day or two:

![Screenshot from 2021-03-25 13-42-44](https://user-images.githubusercontent.com/2112477/112519557-ddaeb500-8d70-11eb-9728-13c6e580adbc.png)

It's an odd bug to me - Pluto starts up perfectly and works very well for at least a day every time, but then eventually I get back to this state.

Let me know if there are other tests I can run or logs I can share! Thanks!

**Comment by fonsp** [comment]
Thanks! Some follow-up questions:
- Does your computer stay on or does it hibernate/sleep?
- When in the broken state, can you try a Private window and a different browser?
- Could you `]add Pluto#main` to see if the problem also exists on our latest development branch?

**Comment by ThatcherC** [comment]
- Computer sleeps and hibernates. It's a laptop and sleeps every time I close the lid (usual several times per day)
- I've added `Pluto#main` and started a fresh session. I'll report back if/when I encounter the broken state. Stay tuned!

**Comment by ThatcherC** [comment]
Okay, took a while to get the error again but I got it. I'm on Julia 1.6 now, and using `Pluto#main`. I tried to open a new notebook inf Firefox this afternoon (from a Pluto session that's been running for a few days) and the front page wouldn't load (see the first picture below). I got the same thing in a Firefox Private Window, and saw an error being output on the browser console very rapidly (see second picture below):

![Screenshot from 2021-03-29 18-08-01](https://user-images.githubusercontent.com/2112477/112906318-fa712280-90b9-11eb-9aca-d20b39535cd1.png)

![Screenshot from 2021-03-29 18-06-06](https://user-images.githubusercontent.com/2112477/112906308-f7763200-90b9-11eb-81c0-5ef62b9a0f90.png)

Opening the front page in Chrome was successful! I was open to open up my notebook with no problems. I did see the same error in the browser console, but only once: 

![Screenshot from 2021-03-29 18-10-56](https://user-images.githubusercontent.com/2112477/112906485-3efcbe00-90ba-11eb-8f74-e78cd88f7f0c.png)

I hope this is helpful! Let me know if there are other tests I should run as well.

**Comment by fonsp** [comment]
> very rapidly

What do you mean exactly? Twice per second? Definitely more than twice per second?

Follow-up questions:
- Do you see any output in the terminal where you launched Pluto?
- Is your firefox installation up to date?
- Can you disable adblocking/privacy extensions and see if that fixes the problem?
- While it is trying to connect, can you take detailed screenshots of Firefox's network log? Are there any WS (websocket) connections? Are there messages being sent?

FYI the 404 error was "intentional", but I have removed the warning message in a recent commit. It should not be related.

**Comment by ThatcherC** [comment]
"Very rapidly" was at least twice person, probably more like 10 or 20 times per second. I wasn't able to time it.

For the follow up questions:
- I did see this in the Pluto terminal:
  ```
  ┌ Error: (Base.IOError("read: connection reset by peer (ECONNRESET)", -104), Base.StackTraces.StackFrame[wait_readnb(x::Sockets.TCPSocket, nb::Int64) at stream.jl:408, eof at stream.jl:106 [inlined], read_to_buffer(t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, sizehint::Int64) at ConnectionPool.jl:251, readuntil(t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, f::Function, sizehint::Int64) at ConnectionPool.jl:271, readuntil at ConnectionPool.jl:269 [inlined], readheaders at Messages.jl:471 [inlined], startread(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at Streams.jl:155, handle_transaction(f::HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#204#214"{Pluto.ServerSession, Base.RefValue{Function}, HTTP.Handlers.Router{Symbol("##257")}}}}, t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, server::HTTP.Servers.Server{Nothing, Sockets.TCPServer}; final_transaction::Bool) at Servers.jl:343, (::HTTP.Servers.var"#handle_transaction##kw")(::NamedTuple{(:final_transaction,), Tuple{Bool}}, ::typeof(HTTP.Servers.handle_transaction), f::Function, t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, server::HTTP.Servers.Server{Nothing, Sockets.TCPServer}) at Servers.jl:338, handle_connection(f::Function, c::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, server::HTTP.Servers.Server{Nothing, Sockets.TCPServer}, reuse_limit::Int64, readtimeout::Int64) at Servers.jl:299, (::HTTP.Servers.var"#8#9"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#204#214"{Pluto.ServerSession, Base.RefValue{Function}, HTTP.Handlers.Router{Symbol("##257")}}}}, HTTP.Servers.Server{Nothing, Sockets.TCPServer}, Base.RefValue{Int64}, Int64, Int64, Bool, HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})() at task.jl:406])
  └ @ HTTP.Servers ~/.julia/packages/HTTP/IAI92/src/Servers.jl:264
  ```
  There's no timestamp on this error though so I can't be 100% sure it's connected to this failure-to-load error. Might be though
- Firefox is up to date (currently running version 87)
- I have uBlock Origin installed but it is disabled for all Pluto pages
- Here are a couple pictures from the Firefox network log while I am trying to load the Pluto main page. Looks like no WebSocket connections, just the same HTTP request over and over and a repeating set of JavaScript errors. Second picture shows an empty WS connection log:
  
  ![Screenshot from 2021-04-06 11-14-45](https://user-images.githubusercontent.com/2112477/113734708-8e01af00-96c9-11eb-87ce-d7f3c181e7c0.png)

  ![Screenshot from 2021-04-06 11-15-05](https://user-images.githubusercontent.com/2112477/113734731-922dcc80-96c9-11eb-9805-a22a7b221d18.png)

**Comment by pankgeorg** [comment]
Closing due to lack of progress - let's continue in #848 if we have new data
