### ISSUE TITLE
Use name from URL when saving notebook loaded via URL

### ISSUE THREAD

**Issue by david-macmahon** [fonsp/Pluto.jl#1027]
It's cool that one can open notebooks straight off the web by pasting a URL into the "open" field, but then they get saved locally with cute names like "adjective_noun.jl".  It would be great if the local name were instead the "base name" from the URL.  For example, a notebook loaded from `http://my.school.edu/pluto101/pl101_assignment1.jl` would be saved locally as `pl101_assignment1.jl` or maybe `pluto101_pl101_assignment.jl`.

**Comment by zerefwayne** [comment]
@fonsp I would like to take this up! 😄

**Comment by fonsp** [comment]
Great! Let us know if you have questions
