### ISSUE TITLE
Error when loading notebook with unicode

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#103]
When trying to load the following notebook (which was created with Pluto)
```
### A Pluto.jl notebook ###
# v0.8.4

using Markdown

# ╔═╡ 6ab2e91c-92db-11ea-1aa6-f5b8e0b16f4b
ψ₀ = 1

# ╔═╡ 6fb15e76-92db-11ea-1893-2f0d54e55e40
a = ψ₀

# ╔═╡ Cell order:
# ╠═6ab2e91c-92db-11ea-1aa6-f5b8e0b16f4b
# ╠═6fb15e76-92db-11ea-1893-2f0d54e55e40
```

it fails with the following error
```
Failed to load notebook:

StringIndexError("a = Ïˆâ‚€\n\n", 9)

<a href="/">Go back</a>
```

The lower index seems to be the problem, using only `\psi` works.

**Comment by fonsp** [comment]
Thanks so much! UTF-8 compatibility is a big one for me!

**Comment by fonsp** [comment]
It's fixed now, I will release a new update soon.

**Comment by fonsp** [comment]
`0.8.5` will be available soon!

This is now [a testset](https://github.com/fonsp/Pluto.jl/commit/6646ac7dd72d531aae2994a6403bda1baf613b24#diff-82debc19e4c905ab154797b97770e3f7R11) 🐑.
