### ISSUE TITLE
Is plutojl.org supposed to be tilted like this?

### ISSUE THREAD

**Issue by JobLeonard** [fonsp/Pluto.jl#1034]
![image](https://user-images.githubusercontent.com/259840/112663164-cb0fab00-8e58-11eb-84ea-57c5a56474d9.png)

The bottom of the website is unreachable on Firefox for me as a result btw.

Checking the page source mentions a glitch button that's not visible at all in any of my browsers:

![image](https://user-images.githubusercontent.com/259840/112663295-f1cde180-8e58-11eb-9ac5-c064d013b7f2.png)

**Comment by fonsp** [comment]
It is! Thanks for checking

**Comment by anand-bala** [comment]
Hey, @fonsp would it be possible to not have that on by default, as it would be an accessibility issue (for people, like me, with visual interpretation problems)?

**Comment by fonsp** [comment]
Hi @anand-bala,

Thanks for pointing that out! Right now the site was not really meant to be seen by many people, it's just a 'placeholder' page until we write some content to put on the site. But when we do, I'll be sure to make the website less dizziness-inducing!

-fons

**Comment by JobLeonard** [comment]
Just so you know, it's the first hit I get on DuckDuckGo:

![image](https://user-images.githubusercontent.com/259840/113717014-763b2280-96eb-11eb-8aa3-cd4e6ef31baf.png)

(I just checked: it's not on Google, but that is personalized anyway)

**Comment by fonsp** [comment]
Ah now I understand! I will just disable the funky effect for now and think about it more later! Thanks!

**Comment by anand-bala** [comment]
Hey, @fonsp thanks for the reply. I don't think you have to fully remove it if you don't want to, just maybe have some button on the site that toggles the tilt 😄
