### ISSUE TITLE
struct A{T} <: B not analysed correctly

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#104]
Most times changing cells that define a `struct` works fine. For example when changing the field in
```
struct B{T}
	old::T
end
```
to
```
struct B{T}
	new::T
end
```
it works.

However if the struct also has an abstract base:
```
struct B{T} <: Number
	old::T
end
```
then changing the field name to something else like
```
struct B{T} <: Number
	new::T
end
```
raises the following error:
```
cannot assign a value to variable workspace123.B from module workspace124
top-level scope at .julia/packages/Pluto/74Pu3/src/react/WorkspaceManager.jl:146
top-level scope at .julia/packages/Pluto/74Pu3/src/react/WorkspaceManager.jl:156
(::Distributed.var"#101#102"{Distributed.CallMsg{:call}})() at /build/julia/src/julia-1.4.1/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:290
run_work_thunk(::Distributed.var"#101#102"{Distributed.CallMsg{:call}}, ::Bool) at /build/julia/src/julia-1.4.1/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:79
run_work_thunk(::Distributed.RemoteValue, ::Function) at /build/julia/src/julia-1.4.1/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:88
```

**Comment by fonsp** [comment]
Interesting! I'll look into it.

**Comment by karlwessel** [comment]
Maybe the following Warning has the same origin:

When I execute the following valid cell
```
a(a::AbstractArray{T}) where T = 5
```
Pluto gives the following warning:
```
┌ Warning: unknow use of `=`. Assignee is unrecognised.
│   expr = :(a(a::AbstractArray{T}) where T)
└ @ Pluto.ExploreExpression ~/.julia/packages/Pluto/rQZbA/src/react/ExploreExpression.jl:164
```

**Comment by fonsp** [comment]
Thanks! I'll add that to the tests once the reactive types are implemented.

**Comment by fonsp** [comment]
This is now [a testset](https://github.com/fonsp/Pluto.jl/commit/b5cd3d6144c1a3a32a00dfe6fa6ea405ceda8a52#diff-d211991578bcafb62c17fdafd79c957dR40-R52) 🐠

**Comment by karlwessel** [comment]
> Maybe the following Warning has the same origin:
> 
> When I execute the following valid cell
> 
> ```
> a(a::AbstractArray{T}) where T = 5
> ```
> 
> Pluto gives the following warning:
> 
> ```
> ┌ Warning: unknow use of `=`. Assignee is unrecognised.
> │   expr = :(a(a::AbstractArray{T}) where T)
> └ @ Pluto.ExploreExpression ~/.julia/packages/Pluto/rQZbA/src/react/ExploreExpression.jl:164
> ```

I still get this warning. Is that intended?

**Comment by fonsp** [comment]
ooh

**Comment by karlwessel** [comment]
It is a function definition (although maybe not the most sensible one).

**Comment by fonsp** [comment]
Right! I will look into it

**Comment by fonsp** [comment]
Here's the added [testset](https://github.com/fonsp/Pluto.jl/commit/2c403451eaefa0a65337ed47d0cf035838b29793#diff-d211991578bcafb62c17fdafd79c957dR195-R197) 🦘
