### ISSUE TITLE
div img support

### ISSUE THREAD

**Issue by montyvesselinov** [fonsp/Pluto.jl#1041]
Do you plan to support div?! It works in Jupyter. It is convenient to auto-scale and align multiple images. 

```
md"""
<div style="text-align: left; padding-bottom: 30px;">
    <img src="../../logos/geothermalcloud-small.png" width=25%  max-width=125px;/>
</div>
"""
```

**Comment by fonsp** [comment]
Markdown is a part of Julia itself, not of Pluto. Maybe https://discourse.julialang.org/t/including-raw-html-in-julia-markdown/26165 is useful
