### ISSUE TITLE
Anyway to deploy on binder

### ISSUE THREAD

**Issue by newptcai** [fonsp/Pluto.jl#105]
Some times I want to deploy something interactive so students can play with themselves. Is it possible to run Pluto on binder?

**Comment by fonsp** [comment]
Hi!
Unfortunately not, I think that binder is specific to Jupyter, the workings of which are unrelated to Pluto. But I think that this would be very cool to have!

Are you talking about **interactivity using `@bind`**, or **interactivity as in _reactivity_** - direct results from code changes?

For both cases, I have some ideas. The former would be easiest to do, as it does not require a running Julia process to connect to. My solution to this would be #16 - this is not hard to implement, I just need to find the time :)

About the latter: have a look at what I wrote in the [FAQ](https://github.com/fonsp/Pluto.jl/wiki#-ui) (just above _⚡ Writing and running code_).

**Comment by fonsp** [comment]
It's happening!

**Comment by fonsp** [comment]
https://pluto-on-binder.glitch.me/
