### ISSUE TITLE
Installation instructions are scary

### ISSUE THREAD

**Issue by antoine-levitt** [fonsp/Pluto.jl#1051]
On julia 1.6 with a couple of packages already installed, the time for installing and running Pluto was basically negligible. Saying "Using the package manager for the first time can take up to 15 minutes - hang in there!" on the homepage is unnecessarily scary.

**Comment by fonsp** [comment]
Right, it's mostly there for Windows users (https://discourse.julialang.org/t/why-is-the-update-of-the-registries-so-slow/28659/18). And note that the warning says:

> Using the package manager for the first time

but your comments says:

> with a couple of packages already installed

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/301c48c51ef6b23e345b6bd7883e4ea74f0909b4

**Comment by antoine-levitt** [comment]
Julia 1.6 on linux, from a clean .julia: add Pluto = 13s, using Pluto = .5s. I would qualify with "on windows" then.
