### ISSUE TITLE
[FR] Add kwarg to Pluto.run() for choosing browser

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#1057]
Referencing to the [discussion at discource](https://discourse.julialang.org/t/chose-what-browser-to-lanuch-pluto-in/58488/3) that spawned this issue.

I use Firefox as my default browser, but it seems like it does not handle the markdown or HTML well - I am having most of the lines in my notebook spanning two lines instead of 1, which really clutters things (see [my issue](https://github.com/fonsp/PlutoUI.jl/issues/89) about it). So I want to keep my default browser, but have Pluto notebooks launch in Chrome. Would it be possible to add a kwarg, something like `path_to_browser`, which would allow me to chose the browser to launch in?

**Comment by fonsp** [comment]
I am declining this feature request because we need to prioritize. You can write a Pluto launcher script yourself or use a fork of Pluto

**Comment by holomorphism** [comment]
@KronosTheLate 
I am using Ubuntu (Xubuntu) Linux and have set the following command in the GUI launcher button to start Pluto.

```
zsh -c "julia -e 'import Pluto; Pluto.run(;require_secret_for_access=false)'"
```
![image](https://user-images.githubusercontent.com/3076585/113496215-59a7ba80-9532-11eb-912d-e3e39a512bc5.png)

If you are also using Linux, you can change this to the following and it should work as you wish.

```
zsh -c "julia -e 'import Pluto; Pluto.run(;require_secret_for_access=false,launch_browser=false)' & { sleep 3; google-chrome-stable http://localhost:1234; }"
```

The following points should be modified according to your environment.

- If you are not using zsh, change it to another shell (e.g, bash).
- The path to the julia command needs to be referable from the shell.
  For example, I have the following line in ~/.zshenv:
  ```
  export PATH=$HOME/julia-1.6.0/bin:$PATH
  ```
- If chrome starts before Pluto starts, increase the number of seconds to sleep.
