### ISSUE TITLE
installing pluto via pkg fails    SOLVED

### ISSUE THREAD

**Issue by philippe-astro** [fonsp/Pluto.jl#1068]
SOLVED : case sensitive....
pluto is not Pluto, sorry for the inconvenience...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> add pluto
   Updating registry at `~/.julia/registries/General`
--2021-04-07 12:29:59--  https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/899d73fef730ad330cdaefcd586b1dbc683a0c8b
Résolution de pkg.julialang.org (pkg.julialang.org)… 151.101.122.217, 2a04:4e42:1d::729
Connexion à pkg.julialang.org (pkg.julialang.org)|151.101.122.217|:443… connecté.
requête HTTP transmise, en attente de la réponse… 301 EU internal redirect trigger
Emplacement : https://eu-central.pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/899d73fef730ad330cdaefcd586b1dbc683a0c8b [suivant]
--2021-04-07 12:29:59--  https://eu-central.pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/899d73fef730ad330cdaefcd586b1dbc683a0c8b
Résolution de eu-central.pkg.julialang.org (eu-central.pkg.julialang.org)… 18.157.163.169
Connexion à eu-central.pkg.julialang.org (eu-central.pkg.julialang.org)|18.157.163.169|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 2975440 (2,8M) [application/octet-stream]
Enregistre : «/tmp/jl_sxTmH0-download.gz»

/tmp/jl_sxTmH0-download.gz              100%[===============================================================================>]   2,84M   359KB/s    ds 7,0s    

2021-04-07 12:30:06 (418 KB/s) - «/tmp/jl_sxTmH0-download.gz» enregistré [2975440/2975440]

ERROR: The following package names could not be resolved:
 * pluto (not found in project, manifest or registry)

(@v1.5) pkg> add pluto
ERROR: The following package names could not be resolved:
 * pluto (not found in project, manifest or registry)

**Comment by fonsp** [comment]
Thanks!
