### ISSUE TITLE
Create workspace module as toplevel?

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#1072]
To fully mimic the behaviour of `Main` maybe one can create workspace module using

```julia
m = Base.eval(Base.__toplevel__, :(module MyWorkspace end))
```

so that `MyWorkspace` will be a toplevel module like `Main` and thus you can get rid of things like `Main.Workspace` etc.?

---

also this would fix potential name conflicts when someone's package export the same workspace module name as Pluto creates (tho it is unlikely to happen I think)

**Comment by fonsp** [comment]
Interesting! Can you be more specific about what problem this would solve?

**Comment by fonsp** [comment]
@dralletje Can you take a look?

**Comment by dralletje** [comment]
I was really excited because this looks pretty cool (and I love magic modules), but it seems that this module has [quite some magic](https://github.com/JuliaLang/julia/blob/master/src/toplevel.c) going on so I'm hesitant to actually do this
