### ISSUE TITLE
Splitting out Workspace into its own package

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#1073]
the functionality of the workspace manager inside Pluto can be useful in other places, e.g accelerating CLIs, scripts, and GUIs. I'm wondering if @fonsp has interests to split out the workspace manager and evaluation into a package so that one can use it in other places, and when all the applications use the same workspace protocol, they can share the process and compilation results, which would make Pluto starts faster when someone already spawns a workspace daemon process locally (for other packages) and same for whoever uses the same protocol too.

This would be similar to the [DaemonMode.jl](https://github.com/dmolina/DaemonMode.jl) but provides an elegant namespace. The use case on my side is to run CLI scripts created by [Comonicon](https://github.com/Roger-luo/Comonicon.jl) in such a daemon process within a `Workspace` module that works similarly to Pluto notebooks to reduce start-up latency.

**Comment by fonsp** [comment]
Do you mean the concept of using multiple dynamically generated modules (`Main.workspace123.x`) to keep scope isolated, or the way we use multiple processes? Can you edit your issue to clarify?

**Comment by Roger-luo** [comment]
I mean the way how you evaluate the cells, which is related to the following

1. using multiple dynamically generated modules to keep scope isolated
2. communicate with another process to evaluate certain Julia expression

2 is actually close to the implementation of DaemonMode.jl, but DaemonMode doesn't have 1.

**Comment by fonsp** [comment]
I see! 

2. is just the Distributed stdlib, we use the secret function `remotecall_eval`.
```julia
julia> import Distributed

julia> p = Distributed.addprocs(1)
1-element Vector{Int64}:
 2

julia> eval_remote(ex) = Distributed.remotecall_eval(Main, p[1], ex);

julia> eval_remote(:(1+1))
2
```

The basic idea of 1. is also easy to implement:
```julia

julia> clear_scope() = e(:(m = Module(); nothing))

julia> clear_scope()

julia> eval_remote_scoped(ex) = e(:(Core.eval(m, $(QuoteNode(ex)))));

julia> eval_remote_scoped(quote
           x = 123
           y = x*2
       end)
246

julia> eval_remote_scoped(quote
           x + y
       end)
369

julia> clear_scope()

julia> eval_remote_scoped(quote
           x + y
       end)
ERROR: On worker 2:
UndefVarError: x not defined
Stacktrace:
```

**Comment by fonsp** [comment]
@Roger-luo sorry for being a bit dismissive of your request, I think I understand your request better now, see my updated previous comment

**Comment by Roger-luo** [comment]
Sorry for this late reply @fonsp I'm back to this question now after trying the code you referred above a bit, I find I will also need the implementation of auth and the server code in WebServer.jl since I wish to have a server running in the backend of my machine to execute a given Julia script file. I'm trying to experiement some ideas (and will probably need to do some copy-pasting first to see which part I need exactly from Pluto) here: https://github.com/comonicon/Workspace.jl

**Comment by fonsp** [comment]
@Roger-luo with or without reactivity?

**Comment by Roger-luo** [comment]
I mainly want to use this functionality to make script execution faster and potentially also provide a way to accelerate native GUIs without building a system image (I'm trying to generate GUI from Comonicon), so ideally it should have some reactivity, but I think without it seems simpler.

**Comment by Roger-luo** [comment]
I roughly get a REST server version of the workspace working that supports:

1. client send a request to create a new workspace
2. client send the Julia expression (as String) want to execute in a workspace with a simple JSON schema
3. client delete or check the workspace

now comes to the authentication, I realize currently Pluto uses a random string for authentication, I'm wondering if using OpenID Connect would be a good idea? There seems to be https://github.com/tanmaykm/OpenIDConnect.jl already, this would allow people to login to a remote notebook server via their GitHub account/Google account/whatever they like. I think JuliaHub currently uses this, but it might be too heavy for those who only uses the notebook locally (or maybe for this case, authentication can be just turned off since it's on the same machine anyway?)

**Comment by fonsp** [comment]
About authentication (though it seems unrelated?): Our stand is that we are not auth developers so we won't implement it ourselves. You can run Pluto through a proxy with custom auth if you need it. About the secret on zoom: they would also need access to your computer to access `127.0.0.1`. 

It sounds like you want the entire Pluto package (with some API that is currently not public). I won't have time to work on stabilizing this API myself, but if you have specific requests then we can see. Let's wait for #1052 first though.
