### ISSUE TITLE
Quit/Exit button

### ISSUE THREAD

**Issue by crstnbr** [fonsp/Pluto.jl#1075]
Would love to see a quit/exit button/link that stops the Pluto server and perhaps (if Pluto has been started with a keyword argument or similar) even `exit()`s the Julia session. (Note that Jupyter has this as well.)

Reason: I want to be able to quit the Pluto server when run as a background process.

Explanation: I typically like to have a server like Jupyter or Pluto running in the background so that I can access it through the browser any time (with out having to go through the "open a terminal -> type `julia -e 'using Pluto; Pluto.run()'`" process). I also want to get rid of the unnecessary terminal, which is hosting the server, so I actually run something like `julia -e 'using Pluto; Pluto.run()' &` and close it (CTRL/CMD + W). This works fine, but to quit/restart the server I have to manually find the Pluto process and kill it. Would be much nicer to be able to klick on a quit/stop/exit button on the Pluto front page.

What do you think?

**Comment by crstnbr** [comment]
If time permits and you guys would consider such a feature, I would also be willing to give this a try in a PR.

**Comment by fonsp** [comment]
Can you post this [feature request](https://github.com/fonsp/Pluto.jl/issues/182) to our built-in suggestion box instead?

**Comment by crstnbr** [comment]
You mean I should copy paste the paragraphs above to this tiny feedback input box? (Will do if you say so, just want to be sure.)

**Comment by fonsp** [comment]
Yes please ☺️

I am sorry for not discussing feature requests here on github, I wrote a bit about why here: https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439

**Comment by crstnbr** [comment]
Alright, done.
