### ISSUE TITLE
plotly.js support

### ISSUE THREAD

**Issue by newptcai** [fonsp/Pluto.jl#108]
Please the following attached image.

![image](https://user-images.githubusercontent.com/982197/81751039-ef67d080-94ae-11ea-8c2d-aa4943fdf9cc.png)

**Comment by fonsp** [comment]
Currently you have to run that cell twice for the plot to show up. I'm working on a fix.

**Comment by newptcai** [comment]
Does seem to work how many times I run the cell.

```
### A Pluto.jl notebook ###
# v0.8.6

using Markdown

# ╔═╡ dcd2db40-94ae-11ea-3433-b9eb99f230e4
using Plots

# ╔═╡ e5c1edb8-94ae-11ea-1cba-7f945804c37f
plotlyjs()

# ╔═╡ 051de40a-94af-11ea-155d-033c519fb430
x = 1:10; y = rand(10); # These are the plotting data

# ╔═╡ 0b6fa974-94af-11ea-20ee-3922a821fd27
plot(x, y)

# ╔═╡ Cell order:
# ╠═dcd2db40-94ae-11ea-3433-b9eb99f230e4
# ╠═e5c1edb8-94ae-11ea-1cba-7f945804c37f
# ╠═051de40a-94af-11ea-155d-033c519fb430
# ╠═0b6fa974-94af-11ea-20ee-3922a821fd27
```

**Comment by fonsp** [comment]
Thanks! I am working on supporting PlotlyJS. For now you have to replace `plotlyjs()` with `plotly()`.

**Comment by fonsp** [comment]
The dynamic loading issue is fixed, but plotly is still broken 😢

**Comment by fonsp** [comment]
Fixed! 

![image](https://user-images.githubusercontent.com/6933510/87574193-53d12700-c6ce-11ea-976e-d2aca1b60247.png)

**Comment by dpsanders** [comment]
`plotly()` seems to work, but `plotlyjs()` still does not.
