### ISSUE TITLE
I don't understand how root_url is supposed to work

### ISSUE THREAD

**Issue by lahvak** [fonsp/Pluto.jl#1082]
I tried to launch Pluto with
```
Pluto.run(launch_browser=false, require_secret_for_access=false, root_url="blah/")
```
Pluto responds with `Go to blah/ in your browser to start writing ~ have fun!`

If I try to access `http://localhost:1234/blah/`, I get a 404 error, and the server (I do make a connection to the server) says "Not found!".

What am I doing wrong?

**Comment by fonsp** [comment]
What are you trying to do?
