### ISSUE TITLE
TypeError: Failed to Register a ServiceWorker in HTML Export

### ISSUE THREAD

**Issue by jkort** [fonsp/Pluto.jl#1087]
Hello,

If I open a static HTML export file in Chrome, I get this error:

TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('null') is not supported.
    at Stunning program.jl.html:23

which I assume is this:
 navigator.serviceWorker?.register(document.head.querySelector("link[rel='pluto-sw']").getAttribute("href"), { scope: "./" }).catch(console.warn)

Julia v1.5.2; Pluto v0.14.1
Chrome Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by fonsp** [comment]
This is fine to ignore, we can't register a serviceworker on `file://` URLs. Since the SW is only an optimization, it is not a problem.
