### ISSUE TITLE
Plot height of plotly graph in html export is incorrect (Pluto 0.14.1 & chrome)

### ISSUE THREAD

**Issue by holomorphism** [fonsp/Pluto.jl#1088]
With the change from Pluto 0.14 to 0.14.1, when I export a notebook containing plotly (Plots.jl) graphs to html and open it locally in chrome, the height is no longer displayed correctly. (I am using google chrome 89 on Ubuntu 18.04. In firefox it is displayed correctly.)

**Pluto 0.14:**
![image](https://user-images.githubusercontent.com/3076585/114553545-b3318700-9ca0-11eb-8c44-52bedd040337.png)
[plotly_minimal.jl.0.14.0.html.txt](https://github.com/fonsp/Pluto.jl/files/6303773/plotly_minimal.jl.0.14.0.html.txt)

**Pluto 0.14.1:**
![image](https://user-images.githubusercontent.com/3076585/114553707-e411bc00-9ca0-11eb-94f7-b5dc9e2b0eec.png)
[plotly_minimal.jl.0.14.1.html.txt](https://github.com/fonsp/Pluto.jl/files/6303771/plotly_minimal.jl.0.14.1.html.txt)

The html by Pluto 0.14.1 had the following error in the chrome console.

![image](https://user-images.githubusercontent.com/3076585/114556821-0c4eea00-9ca4-11eb-879f-b9677d02f9be.png)

I think this is due to a security restriction of chrome, and if you open the html uploaded to the web, the error will not occur. The above behavior of Pluto 0.14.1 may be normal, but I report it just in case. If this is not considered a problem, please close it.

**Comment by holomorphism** [comment]
I think this issue is the same as #1087.

**Comment by holomorphism** [comment]
(I posted a comment that I think this issue is similar to #1087, but I'm still not sure, so I deleted that post)

**Comment by fonsp** [comment]
I think this might be "impossible to fix", @pankgeorg can you verify? Is it a Chrome bug?

This is not a major issue, iframe-embedded HTML output is not super common, and it works when served over HTTPS, which is our main focus.

**Comment by pankgeorg** [comment]
It also works over HTTP, if, for example, you `npx serve -s`.
Indeed, the problem doesn't seem 'fixable' as the code is now. Maybe we can detect running in through local filesystem and skip `iframe`s - or you can disable security: https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by holomorphism** [comment]
Thanks for the reply and the useful info!

**Comment by fonsp** [comment]
Some simple solutions:
1. Put the html file in a github repository and use github pages to view the html
2. Put the html file in a github repository or on gist.github.com and use https://htmlview.glitch.me/ to view it

**Comment by holomorphism** [comment]
I noticed that this problem is solved in Pluto v0.14.8 and Plots v1.16.8.
Maybe it's because of this PR?
https://github.com/JuliaPlots/Plots.jl/pull/3559
Thanks a lot!

**Comment by fonsp** [comment]
The issue only occurs with the plotly backend, the PR is about the GR backend.

**Comment by fonsp** [comment]
That's right! yayo
