### ISSUE TITLE
Please replace prompt: "A new version of Pluto.jl is available!"

### ISSUE THREAD

**Issue by stephans3** [fonsp/Pluto.jl#1096]
**Please replace** the prompt "A new version of Pluto.jl is available!..."

It is **very very annoying** to read it everytime when I open Pluto. And everytime I have to click on "ok". 
I am not able to tell the system: "Do not show again" or something like this.

Everytime I update Pluto, after a couple of days and I read the message again :( 

David Sanders also mentioned it #887

**Comment by pankgeorg** [comment]
Hello!! The message will go away if you update! Is there any reason _not_ to update Pluto?

**Comment by fonsp** [comment]
We are aware of this problem and thinking about solutions, but I am closing this issue because I feel a lot of negative sentiment.
