### ISSUE TITLE
Feature request: Reader mode

### ISSUE THREAD

**Issue by frankhuettner** [fonsp/Pluto.jl#1104]
It would be fantastic to have a read only mode. Basically it would convert the notebook into a live document. 

A quick kill could be a button that disables/hides (what would be the code for having this as a checkbox button?)
- the Pluto top banner
- the bottom banner and the live docs
- all code fields

I love to show people stuff in Pluto, and let them play around with the slider etc. But as soon as there is source code popping up (e. g., a curious student might click on the eye and is scared that this just broke something), some people get very uncomfortable.

**Comment by fonsp** [comment]
Thanks! We happen to have a CSS script that does most of what you want (used to make  look like a website, not an IDE). To also hide cell inputs, you need to add one CSS rule:

```julia
@bind hide_ui Checkbox()
````

```julia
html"""
<link rel="stylesheet" href="./hide-ui.css">
<style>
pluto-input {
	display: none;
}
</style>
"""
```

**Comment by fonsp** [comment]
After https://github.com/fonsp/Pluto.jl/issues/1105 is fixed, you will be able to get this functionality by adding `&disable_ui=true` to the URL. I think also hiding all cell inputs is a separate issue, not necessarily applicable to everyone (code is also a form of documentation), so I will leave that for now.
