### ISSUE TITLE
undetected circular dependency

### ISSUE THREAD

**Issue by gpucce** [fonsp/Pluto.jl#1107]
Hi, after reading #182 I believe this should be posted here, hoping that is the case here it goes: 

Writing the two following lines in two different cells in Pluto

```
select = @bind selection NumberField(1:10, default=1)
md"$select $selection"
```

the second cell will rerun continuously as if it was pointing to itself (I believe this is what is happening) instead of raising a circular dependency error.

Already that I am here, you're doing a great job with Pluto!!

**Comment by fonsp** [comment]
Thanks! Linked to #515

**Comment by fonsp** [comment]
Fixed!

https://user-images.githubusercontent.com/6933510/155308517-a62ca5a5-c849-4353-b282-bb1b3232c00c.mov
