### ISSUE TITLE
The `fillalpha` attribute will make the browser crash  

### ISSUE THREAD

**Issue by foldfelis** [fonsp/Pluto.jl#1111]
I was trying to plot a surface via Plots.jl (with gr back end). And I found that the `fillalpha` attribute will crash the browser.

Environment:
```
julia v1.6.0
[91a5bcdd] Plots v1.12.0
[c3e4b0f8] Pluto v0.14.2
```

Here is the minimal reproduce example

```julia
### A Pluto.jl notebook ###
# v0.14.2

using Markdown
using InteractiveUtils

# ╔═╡ 7942f4b0-a1d8-11eb-3870-e962d5b4f121
begin
	using Plots
	gr()
end

# ╔═╡ 8ffbdb95-1fd9-4c37-9902-0af58a35e2d5
begin
	x_range = -10:0.01:10
	surface(x_range, x_range, (x, y)->sin(x)+cos(y), fillalpha=0.5, color=:coolwarm)
end

# ╔═╡ Cell order:
# ╠═7942f4b0-a1d8-11eb-3870-e962d5b4f121
# ╠═8ffbdb95-1fd9-4c37-9902-0af58a35e2d5
```

![2021-04-20 21-05-13 的螢幕擷圖](https://user-images.githubusercontent.com/59465497/115401865-6f4cfd80-a21d-11eb-9077-1183c1c8bc9c.png)

But if the size of `x_range` is small enough, say `-10:0.1:10`, Pluto will work like a charm

![2021-04-20 21-16-42 的螢幕擷圖](https://user-images.githubusercontent.com/59465497/115402352-eda99f80-a21d-11eb-9e0d-697319fd3773.png)

BTW, using Plots.jl in REPL works just fine:

![2021-04-20 21-27-34 的螢幕擷圖](https://user-images.githubusercontent.com/59465497/115403848-5e04f080-a21f-11eb-89a4-25eb5e6db3d4.png)

**Comment by pankgeorg** [comment]
Can you try to use PNG output?
It's usually a keyword argument like:  `fmt = :png` in the `surface` call!

**Comment by foldfelis** [comment]
Hi @pankgeorg , I have tried `gr(fmt=:png)` or `surface(..., fmt=:png)`. both way didn't solve the problem.

**Comment by pankgeorg** [comment]
Your notebook exports to 865.050KB, so I guess that's why Chrome gives up.
VSCode declines to open it too! ![image](https://user-images.githubusercontent.com/8681967/115434076-f0ea5e80-a210-11eb-8808-c5856b048993.png)

![image](https://user-images.githubusercontent.com/8681967/115434110-fb0c5d00-a210-11eb-8e8b-6a32f3742868.png)

**Comment by foldfelis** [comment]
So I guess this is a render problem.

**Comment by pankgeorg** [comment]
It seems that the surface functionality ignores the `fmt` keyword.
As a workaround you can use the amazing https://github.com/tkf/DisplayAs.jl for force the Plot to be rendered as PNG:


```
### A Pluto.jl notebook ###
# v0.14.2

using Markdown
using InteractiveUtils

# ╔═╡ 7942f4b0-a1d8-11eb-3870-e962d5b4f121
begin
	using Plots
        import Pkg; Pkg.add("DisplayAs")
        import DisplayAs
	gr()
end

# ╔═╡ 8ffbdb95-1fd9-4c37-9902-0af58a35e2d5
begin
	x_range = -10:0.01:10
	surface(x_range, x_range, (x, y)->sin(x)+cos(y), fillalpha=0.5, color=:coolwarm) |> DisplayAs.PNG
end

# ╔═╡ Cell order:
# ╠═7942f4b0-a1d8-11eb-3870-e962d5b4f121
# ╠═8ffbdb95-1fd9-4c37-9902-0af58a35e2d5
```

**Comment by pankgeorg** [comment]
possibly related: https://github.com/fonsp/Pluto.jl/pull/1090

**Comment by foldfelis** [comment]
> @pankgeorg  [DisplayAs advice](https://github.com/fonsp/Pluto.jl/issues/1111#issuecomment-823454169)

Thanks for the awesome advice!!

**Comment by fonsp** [comment]
@pankgeorg Can you verify that plot size was the problem by comparing the SVG size before and after enabling `fillalpha`?

**Comment by pankgeorg** [comment]
> ```julia
> length(repr(MIME"image/svg+xml"(), my_plot))
> ```

Yes, it's a thousand times bigger:
![image](https://user-images.githubusercontent.com/8681967/115695008-163eb000-a36a-11eb-8010-bc9695e46f8e.png)

**Comment by fonsp** [comment]
@pankgeorg Can you report that last screenshot as a bug to GR and we'll close it here?
