### ISSUE TITLE
Win10 (opera) exiting Pluto gets error in console (almost every time)

### ISSUE THREAD

**Issue by cedricchi** [fonsp/Pluto.jl#1119]
Hi team, I am using Opera explorer under Win10, when I exit Pluto no matter if I close my browser or not I almost always get error in PowerShell like the following:
Have a nice day! 🎈
      From worker 2:    fatal: error thrown and no exception handler available.
      From worker 2:    InterruptException()
      From worker 2:    jl_mutex_unlock at /cygdrive/c/buildbot/worker/package_win64/build/src\locks.h:134 [inlined]
      From worker 2:    jl_task_get_next at /cygdrive/c/buildbot/worker/package_win64/build/src\partr.c:475
      From worker 2:    poptask at .\task.jl:755
      From worker 2:    wait at .\task.jl:763 [inlined]
      From worker 2:    task_done_hook at .\task.jl:489
      From worker 2:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
      From worker 2:    jl_finish_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:208
      From worker 2:    start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:850

**Comment by fonsp** [comment]
We can't catch 'em all
