### ISSUE TITLE
Book Mode

### ISSUE THREAD

**Issue by caseykneale** [fonsp/Pluto.jl#1122]
This is absolutely not a bug/etc... But I think it's a good idea.

I would love to see a book mode/view. Where you have "pages" and can display two pages at once, as if you were reading a book. I think this could open doorways to really cool interactive learning "texts".

You know how when you read a math book you have to pull out a scrap of paper to test something out, or handle the "it easily follows that..." and you need to fill in the details to understand it? Users could pop in new cells and do the same to make sure they understand stuff, without opening an IDE, needing a second monitor, etc.

Anyway its one of my classic "stupid suggestions"

**Comment by fonsp** [comment]
Thanks! We are definitely working on these types of features, but can you post this to our suggestion box instead? https://github.com/fonsp/Pluto.jl/issues/182
