### ISSUE TITLE
Add warning about print statements not showing anything

### ISSUE THREAD

**Issue by logankilpatrick** [fonsp/Pluto.jl#1123]
Fons, don't be mad at me, but I finally got around to playing with Pluto more this morning 😄. I made a notebook and added some cells but print did not work. It took me 5 minutes of playing around and starting to write this issue for me to remember that someone mentioned it does not work in Pluto. Would it be possible to add an error/warning for this?

**Comment by fonsp** [comment]
Linked is #420 and #279

**Comment by fonsp** [comment]
Print statements work now! See #1957
