### ISSUE TITLE
Random scrolling

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#113]
With version 0.8.9 I get some "random" automatic scrolling when I click into cells.

Here is a way to reproduce the behaviour:
1. Open the interactivity example notebook
2. Click into the Programmcode for the "How many pets do you have" cell. As if you would like to edit it.
3. Scroll down to the bottom of the notebook and click anywhere in a cell. At my PC the notebook then jumps focus back to somewhere around the place where i clicked in step 2.

**Comment by fonsp** [comment]
Thanks for the steps to reproduce! It will be fixed in the next version :)

**Comment by karlwessel** [comment]
This issue seems to have come back from the dead (see my [comment](https://github.com/fonsp/Pluto.jl/issues/205#issuecomment-655522976) in issue #205 ).

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/b178c5067c786a7d3a0209c54ce8333461e0c7c5

**Comment by fonsp** [comment]
And it's a [testset](https://github.com/fonsp/Pluto.jl/commit/b178c5067c786a7d3a0209c54ce8333461e0c7c5#diff-a0be523121bffbc7fd3aa73cbf58888dR55-R62) 💫

**Comment by karlwessel** [comment]
Can you push a release with this fix? I have projects where I don't want to add Plutos master as a dependency.
