### ISSUE TITLE
no recalc when modifying custom method  Plots.plot!  

### ISSUE THREAD

**Issue by maajdl** [fonsp/Pluto.jl#1136]
Hello

I created a custom Plots.plot! method like this:

```
function Plots.plot!(rea::Mixture, f::Function; kw...)
    ....
end
```

When making changes to this function, the changes do not trigger a recalculation of the plots using this function. 
Only a forced recalculation of the involved cells works.

This problem doesn't occur if I proceed in the way without extending Plot.plot! : 

```
function myPlot!(rea::Mixture, f::Function; kw...)
    ....
end
```
Changing this function triggers a recalculation every time.

Thanks

Michel

**Comment by fonsp** [comment]
Thanks! See https://github.com/fonsp/Pluto.jl/issues/1019
