### ISSUE TITLE
Inconsistent scoping rule compared to Julia REPL

### ISSUE THREAD

**Issue by tk3369** [fonsp/Pluto.jl#1137]
This code runs fine from Julia REPL but fails in Pluto:

```julia
begin
    foo() = 1
    s = 0
    for i in 1:10
        s += foo()
    end
    s
end
```

In Pluto, you get this error:
```
UndefVarError: s not defined

top-level scope@Local: 5
```

My test environment:
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, westmere)
```

**Comment by Pangoraw** [comment]
See #1031. As a workaround, if you define `foo` outside the cell, it should work.

**Comment by pdeffebach** [comment]
As mentioned on slack, this would break the guarantee that Pluto.jl is "just a script" that can be run the same in interactive or from the terminal. 

I don't use Pluto so take what I say with a grain of salt, just keeping consistency across forums.

**Comment by jlperla** [comment]
> As mentioned on slack, this would break the guarantee that Pluto.jl is "just a script" that can be run the same in interactive or from the terminal.

Sure. But then the answer seems to be that scripts should also be made consistent (albeit with a default warning). This same issue happens in vscode `.jl` files. You use them through the typical interactive features in vscode like shift enter and they work as people expect, but if you push the button to run as a file it is inconsistent.

**Comment by tk3369** [comment]
Ok, just for clarity/documentation reasons, running the above code as a julia script yields the following warning and error:
```
$ julia /tmp/wat.jl 
┌ Warning: Assignment to `s` in soft scope is ambiguous because a global variable by the same name exists: `s` will be treated as a new local. Disambiguate by using `local s` to suppress this warning or `global s` to assign to the existing global variable.
└ @ /tmp/wat.jl:5
ERROR: LoadError: UndefVarError: s not defined
```

IMHO, Pluto frontend should behave as if it's an interactive tool... Why? I believe that's how most people use Pluto today. It's less likely that someone would create the notebook and turn around and try to run it as a script.
