### ISSUE TITLE
Live docs does not parse some operators correctly

### ISSUE THREAD

**Issue by melonedo** [fonsp/Pluto.jl#1138]
When I type the code in a Pluto cell:
```julia
abs(-1)|>add|>sum
```
put the cursor around `abs`, `-` or '|>', live doc shows corresponding info; but if cursor is put after `add` , live doc attemps to get help for `|>add`; whats worse, when the cursor is put in `sum`, live doc attemps to get help for `|>add|>sum`.
This is also true for `->`.

**Comment by melonedo** [comment]
After I traced several breakpoints, it seems the culprit is that the `module_expand_selection` function. It does not recognize "operator" as a stop token and keep pushing tokens before the current token,  until it finds a number or "null"-type token (the type of token comes from codemirror, I am not sure what that means)
https://github.com/fonsp/Pluto.jl/blob/aef57ba471f6250a434ca389c1895952dfb84fd8/frontend/components/CellInput.js#L786-L802
So a string of operators and tokens will be concatenated all together and fed to `Doc.doc`.

**Comment by dralletje** [comment]
Fixed by https://github.com/fonsp/Pluto.jl/commit/eada0647077f3ebf93d1e76a8515ed0c33eee2aa
