### ISSUE TITLE
Automatic deletion of empty cells

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#114]
It seems like with Version 0.8.9 you implemented that empty cells are deleted automatically when they lose focus. 

This is nice for keeping a clean notebook. 

However I often create a new cell and then want to copy paste some content from another cell into it. As soon as I mark the text to copy from another cell my new empty cell is deleted before I can paste the new code into it.

Of course I can prevent that by remembering to copy the text before I create the new cell, where I want to paste it but maybe a better solution would be:

Instead of deleting empty cells when they lose focus, you could delete them when the user actively edits another cell.

**Comment by fonsp** [comment]
Interesting idea! I'll add it to 0.8.10 and we'll see how it feels. 

I suppose that it would also have to correct for the change in page height when the cell gets deleted.

**Comment by karlwessel** [comment]
Ok, now I am confused. Is the currently implemented automatic deletion of empty cells an intentionally implemnted feature or is it a bug which we now turn into a feature?

**Comment by fonsp** [comment]
It was intentional, but I am not super happy with how it turned out

**Comment by karlwessel** [comment]
Ok, i was a bit unsure :)

**Comment by fonsp** [comment]
I disabled it for now, but let's revisit this in the future!
