### ISSUE TITLE
Feature request: copy-paste code from REPL

### ISSUE THREAD

**Issue by schneiderfelipe** [fonsp/Pluto.jl#1140]
It would be super cool to paste code such as

```julia
julia> using Plots

julia> plot(sqrt, 0, 1)
```

directly into a Pluto notebook 😄 

Cells could be detected and split by looking for `julia> `.

It might be related to #964.

**Comment by fonsp** [comment]
Nice, let's do that!

As it happens I already wrote this code for another project, see the `split_to_cells` function in https://julia-docs-pluto.netlify.app/generate.html
