### ISSUE TITLE
Cell output richest formatter difficulty

### ISSUE THREAD

**Issue by maajdl** [fonsp/Pluto.jl#1148]
Hello,

I implemented these methods for my `ThermoData = Array{Substance,1}` :

```
Base.show(io::IO, td::ThermoData)
Base.show(td::ThermoData)
Base.show(io::IO, ::MIME"text/plain", td::ThermoData)
Base.summary(td::ThermoData)
```

None of these methods are used to display an instance **td** of ThermoData (written as such in a Pluto cell) .
Instead, what I get diplayed is a list of summary(su::Subtance) .
Probably, Pluto bypasses my code with a "richer formatter"?

Of course, if I the Pluto cell contains  **summary(td)** ,  then I get what I wanted.

How can I get back in control of what get displayed for **td** ?

Besides that, I would like to avoid developping my package with specific code for Pluto of for Jupyter.

Any suggestion for how to proceed when writing my packeg and controlling how thing get shown?

Thanks,

Michel

**Comment by maajdl** [comment]
Hello,

I just added a method which is then used, indeed, as a "richer formatter":

```
Base.show(io::IO, ::MIME"text/html", td::ThermoData) = print(io, summary(td))
```
Unfortunately, I cannot get the output I would like.
This returns exactly what I wish:
```
summary(someThermo)
```

But this returns a scrambled version of the same:
```
someThermo
```

Is there a (simple) way to have the same display by `summary` and by `show` ?

Thanks

Michel

**Comment by fonsp** [comment]
@maajdl Can you continue experimenting with this until you have a small number of concrete questions? Open a [Discussion](https://github.com/fonsp/Pluto.jl/discussions) when you're ready.
