### ISSUE TITLE
localhost refused my connection. ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by TracyWu1122** [fonsp/Pluto.jl#1150]
I just cannot connect to the localhost as I used to do. How to cope with it?

**Comment by fonsp** [comment]
Without more information, the best advice I can give is: restart your computer and update everything.

**Comment by decoherencer** [comment]
On a related connection issue, I used `host="0.0.0.0"` argument in the Pluto.run to fix it

https://github.com/fonsp/Pluto.jl/blob/8f836578984d7f7c6dcc80332cd8e5df07d5856f/src/webserver/WebServer.jl#L78

**Comment by fonsp** [comment]
@decoherencer What is your set-up like? Are you using a proxy/container?

**Comment by decoherencer** [comment]
Yes, I was behind a campus proxy.
