### ISSUE TITLE
Highlight syntax for HTML/CSS/JS/Markdown within Julia code (juliamixed mode)

### ISSUE THREAD

**Issue by schneiderfelipe** [fonsp/Pluto.jl#1152]
This would require [creating a new, *nested* CodeMirror mode](https://codemirror.net/doc/manual.html#modeapi) for Pluto. This new mode would delegate work to other modes based on context. This is [what `htmlmixed` does](https://codemirror.net/mode/htmlmixed/htmlmixed.js).

I think the most straightforward approach would be to detect literal strings in Julia and delegate a separate mode within the string if the content matches some regular expression. This `juliamixed` mode might be too specific for the CodeMirror project, so should the contribution be made here?

**Comment by Pangoraw** [comment]
This had been discussed at the PlutoCon Q&A but I can't find the replay :smiley: 
> This new mode would delegate work to other modes based on context.

The main difference is that compared to `htmlmixed`, `juliamixed` can be recursive. For example, when using interpolation inside `@md_str`.

**Comment by schneiderfelipe** [comment]
> The main difference is that compared to `htmlmixed`, `juliamixed` can be recursive. For example, when using interpolation inside `@md_str`.

That's a great idea 💡.

Not sure whether this should be contributed to Pluto or CodeMirror, though.

**Comment by pankgeorg** [comment]
Also CodeMirror is evolving to [v6](https://codemirror.net/6/) so maybe it's wiser to wait a bit for something major.

**Comment by fonsp** [comment]
Implemented in #1533 , (then removed again in https://github.com/fonsp/Pluto.jl/commit/54646ed581e4f70c2c5585daa42a0c5005402033, then added back in https://github.com/fonsp/Pluto.jl/pull/1855, then removed again in https://github.com/fonsp/Pluto.jl/pull/1940, but we will add it back soon!)
