### ISSUE TITLE
HTML export no longer shows up in htmlpreview.github.io

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#1162]
Exporting to HTML and then using [htmlpreview.github.io](htmlpreview.github.io) to display the rendered HTML as a link no longer works.

Does not work in Pluto version v0.14.2 (not sure at what version it stopped working). Previously worked in version v0.12.20.

Here's an example of it **failing** with the corresponding .jl code (v0.14.2):
- http://htmlpreview.github.io/?https://raw.githubusercontent.com/mossr/PlutoNotebooks/master/html/em_algorithm.html
- https://github.com/mossr/PlutoNotebooks/blob/master/em_algorithm.jl

Here's an example of it **working** (v0.12.20): 
- http://htmlpreview.github.io/?https://raw.githubusercontent.com/mossr/PlutoNotebooks/master/html/gibbs_sampling.html
- https://github.com/mossr/PlutoNotebooks/blob/master/gibbs_sampling.jl

Note that opening the HTML file locally in my browser (Chrome) works fine. Also, I've tried running Pluto with `Pluto.run(require_secret_for_open_links=false, require_secret_for_access=false)` but that did not fix it.

**Comment by fonsp** [comment]
This is a problem with `htmlpreview.github.io`, which might be unavoidable due to their design, and I don't think that it is within our scope to fix it.

**Comment by fonsp** [comment]
Good point!

I made a site similar to htmlpreview that uses a more stable mechanism, and it works for Pluto notebooks:

https://htmlview.glitch.me/

**Comment by mossr** [comment]
Oh Fons, that's perfect! Thank you for sharing

**Comment by fonsp** [comment]
https://github.com/htmlpreview/htmlpreview.github.com/issues/102

**Comment by simona70** [comment]
Thx for https://htmlview.glitch.me/ :-)
