### ISSUE TITLE
Display equations in live docs

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#117]
The live docs feature is very neat! 
Perhaps equations in the live docs can also be rendered in Katex? 
e.g. `?exp`

**Comment by fonsp** [comment]
Thanks! I'll add that soon.

(We use MathJax right now, but you're right that Katex might be better. Although I have the impression that Katex supports fewer commands/extensions.)

**Comment by dpsanders** [comment]
MathJax is good too, whatever works!

**Comment by fonsp** [comment]
Implemented in `v0.9.1` :)
