### ISSUE TITLE
[suggestion] Make the order of display (optionally?) have an effect on execution order

### ISSUE THREAD

**Issue by rapus95** [fonsp/Pluto.jl#1173]
as far as I can tell the order of execution depends on how the cells are placed initially. I suggest to execute the cells in the order they are placed to break tie for cells that haven't a clear order by their dependencies. I.e. Run from top to bottom and only let go those cells first that are needed due to the topology/dependency graph.

That's especially helpful for global state/dependency management. Like having multiple cells that mutate that global state and shall happen in a certain order when the global object is (re)created but still be runnable independently.

Alternatively providing a way to intentionally manipulate the execution order would work aswell. (like ctrl+drag to change execution order while normal drag changes visual order)

**Comment by rapus95** [comment]
How about showing the order of execution as little numbers at the left end per cell div? I.e. the order the cells are executed on startup.

**Comment by fonsp** [comment]
> execute the cells in the order they are placed to break tie for cells that haven't a clear order by their dependencies

This is already how Pluto works

**Comment by rapus95** [comment]
Ok, then I need to investigate further, because I have a cell situation, where the evaluation on startup is as following:
A -> B (erroring) -> C -> B (no errors)
I'll get back here once I found out why.

Is it ok to open that "order of execution counters/numbers" idea as a new suggestion/issue?

**Comment by fonsp** [comment]
@patrickm663 Can you follow the instructions [here](https://github.com/fonsp/Pluto.jl/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) to help us fix it?
