### ISSUE TITLE
Hide UndefVarError if the upstream cell errored

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1179]
In this notebook, there is an error in the 2nd cell, causing **many dependent cells to error**, because they (indirectly) depend on a variable that should have been defined in the erred cell. 

<img width="863" alt="Schermafbeelding 2021-05-19 om 12 09 28" src="https://user-images.githubusercontent.com/6933510/118795628-12377c80-b89b-11eb-8d14-44910df5222a.png">

We should hide/de-emphasize these errors, and make them point to the _source error_.

---

For new contributors: This can be done entirely in the JS frontend, because the cell dependency information is available to frontend code. Computing this on the Julia side and writing this info in the error data is also okay. Also see https://github.com/fonsp/pluto-developer-instructions

**Comment by lungben** [comment]
How to detect affected cells in the frontend:

- `editor_state.notebook.cell_results[cell_id].errored == true` and

- `editor_state.notebook.cell_results[cell_id].output.body.msg` starts with `UndefVarError:` and 

- at least one upstream dependency cell, as given in the values of the dict `editor_state.notebook.cell_dependencies[cell_id].upstream_cells_map`, errored (i.e. `editor_state.notebook.cell_results[cell_id].errored == true`). Which error does not matter here.

**Comment by HirumalPriyashan** [comment]
![image](https://user-images.githubusercontent.com/57571152/164886203-9bf0fc60-dc5d-4125-92af-87ffc4a36f71.png)

Is this what we are expecting here?

**Comment by fonsp** [comment]
Fixed by #2057
