### ISSUE TITLE
Feature request: Presentation mode

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#118]
It would be fantastic to have a presentation mode like RISE for Jupyter notebooks:

https://rise.readthedocs.io/en/stable/

Basically it would convert the notebook into a live presentation.

**Comment by fonsp** [comment]
Yes that would be cool!

My current idea to use `h1` and `h2` tags as slide delimiters (that's `#` or `##` in markdown). There would be a _presentation mode_, which does nothing except add a large margin above every `h1` or `h2` tag, and some buttons to jump between them.

**Comment by fonsp** [comment]
You might see it in action next week!

**Comment by fonsp** [comment]
You need to write `present()` in the browser console to activate it, I will add a button later :)

**Comment by dpsanders** [comment]
I get `present() not defined`

**Comment by fonsp** [comment]
I took it out again 😬 but I can easily add it back in if you like? I just noticed that Markdown-only slides are a bit limiting, you need to write a bit of HTML and CSS to make things look more flashy.

For example, I wrote a `two_columns(md"I am on the left", md"I am on the ![](right.png)")` function - I can send that too!

**Comment by dpsanders** [comment]
I'd definitely like to have a go to see if it's usable!

**Comment by fonsp** [comment]
I've added it to `0.9.8` - with the same hack to activate it :)

**Comment by dpsanders** [comment]
Great, thanks!

**Comment by briochemc** [comment]
Could you describe what the hack is to start a presentation?

**Comment by dpsanders** [comment]
Open the Javascript console in your browser (developer tools) and type `present()` there.

**Comment by briochemc** [comment]
Of course! For the record, I got confused because, on Firefox, there is a *Web* console and a *Browser* console, and `present()` can only be typed and work in the *Web* console...

**Comment by fonsp** [comment]
@briochemc Could you let us know what you think about the presentation mode after you have tried it out?

**Comment by briochemc** [comment]
My three cents up to now:
- Maybe increase the size to match the screen width when in presentation mode? I think something like is done by [Remark](https://remarkjs.com/#3) could be a good guide?
- Use or h3 or even h4 as markers to split between slides? Or maybe have it in the `present` function, i.e., something like
`present(h3) would mark anything h3 or higher as a slide separator?
- As mentioned in https://github.com/fonsp/PlutoUI.jl/issues/11, showing values next to sliders for presentations would be a nice feature!
- Being able to "recall" a slider is useful. For example, when you want to change a variable with a slider that was defined a few slides before. But I noticed the sliders are not synced then, as in this MWE (cell 1 creates slider, cell 2 "recalls" the slider, cell 3 shows its value):
    <img width=60% alt="Screen Shot 2020-07-10 at 12 18 05 pm" src="https://user-images.githubusercontent.com/4486578/87109279-90a0b680-c2a7-11ea-92f2-3b94580f6ccd.png">
    I can change the value of `x` by moving either slider. But it is a bit annoying that the other slider does not update its position (as you can see they are not synced). Maybe that's intended though?

**Comment by fonsp** [comment]
Thanks! 3 and 4 are useful for Pluto in general, I have added them to the suggestion box. 

1 and 2 might be nice to have, but I think a bigger issue is that slides written in `md""` are just not exciting enough. (That's why this is still a hidden feature.) What could be added to make slides more attractive?

Remark looks fun, but it's not trivial to integrate with Pluto

**Comment by briochemc** [comment]
FYI, I just mentioned remark for inspiration for the sizing (font size and spacing), but I guess there are plenty of other sources of inspiration out there, like, e.g., RISE. And 2 was because I felt like I had to manually zoom in on my browser to get a good font size, but then the h1 and h2 titles seemed too big.

BTW, I should mention that Pluto already looks great anyway! 😃

**Comment by fonsp** [comment]
_note to self: the autoscrolling should be disabled in presentation mode_

**Comment by AsafManela** [comment]
I love this feature. Two questions:
1.  Is there a function to exit (e.g. `unpresent()`)?
2.  Can I put in a pause in the middle of a slide to gradually uncover cells?

**Comment by GiggleLiu** [comment]
> 1. Is there a function to exit (e.g. `unpresent()`)?

Call `present()` again to exit.

**Comment by fonsp** [comment]
>     2. Can I put in a pause in the middle of a slide to gradually uncover cells?

No, but you can copy paste the same slide a couple of times, and delete parts of it

**Comment by fonsp** [comment]
Are we satisfied with the current presentation mode? Then I'll add a button in the export menu

**Comment by AsafManela** [comment]
> > ```
> > 2. Can I put in a pause in the middle of a slide to gradually uncover cells?
> > ```
> 
> No, but you can copy paste the same slide a couple of times, and delete parts of it

That's certainly a workaround. Just requires a bit of code replication I was hoping to avoid. 

I can open another issue with this feature request.

**Comment by Moelf** [comment]
one idea is when redering a cell in presentation mode, if it has multiple `##` under `#`, put them in separate slides when presenting

**Comment by AsafManela** [comment]
What I had in mind is like RISE's feature for [fragment](https://rise.readthedocs.io/en/stable/usage.html) cells

**Comment by fonsp** [comment]
@Moelf what do you mean? this sounds like the current behavior

@AsafManela that sounds like something that an external package/code should do

**Comment by Moelf** [comment]
you're right

**Comment by p-gw** [comment]
@fonsp would you mind sharing the functions you used for layouting your JuliaCon presentation?

**Comment by jinjunsun** [comment]
nice to hear about that.

**Comment by fonsp** [comment]
# Instructions
@andreasKroepelin wrote a wonderful guide about this feature:

https://andreaskroepelin.de/blog/plutoslides/

**Comment by schneiderfelipe** [comment]
It would be nice to be able to show the slide number next to the control buttons, in the corner of the screen. That could be made optional, of course.

**Comment by VivaldoMendes** [comment]
Regarding the presentation mode in Pluto, one particular point does not seem very convenient (if I am not missing some specific functionality in Pluto). When one increases the size of the display (Ctrl->+) in Windows --- and with no `Table of Contents` (by mere option) and without the `Live docs` window (removed by the presentation mode) --- the Pluto display window keeps moving further to the left of the monitor.  In this case, there will be a large area on the right-hand side of the monitor that will be left idle. Why not allowing the Pluto display to be seen in the center of the monitor if there are no Table of Contents neither Live docs on the right-hand side? 

If we are presenting the materials online, there will be no problem (for obvious reasons). But if we are going to use a Pluto notebook in a classroom, I think this particular point may unappealing to students.

**Comment by KingBoomie** [comment]
For anyone who wants to go (forward / back) a slide by right/left clicking anywhere (that isn't an interactive component), I'm using this small snippet:
```
SlideNextPrev() = @htl("""
<div>
<script>
	var body = document.querySelector("body")
	var prev = document.querySelector("button.changeslide.prev")
	var next = document.querySelector("button.changeslide.next")
	
	const click_background = (e => {
		if (body != e.target) return;
		e.preventDefault();		
		console.log(e.button);
		if (e.button === 2 && prev) {
			prev.click();
		} else if (e.button === 0 && next) {
			next.click();
		} 
		})
	body.addEventListener("click", click_background)
	body.addEventListener("contextmenu", click_background)
</script>
</div>
""")
```

**Comment by rgouveiamendes** [comment]
I don't know if anyone else has this problem, but the navigation buttons are not working in my machine.

**Comment by DhruvaSambrani** [comment]
@fonsp, is it possible to edit the elements which trigger the slide break? I would suggest h1, h2, and a custom "slidebreak" element. Currently, PlutoReport.jl has a `slidebreak` which is just `<h1></h1>`, but this needs some css hack for the TableOfContents to not show an empty entry. Also, at this point, it may be useful to refacter the presentation code into a new package, maybe `PlutoSlides`?

**Comment by jrdegreeff** [comment]
> Is there a keyboard shortcut to go forward - backward? If not, is it possible to define one myself?

@gdalle, you may have figured out your own way of doing this by now, but I was wanting the same thing and put together this solution. Just stick this anywhere in the notebook and when in presentation mode the arrow keys will be equivalent to the prev/next buttons. You can also use other keys by changing the key codes.

```
html"""<script>
window.addEventListener('keyup', function(e) {
	if (document.body.classList.contains("presentation")) {
		if (e.keyCode === 37) {  // left arrow
			document.getElementsByClassName("changeslide prev")[0].click();
		} else if (e.keyCode === 39) {  // right arrow
			document.getElementsByClassName("changeslide next")[0].click();
		}
	}
});
</script>"""
```

**Comment by gdalle** [comment]
@jrdegreeff yesterday's release of Pluto includes this out of the box ;)

**Comment by jrdegreeff** [comment]
What funny timing hahaha. In any case, glad we are updating this thread because this is what comes up if you search on Google.

Thanks for pointing this out because I was going to be very confused when I eventually updated versions and started skipping slides because of the doubled action!

**Comment by gdalle** [comment]
I think we can close this issue now in favor of more specific ones?

**Comment by mossr** [comment]
Note, it looks like the instructions have been moved to https://www.andreaskroepelin.de/blog/plutoslides/

**Comment by navidcy** [comment]
Strange that the docs don't have anything on presentation mode (I was just looking at least and couldn't find anything).
Should we at least link to the [blog](https://www.andreaskroepelin.de/blog/plutoslides/) mentioned above somewhere in the docs?

**Comment by fonsp** [comment]
Docs on plutojl.org will come soon!

**Comment by fonsp** [comment]
Check out the [📚 documentation on plutojl.org](https://plutojl.org/en/docs/presentation/) to learn how to use it! 

_If you have comments or feedback about this feature, feel free to open a new issue!_
