### ISSUE TITLE
Pluto works only with Firefox, with Chrome makes Explorer in Win7 to freeze

### ISSUE THREAD

**Issue by marcello-pietrobon** [fonsp/Pluto.jl#1188]
Hello Pluto's team,

on Win7 I can only run Pluto on Firefox without problems.

With Brave is randomly working (one time out of three or more)

With Chrome I have serious problems. Especially when it works, if I do Ctrl+C from the Julia console I get Win7 explorer freeze.

This is extremely annoying because when you kill the explorer process the Quick Launch taskbar looses all it's ordering (and MS doesn't know how do something working right)

I'm not submitting the stack trace because it seems every time different, but if you need...

Thank you.

**Comment by marcello-pietrobon** [comment]
Here too, as in issue [1189](https://github.com/fonsp/Pluto.jl/issues/1189) the problem is due to the per-application firewall I'm using.

Still, I have issue with the fact that by doing Ctrl+C to an application to kill it, the OS' explorer has to freeze. but maybe this is completely **not** due to the way the notebook is launched by Pluto, I simply don't know.

Well, at least others will know what the problem could be if it happens with them.

Best,
M

**Comment by pankgeorg** [comment]
This is an issue that's not related to pluto. 
Also note that Windows 7 are not supported [_by **Microsoft**_](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information), so we can't really debug it!

I'm closing this issue as your primary issue is solved, please do let us know for anything pluto-specific you dig out!

Thanks,
Panagiotis
