### ISSUE TITLE
Error message is not shown

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#119]
When I write the following into the REPL
```
"At $t_i$"
```
I get the expected error message 
```
ERROR: syntax: invalid interpolation syntax: "$""
Stacktrace:
 [1] top-level scope at REPL[6]:0
```

But when I enter the same into a Pluto cell and execute it the cell is correctly marked as failed but the error is neither shown in the notebook nor in the terminal where Pluto was started.

**Comment by fonsp** [comment]
Thanks! Happens for me too.

**Comment by fonsp** [comment]
[Testset](https://github.com/fonsp/Pluto.jl/commit/1ee7804f394f704281c91c25d3523bbfce4e148e#diff-d4b8b4704dfa87745eb39b155c966ae4R84) 🐒
