### ISSUE TITLE
Feature request: ability to specify in some way which browser to launch

### ISSUE THREAD

**Issue by marcello-pietrobon** [fonsp/Pluto.jl#1190]
Hello Pluto's team,

due to issue  https://github.com/fonsp/Pluto.jl/issues/1189
it would be nice to have the possibility to specify in some way which browser to launch when running Pluto, that is non just with the default browser.

A solution like
[How to set default web browser per domain?](https://superuser.com/questions/448030/how-to-set-default-web-browser-per-domain) seems truly too cumbersome.

Thank you.

**Comment by pankgeorg** [comment]
This is also, not a Pluto feature/issue! I would propose though, to ask pluto not to launch a browser and then launch it yourself.

The command would look something like the following:

`julia -e "import Pluto; Pluto.run(launch_browser=false)"`

Then, use something like [this - for PowerShell](https://stackoverflow.com/a/44335508/3757815) for example, to open a browser!
