### ISSUE TITLE
Large arrays hang up the browser

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1193]
Showing any large 2d array, such as `rand(10000, 1000)`, results in the browser hanging. Tested with smaller arrays: looks like Pluto tries to display the complete content, which is clearly infeasible.

This is on Pluto 0.14.6. Previous versions (correctly) only show a part of the array content.

**Comment by fonsp** [comment]
Thanks! Fixed in 0.14.7
