### ISSUE TITLE
Memory allocated in cells doesn't get freed easily

### ISSUE THREAD

**Issue by maleadt** [fonsp/Pluto.jl#1194]
From https://github.com/JuliaGPU/CUDA.jl/issues/926: creating a cell that allocates a bunch of memory (but doesn't assign it) ultimately results in an OOM:

![image](https://user-images.githubusercontent.com/383068/119674858-d6715980-be3c-11eb-8f81-deb84156fa25.png)

This might be related to the fact that Pluto uses different tasks for each cell (or at least that's what it looks like, I'm not familiar with the architecture):

![image](https://user-images.githubusercontent.com/383068/119674566-9611db80-be3c-11eb-814b-1469ba9d8d75.png)

... and data can get captured in a task:

![image](https://user-images.githubusercontent.com/383068/119688953-bd6ea580-be48-11eb-85dd-21e613dc7b31.png)

```
      From worker 2:    Task (runnable) @0x00007fe1c7500400
      From worker 2:    Task
      From worker 2:      code: #96 (function of type Distributed.var"#96#98"{Distributed.RemoteValue, Distributed.var"#103#104"{Distributed.CallMsg{:call}}})
      From worker 2:        rv: Distributed.RemoteValue
      From worker 2:          c: Channel{Any}
      From worker 2:            data: Array{Any}((1,))
      From worker 2:              1: Tuple{Vector{Float64}, UInt64}
      From worker 2:                1: Array{Float64}((512,)) [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      From worker 2:                2: UInt64 0x000000000001108a
```

**Comment by fonsp** [comment]
This is 'by design': we store the resulting object of each cell, allow us to implement a "more" button in the tree viewer. (In your example, the `;` disables output, but the expression still returns the `one` array as the cell's result.)

Try changing `;` to `; "hello"` and see if the problem is still there?

**Comment by maleadt** [comment]
Yeah, this is what I figured in https://github.com/JuliaGPU/CUDA.jl/issues/926#issuecomment-848728976, and is going to be problematic for GPU use cases. The fact that cells are executed in separate tasks doesn't help, but that's probably due to how Distributed works. Copying @roflmaostc, who filed the original issue.

**Comment by fonsp** [comment]
@maleadt Can you confirm that  memory is freed when adding `; "hello"`?>

**Comment by maleadt** [comment]
Yes, It is.
