### ISSUE TITLE
TypedTables.Table and PrettyTables not displayed properly

### ISSUE THREAD

**Issue by oschulz** [fonsp/Pluto.jl#1197]
Pluto doesn't display `TypedTables.Table` and the output of `PrettyTables.pretty_table` properly, I get

![typetables](https://user-images.githubusercontent.com/546147/119829098-2ca4d200-befb-11eb-9959-b68a9a19f78a.png)

The output of `pretty_table` should actually be independent from the type of table (TypedTables, Dataframes, etc.) used.

I'm sure if there's something missing in Pluto, or if TypedTables and PrettyTables are missing some show method(s) that Pluto needs. In Jupyter, the example above shows the tables correctly (as tables). How does Pluto handle display?

**Comment by fonsp** [comment]
Can you press F12 and share the JS console output?

**Comment by oschulz** [comment]
This one?

![jsconsole](https://user-images.githubusercontent.com/546147/119946361-d84f3000-bf96-11eb-8dd3-ed5baf7410ab.png)

**Comment by oschulz** [comment]
Also, on the Julia console:

```
      From worker 3:	Table with 2 columns and 5 rows:
      From worker 3:	     a         b
      From worker 3:	   ┌───────────────────
      From worker 3:	 1 │ 0.470925  0.310589
      From worker 3:	 2 │ 0.164783  0.382515
      From worker 3:	 3 │ 0.167323  0.880481
      From worker 3:	 4 │ 0.620667  0.929455
      From worker 3:	 5 │ 0.253003  0.892914┌───────────┬───────────┐
      From worker 3:	│         a │         b │
      From worker 3:	│   Float64 │   Float64 │
      From worker 3:	├───────────┼───────────┤
      From worker 3:	│  0.877966 │  0.343609 │
      From worker 3:	│ 0.0456932 │  0.653112 │
      From worker 3:	│  0.509526 │  0.899253 │
      From worker 3:	│  0.253696 │ 0.0522081 │
      From worker 3:	│  0.371058 │  0.210265 │
      From worker 3:	└───────────┴───────────┘
      From worker 3:	┌──────────┬──────────┐
      From worker 3:	│        a │        b │
      From worker 3:	│  Float64 │  Float64 │
      From worker 3:	├──────────┼──────────┤
      From worker 3:	│ 0.987645 │ 0.834434 │
      From worker 3:	│ 0.189591 │ 0.283874 │
      From worker 3:	│ 0.131987 │ 0.518774 │
      From worker 3:	│ 0.374513 │ 0.565222 │
      From worker 3:	│ 0.696506 │ 0.992867 │
      From worker 3:	└──────────┴──────────┘
      From worker 3:	┌──────────┬──────────┐
      From worker 3:	│        a │        b │
      From worker 3:	│  Float64 │  Float64 │
      From worker 3:	├──────────┼──────────┤
      From worker 3:	│ 0.615555 │ 0.606287 │
      From worker 3:	│ 0.171489 │ 0.447787 │
      From worker 3:	│ 0.646762 │ 0.527264 │
      From worker 3:	│ 0.517251 │ 0.136518 │
      From worker 3:	│ 0.979005 │ 0.495694 │
      From worker 3:	│ 0.256644 │ 0.235649 │
      From worker 3:	└──────────┴──────────┘
```

**Comment by fonsp** [comment]
It looks like your package writes to the terminal, not the `io` argument provided to `Base.show`.

E.g. write this:
```julia
Base.show(io::IO, ::MIME"text/plain", x::MyType)
	println(io, "hello")
end
```
not this:
```julia
Base.show(io::IO, ::MIME"text/plain", x::MyType)
	println("hello")
end
```

**Comment by oschulz** [comment]
> It looks like your package

It's not my package, but I'll let them know! :-)

Sorry, I wasn't aware that Pluto doesn't capture `stdout` output like Jupyter does.

**Comment by ederag** [comment]
With the `HTML` backend, [an HTML object is returned](https://ronisbr.github.io/PrettyTables.jl/stable/man/usage/#Usage) by `pretty_table`, and well displayed by Pluto:
```julia
using PrettyTables
data = rand(3, 5)
pretty_table(HTML, data)
```
The style can be controlled, e.g. with `pretty_table(HTML, data, tf=tf_html_simple)`;
see the [HTML backend](https://ronisbr.github.io/PrettyTables.jl/stable/man/html_backend/) section for more.
