### ISSUE TITLE
Cell disabling at notebook startup

### ISSUE THREAD

**Issue by lungben** [fonsp/Pluto.jl#1198]
Currently, the cell disabling #985 is only in the current Pluto session, but not persistent in the notebook.jl file. Especially, when opening a notebook all cells are active, which may lead to long execution times.

It should be possible in Pluto to mark cells which should be disabled when starting the notebook. This information is then stored in the notebook file.

Backend:
* Store the information if a cell is disabled as startup as a comment in the first line of the cell, e.g. 
`# 🛑 disabled at startup 🛑`
* The disabled code still stays active in the notebook.jl file itself so that it is executed if the notebook.jl file is run as a standard Julia file. Cell disabling is a feature for improving interactive notebook experience.

Frontend:
* For enabling / disabling the cell at startup, additional entries in the cell context menu (the same as for disabling cells in the current session) should be added.
* How do we show if a cell is disabled at notebook start?
  * Add a new UI element for it, e.g. 🛑 at the cell?
  * Just show the comment `# 🛑 disabled at startup 🛑` as first line in the cell itself (simplest solution)?

Happy to discuss!

**Comment by ederag** [comment]
Persistent disabling would be great indeed.

> The disabled code still stays active in the notebook.jl file itself
> so that it is executed if the notebook.jl file is run as a standard Julia file.

Just to fuel the discussion, I'd prefer the opposite.
Disabled cells can become obsolete, as they are not executed by Pluto.
So to me they are in the limbo, and should not be executed in the repl.
(Only cells that actually run in Pluto would be run when the file is included in the repl).

Technically, disabled cell code could be wrapped in a [multi-line comment](https://docs.julialang.org/en/v1/base/punctuation/), as
```julia
# ╔═╡ 45fab7a0-9076-11eb-284b-9b712e6f3d46
#=╠═ Cell manually disabled in Pluto (or "Cell disabled by Pluto because it depends on a disabled cell")
...
=#
```
The documentation says multi-line comments are nestable, 
so it should work even with other comments in the cell code.

**Comment by fonsp** [comment]
I was also thinking that "Cell disabling" should be codified as commenting-out-the-cell in Pluto! That fits the ideal that Pluto is "making existing Julia features interactive", instead of adding our own.

Just using `#= ...cell code... =#` could lead to edge cases that break existing notebooks, so  I really like @ederag's suggestion of using a special first line!
