### ISSUE TITLE
Expected notebook features

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#12]
See below

**Comment by malyvsen** [comment]
Priority imo:

- [ ] adding cells
- [ ] removing cells
- [ ] move cells - _should not be clunky!_
- [ ] errors inside UI
- [ ] error when multiple cells modify the same symbol
- [ ] show which cells are running/pending
- [ ] hiding code
- [ ] show that a cell's code is different from when it was evaluated
- [ ] button to run code
- [ ] keyboard shortcuts
- [ ] "run all" button
- [ ] export PDF
- [ ] export HTML

**Comment by fonsp** [comment]
😎😎😎
