### ISSUE TITLE
Ctrl + d  keyboard shortcut interferes with macOS functionality

### ISSUE THREAD

**Issue by terasakisatoshi** [fonsp/Pluto.jl#1200]
I prefer to use Ctrl-P/N/F/B/D/K/Y/D/A/E on macOS to control the cursor on text. On Pluto notebook, It seems Ctrl-P/N/F/B/K/A/E works as described in `Document shortcuts` section of Mac keyboard shortcuts: https://support.apple.com/en-us/HT201236.

Unfortunately `Ctrl-D` does not work as `Control-D: Delete the character to the right of the insertion point.`. 

Since line in `KeyboardShortcuts.js` tries to replace `Ctrl-blah-blah` in with `Cmd-blah-blah` in `keymap`, one may think this is fine. 

https://github.com/fonsp/Pluto.jl/blob/cd7c123e5dc9cb5c2d28e119aa66b83cdb0371f7/frontend/common/KeyboardShortcuts.js#L14

However, this lines assigns `Ctrl-D` shortcut to do something (selecting some words ???)

https://github.com/fonsp/Pluto.jl/blob/28615ad0f053f505bc478f814bb69c4ccb522e8d/frontend/components/CellInput.js#L151-L162

If I remove this lines above, I can use Ctrl-D to delete the character to the right, which is what I expect on macOS.

Note that if one would like to use `Ctrl-D` functionality that Pluto.jl provides on macOS, one only have to do use `Cmd+D` (due to this line https://github.com/fonsp/Pluto.jl/blob/cd7c123e5dc9cb5c2d28e119aa66b83cdb0371f7/frontend/common/KeyboardShortcuts.js#L14) .

Do we need insert conditional branch something like ?

```javascript
if (!is_mac_keyboard){
  keys["Ctrl-D"] = () => {
  // do something
  }
}
```

Any thoughts about this issue ?

**Comment by terasakisatoshi** [comment]
using `delete` to remove `Ctrl-...` key from `keymap_with_cmd` works.

```javascript
export let map_cmd_to_ctrl_on_mac = (keymap) => {
    if (!is_mac_keyboard) {
        return keymap
    }

    let keymap_with_cmd = { ...keymap }
    for (let [key, handler] of Object.entries(keymap)) {
        keymap_with_cmd[key.replace(/Ctrl/g, "Cmd")] = handler
        delete keymap_with_cmd[key] // delete Ctrl-blah-blah e.g. Ctrl-D or Ctrl-M etc ...
    }
    return keymap_with_cmd
}
```

**Comment by fonsp** [comment]
Thanks! Feel free to make a PR, but notice that removing the `Ctrl-` shortcuts will break other shortcuts, e.g. `Ctrl-M` for `md"""`.

**Comment by likanzhan** [comment]
As `Ctrl + d` has been removed, is there a shortcut to stop the Pluto in the terminal? Thanks
