### ISSUE TITLE
Bad local forwarding specification 'N' when following the remote SSH instructions

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#1201]
I get an error following the instructions here: https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%92%BB--UI
```
> ssh doodoo -LN 1234:localhost:1234
Bad local forwarding specification 'N'
```

I'm running NixOS on the remote machine and connecting via Ubuntu with
```
> ssh -V       
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
```

By the way, is there a way to configure Pluto.jl to listen on 0.0.0.0 instead of 127.0.0.1 so that it picks up all incoming traffic and not just that from localhost?

**Comment by Ellipse0934** [comment]
Try `ssh -N -L 1234:localhost:1234` which should probably work.

But, of course you can configure the host and port as follows:

```julia
julia> conf = Pluto.Configuration.from_flat_kwargs(host="0.0.0.0", port = 1729)
Pluto.Configuration.Options(
  server = Pluto.Configuration.ServerOptions(
  root_url = nothing, 
  host = "0.0.0.0", 
  port = 1729, 
  launch_browser = true, 
  show_file_system = true, 
  notebook_path_suggestion = "/home/ubuntu/", 
  notebook = nothing, 
), 
  security = Pluto.Configuration.SecurityOptions(
  require_secret_for_open_links = true, 
  require_secret_for_access = true, 
), 
  evaluation = Pluto.Configuration.EvaluationOptions(
  run_notebook_on_load = true, 
  workspace_use_distributed = true, 
), 
  compiler = Pluto.Configuration.CompilerOptions(
  compile = nothing, 
  sysimage = nothing, 
  banner = nothing, 
  optimize = nothing, 
  math_mode = nothing, 
  project = "@.", 
  startup_file = "no", 
  history_file = "no", 
  threads = "2", 
), 
)

julia> Pluto.run(conf)
```

PS: Fixed the instruction on the wiki page which was `ssh user@ipaddress -LN 1234:localhost:1234` to `ssh user@ipaddress -N -L 1234:localhost:1234`

**Comment by samuela** [comment]
I'll give that a shot!

**Comment by fonsp** [comment]
> is there a way to configure Pluto.jl to listen on 0.0.0.0 instead of 127.0.0.1 so that it picks up all incoming traffic and not just that from localhost?

```julia
Pluto.run(host="0.0.0.0", extra_kwargs...)
```

@samuela @Ellipse0934 should we put this on the wiki?

**Comment by Ellipse0934** [comment]
So the difference between the two is that `127.0.0.1` is a loopback address; meaning that it's a service **only** for the host machine. `0.0.0.0` on the other hand is a a service available to any configured addresses. This is the book definition.

The functional difference is that say I am on wi-fi and my ip is `192.168.1.7` and I start Pluto with `host = "0.0.0.0"; port=1234` then other devices on the  same wi-fi network can access my pluto using the address `192.168.1.7:1234` in their browser however if I had set the host to `127.0.0.1` it cannot be accessed by anything outside this machine. Makes sense for a file server. I don't know if whether this to be the default address from the security perspective. I have however added this to the 'Can I use Pluto remotely ?' section.

**Comment by fonsp** [comment]
@Ellipse0934 modify the wiki as you think is best! You should have write access, otherwise let me know.

I think I understand the 127.0.0.1 / 0.0.0.0 difference, and indeed, a web server is meant to be public, a pluto server is meant to be private (by default). So let's leave the current default as is

**Comment by Ellipse0934** [comment]
Yeah I can edit. Just wanted to ensure if the modification was fine. I have done it.

We should close this issue. @samuela Were you successful ?

**Comment by samuela** [comment]
On my setup, `ssh doodoo -N -L 1234:localhost:1234` hangs forever but `ssh doodoo -L 1234:localhost:1234` works.

**Comment by Ellipse0934** [comment]
It doesn't hang; it simply creates a connection with no terminal interface. This is only useful if a pluto session is already running. I guess the latter command is the general case because to start a Pluto session we need a terminal.
