### ISSUE TITLE
Static HTML puts Plots.jl+plotly output in small scrolling window

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#1211]
MWE:
```
### A Pluto.jl notebook ###
# v0.14.7

using Markdown
using InteractiveUtils

# ╔═╡ 2bdcda10-c30c-11eb-26be-d19795e40a62
begin
	import Pkg
	Pkg.activate(mktempdir())
	Pkg.add("Plots"); using Plots
	plotly()
end

# ╔═╡ 2106fff7-743e-4b07-ae43-6a3d261639e8
plot(-2π:.002:2π, sin)

# ╔═╡ Cell order:
# ╠═2106fff7-743e-4b07-ae43-6a3d261639e8
# ╠═2bdcda10-c30c-11eb-26be-d19795e40a62
```

Instructions: Run the MWE, click the Static HTML button, then open the created static html page.

Output looks like: 

![image](https://user-images.githubusercontent.com/6796478/120377766-2cce1480-c2e3-11eb-8c13-3f65f6617936.png)

Windows 10, Julia v1.6.1, Pluto v0.14.7

**Comment by holomorphism** [comment]
Is this the same problem as issue #1088?

**Comment by klaff** [comment]
I think it is. It's not limited to Chrome (the above image is from Edge). 

I guess I didn't look through the closed issues before making this one.

**Comment by fonsp** [comment]
(Chrome and Edge use the same rendering engine)

**Comment by fonsp** [comment]
See my solution on https://github.com/fonsp/Pluto.jl/issues/1088
