### ISSUE TITLE
Revise.jl stopped working with 0.14.6

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#1212]
Hi, I am using Revise.jl for some package development with Pluto. In  0.14.5  it still worked, after the update it has no effect.

**Comment by fergu** [comment]
I'm new to Pluto so I can't say for sure it used to work, but I can confirm that I've also observed this behavior. The behavior also persists if `using Revise` is called before `using Pluto; Pluto.run()`.

If a module is updated then the only way to get those changes in to the Pluto notebook is to restart Julia as a whole. Simply stopping Pluto is not enough to clear the state.

**Comment by j-fu** [comment]
Yeah you can temporarily downgrade to 0.14.5 in oder to  speed up your development as long as you don't use any newer features. That's what I do in the moment.  Just use Pkg: `add Pluto@0.14.5` ... 

It is sufficient to have `using  Revise` before `using` any other packages in the notebook.

**Comment by fonsp** [comment]
Fixed and released in v0.14.8
