### ISSUE TITLE
A broken link in the javascript sample notebook

### ISSUE THREAD

**Issue by holomorphism** [fonsp/Pluto.jl#1225]
https://github.com/fonsp/Pluto.jl/blob/ed2e9dc9722e38811775d471e0cc9db7b70967c5/sample/JavaScript.jl#L475

The following links in the above notebook were not accessible:
- <https://observablehq.com/@observablehq/standard-library>

I think the correct link is
- <https://observablehq.com/@observablehq/stdlib>

I'm not sure how to submit a pull request, so I reported it as an Issue.

P.S. This notebook is very interesting!

**Comment by SyxP** [comment]
I could just help you write a PR, but I think its a worthwhile learning experience!

You can choose to use the github interface, or not. I have done exactly a simple "edit a link" PR earlier: https://github.com/fonsp/Pluto.jl/pull/1185 .

Without the github interface, the following video: https://www.youtube.com/watch?v=rgbCcBNZcdQ I think is pretty straightforward. Do give it a go!

**Comment by holomorphism** [comment]
@SyxP Thank you! I'll try.
