### ISSUE TITLE
Starting a markdown bullet with a latex character does not render correctly

### ISSUE THREAD

**Issue by caryfitz** [fonsp/Pluto.jl#1235]
A notebook cell containing this:

```
md"""
### $\int$ is not a greek letter
* I am fond of $\nu$
* $\nu$ it!
* Something old, something $\nu$, something borrowed
    * I am fond of $\nu$
    * Something old, something $\nu$, something borrowed
    * $\nu$ that I would find $\nu$
"""
```

Comes out with bad rendering.  It looks like the symbol is rendered by itself in the middle of a  line, followed by the rest of the text.  A latex symbol at the beginning of a line triggers this behavior.  Interestingly, it only applies to bullet points, (at any level) but not headers.

![nu](https://user-images.githubusercontent.com/1588610/121283862-b441f780-c890-11eb-8373-e072f0da7686.png)

It's not clear to me where the bug is.  The same text renders correctly with pandoc.  I installed julia from the julia archives, so I assume the tex/md are installed with julia and are different from the system's.  Given that the problem is specific to bullet points, it seems more likely that md is the culprit.
My  configuration:

julia> Pkg.dependencies()
Dict{Base.UUID, Pkg.Types.PackageInfo} with 145 entries:
  UUID("92933f4c-e287-5a05-a399-4b506db050ca") => PackageInfo("ProgressMeter", v"1.7.1", "afadeba63d90ff223a6a48d2…
  UUID("7f904dfe-b85e-4ff6-b463-dae2292396a8") => PackageInfo("PlutoUI", v"0.7.9", "44e225d5837e2a2345e69a1d1e01ac…
  UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb") => PackageInfo("REPL", nothing, nothing, false, false, false, false…
  UUID("cd3eb016-35fb-5094-929b-558a96fad6f3") => PackageInfo("HTTP", v"0.8.19", "c7ec02c4c6a039a98a15f955462cd7ae…
  UUID("6218d12a-5da1-5696-b52f-db25d2ecc6d1") => PackageInfo("ImageMagick", v"1.2.1", "5bc1cb62e0c5f1005868358db0…
  UUID("2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac") => PackageInfo("ImageAxes", v"0.6.9", "794ad1d922c432082bc1aaa9fa8f…
  UUID("53c48c17-4a7d-5ca2-90c5-79b7896eea93") => PackageInfo("FixedPointNumbers", v"0.8.4", "335bfdceacc84c5cdf16…
  UUID("10745b16-79ce-11e8-11f9-7d13ad32a3b2") => PackageInfo("Statistics", nothing, nothing, false, false, false,…
  UUID("83e8ac13-25f8-5344-8a64-a9f2b223428f") => PackageInfo("IniFile", v"0.5.0", "098e4d2c533924c921f9f9847274f2…
  ⋮                                            => ⋮

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4700G with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)

**Comment by holomorphism** [comment]
See this issue: #1127

**Comment by caryfitz** [comment]
Agreed it's the same issue...closing.
