### ISSUE TITLE
Interpolating LaTeXString into Markdown

### ISSUE THREAD

**Issue by zfengg** [fonsp/Pluto.jl#1237]
Recently I find the output of latexify() doesn't render well in markdown cell at the new versions included `v0.14.8` and `v0.14.7`. However, it works well in `v0.14.5`.

##  Comparison.
`v0.14.5`
![plutov5](https://user-images.githubusercontent.com/42152221/121305666-6ed50700-c930-11eb-9b78-b7acf7625c55.png)
### VS
`v0.14.8`
![plutov8](https://user-images.githubusercontent.com/42152221/121305715-83190400-c930-11eb-88f4-3d83251ae7a9.png)

## env
Both run in Chrome on Windows 10.

Also, the render doesn't work on Binder on which the Pluto version is `0.14.7`.

## remark
Right now I pin to `0.14.5` but I hope I can walk around this in the future versions to enjoy the amazing Pluto! Thanks.

**Comment by fonsp** [comment]
Unfortunately, this 'worked' because of a bug, and I fixed that bug: https://github.com/fonsp/Pluto.jl/pull/1164/files#diff-98c649aba98aa3bee0202b56f4e1d1e44ae620b564690ad53b114b49b03d69fcL351-R351

Markdown interpolation does not support latex objects (it will render them as text), you have to wrap them in a `Markdown.LaTeX`. You can use this helper function:

```julia
latexify_md(args...; kwargs...) = Markdown.LaTeX(repr(MIME"text/latex"(), latexify(args...; kwargs...)))
```

or more general for LaTeXStrings:
```julia
wrap_tex(x) = Markdown.LaTeX(repr(MIME"text/latex"(), x))
```

![Schermafbeelding 2021-06-09 om 10 49 28](https://user-images.githubusercontent.com/6933510/121323736-5ead2f80-c910-11eb-92fd-1e03437e6b92.png)

**Comment by zfengg** [comment]
I see. Thanks a lot!

**Comment by gustaphe** [comment]
Can you think of a good way to use this as a html show method?

```julia
Base.show(io, m::MIME"text/html", x::LaTeXString) = show(io, m, Markdown.LaTeX(repr(MIME"text/latex"(), x)))
```
doesn't work. I don't want to have to define a `latexify_md`, `latexraw_md`, `latexequation_md` when just allowing interpolating a latexstring would give me the full gamut of `Latexify`.

**Comment by fonsp** [comment]
@gustaphe You need to wrap the `Markdown.LaTeX` in a `Markdown.MD(...)`.

The problem them is that you Markdown's ability to automatically switch between display math and inline math, and I don't see a way to resolve that using the html show method. Let me try something else...

Interpolating LaTeX is a missing feature in Markdown, and `LaTeXString.jl` confuses the ecosystem.

**Comment by fonsp** [comment]
This works:

```julia
begin
	using Latexify
	using LaTeXStrings
	
	Markdown.html(io::IO, ls::LaTeXString) = 
		Markdown.html(io, Markdown.LaTeX(
			repr(MIME"text/latex"(), ls)
		))
	
	Markdown.htmlinline(io::IO, ls::LaTeXString) = 
		Markdown.htmlinline(io, Markdown.LaTeX(
			repr(MIME"text/latex"(), ls)
		))
end
```

![Schermafbeelding 2021-06-10 om 14 47 15](https://user-images.githubusercontent.com/6933510/121527492-c049c880-c9fa-11eb-8532-14641905b8ee.png)

**Comment by newptcai** [comment]
> This works:
> 
> ```julia
> begin
> 	using Latexify
> 	using LaTeXStrings
> 	
> 	Markdown.html(io::IO, ls::LaTeXString) = 
> 		Markdown.html(io, Markdown.LaTeX(
> 			repr(MIME"text/latex"(), ls)
> 		))
> 	
> 	Markdown.htmlinline(io::IO, ls::LaTeXString) = 
> 		Markdown.htmlinline(io, Markdown.LaTeX(
> 			repr(MIME"text/latex"(), ls)
> 		))
> end
> ```
> 
> ![Schermafbeelding 2021-06-10 om 14 47 15](https://user-images.githubusercontent.com/6933510/121527492-c049c880-c9fa-11eb-8532-14641905b8ee.png)

This works. Cannot you add it to Pluto? It's a bit of complicated to use LaTeXStrings now in Pluto.

**Comment by AtheistApe** [comment]
Greetings,

None of these methods seem to work in Pluto notebook v.0.19.29. Can anyone provide modifications of any of these solutions so it continues to work in the newer version of Pluto notebook?

**Comment by johtok** [comment]
Hi there!
Using pluto v.0.20.3 and both of these worked fine for me :)
> Unfortunately, this 'worked' because of a bug, and I fixed that bug: https://github.com/fonsp/Pluto.jl/pull/1164/files#diff-98c649aba98aa3bee0202b56f4e1d1e44ae620b564690ad53b114b49b03d69fcL351-R351
> 
> Markdown interpolation does not support latex objects (it will render them as text), you have to wrap them in a `Markdown.LaTeX`. You can use this helper function:
> 
> ```julia
> latexify_md(args...; kwargs...) = Markdown.LaTeX(repr(MIME"text/latex"(), latexify(args...; kwargs...)))
> ```
> 
> or more general for LaTeXStrings:
> 
> ```julia
> wrap_tex(x) = Markdown.LaTeX(repr(MIME"text/latex"(), x))
> ```
> 
> ![Schermafbeelding 2021-06-09 om 10 49 28](https://user-images.githubusercontent.com/6933510/121323736-5ead2f80-c910-11eb-92fd-1e03437e6b92.png)

> This works:
> 
> ```julia
> begin
> 	using Latexify
> 	using LaTeXStrings
> 	
> 	Markdown.html(io::IO, ls::LaTeXString) = 
> 		Markdown.html(io, Markdown.LaTeX(
> 			repr(MIME"text/latex"(), ls)
> 		))
> 	
> 	Markdown.htmlinline(io::IO, ls::LaTeXString) = 
> 		Markdown.htmlinline(io, Markdown.LaTeX(
> 			repr(MIME"text/latex"(), ls)
> 		))
> end
> ```
> 
> ![Schermafbeelding 2021-06-10 om 14 47 15](https://user-images.githubusercontent.com/6933510/121527492-c049c880-c9fa-11eb-8532-14641905b8ee.png)
