### ISSUE TITLE
Cannot display docstring of type Text{String}

### ISSUE THREAD

**Issue by melonedo** [fonsp/Pluto.jl#1239]
PyCall.jl returns documentation of Text{String}, `doc_fetcher` can not display it. This is how `doc_fetcher` uses its documentation
https://github.com/fonsp/Pluto.jl/blob/aef57ba471f6250a434ca389c1895952dfb84fd8/src/runner/PlutoRunner.jl#L1171
which fails because `show(::IOBuffer, ::MIME{Symbol("text/html")}, ::Text{String})` is not defined.

**Comment by fonsp** [comment]
Thanks for all the feedback on live docs, keep them coming!

**Comment by dralletje** [comment]
Ah I was too quick.
Obviously it's docs it gets through python... like in `PyPlot`!
But it is fixed now
