### ISSUE TITLE
Some unicode completions don't work

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1242]
Type `\^2<tab>` in a pluto cell - get `²` as expected. 
Type `\^-<tab>` and get `\^-	`: completion didn't trigger.
Meanwile, julia repl correctly gives `⁻` for the latter.

**Comment by fonsp** [comment]
To newcomers: search for `on_tab_key`

**Comment by fonsp** [comment]
🔥🔥🔥
