### ISSUE TITLE
Status mark missing for multiline using

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1243]
(By @sethaxen)

![image](https://user-images.githubusercontent.com/6933510/121780897-b06ce880-cba2-11eb-9ff3-7f6923a03833.png)

I think the solution is to ~simply~ switch our regex to multiline mode. I think we also need to switch to scanning the whole code, not just the changed line. But maybe this optimisation was too much anyways, since we already to `getCode` after every change.

Another idea is to move our analysis to the CM lexer

**Comment by dralletje** [comment]
Don't think so! Fixed by https://github.com/fonsp/Pluto.jl/commit/eada0647077f3ebf93d1e76a8515ed0c33eee2aa
