### ISSUE TITLE
My Pluto installation does not autocomplete

### ISSUE THREAD

**Issue by VivaldoMendes** [fonsp/Pluto.jl#1250]
Hi,

I have seen videos of people working with Pluto and using the autocomplete facility with the usual Tab. I am on a Windows 10 machine, Julia 1.6.1 and Pluto v0.14.7. But, despite having the autocompletion available in other IDESs (Atom, VScode, Jupyter), I do not see how to get it to work in Pluto. Do I need any particular package?

Help will be very much appreciated..

**Comment by fonsp** [comment]
What keyboard layout do you have?

**Comment by VivaldoMendes** [comment]
@fonsp thanks a lot for your shot. Right on the spot. I changed the keyboard ... and I have my autocompletion working on Pluto. My keyboard is Portuguese and I may have changed something in the customization I did in the past and never noticed.  Stupid thing, really. Thanks.

**Comment by fonsp** [comment]
@VivaldoMendes does autocomplete in Pluto not work with a Portuguese layout, or was it something specific to your system?

**Comment by VivaldoMendes** [comment]
@fons No, no, not all. Pluto works perfectly well with a Portuguese keyboard. The problem I had is a mixture of bad luck and lousy timing. I bought a fancy keyboard and customized it to my needs (basically, I was really fed up with the position of the brackets on a normal keyboard). But the (English) software to customize a Portuguese keyboard is not a free lunch. And the problem was based on that. In Atom or VSCode, we can do the autocompletion without the "tab" key,  but we have to use it in Pluto.  I was a bit lost about the autocompletion problem, and when you mentioned "keyboard", I got it immediately.

Sorry for the worries I might have caused you about the "Portuguese" keyboard. No problem with that. The problem was with **my** Portuguese keyboard. 

Congrats on the fantastic piece of software you developed. Jupyter ... long time, no see.
