### ISSUE TITLE
Copy cell output to clipboard

### ISSUE THREAD

**Issue by MarkNahabedian** [fonsp/Pluto.jl#1258]
It is easy to copy a cell's contents to the clipboard.  This is not so of the cell's output though.  When I want to copy the output of a Pluto cell, I first need to select all of the output, which is difficult to do using my laptop's trackpad.  Then, once I paste elsewhere, e.g. to GNU Emacs, I find that much of the punctuation is lost.  My best guess is that when outputting Julia objects the punctuation characters come from a CSS stylesheet rather than the output content.

**Comment by fonsp** [comment]
@MarkNahabedian What kind of output?

**Comment by MarkNahabedian** [comment]
I didn't really think about that.  In the cases I was interested in I just wanted plain text, mostly to reformat it in emacs to make it easier to read.

There was also a case though where I wanted to grab some SVG output as a string.  I'm using a Pluto notebook to do a CAD drawing (https://github.com/MarkNahabedian/DesignWithSVG/tree/master/solar_lights_bracket) for a CNC router and SVG is the router's input format.  I don't think the punctuation was lost when copying the SVG, but it was hard to select it all by dragging on the track pad.

It would be helpful to have a way to do "select all" on the cell output.

A workaround for the lost punctuation might be to format to a string before returning.  I've not tried this though.  More handy might be a context menu item to grab the cell output as plain text.


On Jun 22, 2021 7:10 AM, Fons van der Plas ***@***.***> wrote:

@MarkNahabedian<https://github.com/MarkNahabedian> What kind of output? An array/dict?

-

**Comment by fonsp** [comment]
Did you try triple-clicking the output?

**Comment by fonsp** [comment]
For SVG, you can right click the image to save it (depending on some other factors). There is also the `clipboard` function built in to Base. You can also try `PlutoUI.DownloadButton`.

**Comment by MarkNahabedian** [comment]
I didn't know triple click was a thing.

Thanks.


On Jun 22, 2021 6:43 PM, Fons van der Plas ***@***.***> wrote:

For SVG, you can right click the image to save it (depending on some other factors). There is also the clipboard function built in to Base. You can also try PlutoUI.DownloadButton.

-

**Comment by MarkNahabedian** [comment]
Tripple clicking on the cell output when that output represents a julia object just toggles between one line and multi-line representtations severaltimes.  Yes I'm clicking fast enough.

**Comment by ederag** [comment]
Just in case this was closed because of the triple click: it helps only to select a whole number.
The issue is about copying the whole output as text.

For instance, to transfer (`α = 0.180722891566265`) to a text note taking application,
`α` has to be copy/pasted, then ` = ` typed by hand, then triple-click to copy/paste `0.180722891566265`.

And for arrays, each element has to be copy/pasted by hand.

A "copy output" with tooltip "copy cell output to clipboard" action would be nice.

**Comment by MarkNahabedian** [comment]
Thanks.

My issue was to copy the full output of a complex nested Julia object so that it could be pasted to an editor for reformatting (mostly by adding newlines and reindenting) to make it more readable.

Having a popup menu item to copy output cell content as text would do what I want.

I find that triple click does not behave consistently across all cases of output content.
