### ISSUE TITLE
Store recent notebooks with absolute path

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#126]
Just recording this here quickly. I will investigate it more later.

When Pluto server is started from a different directory then normally the recent notebooks don't open anymore. I guess only their relative path is stored.

**Comment by fonsp** [comment]
Did you initially open those notebooks using a relative path?

**Comment by karlwessel** [comment]
Yep, I just tested it with two notebooks, one which I opened before with a relative path and one which I opened with an absolute path. After restarting Pluto from a different directory, the notebook that I opened by an absolute path worked, the other didn't.

**Comment by fonsp** [comment]
👍 I will fix this in the next release
