### ISSUE TITLE
Default not activating properly for MultiCheckBox on Pluto v0.14.8

### ISSUE THREAD

**Issue by ArchieCall** [fonsp/Pluto.jl#1260]
For MWE below: each line is a separate cell.
```julia
using Pluto
using PlutoUI
@bind my_boxes MultiCheckBox(["A", "B"]; default = ["B"])
my_boxes
```
Pluto v0.14.7
Activate Pluto and let it settle down -- do not click on the multi check boxes in any way.
The @bind line outputs check boxes "A" and "B" with box "B" checked. This is expected.
The my_boxes line outputs ["B"] which is the expected output.

Pluto v0.14.8
Same thing as Pluto v0.14.7, except the my_boxes line outputs shows nothing.
This means box "B" is checked, however the my_boxes cell has not reacted to this check.
If I uncheck box "B" and then check it again, then my_boxes shows ["B"], which is expected.

The net of this behavior is; MultiCheckBox defaults have no meaning on v0.14.8.

**Comment by fonsp** [comment]
#1284 might be related,

**Comment by fonsp** [comment]
Fixed, probably by https://github.com/fonsp/Pluto.jl/pull/1898
