### ISSUE TITLE
Print link with full hostname when starting?

### ISSUE THREAD

**Issue by DrChainsaw** [fonsp/Pluto.jl#1262]
This is what I do when starting a remote Pluto server:

```julia
julia> Pluto.run(host = "0.0.0.0", launch_browser=false)

Go to http://0.0.0.0:1234/?secret=sZ8noXtZ in your browser to start writing ~ have fun!

Press Ctrl+C in this terminal to stop Pluto
``` 

Here it seems like a low hanging fruit for the printout to be more helpful and insert the actual IP of the host instead of just echoing `0.0.0.0`. Or is there a better way to start the server?

Thanks for awesome software. It has eliminated alot of my fears wr.t. notebooks.

**Comment by fonsp** [comment]
Feel free to open a PR, but finding the IP seems like something beyond the scope of our project.

**Comment by DrChainsaw** [comment]
I'd be happy to make a PR. I was thinking about using [Sockes.getipaddrs](https://docs.julialang.org/en/v1/stdlib/Sockets/#Sockets.getipaddrs) because that is what solves my usecase, but I might be blissfully ignorant of the possible pitfalls here.

**Comment by Ellipse0934** [comment]
I too think this is beyond the scope of this project however it does have it's place in the docs. This may be useful for others.

**Comment by fonsp** [comment]
You could use #1285 to implement this just for your application

**Comment by DrChainsaw** [comment]
That looks like exactly what is needed! 

I was planning to do a similar local hack by just trying to brute-force multiple dispatch through the call chain, but now I'll wait for the above feature. Feel free to close this issue or make it so that #1285 fixes it.
