### ISSUE TITLE
Grouping "delete" button into "..." button causes inconvenience

### ISSUE THREAD

**Issue by liuyxpp** [fonsp/Pluto.jl#1266]
I find the "delete" button is replaced by "..." button on the rightmost side of each cell in the recent Pluto version (at least 0.14.8).  The "delete" button is very handy. I use it quite a lot: I always find myself trying some grammar/function in a temp cell.

So may I propose: please keep the "delete" button and place the "..." button next to it.

I think two buttons on the rightmost side of a cell will not consume too much place.

**Comment by fonsp** [comment]
Can you use our built-in feedback system instead? https://github.com/fonsp/Pluto.jl/issues/182
