### ISSUE TITLE
Markdown Latex issues

### ISSUE THREAD

**Issue by ess3sq** [fonsp/Pluto.jl#1273]
I have been noticing that some Latex commadns in Pluto markdown rendering cannot be stacked for some reason, ie. `\dot a` produces the correctly "dot-accented" letter, and `\vec a` produces the correct vector notation.

However, stacking `\dot \vec a` or `\vec \dot a` does not work. Is there any way to do this?

Thanks and sorry if I should have looked elsewhere to find the solution.

**Comment by lllusion3418** [comment]
Well, it's apparently not proper LaTeX either - this document
```tex
\documentclass{article}

\begin{document}
$\dot \vec a$
\end{document}
```
doesn't properly compile either:

<details>
<summary>output</summary>

```
$ pdflatex -interaction=nonstopmode foo.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./foo.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (./foo.aux)
! Missing { inserted.
<to be read again> 
                   \mathaccent 
l.4 $\dot \vec
               a$
! Missing } inserted.
<inserted text> 
                }
l.4 $\dot \vec a$
                 
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./foo.aux) )
(see the transcript file for additional information)</usr/share/texmf-dist/font
s/type1/public/amsfonts/cm/cmmi10.pfb></usr/share/texmf-dist/fonts/type1/public
/amsfonts/cm/cmr10.pfb>
Output written on foo.pdf (1 page, 15900 bytes).
Transcript written on foo.log.
```

</details>

Otoh, this works, both in Pluto (Mathjax) and in Pdflatex: `$\dot{\vec{a}}$`

![Screenshot_20210628_004742](https://user-images.githubusercontent.com/4203927/123561732-7870c280-d7aa-11eb-8a13-8184353c2383.png)

**Comment by ess3sq** [comment]
Interesting. It actually compiles on my pdflatex installation, which is why I use it. I don't doubt that it is sloppy to write like this, but I do it to save time.

**Comment by fonsp** [comment]
This sounds like a problem with MathJax. Can you try it on their demo website:

https://www.mathjax.org/#demo

and then report the issue there?

https://github.com/mathjax/MathJax-src

**Comment by ess3sq** [comment]
> This sounds like a problem with MathJax. Can you try it on their demo website:
> 
> https://www.mathjax.org/#demo
> 
> and then report the issue there?
> 
> https://github.com/mathjax/MathJax-src

After testing it on the demo page I can confirm that you are correct, I'll report it there.
