### ISSUE TITLE
Notebook title does not change after moving/renaming notebook

### ISSUE THREAD

**Issue by ess3sq** [fonsp/Pluto.jl#1274]
Dear all, after typing a path/name in the box at the top and hitting "Move", the title of the notebook does not change and stays at its default. Is that intended? If yes I thought it can be confusing because one is not sure if the "Move" button worked.
If this si a duplicate, sorry!

//Edit: yes, I checked and the Move button did indeed rename the notebook file, it just did not change the title of the notebook.

**Comment by fonsp** [comment]
What do you mean with "Notebook title"? Can you post a screenshot?

**Comment by Ellipse0934** [comment]
I think OP means the webpage title i.e. `<title>` in html. It seems to work for me. Screenshots, version info or some way to reproduce this would be helpful.

**Comment by ess3sq** [comment]
> I think OP means the webpage title i.e. `<title>` in html. It seems to work for me. Screenshots, version info or some way to reproduce this would be helpful.

That is indeed what I meant. Interestingly enough I can't seem to reproduce the issue on the latest Pluto version (I believe I upgraded a couple days ago), maybe the cause was fixed a while ago?

 Until I am met with the issue again, I suppose this should be closed. Thanks for replying everyone!
