### ISSUE TITLE
Pluto seems to work fine in Firefox but not in safari. 

### ISSUE THREAD

**Issue by santoshkumarradha** [fonsp/Pluto.jl#128]
Hi,

I just downloaded Pluto to try it out, but was surprised that I was stuck on 
![image](https://user-images.githubusercontent.com/29346072/83168785-07ab3280-a0e0-11ea-8aae-188df6fd259b.png)
but same when run on Firefox, it seems to be up and dandy.

**Comment by fonsp** [comment]
Hi, thanks for posting the issue!

To keep development fast-paced we are only supporting the latest versions of Firefox and Chrome _right now_, eventually support will be added for more browsers.

**Comment by CiaranOMara** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/24236593/83364693-717c5280-a3e6-11ea-980d-a6abbc91f7ea.png">

```
TypeError: event.data.text is not a function. (In 'event.data.text()', 'event.data.text' is undefined)
```

https://github.com/fonsp/Pluto.jl/blob/1ee7804f394f704281c91c25d3523bbfce4e148e/assets/client.js#L83

**Comment by fonsp** [comment]
We support safari by now
