### ISSUE TITLE
WYSIWYR: api.json and rapidoc

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1298]
@ctrekker I just found out about a standard for documenting web APIs:

https://jsonapi.org/

which can be used to automatically generate docs, e.g.:

https://mrin9.github.io/RapiDoc/

**Comment by ctrekker** [comment]
It wouldn't hurt to implement this, but I'm not sure how much it would help either. Much of the API's request and response requirements depend on the notebook itself, meaning little to nothing is known about type or attributes beforehand. There's also only one "resource" in the API, meaning there are no "relationships" and consequently about half of the spec dedicated to standardizing them would go unused. 

For example, here's what a request and response body currently looks like:
**Request:**
```json
{
  "inputs": {
    "a": 3,
    "b": 4
  },
  "outputs": ["c"]
}
```
**Response:**
```json
{
  "c": 5
}
```

And here's what it would look like with JSON:API:
**Request:**
As far as I can see JSON:API says very little about how requests bodies themselves should be formatted, so it would likely stay the same

**Response:**
```json
{
  "data": [{
    "type": "evaluate",
    "id": "c",
    "attributes": {
      "result": 5.0
    }
  }]
}
```
There's quite a bit of unused information that I'm not certain would provide any utility to the user
