### ISSUE TITLE
Import and overload function: multiple definitions

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1308]
Import and overload a function, Julia REPL:
```julia
julia> import Base: sin

julia> struct MyStruct end

julia> sin(x::MyStruct) = 2.0
sin (generic function with 14 methods)
```
The same doesn't seem to work in Pluto:
![image](https://user-images.githubusercontent.com/687995/125201171-947a6680-e276-11eb-8780-fa6556047dad.png)

**Comment by Pangoraw** [comment]
Hi! See https://github.com/fonsp/Pluto.jl/issues/846
