### ISSUE TITLE
Markdown cell output overflows when last row of contains LaTeX

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1309]
Whenever I create a markdown cell and there is a latex rendered element in the last row of the text, the cell output does not automatically update its height and a small overflow/scrollbar appear:

![image](https://user-images.githubusercontent.com/12846528/125266640-4dd44d00-e306-11eb-88df-5c260cfa89aa.png)

Any tips on how to fix this?

**Comment by holomorphism** [comment]
I am currently dealing with this by adding a custom css like the following.

```julia
html"""
<style>
mjx-assistive-mml { display: none !important; }
</style>
"""
```

(I don't really understand if it's okay to hide the "mjx-assistive-mml" element)

I'm not sure if Pluto or MathJax is responsible for this problem, but it seems to be caused by the height of the MathJax formula elements exceeding the output cell.

![image](https://user-images.githubusercontent.com/3076585/123520050-afcb6a80-d6e9-11eb-98ee-69692aa0f90d.png)

**Comment by disberd** [comment]
Thanks for the tip!

I noticed that you could also simply reduce it's height instead of removing it from the layout (and that doesn't need !important):

![image](https://user-images.githubusercontent.com/12846528/125295084-2b056100-e325-11eb-810c-3fdea7ec83d1.png)

Looking at the MathJax documentation, it seems that this `assistive-mml` is used to provide additional details for screen readers.
While probably not very relevant to Pluto, I think that putting a `display: none` there removes them completely from the layout so probably blocking their functionality of screen reading support

**Comment by disberd** [comment]
Reopening this as we might actually want to wait for feedback to see if it's the case to create a pull request to have this in the main Pluto css

**Comment by holomorphism** [comment]
@disberd Thanks for looking into MathJax! I'll use your solution for the time being.

**Comment by sje30** [comment]
just commenting that we also see this odd scrollbar behaviour, if there is tex on the last line of a text paragraph, 

https://sje30.github.io/catam-julia/casestudies/Primes%20and%20Efficiency/primes.html

but only in Chrome, not Firefox.

CC: @valentin-imbach @jmb280cam
