### ISSUE TITLE
Delete button is too deep

### ISSUE THREAD

**Issue by Moelf** [fonsp/Pluto.jl#1310]
delete is a frequently used function I think it shouldn't be hidden inside the menu. We could have delete on the bottom left of the cell which correspond to the `+` button and have the other two items in the menu as they are right now.

At least if we were going to hide it we should have snappy deletion with keyboard first

**Comment by ess3sq** [comment]
Tbh I think it's fine because if you hit backspace/delete in an empty cell, it deletes the cell. In my opinion this is very pleasant and prevents having to clutter stuff up by adding an explicit delete button under people's eyes.

**Comment by Moelf** [comment]
backspace/delete is not reliable. Try having multiple cells and then quickly do `Ctrl-A`-`BackSpace`-`BackSpace`-`Ctrl-A`-`BackSpace`-`BackSpace`-`Ctrl-A`-`BackSpace`-`BackSpace`

see how many times it doesn't register your delete-cell intention.

**Comment by ess3sq** [comment]
Backspace always registers for me, but you still make a good point. Personally I would prefer a way to just select a bunch of cells in bulk and hit backspace or ctrl-backspacd or something, it would be better than clicking delete so many times.

**Comment by liuyxpp** [comment]
> delete is a frequently used function I think it shouldn't be hidden inside the menu. We could have delete on the bottom left of the cell which correspond to the `+` button and have the other two items in the menu as they are right now.
> 
> At least if we were going to hide it we should have snappy deletion with keyboard first

Strange. I raised the issue before but it was deleted. I sincerely hope the delete button is exposed as in old versions.

**Comment by fonsp** [comment]
Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?

**Comment by Moelf** [comment]
I like to hear what others think, which could prove me wrong or I just have a bad workflow.

Posting to a black box doesn't feel useful.
