### ISSUE TITLE
Paste hijack is too strong

### ISSUE THREAD

**Issue by Moelf** [fonsp/Pluto.jl#1311]
![image](https://user-images.githubusercontent.com/5306213/125333473-9281d780-e34a-11eb-9d2c-e7dbb74c190f.png)

cannot paste from Julia REPL into cells where I want to have REPL example in markdown block

**Comment by Pangoraw** [comment]
Hey! Have you found a solution ?

**Comment by Moelf** [comment]
Nope but Pluto doesn't use issues for issues tracking it seems
