### ISSUE TITLE
MultiSelect does not stay selected upon `@bind`ing

### ISSUE THREAD

**Issue by mihalybaci** [fonsp/Pluto.jl#1316]
I am getting a weird behavior with multiple select HTML elements. When I create a multiple select field, the variable appears to bind properly, but the selected fields do not stay highlighted. So, if I try to CTRL+click to add a selection, the old values clear and I'm left with only the value I click. I had been using `MultiSelect` from PlutoUI.jl, but the issue appears to be with Pluto. The HTML element itself seems fine, and if I type this into a cell
```
#seems fine
html"""
  <select name="cars" id="cars" multiple>
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
"""
```
I get the proper highlighting. The problem only comes in when I try to bind a variable
```
# binds, but selections clear when trying to add new variables
@bind test html"""
  <select name="cars" id="cars" multiple>
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>
"""
```
I went through the different Pluto versions and think the issue started with v0.14.5. If it helps, I am also using Julia v1.6.1 and Firefox v89.0.2.

**Comment by disberd** [comment]
I think I rememberd reading that @bind gets the value of the first child of the pluto-output. It looks that the value of the `select` tag in HTML is just the first element that is selected.
I tried to modify the html code you put to include a custom getter and setter to properly match what is the actual selection:
```julia
@bind test html"""
	<div>
		<select name="cars" id="cars" multiple>
			<option value="volvo">Volvo</option>
			<option value="saab">Saab</option>
			<option value="opel">Opel</option>
			<option value="audi">Audi</option>
		</select>
		<script>
			const dv = currentScript.parentElement
			const sel = dv.firstElementChild

			Object.defineProperty(dv,"value",{
				get: () => {
					let val = []
					for (let i = 0; i < sel.options.length; i++) {
						const opt = sel.options[i]
						opt.selected && val.push(opt.value)
					}
					return val
				},
				set: vals => {
					sel.selectedIndex = -1
					vals.forEach(el => {
						const opt = sel.querySelector(`[value=${el}]`)
						opt && (opt.selected = true)
					})
				}
			})
		</script>
	</div>
"""
```

By putting that in a pluto cell I was able to correctly get the result from the @bind macro

![image](https://user-images.githubusercontent.com/12846528/127499478-08327cdd-3bc1-40fc-b4f9-9d043e2c89b9.png)
