### ISSUE TITLE
Stopwatch does not run

### ISSUE THREAD

**Issue by ess3sq** [fonsp/Pluto.jl#1325]
Sometimes the stopwatch for a cell just does not run. In this screenshot you can see it clearly. The cell is running (see the animated grey bar on the left), but the stopwatch is still showing the time from the previous run and the button is wrong (it is the "Run" button instead of the "Stop" button so that I cannot even kill the cell if I want to):

![plutoissue](https://user-images.githubusercontent.com/23216439/125866435-dd4d5a93-8ee9-410d-bbe5-2191c1a8fdb1.png)

See the last cell.

Obligatory details:
```shell
$ julia -v
julia version 1.6.1
```

```
(@v1.6) pkg> st Pluto
      Status `~/.julia/environments/v1.6/Project.toml`
  [c3e4b0f8] Pluto v0.15.1
```

Thanks for the help, I hope this is not a duplicate. Sorry if it is...

**Comment by fonsp** [comment]
The cell is queued (i.e. waiting to run), not running. Another cell might be running, or you are waiting for an internal process to complete.

**Comment by ess3sq** [comment]
No other cell was running. Is it normal for internal processes to take ~5min? This happens relatively often.
