### ISSUE TITLE
jlerror or jltree

### ISSUE THREAD

**Issue by CiaranOMara** [fonsp/Pluto.jl#133]
The opening and closing tags are different, Is that intended?

https://github.com/fonsp/Pluto.jl/blob/de637fbc8fd57b93bc8f0d78dbe31fcb3b5cb27d/assets/editor.js#L850-L862

**Comment by fonsp** [comment]
Nope! Thanks

**Comment by fonsp** [comment]
Fixed! [https://github.com/fonsp/Pluto.jl/commit/82aef9a4240333a58b4e408e72ebd0f11e492b51#diff-0c21b4b25ca12689564c836bc3749ac9L862-R864](https://github.com/fonsp/Pluto.jl/commit/82aef9a4240333a58b4e408e72ebd0f11e492b51#diff-0c21b4b25ca12689564c836bc3749ac9L862-R864)
