### ISSUE TITLE
PlutoUI table of contents overlaps cell action menu.

### ISSUE THREAD

**Issue by JaydevSR** [fonsp/Pluto.jl#1331]
The aside TOC from PlutoUI overlaps the cell action menu as shown in the SS. I think the z-index should be modified.
![Screenshot from 2021-07-24 17-52-06](https://user-images.githubusercontent.com/59474411/126868356-2db3f0e6-4f41-4bd8-96c8-c938361f6472.png)

**Comment by disberd** [comment]
Similar to [#1256](https://github.com/fonsp/Pluto.jl/issues/1256) but unlike that, this can actually be solved by setting a negative z-index to the cell containing the ToC itself, so probably more relevant as an issue for https://github.com/fonsp/PlutoUI.jl

**Comment by JaydevSR** [comment]
okay then I'll open a new issue at PlutoUI.
