### ISSUE TITLE
Markdown support for checkboxes

### ISSUE THREAD

**Issue by Dsantra92** [fonsp/Pluto.jl#1333]
Julia version - 1.7.0-beta2
Pluto version - 0.14.7

Though pluto allows checkboxes for Julia code, I cannot add checkboxes for simple markdown files.  I have used two possible formats for checkboxes in markdown:

```julia
md"""
- [] checklist 1
-[] checklist 2
"""
```
It results in the following output:
![image](https://user-images.githubusercontent.com/55111154/126929972-57fb1613-b3d9-4d8f-adf8-76087d105906.png)

If I am not missing out on anything,  I should consider checkboxes are not yet supported in Pluto. In that case, is there any planned support for the markdown checkbox in Pluto?

**Comment by fonsp** [comment]
Markdown is a part of Julia itself, not of Pluto. Can you repost your suggestion to https://github.com/JuliaLang/julia ?
