### ISSUE TITLE
Long array content is shown in full sometimes

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1337]
Here is what I mean:
![image](https://user-images.githubusercontent.com/687995/127282713-901f0457-c27b-438d-a6a2-6f252c6e5a49.png)
The original array content in the last cell is shown in full and not cut off. Changing `n=1000` to `n=1000000` can hang and crash the browser tab.

Julia REPL correctly puts an ellipsis:
```
julia> using MappedArrays
julia> let
       n = 1000
       arr = rand(n)
       mappedarray(i -> arr[i], 1:n)
end
1000-element mappedarray(var"#21#22"{Vector{Float64}}([0.9897030533970805, 0.6818836850726486, 0.5667066632392825, 0.4694552730109145, 0.5636352913770857, 0.5817086552085224, 0.8966505840658374, 0.7529363938230997, 0.23266344160781727, 0.529559558437215  …  0.11551969724613054, 0.4949727290098367, 0.34022708978720684, 0.5880226800082433, 0.7667254585081051, 0.7069391669643987, 0.23297682380023077, 0.7952726432181185, 0.24279359784294607, 0.8919694395208921]), ::UnitRange{Int64}) with eltype Float64:
```

**Comment by fonsp** [comment]
I labeled this as "Good first issue" because it should be relatively easy to debug why the array is not truncated. Report your findings here!
