### ISSUE TITLE
Can't modify structs defined with @with_kw from Parameters.jl

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1338]
Since the last update to better support macros in Pluto, I cannot re-define structs defined with `@with_kw` from [Parameters.jl](https://github.com/mauro3/Parameters.jl) (`Base.@kwdef` still works though)

I am not sure if this is something that can be fixed in Pluto without impacting the new macro analysis feature.

When trying to redefine structs from Parameters, the error about redefining values in another workspace is shown:
![image](https://user-images.githubusercontent.com/12846528/127287569-4b791916-18f4-4945-9800-4df058412ff5.png)

Of course in the example above I was trying to redefine same struct in two different cells, but updating a definition would work correctly for normal `struct` and `Base.@kwdef` but not for the `@with_kw` one, leading to the same error

**Comment by Pangoraw** [comment]
Thanks for reporting @disberd ! 

Can you try #1339 by adding:

```julia
(@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_FkIw9B/Project.toml`

(jl_FkIw9B) pkg> add https://github.com/Pangoraw/Pluto.jl#macro-parameters
     Cloning git-repo `https://github.com/Pangoraw/Pluto.jl`
    Updating git-repo `https://github.com/Pangoraw/Pluto.jl`
```

and confirm this solves the problem ?

**Comment by disberd** [comment]
@Pangoraw It does indeed fix the issue!
Thanks a lot!
