### ISSUE TITLE
Pluto doesn't see exported macros in the same cell where package is "using"

### ISSUE THREAD

**Issue by bvdmitri** [fonsp/Pluto.jl#1340]
The issue is pretty straightforward, Pluto.jl doesn't see any exported macro from any package within the same cell where `using SomePackage` is called.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/6557701/127328229-d12282ae-cc68-4ff3-8b78-a2ada40a7443.png">

If you prefix macro with a package name it also doesn't work:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/6557701/127328527-6a27f193-41d8-4cc3-b0ba-7e08c77ba416.png">

**Comment by fonsp** [comment]
This is a bug/feature of Julia: macros are expanded before evaluating the expression. `begin` groups everything into a single expression, and the macro is not defined before evaluating it.

**Comment by bvdmitri** [comment]
@fonsp I see, that makes sense. This issue can be closed I believe.

**Comment by Pangoraw** [comment]
Sorry about the wrong pointer. You can also use `DrWatson.@quickactivate` ton tell Pluto that the activate cell depends on DrWatson
