### ISSUE TITLE
Macro analysis doesn't work with CommonMark.@cm_str

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1342]
@Pangoraw using the latest main branch with macro analysis, it looks like the `@cm_str` string literal from [CommonMark.jl](https://github.com/MichaelHatherly/CommonMark.jl) do not update when variables it references get changed.

Tried using the `@htl_str` macro to test and that gets the update correctly: 

![cm](https://user-images.githubusercontent.com/12846528/127487168-1a3c37f8-f58d-4db8-a760-f3fa6bf59cdf.gif)

This thing came up on discourse where @MichaelHatherly mentioned he is willing to help in case there is some change needed on CommonMark side

**Comment by MichaelHatherly** [comment]
For reference as to what the macros expand to:

```
julia> @macroexpand htl"$x"
:(HypertextLiteral.Result(HypertextLiteral.content(x)))

julia> @macroexpand cm"$x"
:(
    CommonMark._interp!(
        Node(CommonMark.Document),
        CommonMark.JuliaValue[CommonMark.JuliaValue(:x, Base.RefValue{Any}(nothing))],
        [x],
    ),
)
```

So `cm""` has the interpolated expressions in a vector passed as the third argument to `_interp!`. Is that too complex for analysing?

**Comment by MichaelHatherly** [comment]
@disberd what commit are you using of `Pluto`? I've just tried out current `main` at 4ad8f1d0314a5dddf2734d541286c0b3eb43c3ea and `cm""` does appear to be doing the right thing.

**Comment by disberd** [comment]
@MichaelHatherly quite strange!
I retried just now doing a temporary environment and doing
`add Pluto#4ad8f1d` (Don't know if the reduced hash is sufficient)
and also later with 
`add Pluto#main` (which should work correctly)
but in both cases I still se the `cm""` macro not updating.
Since it works for you it might be an issue on my side maybe.

I am running skimulations so can't reboot right now but I'll try later to see if it fixes the issue

**Comment by Pangoraw** [comment]
Not reactive for me too :wave: This is not an issue with CommonMark and should be easy to fix. There are rules to convert the expanded expression to a "sanitized" version which should not contain package specific values because those cannot be sent to the Pluto process since it does not have those package loaded in (and shouldn't).

In this case the `@cm_str` macro returns a `Vector{CommonMark.JuliaValue}` as part of the expression which cannot be deserialized in the Pluto process.

I will open a PR with something like https://github.com/Pangoraw/Pluto.jl/commit/86bb4aad0c317652716acd9a75c3023de468a7f7 to fix this.

**Comment by MichaelHatherly** [comment]
`CommonMark` was already loaded in the REPL that started `Pluto.run()`. I assume that is what allowed it to work. Starting up `Pluto` in a REPL without it imported causes it to become unreactive.

> In this case the @cm_str macro returns a Vector{CommonMark.JuliaValue} as part of the expression which cannot be deserialized in the Pluto process.

There's also a `CommonMark.Node` returned, but I assume the same sanitisation will happen with that object.

**Comment by Pangoraw** [comment]
> There's also a CommonMark.Node returned, but I assume the same sanitisation will happen with that object.

Yes, it should be dealt with by this method:

https://github.com/fonsp/Pluto.jl/blob/9b1c07c799430cc7f854b2d22aa703a0902bfc88/src/runner/PlutoRunner.jl#L144-L149
