### ISSUE TITLE
When importing Oscar display of Vectors is broken

### ISSUE THREAD

**Issue by iimog** [fonsp/Pluto.jl#1346]
When I import [Oscar.jl](https://github.com/oscar-system/Oscar.jl) into a Pluto notebook the output of Vectors is broken. It looks strange for numbers and gives an Error for other types (e.g. strings):
```julia
# first cell
import Oscar
# second cell
["a","b"]
```
Error message:
```
Failed to show value:
MethodError: no method matching show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::String)
Closest candidates are:
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.QabModule.QabElem) at /home/markus/.julia/packages/Oscar/u2chq/experimental/Rings/QabAndPChars.jl:54
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.QabModule.QabField) at /home/markus/.julia/packages/Oscar/u2chq/experimental/Rings/QabAndPChars.jl:30
show(::IO, ::Union{MIME{Symbol("text/latex")}, MIME{Symbol("text/html")}}, !Matched::Oscar.MPolyIdealLoc) at /home/markus/.julia/packages/Oscar/u2chq/src/Rings/mpoly-local.jl:215

...

    show(::IOContext{IOBuffer}, ::MIME{Symbol("text/html")}, ::Vector{String})@IJulia.jl:325
    show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:654
    var"#sprint_withreturned#28"(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Vector{String})@PlutoRunner.jl:591
    format_output_default(::Any, ::Any)@PlutoRunner.jl:515
    #format_output#17@PlutoRunner.jl:532[inlined]
    formatted_result_of(::Base.UUID, ::Bool, ::Nothing, ::Module)@PlutoRunner.jl:448
    top-level scope@none:1
```

Here is a screenshot of the expected output (before importing Oscar)
![Screenshot_without_Oscar](https://user-images.githubusercontent.com/7403236/127671594-63daa996-d2d5-4c12-a74f-e4bb2b182570.png)

this is the output with Oscar imported
![Screenshot_with_Oscar](https://user-images.githubusercontent.com/7403236/127671609-2fd28034-a115-4a50-aaf3-93f1e6426a98.png)

I really love Pluto and Oscar, it would be great to use them together.

**Comment by fonsp** [comment]
Did you report this to the developers of Oscar.jl? It looks like the `Base.show` and `Base.showable` overloads added by (a dependency of) the package are not well-tested

**Comment by iimog** [comment]
Thanks for your response! I opened the issue here first as I only discovered the error when using Oscar inside Pluto. But I opened an issue there now as well: https://github.com/oscar-system/Oscar.jl/issues/597

**Comment by iimog** [comment]
This is fixed by Oscar (in the dev version) :tada: 
Thanks for your help and for creating Pluto.
