### ISSUE TITLE
@. macro gets highlighted in red

### ISSUE THREAD

**Issue by cjwyett** [fonsp/Pluto.jl#1360]
`@.` is legal Julia syntax, but in pluto notebooks the `@` symbol is highlighted in a ghastly red color. This is inconsistent with the way other macros are treated.

**Comment by Pangoraw** [comment]
This should be fixed by https://github.com/codemirror/CodeMirror/issues/6750

**Comment by dralletje** [comment]
Fixed by https://github.com/fonsp/Pluto.jl/commit/eada0647077f3ebf93d1e76a8515ed0c33eee2aa
