### ISSUE TITLE
Symbolics/ModelingToolkit parametric @variables not defined issue

### ISSUE THREAD

**Issue by Arryk** [fonsp/Pluto.jl#1362]
Simple issue that should be easy to replicate. When trying to define @variables that depends on @parameters I get a not defined error. See image below
![image](https://user-images.githubusercontent.com/12896037/128083349-aef848c0-174c-4dd3-9350-08502db3de8e.png)

Interestingly if we call @variables x(t) inside a function, Pluto is okay with it
![image](https://user-images.githubusercontent.com/12896037/128084992-576f4739-a8c7-42b3-80e7-4e24e2dd4d6f.png)

**Notebook Pkg.Status()**
[961ee093] ModelingToolkit v5.20.0
[0c5d862f] Symbolics v0.1.32

**Pluto Version:** 
[c3e4b0f8] Pluto v0.15.1

**Comment by Pangoraw** [comment]
It look like you are using Pluto v0.15.1, you can try the main branch of Pluto by doing `add Pluto#main` in the Pkg repl. The support for macros from Symbolics should be improved.

**Comment by Arryk** [comment]
This works on the main branch
![image](https://user-images.githubusercontent.com/12896037/128178422-7de0262a-fa76-446d-b562-abed88fc6b23.png)

[c3e4b0f8] Pluto v0.15.1 `https://github.com/fonsp/Pluto.jl.git#main

I guess this will be fixed on next release, I am closing the issue
Thanks for the quick answer
