### ISSUE TITLE
File sync

### ISSUE THREAD

**Issue by joshuacharleshyatt** [fonsp/Pluto.jl#1363]
Pluto philosophy is that notebook state is defined by code, yet if I change the code in an editor and save changes, Pluto does not refresh and update the notebook. Even if refreshing the browser, it appears Pluto does not sync the edits. For changes to sync, I have to close and reload the file inside Pluto.

**Comment by holomorphism** [comment]
See discussion #1314 and PR #1029.

**Comment by samuela** [comment]
See also https://github.com/fonsp/Pluto.jl/issues/240
