### ISSUE TITLE
"import PyPlot as plt" syntax breaks Pluto

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#1364]
As of Julia 1.6, there is now a convenient import/aliasing combined syntax, eg.
```julia
import PyPlot as plt
```
But Pluto isn't happy about this syntax at all: 
https://user-images.githubusercontent.com/226872/128089974-4a496bb6-ee02-4707-907b-a6f4cc46626a.mov

**Comment by Pangoraw** [comment]
See #1271
