### ISSUE TITLE
Pluto imports packages from false if-condition statements

### ISSUE THREAD

**Issue by bvdmitri** [fonsp/Pluto.jl#1365]
Pluto imports packages in global name space in cases where import is guarded with some condition, mwe:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/6557701/128192915-582d5bd8-031d-4241-86ab-aa6279019f3c.png">

This behaviour might be wrong, especially if `using SomePackage` has some side-effects and name conflicts

For example:

```julia
if false
    using CairoMakie
else
    using Plots
end
```

results in 

```bash
WARNING: both Plots and CairoMakie export "plot"; uses of it in module workspace11 must be qualified
```

In REPL for example that doesn't happen and it is possible to load packages based on some condition.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/6557701/128192961-092195dc-641f-4ac5-8a2f-f764810b9eb9.png">

**Comment by fonsp** [comment]
This is too difficult too fix right now :)
