### ISSUE TITLE
CSS style for blockquote

### ISSUE THREAD

**Issue by TheCedarPrince** [fonsp/Pluto.jl#137]
Hey all,

Working with Markdown in Pluto. I am seeing some strange behaviors in Pluto that I want to report. I am not sure if these were intentional or not. Here they are:

1. **I cannot comment in markdown blocks.** This is a pretty severe issue as sometimes I will need to comment things while writing things. As of now, whenever I comment something in a markdown block, it shows up like this:

```
<!-- Hello, I am a comment -->
```

When it should not show up at all.

2. **Why does HTML not render inside of Markdown?** Most of the time, I embed some HTML syntax inside of my markdown for formatting or my workflow such as the comment style in 1. Why can I not do that here?

3. **Unexpected behavior for quotes.** Whenever I make a quote using the `>` character, the text is simply indented. I was expecting it to be highlighted like this:

> I am a quote!

As opposed to this:

```
    Hello world!
```

Is this behavior intentional?

---

Thank you so much for looking at this, and I hope that we can continue to make things better in Pluto. If this is something doable to fix, let me know, and I can take a look. Otherwise, I'd be happy to report on testing things out for you.

P.S. I am using Pluto v.1.4

**Comment by fonsp** [comment]
Hi Jacob!

I am sorry to say that most of these points are because of Julia's built-in Markdown parser, which has a lot of strange quirks, and does not understand HTML syntax. (The Julia contributors have decided that Julia should not contain a full HTML parser - this would be too complex.)

But the quotes issue is on the Pluto end! We haven't written a CSS rule for it yet.

**Comment by TheCedarPrince** [comment]
That makes a lot of sense. Hmmm... 

### Regarding Comments

Is there anyway to get around the comments issue? Do you have any thoughts? My initial thought is something like this in the cell you are working on:

```
md"

Markdown Block 1

"

# I am a comment after Markdown Block 1!!!

md"

Markdown Block 2

"

...
```

The only problem with this sort of syntax is:

1. Feels like a Pluto anti-pattern
2. You need to use a begin/end statement to do this
3. When using the begin/end statement, only the second block is parsed.

Not sure what would be an elegant way to fix or workaround this. Thoughts?

### Regarding CSS Rule

If you point me in the right direction with the Pluto source code, I can start poking around with getting a good CSS rule made. Once I have a few done, I can report back to you. Then, we can make a PR and go from there. :)

**Comment by fonsp** [comment]
For comments:

```julia
md"
Hello World!
$(#= Let me think... =#)
Woo!
"
```

Similarly, if you want HTML inside markdown:

```julia
md"""
Hello World!
$(html"<marguee>wow</marquee>")
Woo!
"""
```
(mind the number of quotes)

**Comment by fonsp** [comment]
For blockquotes:

The CSS rules for cell output are given here: [https://github.com/fonsp/Pluto.jl/blob/master/assets/editor.css#L47-L157](https://github.com/fonsp/Pluto.jl/blob/master/assets/editor.css#L47-L157)

Change the file and refresh :)

**Comment by TheCedarPrince** [comment]
Hey @fonsp , what do you think of how this looks?

![image](https://user-images.githubusercontent.com/29561456/83576283-62d58e80-a4ff-11ea-922a-431465be655d.png)

The quoted text below the Title is indented and on a very faint overlay that matches Pluto's base theme. If you think it is good, I will open a PR for you to review. :smile:

**Comment by fonsp** [comment]
This looks great!! Welcome to the project! 

Could you add a bit of padding? And experiment with rounded corners?

**Comment by fonsp** [comment]
How does it look when quoting a single sentence?

**Comment by TheCedarPrince** [comment]
Haha, thanks for having me @fonsp ! I'm happy to contribute where I can! :smile: 

Experimented with padding a bit more for a blockquote:

![image](https://user-images.githubusercontent.com/29561456/83584088-1a749b80-a514-11ea-975f-70853969c1f8.png)

Single line:

![image](https://user-images.githubusercontent.com/29561456/83584116-2eb89880-a514-11ea-8701-c173ef88a129.png)

---

Want me to open a PR on this?

**Comment by fonsp** [comment]
Perfect! Yes please

**Comment by TheCedarPrince** [comment]
You got it!

**Comment by TheCedarPrince** [comment]
You got it!
