### ISSUE TITLE
Document exporting to HTML / PDF from Julia

### ISSUE THREAD

**Issue by junglegobs** [fonsp/Pluto.jl#1376]
It's already possible to export notebooks as HTMl and PDFs, but for the life of me I can't figure out what command to use to do this from within Julia (instead of Pluto).

**Comment by Pangoraw** [comment]
I think you are supposed to use either:
 - [static-export-template](https://github.com/JuliaPluto/static-export-template) for HTML exports
 - [PlutoPDF.jl](https://github.com/JuliaPluto/PlutoPDF.jl) for PDF exports

Though I have not used them myself.

**Comment by junglegobs** [comment]
`static-export-template` is quite cryptic and is specific to GitHub it seems. Surely there is a function e.g. `export_to_html` that I can use?

**Comment by Pangoraw** [comment]
You're right, it is using [PlutoSliderServer.jl](https://github.com/JuliaPluto/PlutoSliderServer.jl) under the hood.
Looks like [`export_directory()`](https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/main/src/PlutoSliderServer.jl#L47-L71) is what you are looking for.

**Comment by junglegobs** [comment]
Cool it works. Out of interest why is `PlutoSliderServer.jl` required? Since it is possible to do this with just `Pluto.jl` graphically.

Also I guess it would be useful to have an example of how to export a notebook as HTML in `PlutoSliderServer.jl`?

**Comment by Pangoraw** [comment]
PlutoSliderServer contains the logic for opening and manipulating notebooks without a browser but it uses Pluto under the hood to generate the HTML. For the PDF, there is a need for a HTML to PDF converter so the code using this is in PlutoPDF.

**Comment by fonsp** [comment]
Use `PlutoSliderServer.export_notebook(path::String)` to export a notebook to HTML. 🌈
