### ISSUE TITLE
Package not automatically installed

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#1381]
I'm running [c3e4b0f8] Pluto v0.15.1. Pluto's new package manager per notebook feature has been working well up until this afternoon when I was shown this error:

<img width="740" alt="Screen Shot 2021-08-09 at 3 10 11 PM" src="https://user-images.githubusercontent.com/226872/128780813-7713503f-01c8-4706-b6b5-50467481a41d.png">

Shouldn't Pluto be automagically handling this? This exact notebook worked fine a few days ago.

**Comment by samuela** [comment]
Restarting Pluto seems to make the problem go away.

**Comment by fonsp** [comment]
Oops! Send us the notebook file if it happens again, or try to find a way for us to reproduce it. Closing for now...
