### ISSUE TITLE
method declarations don't follow rective order

### ISSUE THREAD

**Issue by drdozer** [fonsp/Pluto.jl#1384]
Create cells as follows:

greet(i::Int) = "Hi"

greet(4)
<output>HI

greet("Bob")
<method error>

OK, all so good so far. Now I add a cell below this:

greet(s::String) = "Hi $s"

What now happens is that the notebook re-evaluates, and the previous cell that had a method error now completes successfully. The cell I added below and after has affected an older, higher-up cell.

**Comment by fonsp** [comment]
That sounds great! What is the issue?
