### ISSUE TITLE
Failing to display DataFrame() output

### ISSUE THREAD

**Issue by anuraag94** [fonsp/Pluto.jl#1385]
I have a Pluto notebook where I'm running a simulation, and the output is in the form of a dataframe from the Julia package DataFrames. However, I only see this blank field as output. 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/6537752/129077134-00a29e9c-405a-4cbf-8309-5cf1a36f1b91.png">

My output does print as expected in a Jupyter notebook. If DataFrame output is currently unsupported, are there plans to bring it to Pluto? If not, what would be a good workaround for me?

**Comment by fonsp** [comment]
Could it be that the table is empty? Can you use the `Text` function to compare it to plaintext output?
