### ISSUE TITLE
Ability to Use Custom Style Sheet for Cell Formatting

### ISSUE THREAD

**Issue by TheCedarPrince** [fonsp/Pluto.jl#139]
I realized that I think it might be somewhat trivial to add an option for a user to add their own style sheet for the layout of Pluto.

I was thinking about implementing such that you could run it like this: 

```julia
using Pluto

Pluto.run(1234, stylesheet="my_custom_stylesheet.css")
```

If nothing is provided, the default is to use the built in stylesheet. Thoughts on this as a new feature to add?

**Comment by fonsp** [comment]
#2

**Comment by fonsp** [comment]
I mentioned your suggestion in the other issue :)
