### ISSUE TITLE
Pluto reactivity doesn't work with blocks containing latexify (Latexify.jl)

### ISSUE THREAD

**Issue by ghralima** [fonsp/Pluto.jl#1399]
Pluto reactivity doesn't work with blocks containing latexify (from Latexify.jl package). For example, you define a variable in one block:

```julia
t = 10
```

Then call latexify in another block:
```julia
latexify(:(x = $t))
```
It works, but when you change the value of t in the other block, the block containing _latexify_ doesn't update automatically. You have to rerun it manually. 

I'm not sure if it's a problem in Latexify.jl or with Pluto.jl.

**Comment by Pangoraw** [comment]
This is a problem with Pluto, see #1001 (closing because of duplicate).
