### ISSUE TITLE
Pluto: how to run a simple JuMP model?

### ISSUE THREAD

**Issue by VivaldoMendes** [fonsp/Pluto.jl#1401]
Hi all,

To my surprise, I tried to run a simple optimization problem framed in JuMP syntax and got a strange error. 

```
cannot assign a value to variable workspace5.z1 from module workspace11
	1. macro expansion    @   macros.jl:149[inlined]
	2. top-level scope    @   Local: 3
```

Is it the case that Pluto can not run code that has macros in it?  There are many vital Julia packages with their syntax depending on the use of macros that such a limitation looks more structural than circumstantial.

I am using Pluto v0.15.1, PlutoUI v0.7.9, Julia 1.6.2. The following problem runs in VSCode, Atom and Jupyter:

```
begin
	m1 = Model(Ipopt.Optimizer)
	@variable(m1, z1)
	@variable(m1, z2)
	@variable(m1, z3)

	@objective(m1, Min, z1^2 + 0.5*z2^2 + 0.4*z3^2)

	@constraint(m1, cons1b, 0.5*z1 + z2 == 10)
	@constraint(m1, cons1c, 0.5*z1 + z3 == 20)
end
```
Help will be very much appreciated. Thanks.

![a](https://user-images.githubusercontent.com/48516539/130052654-5cb8ba53-c448-48bf-9c2e-7e154b735cf8.png)

**Comment by Pangoraw** [comment]
Support for macros is enabled in the main branch of Pluto and not part of a release yet. You can try it by running `] add Pluto#main` in the Pkg repl instead of just adding `Pluto`. If things don't work on `main` please report any issue you have.

**Comment by VivaldoMendes** [comment]
Thank you for the help provided. 

Unfortunately, that will not be a viable solution in my case. The Pluto notebooks I have are for teaching economics to undergrad students. I can not arrive there with Pluto notebooks (which is already quite something, I guarantee you) and tell students, "oh,  let's work on `main`, because ...". Pluto is a brilliant piece of software. However, if it can not deal with a fundamental part of Julia, it will be abandoned. I will teach a postgrad course later, but I will have to stick to my old Jupyter notebooks.

I never suspected that something that works on Jupyter exceptionally well (a simple JuMP script), could not work on Pluto. I had a taste of this problem with a PGFPlotsX file in the past. I managed to produce one plot with a macro, but the macro problem popped up when the second plot was called. In the case of PGFPlotsX, there are alternatives. However, in the case of JuMP, there are not, like in many other cases in the Julia world.

Here is an example of using PGFPlotsX and getting a stupid error by having a simple macro inside the code: 

```
grid, ylabel, height, title, xlabel, width
```
are keywords of the @pgf macro, they are not definitions of anything.

![a0](https://user-images.githubusercontent.com/48516539/130061066-9b459c4b-6b86-43f7-95c3-30a57b28ea82.png)

**Comment by mcabbott** [comment]
> it will be abandoned

Easy on the hyperbole. Pluto is young and while it's pretty neat for many things, it might not yet everything to all people. It's actually a pretty hard problem to make it understand macros, and Paul is the guy who figured it out & did the work.

There might be a release date planned, you could ask nicely if there is a timeline.

There are also other hacks people used to get some macros to work without error, before this new feature. If you only have a few, these might be enough, for now.

**Comment by VivaldoMendes** [comment]
Thanks for your comments. I am not a professional programmer. I use Julia because I find it incommensurably better than Matlab (my long-time companion), and I use it for teaching and research.  This macro thing surprised me because I was not expecting that some simple script that runs OK in all IDEs (I have used) does not work in Pluto. Besides that, in a reply from Oscar Dowson, he mentioned that, even if this macro problem is solved, the workflow of JuMP does not flow well in Pluto. I will have an entire course that depends 100% on constrained optimization. As you mention, at the current time, Pluto is not the solution to all problems. My naivety thought otherwise.

**Comment by VivaldoMendes** [comment]
In the end, I managed to run the simple JuPM model described above inside Pluto. 

With the help of @disberd, [here](https://discourse.julialang.org/t/announcing-neptune-jl-now-updated-to-multi-line-cells/54088/95), a complete solution as provided by using VSCode, Atom, or Jupyter can be found in that link.

**Comment by VivaldoMendes** [comment]
Sorry for coming back with a macro problem again. 

After working with macros in JuMP and having no problems, in the end, I was now using Symbolics and ModelingToolkit and was surprised. The macro `@parameters` shows no problems in the case of ModelingToolkit, but I get an error in the case `@variables`, which is a macro also used in Symbolics. 

Am I missing something, or is there a way around this problem with @variables? I am using ModelingToolkit v6.4.2, Symbolics v 3.1.0, Julia 1.6.2. Thanks. 

MWE:

```
@variables t x y 
```

thows out:

```
LoadError: UndefVarError: @variables not defined
```

**Comment by holomorphism** [comment]
@VivaldoMendes This does not seem to be a Pluto's problem. I tried it with REPL and got the same error.

In REPL, I get the following warning. It may be confusing that Pluto does not show this warning. (I think the warning is shown on the terminal screen where you started Pluto):

```
julia> using JuMP

julia> using Symbolics

julia> @variables x
WARNING: both Symbolics and JuMP export "@variables"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: @variables not defined
in expression starting at REPL[3]:1
```

I was able to use the `@variables` macro by loading Symbolics.jl as follows.
(If you want to use JuMP's `@variables` in the same notebook, you can "qualify" it as `JuMP.@variables`)

```julia
using Symbolics: @variables
```
![](https://user-images.githubusercontent.com/3076585/130308361-c0fd657a-7014-406d-85ad-f576c66aa935.png)

**Comment by VivaldoMendes** [comment]
Thank you for helping. Excellent solution.

I had used Symbolics and ModelingToolkit in VSCode and Jupyter and had no problems with macros there. I have just tried the REPL, and they work as well.  Please find the example below. 

I am working with the latest versions of ModelingToolkit, Symbolics, and Julia, so maybe this may explain the different outcomes we get. In my case, in the REPL, using the two packages simultaneously, there seems to exist no conflict between them in the case of the macro `@variables`, which both use. Thanks.


![a](https://user-images.githubusercontent.com/48516539/130320078-1cf97033-96a8-47fc-8af3-08d7439830d8.png)

**Comment by VivaldoMendes** [comment]
@holomorphism, 

Sorry, you are right in the case of using JuMP and Symbolics simultaneously. That conflict does indeed appear in my REPL as well. We can avoid using the macro `@variables` in JuMP (I have used `@variable` instead) so that conflict never pops up. My concern was the macro `@variables` in both ModelingToolkit and Symbolics. I will try your solution, which seems to work.
