### ISSUE TITLE
Functions defined with docstrings are not reactive (regression in #main from 0.15.1)

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1402]
I just noticed that on the `main` branch, if one defines a function with a docstring, the function does not seem to be correctly registered among the cell definitions, and hence the reactivity between that function definition and the cells using that function is lost.

This can also be seen from the html on the left where `test1` is listed as definition immediately after the first cell, while `test2` is not in the second cell

![7c9ef307-0f07-4b64-86ed-ce1315c03142](https://user-images.githubusercontent.com/12846528/130088090-d79758bf-f8c8-466c-b7d8-244cc7c45aed.gif)

I tried using the registered 0.15.1 version and the problem didn't seem to be present there.

**Comment by fonsp** [comment]
@Pangoraw I expect that this is caused by macro expansion, docstrings are interally stored as a `@doc` macro call.
