### ISSUE TITLE
Hosted HTML of Pluto 0.15.1 does not render

### ISSUE THREAD

**Issue by jakobnissen** [fonsp/Pluto.jl#1405]
I made a static HTML of a notebook using Pluto 0.12.21 and put it on the web. It works fine.
I then made small changes to the same notebook and re-rendered it as static HTML using Pluto 0.15.1. Now it does not render.
Both notebooks renders on my own computer.

Here is a link to the old website: https://viralinstruction.com/posts/hardware/
Here is a link to the new website: https://viralinstruction.com/posts/test/
Here are the two notebooks: https://github.com/jakobnissen/jakobnissen.github.io/tree/master/posts

It may be related to #1191

**Comment by jakobnissen** [comment]
It reproduces with every notebook. I updated the page (in the GitHub link in OP) to include "novel" and "ground" - two nearly empty notebooks with the same behaviour.

When opening the larger, also dysfunctional `test`, my Firefox console displays this:
![image](https://user-images.githubusercontent.com/23193950/131250419-957804db-d426-4b0d-b7bb-c42c55baebef.png)

A user on the Julia Slack suggested:
> looks like there's no semicolons between statements in index for some reason, you could try adding them manually

I.e. adding semicolons in between statements such as:
```
window.pluto_disable_ui = true
window.pluto_slider_server_url = undefined
```

I don't know if there is any more information I can provide.

**Comment by fonsp** [comment]
@jakobnissen Are you on Windows? Can you describe the steps you take to host the HTML file? (Did you copy-paste the contents into the GitHub web interface by any chance?)

**Comment by jakobnissen** [comment]
I'm on Linux. My page is being generated with Franklin. I don't know much about webpages or anything like that, so maybe I'm doing something wrong! Here are the steps:
* Open Pluto v. 0.15.1
* Add any content (say, a cell with `1+1`)
* Save as HTML (say, `test.html`)
* Copy the HTML file (not the contents, but the file) into the `posts` directory of the Franklin top level dir
* Push to GitHub, where the page gets deployed
* This then creates a page called `test`, which appears empty

Doing the same steps with a page generated with an older version of Pluto does not result in a blank page.

**Comment by fonsp** [comment]
@jakobnissen Can you try out https://github.com/fonsp/Pluto.jl/pull/1441 and let us know if it worked? Leave the current `test.html` on your website for us to test.

**Comment by jakobnissen** [comment]
Yep, that works! Thanks! I'll keep `test.html` up if you need it, but remove the rest

**Comment by botchkoAI** [comment]
it worked for me as well
