### ISSUE TITLE
how to serve pluto notebook behind an ingress controller on a relative path

### ISSUE THREAD

**Issue by sdeoras** [fonsp/Pluto.jl#1412]
Hi, this is a question and not a bug. I am putting together Kubernetes manifests to serve `Pluto` notebook and things are working fine when deployed and exposed as a service.

```
└─ $ ▶ kubectl --namespace=julia-system get deployments,pods,svc,ingresses.networking.k8s.io 
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/julia   1/1     1            1           49m

NAME                         READY   STATUS    RESTARTS   AGE
pod/julia-64c4697fcf-wxfpq   1/1     Running   0          49m

NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/julia   ClusterIP   10.97.160.178   <none>        80/TCP    49m

NAME                              CLASS   HOSTS   ADDRESS         PORTS   AGE
ingress.networking.k8s.io/julia   nginx   *       10.100.98.121   80      17m
```
However, when the notebook is accessed via ingress controller on a relative path `/julia`, the notebook rendering fails. I am wondering if there are ways to configure it to serve behind a relative path? Are there other ways to achieve the same?

**Comment by fonsp** [comment]
I am definitely missing a lot of context, but my first guess is that you should use a URL that ends with a `/`. Pluto will use relative URLs to redirect you to the notebook page, and `/julia` would get redirected to `/edit?id=...` when you open a notebook. `/julia/` would redirect to `/julia/edit?id=...`, which is probably what you want.

Also take a look at https://github.com/fonsp/Pluto.jl/discussions/1084

**Comment by sdeoras** [comment]
@fonsp yup, with a URL ending in `/` everything works, however, I have other services behind the ingress and am looking to make URL `/pluto` be the root url for the pluto notebook.

**Comment by fonsp** [comment]
Alright! I will close this since it seems too specific to work on further, but feel free to work on documentation improvements or a PR!
