### ISSUE TITLE
`publish_to_js` could return object printable as `text/javascript`

### ISSUE THREAD

**Issue by clarkevans** [fonsp/Pluto.jl#1413]
Currently, `publish_to_js` returns a string value.  However, HypertextLiteral (and other display systems) don't know that the object is actually properly formatted JavaScript.  Consider returning a `JavaScript` value instead, much like `HTML`.  This approach would then let you test if an object is `showable` as `text/javascript` if one implements `Base.show(io::IO, ::MIME"text/javascript", js::JavaScript)`.  The `HypertextLiteral` code that makes this work is a [generated function](https://github.com/MechanicalRabbit/HypertextLiteral.jl/blob/master/src/script.jl#L98-L104).  Note this data type shouldn't be a subtype of `AbstractString` (`HTML` isn't a subtype of `AbstractString`).

**Comment by dralletje** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/cc219fdfe21eafc046218a4390608bb2733577cb
