### ISSUE TITLE
PyPlot.jl and `imshow`

### ISSUE THREAD

**Issue by roflmaostc** [fonsp/Pluto.jl#1422]
Hey,

I've seen that `PyPlot.jl` in general works, but in Pluto nothing really happens for:

```julia
begin
	using PyPlot
	PyPlot.imshow(randn((3,3)))
end
```
Only some output:
```julia
PyObject <matplotlib.image.AxesImage object at 0x7f08ddf99700>
```

In the REPL that pops-up an external, interactive viewer. In Jupyter it is within the browser, but I would be happy to have it externally.

Thanks a lot,

Felix

Setup:
* PyPlot v2.9.0
* Pluto v0.15.1

**Comment by fonsp** [comment]
Can you report this to PyPlot.jl instead? Feel free to get in touch if you have a specific question or issue.

**Comment by diegozea** [comment]
Hi! 

This is a workaround in case someone needs it:

```julia
import PyPlot

begin
	PyPlot.figure()
	PyPlot.imshow(randn((3,3)))
	PyPlot.gcf()
end
```

Best!
