### ISSUE TITLE
Got UndefVarError: table_data not defined errors when using StringParserPEG

### ISSUE THREAD

**Issue by ysaereve** [fonsp/Pluto.jl#1423]
Got the following errors when using StringParserPEG:

Failed to show value:

UndefVarError: table_data not defined

show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:641
var"#sprint_withreturned#28"(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::StringParserPEG.Grammar)@PlutoRunner.jl:591
format_output_default(::Any, ::Any)@PlutoRunner.jl:515
#format_output#17@PlutoRunner.jl:532[inlined]
formatted_result_of(::Base.UUID, ::Bool, ::Nothing, ::Module)@PlutoRunner.jl:448
top-level scope@none:1

begin
	using StringParserPEG
	calc2 = Grammar("""
  start => (number & op & number){(r,v,f,l,c) -> c[2](c[1],c[3])}
  op => plus | minus
  number => (-(space) & r([0-9]+)r) {(r,v,f,l,c) -> parse(Int,c[1].value)}
  plus => (-(space) & '+'){(a...) -> +}
  minus => (-(space) & '-'){(a...) -> -}
  space => r([ \\t\\n\\r]*)r
	""")
end

Environment:
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = atom  -a
  JULIA_REVISE_WORKER_ONLY = 1
nothing
Pluto Version 0.15.1
PlutoUI Version 0.7.9

**Comment by fonsp** [comment]
Can you post a small notebook that we can run to reproduce your problem?
