### ISSUE TITLE
Printing DataTables or making PDF Cuts off Rows at New Page

### ISSUE THREAD

**Issue by BrettKnoss** [fonsp/Pluto.jl#1428]
When i try to convert a Pluto notebook to PDF for printing, it places the description bars of dataframes on the earlier page, and doing so, cuts off several rows.

**Comment by fonsp** [comment]
Can you give an example notebook and PDF?

**Comment by BrettKnoss** [comment]
Is there a way to add photos?  i  have screenshots as samples.
