### ISSUE TITLE
Give more helpful error message when address is already in use

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#143]
```jl
julia> Pluto.run()
ERROR: IOError: listen: address already in use (EADDRINUSE)
```

It should tell me what to do, i.e. find an available address for me and give me the command to run -- or, better,  just automatically choose an available address and run that one.

**Comment by fonsp** [comment]
Right, thanks!

To anyone finding this issue in the meantime: try a different _port_, i.e. `Pluto.run(1235)`.

**Comment by fonsp** [comment]
How did you find this issue?

**Comment by fonsp** [comment]
Oh wait now I see what you mean - when you call `Pluto.run()` _without specifying a port_ it should play nicer.

**Comment by dpsanders** [comment]
Exactly. I had one session already running on 1234 and then tried to open another one from a new Julia session.

**Comment by TheCedarPrince** [comment]
Will do @fonsp - can you assign this to me?

@dpsanders, what version of Pluto were you running? Thanks!

**Comment by fonsp** [comment]
Happens on all versions
