### ISSUE TITLE
kf.coreaddons errors when starting Pluto

### ISSUE THREAD

**Issue by kimmolinna** [fonsp/Pluto.jl#1432]
When I start Pluto on the updated Kubuntu (21.04) I will get the following error messages: 
```
kf.coreaddons: no metadata found in "/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/applications.so" "Failed to extract plugin meta data from '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/applications.so'"
kf.coreaddons: no metadata found in "/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/desktop.so" "Failed to extract plugin meta data from '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/desktop.so'"
```
I don't know does this effect for a starting time of Pluto or not but It takes quite much time. Especially "waiting for api.github.com" take some time.

**Comment by fonsp** [comment]
What is the issue exactly?

**Comment by kimmolinna** [comment]
I'm not sure is it related to this but Pluto always opens Chrome and It's not otherwise my default browser. But I did some extra research and this (applications.so and desktop.so) seems to be KDE/Plasma problem.
