### ISSUE TITLE
Inline Markdown LaTeX causes scrollbar to appear

### ISSUE THREAD

**Issue by ctrekker** [fonsp/Pluto.jl#1435]
In certain browsers (Chrome, Edge, maybe others) a small scrollbar appears to the right of cells containing equations who's height is greater than the height of the surrounding text. For example, below I have a cell with two inline equations. When the equations are removed the scrollbar disappears.

![Screenshot 2021-09-01 104903](https://user-images.githubusercontent.com/22894011/131711407-253b0072-7efa-4fd6-8747-69da7d08bcab.jpg)

I also tested this notebook in Firefox and the scrollbar doesn't appear, as intended.

**Comment by holomorphism** [comment]
It seems that this problem has already been solved in PR #1328. Isn't it?

**Comment by ctrekker** [comment]
You're absolutely right, thanks for letting me know!
