### ISSUE TITLE
Some color emojis crash st terminal

### ISSUE THREAD

**Issue by jbrea** [fonsp/Pluto.jl#1437]
A colleague and I just spent quite a bit of time trying to figure out why Pluto 0.15.1 crashes the terminal without leaving an error message when opening a notebook that disables PlutoPkg. Turns out it was the broken heart emoji in the line `[ Info: Stopped using PlutoPkg` that the st terminal doesn't like. We learned that this is a known problem with st and there [is a fix for it](https://wiki.archlinux.org/title/St#Crashes_if_page_contains_emoji_characters), but I'm wondering if one couldn't just remove this broken heart emoji for increased stability with arbitrary terminals (unless it is absolutely indispensable ;-)).

**Comment by fonsp** [comment]
Thanks for going through the painful debugging process! It's fixed, and will be released in 0.15.2! 💕🌈
