### ISSUE TITLE
colors from `UnicodePlots.jl` `heatmap` do not display

### ISSUE THREAD

**Issue by SimonEnsemble** [fonsp/Pluto.jl#1442]
Pluto v0.15.1, Julia 1.6, Linux Mint.

```julia
using UnicodePlots
heatmap(collect(0:30) * collect(0:30)', xscale=0.1, yscale=0.1, xoffset=-1.5, colormap=:inferno)
```

gives in REPL:

![image](https://user-images.githubusercontent.com/30643894/132266078-42cab959-7e5e-4229-b9d9-6da83f04bd15.png)

but in Pluto.jl:

![image](https://user-images.githubusercontent.com/30643894/132266105-b98f7523-45db-45dd-bbc7-5773ec2c5461.png)

:eyes:

**Comment by SimonEnsemble** [comment]
related is https://github.com/fonsp/Pluto.jl/issues/870 
> (heatmap [in UnicodePlots.jl] also doesn't work, but for a different reason relating to color display and not alignment.)

**Comment by fonsp** [comment]
Thanks! This is due to https://github.com/fonsp/Pluto.jl/issues/894
