### ISSUE TITLE
Promise timed out

### ISSUE THREAD

**Issue by niltsz** [fonsp/Pluto.jl#1443]
I wanted to give a feedback using the instant feedback box, and I got the error message:

localhost:1234

Whoops, failed to send feedback 😢
We would really like to hear from you! Please got to https://github.com/fonsp/Pluto.jl/issues to report this failure:

Error: Promise timed out.

I sent the feedback again, and it worked.

**Comment by fonsp** [comment]
Sounds like a network issue, but I'm happy to hear that it worked the second time!
