### ISSUE TITLE
Release v0.15.2?

### ISSUE THREAD

**Issue by cscherrer** [fonsp/Pluto.jl#1448]
Hi, it's exciting that Pluto `main` now works with Soss (https://github.com/fonsp/Pluto.jl/issues/1438). Could you please tag a new release that includes this?

**Comment by fonsp** [comment]
Sorry for the slow releases, I have been enjoying my holiday :) 0.16.0 is coming very soon!

**Comment by cscherrer** [comment]
No worries, it's important to recharge. Glad to hear you're enjoying it.

Looking forward to 0.16, but definitely no emergency :)

**Comment by fonsp** [comment]
https://github.com/JuliaRegistries/General/pull/44603
