### ISSUE TITLE
Artifact downloads not showing in pkg terminal

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1451]
They show in the server terminal instead

![image](https://user-images.githubusercontent.com/6933510/132758587-25983ede-e898-4c47-8f1b-94639bb00233.png)

**Comment by Pangoraw** [comment]
Should be fixed in https://github.com/JuliaLang/Pkg.jl/commit/2496426f569f741fac26dbd67663f05cc382f7a4 :crossed_fingers:

**Comment by Pangoraw** [comment]
Ref: https://github.com/JuliaLang/Pkg.jl/pull/3051

**Comment by fonsp** [comment]
Thanks Paul! This was merged last month, so it should be fixed in the upcoming 1.8.6 and 1.9.0 releases.
