### ISSUE TITLE
GitHub's HTML preview broken by new export format?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#1453]
I used notebooks for a class last year (https://github.com/MikaelSlevinsky/MATH2160/tree/master/notebooks). Updating from Pluto v0.11.14 to v0.15.1 has broken the ability to view the exported HTML through GitHub's previewer:

- https://htmlpreview.github.io/?https://github.com/MikaelSlevinsky/MATH2160/blob/master/notebooks/Introduction.jl.html is broken
- https://htmlpreview.github.io/?https://github.com/MikaelSlevinsky/MATH2160/blob/master/notebooks/OrthogonalPolynomials.jl.html an example of how it used to work

**Comment by fonsp** [comment]
htmlpreview is no longer maintained, I submitted a PR to fix this bug but no luck: https://github.com/htmlpreview/htmlpreview.github.com/issues/102

Use https://htmlview.glitch.me/ instead (created by me).
