### ISSUE TITLE
Cell context menu is hidden behind Live Docs

### ISSUE THREAD

**Issue by lungben** [fonsp/Pluto.jl#1454]
When Live Docs is enabled, the cell context menu (opened by clicking on (...)) is partially hidden behind it, see screenshot.

![image](https://user-images.githubusercontent.com/52384612/132881284-b092d458-e7a8-402a-81df-12dd8d495ccb.png)

The cell context menu should be in the foreground.

**Comment by disberd** [comment]
I think this is a duplicate of https://github.com/fonsp/Pluto.jl/issues/1256

Unfortunately there doesn't seem to be a simple CSS solution without the need to restructure the elements layout in the page.
The problem is the way CSS stacking works as referenced by @fonsp in the original issue above

**Comment by lungben** [comment]
@disberd thanks for pointing this out - unfortunately I missed the original Issue in my search. 

Closing this one.
