### ISSUE TITLE
Importing package causes websocket error in hosted docker image

### ISSUE THREAD

**Issue by ctessum** [fonsp/Pluto.jl#1456]
Hello, I am getting kind of a strange error and I was wondering if there was any way I could get more information about what's going on so I can debug it. 

Basically, I am trying to run an instance of Pluto.jl inside of a docker container as a "workspace" in the PrairieLearn learning system (more information [here](https://prairielearn.readthedocs.io/en/latest/workspaces/)).

The docker container works fine by itself, just not inside of PrairieLearn, so I don't think there's any direct problem with Pluto itself or the docker container, however when I'm running it inside of PrairieLearn I get a websocket error whenever I try to import any package besides `PlutoUI`:

![Screen Shot 2021-09-10 at 6 37 04 PM](https://user-images.githubusercontent.com/6193153/132928159-df54b3cd-dff7-4564-89d6-55a2781dd1f6.png)

The Pluto logs inside of the docker image don't give any useful information:

```
Resolving package versions...
Updating `/tmp/jl_XEJ503/Project.toml`
[7f904dfe] + PlutoUI v0.7.9
Updating `/tmp/jl_XEJ503/Manifest.toml`
[682c06a0] + JSON v0.21.2
[69de0a69] + Parsers v2.0.3
```
...and so on.

The PrairieLearn logs give an error message but it's not especially useful:
```
error: Error proxying workspace request: Error: socket hang up {"err":{"code":"ECONNRESET"},"url":"/"}
error: Error proxying workspace request: Error: socket hang up {"err":{"code":"ECONNRESET"},"url":"/possible_binder_token_please"}
error: Error proxying workspace request: Error: connect ECONNREFUSED 192.168.65.2:41992 {"err":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.65.2","port":41992},"url":"/"}
```

Because it works when I run the docker container by itself I guess the error itself has something to do with the way that PrairieLearn runs the docker container, but I would really like to get a more detailed description of what is actually going on rather than "websocket error". Is there any way I can get it to output more information?

Thanks for any help you can give!

**Comment by fonsp** [comment]
Could it be that the problem is not just a networking error, but the container crashed completely when installing these packages? Maybe the package installation causes it to run out of storage/memory?

**Comment by ctessum** [comment]
You are right, the container is crashing. I guess the web UI can't be expected to give a more informative error message in that case, so I will close this. Thanks for your help!
