### ISSUE TITLE
println(..) goes to STD/IO not notebook

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#146]
Hi!

Is it just me, or does Pluto ignore IO?

When using Pkg.status() I assumed it is an issue of Pkg, but today I tried

     println(intermediateResult)

and it failed to show in the notebook, but showed in the shell where I started Pluto. So there seems to by a system in it.

Kind greetings from Hamburg,

Falko

**Comment by fonsp** [comment]
Ignoring IO is intended behavior 😊 (for now... #5). Also have a look at `Base.sprint`!

LG aus Berlin,
Fonsi

**Comment by zenon** [comment]
Ah.
Okay.
Hm. I have to think about that :-)

Enjoy the weekend!

**Comment by diegozea** [comment]
It would be great to see `stdout` and `stderr` without leaving the browser, at least for "debugging" with `println` & `@show`. I have imagined an element similar to *Live docs* at the left/rigth border of the screen.
