### ISSUE TITLE
@eval and using

### ISSUE THREAD

**Issue by markNZed** [fonsp/Pluto.jl#1463]
I tried the following code
```
        import Pkg
	Pkg.activate() 
	# this replaces the deprecated Pkg.installed()
	isinstalled(pkg::String) = any(x -> x.name == pkg && x.is_direct_dep, values(Pkg.dependencies()))
	packages = [:Revise, :PlutoUI, :StatsPlots]
	for p in packages; isinstalled(String(p)) || Pkg.add(p); end
	# This does not work and I don't know why
	for p in packages; @eval using $p; end 
```
The eval above does not seem to work in the context of Pluto but works in REPL. I needed to explicitly "using Revise" etc in Pluto. Is there a way to use the array of symbols to automate the calls to using?

**Comment by fonsp** [comment]
This type of syntax is not supported in Pluto. Be sure to try out Pluto's built-in package manager: https://www.youtube.com/watch?v=HiI4jgDyDhY

**Comment by markNZed** [comment]
I would like to use the built-in package manager but this does not seem to work with packages in dev :(

**Comment by fonsp** [comment]
I see! Take a look at https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#advanced-set-up-an-environment-with-pkgactivate
