### ISSUE TITLE
ugly highlighting over `@`

### ISSUE THREAD

**Issue by lmiq** [fonsp/Pluto.jl#1465]
This is Pluto 0.16.0 on Firefox. When using `@.` I get a a red highlighting over the `@` which is quite ugly:

![image](https://user-images.githubusercontent.com/31046348/133299296-631ea744-5dd7-4849-b257-bf23e3ca0d01.png)

Is this intentional?

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/854
