### ISSUE TITLE
Code completions suggestion contains duplicates

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#1467]
<img width="283" alt="Screen Shot 2021-09-16 at 4 17 57 PM" src="https://user-images.githubusercontent.com/226872/133697569-64f1d93f-8a11-46e3-8d11-a955ef402a8e.png">

I'm not sure what the intended behavior is here exactly, but it seems confusing IMHO.

**Comment by fonsp** [comment]
@aviatesk What do you think?

**Comment by dralletje** [comment]
I _think_ it should be fixed now, but let me know if it isn't
