### ISSUE TITLE
`PlutoTest.@test` does not show reactivity with Pluto 16.0

### ISSUE THREAD

**Issue by roflmaostc** [fonsp/Pluto.jl#1469]
Hey,

playing around with Pluto 16.0 (including 3f4d92f4aaa9eff20591114396499c93357a5d44) and [PlutoTest](https://github.com/JuliaPluto/PlutoTest.jl) there are some issues with reactivity.
Pluto 15.1 works fine.
For 16.0 it doesn't update the tests:
[See here](https://imgur.com/a/XwntCkp)

If it's related to the existing macro issues, feel free to close!

Thanks,

Felix

**Comment by fonsp** [comment]
Thanks for pointing this out! Fixed in PlutoTest 0.1.1: https://github.com/JuliaPluto/PlutoTest.jl/commit/6eb0ddd6e0c9148954523430cd1c110aa8759f48
