### ISSUE TITLE
install issue (almost sure that's just my problem)

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#147]
Hi Fons,

I mentioned an installation issue on a computer where I don't have admin right. It might even be a firewall issue or something. Seems it (who? Julia?) can't connect to or download from GitHub.

So, I don't expect that it is you who can help here.
(Beside switching to an all Julia stack, that is :-) )
Feel free to close it.

Kind greetings, Falko

```
(plutoJL2) pkg> build Pluto
  Building MbedTLS → `C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.log`
┌ Error: Error building `MbedTLS`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr\downloads\Mb
edTLS.v2.16.0.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps
\usr\downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:619
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ in expression starting at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:44
│ caused by [exception 1]
│
│ Stacktrace:
│  [1] error() at .\error.jl:42
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:613
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ Ausnahme beim Festlegen von "SecurityProtocol": "NULL kann aufgrund von ung�ltigen Enumerationswerten nicht in den Typ "System.Net.SecurityProtocolType" konvertiert werden. Geben Sie einen der folgenden
E
│ numerationswerte an, und versuchen Sie es erneut. M�gliche Enumerationswerte sind "Ssl3, Tls"."
│ Bei Zeile:1 Zeichen:35
│ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
│     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
│     + FullyQualifiedErrorId : PropertyAssignmentException
│
│ Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden.."
│ Bei Zeile:7 Zeichen:24
│ + $webclient.DownloadFile <<<< ("https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz", "C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr
\
│ downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz")
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : DotNetMethodException
│
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

**Comment by fonsp** [comment]
What commands did you run before this? Was it:
```
(v1.2) Pkg > activate "an_empty_directory"
(v1.2) Pkg > add Pluto
```

This is [an open issue with Pkg](https://github.com/JuliaLang/Pkg.jl/issues/1847), so it would be great if you could find the steps to reproduce it and post it there! :)

**Comment by zenon** [comment]
Interesting, yes looks like the Pkg issue!

Complete log:


(v1.2) pkg> activate "."
Activating new environment at `C:\test\Project.toml`

(plutoJL2) pkg> add Pluto
  Updating registry at `C:\Users\zenon\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating git-repo `https://github.com/JuliaData/Parsers.jl.git`
 Installed Parsers ──────── v1.0.4
  Updating git-repo `https://github.com/JuliaWeb/HTTP.jl.git`
 Installed HTTP ─────────── v0.8.15
   Cloning [c3e4b0f8-55cb-11ea-2926-15256bba5781] Pluto from https://github.com/fonsp/Pluto.jl.git
 Installed Pluto ────────── v0.9.3
  Updating git-repo `https://github.com/JuliaPackaging/BinaryProvider.jl.git`
 Installed BinaryProvider ─ v0.5.10
  Updating `C:\test\Project.toml`
  [c3e4b0f8] + Pluto v0.9.3
  Updating `C:\test\Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.10
  [cd3eb016] + HTTP v0.8.15
  [83e8ac13] + IniFile v0.5.0
  [682c06a0] + JSON v0.21.0
  [739be429] + MbedTLS v0.7.0
  [69de0a69] + Parsers v1.0.4
  [c3e4b0f8] + Pluto v0.9.3
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

Ξ using Pluto
[ Info: Precompiling Pluto [c3e4b0f8-55cb-11ea-2926-15256bba5781]
┌ Info:
│     Welcome to Pluto v0.9.3 �
│     Start a notebook server using:
│
│   julia> Pluto.run(1234)
│
│     Have a look at the FAQ:
│     https://github.com/fonsp/Pluto.jl/wiki
└
ERROR: LoadError: MbedTLS not installed properly, run Pkg.build("MbedTLS"), restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\src\MbedTLS.jl:43
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:432
 [9] top-level scope at .\none:3
in expression starting at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\src\MbedTLS.jl:42
ERROR: LoadError: LoadError: Failed to precompile MbedTLS [739be429-bea8-5141-9913-cc70e7f3736d] to C:\Users\zenon\.julia\compiled\v1.2\MbedTLS\bf9T0.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include at .\Base.jl:31 [inlined]
 [9] include(::String) at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:1
 [10] top-level scope at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:18
 [11] include at .\boot.jl:328 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1094
 [13] include(::Module, ::String) at .\Base.jl:31
 [14] top-level scope at none:2
 [15] eval at .\boot.jl:330 [inlined]
 [16] eval(::Expr) at .\client.jl:432
 [17] top-level scope at .\none:3
in expression starting at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\IOExtras.jl:11
in expression starting at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:18
ERROR: LoadError: LoadError: Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to C:\Users\zenon\.julia\compiled\v1.2\HTTP\zXWya.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include at .\Base.jl:31 [inlined]
 [9] include(::String) at C:\Users\zenon\.julia\packages\Pluto\xXDxM\src\Pluto.jl:1
 [10] top-level scope at C:\Users\zenon\.julia\packages\Pluto\xXDxM\src\Pluto.jl:43
 [11] include at .\boot.jl:328 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1094
 [13] include(::Module, ::String) at .\Base.jl:31
 [14] top-level scope at none:2
 [15] eval at .\boot.jl:330 [inlined]
 [16] eval(::Expr) at .\client.jl:432
 [17] top-level scope at .\none:3
in expression starting at C:\Users\zenon\.julia\packages\Pluto\xXDxM\src\webserver\WebServer.jl:3
in expression starting at C:\Users\zenon\.julia\packages\Pluto\xXDxM\src\Pluto.jl:43
ERROR: Failed to precompile Pluto [c3e4b0f8-55cb-11ea-2926-15256bba5781] to C:\Users\zenon\.julia\compiled\v1.2\Pluto\OJqMt.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906

**Comment by fonsp** [comment]
So the error should be when you do this:

```
dos> create an empty directory

dos> cd "my-empty-dir"

dos> julia

julia> ]

(v1.2) Pkg > activate "."

(my-empty-dir) Pkg> status

# should be empty

(my-empty-dir) Pkg> add HTTP

julia> import HTTP

# this should give an error

```

Could you do those steps, and post the full terminal output here?

**Comment by zenon** [comment]
C:\test>mkdir xx

C:\test>cd xx

C:\test\xx>..\j.cmd
(v1.2) pkg> activate "."
Activating new environment at `C:\test\xx\Project.toml`

(xx) pkg> status
    Status `C:\test\xx\Project.toml`
  (empty environment)

(xx) pkg> add HTTP
  Updating registry at `C:\Users\zenon\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Some registries failed to update:
│     — C:\Users\zenon\.julia\registries\General — failed to fetch from repo
└ @ Pkg.Types C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\Types.jl:1171
 Resolving package versions...
  Updating `C:\test\xx\Project.toml`
  [cd3eb016] + HTTP v0.8.15
  Updating `C:\test\xx\Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.10
  [cd3eb016] + HTTP v0.8.15
  [83e8ac13] + IniFile v0.5.0
  [739be429] + MbedTLS v0.7.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [de0858da] + Printf
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [4ec0a83e] + Unicode

Ξ using HTTP
[ Info: Precompiling HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3]
ERROR: LoadError: MbedTLS not installed properly, run Pkg.build("MbedTLS"), restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\src\MbedTLS.jl:43
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include(::Module, ::String) at .\Base.jl:31
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:330 [inlined]
 [8] eval(::Expr) at .\client.jl:432
 [9] top-level scope at .\none:3
in expression starting at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\src\MbedTLS.jl:42
ERROR: LoadError: LoadError: Failed to precompile MbedTLS [739be429-bea8-5141-9913-cc70e7f3736d] to C:\Users\zenon\.julia\compiled\v1.2\MbedTLS\bf9T0.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1094
 [8] include at .\Base.jl:31 [inlined]
 [9] include(::String) at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:1
 [10] top-level scope at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:18
 [11] include at .\boot.jl:328 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1094
 [13] include(::Module, ::String) at .\Base.jl:31
 [14] top-level scope at none:2
 [15] eval at .\boot.jl:330 [inlined]
 [16] eval(::Expr) at .\client.jl:432
 [17] top-level scope at .\none:3
in expression starting at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\IOExtras.jl:11
in expression starting at C:\Users\zenon\.julia\packages\HTTP\BOJmV\src\HTTP.jl:18
ERROR: Failed to precompile HTTP [cd3eb016-35fb-5094-929b-558a96fad6f3] to C:\Users\zenon\.julia\compiled\v1.2\HTTP\zXWya.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906

Ξ

**Comment by zenon** [comment]
btw. I'm can't promise any responsiveness in the next 60 hours :-)

Greetings from Hamburg, f.

**Comment by zenon** [comment]
Ah. I should add:
That's Windows 7 & Julia 1.2.

**Comment by fonsp** [comment]
That's another error 😥

**Comment by fonsp** [comment]
could you do
```
(xx) Pkg> build MbedTLS 
```

**Comment by zenon** [comment]
A I love diversity.
Good Night nevertheless. :-)

**Comment by zenon** [comment]
(xx) pkg> build MbedTLS
  Building MbedTLS → `C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.log`
┌ Error: Error building `MbedTLS`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr\downloads\Mb
edTLS.v2.16.0.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz to C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps
\usr\downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:619
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ in expression starting at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:44
│ caused by [exception 1]
│
│ Stacktrace:
│  [1] error() at .\error.jl:42
│  [2] #download#100(::Bool, ::typeof(BinaryProvider.download), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:613
│  [3] #download at .\none:0 [inlined]
│  [4] #download_verify#101(::Bool, ::Bool, ::Bool, ::typeof(download_verify), ::String, ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\PlatformEngines.jl:688
│  [5] #download_verify at .\tuple.jl:0 [inlined]
│  [6] #install#141(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::typeof(install), ::String, ::String) at C:\Users\zenon\.julia\packages\BinaryProvider\U2dKK\src\Prefix.jl:314
│  [7] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at .\tuple.jl:0
│  [8] top-level scope at C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\build.jl:48
│  [9] include at .\boot.jl:328 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1094
│  [11] include(::Module, ::String) at .\Base.jl:31
│  [12] include(::String) at .\client.jl:431
│  [13] top-level scope at none:5
│ Ausnahme beim Festlegen von "SecurityProtocol": "NULL kann aufgrund von ung�ltigen Enumerationswerten nicht in den Typ "System.Net.SecurityProtocolType" konvertiert werden. Geben Sie einen der folgenden
E
│ numerationswerte an, und versuchen Sie es erneut. M�gliche Enumerationswerte sind "Ssl3, Tls"."
│ Bei Zeile:1 Zeichen:35
│ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
│     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
│     + FullyQualifiedErrorId : PropertyAssignmentException
│
│ Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Die Verbindung mit dem Remoteserver kann nicht hergestellt werden."
│ Bei Zeile:7 Zeichen:24
│ + $webclient.DownloadFile <<<< ("https://github.com/JuliaWeb/MbedTLSBuilder/releases/download/v0.17.0/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz", "C:\Users\zenon\.julia\packages\MbedTLS\a1JFn\deps\usr
\
│ downloads\MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz")
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : DotNetMethodException
│
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

(xx) pkg>

**Comment by zenon** [comment]
and off

**Comment by fonsp** [comment]
Thanks! Ciao

**Comment by fonsp** [comment]
I've reported this with Pkg. ([linky link](https://github.com/JuliaLang/Pkg.jl/issues/1847))

**Comment by fonsp** [comment]
Here's the solution: https://github.com/JuliaLang/Pkg.jl/issues/1847#issuecomment-649873449
