### ISSUE TITLE
Adding a `using` does not re-evaluate cells that use imported names

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#1473]
1. 
![image](https://user-images.githubusercontent.com/4170948/133907241-0e5e7745-d633-467c-a7c0-b8bf3bc6f6da.png)

2. adding `using Statistics`
![image](https://user-images.githubusercontent.com/4170948/133907249-529aa7fd-edd2-43c4-9914-d1b29900f058.png)

The cell referencing `mean` is not automatically re-evaluated.
This is easily fixed by running it manually in this example, but it becomes more annoying when the error is deep in a stack trace and triggered conditioned on some UI elements.

**Comment by fonsp** [comment]
#24
