### ISSUE TITLE
Pasting multiline string  with `julia>` is broken

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1479]
If you paste this docstring into a pluto cell:

https://github.com/Jutho/RationalRoots.jl/blob/456730550ea5ebfda7587e6b8e1bf39a7d44daff/src/RationalRoots.jl#L26-L46

(including the `"""`)

then the result is:

![Schermafbeelding 2021-09-21 om 15 01 44](https://user-images.githubusercontent.com/6933510/134175121-cb02c561-9d91-4a39-a0fb-76576d87fe0a.png)

**Comment by dralletje** [comment]
This would be a perfect thing for `julia>` support in @lezer/julia 😎

**Comment by dralletje** [comment]
Fixed by https://github.com/fonsp/Pluto.jl/commit/863fb9e7ef08f130221d310e178e089153b10a6e
