### ISSUE TITLE
Symbolics.jl complex numbers don't show up as latex output

### ISSUE THREAD

**Issue by vini-fda** [fonsp/Pluto.jl#1486]
I'm posting this issue here because I don't think the issue is on Symbolics.jl end, but I might be mistaken. Anyways, most expressions in Symbolics.jl are "prettified" into LaTeX output in the pluto notebook, except those involving complex numbers. 

Screenshot of the output:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/20410205/134449848-78f0fe99-55b6-4ddb-a9a3-51f4920d88f2.png">

For reference, this is what the output of `z2` should look like:
<img width="133" alt="image" src="https://user-images.githubusercontent.com/20410205/134449607-aec91edd-8beb-495d-8a9d-0a83f5de33d5.png">

**Comment by fonsp** [comment]
How did you generate the second image?

**Comment by fonsp** [comment]
How did you report the last image? Perhaps you should report this to Symbolics.jl instead?

**Comment by vini-fda** [comment]
I think you're correct. My bad. For clarification: the last image was just created in latex, not using Julia. But it's more likely that the problem is on Symbolics.jl's end, because it also doesn't work on Jupyter Notebook.
