### ISSUE TITLE
Can't select multiple lines

### ISSUE THREAD

**Issue by dralletje** [fonsp/Pluto.jl#1492]
Well you can... you just can't start on text:

https://user-images.githubusercontent.com/767261/134527818-ef6855c2-08a5-4cfb-b099-7cad9c1564a8.mov

This is a problem with Codemirror itself (as you can see, I'm on the Codemirror homepage), but adding it here to keep track of it.

**Comment by fonsp** [comment]
Post to codemirror?

**Comment by dralletje** [comment]
Yeh

**Comment by fonsp** [comment]
Will you?

**Comment by dralletje** [comment]
Yes

**Comment by fonsp** [comment]
Noice
