### ISSUE TITLE
Using Pluto offline

### ISSUE THREAD

**Issue by dorn-gerhard** [fonsp/Pluto.jl#1497]
In order to start the browser view of Pluto, it needs to load some scripts (I use private browser mode in firefox not saving any cookie or script by default)
(e.g. 
"https://cdn.jsdelivr.net/npm/@observablehq/stdlib@3.3.1/dist/stdlib.js"
"https://cdn.jsdelivr.net/npm/codemirror@5.60.0/lib/codemirror.min.js"
"https://cdn.jsdelivr.net/npm/codemirror@5.60.0/addon/hint/show-hint.min.js"
"https://cdn.jsdelivr.net/npm/codemirror@5.60.0/addon/display/placeholder.min.js"

also a font has to be downloaded:
https://cdn.jsdelivr.net/gh/fonsp/Vollkorn-Typeface@1/fonts/woff2/Vollkorn-SemiBoldItalic.woff2
which fails if internet is not available. 

For some applications it would be useful to be able to start pluto offline (I am not sure if starting offline works if private browsing is deactivated)

**Comment by fonsp** [comment]
Hi! Take a look at #241 (and #1046 #1132 )
