### ISSUE TITLE
Safari on macOS doesn't load, but Firefox does

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#150]
On Safari macOS Catalina the Create new and Open Sample commands both lead to a window that never finishes loading. 

<img width="905" alt="Screenshot 2020-06-06 at 15 40 27" src="https://user-images.githubusercontent.com/52289/83946976-0da1c180-a80c-11ea-9331-3978a998c2a5.png">

I also tried with extensions disabled without success so it probably isn't ad blocker related.

Not sure whether these statistics mean anything useful:
```
Here's the entire statistics message of your editor:

{
    "numCells": 0,
    "numErrored": 0,
    "numFolded": 0,
    "numCodeDiffers": 0,
    "numMarkdowns": 0,
    "numBinds": 0,
    "numBegins": 0,
    "numLets": 0,
    "numConcurrentNotebooks": 0,
    "cellSizes": {},
    "runtimes": {},
    "versionPluto": "unknown",
    "timestamp": {
        "seconds": 1591454885,
        "nanoseconds": 852000000
    },
    "screenWidthApprox": 800,
    "docsOpen": false,
    "hasFocus": true,
    "pingTimeWS": null,
    "pingTimeHTTP": null,
    "numEvals": 0,
    "numRuns": 0,
    "numBondSets": 0
}
```
On Firefox everything works perfectly and it looks great. So I'm happy using  FireFox (and looks  pretty good so far!), and I'm just reporting this in case anyone else encounters it.

By the way, there are some neat Unicode symbols for Pluto - it would be cool to see one or more of them put to good use... :)

<img width="371" alt="Screenshot 2020-06-06 at 15 45 34" src="https://user-images.githubusercontent.com/52289/83947092-cc5de180-a80c-11ea-9b4b-b63e5b5b8df3.png">

**Comment by fonsp** [comment]
Hey! Safari is not a supported browser, see #128.

We considered the bottom left for our logo - maybe one day! But since they are unicode - you can use them in your Julia code - that's also fun?
