### ISSUE TITLE
Incorrect interpretation of function names

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#1505]
```julia
# ╔═╡ 061784ce-1e6a-11ec-0555-b38dc6f2e2ab
function (obj::typeof(Float64[]))(x)
	return "this is float64!"
end

# ╔═╡ a0f62a44-f158-4581-b148-b90851787cf7
function (obj::typeof(Int64[]))(x)
	return "this is int64!"
end
```

You will see the error: Multiple definitions for `typeof`. However, this is not the function name.

Pluto version 0.16.1

Note: a practical using case is https://github.com/GiggleLiu/NiLang.jl/issues/77

**Comment by fonsp** [comment]
Looks like #288 was not completely fixed. @Pangoraw what do you think?

**Comment by Pangoraw** [comment]
It should be fixed!
