### ISSUE TITLE
How does hot reloading handle moving the notebook file?

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1506]
If you change the filename or move the notebook using the filepicker UI, what happens? #1029

**Comment by disberd** [comment]
I tried creating a new notebook and moving it twice 
- First time from new notebook to specifica path/name
- Second time just renaming it within the same directory
Both times I tried updating the contents of the file from VSCode and both times the file change was tracked succesfully.

Is there really anything else to test?

**Comment by fonsp** [comment]
@disberd Thanks for testing! 💕 Did you use Windows? Or WSL?

> Is the filepicker UI this thing on top of the notebook?

Yep!

**Comment by disberd** [comment]
I only did tests on plain Windows, I don't think I even have access to WSL 2 on the work laptop so I never even tried setting anything up
