### ISSUE TITLE
Wrong placement of checkmarks in Pkg cell (chrome/linux)

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#1507]
Hi, when working with the main branch there seems to be an issue with the screen size of strings in the  new editor component:

![checkshift](https://user-images.githubusercontent.com/9221937/134816538-3678b185-3732-42bc-88f5-7960ae434479.png)

```
Google Chrome:	94.0.4606.54 (Offizieller Build) (64-Bit)
Betriebssystem	Linux
JavaScript	V8 9.4.146.16
User-Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36
```

**Comment by fonsp** [comment]
Which browser?

**Comment by fonsp** [comment]
@dralletje Any idea why? I thought chrome is the same on every OS :((((

**Comment by j-fu** [comment]
I seems to be the character spacing - it feels a bit larger than before...

**Comment by dralletje** [comment]
This was related to the wrapping plugin (the tabs before the import were the culprit), can you check if this still happens at current main? @j-fu

**Comment by j-fu** [comment]
Looks good now!  Thanks!
