### ISSUE TITLE
Cmd+D should select whole word

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1523]
Like in VS Code: it acts as a double click at the cursor

We had this shortcut before, and now it's not being cancelled and triggers chrome's bookmark feature

What we didn't have, but would be awesome to have, is pressing Cmd+D a **second time** to add the next exact match to the selection (like in VS Code, see video)

https://user-images.githubusercontent.com/6933510/135443676-212e6f43-f7b2-4da4-8e9b-3faeb633d99f.mov

**Comment by fonsp** [comment]
@dralletje Can you open a draft PR?

**Comment by dralletje** [comment]
> @dralletje Can you open a draft PR?

Uhhh....

🙃 

Sorry
