### ISSUE TITLE
URL links in htmlview.glitch.me broken

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#1530]
Hey Fons et al. 👋

Clicking a hyperlink from a static HTML notebook (through htmlview.glitch.me) does not redirect to said link.

Here's an example notebook, click on the `QuickPOMDPs` link at the top:
https://htmlview.glitch.me/?https://github.com/JuliaAcademy/Decision-Making-Under-Uncertainty/blob/master/html/2-POMDPs.jl.html

The dev console (on Chrome) looks like this (note, the issue is also on Firefox):
![image](https://user-images.githubusercontent.com/1592413/135680148-969034ee-e935-41d7-bcf5-3cda0bf0808a.png)

**Comment by fonsp** [comment]
Thanks again! It's fixed, try the link again

**Comment by fonsp** [comment]
(That's a very cool notebook!!)

**Comment by mossr** [comment]
@fonsp Works like a charm! Thanks for fixing that so quickly :)

If you liked that one, you should check out all the notebooks I made for my recent Julia Academy course: https://github.com/JuliaAcademy/Decision-Making-Under-Uncertainty
