### ISSUE TITLE
htmlview.glitch.me should not use an iframeresizer?

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1538]
From @mossr in https://github.com/fonsp/PlutoUI.jl/issues/97

> The ToC does not follow when scrolling. Here's a GIF to put some fire under this issue 🔥

![ToC-static-bug](https://user-images.githubusercontent.com/1592413/133948205-e47906c8-acc4-4b13-a43a-c8130c9c2300.gif)

**Comment by dralletje** [comment]
Whenever you feel like it :)

https://htmlview-dral.glitch.me/

**Comment by mossr** [comment]
@dralletje works great over there! Thank you!

One more issue is that the z-index of the TOC is under the yellow/tan cell itself.

![image](https://user-images.githubusercontent.com/1592413/140668732-9c17e556-954c-4ac1-a7be-6e505e26ab05.png)

The fix seems easy as you just have to change the z-index to 20 or higher here: https://github.com/JuliaPluto/PlutoUI.jl/blob/main/src/TableOfContents.jl#L150

**Comment by dralletje** [comment]
This is always the case, not just in the webviewer? Dang hahaha. Can you make a PR for it? 😁

**Comment by mossr** [comment]
Yes, it also has issues if you just open the HTML locally. 

Sure thing! I tested it out and that fix works:

![image](https://user-images.githubusercontent.com/1592413/140669787-c89812c9-02bc-4543-93af-230cddff6894.png)

PR incoming.

**Comment by fonsp** [comment]
Fixed! https://htmlview.glitch.me/

The binder button should also work better after https://github.com/fonsp/Pluto.jl/commit/5c594bce662f115a1643f30db1058435c39c33da
