### ISSUE TITLE
Way of Creatively Handling Automatic Running of Notebooks

### ISSUE THREAD

**Issue by TheCedarPrince** [fonsp/Pluto.jl#154]
So, I read issue #92 about not running all cells at start time. I definitely agree with the philosophy for automatically executing a notebook as a single unit. However, I have an interesting dilemma.

In one of the tutorials I am working on, I prompt the user to install certain versions of packages. I do not want this to automatically run in case the user does not want to install the packages or change their already installed package versions. This may interfere with someone's Julia installation.

I am not sure how best to handle this in keeping with Pluto philosophy. The best thing that I could think of is a Pluto provided macro that could cause a prompt or notification to appear with a specific, user-provided message that alerts someone to deciding whether or not to continue with running the notebook.

Here is an example of a notebook that I am working on that is running into this issue:

![image](https://user-images.githubusercontent.com/29561456/83951030-d0820300-a7fc-11ea-8f72-be2df4d468f3.png)

How do you think I should handle the matter of requirements without messing with a user's main Julia installation? Thanks!

**Comment by TheCedarPrince** [comment]
This looks promising: https://github.com/QuantEcon/InstantiateFromURL.jl

I will look at this more -- might be useful to bring some of this functionality over into Pluto perhaps.

**Comment by TheCedarPrince** [comment]
#142 may be relevant here.

**Comment by fonsp** [comment]
Ooh interesting link.

To me, the solution is to solve the package problem altogether - Pluto should be able to automatically resolve package silliness for you - #142 

As for your current dilemma: there is no way (I think) to describe the required package environment _in the same notebook_ where you use that environment. This is a nasty habit from Jupyter I think. The current fix (#142 will take a couple of months) is to describe the required environment in a separate file. A git repo with a Project.toml and a README with instructions would be best,

**Comment by fonsp** [comment]
(This is also preventing us from writing cool sample notebooks)
