### ISSUE TITLE
Use Italic font for comments in code?

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#1552]
You could now use a monospaced italic version of JuliaMono for comments in code blocks (and for anything else that you use _faux_-italics for at the moment:

Current version:

<img width="1322" alt="Screenshot 2021-10-11 at 13 43 50" src="https://user-images.githubusercontent.com/52289/136792263-baece2fc-cce6-45af-9974-4efab4967d1f.png">

Possible change:

<img width="1325" alt="Screenshot 2021-10-11 at 13 44 18" src="https://user-images.githubusercontent.com/52289/136792252-a04e5b7e-eb2b-45a0-b89d-6bfecb15b9c5.png">

with css such as:

```
	font-family: JuliaMono-RegularItalic;
	font-style: normal;
```

But is it really worth the extra effort and resources for such a small change? Well, to be honest, probably not, so feel free to close... 😄 Most people wouldn't notice, and some might not like it anyway. (Italics are not always popular, judging from the [reaction](https://github.com/microsoft/cascadia-code/issues/468) to CascadiaCode's italics.)

**Comment by dralletje** [comment]
Is it worth the effort? Surely Pluto is bound to JuliaMono as the moon is tidally locked to earth.



(Fixed as soon as the bundling PR is merged)
