### ISSUE TITLE
Unsatisfiable requirements

### ISSUE THREAD

**Issue by KenziTrader** [fonsp/Pluto.jl#1553]
When starting a notebook in `Pluto v0.16.1` the console shows 

```
┌ Error: Failed to resolve notebook boot environment
│   exception =
│    Unsatisfiable requirements detected for package HTTP [cd3eb016]:
│     HTTP [cd3eb016] log:
│     ├─possible versions are: 0.6.10-0.9.16 or uninstalled
│     └─restricted to versions 0.9.15 by an explicit requirement — no versions left
```

Now the notebook shows a `Not yet authenticated` error.

Installing a specific version of the `HTTP` package doesn't resolve the issue.

```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_COPY_STACKS = 1
```

How can I get my notebook to work again?

**Comment by KenziTrader** [comment]
Yes, I opened the link with the `?secret=XXX` in Safari. The browser window says it had to be reloaded and then show the `Not yet authenticated` error. 

I will use Opera for Pluto,

**Comment by Pangoraw** [comment]
Ok! Feel free to open a new issue if you encounter the problem again with Safari
