### ISSUE TITLE
Feature request: multi-cursor text selection (Sublime Text style)

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#1569]
This may be a big ask 🙃

I'm a huge Sublime Text fan and my programming productivity relies heavily on _multi-cursor selection_ using `ctrl+d`:

![multi-cursor](https://user-images.githubusercontent.com/1592413/137601421-7364f8a1-2b37-458b-8ec9-2e13bc9e497c.gif)

Most text editors and IDEs (e.g., VSCode) implement this feature. It would be a **tremendous** help to have this feature within a Pluto cell!

![multi-cursor-pluto](https://user-images.githubusercontent.com/1592413/137601491-f9c334d1-c96c-4e34-b0ed-5897c77e9733.gif)

Current alternatives:
- [Chrome extension for multi-cursor selection](https://chrome.google.com/webstore/detail/multi-cursor-for-chrome/ibhdngmggbgccjdnjkdchlnfgldpmekf?hl=en-US) (but doesn't work in Pluto)
- [GhostText Chrome extension](https://github.com/fregante/GhostText) allows you to mirror a textbox from Chrome to Sublime Text (but this workflow is tedious)

**Comment by fonsp** [comment]
Thanks! You can subscribe to https://github.com/fonsp/Pluto.jl/issues/1523
