### ISSUE TITLE
html is not rendered in error message

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#157]
Error messages that include html formatting, like the one displayed when a cell contains multiple variable definitions like
```
a = 1
b = 2
```
are not rendered correctly:
```
Multiple expressions in one cell.

<a href="#" onclick="errorHint(event)">Wrap all code in a `begin ... end` block.</a>
```

**Comment by fonsp** [comment]
This will be fixed by [the front-end rewrite that I'm working on](https://github.com/fonsp/Pluto.jl/tree/react-rewrite-oof)
