### ISSUE TITLE
auto-reload-from-file seems to be not accessible im 0.16.2

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#1580]
Hi, though #1029 seems to be in the list of release commits, the auto reload feature appears to be not accessible with 0.16.2.   The kwarg is not part of the API,  and it also seems that the feature is not enabled by default.

**Comment by Pangoraw** [comment]
The 0.16.2 release only contains a fix for #1511. Newer changes will be part of the upcoming version 0.17. You can see the list of changes from 0.16.1 to 0.16.2 [here](https://github.com/fonsp/Pluto.jl/compare/v0.16.1...v0.16.2).
