### ISSUE TITLE
Locate/stop current running cell easily

### ISSUE THREAD

**Issue by liuyxpp** [fonsp/Pluto.jl#1585]
My notebooks are usually quite lengthy. In addition, several cells may take a quite long time to compute (e.g. 10min+ to 10hr+). During development, I frequently modify some cells to experiment. This revision will cause related cells to rerun. Then the process may be blocked by the long-running cell. Normally I want to stop that particular cell. But as all those cells to be run have same visual indication (waving in the left border), I can not quite easily identify which cell is the current running one. The running time below the cell is another indication but it is hidden by default. Can you provide a button to locate the current running cell? Or even better, a button to stop current running cell no matter where it is? Thanks!

**Comment by fonsp** [comment]
All stop buttons are actually the same: they stop the current cell and prevent queued cells from running. So you can press the stop button on any cell in the notebook to stop the currently running cell.

Hope this helps!

Also try out the "Disable cell" feature: https://www.youtube.com/watch?v=HiI4jgDyDhY&t=57s

**Comment by yha** [comment]
> We recently added a progress bar #888, when you click it, you jump to the running cell

This feature doesn't work for me, using either Firefox or Edge on Windows 10. Clicking the progress bar does nothing.

**Comment by fonsp** [comment]
Thanks for pointing that out @yha ! Fixed now

**Comment by icweaver** [comment]
> We recently added a progress bar #888, when you click it, you jump to the running cell

Whaaat. I need to start making a list of all these neat features
