### ISSUE TITLE
Adding a ; at the end of statement inserts a tab

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#159]
Hi,

when I end the last line of a cell with a ; to supress output, this line gets a tab prepended.
I don't think that's how it should be.

Kind greetings, Falko

**Comment by fonsp** [comment]
This doesn't happen for me, maybe it only works for a specific line of code?

**Comment by zenon** [comment]
e.g. if I enter this into a cell:

    foo = begin
    	r = rand(20)
    	map(sin, r)
    end

and add a ; to the last line, it gets shifted.

**Comment by fonsp** [comment]
Thanks! I have [submitted a fix to CodeMirror](https://github.com/codemirror/CodeMirror/pull/6309) (that's what we use as code editor) to fix this issue 😊

**Comment by zenon** [comment]
Cool :-)
