### ISSUE TITLE
`with_terminal` does not capture `CSV.write` output

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#1590]
```
with_terminal() do
	CSV.write(stdout, DataFrame(x=[1,2,3],y=[2,3,4]))
end
```
output is shown in the terminal which launched Pluto, and not inside the notebook:
![image](https://user-images.githubusercontent.com/4170948/138317022-d47e05de-5883-4edc-9a76-e063f36d08dd.png)

**Comment by dralletje** [comment]
Can you open an issue for this on [the PlutoUI repo](https://github.com/JuliaPluto/PlutoUI.jl)?

**Comment by yha** [comment]
JuliaPluto/PlutoUI.jl#155
