### ISSUE TITLE
Load InteractiveUtils by default?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#160]
I found it jarring that `@time` and `@show` were immediately available, but `@which` or `@code_native` weren't. Digging around, I realized it's because my usual environments, the Julia REPL and Atom, automatically load the standard library `InteractiveUtils` by default:
```julia
julia> names(Main)
4-element Array{Symbol,1}:
 :Base            
 :Core            
 :InteractiveUtils
 :Main            

julia> 

```
Should this be loaded by default in Pluto?

**Comment by fonsp** [comment]
Didn't you say that those macros only print to the terminal?

**Comment by MikaelSlevinsky** [comment]
What does that have to do with making them available?

**Comment by MikaelSlevinsky** [comment]
`@which`'s output is in the worksheet

**Comment by fonsp** [comment]
I'm sorry, what I meant was that these `InteractiveUtils` look like they were designed for a terminal environment. It would be confusing to add them in if they don't work outside of one.

**Comment by dpsanders** [comment]
I just ran into this. I agree that InteractiveUtils should be automatically loaded. 

E.g. the following works fine in Pluto:

```jl
using InteractiveUtils
m = @which 1 + 2
typeof(m)
```

**Comment by fonsp** [comment]
I'll add it in 👍
