### ISSUE TITLE
Opening pluto in chrom shows site is not secure

### ISSUE THREAD

**Issue by fieldofnodes** [fonsp/Pluto.jl#1621]
I went to run Pluto on
Julia 
1.6.3
Chrome
Version 95.0.4638.54 (Official Build) (64-bit)

![pluto_not_secure](https://user-images.githubusercontent.com/19248072/139680567-729d1f9c-5a39-4c73-b7af-7b201d6aae21.png)

I know it is not a hindrance to running Pluto, but thought I would share.

**Comment by fonsp** [comment]
Can you make a video screen recording to show how you got to this point?

**Comment by fieldofnodes** [comment]
Yes will do
will send as soon as i can
