### ISSUE TITLE
Cyclic reference for self-recursive A.b methods

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1622]
Neither should error:

<img width="809" alt="Schermafbeelding 2021-11-01 om 21 18 28" src="https://user-images.githubusercontent.com/6933510/139736638-8f87ac6d-1c88-4cd1-a9df-645b24e0f1a1.png">

```julia
# ╔═╡ 37e09898-5771-4731-976a-40f6f8dae13a
Base.sqrt(x::Vector) = Base.sqrt("1")

# ╔═╡ 89ff3f12-464a-46dd-a431-a6d13d8f1a81
Base.sqrt(x::String) = Base.sqrt("1")

# ╔═╡ 1d7f81ae-3e57-4227-8a39-78767aeec35d
f(x::Vector) = f("1")

# ╔═╡ 0d506751-811e-4850-a749-a65cb2724979
f(x::String) = f(123)

```

# `Base.show`

It is important that these don't error, because it is common for a `Base.show` overload to use `Base.show` in its definition, for example in PlutoUI:
```julia
function Base.show(io::IO, m::MIME"text/html", slider::Slider)
	x = slider.asdf
	Base.show(io, m, @htl("""
		<input type=range max=$(x)>
	"""))
end
```

The current workaround is to define a method for `Base.show`, but use `show` (without `Base.`) in the function body. Fortunately we were already doing this in the PlutoUI source code :)

**Comment by dralletje** [comment]
Time for our DAG to become a DCG
