### ISSUE TITLE
Incorrect syntax highlighting in `begin/end` block

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1624]
This code:

```julia
begin
	function under_root(x::BigFloat)::BigFloat
		BigFloat(128177) / BigFloat(40800) - exp(-x^2)/2 - 16exp(-17x^2 / 16) / 17 - 4exp(-5x^2 / 4) / 5 - 16exp(-25x^2 / 16) / 25 - 25exp(-2x^2) / 96 * (1 + 2x^2 / 25)
	end

	function under_root(x::Real)
		ret = 128177 / 40800 - exp(-x^2)/2 - 16exp(-17x^2 / 16) / 17 - 4exp(-5x^2 / 4) / 5 - 16exp(-25x^2 / 16) / 25 - 25exp(-2x^2) / 96 * (1 + 2x^2 / 25)

		# `ret` can become slightly negative at x=0
		clamp(ret, 0.0, Inf)
	end
end
```

...is highlighted like this in Pluto:

![pluto_highlight](https://user-images.githubusercontent.com/8695383/139829819-636edf2d-c44a-49ff-b9e2-78089f3f0091.png)

1. The `begin` should be associated with the _last_ `end`, but it's associated with the second function's `end` instead, as indicated by its gray background;
2. The last `end` isn't highlighted as a keyword

------

- Julia 1.7.0-rc1
- Pluto v0.17.0

**Comment by fonsp** [comment]
MWE
```julia
begin
	function under_root(x)
		ret = 2exp(-x^2) / 1
	end
end
```

**Comment by fonsp** [comment]
https://github.com/lezer-parser/julia/issues/9

**Comment by dralletje** [comment]
"Minimal" working example... Love what a specific bug this is
