### ISSUE TITLE
Display of DataFrames with CategoricalArray columns

### ISSUE THREAD

**Issue by gdalle** [fonsp/Pluto.jl#1625]
Hey there,
Thanks for all the hard work on pretty visualizations! I just started working with DataFrames in Pluto, and I noticed that categorical columns look pretty ugly in the interface, because they display the CategoricalValue type of each element. Would it make sense to make an exception for that, since the column type already tells us as much?

![Minimal working example](https://user-images.githubusercontent.com/22795598/139863965-f1f6e6e8-5d11-4e5e-a731-832a34d7373d.png)

**Comment by fonsp** [comment]
Thanks! You can subscribe to #807
