### ISSUE TITLE
LaTeXStrings inside Plots label regex error

### ISSUE THREAD

**Issue by AshtonSBradley** [fonsp/Pluto.jl#1627]
I have tried this in vscode and it works fine. Clearly some string commands are handled fine by Pluto. But just today I encounter a new error when using Plots with LaTeXStrings in Pluto 

<img width="917" alt="Screen Shot 2021-11-03 at 5 11 05 PM" src="https://user-images.githubusercontent.com/24194258/140009126-cbde3f0a-2704-468d-89e8-e0cf8ce0250c.png">

**Comment by fonsp** [comment]
Can you send a notebook file?

**Comment by greimel** [comment]
This was a bug in GR and seems to be fixed: https://github.com/jheinen/GR.jl/issues/437
