### ISSUE TITLE
plutopkg tries to install package from markdown macro string

### ISSUE THREAD

**Issue by rapus95** [fonsp/Pluto.jl#1629]
![image](https://user-images.githubusercontent.com/5960902/140054906-9fb677d3-d1b4-4e8b-acfb-66ef52a661dd.png)

Off-topic: how can I make the `using RCall` use the ENV variable?

**Comment by fonsp** [comment]
Thanks for the report!

Pluto uses the real Julia parser to find using statements, so it won't actually install this package, the only error is that your browser is wrongly telling you that it will :) This will be fixed when #1630 is fixed

Can you open a new issue or discussion about the ENV question?
