### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#163]
I found a few of them in the FAQ, but one isn't working on my setup (Chrome in macOS on a MacBook Pro laptop where `delete == backspace`, i.e. there's no special delete key as there is on a detached keyboard):

- [x] Ctrl+Enter - run cell
- [x] Shift+Enter - run cell and add cell below
- [ ] Ctrl+Shift+Delete - delete cell
- [x] Tab - show autocomplete
- [x] Ctrl+Shift+? - show keyboard shortcuts

Also, when I use the last one to show keyboard shortcuts, I see two others that are unlisted in the FAQ that both work:

- [x] Ctrl+Q - interrupt notebook
- [ ] Ctrl+S - rename notebook

To help make this more intuitive (and faster for the user), there could be a few others, for example:

- [ ] Toggle cell view
- [ ] Enter/exit a cell
- [x] Traversing between adjacent cells

The keyboard shortcuts in Jupyter are generally very useful. They could serve as a source of inspiration. (I realize these two projects are distinct, but maybe a little bit more ease-of-use would go a long way for Pluto.jl. Speed is a combo of good software and a human being able to use it!)

**Comment by MikaelSlevinsky** [comment]
Ah I see there are a few other issues regarding shortcuts.

The strangest one for me was Shift+Enter adding a new cell. What if:
- Ctrl+Enter and Shift+Enter were swapped? For me, most of a worksheet's time is spent tweaking cells that already exist. So I could easily create a bunch of empty cells with the less-intuitive Ctrl+Enter and then switch to using the easier Shift+Enter
- Shift+Enter only created a new cell if one is executing the last cell of a sheet? (It's already possible to insert/delete a cell anywhere with the buttons, so functionality is not lost.)

**Comment by fonsp** [comment]
Hey! Thanks for your input in the project, I did not know about funky `delete == backspace` keyboards. Like you said, this is a duplicate issue, but I like this description better, so I have closed the other one :)

About swapping shortcuts: 🤷‍♀️ 
About the shift+enter change: the point is not to add functionality (like you said, there are buttons), but to make the editor accessible without a mouse

**Comment by fonsp** [comment]
#56

**Comment by isentropic** [comment]
Perhaps add all the jupyter standard keybindings? it is a very long list, but few notables are:
```
a - add a cell bottom
b - add a cell top
dd - delete cell
j-k movement up-down
```

**Comment by fonsp** [comment]
I think it's good to copy keybindings from familiar editors but I dislike Jupyter's two-mode editing, see #65. (I dislike traditional notebook _programmer experience_ in general, hence this project 😊)

**Comment by dpsanders** [comment]
I definitely miss having a shortcut to delete a cell. Especially since with the current bindings I keep adding blank cells when I use shift-enter to reevaluate, as @MikaelSlevinsky already mentioned.

**Comment by fonsp** [comment]
I'm compiling a list in #65
