### ISSUE TITLE
linting error for raw string macro

### ISSUE THREAD

**Issue by rapus95** [fonsp/Pluto.jl#1630]
![image](https://user-images.githubusercontent.com/5960902/140054906-9fb677d3-d1b4-4e8b-acfb-66ef52a661dd.png)
as you can see it suddenly stops recognizing using statements

**Comment by greimel** [comment]
It seems that Pluto doesn't realize that `"\\"`  is an escaped backslash, but thinks that the second `"` is escaped. See the reduced example

![image](https://user-images.githubusercontent.com/6280307/140078321-1f231f76-1bee-4d85-b43a-1e75fb3fff36.png)

```julia
begin
	"\\"
	x = 5
end
```
