### ISSUE TITLE
PlutoUI: Adding Plus/Minus button in Slider

### ISSUE THREAD

**Issue by DataPsycho** [fonsp/Pluto.jl#1641]
Hi,
When create a Slider using PlutoUI is it possible to has a tiny Up/Down or plus/minus button for one step increment. It is sometime annoying to use the slide button to adjust the number when I just need one or two step ahead or behind.

Thanks

**Comment by dralletje** [comment]
Hey!  Can you open this issue on the [PlutoUI repo](https://github.com/JuliaPluto/PlutoUI.jl)?
