### ISSUE TITLE
Stacktrace for macro expansion gets rewritten

### ISSUE THREAD

**Issue by Pangoraw** [fonsp/Pluto.jl#1648]
before:
![image](https://user-images.githubusercontent.com/9824244/140783930-97e40b74-86d7-4cb9-9364-aa56dd70002f.png)
on main:
![image](https://user-images.githubusercontent.com/9824244/140783964-de1197b2-d555-480a-b856-4ed9cc38318f.png)

The last line should at least still be there and be clickable.

**Comment by dralletje** [comment]
Yeah, on it
