### ISSUE TITLE
Include startup.jl

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#165]
This is different from the REPL, Atom, and Jupyter.

If this is by design, then maybe a line should be added to the FAQ.

**Comment by fonsp** [comment]
Thanks! This should be implemented.

On the other hand, my long-term goal is for Pluto notebooks to be entirely reproducible, by containing its own package env etc, and startup.jl would make that more difficult.

**Comment by fonsp** [comment]
For now, you have to do `include("dir/to/startup.jl")` in the first cell

**Comment by fonsp** [comment]
After some thought, `include(...)` will be the only supported method for now (it's easy and explicit) - I don't want to make any changes that will make my 100%-reproducible-plan more difficult later.

**Comment by MikaelSlevinsky** [comment]
Add a line to the FAQ?

**Comment by fonsp** [comment]
https://www.notion.so/Writing-and-running-code-7ddc40b7f1a24b809690954c373b20c8
