### ISSUE TITLE
Pluto doesn't display namespace conflicts

### ISSUE THREAD

**Issue by ratepenado** [fonsp/Pluto.jl#1650]
Hello,

Pluto doesn't precise when there is a conflict between 2 modules namespaces. For example if I use both Plots.jl and Luxor.jl, I have this error message:

![Screenshot 2021-11-08 at 23-40-38 🎈 Tiny notes 1 jl — Pluto jl](https://user-images.githubusercontent.com/67142261/140829968-7c6ebab5-9fe1-4095-9682-78e720a596d9.png)

The critical explanation that it is because of a conflict between the 2 packages isn't displayed as in the command line:

![Capture](https://user-images.githubusercontent.com/67142261/140830038-56716493-47f7-485b-a858-8bd970bc3a54.PNG)

I guess because it's a warning , so maybe it is more of a Julia issue  ?

**Comment by icweaver** [comment]
Could this also be closed by #1957 like #890 was?

**Comment by fonsp** [comment]
Yes! Thanks!
