### ISSUE TITLE
Incorrect matching parentheses highlighting

### ISSUE THREAD

**Issue by gpucce** [fonsp/Pluto.jl#1659]
In a pluto cell the line

```julia
f(g((args...; kwarg1=dict[index], karg2=kwarg2) -> X))
```

makes the parentheses of `f` and `g` not matched correctly, `g` closing one matches `f` opening one when moving the typing next to it. 
Using, for example, OhMyRepl in the Repl it is highlighted correctly.

**Comment by yha** [comment]
This example also has mismatched parentheses:
```
(f(y for y in z), z)
```
The first opening parenthesis wrongly matches the first closing parenthesis, and the last opening/closing parentheses don't match.

**Comment by dralletje** [comment]
So the
```julia
(f(y for y in z), z)
```
is fixed, but the original one ain't?? Pffft

**Comment by fonsp** [comment]
Looks like this has been fixed 👍
