### ISSUE TITLE
Overriding variable with `using` causes "Can't assign to WorkspaceX.varname from workspaceX+1" in dependent cells

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1663]
On main:

https://user-images.githubusercontent.com/6933510/141776584-3de106ac-f6fb-4bd9-bc4b-b6e5ef3f08d7.mov

**Comment by dralletje** [comment]
Weirdly this has nothing to do with the table viewer D:

**Comment by fonsp** [comment]
Can we add a test for this, maybe there is some similar dependency between stdlibs that is faster to test?

**Comment by fonsp** [comment]
MWE without dependencies, I need to switch the cell 4 times to get an error for some reason:

https://user-images.githubusercontent.com/6933510/142048395-93238832-bdda-42be-b583-b5360f48e237.mov


```julia
# ╔═╡ 30da8676-470e-11ec-398c-cf6216171cca
using Dates

# ╔═╡ 343c1521-f88b-4000-8271-76601f44ae14
Core.eval(Main, :(module Hello
	import Dates

	c = 123
	export c
	export Dates
end))

# ╔═╡ 50237b8c-4f86-461b-abae-7204014f19db
using ..Hello

# ╔═╡ 69fc6f26-158b-44e0-9a18-bcb1fcc3a38c
zz = Dates

```

**Comment by dralletje** [comment]
Why don't we bump the workspace on every cell run?
