### ISSUE TITLE
@benchmark from BenchmarkTools.jl is not reactive

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1664]
Re-running this cell:

```julia
f(x) = 1 + x
```
does not trigger this cell:
```julia
@benchmark f(2)
```

On Pluto release 0.17.1 and on main

**Comment by dralletje** [comment]
Yeah.. Never will unless we code in an exception. This was the reason for the PlutoTest rewrite: @benchmark passes the ast to another function that we can't look in..

We might be able to hijack eval? But gets very tricky very fast..

**Comment by Pangoraw** [comment]
Maybe we can try https://github.com/fonsp/Pluto.jl/issues/1496#issuecomment-927661428 ? Probably there won't be many false positive negatively impacted.

**Comment by dralletje** [comment]
We can try, but I'm skeptical because we really don't want it to alter the execution in any way.. Maybe only references and throw out any assignments? And make very sure that we're not accidentally creating cyclic references (another reference type???h

**Comment by simeonschaub** [comment]
Just ran into this as well. Does Pluto's expression explorer not just call regular macro expansion?

**Comment by dralletje** [comment]
> Just ran into this as well. Does Pluto's expression explorer not just call regular macro expansion?

Pluto does, but `@benchmark` doesn't just put your expression into that macro expansion.
`@benchmark` instead puts your input `quote`'ed into the expansion, which Pluto assumes to not access local variables (which strictly, it doesn't, but `@benchmark` instead `eval`s in the module it is being called in).

This is the reason for this note in their readme:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/767261/153747230-960a6cd8-01c8-4143-806b-0602681f7b28.png">

**Comment by fonsp** [comment]
Let's special-case this package?

**Comment by rikhuijzer** [comment]
For what it's worth, `TimerOutputs.@timeit` is also not reactive unfortunately.
