### ISSUE TITLE
Tab completion is broken

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#168]
Typing something like `\psi` and trying to tab-complete it does not work anymore. Instead the tab changes the keyboard fokus from the cell to the stop button instead.

**Comment by fonsp** [comment]
I expected something to break after the rewrite 😅

**Comment by karlwessel** [comment]
Expanding arrays and dicts also doesn't seem to work anymore :(

**Comment by fonsp** [comment]
oops
