### ISSUE TITLE
Extra update with `missing`

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#1680]
Sometimes updating a bound value causes a dependent bound value to update to `missing` before triggering another correct update. Example:
```
using PlutoUI
@bind n Slider(1:300)
d = Dict("n"=>n)
@bind k Select(collect(keys(d)))
(sleep(1); d[k])
```
![out](https://user-images.githubusercontent.com/4170948/142769486-201abd25-f68b-4b6c-ab18-d2eb6392eaed.gif)

**Comment by fonsp** [comment]
Can you update PlutoUI, try again, and send the notebook file if it is still a problem?

**Comment by yha** [comment]
This is with updated PlutoUI. The issue occurs with PlutoUI version 0.7.18-19, but not with version 0.7.17.
Notebook file:
https://gist.github.com/yha/81a1fc6337dc35c739fa12c289813a38

**Comment by fonsp** [comment]
Thanks @yha!
