### ISSUE TITLE
Check that the frontend assets are unchanged before serving bundled

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1681]
So that 
`pkg> dev Pluto` -> edit frontend assets -> run 
still works

**Comment by dralletje** [comment]
I can also check for the existence of a git repo? 😏

**Comment by fonsp** [comment]
Sounds good! You mean checking for `.git`?

You could also do something like:

```julia
import Pkg
deps = Pkg.API.dependencies()

p_index = findfirst(p -> p.name == "Pluto", deps)
p = deps[p_index]

is_developing = !p.is_tracking_registry
```

But this is probably using some internal Pkg API and might miss corner cases that I don't see

**Comment by dralletje** [comment]
Lekkerrrr
