### ISSUE TITLE
Cell drag and drop broken in 0.17.2 (linux/chrome)

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#1684]
Hi, with the new release,  instead of the moved cell, Pluto inserts something like this:
```
png_joinpathsplit__FILE__1assets1_q8s7EQC6INcqCHZELbVIDA6png = let
    import PlutoUI
    PlutoUI.LocalResource(joinpath(split(@__FILE__, '#')[1] * ".assets", "1_q8s7EQC6INcqCHZELbVIDA 6.png"))
end
```
The cell to be moved remains on its place. Couriously, on Firefox this problem does not occur.

**Comment by jcanizales** [comment]
Maybe Chrome isn't implementing the API as per the spec this relies on https://github.com/fonsp/Pluto.jl/pull/977/files ? The original "don't do it if dragging started inside the notebook" wording might be the best solution.

**Comment by jcanizales** [comment]
FWIW, I'm seeing this on Pluto 0.16.0, Chrome 96.

**Comment by fonsp** [comment]
Can you try out https://github.com/fonsp/Pluto.jl/pull/1780 to see if that fixes the problem?

**Comment by j-fu** [comment]
Hi, ... well  it seem that this again is not working - my suspicion is chrome v97, because the fix in #1780 ceased to work, and so it doesn't work in 0.17.5 as well. I also tried Pluto 0.16.1 for double checking - the same.

**Comment by fonsp** [comment]
Let's make a new issue

**Comment by fonsp** [comment]
Moved to #1809
