### ISSUE TITLE
"Submit all changes" disapears for small windows

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#169]
When i reduce the width of the browser window below a certain limit the submit all changes icon disappears.

Also, is there a keyboard shortcut for that function. It often happens that I need to change two cells and only submitting both changes at ones gives a meaningful state. For example when one renames a variable over different cells.

**Comment by fonsp** [comment]
Thanks!

Shortcut is `Ctrl+S` since the recent update

**Comment by karlwessel** [comment]
According to the help displayed when pressing F1 `Ctrl+s` is rename notebook.

**Comment by fonsp** [comment]
@karlwessel suggested that we only display the filename, without path or extension. I like the idea of dropping the extensions - people might realize that you can use spaces and capital letters inside filenames with no issues. 

Why call your notebook `ch1-getting_started.jl` if you can call it `Chapter 1: Getting started.jl`?

**Comment by karlwessel** [comment]
How would Pluto handle ":" in the notebook filename under windows?

**Comment by fonsp** [comment]
haha UGH

**Comment by fonsp** [comment]
Luckily Julia will just error when it can't write a file

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/87227245-100eb280-c39a-11ea-883c-d22d2e269872.png)
