### ISSUE TITLE
Option to export a file

### ISSUE THREAD

**Issue by mgautam98** [fonsp/Pluto.jl#170]
How can I export the program to say Markdown, or latex or HTML? Is there any option for that?

**Comment by fonsp** [comment]
Right now, the only export other than `.jl` and `.pdf` is a full snapshot of the web page: right click on the page, and then `Save as...`. This is not very flexible though - I'd like to improve the HTML export.

About markdown and latex - do you mean extracting the Markdown strings or generating a document with embedded output? That sounds difficult difficult, I think that just having HTML export (which you can pandoc to something else) is the first thing we should add.
