### ISSUE TITLE
reactive run of function definitions appends to @doc

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1708]
Probably related to https://github.com/fonsp/Pluto.jl/issues/1693 but thought it would be better to have separate issues if it's not actually cause by the same thing.

When cells containing function definitions with docstrings are run reactively the docstring is appended multiple times rathern than simply replaced.

![6d36a10f-8255-45dd-9485-2f27dbf18219](https://user-images.githubusercontent.com/12846528/144240173-4fffe00f-e22a-4a26-9380-7ccf2056fe08.gif)

Manually re-running the cell with the definition correctly replaces the docstring.

**Comment by fonsp** [comment]
bump

**Comment by Pangoraw** [comment]
Both #1708 and #1693 have been fixed with #1966.
