### ISSUE TITLE
Autocompletion issues after migration to CM6

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1718]
As discussed on [zulip](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/Autocomplete.20dict.20keys)

There are some cases where autocompletion used to work before CM6 and does not anymore:
- Dict keys (`dict[<TAB>`)
- apparently also paths `"path/completeion/<TAB>"` (as mentioned by @fonsp)

**Comment by fonsp** [comment]
@dralletje I had a quick look but this seems like something you could fix more easily?

**Comment by dralletje** [comment]
I can't find any release of Pluto where this used to work... Do you have any pointer? I tried 0.16.4 and 0.14 but neither does..

[However, this made me rethink (and optimise) a bunch of how we do autocomplete.](https://github.com/fonsp/Pluto.jl/pull/1749)
