### ISSUE TITLE
Everything is blue

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1723]
We need more variety in our colours, this is useless:

![Schermafbeelding 2021-12-02 om 14 26 34](https://user-images.githubusercontent.com/6933510/144430815-c57ae65a-a8e4-456f-b3d1-81a256c6a145.png)

```julia
	@info reaction_nodes
	@info typeof.(reaction_nodes)
	reaction_rate_variables = Dict(n.id => ((n.reaction_rate isa Symbol) ? to_sym_param(n.reaction_rate) : n.reaction_rate) for n ∈ reaction_nodes)
	@info reaction_rate_variables
	species_variables = Dict(n.id => to_sym_variable(Symbol(n.label)) for n ∈ species_nodes)

	to_variable(n::SpeciesNode) = species_variables[n.id]
	stoich(c::AbstractReactionNetworkConnection) = c.stoich

	rx = []
	for reaction_node ∈ reaction_nodes
		substrate_connections = reaction_node.connects_from
		product_connections = reaction_node.connects_to

		substrate_nodes = (x->x.from).(substrate_connections)
		product_nodes = (x->x.to).(product_connections)

		substrate_stoich::Vector{Int} = stoich.(substrate_connections)
		product_stoich::Vector{Int} = stoich.(product_connections)

		push!(rx, Reaction(reaction_rate_variables[reaction_node.id], to_variable.(substrate_nodes), to_variable.(product_nodes), substrate_stoich, product_stoich))
	end

```

**Comment by ankur12-1610** [comment]
Can I work on this issue?

And regarding the other colors, which color scheme should be added?

**Comment by dralletje** [comment]
I'd love to say "good first issue" but I think part of this is... hmpfff.. julia-lezer........

I'LL WORK ON IT THIS WEEK OKAY

**Comment by dralletje** [comment]
So we got a bit further, but variables are still all variables...

One idea I have is making explicitly block-scoped variables a different color (the `x`s in all these examples):

```julia
for x in xs
  x
end
```

```julia
function f(x)
  x
end```

```julia
let x = 10
  x
end```

This could be done very reliably with lezer (as we already get all variable info), and macros wouldn't even really be able to interfere with this.
Problem with doing this with all local variables is that macros could screw it up:

```
let
  x = 10
  @someassigningmacro z
  x // Would be highlighted as local
  z // Would be highlighted as normal :(
end
```

**Comment by fonsp** [comment]
Current state:

<img width="718" alt="Schermafbeelding 2022-01-21 om 20 58 40" src="https://user-images.githubusercontent.com/6933510/150592294-76692374-ee0c-401b-9c90-2d851afb35b9.png">
