### ISSUE TITLE
Extra updates on bound value change

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#1724]
The issue #1680 is still around. The extra updates are not with `missing` any more, but they are still really slowing down my big notebook (not sure if this is only this issue or other extra updates as well. I regularly get chains of 3-4 updates from one widget interaction on PlutoUI 0.7.21, which doesn't happen on 0.7.17)

example notebook:
https://gist.github.com/yha/a92e41f975ac3e87cf6b56861c9f7a5a
![double-update](https://user-images.githubusercontent.com/4170948/144468719-672991d0-9788-496e-973d-9d9c40bdc5ad.gif)
)

**Comment by fonsp** [comment]
Thanks for the video recording and the clever example notebook!
