### ISSUE TITLE
Display `Text{String}` from python docstring as plain string instead of markdown

### ISSUE THREAD

**Issue by melonedo** [fonsp/Pluto.jl#1727]
In #1239, I complained about python documentation not displayed in Pluto notebooks, which has been partially fixed in https://github.com/fonsp/Pluto.jl/commit/0757a34078929198d652e6c0358305a0fa647ad6 by parsing the returned docstring as markdown.

However, in my observation, python docstring is not standard markdown, at least not conformant to Julia's specification. For example, double backticks "``" are interpreted by Julia as [LaTeX](https://docs.julialang.org/en/v1/stdlib/Markdown/#\\LaTeX), but by Python (Sphinx) as [inline code](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup).

As a result, documentation for `sympy.fourier_transform` from SymPy.jl and `plot` from PyPlot.jl are not rendered perfectly:
![image](https://user-images.githubusercontent.com/44501064/144695281-1c014d38-1e77-454a-a9ad-afc55886cb44.png)
![image](https://user-images.githubusercontent.com/44501064/144695272-ba39a17d-e855-4a43-92c2-f3f15d1e0add.png)

**Comment by dralletje** [comment]
I'd say this is an issue in PyCall.
We don't really have a way to check if docs "come from python", and it would help other docs-based programs a lot if PyCall would convert this.
Could you open an issue with PyCall?

**Comment by stevengj** [comment]
If we're returning a `Text` string and not `Markdown`, why are you displaying it as `text/markdown`?

Shouldn't you be checking `showable("text/markdown", docstring)` to check whether a `show("text/markdown")` method exists?

**Comment by stevengj** [comment]
Even from Julia, documentation can be any show-able object, and you're supposed to be using the multimedia I/O machinery to decide how to `display` it.

**Comment by dralletje** [comment]
@stevengj its an exception so PyCall docs work

**Comment by stevengj** [comment]
I'm confused, why do you need an "exception" rather than just using `display` (or equivalent)?

**Comment by dralletje** [comment]
Because PyCall (or python itself, don't know how deep this is embedded) doesn't think about exposing it as markdown (instead using `Text`), but as far as I could find python docs are generally implemented in markdown.

Ideally this would be fixed at a deeper layer, but AFAIK this fix works enough.

What problem are you addressing?

**Comment by stevengj** [comment]
> but as far as I could find python docs are generally implemented in markdown.

You can't assume this.  There are lots of Python packages with non-markdown docstrings

If an object doesn't have a `text/markdown` method for `show`, you should use the `text/plain` method.  Treating it as text/markdown anyway is broken.

**Comment by dralletje** [comment]
Thanks for you're feedback
