### ISSUE TITLE
the livedocs don't refresh 

### ISSUE THREAD

**Issue by shubhangi013** [fonsp/Pluto.jl#1730]
The livedocs don't refresh and show the previously restored screen unless the user refreshes the browser. 

I went through the code and I'm eager to contribute to solving this issue. Any guidance would be appreciated!

video reference : 

https://user-images.githubusercontent.com/78342516/144713563-6ce5cf7b-06f6-4a5f-857a-aa2c88a13737.mp4

**Comment by fonsp** [comment]
What is the issue exactly? Why is this an issue?

**Comment by shubhangi013** [comment]
> What is the issue exactly? What do you mean with "fresh"? Why is this an issue?

Actually when user searches something on the livedocs, and them closes it, it shows the previously restored screen unless the browser is refreshed.

**Comment by dralletje** [comment]
So what is the problem with it staying open? 
I don't see the issue either? Can you a bit better describe what it is your expecting to happen, and specifically what of that expectation isn't working?
