### ISSUE TITLE
Live Docs does not clear when search query is cleared

### ISSUE THREAD

**Issue by ankur12-1610** [fonsp/Pluto.jl#1732]
![issue](https://user-images.githubusercontent.com/76884959/144721404-e5f97519-5d73-446b-8f6c-0a30e21b34ae.gif)

`Live Docs` executes the search query even if there is no input given in the search-box. 

Is there any reason to pass on first letter of any typed word as a query? :thinking:

If not then this bug should be fixed.

**Comment by ankur12-1610** [comment]
I'll like to work on this issue, this is my first time in `Pluto.jl` so I don't know much about the code base:sweat_smile:. Could anyone please guide me through this?

**Comment by fonsp** [comment]
Hi @ankur12-1610 ! I'm not sure I understand the issue

You write: "even when there is no input", but you *are* giving input! Can you be more precise about what the issue is? Is it a problem or just an aesthetic change?

**Comment by ankur12-1610** [comment]
> Hi @ankur12-1610 ! I'm not sure I understand the issue
> 
> You write: "even when there is no input", but you _are_ giving input! Can you be more precise about what the issue is? Is it a problem or just an aesthetic change?

@fonsp by no input means: when we type a word and then after backspacing it completely, the search box searches the first letter of the word even if the typed word is no more. So, my doubt was is this intentional or is this a bug?

**Comment by fonsp** [comment]
This is 'intentional' to make our code simpler: we don't want to clear the doc result when you move your cursor to a new line (which triggers searching the empty string). This is a bit too minor to continue discussing, but let us know when you find another problem!

**Comment by ankur12-1610** [comment]
> `Live Docs` executes the search query even if there is no input given in the search-box.
> 
> Is there any reason to pass on first letter of any typed word as a query? thinking
> 
> If not then this bug should be fixed.

Oh! got it :), thanks for replying.
