### ISSUE TITLE
Can't git checkout `frontend-dist` on Windows

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1739]
It looks like `git` is not allowed to checkout this filename:

[https://github.com/fonsp/Pluto.jl/blob/release/frontend-dist/LICENSE.db2818f0.](https://github.com/fonsp/Pluto.jl/blob/release/frontend-dist/LICENSE.db2818f0.)

I found this out because I accidentally ran our backend tests on the `release` branch: https://github.com/fonsp/Pluto.jl/runs/4436763504?check_suite_focus=true

**Comment by fonsp** [comment]
This might fix it https://github.com/fonsp/Pluto.jl/commit/106cc81b6578a0d816797471ea9c1d7a7f1b5da8

**Comment by dralletje** [comment]
Nice "fix" 🙃 👍

**Comment by fonsp** [comment]
Test to see if it was fixed: https://github.com/fonsp/Pluto.jl/actions/runs/1555284887
