### ISSUE TITLE
Remove deleted files from 'Recents' list

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#174]
To keep the list of recent notebooks clean it would be nice if Pluto could purge the list of recent notebooks from notebooks that are in the temporary folder and don't exist anymore.

**Comment by fonsp** [comment]
The motivating issue is that your recents list gets cluttered up by tmp notebooks right?

(some loose thoughts:)

I was thinking: Pluto doesn't actually need a file on disk to work - the state is kept in memory. So temporary notebooks and new notebooks could start out with _no_ file, and invite the user to save it somewhere. This also solves #97 and some feedback that we got that it is unclear how to save a notebook. They are right: when you open a sample notebook, you are first greeted with the Pluto logo, and then some OS magic spell words that don't mean anything to most people, even if you are familiar with paths and file systems. What the technowords don't communicate is: "I am the current filename and you can change me". Part of this is that software usually does not save somewhere until you explicitly do so. Although a common trend is to always save as "Untitled" (google drive) or "FunkyApricotDolphin".

One reason I can come up with to always save notebooks is for backups in case Pluto breaks. But that doesnt seem to happen anymore, especially not with quick-and-dirty notebooks that you would not care enough for to save them yourself. The other one is for user error: if you close the Pluto server you might not realise that you had an unsaved notebook open. With the current `/tmp` solution, you could always open that folder and sort by most recently modified (if you are techy enough).

What do you think @karlwessel ?

**Comment by karlwessel** [comment]
I really like that notebooks are stored on file and not in memory, exactly because of the reasons you described. Also, the /tmp folder is ideal for storing "untitled" notebooks, since it assures that no important directory gets cluttered with sample and test notebooks. If I just want to test something in a notebook I know /tmp will clean up after me and if the tests are worthy I can still decide to give them some proper location.

This issue is only about the fact that while tmp automatically cleans up my mess of notebooks, Pluto does not (yet).

Regarding the "users are greated with some OS-Magic" issue. Can't Pluto just display only the notebook name without extension and path? And if you click on it it is expanded to the full path for the techy people and for the non techy people there is the "rename" button which could be renamed to "save as" (a bit like for jupyter-notebooks).

And I really like the "FunkyApricotDolphin" approach to naming new/temporary notebooks. That way there is a nice name to display even if the notebook hasn't been saved yet and it is easier to find/remember than "YhZGQnwe.jl" in the temporary folder.

**Comment by fonsp** [comment]
One thing we could do is keep the functionality the same, but instead of the initial /tmp path, we show "Save notebook...", and when you click on it, it defaults to:
`[home dir]/funky-apricot-dolphin.jl` with `funky-apricot-dolphin.jl` preselected. 

The only thing we miss is that users don't know where to look for backups, but maybe we can print things to the terminal like:
```
[ Info: opened a new notebook in /tmp/jl_jkadfskjh.jl
```
and
```
[ Info: renamed /tmp/jl_jkadfskjh.jl to /home/fonsi/apricot.jl
```

to teach users that Pluto keeps backups there.

Displaying a shorter path is #169, let's talk more there

**Comment by karlwessel** [comment]
That sounds good! Does anything speak against already naming the temporary file with some random word combination like `cinnamon-zebra.jl` instead of "jl_jkadfskjh.jl"?

**Comment by fonsp** [comment]
Yes that makes sense! Perhaps you can write this in a PR?

You just replace `tempname()` with our own `cutename()` [here](https://github.com/fonsp/Pluto.jl/blob/master/src/notebookserver/Notebook.jl#L25). Have a look at the source for `tempname()` to see how they do cross-OS support, i think that it's `joinpath(tempdir(), "dolpin.jl")`. 

I wrote a [list of cute words](https://github.com/fonsp/printi/blob/master/client/namegenerator.py#L16) for another project, if you need inspiration :) Maybe nice to split it into adjectives and nouns?

**Comment by karlwessel** [comment]
Can do that, together with the other PRs I promised, when the semester ends.

**Comment by fonsp** [comment]
okay :)

**Comment by fonsp** [comment]
#97

**Comment by fonsp** [comment]
Small change: @lukavdplas suggested to use the creation date as filename for temporary files - that way they still make some sense when you see them in your recents. `funky-dolphin.jl` is memorable, but showing `Save notebook...` instead of `/tmp/funky-doliphin.jl` means that you will never see that filename.

**Comment by fonsp** [comment]
I went with the [cute names](https://github.com/fonsp/Pluto.jl/commit/2d2176906bfa731fe5ac6dc5f640bad26b27d7cc#diff-683cae015a3e9756dcaeeeffd712c69fR1-R25) after all. 

When the notebook lives inside the temp dir:
![image](https://user-images.githubusercontent.com/6933510/87227320-8b706400-c39a-11ea-945c-d32e76e5a254.png)


When you click on "Save notebook..." you get a suggested filename, and "Rename" is "Save" instead:
![image](https://user-images.githubusercontent.com/6933510/87227308-77c4fd80-c39a-11ea-8c15-1c9e607dd03b.png)

**Comment by karlwessel** [comment]
I like the new default note book names! 

Since Pluto now purges temporary notebooks automatically we can close this issue right?

Although one last thing: how do I purge notebooks that don't exist anymore (all my old temporary ones) from the recent notebooks list?

**Comment by fonsp** [comment]
Sure! But your point was valid - notebooks stick around forever in the recents list, there is no way to delete them automatically/manually.

**Comment by karlwessel** [comment]
Yep. I also had a quick glance to see whether I could fix this by only showing notebooks that exist or aren't located in the `/tmp` directory. But it seem Preact has no access to the filesystem and and therefore this would have to be fixed on backend and front end side.

**Comment by fonsp** [comment]
Yep! And they might not be the same computer

**Comment by fonsp** [comment]
Notebooks are no longer stored in temporary storage :)

As for removing deleted files, hmmmm i'm not sure. Not a priority

**Comment by fonsp** [comment]
Continued in #977

**Comment by scls19fr** [comment]
Hello,

Thanks for Pluto.jl. That's a great software.

When clicking on a recent file I'm getting

    Can't find a file here
    Please check whether C:\Users\scell\live_plot_sin.jl exists.

    

    
    [Go back](http://localhost:1234/open?path=C%3A%5CUsers%5Cscell%5Clive_plot_sin.jl#)

Maybe in such a case you could ask user if he want to remove this entry from Recent notebooks list.

Any opinion ?
