### ISSUE TITLE
Write ML models on Pluto notebook

### ISSUE THREAD

**Issue by dnabanita7** [fonsp/Pluto.jl#175]
For a sample notebook, I will start with a regression model from Kaggle and write it on Pluto notebook. This can be stored in a ``models`` folder and can be similarly used as zoomodels. For now, I am working to create some ML setups as FluxModels.jl. Those models can also be written on Pluto notebook. I am not sure about the compute power. 
cc @TheCedarPrince

**Comment by fonsp** [comment]
Hi! You can work on notebooks in a new repository, [like here](https://github.com/lukavdplas/pluto-notebooks).
