### ISSUE TITLE
Macro call syntax echoed in cell output

### ISSUE THREAD

**Issue by MichaelHatherly** [fonsp/Pluto.jl#1752]
When invoking a macro where it's arguments are keyword/assignment syntax the macro name itself appears in the cell output as if it's an assignment to a variable in the cell:

![image](https://user-images.githubusercontent.com/6144086/145305818-50667095-a296-43bd-8459-4a1f4c263d65.png)

On Pluto `0.17.3` with Julia `1.6`.

**Comment by dralletje** [comment]
= feature

😅 

I added this as a feature, where I assumed most macros you put before an assignment will actually also do that assignment.
I'm guessing that won't work with macros that want to treat their inputs as keyword arguments >:(
I still really like it for `@time` and `@skip_as_script` macros through..
