### ISSUE TITLE
Renaming a macro does not cause dependent cells to error

### ISSUE THREAD

**Issue by MichaelHatherly** [fonsp/Pluto.jl#1753]
When renaming a macro in one cell that is referenced in other cells the dependent cells do not error as happens when doing the same for a method definition.

Prior to renaming:

![image](https://user-images.githubusercontent.com/6144086/145306043-496fc39f-17b5-4b87-8a53-6b4ed629f443.png)

After renaming and evaluating the first cell:

![image](https://user-images.githubusercontent.com/6144086/145306027-64ec7ca1-9c7c-42a4-8c51-f2c301059673.png)

**Comment by dralletje** [comment]
Oof
