### ISSUE TITLE
Multiple function definitions when using value types

### ISSUE THREAD

**Issue by blepabyte** [fonsp/Pluto.jl#1756]
This only seems to happen when both functions have some macro call inside them. The notebook file runs fine in Julia. 

![image](https://user-images.githubusercontent.com/74576829/145667712-eb183e50-7ebb-477d-853a-8469fbaf557b.png)

[Gist with notebook file](https://gist.github.com/blepabyte/12a0130d8ae7edb6f187196683b0ff65)

- Pluto 0.17.3

**Comment by Pangoraw** [comment]
Thanks for reporting!
