### ISSUE TITLE
Dict as array element doesn't display

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1759]
MWE - copy this into an empty notebook cell:
```
[Dict(Symbol("x$i") => i for i in 1:100)]
```
Result:
![image](https://user-images.githubusercontent.com/687995/145891208-63683e8c-c31d-48e5-ac1d-cc1e70a0cfa7.png)

Smaller dicts, or dicts with key type other than symbols, display just fine.

**Comment by fonsp** [comment]
(You need to add `import Tables` in a second cell to get this bug.)

**Comment by fonsp** [comment]
Thanks!
