### ISSUE TITLE
variable is incorrectly marked as global in generator

### ISSUE THREAD

**Issue by Pangoraw** [fonsp/Pluto.jl#1764]
maybe related: `i` is incorrectly marked as global here:
```
triuvec(x) = [x[i,j] for j=1:size(x,2) for i=1:j-1]
```
![image](https://user-images.githubusercontent.com/4170948/144890789-a59860ab-083b-4901-8b34-5f6c97070caa.png)

_Originally posted by @yha in https://github.com/fonsp/Pluto.jl/issues/1733#issuecomment-986978987_

**Comment by fonsp** [comment]
(Since this is a bug in our highlighting extension, not the expression explorer, you need to also define `i = 123` in another cell to reproduce.)

**Comment by fonsp** [comment]
Maybe this is impossible, because it needs to traverse backwards?

**Comment by dralletje** [comment]
I didn't fix this, but it doesn't happen anymore! Say whaaaaat
