### ISSUE TITLE
Ghost text in CM6

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1768]
```julia
@markdown("""
<p>The macro <code>@markdown</code> lets you write <a href="https://developer.mozilla.org/docs/Web/HTML">HTML</a>
""")
```

https://user-images.githubusercontent.com/6933510/146608899-86e8d427-f7bc-4ed5-8776-6179795dcbde.mov

**Comment by Pangoraw** [comment]
Maybe related, pasting `[]` inside `""` creates an extra ghost `"`.
![ghost_text gif](https://user-images.githubusercontent.com/9824244/146637115-78480daf-b40f-418f-b2b4-aab5adcea6e2.gif)

**Comment by fonsp** [comment]
Smaller example:

https://user-images.githubusercontent.com/6933510/146780951-530125d8-1d94-483b-8389-24ffdb6b105a.mov

**Comment by fonsp** [comment]
See https://github.com/fonsp/Pluto.jl/issues/1771 for another example

**Comment by fonsp** [comment]
@dralletje This bug is only happening on `main`, not on 0.17.3

**Comment by fonsp** [comment]
> @dralletje This bug is only happening on `main`, not on 0.17.3, so maybe it was caused by updating the cm dependency in [3243c60](https://github.com/fonsp/Pluto.jl/commit/3243c605a414add009359c454d51af3c6f6517c6) ?

If I revert this commit, the problem is gone. If I then change the `pluto-codemirror-setup` import from 0.19.2 to 0.19.4, the problem is there again. So it must be because of bug that was introduced in one of the `@codemirror` packages inbetween those versions.
