### ISSUE TITLE
Method definition doesn't work in Pluto

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1769]
I'm trying to define a simple `Table` in Pluto, but it doesn't fully work:
![image](https://user-images.githubusercontent.com/687995/146669958-fb4035f4-9966-4217-b7fa-4f2dff7ddf64.png)
Specifically, the `Tables.columnaccess(::S) = true` part: following the traceback, I see that the check at https://github.com/JuliaData/Tables.jl/blob/main/src/fallbacks.jl#L87 fails. Strangely, calling `Tables.columnaccess(S())` is a Pluto cell correctly returns `true`.

Of course, everything is fine when I paste the same code into the regular Julia REPL:
<details>
<summary>Copy-pasted from notebook directly</summary>

```julia
julia> # ╔═╡ a82179a6-fcf5-4a95-9b11-e4e339b797ae
       using Tables

julia> # ╔═╡ 2b598cdf-9ffc-4757-a9ac-d30d23ce9eae


       # ╔═╡ 55cc8eb7-fd31-4950-bc24-8497043b0a4e
       struct S end

julia> # ╔═╡ 12587f04-d10d-466d-b7ac-98c29f32d75b
       Tables.istable(::S) = true

julia> # ╔═╡ 1375294c-ef18-4b5b-8828-bea28e1aa62c
       Tables.columnaccess(::S) = true

julia> # ╔═╡ 0d2b9f4d-0b82-464e-a343-1bfb26c8bf54
       Tables.columns(::S) = (a=rand(10),)

julia> # ╔═╡ c19ae837-47c0-493b-9441-3f6115a2be41


       # ╔═╡ 53e951f6-422e-4059-be7d-6321bd4e07d9
       columntable(S())
(a = [0.3178549471518519, 0.38500468343422634, 0.02408450590669209, 0.4329608204858352, 0.3292489991779296, 0.8779441338049941, 0.30372894506202464, 0.4989385634139504, 0.22188677189857553, 0.21967207407765788],)

julia> # ╔═╡ b1d60973-87b6-450b-a9a9-760b88e9dd45
       rowtable(S())
10-element Vector{NamedTuple{(:a,), Tuple{Float64}}}:
 (a = 0.13645275325585793,)
 (a = 0.07176155300992748,)
 (a = 0.9315739873393201,)
 (a = 0.8553309756585938,)
 (a = 0.16682906014240262,)
 (a = 0.4823154984291812,)
 (a = 0.15996004969244848,)
 (a = 0.5992253264750519,)
 (a = 0.5741887343881732,)
 (a = 0.36447483931345437,)
```

</details>

Not sure how to debug this Pluto issue further.

Notebook [gist](https://gist.github.com/aplavin/98095b531ccc8648c93f8414d5e45121) and [binder](https://binder.plutojl.org/v0.17.1/open?url=https%253A%252F%252Fgist.githubusercontent.com%252Faplavin%252F98095b531ccc8648c93f8414d5e45121%252Fraw%252Fc34774750605f88cae7d9b8b3f2dec2ba3f5db62%252Fnotebook.jl)

**Comment by fonsp** [comment]
I have no clue why this is happening 😳 maybe it's a world age problem...

**Comment by dralletje** [comment]
Works for me.. think Pluto runs the `rowtable(S())` cell before it runs `Table.columnaccess() = true`.
Try re-running the last cell.

A solution, though not pretty, it putting `struct S ... end` and the method definitions in one cell :/

![image](https://user-images.githubusercontent.com/767261/147111533-2fd9e620-12b7-4a60-b72c-c3d1e17e33cc.png)

@Pangoraw how hard would it be to make Pluto prioritise method definitions even if we don't see a cell depending on it directly? This would also fix a lot of my `No Base.show for XXX` errors 😅

**Comment by Pangoraw** [comment]
I was not able to make it work :grimacing: @dralletje it works on the first run for you ?

![image](https://user-images.githubusercontent.com/9824244/147123438-62f7d368-8153-4ec6-b646-c48a671aee67.png)

**Comment by dralletje** [comment]
Noooo sorry, it specifically didn't run for me on first run either.

**Comment by Pangoraw** [comment]
:thinking: 

![image](https://user-images.githubusercontent.com/9824244/147124389-4b8ca6d8-6711-4c87-8253-f39bea596391.png)

**Comment by fonsp** [comment]
Does it work if everything is in one big cell?

**Comment by Pangoraw** [comment]
It does not work even when everything is in one cell

![image](https://user-images.githubusercontent.com/9824244/147127618-43203d80-d92d-45db-9699-2c0a1cb14c14.png)

**Comment by Pangoraw** [comment]
Ok, i found the issue which is the difference with the Tables.jl version (0.16.0 in the notebook) and the released version which is 0.16.1.

You either need to set

```julia
Tables.columnaccess(::Type{S}) = true
```
or update Tables.jl

on the left (0.16.1), on the right (0.16.0)
![image](https://user-images.githubusercontent.com/9824244/147128425-d7a88dec-0054-4446-9f3a-d7b156e53392.png)

**Comment by Pangoraw** [comment]
There is however a real issue with tracking reactive dependencies between `columnaccess()` and `rowtable()` but we can open a fresh issue for that or use #326.

**Comment by fonsp** [comment]
Woah amazing Paul!
