### ISSUE TITLE
Table of content overlaps text in static HTML

### ISSUE THREAD

**Issue by jakobnissen** [fonsp/Pluto.jl#1770]
When exporting a static HTML of a file with a table of contents, in the HTML, the table of contents will overlap the content of the HTML making it unreadable.

I use the latest version of Pluto (0.17.3)

You can find the notebook to reproduce the issue here:
https://github.com/jakobnissen/hardware_introduction

## How it looks in Pluto
![image](https://user-images.githubusercontent.com/23193950/146673007-b1fa8fef-59c1-4840-86ac-67dc8bf886d2.png)

## How it looks in the static HTML
![image](https://user-images.githubusercontent.com/23193950/146673021-aa1ec748-962d-4040-b442-dc269e172146.png)

**Comment by fonsp** [comment]
Fixed in the PlutoUI update!
