### ISSUE TITLE
Making a new line spliting text can cause text to appear duplicated

### ISSUE THREAD

**Issue by max-sixty** [fonsp/Pluto.jl#1771]
When hitting return splits some text, the original text can sometimes remain displayed. Here's an example where `countmap` persists:

![Screen Cast 2021-12-19 at 12 54 48 PM](https://user-images.githubusercontent.com/5635139/146690499-1618d4b3-b6f2-4d57-b762-0b1f49dbf902.gif)

The text isn't there if the page is reloaded, or the text copy & pasted.

Here's the text for reference & reproducibility:

```julia
offsets = @p begin
	distances
	dictionary
	map() do __
		sort
		countmap
		filter(__) do (x, y)
			y[2] == 12
		end
	end
	# filter() do __
	# 	true
	# 	# 
	# end #filter(length(_[2])>0)
end
```

Thanks for making Pluto — it's such a wonderful app!

**Comment by fonsp** [comment]
Thanks! I'm adding this to our list in #1768
