### ISSUE TITLE
placeholder extension is broken

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1779]
![image](https://user-images.githubusercontent.com/6933510/147119976-cca8cda0-2089-4f37-a80d-612ff7f9fe4f.png)

**Comment by fonsp** [comment]
https://github.com/codemirror/codemirror.next/issues/649

**Comment by fonsp** [comment]
@pankgeorg i'm curious, how did that fix it?

**Comment by pankgeorg** [comment]
The right way!
