### ISSUE TITLE
Cyclic references between methods in cells

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#178]
At the moment Pluto considers the following example as cyclic references between two cells:

Cell A:
```
begin
	constructor(a) = a
	constructor(a, N) = refine(constructor(a), N)
end
```

and Cell B
```
refine(a, N) = constructor(a) * N
```

According to fonsps comment in issue #177 that should not be a cyclic reference.

**Comment by karlwessel** [comment]
Another MWE where this happen.
First cell:
```
f(x) = g(x+2)
```
Second cell:
```
g(x) = x<10 ? f(x+1) : x
```

Is there some easy fix or workaround for this problem? This basically doesn't allow you to implement certain recursive function calls.

**Comment by drdozer** [comment]
I also hit this, where I have a complex structure where parts need to know the whole during initialization. I get cyclic references between the initialization of the whole and the initialization of the parts.
