### ISSUE TITLE
Ignore .DS_Store files in file picker

### ISSUE THREAD

**Issue by jeremiahpslewis** [fonsp/Pluto.jl#1785]
I can't come up with a reason why one would want to load MacOS's `.DS_Store` files as a Pluto notebook and they're all over the place, so maybe they should be filtered out?

https://user-images.githubusercontent.com/4462211/147304124-ee2608db-f8a5-462a-a98d-cc6270d7fb3d.mov

**Comment by fonsp** [comment]
Let's see if https://github.com/JuliaLang/julia/issues/38841 gets anywhere
