### ISSUE TITLE
Open default browser on run

### ISSUE THREAD

**Issue by mgautam98** [fonsp/Pluto.jl#179]
Can we open the default browser with the localhost:port on run?

**Comment by mgautam98** [comment]
I think we can detect the platform and run a system call within julia to open the default browser with the mentioned port. 
Can I take this issue?

**Comment by fonsp** [comment]
Cool! It should just be [a single line of code](https://github.com/fonsp/Pluto.jl/blob/master/src/webserver/WebServer.jl#L222), but I also want it to work for the special case that you are running on WSL. Do you have WSL by any chance?

**Comment by mgautam98** [comment]
Yes, I am running WSL2 I have tested it with WSL2 It works fine.

**Comment by fonsp** [comment]
Nice! Make it a PR!

**Comment by fonsp** [comment]
Thanks again! Sorry it took so long

**Comment by MikaelSlevinsky** [comment]
This is a really cool feature :+1: but I might never change Safari as my default browser. For Pluto, is there a way to try/catch and look for Chrome/Firefox instead of default?

**Comment by MikaelSlevinsky** [comment]
Oh I'm sorry, I didn't realize Safari support has been fixed! https://github.com/fonsp/Pluto.jl/pull/289
