### ISSUE TITLE
Cursor jumps around when inputting brackets

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1790]
The cursor jumps to the beginning of the line when I input a bracket to index into an array: `my_array[`.

## How to reproduce

1. If I input `nonexistent_name[`, everything works fine.
2. Now define `existing_name = [1,2,3]`
3. In another cell, input `existing_name[`

__What I expect to happen?__ The cursor should remain where it was: `existing_name[|` (the `|` is the cursor)

__What happens instead?__ The cursor jumps to the beginning of the cell: `|existing_name[`

## Screencap

![screencap](https://user-images.githubusercontent.com/8695383/147588663-901c0fd4-67ae-4bce-9955-fa556721f201.gif)

Also, as shown in the GIF, after the cursor jumps to the beginning of the cell: `|a[]` ...and I input a question mark (I was surprized by the cursor jumping around), the cursor jumps again to _after_ the variable name: `?a|[]`. I would expect it to remain after my input, like `?|a[]`.

## Versions

- Julia 1.8.0-DEV.1137 (2021-12-14) and 1.7.1
- Pluto v0.17.4
- Safari 15.1 (15612.2.9.1.30, 15612)

**Comment by ForceBru** [comment]
The cursor can also jump _after_ the closing bracket, like `thing = a[]|`:

![Jump after the bracket](https://user-images.githubusercontent.com/8695383/147590188-f2885c69-0b44-4574-9fbc-e06b9f44a5ed.gif)

However, everything works fine if I input:

```
let
    a[|]
```

The cursor correctly stays between the brackets.

You can also write `thing = a[]|` without `let`, and the cursor will jump after the closing bracket too.

**Comment by ForceBru** [comment]
When writing a function's arguments, the _second_ (but not the first) argument disappears entirely when I input an opening bracket:

![t-rec_4](https://user-images.githubusercontent.com/8695383/147590677-5a747e03-e9ad-4a19-a39a-2686a3c9e546.gif)

## Steps to reproduce

1. Define some variable: `a = [1,2,3,4]` (this doesn't happen when the variable is _not_ defined)
2. Start typing `my_func(|`
3. The closing parenthesis appears, the cursor correctly stays _within_ parentheses: `my_func(|)`
4. Start writing the first argument: `my_func(a[|)`
5. The closing bracket appears, the cursor correctly stays _within_ brackets: `my_func(a[|])`
6. Type in some index and begin writing the second argument: `my_func(a[1], a|)`
7. Type in an opening bracket, `[`. The cell now looks like this: `my_func(a[1], )|`, so both `a` and the opening bracket disappeared!
8. Erase the current character with Backspace. The cursor jumps again and erases the opening bracket instead of the closing parenthesis: `my_func(a[1], a|)`

If the window loses focus at step 7, `my_func(a[1], a[])` correctly appears in the cell. If you focus on the window again, the cursor is correctly placed _between_ the last two brackets: `my_func(a[1], a[|])`

**Comment by pankgeorg** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by pankgeorg** [comment]
@ForceBru can you try this on Chrome too? Unfortunately I don't have Apple hardware so I can't reproduce this.

**Comment by ForceBru** [comment]
> @ForceBru can you try this on Chrome too? Unfortunately I don't have Apple hardware so I can't reproduce this.

None of these issues seem to be present when using Chrome 94.0.4606.71. However, I can consistently reproduce all of them in Safari, even on a fresh Pluto install...

**Comment by dralletje** [comment]
Related #1818 #1811 

Just keeping a log for my findings:

It only seems to happen for underlined elements.
It triggers for basically every non-alphanumeric character (Even a space!!).
It happens on safari

**Comment by dralletje** [comment]
@ForceBru just to be sure, can you try if it is fixed for you on main?

**Comment by ForceBru** [comment]
> @ForceBru just to be sure, can you try if it is fixed for you on main?

Yep, I'm now no longer able to reproduce any of this in Safari, so looks like everything works fine:

- After typing the `[` in `existing_name[`, the closing bracket appears and cursor correctly stays within brackets;
- After typing the `[` after `thing = a`, the closing bracket appears and the cursor stays within brckets
- Using indexing within function calls seems to work fine now

**Comment by dralletje** [comment]
Awesomeeer
