### ISSUE TITLE
Amazing project. Meta-issue

### ISSUE THREAD

**Issue by isentropic** [fonsp/Pluto.jl#180]
I just found this amazing project, keep up the work! Looking good so far.

I just wanted to suggest that you might perhaps want to have a pinned meta-issue with most important feature requests and bug reports, and layout a roadmap for potential contributros. Right now these issues look very unorganized, and perhaps overwheming for someone new. 

Feel free to close this. This meant to be a praise and a little suggestion

**Comment by fonsp** [comment]
Thanks for the suggestion! Could you post some links to projects that do this well? 🙃

**Comment by fonsp** [comment]
I did it! Thanks!

I'd love to chat for more tips on managing this project! (First time for me 😮) Send me email if you like! ([email](https://github.com/fonsp))
