### ISSUE TITLE
Pluto hangs when cell contains `(md" ", md"$t")`

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#1800]
Pluto notebook does not react anymore if the following MWE is passed to a new empty cell:
```
(md" ", md"$t")
```
Only happens with Pluto 0.17.4. On Firefox and Chrome. I cleared the cache for localhost and used a new temporary julia environment for testing this.

**Comment by lucifer1004** [comment]
This also happens when trying to insert a `$` into `md"a", md"|a"` (`|` denotes the cursor).

**Comment by fonsp** [comment]
@pankgeorg can you take a look?

**Comment by fonsp** [comment]
This is caused by #1533 , and we are working on fixing it, but it seems more difficult than we thought.

We will revert #1533 in the next release (0.17.5), to workaround this issue, and continue working on it...
