### ISSUE TITLE
`Slider` fails if in CommonMark string

### ISSUE THREAD

**Issue by chunjiw** [fonsp/Pluto.jl#1807]
This is actually #1637. Now I reproduced it in binder. I couldn't reopen that issue so I opened a new one here.

Thank you!

Video and gist:

https://user-images.githubusercontent.com/7267426/148140937-eb151f7e-4d92-4494-b4c3-c396038bfaa2.mp4

https://gist.github.com/chunjiw/d56949081764643ab9a5d205479bc53a

**Comment by icweaver** [comment]
oof, yea, I think that might be related to the changes to `Slider` mentioned [here](https://github.com/JuliaPluto/PlutoUI.jl/issues/154#issuecomment-995635266). The old version of the slider still looks to be working I think, but this is def a good thing to keep an eye on!

```julia
using PlutoUI.BuiltinsNotebook: OldSlider
cm"$(@bind cm_d OldSlider(0.5:10))"
cm_d
```

**Comment by chunjiw** [comment]
Indeed, this issue happens at 0.17.1 and after. I think you are right :+1:

**Comment by fonsp** [comment]
Hey! You can use https://github.com/JuliaPluto/MarkdownLiteral.jl instead of CommonMark until this is resolved

**Comment by fonsp** [comment]
You can use [MarkdownLiteral](https://github.com/JuliaPluto/MarkdownLiteral.jl) 0.1.1 (just released) instead of CommonMark while we work on this issue

**Comment by runjaj** [comment]
Any progress solving this bug? It drove me crazy a couple of days ago.

**Comment by fonsp** [comment]
Working on a fix: https://github.com/MichaelHatherly/CommonMark.jl/pull/58

**Comment by fonsp** [comment]
Fixed in the new CommonMark release ✅
