### ISSUE TITLE
👀👀 What are the future plans?

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#181]
We are **excited** to keep experimenting with a new scientific IDE - it's not just bug fixes from now on. 

### Have a look at the [developer notes](https://www.notion.so/Pluto-jl-a9982e79b7bb4c658e6216c15a9d4cab) 🎈

Our short-term plans are here: #280 
medium-term plans here: #281 
and wild future ideas here: [developer notes](https://www.notion.so/Pluto-jl-a9982e79b7bb4c658e6216c15a9d4cab)

**Comment by jonas-schulze** [comment]
It seems like it's no longer possible to read the notion deck without having an account. :confused:
