### ISSUE TITLE
Cell drag drop broken in Linux Chrome v97

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1810]
Continued from #1684

> Hi, ... well  it seem that this again is not working - my suspicion is chrome v97, because the fix in #1780 ceased to work, and so it doesn't work in 0.17.5 as well. I also tried Pluto 0.16.1 for double checking - the same.

_Originally posted by @j-fu in https://github.com/fonsp/Pluto.jl/issues/1684#issuecomment-1007349900_

**Comment by fonsp** [comment]
@j-fu Can you upload a video demonstrating the problem? It would be nice if you had the JavaScript console open while you record.

**Comment by j-fu** [comment]
ok issues crossed: #1809, video is there, though without console. Just had a look - there is no message in the console during D&D.  Is there anything else I can enable ?
