### ISSUE TITLE
Cursor Hijinks

### ISSUE THREAD

**Issue by jeremiahpslewis** [fonsp/Pluto.jl#1811]
Seems like Pluto's fancy variable recognition is going haywire, causing the cursor to appear ahead of a variable when a forward slash is used.

Movie: 

https://user-images.githubusercontent.com/4462211/148567095-6c3ac1ba-2328-4380-b775-6e330b2bb1fd.mov

Gist: 

https://gist.github.com/jeremiahpslewis/3c010a75166a5aa6ebf11753e6105da4

**Comment by fonsp** [comment]
Thanks! On which browsers is this happening?

**Comment by fonsp** [comment]
Might be linked to #1818

**Comment by jeremiahpslewis** [comment]
Safari 15.2

**Comment by jeremiahpslewis** [comment]
Agree, think this is the same issue.
