### ISSUE TITLE
Tables integration causes method ambiguities for `pluto_showable`

### ISSUE THREAD

**Issue by MichaelHatherly** [fonsp/Pluto.jl#1815]
A `Union{}[]` vector shows fine when `Tables` isn't loaded, but after loading that package additional `pluto_showable` methods are defined which cause a method ambiguity error.

![Peek 2022-01-10 11-50](https://user-images.githubusercontent.com/6144086/148761786-3c9eefa2-01ac-45af-a38e-14fe0729564c.gif)

Julia 1.7 and Pluto 0.17.5.

Error message:

<img width="736" alt="Schermafbeelding 2022-01-19 om 13 01 53" src="https://user-images.githubusercontent.com/6933510/150125875-225977d6-1beb-43aa-859f-69fd8115a47e.png">

**Comment by fonsp** [comment]
Thanks! Do you think the ambiguity is only for `Union{}[]` or for more types?

**Comment by MichaelHatherly** [comment]
I *think* it should only be `Union{}` that's the issue.
