### ISSUE TITLE
Pkg 'add Pluto' fails in 1.7.1 on Windows

### ISSUE THREAD

**Issue by nyambol** [fonsp/Pluto.jl#1821]
Running 'add Pluto' fails on 1.7.1. It worked and Pluto is loaded on Julia 1.6.1. Screenshot attached to prove it. Video shows failed 'add' on v 1.7.1.  I only installed the new version because of the "unsupported" message on 1.6. Unless there's an immediate and easy fix -- e.g., something messed up with my installation --, I'll just revert to the working version. 

Processor	Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz   3.40 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	21H1
Installed on	‎9/‎4/‎2021
OS build	19043.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

![pluto-julia-1_6_1](https://user-images.githubusercontent.com/4068664/149022273-cee49b34-c5fc-4bd5-9c9f-78d1cc6cb264.png)

https://user-images.githubusercontent.com/4068664/149022450-48b0aab7-2640-4bcd-b9fe-a4f46761b12d.mp4

**Comment by fonsp** [comment]
Try reinstalling your registry

```julia
julia> general_path = joinpath(DEPOT_PATH[1], "registries", "General")
"/Users/fons/.julia/registries/General"

julia> rm(general_path; recursive=true)
```

If that doesn't work, try the Julia helpdesk on Zulip or Slack. They will be able to provide better advice since this is a problem with Julia, not Pluto: https://julialang.org/community/
