### ISSUE TITLE
Line number gutter to narrow for long cells

### ISSUE THREAD

**Issue by pfitzseb** [fonsp/Pluto.jl#1826]
![Peek 2022-01-18 11-48](https://user-images.githubusercontent.com/6735977/149923397-e15bcb6a-660c-415c-ba3e-201a0250180a.gif)

Two options:
- fixed gutter width so the editor content doesn't jump around
- measure text and set gutter width dynamically depending on cell length

**Comment by lucifer1004** [comment]
I think enough space for three digits should be OK? Putting more than 1,000 lines of code in a cell is kind of unrealistic.

The problem of dynamic gutter width is that, if we only measure the length of one cell, then different cells would have different gutter widths, which is unpleasant. Also, this would be more complex.

What do you think, @fonsp ?

**Comment by lucifer1004** [comment]
I have tested locally, by adding just 2px (29 => 31), we can allow up to 999 lines.

**Comment by pfitzseb** [comment]
> I think enough space for three digits should be OK? Putting more than 1,000 lines of code in a cell is kind of unrealistic.

Pretty sure the notebook I initially saw this in had 900+ lines in that cell.

A fixed width (31px) gutter seems like the best solution though.
