### ISSUE TITLE
Local assets in HTML output

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#183]
The web browser blocks reading local files (for good reason), which actually helps with our long-term reproducibility goal.

However, the workarounds are currently a bit technical (like base64 encoding your assets) - this could be made simpler.

**Comment by Pocket-titan** [comment]
Why not have the webserver resolve the files & send them over to the client? Probably best to either require files to be in the specific notebook directory, or copy them over the first time you import them into your notebook, for the sake of reproducibility.

**Comment by fonsp** [comment]
See #171

**Comment by fonsp** [comment]
I am experimenting with the base64 trick:

![image](https://user-images.githubusercontent.com/6933510/87657627-604f9100-c75b-11ea-91bd-f9379fbd7b0d.png)

**Comment by fonsp** [comment]
This is solved by the PlutoUI package (`PlutoUI.LocalResource`), and there's a new sample notebook explaining how to use it! (And why you should use `PlutoUI.RemoteResource` instead 🙃)

**Comment by saf-dmitry** [comment]
> This is solved by the PlutoUI package (`PlutoUI.LocalResource`), and there's a new sample notebook explaining how to use it! (And why you should use `PlutoUI.RemoteResource` instead 🙃)

@fonsp Thank you for the solution. Could you please point me to the notebook you mentioned? The best I could find is the [Images](https://featured.plutojl.org/basic/images) notebook, but it only explains usage of `PlutoUI.Resource` and Images package.
