### ISSUE TITLE
fails to run when JULIA_NUM_THREADS=auto

### ISSUE THREAD

**Issue by Spirarel** [fonsp/Pluto.jl#1831]
[Julia 1.7 allows the system to determine how many threads to start with](https://docs.julialang.org/en/v1/manual/multi-threading/#Starting-Julia-with-multiple-threads)

Having this bash variable set will cause Pluto to crash when attempting to run.

https://user-images.githubusercontent.com/10119394/150274138-5d1d79f3-0305-4649-856c-441770cb7718.mov

Julia 1.7.1
Pluto v0.17.5
MacOS 11.6.2

**Comment by fonsp** [comment]
Thanks! This will be fixed in the next release, #1814
