### ISSUE TITLE
Multiplication by juxtaposition highlights the entire second expression in red

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1836]
Code:

```julia
function D(θ::AV{<:Real}, b::Real, r::AV{<:Real})
	@assert length(θ) % 3 == 0

	N = length(r)
	K = length(θ) ÷ 3
	α, μ, σ = θ[1:K], θ[K+1:2K], θ[2K+1:end]
	var = σ .^2

	sum(
		α[k] * (
			sum(
				α[h] * normal_pdf(μ[k], μ[h], 2b + var[k] + var[h])
				for h ∈ 1:K
			)
			- 2sum(
				1/N * normal_pdf(μ[k], r[j], 2b + var[k])
				for j ∈ eachindex(r)
			)
		)
		for k ∈ 1:K
	)
end
```

Highlighting:

![highlighting](https://user-images.githubusercontent.com/8695383/150525596-c6d5e0b0-d6a5-442d-afe0-238af3a9fc04.png)

1. The _entire_ second inner sum is highlighted in red. `2 * sum(...)` instead of `2sum(...)` is highlighted correctly
2. The `K` in slices (the second one in `θ[K+1:2K]` and the first one in `θ[2K+1:end]`) is highlighted in red too
3. `b` in `2b` is highlighted in red as well

Looks like the last two points are a feature, but the first one is just too much highlighting, to the point that the Julia syntax in the sum isn't highlighted at all (or this highlighting is hard to see because everything is red).

- Pluto v0.17.6
- Chrome 96.0.4664.110

**Comment by fonsp** [comment]
@dralletje

**Comment by dralletje** [comment]
>:(

Hahaha

Okay okay, I want to test out a little bit more before we water it down all the way..
Just probing, but would it be too much to ask for a `*` between `2` and `sum(...)` if you want deeper highlighting? @ForceBru 
Are there any functional differences between `2K` and `2*K`, or "just" readability?

Maybe we shouldn't do any special highlighting for coefficients... :/

**Comment by fonsp** [comment]
I would say that the two `K`s in this expression:
```julia
[K+1:2K]
```
are the same `K`, and they should get the same color. I see that one more as "two times the `K` thing", and not "the 2K thing".

Same with the bug `sum` expression: it's 2 times the "sum thing", not the "2sum" thing.


But in the original motivation: `2u"mg"`, I agree! It's not "2 times the milligram thing", it's "the 2 milligram thing". Maybe we can do special highlighting for `Prefix(Number,StringMacrocall(String))` (pseudocode) ?

**Comment by ForceBru** [comment]
> would it be too much to ask for a `*` between `2` and `sum(...)` if you want deeper highlighting?

Yes, absolutely: this basically disables highlighting for the _entire_ `sum` syntax, which is super strange and is more of a limitation than a feature, IMO. I mean, why highlight the _whole_ expression in red if it can be highlighted like standard Julia syntax, which it is?

Also, red (maybe this is more orange, but that's still more red than highlighting for `function`, `for` and `end`) normally means "warning" or "error" or "invalid syntax" or "this is bad", but there's no error or invalid syntax in this code, so why color it red?

Moreover, the `K` in `2K` isn't special: it's not a keyword or invalid syntax. So why color it differently from any other variable?

> Are there any functional differences between `2K` and `2*K`, or "just" readability?

Apparently, `2K` has different precedence from `2*K` (https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#man-numeric-literal-coefficients):

> The precedence of numeric literal coefficients used for implicit multiplication is higher than other binary operators such as multiplication (`*`), and division (`/`, `\`, and `//`)

However, I think this isn't unintuitive enough to be highlighted with such a bright color, or highlighted at all.

**Comment by fonsp** [comment]
https://github.com/JuliaPluto/lang-julia/pull/1

**Comment by dralletje** [comment]
> Maybe we can do special highlighting just for `Prefix(Number,StringMacrocall(String))` (pseudocode), and leave the rest ? Is that something we can currently do?

Yeah was worried we'd do that...
But I think it is for the better :D

**Comment by icweaver** [comment]
"juxtaposition was a mistake" - some wise julia user
