### ISSUE TITLE
Too much indentation after inserting new line in the middle of a line

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1837]
Code:

```julia
let
	lx = Float64[]ux = Float64[]
end
```

1. Put the cursor after the first pair of brackets: `lx = Float64[]|ux = Float64[]`
2. Press Enter
3. Now the cell looks like this:

![indentation](https://user-images.githubusercontent.com/8695383/150527684-16082191-177b-4a07-889f-757cb9e5eef7.png)

The line with `ux = Float64[]` should have the same level of indentation as `lx = Float64[]`.

A more extreme case (repeat steps 1-2 for each new line):

![indentation2](https://user-images.githubusercontent.com/8695383/150528160-933c61e6-582a-4967-9fec-e30b7165aabd.png)

-----

The following cases work fine.

When the two expressions are separated by a semicolon:

1. Put the cursor after the first pair of brackets: `lx = Float64[]|ux = Float64[]`
2. Input a semicolon: `lx = Float64[];|ux = Float64[]`
3. Press Enter
4. `ux = Float64[]` is indented just enough

When the cursor is at the end of line:

1. Delete everything after the first pair of brackets: `lx = Float64[]|`
2. Press Enter
3. The cursor jumps to the next line with the correct level of indentation

- Pluto v0.17.6
- Chrome 96.0.4664.110

**Comment by dralletje** [comment]
Odd, lezer parses it correctly...
