### ISSUE TITLE
Add "undo" for deleting one or several cells

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#184]
I just deleted a cell I needed and don't think I can get it back!

**Comment by fonsp** [comment]
#110

**Comment by fonsp** [comment]
(I'm sorry!)

**Comment by fonsp** [comment]
Since universal `Ctrl+Z` is still a long way off, we could add a bubble in the corner of your screen when you delete a cell:
```
Cell deleted! UNDO
```
like in gmail

**Comment by fonsp** [comment]
@Pocket-titan suggested that deleting should require a second confirmation click

**Comment by fonsp** [comment]
![pluto_revival](https://user-images.githubusercontent.com/6933510/87608592-a297b480-c700-11ea-8e05-620f4e3972e4.gif)

**Comment by SimonEnsemble** [comment]
the undo delete cell button disappeared before I could click it!

another lost cell :cry: 

how can I undo once the button disappears?

**Comment by briochemc** [comment]
I must have missed something if this is closed: How does one undo multiple cell deletions?

**Comment by fonsp** [comment]
select multiple cells by dragging a selection box from the right or from between cells

**Comment by briochemc** [comment]
Oh I'm not asking how to *select* multiple cells, I'm asking how to undo the deletion of several cells (as per the title of this issue). Maybe a GIF will help: Below, I delete the two bottom cells (`b=2` and `c=3`), and then I can undo the last deletion (of the `b=2` cell), but then I cannot go further back (and bring back cell `c=3`), right?

![undo_several_deletions](https://user-images.githubusercontent.com/4486578/107622617-3425cf80-6cac-11eb-90b3-bb9b8a5f4a2c.gif)

**Comment by fonsp** [comment]
No, #110
