### ISSUE TITLE
Log UI mildly confusing when multiple presented

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#1845]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/1438610/150658827-f692d96f-64bd-47d9-90be-96166401a35b.png">

Not sure what's going on here, one error box is occluding another. Also if I mouseover the box, it shifts left to cover the other box behind it.

v0.17.7, Julia 1.7.1

**Comment by BioTurboNick** [comment]
Ah, I see what's happening. The box wasn't moving, it was revealing a similar error from underneath.

It's an interesting way to do this, but it looks and feels like a rendering error.

**Comment by BioTurboNick** [comment]
Maybe a cascade down and to the right, instead of just to the right? Maybe they could be numbered in the part that peeks out?

Part of my confusion came from absent-mindedly mousing over from the left, which raised the lower error up and completely covered the higher error, making it appear to shift. IMO needs a way to make sure that when you're looking at one of the lower errors, you still retain the context that the other errors still exist?

**Comment by fonsp** [comment]
Fixed by #2297
