### ISSUE TITLE
LaTeXStrings not displayed correctly

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#185]
For some reason, `LaTeXStrings` strings, e.g. as produced by `Latexify.jl`, are not displayed in LaTeX (despite having a suitable `show` method defined).

**Comment by fonsp** [comment]
Can you link to the `show` method that you mean?

**Comment by dpsanders** [comment]
Hmm, apparently I was not quite right.
LaTeXStrings defines a show method for the `text/latex` mime-type [here](https://github.com/stevengj/LaTeXStrings.jl/blob/684defa4a6803a61516f2a9f24f9d02770750b42/src/LaTeXStrings.jl#L51)

Then apparently IJulia does something special with that but I can't actually locate where; I think it passes it through to Jupyter somehow.

I can't see where Pluto implements display of mime-types, but the following hack seems to work to convert a `LaTeXString` object to a `md"..."` object that displays the equation:

```jl
convert_to_md(s::LaTeXString) = md("\$$(s.s)\$")
```

Example:
```jl
convert_to_md(latexify(:(y = x^2)))
```

**Comment by dpsanders** [comment]
This seems to work, but I'm not sure that it's the correct approach:
```jl
Base.show(io::IO, ::MIME"text/html", s::LaTeXString) = show(io, convert_to_md(s))
```

**Comment by fonsp** [comment]
Thanks! We will add the text/latex MIME type to Pluto.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/87250917-7bbf5100-c468-11ea-97f6-dd626c103440.png)
