### ISSUE TITLE
Logging doesn't respect `maxlog`

### ISSUE THREAD

**Issue by Joel-Dahne** [fonsp/Pluto.jl#1858]
https://user-images.githubusercontent.com/13287213/151267144-54483481-c3fa-4aa5-ae6d-f7100b605e8d.mp4

The new logging feature for Pluto doesn't support the `maxlog` argument for logging. Here is a link to the [notebook](https://gist.github.com/Joel-Dahne/851ad2768a4e3495b7e6edec9846c166).

I can also maybe note that I had performance issues with Pluto when there was a very large number of logs. You can try to increase the counter in the loop to, say, 10000, and at least for me the webpage grinds to a halt. In my case it was only a problem because `maxlog` was not respected though.

**Comment by fonsp** [comment]
(This is referring to the "conventional meaning" section of https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.@logmsg )

**Comment by roland-KA** [comment]
Same problem here. The default value should be > 1. Even when only a few lines are printed, the output gets unreadable as in the following example:

![](https://user-images.githubusercontent.com/80126696/151172429-b8600973-ce6d-4a9e-8900-e66ca427de10.png)

The message '_Attempting to evaluate 40 models._' covers here one (or several) message beneath.
