### ISSUE TITLE
Test if Pluto initialized and running

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#186]
In reference to https://github.com/JuliaGraphics/Luxor.jl/issues/90 (adding support for Pluto), is there a way to check whether Pluto is running? At the moment I run this for Jupyter:

```
(isdefined(Main, :IJulia) && Main.IJulia.inited) ? jupyter = true : jupyter = false
```

so want something similar for Pluto. Perhaps 

```
(isdefined(Main, :PlutoRunner) 
```

might be sufficient - wonder if there's anything better?

**Comment by fonsp** [comment]
Hey!
Fun to hear from you! I actually wrote a workaround once to make Luxor work with Pluto - I will talk more about it in the issue that you mentioned.

About detecting whether you are in Pluto - this would work, but we **don't really want this to be something that other packages rely upon**, for two reasons.

First, we think that it _should_ not be necessary. The only code that would need to specialize on the programming environment is _display_ code and _interaction_ code. Interaction code is a bit trickier (feel free to open an issue about it), but for display code: Julia has this very cool multimedia display system built in, and we want to use it!

Pluto's display system is a lot simpler than that of Juno and Jupyter - calling `show` or `print` from (package) just prints to the terminal (like in the REPL), and there are no internal systems to hook into. _The only way to display something in Pluto is by having a cell return it._ Rich output can be created by defining `show` methods for your types, for different MIME types.

The second reason is that Pluto is still in heavy development, including the runtime system, and we want to be free to make breaking changes in this area. (Breaking from the perspective of code for running in Pluto.) We want to find the right architecture _before_ breaking it open for customization and specialized code.

Let's think together about the right solution for Luxor, I really want to make it work - it would be a very cool sample notebook!

**Comment by cormullion** [comment]
Great, thanks!

**Comment by cormullion** [comment]
Fixed by https://github.com/JuliaGraphics/Luxor.jl/pull/91. Thanks!
