### ISSUE TITLE
ProgressLogging: suppressed logging in Turing.jl

### ISSUE THREAD

**Issue by joshualeond** [fonsp/Pluto.jl#1862]
Hi, thanks for your work! 

This issue is related to my comments on this other [issue](https://github.com/fonsp/Pluto.jl/issues/1434#issuecomment-1019992945). I put together a short example that should show a progress bar on the `sample` call. Here' s the gist: [link](https://gist.github.com/joshualeond/4ca8c4c7a71cb577598bb232013148ad#file-turing-log-example-jl-L39)

I'm not 100% sure this is an issue with `Pluto.jl` and it may be on the `AbstractMCMC.jl` side. However, this is what you see when running in the terminal:
![image](https://user-images.githubusercontent.com/3802502/151429633-2d7128b7-9e67-48c6-886d-336df358e36f.png)

Here's the info from the original issue:
---

I see this issue is now closed due to the awesome new updates to `Pluto.jl` with logging and the `ProgressLogging.jl` functionality. So the behavior we should see now is more like the following in `Pluto.jl`:

![image](https://user-images.githubusercontent.com/3802502/150664413-49b448a1-3d0e-444d-b517-999881c800a1.png)

However, when using `Turing.jl` and the `AbstractMCMC.jl` packages within `Pluto.jl` the progress info still seems to be suppressed for some reason. I do now see the logging messages but the progress bar still isn't working:

![image](https://user-images.githubusercontent.com/3802502/150664471-8df4d487-e330-4068-97e0-9d1510090c24.png)

@sethaxen do you think this is an issue on the `Pluto.jl` side or more on the `Turing.jl` side?

_Originally posted by @joshualeond in https://github.com/fonsp/Pluto.jl/issues/1434#issuecomment-1019410851_

**Comment by Pangoraw** [comment]
Thanks for the very detailed report! It should be fixed in https://github.com/fonsp/Pluto.jl/commit/c4a0f53a3f141ef76a0815f2273f4802d485e5cd

**Comment by joshualeond** [comment]
Awesome, that was fast! This is very cool. Thank you.

https://user-images.githubusercontent.com/3802502/151612362-3c4bad4c-e891-45ff-a230-6d31521a6695.mov
