### ISSUE TITLE
"Cyclic references" error despite different variables

### ISSUE THREAD

**Issue by ParadaCarleton** [fonsp/Pluto.jl#1863]
I get a cyclic references error here:
![image](https://user-images.githubusercontent.com/71727937/151603087-1fb33057-c318-476a-837f-ee43ffa8d996.png)

However, the first `m` is a local variable defined only inside a function, so there's no cyclic reference here.

**Comment by Pangoraw** [comment]
Thanks for reporting! From which package is `@model` coming from ?
I tried with Turing.jl but could not reproduce it.

**Comment by Pangoraw** [comment]
Also from the syntax highlighting, it seems that you are not using the latest version of Pluto.jl. Could you try to update it and report back ?

**Comment by ParadaCarleton** [comment]
> Also from the syntax highlighting, it seems that you are not using the latest version of Pluto.jl. Could you try to update it and report back ?

Oh, hmm. I'm using the VSCode plugin, which only seems to go up to 1.7.5; could that be it?

**Comment by fonsp** [comment]
@ParadaCarleton What packages are you using? Can you send us a notebook file?

Try running it without the VS Code plugin (still very experimental) and let us know if this is still an issue

**Comment by fonsp** [comment]
Closing this for now because it sounds like this has been fixed in a new release, but @ParadaCarleton let us know if you find otherwise!
