### ISSUE TITLE
Allow different maths font

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#187]
Personally I am not a fan of the Computer Modern font for maths.
E.g. Jupyter uses some version of Times (I believe), which I (personally) prefer.

Would it be possible to allow this to be configured somehow?

**Comment by fonsp** [comment]
We are not doing any customization _yet_, because this slows down development.

I've [added your suggestion to the built-in suggestion box](https://github.com/fonsp/Pluto.jl/issues/182) 📬 - we will come back to it when we start doing customization
