### ISSUE TITLE
Package name collision breaks Pluto package manager

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#1873]
If you have two registries, each of which contain a package with the same name, Pluto breaks in an unclear way when you add any packages with `using`. In the notebook, the error says it can't add the first package listed. In the terminal output, it sometimes just says `"/tmp/jl_u1Skga/Project.toml": No such file`, one time it showed the true cause, and that a UUID needs to be specified. However, I don't think there's a way to do that with Pluto's package manager?

**Comment by fonsp** [comment]
Continued in #1937
