### ISSUE TITLE
Pluto disconnects after idle

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#188]
Pluto often seems to disconnect randomly after a period of inactivity, and
the message

``` 
[ Info: Client 1ch2b7 stream closed.
```
appears on the REPL that I launched Pluto from. Is this expected, and how can I prevent it?

**Comment by dpsanders** [comment]
Bump. Just happened again...

**Comment by fonsp** [comment]
Thanks! Just so we're on the same page - you were working on a notebook and you had some changes to the code that you hadn't saved yet, left for a while, and then there was no way to keep those changes?

**Comment by dpsanders** [comment]
I think the changes were still there when I reloaded the page. I just come back to a notebook and suddenly can't make any changes for no apparent reason. But scrolling up to the top shows that it disconnected. Reloading the page solves the problem.

**Comment by fonsp** [comment]
Okay. The Disconnected warning should always be on screen without scrolling - what browser do you use?

**Comment by dpsanders** [comment]
Maybe it is on screen actually? I use Chrome.

**Comment by fonsp** [comment]
#370

**Comment by fonsp** [comment]
Fixed!

**Comment by dpsanders** [comment]
Thanks!!
