### ISSUE TITLE
Don't create `frontend-dist/*.map` files?

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1884]
Because they are very big, 10MB total, which is half of our total asset size:

```
➜  frontend-dist git:(main) du -ch *.map | grep total
 10M	total
➜  frontend-dist git:(main) du -ch * | grep total 
 21M	total
➜  frontend-dist git:(main) 
```

**Comment by dralletje** [comment]
No sourcemaps?? :(

**Comment by fonsp** [comment]
Maybe we can:
- disable minification (which will only affect our own code, because our deps are already minified). That way the line numbers in stack traces can still be used to debug.
- write a [custom parcel packager that skips sourcemap info for external sources](https://parceljs.org/plugin-system/source-maps/#concatenating-sourcemaps-in-packagers)
- just remove the sourcemaps because: we almost never get a bug report with a screenshot of the devtools, and if we can reproduce the bug, then we can look at our own (unbundled) stack trace. If we can't reproduce a bug... then we probably don't fix it.

**Comment by dralletje** [comment]
I'll give approach 1 a try today

**Comment by fonsp** [comment]
https://github.com/JuliaPackaging/RelocatableFolders.jl/pull/12

**Comment by fonsp** [comment]
I [disabled source maps](https://github.com/fonsp/Pluto.jl/commit/e2f955e04c0f1abdcb2aa049c5d0a487f61cd1f9) because I want to do a release today. But let's find a solution :)

**Comment by dralletje** [comment]
Nice!!
