### ISSUE TITLE
Zombie process left behind with each `Pluto.run()`

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#1899]
A zombie process is created every time Pluto.run() is called, and it isn't removed when the server is terminated with Ctrl+C. Exiting Julia does remove it.

I suppose it's unclear if this is a problem with Julia (1.7.1, 1.8.0-DEV.1225) or with Pluto (0.17.5-0.18.0).

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1438610/152646725-0da6c749-b713-4320-bd31-6c88fbdbe9f9.png">

**Comment by fonsp** [comment]
Have you set any custom launch parameters beside `port, `host` or `require_secret...`?

**Comment by BioTurboNick** [comment]
We just set the `secret`

**Comment by fonsp** [comment]
@BioTurboNick Could you explain the screenshot? I'm not sure I know how to read these numbers. 😅

I see two Julia processes instead of one, do you mean that there are two zombie processes? Is the second process using 0 bytes of memory?

**Comment by BioTurboNick** [comment]
Sure! The `S` column indicates status, and a status of `Z` means zombie. It's taking up no memory resources, except a PID slot on the system, similar to leaving a file handle open (I think). I think the intent generally is that it ensures a parent process can obtain the exit code for the child process before it's fully terminated?

So PID 10329 here is the Julia process running the Pluto server, and whenever a notebook is opened, it becomes active, as well as the notebook process that gets created. The zombie process just sits there.

**Comment by fonsp** [comment]
Thanks! And what command do I run to see this?

**Comment by BioTurboNick** [comment]
This is the `top` command, and you can filter processes by typing `o` and then `COMMAND=julia`

**Comment by fonsp** [comment]
Looks like `top` on MacOS is different :( It would be great if someone on Linux (who actually knows what a process is, help) would look into this!

**Comment by fonsp** [comment]
I would be interested which of these tests https://github.com/fonsp/Pluto.jl/blob/main/test/runtests.jl create the zombie (experiment by commenting out all includes except one). 

Only Configuration.jl and webserver.jl call `Pluto.run` (and run the web server), most others use SessionActions and such.

**Comment by BioTurboNick** [comment]
Ah, I've figured it out.

I think it occurs if `launch_browser` is `true` on a system that doesn't have a browser.

```
Pluto.run(Pluto.ServerSession(; options = Pluto.Configuration.from_flat_kwargs(; launch_browser = true)))
```

**Comment by BioTurboNick** [comment]
In fact, it might be because `xdg-open`, the command used to launch the browser, is not installed on the system. It seems to happen for any missing command that you attempt to `run`. So looks like actually a Base Julia issue.
