### ISSUE TITLE
Using upticks to format code in markup leads sometimes to erratic behavior of the cursor and/or the editor

### ISSUE THREAD

**Issue by roland-KA** [fonsp/Pluto.jl#1900]
When writing a markdown paragraph with several in-line code elements which are formatted using upticks (like \`x\`) the behavior of the cursor and/or the complete editor sometimes gets erratic. E.g.
- the cursor jumps to the end of the line after each character entered
- pressing 'return' doesn't create a newline at the cursor position, but adds (several) new lines above oder below the paragraph or after the closing """ for markdown (see video; there I'm pressing several times return after the last word of the paragraph)
- positioning the cursor with the mouse doesn't place the cursor at the mouse position but elsewhere in the text (or it can't be repositioned at all)
- entering a closing uptick results in two closing upticks; e.g. writing \`x\` results in `x``
- execution of the cell using Ctrl-Return or Shift-Return doesn't work any more

It only happens when there are several lines of text (and typically after some time of editing). So I couldn't produce a more minimal example than the one in the video.

https://user-images.githubusercontent.com/80126696/152652938-470a57ff-390f-42b8-9322-efd0e8444bfa.mov

I'm using Pluto 0.17.7 on Safari (MacOS) with a German keyboard.

The issue may be related to #1528 and #1563.

**Comment by dralletje** [comment]
Can you confirm still happens with Pluto 0.18?

**Comment by roland-KA** [comment]
I've testet on Safari and Chrome and the problem seems to be solved with 0.18. So I close the issue.
