### ISSUE TITLE
Notebooks hangs when `maxlog` is used in logging and includes `maxlog` in output

### ISSUE THREAD

**Issue by Joel-Dahne** [fonsp/Pluto.jl#1902]
https://user-images.githubusercontent.com/13287213/153057977-00c3b27e-5d57-45ea-a6ce-c0880ce5a233.mp4

Support for `maxlog` in logging was recently added in #1877. However I have issues with Pluto getting stuck on the second run of a cell with `maxlog` specified. In the video I stop after 10 seconds, but it doesn't finish after that either. Link to [notebook](https://gist.github.com/Joel-Dahne/202469a19f543575b8d634448f93d6fe).

One part of the code added in #1877 was
```julia
maybe_max_log = findfirst(((key, _),) -> key == "maxlog", next_log["kwargs"])
if maybe_max_log !== nothing
    n_logs = count(log -> log["id"] == next_log["id"], running_cell.logs)
    try
        max_log = parse(Int, next_log["kwargs"][maybe_max_log][2] |> first)

        # Don't show message with id more than max_log times
        if max_log isa Int && n_logs >= max_log
            return
        end
    catch
    end
end
```
I was able to get it to work for be by changing the `return` to `continue`. However I don't understand enough of Pluto's code to know if this is the proper fix. 

I would also propose to follow the default for logging in Julia and not include the `maxlog` argument in the log message
```julia
julia> for i in 1:10
           @info "Some info" i maxlog = 2
       end
┌ Info: Some info
└   i = 1
┌ Info: Some info
└   i = 2
```
I was able to get this behavior by adding the line
```julia
deleteat!(next_log["kwargs"], maybe_max_log)
``` 
inside the `try`-statement. But again I don't know enough about Pluto to know if editing the log-message is allowed.

And thank you for adding support for logging! I think it can be very helpful!

**Comment by Pangoraw** [comment]
Good catch! Don't hesitate to open a pull request;

**Comment by Joel-Dahne** [comment]
I can try to prepare a PR, possibly later today!
