### ISSUE TITLE
Pluto Failed to register using Julia on Windows 11, Why?

### ISSUE THREAD

**Issue by itisnara** [fonsp/Pluto.jl#1907]
### Discussed in https://github.com/fonsp/Pluto.jl/discussions/1906

<div type='discussions-op-text'>

<sup>Originally posted by **itisnara** February  9, 2022</sup>
Hello Pluto Guru,
Greetings!
My little background on using Julia:
I am a bit late comer to Julia and of course Pluto.
I was serious on doing work on Julia after hearing all good things about Julia for computational thinking as you call i.
I heard Pluto guru talk and heard introduction of MIT computational thinking Course.
I wanted to experiment using Pluto Notebook so I can create Pluto notebook for my field of expertise (including computational numerical methods and FEM modelling structures and its analyses.)
I am a retired University professor, versatile with a "BIT" of experience using FORTRAN, C, C++, Javascript, Java, Matlab, Maple, Mathematica, Octave  etc.
None of these languages came close to Julia;s plus point in terms of mathematical operators and functional programming using Julia, as I hear on YouTube.

Coming to the issue, I tried to use the PLUTO first time, using pkg add Pluto, and it failed on my HP computer with Windows 11 installed recently.  ( i heard the Pluto Guru talk on the installation of PLUTO as spoken on the Intro MIT course.)

Here are the two files: Command line snip and my HP computer system, info notepad file.

![Screenshot-of-add-Pluto-Pks-Failed- 2022-02-09 201509](https://user-images.githubusercontent.com/24774156/153321238-37497959-3640-40ee-8518-2e310ea47ba3.png)

and
[Nara-Desktop-System-Info-Feb9-2022.txt](https://github.com/fonsp/Pluto.jl/files/8037407/Nara-Desktop-System-Info-Feb9-2022.txt)

If you need more info, please do not hesitate to write to me at 'itisnara@gmail.com'

Please reply if you found why PLUTO did not get registered by Julia.

I wish to work deligently on Julia and Pluto to become a BIT more confident of using Julia/Pluto on analyzing structures.

Thanks for help
Nara
1-734-377-7470 if need to call me at your convenience

PS: I see only three section of MIT course on YOU Tube.  How to get other sections of them full 15 week course?</div>

**Comment by icweaver** [comment]
Just directing future discussion to the duplicate post opened here https://github.com/fonsp/Pluto.jl/discussions/1906

**Comment by fonsp** [comment]
Solution here:  https://github.com/fonsp/Pluto.jl/discussions/1906
