### ISSUE TITLE
How to display a string with newlines

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#191]
If I have a String `s = "some text.\nAnd some text on the next line."`, how can I make Pluto display it as 
```
some text.
And some text on the next line.
```
instead of
```
 "some text.\nAnd some text on the next line."
```

**Comment by karlwessel** [comment]
I have the feeling that this should be easy, but I have a hard time finding/googling a solution for it. 

In the REPL i could do `println(mytext)`.

**Comment by fonsp** [comment]
Maybe it's time to make a Pluto standard library for stuff like this

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/84925591-6bff5780-b0ca-11ea-97a2-28cc20d1d69f.png)

**Comment by fonsp** [comment]
(You can scroll the output horizontally)

**Comment by karlwessel** [comment]
Thanks, works nicely, but seems like a bit of a clutter :).

**Comment by garrison** [comment]
I was just in need of this and am thankful to find this solution.  It would be nice if it were documented -- seems like a reasonable thing to mention under https://github.com/fonsp/Pluto.jl/wiki/%E2%9A%A1-Writing-and-running-code section on `print` and `display`.

**Comment by fonsp** [comment]
# Solution

Use `Text`:

```julia
 s = "hello\nworld!"
```

```julia
Text(s)
```
