### ISSUE TITLE
Remove cells with hidden output and code from pdf

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#192]
I would like to hide some cells like `using SomePackage` completely when creating a pdf version. 

The closest I can get to this is by hiding the the cells output by adding a semicolon to the last line and hiding the code itself using the according GUI element. However the cell still takes some vertical space which is ok for the browser display. However when I want to create a pdf it would be nice if it would not only hide all GUI elements but also empty cells like that.

**Comment by fonsp** [comment]
You could move them to the bottom?

**Comment by karlwessel** [comment]
That could work, thank you!

**Comment by fonsp** [comment]
Add this to the built-in suggestion box if you like
