### ISSUE TITLE
Docstring is duplicated when rerunning cells

### ISSUE THREAD

**Issue by adrhill** [fonsp/Pluto.jl#1932]
On Pluto `v0.18.0`, rerunning the cell of a struct that a docstring depends on will duplicate the content of that docstring:

https://user-images.githubusercontent.com/20258504/154684498-a75144d7-9ee4-45f5-92bb-f9abbc1d30a8.mov

The notebook:
```julia
### A Pluto.jl notebook ###
# v0.18.0

using Markdown
using InteractiveUtils

# ╔═╡ 7b38d4b0-90b6-11ec-25bc-19b9d89bc61d
struct Bar end

# ╔═╡ a5ee50af-3243-480f-8a52-a47f9aa34e5e
"""
My doc string
"""
foo(b::Bar) = b

# ╔═╡ Cell order:
# ╠═7b38d4b0-90b6-11ec-25bc-19b9d89bc61d
# ╠═a5ee50af-3243-480f-8a52-a47f9aa34e5e
```

**Comment by icweaver** [comment]
I think was reported here as well https://github.com/fonsp/Pluto.jl/issues/1708

**Comment by adrhill** [comment]
Ah sorry, didn't spot this when looking through the open issues.
Feel free to close! :)

**Comment by fonsp** [comment]
Thanks adrian!! You can subscribe to the other issue 🔔
