### ISSUE TITLE
Feature Request: Make better use of blank space on large displays

### ISSUE THREAD

**Issue by Uroc327** [fonsp/Pluto.jl#1936]
I have a 16:9 4k screen and the column with the cells occupy slightly more than 1/5 of the width of my screen. This feels very wasteful, in particular when there are long lines of data output (e.g. `DataFrame`s with many colums or deeply nested structs) that are cut off by this blank space.

It would be nice if one could
1) Increase or decrease the whitespace between display border and column and
2) allow multiple columns side by side.

Number 1 could be implement somewhat easy, I guess, just by allowing the user to click and drag the edges of the column farther to the left or to the right, keeping the column of cells centered.

Number 2 is a little more involved, but I feature I'd enjoy to see. This would require some fixed pagination, I guess. When the pagination is dependent on the display height, then one can decide to show one, two, three or even more pages (columns) side by side on the screen.

**Comment by fonsp** [comment]
Thanks! Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?

**Comment by Uroc327** [comment]
Not sure whether it worked. It didn't ask for my contact info, as described in the issue.

**Comment by abraemer** [comment]
I feel your pain (only 2k screen but still) and the workaround I used in the past is to include a cell with something like `html"""<style>main { max-width: 1400px;}</style>"""` as that will directly modify the page's CSS when the cell is executed.
