### ISSUE TITLE
UndefVarError: methodswith not defined

### ISSUE THREAD

**Issue by kungfooman** [fonsp/Pluto.jl#194]
Example code:

```julia
methodswith(Set)
```

Error:

```
UndefVarError: methodswith not defined
top-level scope@Local: 1
```

![image](https://user-images.githubusercontent.com/5236548/85426291-90e84480-b57a-11ea-93bd-db85794473c6.png)

Why do these primitives not work?

**Comment by kungfooman** [comment]
I realized it depends on:

`using InteractiveUtils`

Maybe this should be loaded by default to make it as close to the REPL as possible?

**Comment by fonsp** [comment]
Thanks! I'll link this here: #160
