### ISSUE TITLE
Ctrl+click global variable stopped working

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#1960]
Pluto 0.18.0:
![pluto-0 18 0](https://user-images.githubusercontent.com/4170948/156035456-6b7724e2-e972-4ace-8987-258dd0c5ed38.gif)

Pluto 0.18.1:
![pluto-0 18 1](https://user-images.githubusercontent.com/4170948/156035468-9c200ee1-90b7-4898-9080-6b2a4821fef1.gif)

**Comment by fonsp** [comment]
Thanks!!
