### ISSUE TITLE
WebSocket does not connect

### ISSUE THREAD

**Issue by sprungj** [fonsp/Pluto.jl#1965]
![3 2 22](https://user-images.githubusercontent.com/1526724/156622424-6e41e15b-8116-4a1d-9339-5e627756a87b.gif)

The interface hangs in the loading state shown at the end of the video. The same thing happens if I try to load one of the sample notebooks. 

Apologies if there is something obvious going on here -- I haven't been able to find a description of the same issue. 

Thank you!

**Comment by disberd** [comment]
Do you get any errors on the browser's developer console?

**Comment by sprungj** [comment]
Getting 'WebSocket can't connect' errors in both Fireforx and Chromium. Looks like I might be in the same zone as [Issue #848](https://github.com/fonsp/Pluto.jl/issues/848)?
![Screenshot_2022-03-04_08-00-15](https://user-images.githubusercontent.com/1526724/156777617-546d1d4f-ba73-4174-8fbd-62a7e9113eff.png)
![Screenshot_2022-03-04_08-01-45](https://user-images.githubusercontent.com/1526724/156777622-e4de3e40-750a-48ac-b979-0ba5a06640e4.png)

[localhost-1646402874457.log](https://github.com/fonsp/Pluto.jl/files/8186432/localhost-1646402874457.log)

**Comment by rikhuijzer** [comment]
I also can confirm in https://github.com/fonsp/Pluto.jl/pull/1959#issuecomment-1059282733. The problem started somewhere between now and 4 days ago it seems.

When opening the notebook in that PR, I see the following error while the task is being stuck:

```
Unkown error during eval_format_fetch_in_workspace
ex
TaskFailedException
task
Task (failed) @0x00007f5ea6474fe0
MethodError: no method matching run_expression(::Module, ::Expr, ::Base.UUID, ::Nothing, ::Nothing; user_requested_run=true, capture_stdout=false)
Closest candidates are:
  run_expression(::Module, ::Any, ::Base.UUID, ::Union{Nothing, Tuple{Set{Symbol}, Set{Symbol}}}, ::Union{Nothing, UInt64}; user_requested_run) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword argument "capture_stdout"
  run_expression(::Module, ::Any, ::Base.UUID, ::Union{Nothing, Tuple{Set{Symbol}, Set{Symbol}}}) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword arguments "user_requested_run", "capture_stdout"
  run_expression(::Module, ::Any, ::Base.UUID) at ~/.julia/packages/Pluto/2DPK4/src/runner/PlutoRunner.jl:454 got unsupported keyword arguments "user_requested_run", "capture_stdout"
Stacktrace:
 [1] kwerr(::NamedTuple{(:user_requested_run, :capture_stdout), Tuple{Bool, Bool}}, ::Function, ::Module, ::Expr, ::Base.UUID, ::Nothing, ::Nothing)
   @ Base ./error.jl:163
 [2] top-level scope
   @ none:1
 [3] eval
   @ ./boot.jl:373 [inlined]
 [4] (::Distributed.var"#167#168"{Module, Expr})()
   @ Distributed ./task.jl:423
```

With this error, and information about the day, I suspect that my freeze (which might be also the same as the first comment in this issue) is caused by https://github.com/fonsp/Pluto.jl/pull/1957.

**Comment by rikhuijzer** [comment]
> The interface hangs in the loading state shown at the end of the video. The same thing happens if I try to load one of the sample notebooks.

@sprungj, are you running `master` or a Pluto 0.18.1 (latest release)?

**Comment by sprungj** [comment]
I'm using the latest release.

**Comment by fonsp** [comment]
@rikhuijzer Did you mean to post in this issue about the websocket connection? It doesn't sound related. Maybe make a new issue

**Comment by fonsp** [comment]
Did a previous version of Pluto work on your computer before? Do previous versions work right now? Does https://binder.plutojl.org/ work? Did you try restarting your computer?

**Comment by sprungj** [comment]
This was my first attempt to get it running on this computer. I tried 0.17.5 as well and had the same issue; will try an older version. The Binder link does work! But running with a different port doesn't. I'm seeing the same `Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.` error in the browser console.

**Comment by fonsp** [comment]
Hey @sprungj !

Could you do the following in Chrome:

1. Run Pluto, go to chrome and navigate to localhost:1234
2. Press F12, and open the Network panel
3. At the top, click "WS" (WebSocket)
4. Reload the page, now a single request should show up, to `localhost`
5. Click on the request, and send us a screenshot of the entire chrome window. Make sure that all `Request Headers` and `Response Headers` (if any) are visible.

For example, this should look like:
![image](https://user-images.githubusercontent.com/6933510/157946650-298d75a7-ef2d-4d88-9eaa-190b64dff492.png)

**Comment by sprungj** [comment]
The `View source` option doesn't seem to be available, maybe because of the `Provisional headers are shown` warning? 

![Screenshot_2022-03-12_13-58-43](https://user-images.githubusercontent.com/1526724/158033181-a8edcaac-8730-44a0-90ff-120a73fcd77c.png)

I should have tried this earlier, but: Python runs fine in a Jupyter notebook in the browser, but Jupyter can't connect to the Julia kernel in the browser or in VSCode. So it seems like I have something going wrong prior to Pluto -- apologies if this issue has been a red herring!

**Comment by fonsp** [comment]
@quinnj What do you think of this last report? It looks like:
- HTTP.jl can serve HTTP requests, but not WS
- HTTP headers are working, you can see that Pluto's `secret` cookie was set previously
- It is probably caused by the server, not the browser, because:
	- Running Pluto on binder works
	- Python's Jupyter web server can serve HTTP and WS
- Jupyter (running in python) can't connect with IJulia.jl, which does not use HTTP.jl I think, they talk over ZMQ, which is provided by `Sockets` and `ZMQ_jll`

**Comment by quinnj** [comment]
@fonsp are you able to reproduce this at all? Is it perhaps version (Julia or HTTP.jl) specific issue? Or OS specific? Does pluto have verbose logging we could turn on for the HTTP server?

If this is reproducible, I can try to dig in deeper to figure out why the WS connections aren't working but regular http requests are.

**Comment by quinnj** [comment]
I just merged an overhaul of the websockets code in HTTP#master, so it might be worth trying the issue here again with HTTP#master checked out. Happy to help debug things here if it's still reproducible.

**Comment by sprungj** [comment]
Got the following error loading Pluto after adding HTTP#master: 
![Screenshot_2022-06-13_12-17-35](https://user-images.githubusercontent.com/1526724/173409252-4304761b-aa0b-4e21-9fae-9995120c9ea1.png)

**Comment by rikhuijzer** [comment]
@sprungj That's correct. HTTP is in the process of a breaking change so not everything will work. Would be nice if you can update the Pluto code on your system and continue from there. If you put it in a draft PR, then we can quickly switch to the new HTTP once it is released

**Comment by sprungj** [comment]
@rikhuijzer Got it, I will give it a shot!

**Comment by Pangoraw** [comment]
A [new version of Pluto.jl](https://github.com/fonsp/Pluto.jl/releases/tag/v0.19.10) with HTTP.jl 1.0 has just been released. Could you try to see if the problem still happens with Pluto@0.19.10 ?

**Comment by sprungj** [comment]
Looks to be working, hurrah! Thanks all!
