### ISSUE TITLE
drag and drop not working

### ISSUE THREAD

**Issue by AshtonSBradley** [fonsp/Pluto.jl#1979]
from #707 I expected to be able to drag and drop a regular .jl file into Pluto. I see something happening in the progress bar, but a file never opens.

There is no Pluto notebook for this issue (that is what I am trying to create). 

The .jl file contains nothing really:

using Plots

##
plot(sin)
plot!(cos)

##
@show "hello world!"

https://user-images.githubusercontent.com/24194258/158067190-9fd4228b-2a20-4b47-ba85-6c8d432253da.mov

**Comment by AshtonSBradley** [comment]
also:

```julia
julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_PKG_DEVDIR = /Users/abradley/Dropbox/Julia/Dev
  JULIA_NUM_THREADS = 8
```

**Comment by AshtonSBradley** [comment]
trying again on intel, macos, julia 1.7.2
<img width="541" alt="Screen Shot 2022-03-15 at 9 12 41 AM" src="https://user-images.githubusercontent.com/24194258/158253477-3354b1ae-59ad-4895-889e-4c689b6dee4b.png">

**Comment by fonsp** [comment]
It works for me. Do you get an error message in the terminal where you launched Pluto?

**Comment by fonsp** [comment]
You can only use this method to open *Pluto notebook files*, as an alternative to the *Open* box. You can't use it to convert a `.jl` file into a notebook (yet). See https://github.com/fonsp/Pluto.jl/issues/132

Let me try to make the error message a bit better!
