### ISSUE TITLE
can not get `PGFPlotsX` backend of `Plots` to work

### ISSUE THREAD

**Issue by hofmannmartin** [fonsp/Pluto.jl#1982]
I expected this [Pluto notebook file](https://gist.github.com/hofmannmartin/df246ae56b796e459488b53cde7fea33) to load the `Plots` package with the `PGFPlotsX` backend. Somehow this naive approach fails:

![Screenshot from 2022-03-14 14-51-50](https://user-images.githubusercontent.com/7510025/158186502-ec3621ca-70fc-4274-b827-304a0e1004c3.png)

Also
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

```

**Comment by jtschneider** [comment]
I can reproduce the error both with using Pluto's package manager (as @hofmannmartin ) and with the standard local Pkg environment:
![image](https://user-images.githubusercontent.com/9451057/158412613-0d4e4745-9bab-4ce5-aeda-b9a552dff402.png)

```julia
### A Pluto.jl notebook ###
# v0.18.2

using Markdown
using InteractiveUtils

# ╔═╡ 942a4377-ef63-48e0-8bb5-4a6a605b8305
using Pkg; Pkg.activate()

# ╔═╡ 57548dff-d9fe-4255-84b9-a5014f445b0f
using Plots

# ╔═╡ a9eb7059-f1f6-4540-b4ae-73f8657be9d2
pgfplotsx()

# ╔═╡ Cell order:
# ╠═942a4377-ef63-48e0-8bb5-4a6a605b8305
# ╠═57548dff-d9fe-4255-84b9-a5014f445b0f
# ╠═a9eb7059-f1f6-4540-b4ae-73f8657be9d2
```

**Comment by BeastyBlacksmith** [comment]
I suspect this is another case of Plots evaluating in `Main` which doesn't exist in Pluto?
Does `pyplot` work?

**Comment by fonsp** [comment]
@BeastyBlacksmith you can use binder.plutojl.org to try things in Pluto!

**Comment by fonsp** [comment]
https://github.com/JuliaPlots/Plots.jl/pull/4168 might help

**Comment by hofmannmartin** [comment]
Thanks. I will test this with the next version of Plots.

Or is there a way to use `Plots#master` with the Pluto package manager?

**Comment by hofmannmartin** [comment]
The notebook now works as intended using Plots version 1.27.5. So it was a Plots issue after all. Thank you for helping me out.
