### ISSUE TITLE
Feature request: choose page title

### ISSUE THREAD

**Issue by gdalle** [fonsp/Pluto.jl#1984]
Hi there!
When I open a notebook in my browser, the tab name only says "⚡ Pluto.jl ⚡". Same thing with link sharing on platforms like [Discourse](https://discourse.julialang.org/t/getting-started-with-julia/77735/6). Would it be possible to choose the name of the web page, or at least add the file name automatically?

**Comment by rikhuijzer** [comment]
You mean for notebooks hosted via PlutoSliderServer.jl? When running notebooks locally, I do see the title

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/4c31a6b51a4f40b77b729b44fec90ea86da7a839 is 10% of a fix: it removes the default title (`⚡ Pluto.jl ⚡`) from the HTML document, which means that social media previews like discourse will use the filename as the page title.

**Comment by fonsp** [comment]
While working on the new plutojl.org website, I also found this problem! I am thinking about a standardized "frontmatter" system, allowing you to define the title, description, author, date, and more of the HTML export.

Right now, I (quickly) implemented by scanning for a global variable called `frontmatter`, like in this notebook: https://plutojl-preview.netlify.app/docs/widgets/javascript/ (link will probably break in the future). This is pretty cool, but maybe a GUI would be nicer... not sure if that's worth the time though.

**Comment by gdalle** [comment]
Thanks for working on this! Not sure a GUI is worth it, putting `frontmatter` in a cell at the top (as long as this functionality is documented) seems very feasible for most Pluto users

**Comment by fonsp** [comment]
#2008 was merged, but it was not yet used to solve this issue. Still to do: the `generate_html(notebook::Notebook)` function should call `frontend(notebook)` and use that to generate the header fields. They can be inserted with `replace(conents, "<head>" => "<head>$(stuff)")`
