### ISSUE TITLE
Math display in HTML export suddenly won't work

### ISSUE THREAD

**Issue by gdalle** [fonsp/Pluto.jl#1990]
Hey Pluto people!
I just realized that the HTML export no longer renders math properly: see https://gdalle.github.io/IntroJulia/efficiency.html for an example. Note that the math is displayed when the Pluto server runs, so it is really a matter of export.
Is it just me?

**Comment by nilshg** [comment]
Just noticed the same - also to add pdf export works fine with LaTeX rendered.

**Comment by disberd** [comment]
Duplicate of https://github.com/fonsp/Pluto.jl/issues/1987
