### ISSUE TITLE
Allow user-defined themes

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2]

**Comment by fonsp** [comment]
Perhaps using #6

**Comment by fonsp** [comment]
See the suggestion in #139

**Comment by TheCedarPrince** [comment]
Mind if I spend some time on this trying to get this implemented @fonsp ?

**Comment by fonsp** [comment]
Actually, I was planning on changing the CSS structure to make custom themes a lot easier. The remaining questions are mostly:
- where should the custom theme be stored?
- how should Pluto know about a custom theme (I'm thinking `ENV`)
- how is it inserted into the DOM?
- what _is_ a theme? just cell output? UI?
- are multiple themes allowed to combine?

**Comment by TheCedarPrince** [comment]
Ah gotcha! My thoughts to your points:

1. I think we shouldn't worry about where custom themes will be stored. I would think the best way to handle it would be to provide in endpoint that allows users to give a path to exactly where their stylesheet is stored. Perhaps we could make a sort of permanent Pluto config file where someone could specify the path to their stylesheet without having to continuously redefine it?

2. Hmmm... Do we want the same resource file for everything Julia related? Or modularize it specific to Pluto per my thought on point 1. I do like this idea a lot however.

3. I think your question about what is a theme is best discussed in conjunction with the question about how it is inserted into the DOM. My thinking is that it could be up to the user -- I don't think that is something we should worry about defining. Plus, I think the open ended nature of what we mean by a theme and the creativity of users could make some very magical things.

4. Hunh. Multi-themes. Again, I think we should leave that to the user to determine. I think it is a good idea but maybe not something we should decide for them.

5. My thinking is that by giving users the ability to create custom themes of any nature, we should not try to conform to themes people are creating. I think we should continue creating the UI as we see fit, but that we should be very clear about any changes that we make which may impact themes.

What do you think? Are you working on a PR right now that I could assist with? Thanks! :smile:

**Comment by fonsp** [comment]
3 & 4 & 5: I agree!

1: I have an idea! Custom themes (and other addons) _must_ be a URL. People can use GitHub gist or similar to publish and share their themes, and Pluto doesn't need a 🌈🌈 _Pluto extensions marketplace_ 🌈🌈 and you don't need to touch your file system to add themes.

2: Pluto doesn't have a config file and it should stay that way I think, but if all themes are just URLs, it can save those in your browser's local storage (just like your recent notebooks). 

_(To develop a theme locally, you would have to put it in `/assets` while you work on it, or we can add a second dir like `/custom_assets` that is accessible from the web page, which is `.gitignore`d, i.e. you can add stuff in the folder without worrying about git changes.)_

Another solution is to not do any of this, and make _browser extensions_ the way to customize Pluto. I think that this is the coolest way, were it not that browser extensions are fixed to one browser, and there is some learning curve to creating a super simple one. But maybe there is a browser extension out there that just lets you write custom CSS for specific addressed - that could work.

**Comment by fonsp** [comment]
This exists! It's called Stylish and works across [chrome](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe) and [firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/?src=search) and they have a marketplace to share styles publicly. 

So here you would write a CSS script, and apply it to `localhost` (or even a regex that is more specific).

**Comment by TheCedarPrince** [comment]
Hey @fonsp ,

Lots of fantastic thoughts here! I spent some time thinking about this issue further and here is what I concluded:

1. I really like the idea of a simple URL. I think we should go this route! Or even go along with what OhMyZSH did with giving a bunch of [pre-bundled themes to the user](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes).

2. I agree with not having an additional config file. However, I could see _potentially_ having one for development work (though, I think this is unrelated to the current issue).

3. In respect to custom assets, I think that is a great idea and we should implement it. I think themes can be more than just styling as they could also be additional functionality.

In respect to 1 and 3, I think this gets back to the bigger discussion about perhaps making some sort of Pluto Organization and have a core website underneath that. I'd love to help with making that a thing at some point soon.

The one problem I do have with the user styles is that if we have them stored in the browser, will CSS changes persist to the export of a PDF? And if so, a bigger discussion is when/if we can make Pluto deployable to a webservice for web based hosting, can themes apply there as well? These thoughts may be beyond the scope of this issue, but they might be important to think about for long term!

**Comment by TheCedarPrince** [comment]
P.S. Regarding Stylish, does something like that go against Pluto philosophy? It would mean adding an additional step/dependency to worry about. I get the idea, but it makes me anxious having a third party be responsible for our theme idea.

P.P.S. I am ready to work on a PR whenever we can figure out something to do here! :smile:

**Comment by fonsp** [comment]
There is also a (more?) open source version of Stylish: [Stylus](https://github.com/openstyles/stylus/). Both Sylish and Stylus can work offline - so it is not a dependency on a third party to remain operational - but it does feel hacky.

The thing is, having _any_ customization is a bit against the up-until-now Pluto philosophy (which is full end-to-end control). 

Style changes (no matter the method) make it into the PDF (try it!), but not to .html/web exports.

**Comment by fonsp** [comment]
(I'm thinking of something fun for you to work on!)

**Comment by TheCedarPrince** [comment]
I think we should pursue the `ENV` way first as I think that makes the most sense and easiest to implement. What do you wanna do next?

But true, actually, do you think we could discuss the Philosophy of Pluto? I don't really see it on the main README (though from conversations from you, I understand the gist of it) and I feel like having the philosophy be more up front is important for future contributors. Thoughts there?

**Comment by fonsp** [comment]
Well, Stylus has already been implemented 🙃 You could use it today to write new themes, and any CSS you write there is still usable if we ever change the way they are loaded. (But again - I was planning to change the CSS structure, so writing a theme right now would be counterproductive.)

It's just that I am not motivated to solve this issue soon 😬 Besides a dark mode (which could be built-in and [automatically match the system theme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)), there have been no user requests in this area. (And of course, I am personally quite happy with the default theme.) So any solution that adds a config or makes the project less end-to-end controlled, makes me scared. 

Lots of negative sentiment here, but my main point is that there is lots to do that _does_ make me excited, and it is very important to keep the project easy to maintain.

As for outlining the Pluto philosophy - I prefer not to write down my own ideas on this as if they are rules, although I understand that this makes collaboration a little trickier. Discussions are welcome and useful!

**Comment by TheCedarPrince** [comment]
Ah that makes a lot of sense! Want to go ahead and close this issue for now?

**Comment by RocketRoss** [comment]
I'd love some control over the theme and default layout. 

Perhaps what would fit your preferences is an aftermarket script such as [jupyter-themes](https://github.com/dunovank/jupyter-themes/blob/master/setup.py) that would just overwrite Pluto's CSS. I'm assuming that that is what jupyter-themes does, although not 100% certain. 

As an aftermarket script, it is up to the maintainers of the script to ensure some adherence to Pluto's design intention. So I believe its community members are close at hand.

In a month or two I will probably get back to this idea!
