### ISSUE TITLE
subtype error

### ISSUE THREAD

**Issue by AshtonSBradley** [fonsp/Pluto.jl#201]
I wanted to try [paper-scissors-rock](https://giordano.github.io/blog/2017-11-03-rock-paper-scissors/), but I get this error (runs in the REPL):

<img width="743" alt="Screen Shot 2020-07-03 at 4 08 25 PM" src="https://user-images.githubusercontent.com/24194258/86430922-7e72c580-bd47-11ea-8dbd-3e9dbaae5ea3.png">

**Comment by fonsp** [comment]
Can you send the docs for `subtypes`?

**Comment by AshtonSBradley** [comment]
```julia
help?> subtypes
search: subtypes

  subtypes(T::DataType)

  Return a list of immediate subtypes of
  DataType T. Note that all currently loaded
  subtypes are included, including those not
  visible in the current module.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> subtypes(Integer)
  3-element Vector{Any}:
   Bool
   Signed
   Unsigned
```

**Comment by fonsp** [comment]
#160
