### ISSUE TITLE
Using JavaScript Library TikzJax inside Pluto

### ISSUE THREAD

**Issue by feyereisl** [fonsp/Pluto.jl#2034]
Hi,

I am wondering whether it is feasible and sensible to run **TikZJax javascript library** (https://github.com/kisonecat/tikzjax) inside pluto.

The benefit being that one could use tikz directly in a notebook to draw beautiful diagrams with latex math, without having to rely on the heavy latex machinery in the background and thus could be more portable and useful anywhere and anytime.

TikZJax is supposed to convert script tags (containing TikZ code) into SVGs, but if I try to run it inside a notebook, essentially nothing gets displayed. This could be due to the library itself or the way that Pluto deals with parsing tags. I couldn't get it to work, so any help or suggestion whether it is a good/bad idea and why would be very useful.

Thank you very much for your time!

**Comment by Pangoraw** [comment]
Hi, the library works withing Pluto. You need to call `window.load` after including the script tag because the script is not loaded with the page buf afterwards. I made [a small notebook](https://pangoraw.github.io/Notebooks/tikzjax) with a wrapper if you are interested.

**Comment by feyereisl** [comment]
That's perfect! Thank you very much, it works.
