### ISSUE TITLE
"You have v0.10.1, the latest is v0.10.0"

### ISSUE THREAD

**Issue by goretkin** [fonsp/Pluto.jl#204]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/581043/86825994-17625300-c05e-11ea-9f55-7c5cad4ff26b.png">

```
A new version of Pluto.jl is available! 🎉

    You have v0.10.1, the latest is v0.10.0.

You can update Pluto.jl using the julia package manager.
Afterwards, exit Pluto.jl and restart julia.
```

This was after I updated to get "  [c3e4b0f8] ↑ Pluto v0.9.11 ⇒ v0.10.1"

**Comment by fonsp** [comment]
Yeah that's a bit silly (it happens in the short time period between the latest version reaching the general registry, and our GitHub Action registring the 0.10.1 label)

**Comment by fonsp** [comment]
Hope you like the new update though!

**Comment by fonsp** [comment]
It's fixed now, thanks!

**Comment by goretkin** [comment]
I enjoy Pluto and glad to see it developed and appreciated the dialog box (before this one) that announced the new version to me.

Thanks!!

**Comment by fonsp** [comment]
Haha that's nice to hear <3
