### ISSUE TITLE
v0.19.1 doesn't work?

### ISSUE THREAD

**Issue by gpucce** [fonsp/Pluto.jl#2045]
Pluto stuck like this after update to 0.19.1 on windows 11 and wsl

![image](https://user-images.githubusercontent.com/32967787/164492049-ffc0ca58-806d-4135-99be-3fe4136b7886.png)

**Comment by j-fu** [comment]
Same here on Chrome/Linux

**Comment by fonsp** [comment]
Oops! Publishing a fix right now

**Comment by fonsp** [comment]
0.19.2 is being registered: https://github.com/JuliaRegistries/General/pull/58899

**Comment by fonsp** [comment]
It looks like something went wrong in our bundler. We actually have tests to catch this, and the tests did fail: https://github.com/fonsp/Pluto.jl/commit/217e6ba3ce9932a73cc54bb461c176d17c408bfd but I did not notice this failure when registering. 😑

I am planning to redo our release pipeline in a couple of months, and I will be sure to take this oversight into account!

**Comment by fonsp** [comment]
You can update to Pluto 0.19.2 in a couple of minutes! Thanks for your report!
