### ISSUE TITLE
Pluto hardly responding while testing for the 1st time

### ISSUE THREAD

**Issue by sylvain-bougnoux** [fonsp/Pluto.jl#2055]
I was trying to test Pluto for the 1st time, and it partially hangs in the welcome page as below. After doing
```
using Pluto
Pluto.run()
```
In shows in a browser (both firefox & chrome - last version).

![firefox_2022-04-25_11-52-04](https://user-images.githubusercontent.com/6706662/165065629-f009a98a-a66c-4a84-aafd-5f0e0b03daa2.png)

I expected to see a "load file option" as the 3rd choice ('open from file'), but it keeps on *Loading...*

The 2 first choices are responding though (but navigation is very slow - like minutes). 
* The 1st one works (up to me) as showing different examples, but none is accessible (**blank page** forever after clicking one);
![firefox_2022-04-25_11-57-52](https://user-images.githubusercontent.com/6706662/165066976-8ca0e124-7d4c-4e2d-aafc-bce06380703a.png)

* The 2nd one "create a new notebook" leads also to a **blank page**. 

The console does not say anything beside "... have fun" and "ctrl+C and updating registry done". 
 
![2022-04-25_11-56-42](https://user-images.githubusercontent.com/6706662/165066511-cb24f215-4863-4b5e-8585-f3b8d135f22d.png)

A ctrl+C in the console sometimes yields

      From worker 2:    fatal: error thrown and no exception handler available.
      From worker 2:    InterruptException()
      From worker 2:     jl_mutex_unlock at /cygdrive/c/buildbot/worker/package_win64/build/src\julia_locks.h:129 [inlined]
      From worker 2:     jl_task_get_next at /cygdrive/c/buildbot/worker/package_win64/build/src\partr.c:484
      From worker 2:    poptask at .\task.jl:827
      From worker 2:    wait at .\task.jl:836
      From worker 2:    task_done_hook at .\task.jl:544
      From worker 2:    jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
      From worker 2:    jl_finish_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:218
      From worker 2:    start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:888

Tested on Windows 10.

**Comment by fonsp** [comment]
Can you update Pluto and try again? Can you share the output of running `Pkg.status()` in your termina_l?

**Comment by sylvain-bougnoux** [comment]
Yes it seems to work now. It was a bug or a broken update? Many thanks.
```
julia> Pkg.status()
      Status `C:\Users\bougnoux\.julia\environments\v1.7\Project.toml`
  [a6e380b2] ControlSystems v0.12.11
  [7073ff75] IJulia v1.23.3
  [91a5bcdd] Plots v1.27.5
  [c3e4b0f8] Pluto v0.19.2
  [21fd56a4] RobustAndOptimalControl v0.4.6
```

**Comment by fonsp** [comment]
Yes! Seems to be #2045
