### ISSUE TITLE
Automatically folding code

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#206]
When I execute a cell with the shortcut Ctrl+Enter the cells code is automatically hidden. Is this a bug or a feature?

It is actually kind of nice for cells like `a=5` where variable and value are displayed in the output. It would also be nice for small function definitions of the form `mysquare(x) = x^2` if the definition of that function would also be displayed in the output and not only its name.

I'm not so sure if I like this feature for every other cell where the output does not contain the same information as the cell code.

**Comment by fonsp** [comment]
Feature!

Thanks for your feedback, I am still changing the keyboard shortcuts around, I just wanted to try this out :)

I quite like it myself, also note that you now have `PageUp` and `PageDown` (`fn` + arrow keys on mac?) to switch between cells. It even peeks inside cells that have their code folded! Maybe try to incorporate these in your workflow, and see if it still bugs you? For example, if you do `Ctrl+Enter` but realise that you want to change it, you can do `PageUp`.

I like the idea about small function definitions! I've added this to the suggestion box.

**Comment by karlwessel** [comment]
Ok, I gave this some time now to get used to, but the only effect it has is that I don't use CTRL+Enter anymore xD.

If I implemented a function in a cell, i want to test that function in the next cell. I **always** want to see the implementation of that function when writing that test code.

Maybe it would make sense to implement this automatic folding only for cells where the output is more meaningful? So things like plots, markdown or tables. And not for things where the output is more or less meaningless, like for functions?

**Comment by fonsp** [comment]
Thanks for the open minded response! I quite liked the feature myself, until I sat down this week to write an actual notebook (I mostly write silly test notebooks, unfortunately), and then it was counter-productive most of the time.

So undoing it might be a good idea. About the creative solution (easiest to add would be auto-folding markdown-only cells): maybe that makes it feel inconsistent? But it would be fun to try out

**Comment by karlwessel** [comment]
I think, especially together with the automatic updates of Markdown cells the automatic folding for them would be nice. And while it may feel inconsistent at first I would guess one gets the pattern very fast (everything that automatically updates also automatically folds).

**Comment by fonsp** [comment]
I disabled it again:
https://github.com/fonsp/Pluto.jl/commit/87c98f8efe8006bd1c8f3e82b776a9fc32ca3b12#diff-9cb8017817df805bcf2cf06b90b3ff42L60-R60
