### ISSUE TITLE
markdown/docstring issue with multiple dispatch, docstrings multiply

### ISSUE THREAD

**Issue by wisehe** [fonsp/Pluto.jl#2071]
Thank you for reporting an issue about Pluto! Let's get it fixed!

# To report an issue, you need two things:
1. 📹

https://user-images.githubusercontent.com/24848149/165875676-90485eb0-612e-4bec-8727-affd445d1da1.mov

2. 📝
https://gist.github.com/wisehe/58ffd0d6d5b5bd2f92af9d0891c26029
3. 🤕 
When I have multiple functions with the same name, any markdown above those functions seems to "duplicate" itself each time the cell is run. If I remove the other functions, the behavior will go back to normal once the cell with markdown is run.

**Comment by fonsp** [comment]
Looks like #1932 is still open in 0.19.3 @Pangoraw
