### ISSUE TITLE
Notebook keeps reconnecting

### ISSUE THREAD

**Issue by SimiPixel** [fonsp/Pluto.jl#2078]
Hello,

my Pluto Notebook keeps re-connecting every Minute or so, it is almost unusable. What could be the issue / How can i provide useful information or logs?

System:
Thinkpad X1 Tigerlake i7
Ubuntu 20 LTS
Julia 1.7.2
Pluto 0.19.3
Firefox-Browser

Thank you and nice evening everyone.

**Comment by SimiPixel** [comment]
Update:
Switching to chromium as browser limits the problem severely, only occassional re-connects that take less than 2 seconds. The issue must be in combination with Firefox browser.

**Comment by karlwessel** [comment]
I have the same problem. Notebooks keep reconnecting or loosing connection totally. This happens randomly but pretty often. Sometimes restarting the notebook from Plutos main menu helps, sometimes I have to restart Pluto itself. 

Is there something I can do to pin down the cause for this problem?

What can Firefox users do to solve this Problem?
