### ISSUE TITLE
Variable not interpolated if in markdown table

### ISSUE THREAD

**Issue by briochemc** [fonsp/Pluto.jl#208]
Here is a MWE of what I mean:
<img width="718" alt="Screen Shot 2020-07-09 at 2 38 02 pm" src="https://user-images.githubusercontent.com/4486578/86997657-f6cb0200-c1f1-11ea-8a51-f6e5420cccba.png">
Once `x` is defined, it is correctly showing up in markdown text (e.g., `md"$x"`), but it is not interpolated inside a markdown table.

**Comment by karlwessel** [comment]
This probably is a problem of the `Markdown` module of Julia itself since it also doesn't work in the REPL.

**Comment by GiggleLiu** [comment]
I guess the same issue for list,  because
```
md"""
* y1 = $(y1[])
* lx1 = $(lx1[])
* k1 = $(k1[])
* s1 = $(s1[])
"""
```

is rendered to 
```
y1 = :(y1[])
lx1 = :(lx1[])
k1 = :(k1[])
s1 = :(s1[])
```

in Pluto.

**Comment by fonsp** [comment]
Yes, this is unfortunate. You could give this GitHub issue a thumbs up:
https://github.com/JuliaLang/julia/issues/16194#issue-152992087

**Comment by fredrikekre** [comment]
FYI this works on Julia master now.

**Comment by fonsp** [comment]
Wow!
