### ISSUE TITLE
CUArray broken printing

### ISSUE THREAD

**Issue by CarloLucibello** [fonsp/Pluto.jl#2083]
CUArray creation works fine in Pluto

![Screenshot from 2022-04-30 17-14-01](https://user-images.githubusercontent.com/7014210/166111378-10ddc5fb-a358-4f7d-81c5-5fd4e2b5959f.png)

but then an error is thrown when printed in the cell output

![Screenshot from 2022-04-30 17-14-32](https://user-images.githubusercontent.com/7014210/166111461-1abacf57-37e8-4304-ae27-b4f394c3a3c8.png)

**Comment by fonsp** [comment]
Can you share a notebook file?

**Comment by CarloLucibello** [comment]
[notebook](https://gist.github.com/CarloLucibello/da66d33d6f07b6baa879da3581c1beed)

**Comment by cschmidat** [comment]
It works for me after manually executing `CUDA.allowscalar(true)`

**Comment by CarloLucibello** [comment]
But still gives a warning, and in any case `CUDA.allowscalar(true)` is not something you typically want in your code.
