### ISSUE TITLE
Improve initial load time

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#209]
There are essentially two load times: the first time (which includes Julia precompiling and executing) and the second (when all outputs are already in memory). 

To improve the first/second time:
- [x] Bundle all cell inputs in a single message - right now it's a request+response for each cell.
- [x] Same for outputs? Gradually loading them in might be a better experience. 

To improve the first time:
- [x] Prioritize execution of "pure Markdown/HTML cells", under the criteria suggested in https://github.com/fonsp/Pluto.jl/issues/199

**Comment by karlwessel** [comment]
The prioritisation of Markdown is a big improvement! Thanks!
