### ISSUE TITLE
Table of content overlaps text

### ISSUE THREAD

**Issue by jakobnissen** [fonsp/Pluto.jl#2093]
Example notebook (static HTML): https://viralinstruction.com/posts/hardware/
To see the issue, resize the window smaller, then the ToC begins overlapping the text making it unreadable.

Larger window: It looks good
![Screenshot from 2022-05-05 08-33-13](https://user-images.githubusercontent.com/23193950/166873083-c2995015-3db9-4a69-a059-9bea99ffa99f.png)

Smaller window: Overlap
![Screenshot from 2022-05-05 08-33-28](https://user-images.githubusercontent.com/23193950/166873092-b18c718f-3ec3-480e-a313-8b5fef94e7ca.png)

To reproduce:
Open the following notebook
https://gist.github.com/jakobnissen/a74a62aa285e4798d33264f5e41d7302

See also #1770

**Comment by disberd** [comment]
I don't know if you know already but you can move the ToC to the side by clicking on the open notebook icon that is next to the `Table of Contents` title.
I think that was the final solution adopted in PlutoUI to remove the overlap. In your example above having the ToC shrink in width to avoid covering the text would make it way too narrow and compromise readability.

**Comment by jakobnissen** [comment]
Unfortunately, even when minimised, there is overlap:

![Screenshot from 2022-05-05 11-24-59](https://user-images.githubusercontent.com/23193950/166896093-aa79eb9d-6edb-44d5-b49a-bed369ccfe6a.png)

**Comment by disberd** [comment]
I see, when the new collapsible feature was put in they removed the automatic removal of the ToC from the side when the screen width got too narrow.

I think in any case this is an issue for PlutoUI and not for Pluto itself.
It might be desireable to have just the closed book icon (without the full height of the ToC) when it is collapsed to avoid this situation and minimize overlap with text.

**Comment by jakobnissen** [comment]
Yeah - thanks for the new feature! :)
