### ISSUE TITLE
Highlighting issue with `<:`

### ISSUE THREAD

**Issue by Pangoraw** [fonsp/Pluto.jl#2095]
![image](https://user-images.githubusercontent.com/9824244/166981105-a8980154-9f9c-42bf-9be8-9c894a2db160.png)

**Comment by dralletje** [comment]
What are you expecting the colors to be like?

**Comment by Pangoraw** [comment]
Unchanged (blue) for both `Bool` and `Integer` since `<:` is  an operator.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/168808272-b5b30cda-6d2f-4131-8e16-4cfb38d4ecee.png)
