### ISSUE TITLE
Cannot use plotly()

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#211]
If you run this example, it works with `plotly()` commented or replaced by `gr()` but does not work with it uncommented (I only see a blank are where the plot should be).
```
begin
	using Plots
	#plotly()
	plot(0.0:0.01:2π, sin)
end
```

I use the `plotly()` backend because it provides an interactive graph (panning/zooming by mouse) which can also be saved as an html and shared with someone without requiring them to install/learn Julia.

**Comment by fonsp** [comment]
Thanks! I am working on plotly support, let's discuss it here: #108
