### ISSUE TITLE
Markdown for "inline-style link with title" not handled properly

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#212]
I'm working through examples in [this Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet "Title text viewable on hover"), and the title text doesn't seem to get handled properly.

I tried this:
```
md"""[I'm an inline-style link with title](https://www.google.com "Google's Homepage")"""
```
but instead of the quoted title becoming visible on hover, it is appended to the link, breaking it.

**Comment by fonsp** [comment]
Hey! This is a feature that GitHub added to their own Markdown parser (the one used to render this comment), it's not part of Julia's Markdown parser. These differences are called Markdown _flavours_.

**Comment by fonsp** [comment]
Here is a more helpful answer 😊

![image](https://user-images.githubusercontent.com/6933510/87609967-48005780-c704-11ea-94a6-e52bfeadf3b3.png)

**Comment by fonsp** [comment]
We want to have a sample notebook with Julia's markdown syntax (#162), that would make the wide range of online guides less confusing.

**Comment by klaff** [comment]
Thank you. Something you might like to include in such a sample is a canonical way to show a local image (since the typical Markdown way doesn't work due to browser security limitations). I'm using `plot(read("someimage.png")` but I'm not sure if there's a way that is less heavy.

**Comment by fonsp** [comment]
True! You can subscribe to #183 to hear about our progress

**Comment by klaff** [comment]
Awesome, thanks. What's the best place to ask questions about the best way to use this tool? Would you prefer discourse threads? (I like that as I think they are more highly visible to others).

**Comment by fonsp** [comment]
These GitHub issues are good for questions ([see this](https://github.com/fonsp/Pluto.jl/issues/182)), and you can also go to the [zulip chat room](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl).

But my preferred way is to video chat! You can try if any of us are online [in the Pluto room](https://meet.jit.si/Pluto.jl) or send us an email (fonsvdplas@gmail.com) or leave your email with the built-in feedback tool.
