### ISSUE TITLE
a=myfunction(a,...)

### ISSUE THREAD

**Issue by filchristou** [fonsp/Pluto.jl#2140]
The line ``a = rand(a, 4)`` freezes Pluto, while normally it should give ``UndefVarError: a not defined``  as in REPL.
The same happens for different function like `f = findall(f, 5)`

tested on Pluto v0.19.5

**Comment by Pangoraw** [comment]
Thanks for the report! Could you share a notebook and/or a video showcasing the problem with steps to reproduce ?

**Comment by rikhuijzer** [comment]
I can reproduce on Linux 64 bit with Julia 1.7.2 and Pluto 0.19.5. Running a cell with `a = rand(a, 4)` in an empty notebook will run for a few seconds and then the bar at the top stops at about 1/3rd of the width showing that things are still running. Even after a few minutes, doing things such as adding a new cell are still blocked

**Comment by filchristou** [comment]
I now experience that it is more general. 
inserting a cell like ``a = a + 1`` everywhere in the notebook (even empty) will have the same effect.

**Comment by rikhuijzer** [comment]
I created a notebook which should freeze and opened it directly via `Pluto.SessionActions.open(Pluto.ServerSession(), path)`. This didn't freeze, so it looks like a front end problem.

According to `git bisect`, the problem was introduced in #2057 (@fonsp).

**Comment by HirumalPriyashan** [comment]
Sent a fix in https://github.com/fonsp/Pluto.jl/pull/2142
