### ISSUE TITLE
ANSI colored output in captured stdout

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2144]
_Originally posted by @diegozea in https://github.com/fonsp/Pluto.jl/issues/894#issuecomment-1143816541_

I found this while using programs designed for the terminal, distributed in the Julia ecosystem as jll packages. For example:

```julia
# ╔═╡ 4c4d8eaa-87ae-4f2b-8f33-4cced2cc824c
using FastME_jll

# ╔═╡ 0505615f-bf25-4316-923e-eb4dcef34129
fastme() do _fastme
	run(`$_fastme -h`)
end
```
Here the problem is not only color code but also bold character and other things I have no idea about:
Pluto:
![image](https://user-images.githubusercontent.com/2822757/171451756-836d7b37-6312-4435-8afd-aeeed0d25e16.png)

Terminal:

![image](https://user-images.githubusercontent.com/2822757/171451866-11f6b262-d9b9-4027-a909-3016afa79106.png)

**Comment by fonsp** [comment]
This is different from #894 because stdout/stderr is captured and displayed as a log. This should be relatively easy to implement, take a look at how we use AnsiUp in https://github.com/fonsp/Pluto.jl/blob/v0.19.5/frontend/components/PkgTerminalView.js .

**Comment by fonsp** [comment]
@HirumalPriyashan maybe? ☺️

**Comment by diegozea** [comment]
Thanks! It works perfectly now :smiley: 

![image](https://user-images.githubusercontent.com/2822757/173821204-4b0fcc59-a287-465b-9984-ad40c68e7539.png)
