### ISSUE TITLE
Unicode autocomplete takes long to respond

### ISSUE THREAD

**Issue by rikhuijzer** [fonsp/Pluto.jl#2153]
After loading a notebook and running stuff, Pluto responds immediately for normal autocomplete (for example, `contain<TAB>` completes to `contains`). For Unicode, however, the first time it takes 2 seconds here (for example, `\lambda<TAB>`).

Anyone here who can tell me which endpoint this Unicode autocomplete is hitting? I can't find it. We should be able to get the time to zero by adding a small async workload somewhere during notebook startup.

**Comment by fonsp** [comment]
Good find! You can add it here: https://github.com/fonsp/Pluto.jl/blob/129cf25e191b257b19c12d5246103d0d0d15e53e/frontend/components/Editor.js#L782
