### ISSUE TITLE
Pluto crashes after incorrectly overwriting method from package

### ISSUE THREAD

**Issue by greimel** [fonsp/Pluto.jl#2157]
https://user-images.githubusercontent.com/6280307/172169467-3241b72a-e1b7-4c5b-9571-f5c63e6129bf.mov

**Comment by Pangoraw** [comment]
Thanks for the video! Could you share more information about your julia + pluto versions (or send the notebook file) as I did not manage to reproduce the issue? Also is there any log in the terminal when pluto freezes?

**Comment by greimel** [comment]
I've just tried again, and I can't reproduce. (I did manage to reproduce this multiple times before I opened the issue here.)

**Comment by Pangoraw** [comment]
Feel free to reopen if that happens again !
