### ISSUE TITLE
Latex in Markdown stopped working

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#218]
Somewhere in the last commits Latex stopped being rendered in Markdown strings. For example a cell with
```
md"""``\pi``"""
```
is displayed as
```
$\pi$
```

and 
```
md"""$\pi$"""
```
is displayed as 
```
$$\pi$$
```

**Comment by fonsp** [comment]
Oof. What happends if you refresh the page or re-run the cell?

**Comment by karlwessel** [comment]
Re-running the cell did not help, but refreshing the page actually does...hmm.

**Comment by karlwessel** [comment]
I'll investigate more later.

**Comment by fonsp** [comment]
Could you delete the word `async` [here](https://github.com/fonsp/Pluto.jl/blob/v0.10.9/frontend/editor.html#L38) and see if it is still a problem?

**Comment by karlwessel** [comment]
Hmm, can't reproduce the Problem anymore, not even with v0.10.9. So it is fixed, I guess :)
