### ISSUE TITLE
Arrows no longer work in presentation mode

### ISSUE THREAD

**Issue by gdalle** [fonsp/Pluto.jl#2192]
Hey there! I am building some slides with Pluto using the following tutorial: https://andreaskroepelin.de/blog/plutoslides/

Until a few versions ago, the arrows on the bottom right corner used to work fine to switch between slides. However, they don't work anymore as of Pluto v0.19.9: in the attached video, I am clicking on the arrow and nothing happens.

Notebook file: https://gist.github.com/gdalle/46db272810fec60d2a3c74b820dd9fb5

https://user-images.githubusercontent.com/22795598/176101801-88388548-3e17-4110-9620-4ec849e2625f.mp4

Related discussions:

- https://github.com/fonsp/Pluto.jl/issues/118#issuecomment-1148867107
- https://discourse.julialang.org/t/slides-presentations-with-pluto-jl/46516/4

**Comment by Pangoraw** [comment]
Thanks for the report! This will be fixed in the next release. For anyone encountering this issue in affected version (`0.19.? <= Pluto < 0.19.10`), adding [this cell](https://gist.github.com/Pangoraw/cc905dae6f31e79f49785eebdb131620) to your notebook should solve the problem.

**Comment by alecloudenback** [comment]
This seems to be an issue again, and the hotfix linked in the prior post doesn't work for me either. `v0.19.11` and confirmed with two other people (see #pluto slack for one of those other datapoints).

I personally tested `v0.19.11` on Mac (Firefox, Chrome, and Safari) and WIndows (Chrome).

**Comment by Pangoraw** [comment]
Could you send an exported notebook in which arrows don't work ? Arrows still work when I try it.

**Comment by alecloudenback** [comment]
Sure - [this](https://github.com/JuliaActuary/Learn/blob/master/intro-video/Coding-with-Julia.jl) is the notebook (tried with and without the hotfix from prior version after restarting Pluto) and tested on Mac (multiple browsers) and Windows (Chrome). I also tried [this notebook](https://github.com/andreasKroepelin/membrane_adhesion/blob/master/membrane_adhesion.jl) on Mac Firefox.

**Comment by Pangoraw** [comment]
Just to be sure, are you referring to the keyboard arrows and not the arrows in the bottom right? This issue is for the arrows in the bottom left, I don't think there ever was keyboard shortcuts to move to the next slide (see https://github.com/fonsp/Pluto.jl/issues/118#issuecomment-1134818101).

**Comment by alecloudenback** [comment]
Yea, the arrow buttons work. I had thought the keys did in the past as well, as did Fredrik Carlson [on slack](https://julialang.slack.com/archives/C017Z6Q3WS3/p1663787006866549?thread_ts=1663783178.392359&cid=C017Z6Q3WS3) but I believe you that we are misremembering. Thanks!

**Comment by diegozea** [comment]
Hi, this looks to be happening again, the buttons doesn't work for me. 

![image](https://github.com/fonsp/Pluto.jl/assets/2822757/a6ced313-9653-47bf-b08a-b6e1f7437325)


```julia
(@v1.10) pkg> st
Status `C:\Users\dz272503\.julia\environments\v1.10\Project.toml`
  [bb6f5dab] AlphaConformers v0.1.0 `C:\Users\dz272503\.julia\dev\AlphaConformers`
  [6e4b80f9] BenchmarkTools v1.5.0
  [de9282ab] BioStructures v3.0.0
  [46823bd8] Chemfiles v0.10.41
  [e30172f5] Documenter v1.4.0
  [713c75ef] Franklin v0.10.95
  [51bafb47] MIToS v2.15.0 `C:\Users\dz272503\.julia\dev\MIToS`
  [c3e4b0f8] Pluto v0.19.41
  [f535d66d] ROCAnalysis v0.3.6
  [e0db7c4e] ReTest v0.3.2
  [295af30f] Revise v3.5.14
  [aa65fe97] SnoopCompile v2.10.8
  [e2b509da] SnoopCompileCore v2.10.1
  [90137ffa] StaticArrays v1.9.3
  [3c954167] WeatherReport v0.21.1
  [74334e00] DSSP_jll v4.4.0+1
  [f5851436] FFTW_jll v3.3.10+0
  [f5adda9a] Foldseek_jll v8.0.0+0
  [f50d1b31] Rmath_jll v0.4.0+0
  [850473c1] STRIDE_jll v1.0.0+0

julia> InteractiveUtils.versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8 (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × 13th Gen Intel(R) Core(TM) i7-1365U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)

```

```
Google Chrome
Version 123.0.6312.123 (Official Build) (64-bit)
```

**Comment by diegozea** [comment]
No problem. Now, it is working fine. I don't know what has changed.
