### ISSUE TITLE
Pluto unable to "show" 3D Symbolic arrays (of Symbolics.jl)

### ISSUE THREAD

**Issue by hiiroo** [fonsp/Pluto.jl#2193]
1. 📹 A video recording demonstrating the problem. (You can drag a video file into this box)

https://user-images.githubusercontent.com/323068/176127897-4062e58b-80b9-4d50-916a-221a149d23d3.mov

2. 📝 A short Pluto notebook file. (Upload the notebook file to https://gist.github.com/ and include the link.)

https://gist.github.com/hiiroo/57e5a1013e830ac70a71f11d312f8961

3. Hello, Pluto unable to show 3D Symbolic arrays. When attempted, it outputs a trace as shown in the video recording. I don't know if this is related to Pluto or Symbolics.jl but decided to post here, thanks.

**Comment by fonsp** [comment]
This has been fixed in #2109, can you update Pluto and try again?
