### ISSUE TITLE
Package management is broken

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#22]
Because of the moving workspaces, you have to use `import` instead of `using`. Also, all workspaces live inside `Pluto.ModuleManager`, so they can't use packages that you added to your environment. (Pluto has its environment separate from the one you started the REPL in.)

Things exported by a package, from `using`, don't show up in `names`:

```
julia> using Plots

julia> plot
plot (generic function with 3 methods)

julia> names(@__MODULE__, all=true, imported=true)
9-element Array{Symbol,1}:
 Symbol("##1#2")
 :Base
 :Core
 :InteractiveUtils
 :Main
 :Plots
 :ans
 :eval
 :include
```

**Comment by malyvsen** [comment]
I think that using packages which were added to `Main` is not high-priority - the standard use case does not involve the console, I think

**Comment by fonsp** [comment]
i though that maybe we can eval-inject a ModuleContainer into Main, so that our workspaces live in `Main.ModuleManager.workspaceN`. Perhaps we need to do `using`s separately - call the `using` onto the `Main` module, and then import it into the workspaces?

**Comment by fonsp** [comment]
But there must be an alternative to `names` that does include the module exports...
