### ISSUE TITLE
`ProgressLogging` progress bar has large overhead

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2203]
Using `ProgressLogging.@progress` inside Pluto causes a large overhead that scales roughly with the number of iterations. 
In this very simple notebook, it's about 0.05 seconds per iteration. In my actual use case, I observed an overhead of about 0.2 seconds per iteration (which happens to be longer than the computation itself).
https://gist.github.com/yha/9874d03c15175e4075bab565f3730b80

https://user-images.githubusercontent.com/4170948/177637740-19a428e4-8ac7-4a45-ac3f-169e298335bb.mp4

```

**Comment by Pangoraw** [comment]
Thanks for reporting! It will be fixed in the next released

**Comment by fonsp** [comment]
#2894 was reverted so this is fixed again
