### ISSUE TITLE
Shift + Enter does not work for existing cells on binder

### ISSUE THREAD

**Issue by uPvtkBlpiucvDUf** [fonsp/Pluto.jl#2215]
I exported a very simple Julia notebook as a html file. Then opened this html file in the browser and ran it on binder. There I cannot evaluate existing cells using Shift+Enter. But Shift+Enter does work for adding new cells.

[simplescreenrecorder-2022-07-14_00.43.51.webm](https://user-images.githubusercontent.com/35373762/178849649-81329e3a-be2a-435e-a663-d39b63eb0157.webm)

**Comment by fonsp** [comment]
Thank you for the video recording with developer console, let's get in fixed!
