### ISSUE TITLE
"welcome to" logo broken

### ISSUE THREAD

**Issue by pbouffard** [fonsp/Pluto.jl#2230]
I installed the latest release, v0.19.10, from GitHub. The Pluto logo image (after the "welcome to" text) doesn't seem to be found by the browser:

Safari:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/231346/181307968-9dbdfb62-ecf0-4381-9126-4cd334a1fab0.png">

Chrome:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/231346/181307922-4425fd3c-f5d4-4b41-8add-b2dcb039df5a.png">

This is on MacOS Monterey, Julia 1.7.3.

**Comment by Pangoraw** [comment]
Thanks for the report! It should be fixed in https://github.com/fonsp/Pluto.jl/commit/ad07c522cd0fecefe38eaad03aa876e56476fc84 (tagging a new release now)
