### ISSUE TITLE
[Feature Request] Open but do not run 

### ISSUE THREAD

**Issue by tbeason** [fonsp/Pluto.jl#2242]
It would be cool if from the main menu there was an option to "view" the notebook AKA open it but do not execute cells. Perhaps then I could make changes and it would execute upon first save or maybe there was a button to press that would make it execute.

I understand that I can open it in a text editor to see the code or make changes before opening it, but it'd be nice to be able to keep this all within the Pluto workflow.

**Comment by fonsp** [comment]
Thanks! You can subscribe to #259
