### ISSUE TITLE
Cell disabling not enough on windows :(

### ISSUE THREAD

**Issue by laggvar** [fonsp/Pluto.jl#2248]
I know the issue of cell disabling has been mentioned before was addressed in https://github.com/fonsp/Pluto.jl/pull/985. The last comment in the related issue https://github.com/fonsp/Pluto.jl/discussions/298 suggests a better implementation, but was left unaddressed. Thus, the current solution requires the user to manually disable a cell every time after running it. 

As a human being, I often forget to re-disable the cell, which means my computer gets stuck on long computations whenever I change something else. As I'm also forced to work on windows, I cannot interrupt a cell once it is running https://github.com/fonsp/Pluto.jl/issues/452. This gives me the option of either waiting 10 minutes for the computation, or restarting the notebook and waiting for 5 minutes of loading + pre-computations. 

If I cannot cancel a computation, it would be extremely helpful if I could put it into a mode where it at least can never run without my explicit permission. Essentially reactive by default, Jupyter-style as an opt-in (but without the hidden state 🙂). 

A solution to https://github.com/fonsp/Pluto.jl/issues/452 would of course also be ideal, but until then something better than the current cell disabling would be a significant improvement. It could also enable loading notebooks without automatically running the most expensive parts, improving on issues like https://github.com/fonsp/Pluto.jl/issues/2242.

**Comment by fonsp** [comment]
#452 is close to being solved! Subscribe to that issue, more progress is coming soon. 

For addition suggestions, could you use the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead? We appreciate the feedback!
