### ISSUE TITLE
Error loading notebook files when running via WSL

### ISSUE THREAD

**Issue by eahenle** [fonsp/Pluto.jl#2252]
When Pluto is launched from a Julia REPL running Windows Subsystem Linux (Pluto 0.19.11, Julia 1.8.0, Windows 10, Ubuntu 20.04), notebook files will not load from disk.

Inspecting the error message shows that the path is being processed incorrectly (in the video, note the duplication of `mnt/g/` in the `SystemError` path) although the message at the top of the page shows the correct path.  Pluto says it's trying to load one path, but actually tries to load another.  And, as seen in the video, this applies to files that Pluto's file loading interface can readily discover.

https://user-images.githubusercontent.com/16201240/186732408-c474c8cc-5768-47eb-bd21-a928fad6c438.mp4

**Comment by rikhuijzer** [comment]
Very related to #2217 and #2219. Do you see anything wrong with

https://github.com/fonsp/Pluto.jl/blob/72555eda2ba121a023243344ffa1dd75d3a17d35/src/notebook/path%20helpers.jl#L10-L39

**Comment by eahenle** [comment]
That does the trick, but the version of the function in the current release is no good:

![image](https://user-images.githubusercontent.com/16201240/186745534-a668a2a0-12f4-4e2a-b4ba-f43bfa020310.png)

So I guess WSL users have to use the dev branch for now?  Anyway, seems the actual bug has been solved--closing issue.

**Comment by rikhuijzer** [comment]
I meant that `maybe_convert_path_to_wsl` is used internally by Pluto and apparently not correct. It does look like a bug
