### ISSUE TITLE
Interpolating into markdown codeblock not working as intended?

### ISSUE THREAD

**Issue by alecloudenback** [fonsp/Pluto.jl#2253]
I asked this [on StackOverflow](https://stackoverflow.com/questions/73507799/how-to-interpolate-variable-into-markdown-codeblock-in-pluto-jl/73511339#73511339) and the answerer indicated that this might be a bug:

In Pluto if I try to include an interpolated value in the markdown string, it renders the string without interpolating the value. 
![image](https://user-images.githubusercontent.com/711879/187043664-d0be2901-da2f-47f0-95fc-1b5d28a1313e.png)

I'd like the string to render as: My variable's value is: 10

The answer I got was:

> Seems like a bug. You may use Markdown.parse instead of md"" literal.
> 
> ```julia
> Markdown.parse("""
> My variable's value is: `$x`.
> """)
> ```julia
>

**Comment by disberd** [comment]
I see the same behavior also in the Julia REPL, so if it is a bug it should be a Markdown bug, as it's not caused by Pluto

**Comment by MichaelHatherly** [comment]
Yeah, unrelated to `Pluto`. This is the expected behaviour of `md""` interpolation (as implemented in the `Markdown` module): e.g it won't interpolate inside of backtick literals. The suggestion of `Markdown.parse` usage instead is the correct solution.

**Comment by alecloudenback** [comment]
Thanks, I opened a issue here: https://github.com/JuliaLang/julia/issues/46565
