### ISSUE TITLE
the right way to move file

### ISSUE THREAD

**Issue by evadknarf** [fonsp/Pluto.jl#226]
What is the right way to open a file?

I made a copy of sample notebook on desktop but failed to open it....

![image](https://user-images.githubusercontent.com/14981695/88256949-319f6080-ccef-11ea-84e9-64cc01251e2f.png)

**Comment by evadknarf** [comment]
To supplement what I did: 

1. Open sample notebook and rename path to save it to Downloads;
2. Drag the file in Downloads to Desktop;
3. Failed to open via entering the new path (to Desktop)

Then I notice the PlutoUI.jl was still opened (though actual file has been moved to Desktop!) . I click close the Notebook. Then I can open the using the new path (to Desktop).

Another issue, after I have moved the file, the notebook is still able to save a copy in Downloads using a new name. But nothing happens by click rename if the same path persists.

**Comment by fonsp** [comment]
Hi!

Here's how you can move your notebook to a different folder (while it is running):
![howtomove](https://user-images.githubusercontent.com/6933510/88264525-2c7cea00-cccc-11ea-910d-04cef112a24d.gif)


It sounds like you moved the file using the _file manager_ while the notebook was still running - Pluto won't know that the file moved, and will continue to save to the original path. Programs generally don't allow you to move the savefile while you still have it open.

Maybe the confusion was that closing the browser tab does not shut down the notebook?

**Comment by evadknarf** [comment]
Yes I wasn't noticing that the session is still on.  If I make a copy of instead of directly moving the notebook while it is running, there is no issue. I can have both notebooks open. I will close the issue.

> Maybe the confusion was that closing the browser tab does not shut down the notebook?
