### ISSUE TITLE
Main menu: opening notebook in a new tab hides the main menu in current tab

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2301]
Ctrl+clicking an existing notebook (which isn't currently running) or the "create a new notebook" link opens it in a new tab as expected, but show the "Loading something.jl" message (#2292) in the current tab. You can't get back to the main menu with the browser's "back", only with reload.

**Comment by disberd** [comment]
I confirm the problem on Ubuntu under WSL in Windows 10
