### ISSUE TITLE
Refactor: rewrite FilePicker from a class component to a function component

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2304]
This is a great issue for people who want to learn more about react/preact/codemirror and want to contribute to Pluto!

This [`FilePicker` component](https://github.com/fonsp/Pluto.jl/blob/main/frontend/components/FilePicker.js) is currently written as a class component, but we would like to rewrite it to a function component, to match the rest of our source code. This means using hooks such as `useEffect`, `useState`, and more!

Take a look at the [`CellInput` component](https://github.com/fonsp/Pluto.jl/blob/main/frontend/components/CellInput.js), which has already been rewritten to a function component, and which also renders a codemirror. You can learn more about the interaction between codemirror and preact by looking at this example.

**Comment by eigengravy** [comment]
I would love to have a go at this issue!
