### ISSUE TITLE
Problem with PlutoUI.TableOfContents alignment

### ISSUE THREAD

**Issue by FerdinandRieck** [fonsp/Pluto.jl#2306]
There is a bug in the new PlutoUI.TableOfContents. In the TOC the subsubheader doesn't align at the right spot.

PlutoUI version: 0.7.43
![Heading_issue](https://user-images.githubusercontent.com/105821071/194695968-9036db98-33e6-472d-bd42-07c24a0e8d86.png)

Here was everything correct
PlutoUI version: 0.7.38
![image](https://user-images.githubusercontent.com/105821071/194696051-af72706b-24a9-4308-8a8f-065c52217439.png)

**Comment by fonsp** [comment]
Thanks! You can subscribe to https://github.com/JuliaPluto/PlutoUI.jl/issues/228
