### ISSUE TITLE
Error when loading Flux model from BSON file in Pluto

### ISSUE THREAD

**Issue by rgreilly** [fonsp/Pluto.jl#2307]
Hi,

I've run into a problem trying to load within a Pluto notebook a Flux network that's been saved in BSON format ("UndefVarError: NNlib not defined") .  The same code works OK in a REPL.

I'm pasting code from a Pluto notebook that illustrates the issue.  I'm also appending a link to a YouTube video characterising the problem.

Thanks for any help,
Ronan

```
begin
	using Flux
	using BSON
	using BSON: @save, @load
	using NNlib
end

begin
	model = Chain(Dense(10, 5, relu), Dense(5, 2), softmax)
	@save "mymodel.bson" model
	model = ()
	@load "mymodel.bson" model
	model
end
```

https://youtu.be/u-t18qvozsI

**Comment by pankgeorg** [comment]
Hello! Thanks for this report! Can you make the YouTube video not private? And also does this work fine out of Pluto?

**Comment by rgreilly** [comment]
Oops!  The video is public now.

Yes.  The code snippet works fine outside of Pluto.

Thanks for looking at this,
Ronan

**Comment by Pangoraw** [comment]
Thanks for the detailed report! There is a known issue with lookups in `BSON.@load` (see [#1383](https://github.com/fonsp/Pluto.jl/discussions/1380#discussioncomment-1154200)).

One solution is using the `BSON.load(path, init)` function with `@__MODULE__` instead. In your example, something like this will work:
```julia
begin
	model = Chain(Dense(10, 5, relu), Dense(5, 2), softmax)
	@save "mymodel.bson" model
	model = ()
	model = BSON.load("mymodel.bson", @__MODULE__)
	model
end
```
