### ISSUE TITLE
Tables.jl object not triggering Pluto table viewer

### ISSUE THREAD

**Issue by juliohm** [fonsp/Pluto.jl#2309]
The [attached notebook](https://julialang.zulipchat.com/user_uploads/7178/scisJPpde4SIT56FWspa-R6n/test.jl) (see also below) defines a `geotable`, which is a Tables.jl object. The Pluto's built-in table viewer is not being triggered:

![image](https://user-images.githubusercontent.com/3345261/195069434-7058990c-5a69-4e69-8324-3684f6983e5d.png)

Can you help understand why that is the case?

**Comment by pankgeorg** [comment]
Hey! I can't reproduce this with `julia 1.8.2`, `pluto 0.19.12` or *13 running on WSL. Can you share more about your setup?

**Comment by juliohm** [comment]
I am on the same setup, Julia v1.8.2, Pluto v0.19.13, Linux. What is the current logic to display the table viewer? I could try to help debug what is happening with this specific table type.

**Comment by pankgeorg** [comment]
The logic resides in PlutoRunner.jl, mostly.

- The type must not have specialized show methods: https://github.com/fonsp/Pluto.jl/blob/main/src/runner/PlutoRunner.jl#L1077-L1095

- You must allow the mime (not override this https://github.com/fonsp/Pluto.jl/blob/main/src/runner/PlutoRunner.jl#L1103)
-

**Comment by juliohm** [comment]
@pankgeorg it is very strange that it only happens with that particular dataset I shared. If you open the same notebook and create a different object without using the dataset, then it displays properly:

![image](https://user-images.githubusercontent.com/3345261/195092186-b6151b36-01f5-4753-8cad-5f397e4925d3.png)

I wonder why given that these two objects have the same type in theory. Is there any logic on the number of columns for example?

**Comment by juliohm** [comment]
Here you can find the show methods:

https://github.com/JuliaGeometry/Meshes.jl/blob/master/src/traits/data.jl#L201

**Comment by rikhuijzer** [comment]
For future reference and people who cannot login to Zulip, this is the notebook:

```julia
### A Pluto.jl notebook ###
# v0.19.9

using Markdown
using InteractiveUtils

# ╔═╡ 7bf2c6b2-48e0-11ed-03a1-713809e45593
using GeoStats

# ╔═╡ caf64249-e6d7-494c-873c-c8658dd5a2d6
using CSV

# ╔═╡ 81a68a55-5874-4efa-b1ce-4ea0467393e6
table = let
        url = "https://zenodo.org/record/7051975/files/drillholes.csv?download=1"
        fname = download(url)
        CSV.File(fname)
end

# ╔═╡ a680a96d-ffcb-4879-9cee-06cc7a4510c8
geotable = georef(table, (:X,:Y,:Z))

# ╔═╡ Cell order:
# ╠═7bf2c6b2-48e0-11ed-03a1-713809e45593
# ╠═caf64249-e6d7-494c-873c-c8658dd5a2d6
# ╠═81a68a55-5874-4efa-b1ce-4ea0467393e6
# ╠═a680a96d-ffcb-4879-9cee-06cc7a4510c8
```
with CSV 0.10.4 and GeoStats 0.35.1.

**Comment by fonsp** [comment]
This might be caused by https://github.com/fonsp/Pluto.jl/pull/2109

**Comment by juliohm** [comment]
Maybe it is related to the name of the columns in the table? The logic implemented in that PR assumes ascii column names? I noticed that whenever I introduce Greek letters as column names the viewer is not triggered.

**Comment by juliohm** [comment]
I am just guessing of course, is there any update on this? Can we have a hotfix?

**Comment by pankgeorg** [comment]
I can't quite reproduce this, still :(

**Comment by juliohm** [comment]
@pankgeorg anything I can do to help? A video chat where I try a few things in front of you? I am planning a tutorial where the table viewer would be very didactic.

**Comment by fonsp** [comment]
You could change [this](https://github.com/fonsp/Pluto.jl/pull/2109/files#diff-0cc97f3d6a0f647a05e5f913d416242ecb00f6e67e12004a7204b8846a3fa44cR1092) to catch the error `e` and log it to see what is going on

**Comment by eliascarv** [comment]
I run this notebook in Pluto v0.19.6 and in found this error message:
![image](https://user-images.githubusercontent.com/73039601/197396644-d2b3e1ae-e77a-47e0-ae89-0dae42d0a787.png)

**Comment by juliohm** [comment]
Yes, I believe that Pluto is incorrectly relying on getindex for Tables.rows, but the Tables.jl interface only requires iterables.

**Comment by juliohm** [comment]
@pankgeorg did you have a chance to take a look into this? I am preparing a tutorial where the table viewer would be super helpful. It seems that the fix is simple now that we know the root of the error? Whatever is returned by Tables.rows(table) needs to be collected if the code in Pluto is calling getindex.

**Comment by pankgeorg** [comment]
Pluto is not calling `getindex` but it _is_ calling `lastindex` through `last`. In my environment it doesn't, because `applicable(lastindex, Tables.rows(geotable))` is _false_. For some reason, in the environment you're running _Pluto_ it's true (but it's not really true). What are you importing in parallel with pluto (in the session you're doing `Pluto.run()`)?

In the meanwhile for your tutorial you can probably use this patch https://github.com/fonsp/Pluto.jl/pull/2341.

Is the tutorial going to be available online? I'd like to take a look!

**Comment by juliohm** [comment]
> For some reason, in the environment you're running _Pluto_ it's true (but it's not really true). What are you importing in parallel with pluto (in the session you're doing `Pluto.run()`)?

I am running Pluto from a global environment with OhMyREPL.jl, PkgDependency.jl and other utility packages that are not loaded in the Pluto session itself. @eliascarv could also reproduce the issue in his own computer with a different environment than mine.

> Is the tutorial going to be available online? I'd like to take a look!

It will be a video tutorial, I will share it on YouTube :) Unfortunately the data is too large to share in a repository this time.

**Comment by pankgeorg** [comment]
> I am running Pluto from a global environment with OhMyREPL.jl, PkgDependency.jl and other utility packages that are not loaded in the Pluto session itself. @eliascarv could also reproduce the issue in his own computer with a different environment than mine.

Yes, I'm not implying it's your fault, I just want to understand the mechanics!

@eliascarv what about your environment?

@juliohm did the PR work for you?

**Comment by eliascarv** [comment]
This is my global env:
```julia
(@v1.8) pkg> st
Status `C:\Users\Dev01\.julia\environments\v1.8\Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.1
  [5fb14364] OhMyREPL v0.5.12
  [c3e4b0f8] Pluto v0.19.14
  [295af30f] Revise v3.4.0
```

**Comment by juliohm** [comment]
I confirm that this issue is happening just because we are defining `getindex` for our table type to mimic DataFrame's `df[rows,cols]` interface. If we comment out the getindex methods [here](https://github.com/JuliaGeometry/Meshes.jl/blob/6a59231a1213c34d43e88e0ea3137f30c7385e25/src/traits/data.jl#L151-L225) the table is correctly displayed in Pluto. Can you please consider a hot fix @pankgeorg?

Can you explain why the following algorithm is not implemented in Pluto to dispatch the table viewer more reliably?

```julia
if Tables.istable(object)
  # display table!
else
  # do complicated checks to
  # figure out if the table
  # viewer can still be used!
end
```

**Comment by pankgeorg** [comment]
Hey @juliohm ! Is this still happening on Pluto 0.19.16? We did apply some fix 🤔

**Comment by juliohm** [comment]
Yes, the issue is still valid with the latest release.

Em qua., 23 de nov. de 2022 03:21, Παναγιώτης Γεωργακόπουλος <
***@***.***> escreveu:

**Comment by pankgeorg** [comment]
> As you can see I defined a trivial table that is fully compliant with the Tables.jl interface and yet pluto is calling the auto-generated text/plain show method. I think we should fix this basic example first before going to the getindex interference.

This is not the `plain/text` method, but the struct viewer. Plain text is terminal-like.
I'll look into the issue - I thought it was fixed (it doesn't appear on my system eitherway)

**Comment by juliohm** [comment]
> I'll look into the issue - I thought it was fixed (it doesn't appear on my system eitherway)

Can you clarify how is that possible? Are you also using the latest stable release of Pluto on Julia v1.8.2? Maybe it is a Julia version issue?

**Comment by juliohm** [comment]
@pankgeorg can you clarify the issue above? Also, is there any way that I can overwrite the Base.show method for a specific MIME type that Pluto uses? I want to display my types as tables no matter how the current logic in Pluto is implemented. Is that possible?

**Comment by juliohm** [comment]
Thank you @pankgeorg for the workaround. I confirm that it works in the latest stable Pluto release. Looking forward to a more official fix in the next release.
