### ISSUE TITLE
Displaying expected errors for users

### ISSUE THREAD

**Issue by kellertuer** [fonsp/Pluto.jl#2311]
I am currently writing a tutorial for one of my packages, see for example 

https://juliamanifolds.github.io/Manifolds.jl/previews/PR534/tutorials/getstarted.html

For a PlutoStaticHTML version. Now I would like to illustrate as well “How things fail” and which errors to expect and how to read them. In 

https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/148

I noticed that it might be nice to have a Pluto-Way of rendering an error – but an error that is expected! Maybe a nice red box with the error message (similar to terminal output)?

The two ideas I have for this would be to use maybe a macro

```
@expected_error MyErrorType  my_code
```

which is defined to do nothing if the script is run as a script – or does a simple try-catch so the script does not fail.
For Pluto the macro would also basically try-catch the error (the one expected one) and display it

Currently one way I can do this is the little hand-crafted way in the cell just before “3. The Sphere”, but the display is not yet so nice (just a code block again).

Is something like that possible?

**Comment by rikhuijzer** [comment]
> Currently one way I can do this is the little hand-crafted way in the cell just before “3. The Sphere”, but the display is not yet so nice (just a code block again).

Please include an image of this for future reference.

> I noticed that it might be nice to have a Pluto-Way of rendering an error – but an error that is expected! Maybe a nice red box with the error message (similar to terminal output)?

Maybe a bit of a stupid question, but could you also make an image of what you would want to see here? I personally find https://github.com/rikhuijzer/PlutoStaticHTML.jl/issues/73#issuecomment-1042305998 quite clear, so I wonder how that could be improved

**Comment by kellertuer** [comment]
<img width="962" alt="Screenshot 2022-10-12 at 10 21 59" src="https://user-images.githubusercontent.com/115566/195290912-7690d6e0-4cd2-4edb-ab61-67f9f40e625f.png">

What I would prefer is really just a display of the error, not the stack trace and in style different from a code block (maybe closer to what Pluto does recently with terminal output).

**Comment by rikhuijzer** [comment]
> What I would prefer is really just a display of the error

What does this mean? The stacktrace is usually part of the "display". Especially at the REPL.

**Comment by Pangoraw** [comment]
What about something like [this](https://pangoraw.github.io/Notebooks/expected_error)?

![image](https://user-images.githubusercontent.com/9824244/195309460-f3e5b084-aabb-433f-8cc4-ca938070840c.png)

I am not sure I understand what Pluto could provide that cannot be written directly inside the notebook with `try/catch`.

**Comment by kellertuer** [comment]
Wow! That would be super nice and is exactly what I had in mind :)

**Comment by kellertuer** [comment]
> > What I would prefer is really just a display of the error
> 
> What does this mean? The stacktrace is usually part of the "display". Especially at the REPL.

See the first solution up there – I think one could also extend that and provide the stack trace if the user wants, but my main point is to illustrate which error to expect, for my tutorial I do not need the stack trace.

**Comment by kellertuer** [comment]
Ah,  there is one thing missing in the code – if the expected error does not occur it would be fair to error in the notebook. that way the expected error _has_ to occur for the notebook to run without errors.

**Comment by Pangoraw** [comment]
> Ah, there is one thing missing in the code – if the expected error does not occur it would be fair to error in the notebook. that way the expected error has to occur for the notebook to run without errors.

That makes sense. Something like this should do the trick (I have not tested):

```diff
macro expect_error(code, error=:DomainError)
	quote
		try
			$(esc(code))
+                       error(string("Error of type ", $(esc(error)), " was not thrown."))
		catch e
			if e isa $(esc(error))
				pretty_error(e)
			else
				rethrow()
			end
		end
	end
end
```

**Comment by kellertuer** [comment]
Oh that was easier than I thought ;)

Nice solution, thanks!

**Comment by fonsp** [comment]
You could also log the `error,stacktrace` to get Pluto's nice display:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/6933510/195325484-5aa56b6f-2ef3-4b2e-98a8-abc6641e8ced.png">

```julia
try
	sqrt(-1)
catch e
	@warn "Expected error" exception=(e,catch_backtrace())
end
```

**Comment by kellertuer** [comment]
> > Ah, there is one thing missing in the code – if the expected error does not occur it would be fair to error in the notebook. that way the expected error has to occur for the notebook to run without errors.
> 
> That makes sense. Something like this should do the trick (I have not tested):
> 
> ```diff
> macro expect_error(code, error=:DomainError)
> 	quote
> 		try
> 			$(esc(code))
> +                       error(string("Error of type ", $(esc(error)), " was not thrown."))
> 		catch e
> 			if e isa $(esc(error))
> 				pretty_error(e)
> 			else
> 				rethrow()
> 			end
> 		end
> 	end
> end
> ```

Just copying this over my notebook complaints it does not now `pretty_error`, but `using Pluto: pretty_error` before also does not work – what am I missing (running your notebook on binder failed with binder error/timeout).

**Comment by kellertuer** [comment]
> You could also log the `error,stacktrace` to get Pluto's nice display:
>  [...]
> ```julia
> try
> 	sqrt(-1)
> catch e
> 	@warn "Expected error" exception=(e,catch_backtrace())
> end
> ```

Also a neat idea! I am fine without the stack trace though :)

**Comment by kellertuer** [comment]
I changed the error display to something that informs more about what the error looks like

```
function pretty_error(err) 
    Markdown.parse("""
!!! info "This is how the Error we expect here looks like"
    ```
    $(replace(sprint(showerror, err), "\n" => "\n        "))
    ```

""")
end;
```
mainly also using one code block for the error message and the result looks like

<img width="904" alt="Screenshot 2022-10-12 at 13 25 14" src="https://user-images.githubusercontent.com/115566/195330658-73ca4a48-b333-4c2b-83ab-2c9e91c91d8d.png">

Thanks for this really nice idea and the fast response!
