### ISSUE TITLE
Variable assigned through splat never updates

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2314]
For example, here `y` doesn't update, even when manually re-running the cell referring to it.

https://user-images.githubusercontent.com/4170948/195596667-17b22585-5163-45e3-9d77-2f6b9094bef4.mp4

**Comment by Pangoraw** [comment]
Note the console warning:
```
┌ Warning: unknown use of `=`. Assignee is unrecognised.
│   ex = :(y...)
└ @ Pluto.ExpressionExplorer ~/.julia/packages/Pluto/rBF1P/src/analysis/ExpressionExplorer.jl:152
```
