### ISSUE TITLE
File/folders starting with . does not appear in autocomplete

### ISSUE THREAD

**Issue by Dsantra92** [fonsp/Pluto.jl#2316]
The autocomplete feature in the box for inserting notebook paths does not work for folders starting with ".". I expected the autocomplete functionality to show a suggestion of ".julia" when I typed in ".ju" but it did not. I am not totally sure if this is intentional.

![pluto](https://user-images.githubusercontent.com/55111154/195957156-43bfd923-a732-4abc-a96c-4c725cb3de30.gif)

**Comment by fonsp** [comment]
Thanks for the video! This is intentional, see https://github.com/fonsp/Pluto.jl/issues/1785
