### ISSUE TITLE
Run cell button is at the bottom of output

### ISSUE THREAD

**Issue by 8G6** [fonsp/Pluto.jl#2317]
I am a beginner using Pluto.jl. My suggestion is that can you make the run button at the top of the cell, it will be more user-friendly.[image](https://user-images.githubusercontent.com/56481296/195992055-4af3eae6-d077-4dda-bb68-fe99e382f715.png)

**Comment by fonsp** [comment]
Thanks! Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?

**Comment by 8G6** [comment]
Ok
