### ISSUE TITLE
Scroll-to-definition for Markdown footnotes & headers

### ISSUE THREAD

**Issue by evadknarf** [fonsp/Pluto.jl#232]
Is [footnote](https://docs.julialang.org/en/v1/stdlib/Markdown/#Footnotes-1) supported in Pluto?

I tried the syntax, usually need to leave 1-3 empty space before footnote mark, `[^1]:`, to have it display correctly. Otherwise the content after footnote mark will be shown in a separate line. 

Even formatted correctly, it doesn't seem to work [jump to and fro] at this moment.😂

**Comment by fonsp** [comment]
Thanks! Jump to definition scrolling can be added 👍

**Comment by fonsp** [comment]
#235 for making it display nicer

**Comment by fonsp** [comment]
Automatic scrolling to footnotes already works - this is built in to browsers:

```
md"Hey I am referencing [^1], [^two] and [^another_one_here].

[^another_one_here]: Heyy"
```

Maybe it only works if the definition is outside of the visible part of the page? And if the page is large enough to scroll.

**Comment by evadknarf** [comment]
I leave 1 empty Space_ before: `_[^another_one_here]: Heyy` to have the footnote appear in 1 line, and that breaks the link. So the leading whitespace does matter here.

The footnotes appear like this:
![Screen Shot 2020-07-29 at 12 36 54 PM](https://user-images.githubusercontent.com/14981695/88757305-4325b400-d198-11ea-9ecc-b86f9d87a81a.png)

Which is not very nice.

**Comment by fonsp** [comment]
(This is one the quirks of Julia's Markdown parser, not Pluto:) 
Adding the space at the start of a line will create a _paragraph_ element, which contains the rest of the characters of that line. Footnote **definitions** cannot appear inside paragraphs, they have to be at "top-level". Only footnote **references** can appear inside paragraphs. So:
```julia
 [^asdf]: I am a reference to asdf

[^asdf]: I am a definition of asdf
```

**Comment by fonsp** [comment]
Footnotes look a lot nicer now, try it out!

**Comment by evadknarf** [comment]
How about:
![image](https://user-images.githubusercontent.com/14981695/89830210-6ab04f80-db8e-11ea-8eaf-25b752ec022c.png)

Clunky code, but markdown looks neater with jump to and fro at least.

**Comment by fonsp** [comment]
Unfortunately that's a lot more work than you might think
