### ISSUE TITLE
Update from 19.12 to 19.14 - often hangs when opening notebook

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#2337]
Seems to be stuck while loading packages.

![image](https://user-images.githubusercontent.com/1438610/199250027-2fbc41a0-48e8-4652-a88d-3929715d3e91.png)

Killing the notebook process and restarting it can resolve it.

Problem is that I have trouble reproducing it. It's happened twice now today. If I can learn more, I'll add to this.

Working: 0.19.12
Not working: 0.19.14

(edited to remove irrelevant parts of image)

**Comment by fonsp** [comment]
Looking at the [diff](https://github.com/fonsp/Pluto.jl/compare/v0.19.12...v0.19.14), relevant changes could be:
- https://github.com/fonsp/Pluto.jl/pull/2298 (this change happens before instantiating the environment, which already happened in the screenshot)
- https://github.com/fonsp/Pluto.jl/pull/2289 (but you would probably get an error message in the terminal if this fails)
- https://github.com/fonsp/Pluto.jl/pull/2318
- https://github.com/fonsp/Pluto.jl/commit/9aad08d1f8878d8ff59cfb674088627f49f2a4ff (but this just adds more safety)

**Comment by fonsp** [comment]
It could actually be https://github.com/fonsp/Pluto.jl/pull/2318 , in the screenshot, it looks like Pluto's package manager finished (you can see the ✅), but the first cell that should run (the cell with imports) is not yet running (the timer is still at `---`). Perhaps the notebook is stuck creating a workspace process...

**Comment by rikhuijzer** [comment]
Could it be that updating the registry fails for some reason? I am currently also having some problems with a registry update inside a Docker. I one time saw an error from HTTP that the transfer speed was below 1kB/s.

@BioTurboNick, you're not on Windows, right?

**Comment by BioTurboNick** [comment]
In this case it was running on an AWS Linux computer.

**Comment by fonsp** [comment]
If it is the case that it gets stuck on the registry update, we will be able to see that after #2399 :)

**Comment by fonsp** [comment]
#2399 has been released

After loading Pluto, open a notebook, and then press F12 to open the web developer tools. Go to the JavaScript console, and type:
```js
PLUTO_TOGGLE_PROCESS_TAB()
```
to enable the feature.

Could you enable the feature, and let us know the next time a hang happens?

**Comment by BioTurboNick** [comment]
I think I'll close this for now - I haven't noticed it in a while. I'll revisit if I observe it again.
