### ISSUE TITLE
Manually remove item from recent sessions.

### ISSUE THREAD

**Issue by PhyX-Meow** [fonsp/Pluto.jl#2340]
Is there a way to remove particular items in Recent sessions, or just clear them all?
For example I need delete some cache file at somewhere?
I have runed many notebooks and most of them have been deleted, but they still lie in Recent sessions, making it a very long list. This makes me hard to find notebooks that still valid. Even worse, if I renamed a notebook, or move its folder, there will be two of them, it's really annoying.
Thank you for any help.

**Comment by pankgeorg** [comment]
Open a javascript console (F12) and do `localStorage.clear()` - that will purge all notebooks from the list - old and new.

**Comment by PhyX-Meow** [comment]
@pankgeorg Thanks! That's enough for me.
Still, a button in Recent session list to remove an item will be very useful.

**Comment by fonsp** [comment]
See #563, which has the "one day" label
