### ISSUE TITLE
Segfault when instsalling Pluto on Apple Silicon / Julia 1.8.2

### ISSUE THREAD

**Issue by habemus-papadum** [fonsp/Pluto.jl#2347]
On Julia 1.8.2, Mac, aarch64 I get a segfault when trying to install Pluto.   

https://user-images.githubusercontent.com/1161604/198350157-269db4b8-4960-4bdd-b65c-c06a0d70033b.mov

**Comment by fonsp** [comment]
Thanks for the issue report @habemus-papadum ! Could you repost this issue to https://github.com/JuliaLang/julia ? They will be able to help you further.
