### ISSUE TITLE
Custom plain text `Base.show` for composite structs will disable Pluto's object tree view

### ISSUE THREAD

**Issue by liuyxpp** [fonsp/Pluto.jl#2349]
Say we have a simple type `A` and a composite type `AB`:

```julia
struct A
    data
end

struct AB
    va::Vector{A}
    b::Int
end
```

`A` has an image representation, which can be shown as

```julia
Base.show(io::IO, mime::MIME"image/svg+xml", ab::AB) = show(io, mime, plot(ab))
```

Then, in a Pluto cell, all following codes will display images

```julia
# cell 1
A()
# cell 2
[A(), A()]
# cell 3
AB([A(), A()], 1)
```

In particular, a tree view will be displayed for the `AB` object with images presented.

However, if we define a custom `Base.show` for `AB` with either

```julia
function Base.show(io::IO, ab::AB)
    show(io, ab.va)
    print(io, ab.b)
end
```

or

```julia
function Base.show(io::IO, ::MIME"text/plain", ab::AB)
    show(io, ab.va)
    print(io, ab.b)
end
```

Then, the Pluto tree view of an object will be disabled when running following code in a Pluto cell

```julia
# in a Pluto cell
AB([A(), A()], 1)
```

meaning that no images will be displayed for any `A` object. Instead, the plain text representation defined in the custom `Base.show` will be displayed.

At present, my workaround is to define a custom `Base.print` instead of `Base.show` for `AB`. However, I have to use `print(ab)` in REPL to get the custom display where `ab` is an instance of `AB`. Run `ab` in a REPL line will call the Julia default `Base.show` to display the object.

My question is, can Pluto figure out a way to allow user define his own custom `Base.show` without disabling its object tree view?

**Comment by fonsp** [comment]
Hi @liuyxpp !

This is currently not possible (as far as i know), but we might add API for this in the future: https://github.com/JuliaPluto/AbstractPlutoDingetjes.jl/issues/10

One thing you can do is define two show methods for `AB`: one for `text/plain` and one for `text/html`, which uses your display of `A`:

<img width="629" alt="Scherm­afbeelding 2022-11-01 om 12 56 27" src="https://user-images.githubusercontent.com/6933510/199227352-499b0b3f-7a73-4b09-8cdd-760dde378e54.png">

https://gist.github.com/fonsp/625037764d89516571afbd33d3082b93

The `html` show method only applies to Pluto (and VS Code, Jupyter, etc), not to the REPL.

**Comment by fonsp** [comment]
Let me know if this worked, and subscribe to https://github.com/JuliaPluto/AbstractPlutoDingetjes.jl/issues/10 to receive further updates!

**Comment by liuyxpp** [comment]
Thanks! I really like the way Pluto object tree view. So I will stick to my  current hack and will not try your HTML trick. I will wait https://github.com/JuliaPluto/AbstractPlutoDingetjes.jl/issues/10.
