### ISSUE TITLE
Failure to *using Pluto* from a particular path

### ISSUE THREAD

**Issue by baggepinnen** [fonsp/Pluto.jl#2352]
On 
```
(@v1.8) pkg> st Pluto
Status `~/.julia/environments/v1.8/Project.toml`
  [c3e4b0f8] Pluto v0.19.14

Julia VERSION
v"1.8.2
```
I cannot load the Pluto package. 
```
julia> using Pluto; Pluto.run()
ERROR: InitError: IOError: pwd(): no such file or directory (ENOENT)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:97 [inlined]
  [2] pwd()
    @ Base.Filesystem ./file.jl:63
  [3] __init__()
    @ Pluto.Configuration ~/.julia/packages/Pluto/JnB0V/src/Configuration.jl:27
  [4] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loading.jl:1039
  [6] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1315
  [7] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [8] macro expansion
    @ ./loading.jl:1180 [inlined]
  [9] macro expansion
    @ ./lock.jl:223 [inlined]
 [10] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
during initialization of module Configuration
```
Based on the error message, I tried to wipe the `/compiled` folder from `.julia` and everything recompiled just fine, but I still cannot load Pluto. 

However, if I navigate my terminal to another path, one that doesn't contain the notebook I wanted to launch, Pluto loads fine. I'd be happy to share the notebook contained in the folder from which I could not load pluto if required. It contains, among many other things, a cell with
```julia
Pkg.activate(joinpath(@__DIR__, ".."))
```
which, to me, looks like the most likely offender.

It does strike me as a bit odd that I couldn't even `using Pluto` from this path.

![image](https://user-images.githubusercontent.com/3797491/199426383-3272dc9f-bac2-4ae6-87cd-e3dc5016ba79.png)

**Comment by fonsp** [comment]
Thanks for the issue @baggepinnen ! Are you able to run this in the path:
```julia
julia> pwd()
```

Is the path just a local directory, or something special like a network drive?

**Comment by baggepinnen** [comment]
Coming back to this, I can now launch Pluto from the previously problematic path :/ 
Last time when the error occurred, I recall first starting Pluto, launching the notebook and doing some package operations from within the notebook, before the same error message appeared. After terminating Pluto and restarting julia, I could then no longer launch Pluto. 

I realize this is not much info to go on so feel free to close this issue until I, or someone else, find a more reproducible way of triggering this error.
