### ISSUE TITLE
Feature request: docstring for Pluto cells

### ISSUE THREAD

**Issue by mind6** [fonsp/Pluto.jl#2355]
### Discussed in https://github.com/fonsp/Pluto.jl/discussions/2354

<div type='discussions-op-text'>

<sup>Originally posted by **mind6** November  4, 2022</sup>
I would like to see the ability to write a docstring for any individual cell. Sometimes a cell is there to provide state, I don't want to see the printout of the state, just the docstring for what that state represents. This way hidden cells can show a meaningful output instead of occupying a darkened area on the notebook page. 

Right now if you put a string on top of a begin/end block, Pluto actually tries to process it as a docstring but fails to do so.
```
cannot document the following expression:

begin
<julia code>
end

error(::String, ::String)@error.jl:44
top-level scope@[Local: 1](http://localhost:1234/edit?id=ae68b340-5c36-11ed-3b95-6de589f0a234#)[inlined]
```

**Comment by mind6** [comment]
Currently in Pluto it's possible to show docstring for a single output variable. It's only an error to try to docstring a begin...end block 
![pluto docstring](https://user-images.githubusercontent.com/9737618/200089206-24f08d4e-2fa7-4539-9210-3edc65ffcb33.PNG)

**Comment by dralletje** [comment]
Sadly that's not up to Pluto, but part of Julia itself :/

It might look a bit silly, but you can put markdown at the end of your block to render instead:

```
begin
    y = "y's value"
    z = "z's value"
    md"> sets up variables y and z"
end
```
