### ISSUE TITLE
Cell height glitch

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2363]
These single line cells are too high:

![image](https://user-images.githubusercontent.com/6933510/201093364-9e327722-6b43-4d11-853f-2dade59e9672.png)

**Comment by fonsp** [comment]
Caused by the inline height style of the gutter element, somehow miscalculated by CM:

![Scherm­afbeelding 2022-11-10 om 13 49 01](https://user-images.githubusercontent.com/6933510/201095710-fa601380-8a48-4a11-ae2f-7e5a05bbeff8.png)

**Comment by fonsp** [comment]
Caused by https://github.com/codemirror/dev/issues/996

**Comment by dralletje** [comment]
Guess this is also fixed by [#c741b243590ee9a07d6836e2fb2af2d71d0750a6 ](https://github.com/fonsp/Pluto.jl/commit/c741b243590ee9a07d6836e2fb2af2d71d0750a6)
