### ISSUE TITLE
CLI for Pluto

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#237]
Hi Pluto team,

I made a CLI for Pluto using [Comonicon](https://github.com/Roger-luo/Comonicon.jl). The functionality is a bit limited since
there is not much functionality I can forward to `Pluto.run`, but I hope this would make things awesome in terminal. You can check the CLI package here: https://github.com/Roger-luo/PlutoCLI.jl

and a glance of how it looks like in terminal, the startup takes about 500ms on my laptop, thus I guess this is not a big deal, but if anyone think this is still too slow, I could setup a system image CI like [IoncLI](https://github.com/Roger-luo/IonCLI.jl) here which can reduce this to about 200ms on my laptop. (you won't need to build it yourself)

![image](https://user-images.githubusercontent.com/8445510/88871341-a8ec5d00-d1e5-11ea-9b5c-beb75edceb2e.png)

It does not depend on Pluto directly but call Pluto in the global default environment (or Pluto will start from this CLI package's local environment). If you don't have Pluto installed, it will ask you

![image](https://user-images.githubusercontent.com/8445510/88871427-d9cc9200-d1e5-11ea-947f-e49c8cd4c912.png)

Hope whoever want to have a terminal CLI enjoy it.

**Comment by Roger-luo** [comment]
I do hope to support running a Pluto notebook from terminal directly in the future if #236 will be considered.

**Comment by fonsp** [comment]
@malyvsen look!

**Comment by fonsp** [comment]
Wow and it even prompts to install pluto! very cool

**Comment by fonsp** [comment]
See https://github.com/fonsp/Pluto.jl/pull/230 for the conversation about PlutoUtils.jl

**Comment by malyvsen** [comment]
Amazing! We were thinking about making something like this but ran into technical problems

**Comment by Roger-luo** [comment]
just an update: we have moved this to [PlutoUtils.jl](https://github.com/fonsp/PlutoUtils.jl/)
