### ISSUE TITLE
Unnecessary vertical scrollbar appears in the input area (Chrome & Linux )

### ISSUE THREAD

**Issue by holomorphism** [fonsp/Pluto.jl#2373]
At some point (probably 2022-11-04), unnecessary vertical scrollbars began to appear in the input areas.
See the following screenshot. (The scrollbar will appear after the notebook is loaded and the input area is activated)

![input_area_vertical_scrollbar](https://user-images.githubusercontent.com/3076585/202376815-71e7326f-de22-4cae-a381-683840a30af5.gif)

My environment is as follows:
* Pluto v0.19.15
* Linux (Xubuntu 22.04)
* Chrome (version 107.0.5304.87)

Firefox (version 107.0) does not have this problem.

This problem started happening when I updated Pluto from commit  eca8648f to commit 20b3287b. I thought it might be caused by this update, but reverting to commit eca8648f did not fix the problem.

I then updated to commit 4af5a569 and the problem is still there.
I have a feeling this issue is related to Issue #2363, but my problem was not fixed in commit c741b243.

It seems that chrome was updated to version 107 at the same time the problem started occurring, so chrome may be the cause.

I currently hide this scrollbar by adding the following line to `editor.css`.

```css
pluto-input .cm-editor .cm-scroller {
    overflow-x: visible;
}
```

I don't really understand the significance of this setting.
I checked with chrome's DevTools and found that the setting `"overflow-x: auto;"` on elements with `class="cm-scroller"` seemed to be causing this scrollbar to appear, so I added the above setting to disable it.

**Comment by fonsp** [comment]
I can't reproduce on MacOS Chrome 107

@holomorphism Could you confirm that https://github.com/fonsp/Pluto.jl/pull/2377 fixes the problem?

**Comment by holomorphism** [comment]
@fonsp Thank you very much.

#2377 did not fix the problem.
The fix needs to be applied to `pluto-input .cm-editor .cm-scroller`, not `pluto-filepicker .cm-scroller`.
Also, it needs to be set to `overflow-x: visible;` instead of `overflow-x: hidden;`.

I will write a comment to the diff in #2377.
