### ISSUE TITLE
Can Pluto.jl & Revise.jl work together?

### ISSUE THREAD

**Issue by jarvist** [fonsp/Pluto.jl#238]
I'm a computational scientist, so I often have a workflow where I'm simultaneously writing a Julia package, and then using a notebook to run experiments & make plots as I change stuff. Using Tim Holy's Revise.jl is really useful here, as you can edit functions & all it just works. 
In a Jupyter notebook, this workflow requires a first cell something like:
```
using Revise
using Pkg
Pkg.activate("../")
using MyPackage
```

However, this doesn't seem to work in Pluto. It doesn't give any errors, but also Revise.jl does not automatically update. Instead you have to shut down & restart the kernel as you make edits. 
Am I doing something wrong, or is there some fundamental incompatibility with Revise.jl?

**Comment by fonsp** [comment]
I'll come back to this later - I am considering enabling Revise by default, and doing the same from `include`: #78 and https://github.com/fonsp/Pluto.jl/issues/115#issuecomment-661405264

**Comment by jarvist** [comment]
Great! I think Revise (or equivalent) and Pluto would be very natural to use together.

**Comment by lungben** [comment]
I am very much in favor of it, it would have saved me quite some time yesterday ;-)

Should Revise be executed on the Pluto server side, e.g. 
```
using Revise
using Pluto
Pluto.run(1234)
```
or in the notebooks?

Probably both are fine from user perpective.

**Comment by fonsp** [comment]
#416

**Comment by jarvist** [comment]
Fantastic!

**Comment by fonsp** [comment]
Done! You need Revise `2.7.6` and Pluto `0.12.0` (not released yet) 🙂
