### ISSUE TITLE
link to package github page and changes to upgrade Pkg layout

### ISSUE THREAD

**Issue by AshtonSBradley** [fonsp/Pluto.jl#2383]
### Discussed in https://github.com/fonsp/Pluto.jl/discussions/2380

<div type='discussions-op-text'>

<sup>Originally posted by **AshtonSBradley** November 21, 2022</sup>
Inline documentation is great, but what would also be presumably easy to add and greatly aid getting package info would be a link to the github page for the package. 

I have in mind adding a link to this list, as it is relevant to the package itself. This could be next to, or instead of, pluto package management which seems somehow less relevant to the user:

<img width="458" alt="Screenshot 2022-11-21 at 3 20 40 PM" src="https://user-images.githubusercontent.com/24194258/202947297-a053e0cd-8344-4e74-86e2-40690835d4ae.png">

I would see the pluto package management link as a more global link that could go in the notebook header toolbar maybe?

To give a bit more context, I find that as a frequent user I don't  typically need to know about how to override Pluto package management: I am already using Pluto _because_ of the nice package management. Overriding Pluto Pkg seems to me to be a more global choice, not tied to a specific package. 

What I really want tied to a specific package name, is a link to the package github page. From there I can view full docs, read tests, etc.

Also I find the upgrade behaviour a bit unclear when there are multiple packages. For one package it makes sense: I click on the up arrow and get the option to upgrade. For more than one package: what am I upgrading? Everything? This package I clicked on? Its clear once you do it (everything), but again it seems more like a global notebook behaviour than something tied to a specific package. 

Also it seems like it would be better to have the option to upgrade each package separately, rather than all or nothing. 

So what about:
-  a global button for upgrade all packages
- a global link for "more info" on Pluto Pkg
- each package has an "upgrade this package only" button
- each package has a link to its github page

</div>

**Comment by fonsp** [comment]
Thanks! Let's continue this in the original discussion
