### ISSUE TITLE
Plots.jl figure not showing entire graph

### ISSUE THREAD

**Issue by sloede** [fonsp/Pluto.jl#2384]
When trying to plot a large range of values in Pluto using Plots.jl, sometimes parts of the graph are missing. This does not happen when executing the same commands directly in the REPL. When reducing the value range, the error disappears in Pluto as well.

To reproduce the issue: Running the following code in the REPL,
```julia
using Plots
plot([200000, 1], ylims=(0, 20))
```
produces a plot like this:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3637659/203522499-68767514-0847-4ca7-a392-757943c92f7c.png">

Executing the same commands in a Pluto notebook (MWE notebook: https://gist.github.com/sloede/0a59a44f749c70e2f2a4c3688052c8f0), produces a plot like this:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/3637659/203522736-c41c9703-f90a-45ea-8b4e-7be93f5c897e.png">

As you can see, the last part of the graph is missing (approximately between y=1 and y=11). This occurred on an Macbook Pro with an M1 processor and using Julia v1.8.2.

Interestingly, if I reduce the first value from `250000` to something below a certain (unknown) thresold, e.g., `200000`, the issue does not occur anymore:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/3637659/203524165-cc7ac43c-a918-46cf-84d4-66e86c25ade9.png">

**Comment by fonsp** [comment]
I can't reproduce this issue when I run your notebook, but this is probably due to sizing/scaling/browser rendering. We don't have code in the Pluto codebase that alters your plots.

**Comment by sloede** [comment]
OK, thanks for the clarification.
