### ISSUE TITLE
Backspace during unicode complete gives error

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2388]
https://user-images.githubusercontent.com/6933510/203637578-45d18a02-43d4-4c0c-9c8c-7913dcd2027c.mov

**Comment by fonsp** [comment]
If you attach a breakpoint to `on_update_doc_query(docs_string)` in `update_docs_from_autocomplete_selection` then you see that it fires lots of false events:

https://user-images.githubusercontent.com/6933510/207325853-e11dae00-5b8c-4d8a-bf93-38596439ce0b.mov

I didn't see https://github.com/fonsp/Pluto.jl/commit/617238c60bdee9937f3b047423c6e5d51674ac5e before debugging this (can you make PRs and put separate fixes into separate PRs please).

**Comment by Pangoraw** [comment]
Fixed in #2526.
