### ISSUE TITLE
How to close autosave? 

### ISSUE THREAD

**Issue by zxm403089989** [fonsp/Pluto.jl#2396]
Just as the topic, I prefer to work with Pluto without autosave. Is there any command to turn this off?

**Comment by fonsp** [comment]
Hey @zxm403089989 ! This is not possible. Maybe you would like to say a bit more about why you want to turn it off?

**Comment by pankgeorg** [comment]
As a shot in the dark, if you want to avoid reading/writing to the disk or just want volatile storage, you can use a small ramdisk https://linuxhint.com/create-ramdisk-linux/. 

`sudo mkdir /mnt/tmpfs`
`mount -t tmpfs -o size=1g tmpfs /mnt/tmpfs`
 
Pluto's read/writes will now only happen on RAM so disk will not be stressed at all, if that is what concerns you.
