### ISSUE TITLE
Reactive response to removing `using Module`

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#24]
If a Module `export`s some variables, those will be brought into the workspace when a `using Module` call is somewhere, and they will disappear when the `using` call is gone. 

However, removing a `using Module` does not reactively reevaluate cells that depend on its exported variables. Those cells need manual reevalutaion.

Requires Pluto to know exports.

**Comment by fonsp** [comment]
Julia has a function `names` to find the exports of a module.

**Comment by fonsp** [comment]
Static analysis can't infer the exports from the _name_ of the module - it needs to be done _after_ evaluating the `using` expression

**Comment by fonsp** [comment]
#115

**Comment by fonsp** [comment]
@Pangoraw can the new macro behaviour help here?

**Comment by Pangoraw** [comment]
Treating `using Package` as `import Package: exported1, exported2, ...` works with a macro :smiley: We can leverage the new batched updates to run `names(new_module)` and add it to the definitions after executing a cell containing `using`s ?

![macro_using](https://user-images.githubusercontent.com/9824244/124498159-3227ee80-ddbc-11eb-88a7-6b4be3090446.gif)

**Comment by fonsp** [comment]
Cool! One extra point is this:

```julia
julia> using PlutoUI

julia> Slider(x) = x
Slider (generic function with 1 method)

julia> length(methods(Slider))
1
```

```julia
julia> import PlutoUI: Slider

julia> Slider(x) = x
Slider

julia> length(methods(Slider))
4
```

Similarly, `import Example: x` and `x = 123` should be a _multiple definitions error_, `using Example`, `x = 123` should not.
