### ISSUE TITLE
Semi-predictable web socket location -> vulnerability

### ISSUE THREAD

**Issue by owainkenwayucl** [fonsp/Pluto.jl#242]
First of all this project is very cool and clears up a lot of the usability issues with Jupyter.

I did a quick pass though the code though looking for a common issue with "notebook-style" systems whch is that they have web-sockets with predictable locations.  This means that they are vulnerable to web sites the user is concurrenctly browsing connecting to the socket because websockets don't obey same origin policy. 

I believe on a cursory inspection that this is true for Pluto.jl (although not as bad as some as the attacker has to guess the document path):

https://github.com/fonsp/Pluto.jl/blob/9c74022f1a7e16617e1774154ffac42b7ed05d6f/frontend/common/PlutoConnection.js#L131-L133

Luckily, this is trivially resolved by randomisng the websocket path to a suitable degree of entropy.

**Comment by fonsp** [comment]
Thanks so much! This is open source at its best :)

Just so I understand correctly - the websocket address should be randomized per server session, and it should be served through an HTTP endpoint? Like `GET /canihavethewsaddressplease`.

**Comment by fonsp** [comment]
Thanks! It's fixed in `v0.11.2`:
https://github.com/fonsp/Pluto.jl/commit/efca4ee4b18c337f9e4160f82d11b204b7d73cdc#diff-c4f4ca51db1a0b464ff1990702c866f1R133

**Comment by owainkenwayucl** [comment]
Thanks!
