### ISSUE TITLE
"Expand logs" button

### ISSUE THREAD

**Issue by jagot** [fonsp/Pluto.jl#2435]
I find it would be helpful if there was a button that would allow me to expand the logs of all cells (i.e. notebook-wide).

Specifically, a button that lets me toggle the `max-height` parameter on or off:

https://github.com/fonsp/Pluto.jl/blob/5f57f266765fc49a591c053b3001537a3a57ff16/frontend/editor.css#L2664-L2673

My use case is that I'm debugging an algorithm with many steps, which prints logging information at every step, and it would be easier for me if I did not have to move the mouse pointer to the log container HTML element, before scrolling.

EDIT: If this could be configurable by setting a variable in a cell in the notebook, instead of a toggle button, that would make me equally happy.

**Comment by fonsp** [comment]
You could put this in a cell to enable it for that notebook:

```julia
html"""
<style>
 pluto-logs-container {
max-hieght: unset;
}
</style>
"""
```

Can you also post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?

**Comment by jagot** [comment]
Thanks for the code snippet, this is probably the best approach for me.

> Can you also post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?
I tried, but since I wanted to write more than one sentence and also point to a specific section of the code, the feedback box being only one line felt too cramped.
