### ISSUE TITLE
Firefox PDF export squishes markdown cell output to a narrow width

### ISSUE THREAD

**Issue by joeyshi12** [fonsp/Pluto.jl#2440]
When exporting my notebook to PDF,

*I expected the PDF export to look similar to the markdown output, but instead I am seeing that the markdown cell output has been squished to an unreadable width*.

I noticed that in this particular notebook, removing some text from a markdown cell fixes this issue for the markdown cell that's right below.

[!(notebook from video demo)](https://gist.github.com/joeyshi12/2e440201e54ba35edd19f2599cd094d9)

https://user-images.githubusercontent.com/46363213/212043495-bc35bd05-9a3f-4f87-94a5-1cbe28294485.mov

**Comment by Ricardo-Luis** [comment]
This it also have happened to me, but if you narrow a little the page margins (play with the scale on proprieties of PDF) it solves the issue. I'm not sure if this is a problem of Pluto, because it seems using the print tool of the browser.

**Comment by fonsp** [comment]
This is only a problem on Firefox, you can use Chrome to generate the PDF in the meantime, or https://github.com/JuliaPluto/PlutoPDF.jl

**Comment by fonsp** [comment]
Some debugging with browserstack.com: this is an issue with recent Firefox versions, on MacOS, not on Windows.

You can test this by pressing Cmd+P on https://featured.plutojl.org/basic/tower%20of%20hanoi, and then scrolling to the bottom of the PDF preview.

**Comment by fonsp** [comment]
I reported this bug at Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1811548

**Comment by fonsp** [comment]
Because there are no devtools available to debug printing layout, I don't think there is anything else we can do.

**Comment by fonsp** [comment]
@lukavdplas reported the same bug on Windows
