### ISSUE TITLE
word function (of CombinedParsers) becomes nothing after rerun "import CombinedParsers: word, words" cell

### ISSUE THREAD

**Issue by ysaereve** [fonsp/Pluto.jl#2443]
word function (of CombinedParsers) becomes nothing after rerun `using CombinedParsers` cell.

Note: In order to support Julia 1.8, CombinedParsers v0.2.2 is from GitHub repository [gkappler/CombinedParsers.jl](https://github.com/gkappler/CombinedParsers.jl)

As demonstrated in the following video. When loaded initially, the program works properly. i.e. `typeof(word)` 
is `NamedParser{Transformation{MatchedSubSequence, Repeat{ValueIn{Char, Tuple{Char, UnicodeClass{Tuple{UnitRange{Int64}, UnitRange{Int64}}}}}, Int64, Vector{Char}}, Int64, SubString{String}}, Int64, SubString{String}}`. However, if I rerun cell `import CombinedParsers: word, words`, then `typeof(word)` becomes `nothing`.

Same problem will occur for `typeof(CombinedParsers.word)`, if I rerun cell `using CombinedParsers` cell. Which I didn't include it in  Pluto notebook file. 

Version of components:
Julia: 1.8.5
CombinedParsers: 0.2.2
Pluto: 0.19.19
PlutoUI: 0.7.49

1. 📹 A video recording demonstrating the problem. 

https://user-images.githubusercontent.com/70087727/212533015-813043e2-d795-4a49-8a6a-4f2e2fe12c49.mov

2. 📝 A short Pluto notebook file. 
[TDCombinedParsers.jl - Pluto notebook](https://gist.github.com/ysaereve/6a29b14e92e2239cd2404a0b6e7ab37c)

**Comment by Pangoraw** [comment]
Thanks for the detailed report!
