### ISSUE TITLE
Suppress more interactive elements in PDF/print export

### ISSUE THREAD

**Issue by mgkuhn** [fonsp/Pluto.jl#2448]
![Screenshot_2023-01-18_16-54-51](https://user-images.githubusercontent.com/4479402/213245386-652cc959-19de-4e24-9aab-5e7a5c35d82f.png)
As of Pluto v0.19.19 there are still a couple of interactive notebook elements visible in exported PDFs, or when the notebook is printed in a browser, that perhaps ought to be suppressed because they serve no purpose in a printout or PDF:
1. there is a tick after each package name following a `using` keyword
2. there is a dot at the start of each line in each cell (for line counting?)
3. functions defined elsewhere in the notebook are underlined (although they are not clickable links in the PDF)

Could those perhaps be removed in the print version (presumably via adjusting CSS media styles)? That would help to declutter printouts of notebooks a bit.

**Comment by fonsp** [comment]
2. Fixed in https://github.com/fonsp/Pluto.jl/commit/33cb224892eb5cbc0b7caeb35bf3de276a320930

**Comment by fonsp** [comment]
1. Fixed in https://github.com/fonsp/Pluto.jl/commit/9add36611d46ec21fea867c5323718a240a00ed9
