### ISSUE TITLE
Cursor jumps to variable definition almost every time

### ISSUE THREAD

**Issue by abraemer** [fonsp/Pluto.jl#2458]
When clicking somewhere in the code to reposition the cursor, the cursor jumps somewhere else almost every time. As you can see in the video, I am clicking around in the body of the function but the cursor ends up in the first line most of the time. It seems that it goes to the place where the symbol that happened to be clicked is defined. I know that one can jump to the definition of a globally defined symbol by holding the "Control" key, but  I'm not pressing any key in this circumstance. Am I missing something? A "jump to definition" is definitely a nice feature imo, but should not be triggered just by clicking somewhere.

I am using the current Pluto version (v0.19.20). Unfortunately, I can't tell whether this is new, because I did not use Pluto in some time (not because Pluto isn't awesome - I just didn't have something to code :smile: ).

[Jumping cursor](https://user-images.githubusercontent.com/11058200/214317813-97f0bdca-10b7-4399-900d-3fa6f1a54938.webm)

For completeness, [the notebook](https://gist.github.com/abraemer/c315ce231f4e4501eda84468fcf743ad) used in the video.

On a probably unrelated note: I noticed that the cursor position is lost, when Alt+Tabbing, which is somewhat annoying.

Edit: I am on Ubuntu 22.04 and use Firefox 108.0.2 (64-bit).

**Comment by abraemer** [comment]
I just realized that you couldn't see my cursor, so I made new clip. You still can't see the mouse cursor itself but whenever I click there is  a visual indicator.

[New Video](https://user-images.githubusercontent.com/11058200/214323449-4cc4fc26-f7d2-41f4-8592-c8e665e57be6.webm)

**Comment by pankgeorg** [comment]
Can you check the On-Screen Keyboard, if in Windows, to make sure that the Ctrl key isn't stuck? I had the same issue and I realized that a Bluetooth keyboard in my drawer was activated, connected and spammed the Ctrl key.

**Comment by abraemer** [comment]
Not sure how I would check that on my Ubuntu tbh. I tried googling some stuff but nothing was quite conclusive I feel. However, I think we can exclude a stuck control key, because if control was pressed, clicking on e.g. `factorial` in the lower cell should always bring me to the definition and that doesn't happen. Only when I press control, it takes my to its definition.

**Comment by abraemer** [comment]
I just updated to the new version (0.19.21) and could not reproduce this bug anymore!
