### ISSUE TITLE
Formatting DataFrame output nicely

### ISSUE THREAD

**Issue by mthelm85** [fonsp/Pluto.jl#246]
It would be nice to format the output of a DataFrame as they do in Nextjournal notebooks. I do know JavaScript but I'm a bit rusty as I haven't coded anything in JavaScript for over a year. I've built numerous applications with Vue.js so I'm more than willing to help out where I can (probably with some of the things that don't require learning React). What needs to happen to be able to get the DataFrame output to be formatted nicely? I tried loading TableView.jl and calling `showtable(df)` but it didn't work.

**Comment by fonsp** [comment]
Hey! It just needs some nice looking CSS rules for the HTML table elements, you can give it a go without needing to write javascript! Cell output rules are defined here: 

https://github.com/fonsp/Pluto.jl/blob/v0.11.2/frontend/editor.css#L55-L174

**Comment by fonsp** [comment]
#235

**Comment by fonsp** [comment]
For others: discussion moved here #247
