### ISSUE TITLE
MsgPack: buffer write to network io

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2460]
In https://github.com/JuliaPluto/Malt.jl/pull/32, we discovered that making many invidividual `write` calls can be a bottleneck in TCP network performance, and it can be much faster to write to a memory buffer, and write that buffer to the network.

In Pluto, the same situation might be occurring here:

https://github.com/fonsp/Pluto.jl/blob/469b82b36877b03969020efd946bac16b3400557/src/webserver/PutUpdates.jl#L15

because MsgPack makes lots of individual `write` calls.

Next step: find a way to benchmark (maybe a ping pong with JS?) and see if we can improve performance. Does HTTP already enable buffered writing?

**Comment by Pangoraw** [comment]
FYI, the WebSocket IO is not exposed with HTTP.jl API so the serialization writes to an IOBuffer:
https://github.com/fonsp/Pluto.jl/blob/469b82b36877b03969020efd946bac16b3400557/src/webserver/PutUpdates.jl#L70-L72

https://github.com/fonsp/Pluto.jl/blob/469b82b36877b03969020efd946bac16b3400557/src/webserver/PutUpdates.jl#L18-L22

**Comment by fonsp** [comment]
Ah right, this API was removed in HTTP 1.0, right? Thanks for noticing!
