### ISSUE TITLE
Allow spaces immediately after the $$ for math equations in a markdown cell

### ISSUE THREAD

**Issue by liuyxpp** [fonsp/Pluto.jl#248]
Current version (0.11.2) seems not supporting the following
md"
$$ y = x^2 $$"

Note the spaces after the first $$ and before the second $$.

**Comment by fonsp** [comment]
Hey! Markdown parsing is part of Julia itself, it's not part of the Pluto project.

Unfortunately the Markdown parser has some confusing quirks - this is one of them.
