### ISSUE TITLE
Hash URL does not work on initial load

### ISSUE THREAD

**Issue by mmikhasenko** [fonsp/Pluto.jl#2480]
I want to reference a section of the html pluto notebook.
I identify right id, and add it to the url with the hash, it works if page is not reloaded.

When I load the page directly with the [hash in url](https://mmikhasenko.github.io/ReactionAmplitudeExamples.jl/LcLcK_momentumdistribution.html#03bf0964-e32a-48d5-8f16-43bb0892762a), the scrolling does not work.

Then, I can put a **wrong** hash, press Enter, - nothing happens, then again the **right** hash, the scrolling works.

![issue](https://user-images.githubusercontent.com/22725744/219504857-38c6b59e-1189-4eed-a2d8-fee41d27d892.gif)

**Comment by fonsp** [comment]
This is because we load content dynamically using JS, after connecting the websocket and getting the initial state. Might be worth to find a workaround!

**Comment by mmikhasenko** [comment]
@pankgeorg suggested on slack to use html tags, I have not tested yet if it works

> I would suggest the 
> ```
> html”<h1 id=‘heading-for-calculus’>Calculus</h1>”
> ```
> Pluto does have some auto generated ids but they > aren’t guaranteed to be stable so if you want to send bookmarks, include these in your code

**Comment by fonsp** [comment]
This probably won't work because of the same reason: https://github.com/fonsp/Pluto.jl/issues/2480#issuecomment-1450843699

**Comment by fonsp** [comment]
This one might have been fixed! let me cone back to this

**Comment by fonsp** [comment]
Fixed by #2789
