### ISSUE TITLE
Pluto is much slower than plain julia

### ISSUE THREAD

**Issue by amol447** [fonsp/Pluto.jl#2490]
I have a function that loads a few feather files into dataframes using Arrow.jl/DataFrames. I use benchmarktools to measure performance and in plain REPL I see 
@btime some_function(path)
164.470 ms (1420769 allocations: 113.27 MiB)
In Pluto
100.336 s (122600103 allocations: 5.93 GiB)
What could possibly be causing that much allocations in pluto? The files are fairly small.

**Comment by pankgeorg** [comment]
Hello @amol447! Thank you for making this report!

Can you give us a sample feather file (probably with random data) and a notebook that reproduces this issue? We'd love to address it!

**Comment by amol447** [comment]
[pluto_test.zip](https://github.com/fonsp/Pluto.jl/files/10912992/pluto_test.zip)
Attaching a zip with the notebook and feather file. The culprit is actually DataFrame Transform.
In plain julia 
896.755 μs (12122 allocations: 500.77 KiB)
In pluto
629.926 ms (934256 allocations: 45.82 MiB)

**Comment by Pangoraw** [comment]
Thanks for the reproducing notebook! I identified where Pluto was spending most of its time (formatting log messages). Could you try [#2493](https://github.com/fonsp/Pluto.jl/pull/2493#issuecomment-1460606518) and confirm that the difference between Pluto and plain Julia is reduced? There are still possible improvements left but #2493 should reduce the difference quite a lot.

**Comment by amol447** [comment]
Yes this is  better.
Now I see this in Pluto.
4.124 ms (32121 allocations: 2.98 MiB)
