### ISSUE TITLE
Move function reactivity from definition to call

### ISSUE THREAD

**Issue by malyvsen** [fonsp/Pluto.jl#25]
Currently, function definitions are considered dependent on the variables and functions that are referenced in them, and function calls are considered dependent on definitions.
This breaks when `a()` calls `b()`, and `b()` calls `a()` - even though this double recursion is not paradigmatically illegal.

We should instead consider function _calls_ dependent on the variables and functions referenced in the function definition. This will also solve the problem of reactivity in response to modifying global variables within functions.

**Comment by fonsp** [comment]
This is now [a testset 🐶](https://github.com/fonsp/Pluto.jl/blob/a3a0700a12a8e38bee24426d420aa1f35b9d2708/test/React.jl#L129-L145)

**Comment by fonsp** [comment]
(This is reverted again, we have a separate fix for the two-function recursion)
