### ISSUE TITLE
Visual issue: evaluation status with many cells

### ISSUE THREAD

**Issue by tecosaur** [fonsp/Pluto.jl#2503]
This is a rather small thing, but I've noticed that the running code display starts looking a bit dodgy when there are many cells being run:

![image](https://user-images.githubusercontent.com/20903656/224598990-c380562e-aa04-49c2-afe1-524549323664.png)

I imagine the precise point where this starts looking dodgy varies based on display scaling and monitor resolution, but it may be worth having an alternative style for say >50 cells, e.g. just removing the gap

![image](https://user-images.githubusercontent.com/20903656/224599297-4a83852b-6000-4313-ab04-fbc41d9f20c8.png)

**Comment by fonsp** [comment]
thanks!
