### ISSUE TITLE
Reset cell action

### ISSUE THREAD

**Issue by adsick** [fonsp/Pluto.jl#2506]
Sometimes it is useful to go back to the initial state of the cell. I propose adding a "reset cell" action in the "..." dropdown menu for doing it more quickly than tapping Ctrl+Z multiple times (also it makes it more accessible when using touch/mouse)

**Comment by fonsp** [comment]
Hey @adsick ! What do you mean with the initial state of a cell?

**Comment by adsick** [comment]
I mean the state in which the cell was where you open some notebook.

**Comment by fonsp** [comment]
Thanks! Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?
