### ISSUE TITLE
Internal error when wrapping ccall in a function

### ISSUE THREAD

**Issue by Alseidon** [fonsp/Pluto.jl#2511]
I was playing with calls to custom C functions, and got in an issue when trying to pass the C function's symbol to a Julia function, that only happens in Pluto. Here is an example notebook : https://gist.github.com/Alseidon/8ea03a87464fea4ef9d8272b35be2b91

After generating and compiling a C file, I open the `.so` file, get the function symbol, do the ccall and close the file (so I can open it again, in order to include possible modifications).

Now, if the ccall is in a function, and I pass the function symbol as an argument (second part of the notebook), I get this error (the full message is too long to copy it there):
```julia
Internal error: encountered unexpected error during compilation of ##function_wrapped_cell#421:
TypeError(func=:ccall, context="", expected=Ptr{T} where T, got=nothing)
```

When running the notebook without Pluto (with `julia notebook.jl`), I get no error and everything goes fine (ie., the terminal outputs `1\n 2\n 1\n`).

**Comment by Pangoraw** [comment]
Thanks for the report and reproducer! This seems to be an issue with Julia itself (I have opened https://github.com/JuliaLang/julia/issues/49141).
