### ISSUE TITLE
Nothing appears on the screen in the notebook or its html export

### ISSUE THREAD

**Issue by holomorphism** [fonsp/Pluto.jl#2513]
I am experiencing the following problem in my environment since today (2023-03-25).
Is there anyone else in a similar situation?

1. The history list ("My work") does not load on the Pluto top page.
2. When I click on "Create a new notebook" on the Pluto top page, only a white screen appears.
3. When I open an html file exported by Pluto, the contents are not displayed at all (only a white screen is displayed).

The environment in which the problem occurred:
* Ubuntu Linux 22.04
* Chrome 111.0.5563.64  and  Firefox 111.0.1
* julia 1.8.0
* Pluto v0.19.22 (f3d8946d)

When I checked the chrome console under conditions (1), (2), and (3), the following error occurred in all cases.
(The image shows the case of opening a local html file, but the conditions looked the same when opening Pluto's top screen or a file uploaded to the Internet.)
![1](https://user-images.githubusercontent.com/3076585/227693280-b57a066b-e31e-4748-84bd-48c1caf244a7.png)
![2](https://user-images.githubusercontent.com/3076585/227693343-4efc387b-f04e-4402-b667-fb0d0489abaa.png)
![3](https://user-images.githubusercontent.com/3076585/227693358-9d9cba87-6828-40a9-a52b-75751e530a21.png)

I have not been able to fully grasp the conditions under which this phenomenon occurs, but for now I will report on what is currently known.

* This problem did not occur yesterday (around 2023-03-24 03:00 (GMT)).
  It started today (2023-03-25 03:00 (GMT)).
* The problem occurs in the latest Pluto commit (f3d8946d).
  In addition to problems (1) and (2), files exported with this version of Pluto have problem (3).
* After reverting to Pluto v0.19.22 (`] activate --temp`, `] add Pluto`), problems (1) and (2) no longer occur.
  Also, the problem (3) did not (seemingly) occur for files exported with this version of Pluto.
* Problem (3) also occurs in html files exported in the past. I checked several files and found the following tendency.
  (There may be some exceptions. Also, I believe I was using approximately the latest version of Pluto at the time)
  * html files created between 2022-10-01 and 2023-02-01 had this problem.
  * html files created between 2021-10-01 and 2022-02-01 did not have this problem.

I updated Pluto to the latest commit yesterday and used it without any problems and only today noticed the above problem.
So I thought it was not a problem with the Pluto update, but with the program loaded from the CDN.
However, it is strange that the situation has changed since then when I downgraded the Pluto version.
(I have been using Pluto with the `dev` command (`] dev Pluto`), is there something wrong here too?)

I also tried to find notebooks published on the Internet that are experiencing the same phenomenon, but have yet to find any.
The following notebooks did not seem to be affected.
https://computationalthinking.mit.edu/Fall22/

Thanks.

**Comment by pankgeorg** [comment]
Hey! I can confirm this issue, it's probably related to ESM.sh cd release of version 113 which happended yesterday (even though it shouldn't as it's tagged to v66).

I opened an issue with them:
https://github.com/esm-dev/esm.sh/issues/567

**Comment by holomorphism** [comment]
@pankgeorg Thank you very much! I have tried looking at the latest commit (f3d8946d) and opening html files exported in the past, and all problems seem to be gone. Thanks also to the developers of ESM.sh.
