### ISSUE TITLE
"Another cell defining `x` contains error" points to wrong variable

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2524]
```
# ╔═╡ d9c2c1e8-3b8d-46c2-877b-306a80c4b1c4
x = no_such_thing

# ╔═╡ 381e529e-452e-4a78-95e7-612a6300b214
begin
	x
	y = 1
end

# ╔═╡ 1004d176-42be-4b45-b1bf-3866e241ac4b
y
```

![image](https://user-images.githubusercontent.com/4170948/230781339-0510d00d-eef3-4201-a67a-5a31a54b52a9.png)

The last error message should refer to `y`, not `x`, which is not mentioned in that cell.

**Comment by fonsp** [comment]
That's on purpose! It points to the root cause that led to the chain of errors.
