### ISSUE TITLE
Codemirror: simultaneous calls to EditorView.update during blur

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2548]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/6933510/234913996-aa8d6a74-1c42-4c7f-909f-1a05c889ae50.png">

Probably since #2540

Maybe we can fix #2518 at the same time, it seems related

**Comment by Pangoraw** [comment]
This is fixed in https://github.com/fonsp/Pluto.jl/commit/9c052d39d47055444bc03a48abadc9134a27e951 too?

I updated codemirror in #2526 to get the diagnostics, but did not get this issue again.

**Comment by fonsp** [comment]
Yeah I got it again while adding a cell:

<img width="697" alt="image" src="https://github.com/fonsp/Pluto.jl/assets/6933510/a1f7e269-b20b-45a4-a3bb-d774039969e8">

**Comment by fonsp** [comment]
But the stacktrace looks helpful! Something related to the `blur` stuff

**Comment by Pangoraw** [comment]
It's this dispatch which gets run during a CM update:

https://github.com/fonsp/Pluto.jl/blob/06589c782994d8233e29c01742ac69c361c0d0aa/frontend/components/CellInput.js#L645-L652

we can maybe do something like this to run the update in the next tick:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/3fb68dbab1ef52d1c3a65991755c2f24bf297bf7/packages/jupyterlab-lsp/src/features/highlights.ts#L155-L160

**Comment by fonsp** [comment]
that worked yay
