### ISSUE TITLE
Wrap long (in width) Pluto errors

### ISSUE THREAD

**Issue by filchristou** [fonsp/Pluto.jl#2549]
Sometimes errors in Pluto are long and in order to see them you need to use the cursor, which can be quite disturbing in some cases.
It would be nice to wrap the text w.r.t the maximum cell width (like it also happens by default in many terminals)

video:

https://user-images.githubusercontent.com/27723218/234967048-af368dfd-afe5-425d-a9fc-3f901af8aa35.mp4

gist:

https://gist.github.com/filchristou/b876d9445f3641d7b6261252a9993a6f

discourse post:
https://discourse.julialang.org/t/wrap-long-in-width-pluto-errors/97716

**Comment by fonsp** [comment]
Thanks!

This behaviour is on purpose: if the error is a MethodError, we disable line wrapping to make it easier to read and compare the list of candidates.

https://github.com/fonsp/Pluto.jl/blob/90cf1be8887f85adc169887bee9242d0ba41ef4d/frontend/components/ErrorMessage.js#L93-L96
