### ISSUE TITLE
Memory leak when using `push!`

### ISSUE THREAD

**Issue by Alseidon** [fonsp/Pluto.jl#2556]
When I run this snippet of code in a clean Julia notebook multiple times (with Shift+Enter), the memory taken by the Julia process increases each time until it crashes:
```julia
begin
	arr = zeros(10)
	for i in 1:1e8
		push!(arr, i)
	end
	length(arr)
end
```

You can see the result down there (I only ran it three times).
[cinnamon-2023-05-10T120042+0200.webm](https://github.com/fonsp/Pluto.jl/assets/58395551/edc7845d-5443-44a5-bada-168c119c50b7)

When I run the notebook outside of Pluto (with `valgrind julia notebook.jl`), I see no leak. I am not sure what is happening there, or if there is an issue with my code, I am sorry if this is the case.

Edit: forgot to add that I run Pluto 0.19.25 with Julia 1.9.0 (this was also happening with Julia 1.8.5) under Linux Mint 21.1

**Comment by Alseidon** [comment]
It has 8 GB of RAM.

Using `GC.gc()` did work, thanks! `--heap-size-hint=300M` works too, but is more inconsistent, as it lets the memory go to 30-40% sometimes, whereas a direct call to the GC never let memory use go above 20%.

My case is closed with this then, but is the underlying cause an issue or should I close this?

**Comment by pankgeorg** [comment]
Well, it's not an issue with Pluto per-se, but rather with how and when the GC gets invoked. I would say to keep the `--heap-size-hint=300M` instead of the `GC.gc()`, as it feels that it's okey to let the memory go up to 30%-40% (if it isn't, try to hint to 50MB first, before adding `GC.gc()` to your code)
