### ISSUE TITLE
Add "Presentation Mode"

### ISSUE THREAD

**Issue by mthelm85** [fonsp/Pluto.jl#256]
It would be nice to have the ability to hide the `<header>`  and `<footer>` tags when presenting a notebook. It looks like simply setting `display: none;` for the `<header>`s and `<footer>`s takes care of the actual header/footer as well as the _Live Docs_ window. I really like the clean display so I certainly wouldn't want to suggest there should be a button or anything for this but maybe a keyword argument passed to `Pluto.run()` or maybe a standalone function that could be  called from within the notebook (i.e. `Pluto.presentation_mode()`)?

**Comment by fonsp** [comment]
I don't think this is necessary because they are at the start and end of the page - they are already invisible once you go to the first slide, right?

About the live docs - they disappear if you zoom in enough. Or do you think there is a use case for presentation mode without zooming in?

**Comment by mthelm85** [comment]
I didn't realize that live docs goes away when zooming and you are right about simply scrolling - there are certainly higher priority items in the list : )
