### ISSUE TITLE
variable name starting with `end` gets dedented incorrectly

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#257]
Type the following into a cell:
```
begin
    enda = 1
end
```
After typing `begin` it indents properly, but it dedents as soon as it sees `end`. Perhaps it should not until it sees `end `.

Thank you!

**Comment by fonsp** [comment]
Could you submit this to CodeMirror? https://github.com/codemirror/CodeMirror/issues/

**Comment by klaff** [comment]
See https://github.com/codemirror/CodeMirror/issues/6376.
