### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by SubhadityaMukherjee** [fonsp/Pluto.jl#258]
Okay so heads up, I am not sure if this is possible but just a thought.
I came across this package [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl) and it seems to support string as well as file formatting. 
Since Pluto works so well in terms of presentation, maybe code formatting could also be something really cool? Without actually breaking the minimalism because I feel this is the only code editor which isn’t bogged down by a million things. 
Just a thought.

I will test it out and see if it works without messing up Pluto files and let you know just in case.

**Comment by fonsp** [comment]
Do you mean formatting cells after you submit them, or formatting the whole and reopening the notebook?

I appreciate your worries about breaking the minimalism, but isn’t that what adding this feature will do?

**Comment by ilyagr** [comment]
I would like pressing "Ctrl+Alt+F" to run the contents of the cell I'm editing through `JuliaFormatter.format()`. Ideally (but optionally), if there's an error during formatting, it would also be displayed to me.

**Comment by fonsp** [comment]
The formatter can error?

**Comment by ilyagr** [comment]
Yes, for example on syntax errors.

```julia
julia> JuliaFormatter.format_text("2+2")
"2 + 2"

julia> JuliaFormatter.format_text("2+")
ERROR: Parsing error for input:

2+
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] format_text(::String, ::JuliaFormatter.DefaultStyle, ::JuliaFormatter.Options) at /home/ilyagr/.julia/packages/JuliaFormatter/7belo/src/JuliaFormatter.jl:269
 [3] #format_text#124 at /home/ilyagr/.julia/packages/JuliaFormatter/7belo/src/JuliaFormatter.jl:264 [inlined]
 [4] format_text(::String) at /home/ilyagr/.julia/packages/JuliaFormatter/7belo/src/JuliaFormatter.jl:248
 [5] top-level scope at REPL[188]:1
 [6] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

**Comment by fonsp** [comment]
That's fine, you can get the error with `try Meta.parse(str) catch err; sprint(showerror, err) end`

**Comment by max-sixty** [comment]
Re-upping this if that's OK! 

In Jupyter I use https://github.com/dnanhkhoa/nb_black — it's a really simple extension that formats the code after running the cell. It means I don't have to worry about formatting at all — just type away and it'll look good when it's run. Having code well-formatted makes it easier to see its structure, including loops.

I have the same thing when working in VSCode with Julia, but not with Julia in Pluto. Pluto takes care of so much mental overhead around state, but it adds back some of that with having to think about formatting.

IIUC there was a concern about whether the formatter can error above. I don't _think_ that should be a blocking concern — the formatter errors when the code is invalid Julia — so I would imagine Pluto could just ignore those errors, and we'd see the error picked up by the current Julia parser, just as it does now. Or am I missing something?

Thank you for the superb app!

**Comment by fonsp** [comment]
Experiments in #1531

**Comment by taooceros** [comment]
any news
