### ISSUE TITLE
Pluto shows welcome message on precompilation

### ISSUE THREAD

**Issue by bvdmitri** [fonsp/Pluto.jl#2589]
Pluto shows the welcome message on pre-compilation, which should not be displayed until a user runs `import Pluto` 

<img width="1167" alt="Screenshot 2023-06-27 at 10 46 39" src="https://github.com/fonsp/Pluto.jl/assets/6557701/9cc11a25-c9f7-46a2-8bef-ae1e699a9823">

**Comment by ctrekker** [comment]
This will be fixed by #2628
