### ISSUE TITLE
Cells error before giving the correct result with @bind

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#262]
Thanks for developing such a great tool!

I encounter quite often that when waiting for a cell to run, the following cells errors

![image](https://user-images.githubusercontent.com/6257240/89641854-a2628300-d880-11ea-825d-52f68e602068.png)

Although the result is correct, the error message looks terrible. It is because I shouldn't use `x, y = ...` like expression?

**Comment by fonsp** [comment]
Hey! I am a little confused - which cell did you run, which cell(s) have an unexpected error, and why is it unexpected?

It looks like the first cell errored for a valid reason, causing the 2nd and 3rd cell to error because `state` and `history` are no longer defined. Is that what happened?

**Comment by fonsp** [comment]
Maybe you could record a GIF or a sequence of screenshots? And could you show the entire error message?

**Comment by GiggleLiu** [comment]
I updated a cell above the cells shown in the image. The top one in the image will first error, and then be updated correctly after several seconds. I can try harder to get some useful information.

BTW: Is it possible that cells are not executed from top to bottom?

**Comment by fonsp** [comment]
ah right, are you using `@bind`?

**Comment by GiggleLiu** [comment]
Yes

**Comment by fonsp** [comment]
Yes! Cells execute based on their dependency order, not based on how they are placed in the notebook.

**Comment by fonsp** [comment]
If you are `@bind`ing to something simple like a slider or textbox, you can use `PlutoUI.jl` instead of writing the HTML yourself. PlutoUI contains some special code to prevent the error flash

**Comment by GiggleLiu** [comment]
Thanks for your suggestions, they are very helpful.
I changed the order of some blocks. I will fixed the order first and see if it still errors.

**Comment by fonsp** [comment]
Alright, let me know!

**Comment by GiggleLiu** [comment]
Thanks for you suggestion @fonsp , there is not error anymore with PlutoUI.

But there is still an issue. The last cell is refreshed multiple times when I connect a new tab to the server. This is not desired because the last cell is expensive to evaluate in my application.
I checked that the order is correct in the source file.

Should I open a new issue for it?

**Comment by GiggleLiu** [comment]
![optimizer_selector](https://user-images.githubusercontent.com/6257240/89701683-337c3d00-d907-11ea-8378-b8286a570e5e.gif)
