### ISSUE TITLE
Make Pluto boilerplate formatted according to JuliaFormatter

### ISSUE THREAD

**Issue by Joel-Dahne** [fonsp/Pluto.jl#2623]
This is a very minor thing which has annoyed me for some time. It would be nice if the boilerplate added by Pluto was formatted in such a way that running JuliaFormatter on the notebook file didn't reformat anything. 

The only issue at the moment is [this line](https://github.com/fonsp/Pluto.jl/blob/1d2c3038032108fff3a9c565eaa84609f1e75b4e/src/runner/PlutoRunner.jl#L2116C1-L2123C7), i.e
```julia
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end
```
which gets formatted to
```julia
macro bind(def, element)
    quote
        local iv = try
            Base.loaded_modules[Base.PkgId(
                Base.UUID("6e696c72-6542-2067-7265-42206c756150"),
                "AbstractPlutoDingetjes",
            )].Bonds.initial_value
        catch
            b -> missing
        end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end
```

To reproduce you can create a new notebook and add
```julia
begin 
	using PlutoUI
	@bind x Slider(1:10)
end
```
Save the notebook and format it with `JuliaFormatter.format()`. It should return false, meaning that the file was not already correctly formatted. Opening the notebook again, closing it and then formatting it again gives false. 

The reason this is annoying for me is that if you format a Pluto notebook with JuliaFormatter and then open it with Pluto the above code gets "unformatted" again. It of course doesn't affect the result of the code but if the notebook is committed to a git repository you get a modified file.

**Comment by Pocket-titan** [comment]
But not everyone might use JuliaFormatter, or even with the same settings as you, so it might be better to try solving this at a lower level first. It sounds like your problem is with `git` specifically, so you could try adding a `pre-commit` hook that will automatically format all your code before committing? You could put a file in the `.git/hooks` directory named `pre-commit` (don't forget to `chmod +x` it to make it executable) containting:

```
#!/bin/sh
julia -e "using JuliaFormatter; format(\"src\")"
```

where `src` is the directory containing your code, for example.

**Comment by Joel-Dahne** [comment]
Thank you for your comment! I agree that many people probably don't use JuliaFormatter, or use it with different settings. I also agree that there are certainly other ways for me to handle this, indeed just doing it more or less manually as I have done now isn't a big issue. 

I just thought that this would be (slightly) helpful for me and could maaaybe be slightly helpful for some other people as well. For people not using a formatter the change wouldn't make any difference. People using a formatter with different settings probably already have similar issues, this specific change would in that case not solve their issues but would most likely not make them worse either (unless their formatter happens to leave that line unchanged, but I see that as unlikely given that most formatters have some length limit for lines). So I don't really think there are any drawbacks to making it.

It certainly is a silly small change and I would fully understand if people have other things they want to do instead!
