### ISSUE TITLE
Completion in function arguments doesn't work in julia 1.9

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2629]
When running in Julia 1.9, tab completion doesn't seem to work when triggered inside a function call of a defined function.
It works with Julia 1.7.

![image](https://github.com/fonsp/Pluto.jl/assets/4170948/56774584-b543-4442-bffb-c5dcf44a7c22)

```
### A Pluto.jl notebook ###
# v0.19.27

using Markdown
using InteractiveUtils

# ╔═╡ 3c06b5d0-3aad-11ee-1839-371507715cbe
foo = 4

# ╔═╡ f541410d-7ec0-4b2a-aee4-f4592543e2b4
abc(x) = x

# ╔═╡ 9d58c4bf-0ec7-4895-8e2d-207391eaab98
abc(fo  # Tab does not complete here

# ╔═╡ d3654ab3-2d48-44ed-b533-f5fc31b85247
ab(fo   # Can be completed to `foo`

# ╔═╡ e0578f59-3aae-4e89-838a-5e79a594bf05
versioninfo()

# ╔═╡ Cell order:
# ╟─3c06b5d0-3aad-11ee-1839-371507715cbe
# ╠═f541410d-7ec0-4b2a-aee4-f4592543e2b4
# ╠═9d58c4bf-0ec7-4895-8e2d-207391eaab98
# ╠═d3654ab3-2d48-44ed-b533-f5fc31b85247
# ╠═e0578f59-3aae-4e89-838a-5e79a594bf05
```

**Comment by Pangoraw** [comment]
Thanks for the report, this should be fixed in https://github.com/JunoLab/FuzzyCompletions.jl/pull/15.

**Comment by Pangoraw** [comment]
This will be fixed in the next release of Pluto (or with `rm(Pluto.pluto_boot_environment_path[]; force=true, recursive=true)`), upstream pr has been merged
