### ISSUE TITLE
Where can I see the command history used in my Pluto session?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [fonsp/Pluto.jl#263]
Hello.
I just started using Pluto, and I am wondering where I can see the history of commands I used during a Pluto session. Of course, I can save a particular notebook. But it would be quite convenient if all these commands I used in my Pluto session are recorded somewhere, e.g., ~/.julia/logs/repl_history.jl
Currently, that standard command history file ended with
```
# time: 2020-08-06 12:12:28 PDT
# mode: julia
	Pluto.run(1234)
```
And after terminating my Pluto session, no commands I ran in my Pluto session/notebook were recorded in ~/.julia/logs/repl_history.jl

Thanks for your help!

**Comment by fonsp** [comment]
It's not stored anywhere else except the notebook file. Do you think it should be stored?

**Comment by BoundaryValueProblems** [comment]
I think it is a great idea to store the command history other than a notebook. One the other hand, I am not entirely clear in which file you want to save the command history. One obvious choice is to append all those commands to ~/.julia/logs/repl_history.jl after that `Pluto.run(1234)`. But maybe other people may suggest that saving such commands to an independent file, e.g., ~/.julia/logs/pluto_history.jl. Which do you think is better?

**Comment by fonsp** [comment]
But why should it be stored?

**Comment by BoundaryValueProblems** [comment]
Well, in my case, I needed to go back to what exact sequence of commands I ran in the past, in order to reconstruct certain experiments. For that purpose, I relied on the command history file ~/.julia/logs/repl_history.jl.
In the case of Pluto notebook, if one saves one's notebook, not only the currently listed commands, but are all the commands he/she ran on that notebook are saved? In other words, can one reconstruct the sequence of command that led to the current status of the notebook if one saves that notebook?

**Comment by Paethon** [comment]
In Pluto, the current state of the notebook only depends on the code that is currently in the cells of the notebook (there is no hidden state). That is one of the main advantages of Pluto in comparison to e.g. Jupyter.

If you have a command in a cell and you delete it, it is as if that command was never executed in the first place.

**Comment by sosiristseng** [comment]
Since Pluto is reactive (aka memoryless) by design, it's the job of version control tools (e.g. `git`) to save the history IMHO.

- If something goes bad, you could roll back to previous version(s).
- Trying different strategies on the same code base, just create branches.

Not sure if I answered your question.

**Comment by fonsp** [comment]
> are all the commands he/she ran on that notebook are saved? In other words, can one reconstruct the sequence of command that led to the current status of the notebook if one saves that notebook?

In most cases, reactivity assures that _there is only one order that cells can run in_ - when you re-open your notebook, **or when you change code**, cells will always run in the same order.
