### ISSUE TITLE
Progress bar not updating with direct use of `ProgressLogging.progress`

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2634]
This should display a progress bar and not show the log message directly, just like when using the `@progress` macro:
```
ProgressLogging.progress() do id
    for i = 1:10
        sleep(0.5)
        @info "iterating" progress=i/10 _id=id
    end
end
```
(this code is from the docs of `ProgressLogging.progress`)
Instead, it shows the `@info` messages, and only updates the progress bar to 100% at the end.

![image](https://github.com/fonsp/Pluto.jl/assets/4170948/198108e1-9a6d-4863-9d14-7108b5b14857)

**Comment by Pangoraw** [comment]
We currently only update the progress when id and log level are the same so for log level == LogLevel(-1). 

https://github.com/fonsp/Pluto.jl/blob/137420c7c8a7187a426503f2cf957c29086c9868/frontend/components/Logs.js#L40-L41
