### ISSUE TITLE
Broken link: sample/basic.jl not found

### ISSUE THREAD

**Issue by joaquimpuig** [fonsp/Pluto.jl#2635]
In the readme file, 

https://docs.juliahub.com/Pluto/OJqMt/0.10.5/

there is a link to a sample julia Pluto notebook with the following link

Your notebooks are saved as pure Julia files ([sample](https://github.com/fonsp/Pluto.jl/blob/master/sample/basic.jl)) but the file is missing.

**Comment by pankgeorg** [comment]
Please check the latest docs; https://docs.juliahub.com/General/Pluto/stable/

There is an issue with JuliaHub's SEO and Google and it's pointing to older docs. We're actively working on making the new ones get on the top of Google 😅

This is the notebook: https://github.com/fonsp/Pluto.jl/blob/main/sample/Basic.jl

(Closing as this is not Pluto related!)
