### ISSUE TITLE
Incorrect highlighting of `end` in `let f() = 1 end`

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#2639]
Using this code:

```julia
let f() = 1 end

let f() = 1
end
```

GitHub highlights it correctly, but Pluto shows:

![pluto_screenshot](https://github.com/fonsp/Pluto.jl/assets/8695383/2523499b-4c3c-4ebc-9dd1-e242d7f55dbc)

Presumably, `end` should be highlighted in orange as all keywords, but it's not. Same thing happens for more complicated code like `let f(x) = x^2 end`.

Moreover, indentation seems broken as well:

1. In the second cell, place the cursor after `1` in the first line.
2. Hit Enter.
3. The cursor will appear at the _very beginning_ of the next line, no indentation is inserted.

__Versions__: Pluto v0.19.27, Julia 1.10.0-beta2.

**Comment by fonsp** [comment]
Will be reopened by #2980
