### ISSUE TITLE
Displaying preformatted text

### ISSUE THREAD

**Issue by non-Jedi** [fonsp/Pluto.jl#264]
If a value x returned by a cell is `showable("text/markdown", x)`, it's displayed as formatted text, but `showable("text/plain", x)` simply prints the julia literal that could be used for creating it. This means there's no simple way of outputting preformatted text <https://discourse.julialang.org/t/how-can-i-display-single-spaced-multi-line-text-in-pluto/44483/3>.

I feel like ideally `show(io, "text/plain", ::AbstractString)` would give the same result as `print(io, ::AbstractString)` which would take care of this problem for you, but that's not the world we live in.

**Comment by fonsp** [comment]
Hey! Julia has a hidden function built in to `Base`:

```
Text(str)
```
is a wrapper around `str` that is `showable` as `text/plain`.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/89704989-91397500-d959-11ea-9291-d9181770c385.png)

```julia
### A Pluto.jl notebook ###
# v0.11.4

using Markdown
using InteractiveUtils

# ╔═╡ 45a0f8b8-d948-11ea-0691-0b4b411a2674
md"`sprint` works by giving an `IOBuffer` as the first argument of the function that you gave. This only works if the function takes an `IO` as its first argument. 

The `Pkg` functions take `IO` as an optional keyword argument, so we have to do another trick:"

# ╔═╡ 8240a3aa-d947-11ea-083b-858ef1451c4e
Text(sprint(versioninfo))

# ╔═╡ 3409c97e-d948-11ea-3536-5999e4418ec9
Text(sprint(dump, [1,2,[3]]))

# ╔═╡ 81be742e-d948-11ea-2c29-b93dcb78b33f
import Pkg

# ╔═╡ 703a3256-d948-11ea-08de-0bbd3edecea6
Text(sprint(io -> Pkg.status(io=io)))

# ╔═╡ Cell order:
# ╠═8240a3aa-d947-11ea-083b-858ef1451c4e
# ╠═3409c97e-d948-11ea-3536-5999e4418ec9
# ╟─45a0f8b8-d948-11ea-0691-0b4b411a2674
# ╠═81be742e-d948-11ea-2c29-b93dcb78b33f
# ╠═703a3256-d948-11ea-08de-0bbd3edecea6

```
