### ISSUE TITLE
`workspace_custom_startup_expr` kwarg seems broken

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#2652]
This is based on the zulip discussion here https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/pass.20arguments.20into.20Pluto

I didn't even know that the `workspace_custom_startup_expr` was a configuration variable at all, but it seems that it can not really be used (at least on windows).

I just tried calling the example code put on zulip `Pluto.run(workspace_custom_startup_expr=:(ARGS = ["ena", 2, :three]))` but this breaks the Pluto server (even before creating or opening notebooks) with this error:

```
 Warning: Failed to write to WebSocket of 15p5r1q
│   exception =
│    no non-`AnyType` MsgPack mapping found for Expr; please overload `msgpack_type` for this type.
│    Stacktrace:
```

While this is just printed as a warning, it basically breaks the Pluto server.

This also seems to be tested here https://github.com/fonsp/Pluto.jl/blob/27b23a408ebe12e2ef335405b2f3899fd40775b5/test/Configuration.jl#L128-L133

but it does not seem to create a CI error

**Comment by filchristou** [comment]
`workspace_custom_startup_expr` also doesn't work in my machine in linux (Debian 12).
