### ISSUE TITLE
Contains unnessasary directory in release package

### ISSUE THREAD

**Issue by massongit** [fonsp/Pluto.jl#2656]
```bash
$ docker run --rm -it julia /bin/bash
root@72239d0bd257:/# cd ~
root@72239d0bd257:~# julia -e '
import Pkg;
Pkg.update();
Pkg.add([
    "Pluto"
]);
Pkg.precompile();
'
root@72239d0bd257:~# ls .julia/packages/Pluto/kxeso/.vscode/
extensions.json  launch.json  run.jl  settings.json
```

`kxeso/.vscode` directory in Pluto package is a unnecessary directory.
Therefore, I think it is better to delete this directory.

**Comment by rikhuijzer** [comment]
That would cause Pluto developers who use the VSCode settings to have a not so great time. Removing it would cause a bigger problem for Pluto developers than that it improves the situation for users, right?

The best would probably be that Julia releases could specify an ignore file; just like `.gitignore` or `.dockerignore`. However, this is not available as far as I can see.

**Comment by pankgeorg** [comment]
`kxeso` is a version slug, IIRC (not a user or anything, if you are concerned about security or something). That folder has the contents of this folder: https://github.com/fonsp/Pluto.jl/tree/main/.vscode, as it is expected. Julia package distribution works that way currently; nothing we can do about it.

**Comment by Pangoraw** [comment]
We could remove these dev folders in [the release branch](https://github.com/fonsp/Pluto.jl/tree/release) but IMHO it's not worth the hassle.
