### ISSUE TITLE
ReadMe's mp4 video embedding is broken

### ISSUE THREAD

**Issue by briochemc** [fonsp/Pluto.jl#2658]
The Grant Sanderson lecture embedded in the ReadMe does not seem to work anymore for me. Maybe something changed with GitHub's Markdown?

EDIT for clarity, this is what I see:
<img width="872" alt="Screenshot 2023-09-27 at 10 05 58 am" src="https://github.com/fonsp/Pluto.jl/assets/4486578/174a94f4-ce3f-4510-a5b9-5107cb3334b3">

**Comment by Pangoraw** [comment]
can you see the following?

https://user-images.githubusercontent.com/6933510/134824521-7cefa38a-7102-4767-bee4-777caf30ba47.mp4

**Comment by briochemc** [comment]
Oh yes and I can see it in the ReadMe too now. I guess this was just a fluke on GitHub's front. Sorry for the noise!
