### ISSUE TITLE
Even bigger live docs

### ISSUE THREAD

**Issue by Paethon** [fonsp/Pluto.jl#267]
First: Thanks for the "Live docs" feature. It is really great and is extremely convenient to use during programming!
But I think currently it is hindered a bit by the layout of the site.

The window is often too small to use it without scrolling around horizontally, while there is a lot of space wasted on the left side of the screen. In addition, one often has to also scroll vertically because the window is not extending all the way to the top.

Maybe consider moving the code part to the left side of the page while "Live docs" is open and use a bigger part on the right for the "Live docs" window? General formatting is probably nicer if the text is in a tight column, but it would be nice if there would be space to the right for code examples and method signatures to extend into. 

Extending the window further to the top would also be great.

```
height: auto;
max-height: 80vh;
```
seems to work quite well for me height-wise

**Comment by fonsp** [comment]
Have a look at the new version
