### ISSUE TITLE
Obsolete comment about notebook saves in Run.jl ?

### ISSUE THREAD

**Issue by ederag** [fonsp/Pluto.jl#2675]
Just a heads up; the "This is the only time that we save the notebook" comment seems outdated
https://github.com/fonsp/Pluto.jl/blob/a5feb55c96aaaeddbc15fe0a1875e6c6d69011bc/src/evaluation/Run.jl#L135-L136
as there are other calls below:
https://github.com/fonsp/Pluto.jl/blob/a5feb55c96aaaeddbc15fe0a1875e6c6d69011bc/src/evaluation/Run.jl#L223
https://github.com/fonsp/Pluto.jl/blob/a5feb55c96aaaeddbc15fe0a1875e6c6d69011bc/src/evaluation/Run.jl#L232
and the `run_reactive_core!` function calls itself recursively:
https://github.com/fonsp/Pluto.jl/blob/a5feb55c96aaaeddbc15fe0a1875e6c6d69011bc/src/evaluation/Run.jl#L225
https://github.com/fonsp/Pluto.jl/blob/a5feb55c96aaaeddbc15fe0a1875e6c6d69011bc/src/evaluation/Run.jl#L234

It would be nice to update the comment,
otherwise it is easy to stop there and think "then there's no reason for the observed behavior" and give up.

**Comment by fonsp** [comment]
Thanks!
