### ISSUE TITLE
"Scripts and styles not rendered in Safe preview" message

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#2693]
After recent introduction of "safe preview" I see this even after running the notebook:
![image](https://github.com/fonsp/Pluto.jl/assets/687995/7f15adf0-b5a0-46d2-b111-d9ed50adcaec)
I guess that's a bug? Or is there some option for it?

**Comment by Pangoraw** [comment]
This should be fixed in https://github.com/fonsp/Pluto.jl/pull/2689, which is part of release 0.19.31.
