### ISSUE TITLE
HTML export appears to be broken.

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#2699]
With Pluto versions starting 0.19.30, html export (on Linux, both Firefox and Chrome) does not work.
Pluto just opens a new empty browser tab, no html file is created.

**Comment by fonsp** [comment]
I can't reproduce on v0.19.30, v0.19.31 or v0.19.30 on MacOS, Chrome or Firefox. @Pangoraw can you reproduce on Linux?

**Comment by fonsp** [comment]
I also don't see a change that could be relevant in [the diff](https://github.com/fonsp/Pluto.jl/compare/v0.19.29-src...v0.19.30-src)...

**Comment by Pangoraw** [comment]
I cannot reproduce either on Linux

**Comment by j-fu** [comment]
Hm, thanks for your effort! Will try to investigate more tonight...

**Comment by fonsp** [comment]
Hey @j-fu, any news?
