### ISSUE TITLE
"Selection deleted" text appears in PDF

### ISSUE THREAD

**Issue by mgkuhn** [fonsp/Pluto.jl#2704]
Some of my students have submitted Pluto-exported PDFs where the text string “Selection deleted” unexpectedly appears superimposed onto several pages. I don't know yet how to reproduce this, but I suspect this is another GUI element of a Pluto notebook that should be hidden in a PDF printout via appropriate CSS `@media print` rules.

Similar to #2474 ?

**Comment by fonsp** [comment]
Thanks for the report! Working on this in https://github.com/codemirror/dev/issues/1298

**Comment by fonsp** [comment]
Do you still have a PDF document that shows this artefact? It would be really helpful! Did anything else in the PDF document look out of place? The CM author suspects that the student did not use the usual printing (PDF export) feature of the browser.

It would also be helpful to know the browser version number.

**Comment by mgkuhn** [comment]
[student1.pdf](https://github.com/fonsp/Pluto.jl/files/13351930/student1.pdf)

**Comment by fonsp** [comment]
fixed :) updating browsers would also have worked
