### ISSUE TITLE
Allow package updates in "safe preview"

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#2705]
Thanks for the recent "safe preview" mode, now it's much more convenient to look through a few notebooks when you aren't sure which one is needed!
What would be great is to allow running package updates without executing the whole notebook first. Currently package operations seem to be disabled in preview mode.
When I open a relatively old notebook, I know in advance it probably won't work on the current Julia version without package updates. Unfortunate, but that's a part of our reality... So now I need to execute the notebook, wait for package precompilation and some code execution, only to see that some package(s) failed to precompile. Then I click package update button, and wait for it again with new package versions.
Enabling package updates in preview would cut this total delay significantly!

**Comment by fonsp** [comment]
See #3709
