### ISSUE TITLE
HTML exports from Pluto 0.19.4 do not load (recurrence of #2606)

### ISSUE THREAD

**Issue by holomorphism** [fonsp/Pluto.jl#2707]
When opening HTML exports from an older version of Pluto, nothing is displayed.
(Similar issue to Issue #2606, seems to be caused by esm.sh and many-keys-weakmap.js)

This phenomenon has been occurring since about 2023-10-23.
The html file that causes the problem (looks almost the same as in #2606):
* Local html files output between approximately 2022-02-18 and 2023-04-06
* Introduction to Computational Thinking (Spring 2021) page (https://computationalthinking.mit.edu/Spring21/images/)

The following is the chrome DevTools screen shot when opening the Computational Thinking page:
![DevTools console](https://github.com/fonsp/Pluto.jl/assets/3076585/0a748c4c-66f3-473f-bbd0-81bf0db32bb6)

The error message is as follows:
```
Failed to load resource: the server responded with a status of 500 ()
[https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js]
```

I then clicked on [the many-keys-weakmap.js link](https://esm.sh/v64/many-keys-weakmap@1.0.0/es2021/many-keys-weakmap.js), which opened a page with the following content:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "could not resolve \"many-keys-weakmap/many-keys-weakmap\"");
export default null;
```

**Comment by fonsp** [comment]
i dont think we can fix this! 😭😭

@pankgeorg should we report it to esm.sh ?

**Comment by pankgeorg** [comment]
Yes we should. Just did that!

**Comment by BioTurboNick** [comment]
It would be really nice to have an archival version that doesn't depend on external sources that can break. PDF has some limitations with certain kinds of information displays being cut off, and some plots render differently.

**Comment by fonsp** [comment]
Yes! We are working on this in https://github.com/fonsp/Pluto.jl/pull/2802

**Comment by fonsp** [comment]
We opened https://github.com/esm-dev/esm.sh/issues/879 about this, we can't fix this retroactively from our side.


https://github.com/fonsp/Pluto.jl/pull/2802 will prevent this problem in the future.


In the meantime, we stopped using esm.sh and unpkg.com for Pluto imports, we now only rely on jsdelivr.com, which seems like the most reliable. So exports from current Pluto versions are already more stable than 0.19.4.

**Comment by BioTurboNick** [comment]
This appears to be fixed upstream

**Comment by holomorphism** [comment]
I have also confirmed that the issue has been resolved.
@fonsp @pankgeorg  If no problem, can you please close this issue?

By the way, I looked at some of my past html files and again found them interesting.
(Many of them were notes in which I tried to run some Julia code that was available on the Internet and added explanations.)
I love Pluto after all. :blush:
