### ISSUE TITLE
Inconsistency in operator for division of floats

### ISSUE THREAD

**Issue by yestinjoelle** [fonsp/Pluto.jl#2716]
To whom it may concern,

I have encountered an issue with the operand "/div (÷)" where the result (shown in picture) is rounded down automatically; however when I use the operand " (/) " it retrieves the exact float.

Is it possible to enable some similar functionality so that the /div operand also produces the same result as the standard divide operand?

![working](https://github.com/fonsp/Pluto.jl/assets/149094193/8bb33a9d-cd6a-48a1-82ea-b034692d80e8)

![not working](https://github.com/fonsp/Pluto.jl/assets/149094193/69a872be-616a-4d50-be25-e8fb76074782)

**Comment by Pangoraw** [comment]
This is the expected behavior: `div` (÷) refers to the integer division https://docs.julialang.org/en/v1/base/math/#Base.div
You can use `const ÷ = /` if you want ÷ to behave like /
