### ISSUE TITLE
Pluto.run(notebook="...") option too deeply burried in documentation

### ISSUE THREAD

**Issue by mgkuhn** [fonsp/Pluto.jl#2722]
The current docstring for `?Pluto.run` doesn't mention the existing keyword argument `notebook`, which is instead buried two references deeper in `?Pluto.Configuration.ServerOptions`.

The ability to directly name the notebook file to be opened (rather than having to select it via the browser GUI) seems rather basic and essential, therefore it would be nice if how to do this was documented more prominently in `?Pluto.run`.

In fact, why not add it as the first positional argument, such that one can open a notebook directly with
```
Pluto.run("notebook.jl")
```
?

And if the file `notebook.jl` doesn't exist yet, it would be nice if `Pluto.run("notebook.jl")` or `Pluto.run(notebook="notebook.jl")` would create a new notebook and save it under the provided name (like most editors do when being invoked with a non-existing filename). (That latter function could be made conditional on a new `create=true` argument.)

**Comment by fonsp** [comment]
Thanks for the suggestion! Since our audience is less terminal-savvy, we are focusing more on the desktop app https://github.com/JuliaPluto/PlutoDesktop and less on terminal UI.

**Comment by mgkuhn** [comment]
Simple Pluto start-up script for Linux/macOS terminal users: #2725
