### ISSUE TITLE
Feature Request: support hotkeys

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#273]
I feel to make editing more convenient it'd be nice to support some hotkeys, e.g I like the idea using Ctrl/Cmd+B to create new blocks, and maybe a hotkey to add `begin ... end` will also make things easier given this is an requirement for writing multi-line code.

I think at least the following actions that should deserve a hotkey, maybe others would have other idea:

- create new cell
- add `begin ... end`
- execute cell

**Comment by evadknarf** [comment]
I wish for:

- multi-selection
- cell shifting
- cell navigation
- Enter to edit
- cut/paste

**Comment by evadknarf** [comment]
> * create new cell `CTRL` + `ENTER`?

> * execute cell `SHIFT` + `ENTER`?

**Comment by sosiristseng** [comment]
`CTRL` + `ENTER`  = execute cell and add a new cell below

**Comment by fonsp** [comment]
`CTRL` + `ENTER` = execute cell _if the code changed_ and add a new cell below

**Comment by fonsp** [comment]
#163
