### ISSUE TITLE
Pluto input cell font size change

### ISSUE THREAD

**Issue by gganapat** [fonsp/Pluto.jl#2742]
<img width="762" alt="Screenshot 2023-12-09 at 11 00 49 AM" src="https://github.com/fonsp/Pluto.jl/assets/46061218/a397424e-c26c-4e84-a366-a99f5b361d54">

How do I change the input cell font size (and type if possible) in Pluto cells?

Thanks,
Gani -

**Comment by fonsp** [comment]
If the text is too big or small, we recommend zooming the page in or out, or setting your OS's font size in display settings. 

Maybe you could say a bit more about your situation and why you want to change it?

**Comment by gganapat** [comment]
Hi Fons:

Thanks for your response. BTW, just wanted to say that I _love_ your product, Pluto.jl before I go any further. I love that you have learned some good lessons from observablehq for javascript and made something valuable for the Julia community.

Ok, coming back to the topic -- there is no real **need** to have to change the font size beyond the aesthetics of being able to control the type of font and size like you can do with @htl macro for the DOM. I was looking for something that puts the user in control.

gani -

**Comment by fonsp** [comment]
Thanks for the support, that's nice to hear!

We don't really have settings like that, but you can change the typography of one specific notebook, like I did in https://plutojl.org/docs/abstractplutodingetjes/
