### ISSUE TITLE
disabling the package manager doesn't work anymore

### ISSUE THREAD

**Issue by SimonEnsemble** [fonsp/Pluto.jl#2743]
it seems I'm not able to disable the package manger anymore. a student of mine had this same issue. and we had to downgrade Pluto.

see my video: https://www.youtube.com/watch?v=IyZzgDA-1a0

Pluto v0.19.35

Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores

**Comment by SimonEnsemble** [comment]
reproducible across my M1 Mac laptop and desktop.
to anyone having this problem, (1) remove Pluto, then (2) `Pkg.add(name="Pluto", version="v0.19.32")`

**Comment by adannenberg** [comment]
this issue has been closed but it's still there.  i've freed pluto in the package manager, updated to 19.35, exited and re-opened julia, and the problem persists. does this mean that the fix has been merged with a development branch rather than the main branch and won't be available (in main) until 19.36?

**Comment by adannenberg** [comment]
also, in light of the discussion on [#2748](https://github.com/fonsp/Pluto.jl/pull/2748) i've checked that the issue is present in both julia 1.9.4 and julia 1.10.0-rc2.

**Comment by Pangoraw** [comment]
> does this mean that the fix has been merged with a development branch rather than the main branch and won't be available (in main) until 19.36?

Yes, the fix will be available in the upcoming 0.19.36 release. In the meantime, you can test by installing the `main` branch of Pluto: `add Pluto#main` in the Pkg repl where the fix should be present.

**Comment by adannenberg** [comment]
perfect, thank you.
