### ISSUE TITLE
Unclear focus indication

### ISSUE THREAD

**Issue by lukavdplas** [fonsp/Pluto.jl#2747]
When tabbing through the page, it is often unclear where the focus actually is (c.f.  https://www.w3.org/TR/WCAG21/#focus-visible). Here is a video of me tabbing through a notebook:

[screencast of pluto notebook showing repeated tabbing, but without a clear focus ring on every step](https://github.com/fonsp/Pluto.jl/assets/43678097/304e00fa-8a23-4f3b-bea8-85702df54682)

notebook used in recording: https://gist.github.com/lukavdplas/febc2828d061eaeb12b886157e900e45

It's hard to show on video, but between each text cell, there are several TAB presses and elements being focused, but I can't see which ones.

I think the issue is that some buttons don't become visible when they receive focus.

I recorded this on Firefox 120.0 - that may be relevant since I noticed Fons' video in https://github.com/fonsp/Pluto.jl/pull/2746 doesn't seem to have the same issue.

**Comment by fonsp** [comment]
Yayy thanks for looking at this!

I also noticed some of these and they got fixed in https://github.com/fonsp/Pluto.jl/pull/2745 so take another look when you have time

**Comment by lukavdplas** [comment]
Yep, that fixes it! 😄 

Personally, I would also prefer a clearer focus ring around the cell, but that's a style preference. It is possible to see the cell is focused.
