### ISSUE TITLE
Maximize screen real estate

### ISSUE THREAD

**Issue by feribg** [fonsp/Pluto.jl#2751]
Is there a way to make this configurable without using various workarounds to change the CSS etc. 

https://discourse.julialang.org/t/cell-width-in-pluto-notebook/49761/9

I can't see a good reason any developer or presenter or someone who uses Pluto as a dashboard tool, wanting to use 30-50% of the available screen real estate by default. 

All the CSS hacks etc are rather ugly to accomplish that. Is there a good reason for this default ?

**Comment by fonsp** [comment]
Thanks! Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?
