### ISSUE TITLE
All cells appear as running when executing the notebook the first time

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#2755]
Recently (probably since the safe preview feature) all of the cells appear as running and have the running runtime counter active upon starting a notebook.
With long notebooks with potentially long-running cells this might be a bit confusing. The status bar still shows which cell number is being executed but it is still difficult to identify it in the notebook (and clicking on the yellow status bar on top does not seem to reliably point you to the actually executing cell).

https://github.com/fonsp/Pluto.jl/assets/12846528/5ba8857f-c5c8-4249-a0c4-309545ba6133

It would be nice also with this new safe preview mode to still have only the actually running cell being shown as running upon first run.

**Comment by fonsp** [comment]
Hmmm... they should be showing as "queued", not "running", which is currently not easy to distinguish visually. (You can confirm this by looking at the class of the `<pluto-cell>` elements.)

**Comment by disberd** [comment]
@fonsp you are right, it should. But the point I was trying to make showing the running time of the cells is that they are also running (when cell are only queued their running timer doesn't start until they are actually ran).

I checked on the developer pane and it does seem like at first run all cells are both `queued` and `running`.

https://github.com/fonsp/Pluto.jl/assets/12846528/0b912a29-8b9b-4ec7-96f8-4a750869965c

**Comment by fonsp** [comment]
i think this has been fixed... lets check again

**Comment by disberd** [comment]
@fonsp Just tried on 0.19.45 (and on master) and it does not seem to be fixed.
To be clear, this only happens when opening an existing notebook and the clicking `Run`, if you just create a new notebook and populate it with cells after the pluto process for that notebook is already running you don't experience this

**Comment by fonsp** [comment]
Thanks!
