### ISSUE TITLE
Open button doesn't work on Windows

### ISSUE THREAD

**Issue by juliohm** [fonsp/Pluto.jl#2762]
Clicking the `open` button on the welcome page erases the file selection on Windows.

**Comment by fonsp** [comment]
Can't reproduce on MacOS

@pankgeorg What about you on Windows?

**Comment by pankgeorg** [comment]
I'm not sure what you mean @juliohm; deletes the file selection from where? You should get redirected to a different/loading screen. A GIF would be much appreciated! 🤗

**Comment by juliohm** [comment]
You can select the file with the mouse, but when you press the button the
file path is erased.

Em qui., 4 de jan. de 2024 06:15, Παναγιώτης Γεωργακόπουλος <
***@***.***> escreveu:

**Comment by fonsp** [comment]
Can you share a video? Instructions are here https://github.com/fonsp/Pluto.jl/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by juliohm** [comment]
Sorry I didn't see the video request. Can someone reproduce the issue on Windows? Every time I give a workshop with Pluto this happens. All participants with Windows can't open files with the Open button.

**Comment by fonsp** [comment]
Does the enter button work instead of clicking open? Does it happen on every browser?

- fons

**Comment by juliohm** [comment]
Yes, Enter works fine. I believe the issue occurs on every browser, but I'm
sure it occurs on Chrome

Em dom., 11 de ago. de 2024, 13:18, Fons van der Plas <
***@***.***> escreveu:

**Comment by fonsp** [comment]
I can't reproduce on Windows 11 Firefox or Chrome, but I changed the behaviour a bit in #2990

**Comment by juliohm** [comment]
I just reproduced the issue with Pluto.jl v0.19.45 on my tablet with Windows.

```
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, icelake-client)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Google Chrome Version 127.0.6533.100 (Official Build) (64-bit)
