### ISSUE TITLE
Support TestEnv.activate to activate old package management

### ISSUE THREAD

**Issue by schlichtanders** [fonsp/Pluto.jl#2775]
Hi there, I just run into the wish to activate the test environment of my current project - inside Pluto! (aka using Pluto as the IDE).

Pluto already supports a couple of different triggers to activate the old package management, but not yet [`TestEnv.activate`](https://github.com/JuliaTesting/TestEnv.jl)

https://github.com/fonsp/Pluto.jl/blob/be51e4bf8ceaf14bbc5977892a9ac74afefb54c0/src/packages/Packages.jl#L20C1-L35

**Comment by fonsp** [comment]
That would be great! Can you make a PR? You don't need to add a test.

**Comment by schlichtanders** [comment]
I am wondering whether what I wished for makes actually sense.
- If I want to use `TestEnv.activate`, I somehow need access to `TestEnv` ...
- and for the script-file to also be valid, I probably should install it inside another "activation" environment (could also be the projects normal environment)
- hence I will anyway use something like `Pkg.activate("my-TestEnv-bootstrap-environment"); import TestEnv; TestEnv.activate("actual-environment")`

Summary: now I think TestEnv is already perfectly supported. Closing this issue for now.

**Comment by fonsp** [comment]
I agree with @schlichtanders ! But for now I think the situation is so similar to DrWatson.@quickactivate that #3157 is a good idea and it's up to users to figure out the struggle.

If your notebooks contains

```julia
using TestEnv
```

```julia
TestEnv.activate(...)
```

Then currently it leaves the notebook in a broken state: Pluto things it's controlling the package env but you manually activate something else.

After #3157, this will get recognized as an activate, and it will prompt the user to restart the notebook and it contains a message about what happened. After restart, the `using TestEnv` will run in the global env (and it may or may not work). I think it's more predictable behaviour.

And indeed, if you want use TestEnv properly, you should use something like `Pkg.activate("my-TestEnv-bootstrap-environment"); import TestEnv; TestEnv.activate("actual-environment")`.
