### ISSUE TITLE
Investigate use of `@async` instead of `Threads.@spawn` in Pluto

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2779]
In Pluto's source code we have lots of `@async` but apparently that's bad!

https://docs.julialang.org/en/v1/base/parallel/#Base.@async

We should investigate switching to `Threads.@spawn`. I just did a search-replace and it "feels faster"

One concern is that most people just run `julia` which will only have one thread. Does that mean that `Threads.@spawn` and `@async` are equivalent?

**Comment by fonsp** [comment]
Anything else from the call today? Let's close with the "One day" label?

**Comment by pankgeorg** [comment]
We only talked about this and memory management
