### ISSUE TITLE
"Disable cell" has no effect

### ISSUE THREAD

**Issue by roland-KA** [fonsp/Pluto.jl#2801]
Selecting "Disable cell" on a cell in a Pluto has zero effect.

I haven't used Pluto notebooks for a few months. But before, selecting "Disable cell" had the following effect:
- the cell was greyed out
- the cell didn't get updated automatically when a dependent variable changed

The following video shows a simple example of what "no effect" means (the third cell just updates automatically as if "disable cell" wouldn't have been selected): 

https://github.com/fonsp/Pluto.jl/assets/80126696/ce73e0d3-699b-417e-b488-694c0086340f

My environment is:
```
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 8 on 6 virtual cores
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by fonsp** [comment]
What Pluto version are you using?

**Comment by roland-KA** [comment]
I'm using Pluto 0.19.38

**Comment by fonsp** [comment]
Looks like a safari-only issue, possibly caused by #2759

**Comment by roland-KA** [comment]
It works indeed on Chrome.

**Comment by roland-KA** [comment]
I've tried now the new Pluto version 0.19.39 with this fix. 

Here the ...-menu for deleting/disabling the cell appears now on the left side of the cell (before it was on the right side). Unfortunately the content of the menu gets covered by other cells. So it's barely usable.

<img width="963" alt="image" src="https://github.com/fonsp/Pluto.jl/assets/80126696/f5019e44-664b-491b-a600-b281d28c5c49">
