### ISSUE TITLE
🛶 Coming soon!

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#281]
The following features will be added as part of a `v0.12.*` release:
_(feel free to open an issue about any of these)_

- Built-in package manager - https://www.notion.so/Self-contained-reproducibility-995ffa5174894c26b897827bd2ce4990
- 1-click "Deploy on Binder' button (maybe github gist integration?)
- #279 (https://github.com/fonsp/Pluto.jl/issues/115#issuecomment-661405264)
- Running notebooks as scripts - https://www.notion.so/Running-notebooks-as-scripts-48cc50347336412796ca7a7527514f73
- Experiment with notebooks inside notebooks - https://www.notion.so/Notebooks-inside-notebooks-9e99d381c3014e40b310d4846c764a15

**Comment by karlwessel** [comment]
Oh boy, I can't wait for the notebook inside notebook experiments! (Actually, I can wait, no problem, totally grown up and patient...)

**Comment by newptcai** [comment]
How is the "Deploy on Binder" button going?

**Comment by fonsp** [comment]
Hey @newptcai ! We took a slightly different route, and the binder functionality is now built in to the HTML export. Take a look at https://youtu.be/HiI4jgDyDhY?t=474 to learn more
