### ISSUE TITLE
IOContext not properly set for `stdout`, disables ANSI colors

### ISSUE THREAD

**Issue by danielwe** [fonsp/Pluto.jl#2823]
Since #2148 the `stdout` capture window supports ANSI terminal colors, and `:color => true` is set in `default_stdout_iocontext` as seen here:

https://github.com/fonsp/Pluto.jl/blob/216451c3c839d1c3c6c50a0b69ba1b8297cceb43/src/runner/PlutoRunner/src/PlutoRunner.jl#L1007-L1012

However, when querying `stdout` in a Pluto cell, `:color` is set to `false`, so well-behaved Julia code will not print colors. MWE: `printstyled("hello"; color=:red)`. A workaround is to wrap `stdout` in your own `IOContext` and set `:color => true`, but this should not be necessary.

![image](https://github.com/fonsp/Pluto.jl/assets/5809017/b1cc9b07-1254-4f74-87a3-9f8cc2053f75)
(Please take this screenshot in place of a video. Nothing dynamic here.)

Notebook file: https://gist.github.com/danielwe/0663e49fbfb2219b2230d3fe2092c097

Using Pluto 0.19.39 on Julia 1.10.1

**Comment by fonsp** [comment]
Thanks! Can you take a look at https://github.com/fonsp/Pluto.jl/pull/2727 and try to find a solution that works for both use cases?
