### ISSUE TITLE
misplaced action button on 0.19.39

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#2825]
Hi, starting with 0.19.39, the action button is misplaced on the left side
of the code boxes. See this image:

![misplaced_action](https://github.com/fonsp/Pluto.jl/assets/9221937/3cea7194-e7e7-4125-b195-8188df49ad30)

```
julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
Official https://julialang.org/ release
Platform Info:
OS: Linux (x86_64-linux-gnu)
CPU: 20 × 13th Gen Intel(R) Core(TM) i7-13700H
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 20 virtual cores)
Environment:
LD_LIBRARY_PATH = /home/fuhrmann/local/lib64:/home/fuhrmann/local/lib:/usr/local/cuda-12.3/lib64:.:/usr/local/lib64:/usr/local/lib:/home/fuhrmann/local/lib:/home/fuhrmann/Sys/share/pardiso
JULIA_PKG_DEVDIR = /home/fuhrmann/Wias/work/julia/dev
JULIA_PKG_SERVER_REGISTRY_PREFERENCE = eager
JULIA_PARDISO = /home/fuhrmann/Sys/share/pardiso/panua-pardiso-20230908-linux/lib
JULIA_HISTORY = /home/fuhrmann/.julia_histories/_home_fuhrmann
JULIA_SSL_CA_ROOTS_PATH = /home/fuhrmann/.julia/juliaup/julia-1.10.1+0.x64.linux.gnu/share/julia/cert.pem
```

![ffx](https://github.com/fonsp/Pluto.jl/assets/9221937/0a65655d-afce-46c8-a18a-ceddc22b06d3)

**Comment by kellertuer** [comment]
Can confirm the same on Safari (17.2.1, Mac OS Sonoma 14.2.1), where the most problematic part is that the action menu is behind the cell(s).

**Comment by kellertuer** [comment]
I also managed to do 2 recordings on Safari.

1) If the window is broad enough the menu is just behind the cells. They can still be clicked, but you have to know where they are

https://github.com/fonsp/Pluto.jl/assets/115566/d909cd8e-fecb-4703-bf69-acf73bfe84ac

2) If the window is too small in width, the menu even pops to open to the right – which makes it invisible because it reaches outside of the browser window (recording is on the right side of the browser window.

https://github.com/fonsp/Pluto.jl/assets/115566/842d6faa-7dca-4f34-a852-160aa737da1b

**Comment by gecomagenta** [comment]
I can confirm the issue on Safari 17.3.1 and macOS Sonoma 14.3.1: action button on the left side of the code box, and action menu behind the cell.

There seems to be no problem with Google Chrome and other browser based on the same engine.

**Comment by cocoa1231** [comment]
Can confirm the same on Firefox 123 on Debian Stable.

```
(@pluto) pkg> st
Status `~/.julia/environments/pluto/Project.toml`
  [c3e4b0f8] Pluto v0.19.39

julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f0641 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)

shell> cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
