### ISSUE TITLE
Default Pluto indention is tab maybe it should be 4 spaces

### ISSUE THREAD

**Issue by scls19fr** [fonsp/Pluto.jl#2831]
Hello,

When using tab in Pluto.jl, it adds tab character (which seems quite logical). But according to [Style Guide - The Julia Language - Indentation](https://docs.julialang.org/en/v1/manual/style-guide/#Indentation) we can see

    Use 4 spaces per indentation level.

Related #586

It leads to tabs/spaces mixed up when using Visual Studio Code and Pluto.jl

Kind regards

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/586
