### ISSUE TITLE
404: File Not Found /

### ISSUE THREAD

**Issue by scls19fr** [fonsp/Pluto.jl#2835]
Hello,

My Pluto install seems to be broken.

```julia
julia> using Pluto

julia> Pluto.run()
[ Info: Loading...
┌ Info:
└ Opening http://localhost:1234/?secret=vI7BhwHP in your default browser... ~ have fun!
┌ Info:
│ Press Ctrl+C in this terminal to stop Pluto
└
```

open my browser with the following HTML page

```
<!DOCTYPE html>
<html lang="en"><head><meta charset=UTF-8><title>Webots: Not Found</title></head><body><h1>404: File Not Found</h1>/</body></html>
```

Any idea how to overcome that?

Kind regards

**Comment by ctrekker** [comment]
It seems like this might be an issue with running Webots and Pluto simultaneously since they both default to hosting on port 1234. I would suggest running Pluto with the `port` option set to something other than 1234 and see if that helps.

```julia
using Pluto; Pluto.run(; port=4444)  # or replace 4444 with another free port on your machine
```

**Comment by scls19fr** [comment]
Thanks @ctrekker you are right!
I didn't noticed that... https://cyberbotics.com/doc/guide/running-extern-robot-controllers#remote-extern-controllers
