### ISSUE TITLE
Document the list of keyboard shortcuts

### ISSUE THREAD

**Issue by zlatanvasovic** [fonsp/Pluto.jl#284]
I tried to find a list of keyboard shortcuts, but it seems they aren't documented. I found some in the source code: https://github.com/fonsp/Pluto.jl/blob/master/frontend/components/CellInput.js#L57

Besides those, there is Ctrl-D which deletes the current line, for example. Are there some more? Is there an alternative to Pg Up and Down for navigation?

Nevertheless, I think all those should be documented, as they greatly improve the productivity, removing the need to click every second. :smile:

**Comment by zdroid** [comment]
Coincidentally, I found the list in Ctrl+Shift+? / F1, but it seems to be missing Ctrl-D.

**Comment by fonsp** [comment]
It's missing a lot of shortcuts, like Ctrl+C

**Comment by fonsp** [comment]
Where do you think the list should go?

**Comment by zdroid** [comment]
@fonsp Maybe in readme, so that new users know how to use them from the beginning?

**Comment by fonsp** [comment]
The F1 key should be advertised inside Pluto itself

**Comment by zlatanvasovic** [comment]
@fonsp Can this issue stay closed, as I want to close my own issues? You can open another one if this is still a problem.

**Comment by fonsp** [comment]
What do you mean?
