### ISSUE TITLE
Feature Request: Import/Export Jupyter Notebooks (.ipynb) into Pluto Notebooks

### ISSUE THREAD

**Issue by vivekkiran** [fonsp/Pluto.jl#2850]
**Problem Statement:**
Many users within the scientific computing community rely on Jupyter Notebooks for their work. The inability to directly import existing Jupyter Notebooks (.ipynb files) into Pluto Notebooks hinders the exploration of Pluto's unique reactivity and interactivity. Users are forced to manually recreate their work or forgo using Pluto altogether, limiting experimentation, adoption, and collaboration opportunities.

**Proposed Solution:**
Implement a feature to allow the direct import of Jupyter Notebook (.ipynb) files into Pluto Notebooks. 

Ideally, the import process would:
- [ ] **Intelligently convert code cells:** Translate Jupyter's code cells into Pluto's reactive cell structure.
- [ ] **Handle Markdown:** Appropriately render Markdown cells within Pluto's notebook format.
- [ ] **Address Cell Dependencies:** Strive to maintain the execution flow implied by the original Jupyter Notebook's cell order.
- [ ] **Integrate [PythonCall.jl](https://github.com/JuliaPy/PythonCall.jl)** with the Pluto Notebook's notebook import/export feature for seamless execution of Python functions within Julia and vice versa.
- [ ] **Incorporate [RCall.jl](https://github.com/JuliaInterop/RCall.jl)** into the Pluto Notebook's notebook import/export feature to enable direct use of R libraries from Julia.
- [ ] Expand the Pluto notebook's import/export functionality to support the comprehensive range of languages within the **[JuliaInterop] (https://github.com/JuliaInterop)**  ecosystem.

**Alternatives:**
External conversion tools exist but are often unreliable and don't fully capture Pluto's reactive nature. Some online tools attempt Jupyter to Pluto conversion, but they're often unreliable and don't handle the reactive nature of Pluto correctly.
Manual re-creation: This is incredibly time-consuming and prone to errors.

**Additional Context:**
Enabling the import of Jupyter Notebooks would significantly benefit the Pluto Notebook community:
Lower Barrier to Entry: Scientists and developers with existing Jupyter Notebooks could easily evaluate Pluto's advantages saving days/weeks of potential rework.

Streamlined Collaboration: Teams could more easily mix and match both Jupyter and Pluto Notebooks, depending on their specific task and preferences.

**Acknowledgement:** I understand this feature may pose technical challenges due to the underlying differences between Jupyter and Pluto.  Nonetheless, even a partial import/export solution that handles basic code conversion would be a tremendous step forward.

**Comment by ctrekker** [comment]
Something like this would undoubtedly be very valuable, but it should go in its own package. Things like converting Markdown cells andn integrating PythonCall / RCall are pretty much already done and should work in Pluto already. Addressing cell dependencies is the hard part - for example, what should we do with the following Jupyter notebook?
Cell 1:
```julia
x = [1]
``` 
Cell 2:
```julia
last(x)
```
Cell 3:
```julia
push!(x, 2)
``` 

This a highly simplified example, but in general it's not immediately obvious how this code should be translated into a reactive environment. In many cases a conversion process that guarentees a topological ordering that reproduces the original ordering of Jupyter notebooks would produce a converted Pluto notebook that isn't so useful (all code in only a few cells, for example). There are absolutely ways to do it, but it's complicated and certainly belongs in its own package that uses something like [PlutoDependencyExplorer](https://plutojl.org/en/docs/plutodependencyexplorer/).
