### ISSUE TITLE
Safari no longer supported after Pluto v0.11.4?

### ISSUE THREAD

**Issue by goedman** [fonsp/Pluto.jl#286]
Hi,

Going over the issues threads this morning I decided to update Pluto, first to v0.11.5 and later to v0.11.6. Neither seems to work on Safari.

The start-up screen appears fine (on port 1234, a second session will take port 1135), but after selecting to open a new notebook, the top right of the screen shows `Loading` and `Disconnected` repeatedly. Nothing is output to the Terminal window and no cells show up.

It does work on Chrome (but that is not a good option for me right now).

Let me know if I can help out with testing.

Rob

**Comment by fonsp** [comment]
Safari is not an officially supported browser because I can't test on it. But if someone submits a minor PR to add support, I will add it in!

A screenshot of your browser's developer console would be helpful for anyone who wants to fix it
