### ISSUE TITLE
Incorrect dependency for nested functions

### ISSUE THREAD

**Issue by Alseidon** [fonsp/Pluto.jl#2864]
![image](https://github.com/fonsp/Pluto.jl/assets/58395551/6f57787b-d60c-47b7-960e-52fe7f5506b9)

results from this notebook: 

```julia
### A Pluto.jl notebook ###
# v0.19.9

using Markdown
using InteractiveUtils

# ╔═╡ 33533c42-ed09-11ee-0da9-818a477aafad
function func_1(a)
	res = func_2(a)
end

# ╔═╡ 9ccf6b10-fbac-4145-b8e7-99faa7138e2e
a = func_1(3)

# ╔═╡ 8e1c7bb0-1efe-4ee9-b476-32e842ebb050
function func_2(a)
	return a + 2
end

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.2"
manifest_format = "2.0"
project_hash = "da39a3ee5e6b4b0d3255bfef95601890afd80709"

[deps]
"""

# ╔═╡ Cell order:
# ╠═9ccf6b10-fbac-4145-b8e7-99faa7138e2e
# ╠═33533c42-ed09-11ee-0da9-818a477aafad
# ╠═8e1c7bb0-1efe-4ee9-b476-32e842ebb050
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
```

This happens if you write the `func_1` definition before (chronologically) `func_2`.

I can't remember if this was a thing in previous Pluto versions.

**Comment by fonsp** [comment]
Can you update Pluto and try again? Your version is almost 2 years old.

**Comment by Alseidon** [comment]
> Can you update Pluto and try again? Your version is almost 2 years old.

I'm so sorry I didn't realize... Running the same notebooks with v0.19.40 works just fine.

Installing `Plotly.jl` in the same environment actually restricted Pluto to this version, because of a conflict on `HTTP.jl` version. My bad:
