### ISSUE TITLE
Autocomplete shows anon functions

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2866]
<img width="226" alt="image" src="https://github.com/fonsp/Pluto.jl/assets/6933510/743fe84e-2bcc-436f-b57f-5dba05369cad">

**Comment by Pangoraw** [comment]
Are those [anonymous functions](https://github.com/JuliaPluto/ExpressionExplorer.jl/blob/0ad00cca943667688f357ff28e21aabb727ec50e/src/explore.jl#L336C1-L337C13) from ExpressionExplorer?

**Comment by fonsp** [comment]
Yesss I think so, here's a MWE

<img width="426" alt="image" src="https://github.com/fonsp/Pluto.jl/assets/6933510/e59d768b-2353-4373-b9e8-58cc3c2d2eb0">
