### ISSUE TITLE
[small improvement] Add docstring

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#287]
Be nice to have a docstring at the REPL...

<img width="463" alt="Screenshot 2020-08-14 at 08 37 05" src="https://user-images.githubusercontent.com/52289/90225702-b0c51780-de09-11ea-81d3-f4d222795c00.png">

**Comment by fonsp** [comment]
Ooh I didn't know about module docstrings. Would you like to write it? Or copy paste from the readme?

**Comment by fonsp** [comment]
Hey @cormullion have you made any fun notebook that you'd like to share?

**Comment by cormullion** [comment]
:) I think it's just something like this:

```
"""
To launch Pluto, type `run()` and then open your browser at the given address.
"""
module Pluto
```

I just had a blank moment when I forgot whether it was `notebook()` or `run()`...  

I've been testing Lindenmayer.jl with Plutonian sliders, but it's a bit shaky (my fault) when things get complicated:

<img width="450" alt="Screenshot 2020-08-14 at 10 02 02" src="https://user-images.githubusercontent.com/52289/90232943-44501580-de15-11ea-9e46-cebd081bf4c8.png">

Once you're into half a million iterations things get a bit sticky... :)
