### ISSUE TITLE
Autocomplete: select completion with comma key

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#2871]
Typing `funcs = [sin, identi<COMMA>` should autocomplete to `funcs = [sin, identity,`

**Comment by fonsp** [comment]
Same with `(`

**Comment by kosukesando** [comment]
I'm having trouble with this behaviour being overzealous, for example when I just want to iterate over zip'd iterables:

```
for (f,b) in zip(foo,bar)
```

typing in `for (f<COMMA>` will instantly autocomplete this with some arbitrary variable that has nothing to do with this code block.
I think there's been other occurrences of this but can't give off the top of my head right now.

**Comment by kosukesando** [comment]
It's also doubly annoying when I can't <ESC> out of the autocomplete back to the cell, but it takes me out of the autocomplete AND the cell. (please excuse the double comment, it probably belongs somewhere else)

**Comment by fonsp** [comment]
Thanks! What browser do you use?

**Comment by kosukesando** [comment]
Firefox(126.0) on Windows 10, running Julia+Pluto on Ubuntu(WSL2).

**Comment by fonsp** [comment]
Can you check if the ESC issue also exists on Chrome if you have it installed?

**Comment by fonsp** [comment]
Fixed the comma thing in https://github.com/fonsp/Pluto.jl/commit/3af53f9cbc550315ced9fefc7d2e5cd1a22d06ef

**Comment by fonsp** [comment]
Can you check if the ESC issue is also there on `Pluto#main`? I can't reproduce on firefox. If so, could you make a new issue?

**Comment by kosukesando** [comment]
Thanks for the quick response!
I tried Chrome, it turns out the ESC issue was just Vimium, my bad. The comma thing was present in both FF and Chrome.
For the time being I can just deal with the autocomplete with hitting ESC.
