### ISSUE TITLE
All web assets should be offline

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#29]
What to do with fonts? Custom themes? Licenses?

**Comment by Pocket-titan** [comment]
https://webpack.js.org/guides/getting-started/

**Comment by fonsp** [comment]
How would you use that in our case?

**Comment by fonsp** [comment]
If it's a compilation step that puts binaries inside the repository - we can just as well download the dependencies ourselves and put them in the repository. 

I was thinking of a solution that either uses the julia server to cache dynamically ([see this branch](https://github.com/fonsp/Pluto.jl/tree/cached-assets)) or a web worker.

**Comment by Pocket-titan** [comment]
You could use Workbox (https://developers.google.com/web/tools/workbox/) to cache google web fonts, css, js & images (it uses a serviceWorker), but it requires either npm or webpack to use precaching - so you wouldn't even have to have used Pluto online once for it to be able to serve the assets offline. See https://webpack.js.org/guides/progressive-web-application/ for more info

**Comment by Pocket-titan** [comment]
But at this point I'd suggest replacing the script tags with npm modules since they can be bundled + cached, which I think makes it preferable over downloading the scripts manually

**Comment by fonsp** [comment]
Does it require the user to install and run node?

**Comment by Pocket-titan** [comment]
Definitely not, you'd create an npm package and include a build step, and serve the latest build from the julia webserver. This way you could also switch between serving the build or a local dev copy, so you can change the ui without actually changing the "official" Pluto build itself

**Comment by Pocket-titan** [comment]
I can whip something up later today if you want to see what it'd look like?

**Comment by fonsp** [comment]
Hm a build step is not nice

**Comment by fonsp** [comment]
I think it's fine to require Pluto to be run online once - without an internet connection you would not have been able to install Pluto.

**Comment by fonsp** [comment]
But workbox looks nice! (Isn't it just as easy to write a caching webworker ourselves?)

**Comment by Pocket-titan** [comment]
Possible, but not just as easy - the strategies described here https://jakearchibald.com/2014/offline-cookbook/ is already implemented in workbox like this: https://developers.google.com/web/tools/workbox/modules/workbox-strategies

**Comment by fonsp** [comment]
ooh there's a cache API?
