### ISSUE TITLE
Performance - delay creating codemirrors

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#291]
When you load a notebook, it creates a codemirror for every cell. We could optimise this by only creating codemirrors for cells that are _not_ folded. 

Cells that are initially folded should only create the codemirror when it is first unfolded.

Maybe we can even delete codemirrors when they are not visible? Instead of the current `display: none`

**Comment by novoselrok** [comment]
Additional enhancement would be to initialize code mirrors only after they come into the viewport (using IntersectionObserver API).

**Comment by fonsp** [comment]
Solved by #484.

Strangely, the performance benefit is not noticeable, so let's not do the viewport thingy
