### ISSUE TITLE
Dissable the Safe Preview Feature

### ISSUE THREAD

**Issue by guo-yong-zhi** [fonsp/Pluto.jl#2916]
I want to skip the safe preview, and run all cells immediately on the notebook loading, just like in the old version pluto.  What should I do? I have tried the following command, but it is not working.
```julia
Pluto.run(run_notebook_on_load=true, warn_about_untrusted_code=false)
```

**Comment by fonsp** [comment]
There is no setting for this currently. PR welcome!

**Comment by fonsp** [comment]
You can use Pluto's built in feedback box for feature requests
