### ISSUE TITLE
Shortcut to "Show/hide code"

### ISSUE THREAD

**Issue by VivaldoMendes** [fonsp/Pluto.jl#2917]
Hi all,

I use Pluto a lot and I teach two courses with it. In this context, I have to use Markdown extensively. I have a stupid tendinitis that makes using the mouse in repetitive movements quite painful. For people who have this kind of disability, the use of keyboard shortcuts may be precious.

It would be highly beneficial to access the keyboard to **_hide the written and executed Markdown_** instead of using the mouse. I searched and found two cases where this issue has been discussed: [in this thread](https://github.com/fonsp/Pluto.jl/issues/65#issue-595782206) and [here](https://github.com/lucio-cornejo/custom-pluto). @lucio-cornejo's proposal looks very complicated, and this issue was not considered (apparently) in the former thread. In that thread, is the shortcut named as "Fold/unfold cell" intended to do what I am searching for here?  Has it been implemented?

Thanks in advance.

**Comment by fonsp** [comment]
Hey @VivaldoMendes! Currently you need to press Esc, Shift+Tab, Shift+Tab to navigate to the 👁️ and then Enter to click it. That's not super nice!

Do you have a suggestion for a keyboard shortcut? I don't see something useful from the VS Code notebook shortcuts that we can reuse.

**Comment by VivaldoMendes** [comment]
Hi @fonsp, 

Thanks for the reply. For me, any key combination will do. Some people are very sensitive to the particular combinations that may be used (some may even go to the extreme of developing a proto-theory about it), but not me. As long as we have access to two keys to hide our Markup code, I will be more than happy.

By the way, congrats on this wonderful piece of software. I see some colleagues of mine moaning about not having access to something like Pluto in Python.

**Comment by fonsp** [comment]
Thanks for the nice comment! 💛
