### ISSUE TITLE
Packages do not update (Safari)

### ISSUE THREAD

**Issue by tamasgal** [fonsp/Pluto.jl#2918]
I am having a hard time updating packages in Pluto.jl notebooks. If I click on the "arrow up" button which shows when hovering over a `using ...` line, the popup simply disappears and nothing happens. 

Then I tried `using Pkg; Pkg.update()` but nothing gets updated.

I do not fully understand how the magic in Pluto with version pinning (Manifest) is working but I assume something is pinned in the background and I have no idea how to release that. According to the docs, it should be possible by hitting the "arrow up" button when hovering over `using` lines.

The following screen recording shows that Pluto won't let me update `LumenManufaktur.jl` from an old version `0.4.1` to the latest `0.5.1`. Also not when using `Pkg` directly.

https://github.com/fonsp/Pluto.jl/assets/1730350/0634032e-1209-426b-9c76-60d416ffbbec

**Comment by tamasgal** [comment]
With FIrefox I got a popup after clicking on the update arrow and the update worked. So I guess it's relatedo to Safari 17.3 on macOS Sonoma 14.3 (23D56).

**Comment by tamasgal** [comment]
Hey! No luck unfortunately 🙁 The arrow is dark, indicating that there is an available update (I guess?) but the small popup simply disappears when I click it and nothing happens. I don't have any plugins or blockers in Safari.

https://github.com/fonsp/Pluto.jl/assets/1730350/4c96ce8e-a3ff-462f-9974-b851c9f6e3b4

**Comment by fonsp** [comment]
Hey! Can you check for errors in the Julia terminal where you launched Pluto and in the browser dev tools: https://github.com/JuliaPluto/pluto-developer-instructions/blob/main/How%20to%20open%20the%20Browser%20Dev%20Tools.md

**Comment by tamasgal** [comment]
Nothing is reported, neither in the `Pluto.jl` process nor in the developer console. It seems that the click is simply ignored completely.


https://github.com/fonsp/Pluto.jl/assets/1730350/bd436802-6999-4126-9672-685b3a57daf7

**Comment by tamasgal** [comment]
Just noticed that the link is weird, it starts with a `#`:

![Screenshot 2024-05-16 at 11 09 44](https://github.com/fonsp/Pluto.jl/assets/1730350/b3a089c7-1a15-47a7-9f3c-e5eb7d2ff5cc)

**Comment by fonsp** [comment]
Ah sorry, I just tried on safari and it also doesn't work for me. Are you sure that it doesn't work on Chrome on your computer? Can you check error messages there?
