### ISSUE TITLE
Moving Pluto Cells within HTML

### ISSUE THREAD

**Issue by Niels1006** [fonsp/Pluto.jl#2929]
### Discussed in https://github.com/fonsp/Pluto.jl/discussions/2919

<div type='discussions-op-text'>

<sup>Originally posted by **Niels1006** May 13, 2024</sup>
Hey,

I'm curious whether it is somehow possible to move a whole pluto cell to another location within the HTML structure of Plutos frontend.
This would be the cell in its default location:
```html
<div class="default-cell-location">
    <pluto-cell id="id"/>
</div>
``` 

Could I somehow move that cell somewhere else while it keeps its functionality and reactivity?
For example:
```html
<div class="container">
     <div class="container-2">
        <pluto-cell id="id"/>
    </div>
</div>
<div class="default-cell-location">
        
</div>
```
Are there some JavaScript functions already that could be modified to allow for that?</div>
Sorry about no video, but I actually couldn't think of one in any way.

**Comment by fonsp** [comment]
I'll answer in the discussion :)
