### ISSUE TITLE
Unicode completion often doesn't work

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#2944]
I find that unicode completion often doesn't work in Pluto – simply refuses to complete a symbol.
Some symbols never get completed, some get completed in some contexts but not in others.

I _think_ that some long time ago the completion felt more reliable, but not 100% sure on that.

Here's a video, demonstrating Julia REPL behavior (always completes properly) vs Pluto behavior.

https://github.com/fonsp/Pluto.jl/assets/687995/87b2e460-2ba9-4bab-bfdb-f5138bbd6835

**Comment by Pangoraw** [comment]
Thanks for the report!

**Comment by fonsp** [comment]
I'm looking for more autocomplete bugs! Did you find any other cases where autocomplete gave an unexpected result? Please send me a video!

**Comment by aplavin** [comment]
Sure! :)

https://github.com/user-attachments/assets/4b10b751-ac89-4e94-9b3f-081243942665

**Comment by fonsp** [comment]
awesome!! more please!
