### ISSUE TITLE
Package does not update, although the newest version is shown

### ISSUE THREAD

**Issue by tamasgal** [fonsp/Pluto.jl#2947]
I still have the problem that packages won't update although Pluto indicates that the newest version is being installed.

I open the notebook and as you can see, `v0.17.0` of `KM3io.jl` is being shown to be installed:
<img width="391" alt="Screenshot 2024-07-03 at 14 21 08" src="https://github.com/fonsp/Pluto.jl/assets/1730350/1de3adee-2625-432b-ae4d-449cc57b3cd0">

After that however, `v0.16.9` is installed.
<img width="397" alt="Screenshot 2024-07-03 at 14 20 53" src="https://github.com/fonsp/Pluto.jl/assets/1730350/aeda9a71-6272-4195-985d-522dc082cd14">

I don't know how to debug this and I don't see any helpful logs either. I am using Chrome and `Pluto v0.19.43`

**Comment by konstantin-azarov** [comment]
I'm hitting this problem too (with a package in a `LocalRegistry`). I don't have time to debug it now, so I've been manually removing the `[compat]` entry for my package and the manifest from the notebook file.

**Comment by fonsp** [comment]
Thanks! You can subscribe to https://github.com/fonsp/Pluto.jl/issues/2940
