### ISSUE TITLE
[Markdown] Interpolation of variables in URLs does not work

### ISSUE THREAD

**Issue by tamasgal** [fonsp/Pluto.jl#2948]
For some reason, the URL syntax is not working when interpolating variables in the URL markdown syntax `[Link name](URL)`. Variables enclosed by the square brackets gets interpolated, but those in the URL part not.

In the screenshot below, the first URL is pointing to `localhost:1234/$(pluto_url)`, so no variable interpolation is being done.

<img width="644" alt="Screenshot 2024-07-04 at 10 19 34" src="https://github.com/fonsp/Pluto.jl/assets/1730350/9aa3148a-861a-4996-8224-ca4fede0be41">

I checked in the REPL and the escaping of the parentheses is definitely needed and produces the correct markdown output, I think, so I am not sure why Pluto displays the raw text:

```julia
julia> md"""
       [Pluto]($(pluto_url)) (points to **localhost:1234/\$(pluto_url)** -> no interpolation)

       [Pluto]\($(pluto_url)\) (interpolates correctly but prints as it is, without assembling the href)

       [$(pluto_url)](Pluto) (interpolates correctly within the square brackets, but )

       Here is the URL: $(pluto_url)
       """
  Pluto ($(pluto_url)) (points to localhost:1234/$(pluto_url) -> no interpolation)

  [Pluto](https://www.plutojl.org) (interpolates correctly but prints as it is, without assembling the href)

  https://www.plutojl.org (Pluto) (interpolates correctly within the square brackets, but )

  Here is the URL: https://www.plutojl.org

```

Any ideas?

**Comment by Pangoraw** [comment]
> I checked in the REPL and the escaping of the parentheses is definitely needed and produces the correct markdown output, I think, so I am not sure why Pluto displays the raw text:

In this case, doesn't the correct output would be something like:

```julia-repl
julia> Markdown.parse("[Pluto]($pluto_url)") # expected
  Pluto (https://plutojl.org)

julia> md"[Pluto]\($(pluto_url)\)" # actual
  [Pluto](https://plutojl.org)
```

this seems to be a bug in the Markdown standard library.

**Comment by Pangoraw** [comment]
Closing as this issue is tracked in https://github.com/JuliaLang/julia/issues/38298 upstream.
