### ISSUE TITLE
Importing or installing packages is not reactive

### ISSUE THREAD

**Issue by npbarnes** [fonsp/Pluto.jl#295]
Suppose I start a new notebook and write a couple of cells
`plot([1,2,3])`
and
`plot([3,2,1])`
Then I go back and run the first cell. Naturally, I get `UndefVarError: plot not defined`. That's fine, so I add a cell `using Plots` and run it. My other two cells don't update. I have to run both of them individually manually. I would have expected it to realize that `plot` was brought into scope when I ran `using Plots` and update cells accordingly. 

It's not a problem with a notebook that only has two cells, but I first ran into this problem when I tried to look at the sample notebook about Plots.jl. It didn't work as expected because I didn't have Plots installed on this computer. I tried to fix this oversight by adding a cell `import Pkg; Pkg.add("Plots")` and running it. Of course, that works, but it doesn't update the other cells. They have to be re-run manually.

**Comment by fonsp** [comment]
#24
