### ISSUE TITLE
Firefox stuck with 0.19.44

### ISSUE THREAD

**Issue by tmistele** [fonsp/Pluto.jl#2959]
I updated to 0.19.44 and noticed that Pluto doesn't load correctly in the browser. It's stuck at the following screen:

![image](https://github.com/user-attachments/assets/be6815de-5a5f-4ede-99ce-ba2a7054de4a)

I'm using Firefox and it seems the issue is the `navigator.userAgentData` used here

https://github.com/fonsp/Pluto.jl/blob/b146dcc0acbe8c891ef59b47b75507ed82e27ec3/frontend/common/KeyboardShortcuts.js#L2

Perhaps the fix is to simply insert a `?` like this?

```javascript
/Mac/i.test(navigator.userAgentData?.platform ?? navigator.platform) 
```

Downgrading to 0.19.43 fixes the issue.

**Comment by Azzaare** [comment]
I ran into the same issue with both Safari and Firefox.

**Comment by Pangoraw** [comment]
thank you for the report, a new release will be tagged with the fix.
