### ISSUE TITLE
Use JuliaMono font 🔤

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#296]
Thanks @cormullion for helping me out!

Read this discussion about loading the font:
https://github.com/cormullion/juliamono/issues/24#issuecomment-674382769

**Comment by Pocket-titan** [comment]
Just my two cents: you might find the [css property `unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) useful, to be used inside the `@font-face` rule. This way, you could define two `@font-face` rules, one for the latin font & one for Latin + the other glyps (and have them use the same`font-family`identifier), where the former would have a `unicode-range` spanning the Latin alphabet & the latter spanning Latin + the rest.
