### ISSUE TITLE
WebIO & PlotlyJS support?

### ISSUE THREAD

**Issue by KajWiik** [fonsp/Pluto.jl#299]
Should PlotlyJS work? I get `WebIO not detected.` error.

**Comment by KajWiik** [comment]
Oops, this is already being worked on.
 https://github.com/fonsp/Pluto.jl/issues/141#issuecomment-672778575

**Comment by fonsp** [comment]
Can you post a notebook that produces the error?

**Comment by KajWiik** [comment]
```
### A Pluto.jl notebook ###
# v0.11.6

using Markdown
using InteractiveUtils

# ╔═╡ 0ec2f8c0-dfb3-11ea-2064-272cfc7704cf
using PlotlyJS

# ╔═╡ 386ec6f4-dfb3-11ea-021d-7742d5146226
plot(rand(10))

# ╔═╡ Cell order:
# ╠═0ec2f8c0-dfb3-11ea-2064-272cfc7704cf
# ╠═386ec6f4-dfb3-11ea-021d-7742d5146226
```

**Comment by fonsp** [comment]
Until this is fixed, you could use Plotly as a backend for Plots.jl, but the API is different.

**Comment by KajWiik** [comment]
That works perfectly, many thanks!

**Comment by Masacroso** [comment]
Im using PlotlyJS as a backend of Plots.jl and it works like a charm. Maybe you can make the same.

**Comment by NaNotia** [comment]
PlotlyJS works well, but I want the figure shows in Pluto window, not its own Electron window when I use WebIO utilities.

Is there any solutions for taking both PlotlyJS's strong interactivity and PlutoUI's convenient bind tools?

**Comment by dralletje** [comment]
Not yet a solution, we have to implement a webIO solution for Pluto.. Working on it though

**Comment by empet** [comment]
Any news on WebIO for Pluto to be able to display plotly plots defined by PlotlyJS?

**Comment by fonsp** [comment]
It's coming at some point

**Comment by empet** [comment]
Hopping that meanwhile this issue has been fixed, I tried  again to display a  PlotlyJS plot in Pluto, but the same message   persists :(
```
WebIO not detected.
Please read the troubleshooting guide for more information on how to resolve this issue.
https://juliagizmos.github.io/WebIO.jl/latest/troubleshooting/not-detected/
```
Is this much different from displaying plots generated by WGLMakie?

**Comment by KajWiik** [comment]
Plots & Plotly works fine:
[image: Screenshot from 2021-05-02 20-32-47.png]

**Comment by sglyon** [comment]
@fonsp  what would it take to get an integration working?

I'm the PlotlyJS.jl author and am teaching some courses this coming semester. I'd love to use PlotlyJS in my course and am happy to help get this fixed

**Comment by dralletje** [comment]
@sglyon nice! I'll make sure the PR works on the latest Pluto version by tomorrow - then we can have a call to look if it covers all features you need? I use Plotly enough to make that PR, but I'm no expert by any means :P

**Comment by sglyon** [comment]
Excellent! Thank you for the hard work. Ping me if I can help

**Comment by gganapat** [comment]
@fonsp, @dralletje, @sglyon Any progress on this end?

thx!

**Comment by newptcai** [comment]
Any progress?

**Comment by fonsp** [comment]
Some recent progress in #2392 ! We decided not focus on JSServe.jl instead of WebIO.jl for now, see the PR to learn more.

**Comment by fonsp** [comment]
WebIO will probably not be supported in Pluto, but we are working on alternatives:
- dynamic JS content: on top of what Pluto already offers, we are working on #2726 and supporting Bonito.jl (aka JSServe.jl)
- asset server: we find the API of AssetRegistry.jl too difficult to support properly, in particalur in Static HTML exports (viewing online or on the web), where no Pluto server is running. We have working prototypes of alternatives that do not require a web server, and use data URLs or `AbstractPlutoDingetjes.Display.published_to_js` instead.

**Comment by beorostica** [comment]
Hi there!
PlotlyJS relies on WebIO. So, if WebIO is not supported, it means that the beautiful PlotlyJS plots won't be displayed in Pluto 😢. Is there a possibility to maintain support for WebIO?

**Comment by fonsp** [comment]
@beorostica Take a look at PlutoPlotly.jl!
