### ISSUE TITLE
`@bind` inside table always renders in "Safe Preview" mode

### ISSUE THREAD

**Issue by dpgarrick** [fonsp/Pluto.jl#2994]
Tiny reproduction is here:

https://gist.github.com/dpgarrick/9dccbeb1a09821402e2e27e385a2f2fc

Even after running the notebook code and disabling safe preview, the warning message still appears, and the field itself is unusable/uneditable - any changes the user makes to that value in the NumberField element does not save or propagate.

I had a go with Claude AI to try and diagnose and fix the issue in the Pluto code but was unsuccessful....React is not my thing.

The fix (maybe) is for the bonded elements to be regenerated once the safe preview is disabled, otherwise they are stuck in a disabled "safe preview"  mode forever.

Unclear to me if this is a Pluto.jl or PlutoUI.jl bug given the safe preview logic is handled here, but it is not propagating to a PlutoUI element. Seems like it is a Pluto.jl issue but if actually the latter then this issue can be moved to that repo.

**Comment by fonsp** [comment]
Hey @dpgarrick ! Could you post a screenshot?

**Comment by dpgarrick** [comment]
Sure! 

Before running
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/51b17da6-df4a-43f4-877c-7a1027bac283">

After running
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/789e4208-0ce5-421f-977f-13a413206ae5">

And adjusting the myField values doesn't propagate.

**Comment by fonsp** [comment]
Thanks! fixed in the next release
