### ISSUE TITLE
autocomplete on type problematic when defining functions

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#3011]
Motivated by #3008, am posting an example where I found autocomplete on type to be very bothersome, that is when defining new functions as autocomplete on type completes with `(` and `,`, often disrupting workflow when typing function definitions.

This is especially disruptive for very simple oneliners functions for tests as I have to go back and correct this twice in the example below (note, `Shift + 9` is `(`):

https://github.com/user-attachments/assets/1b0a21c1-1993-4736-842b-091366e6d52b

**Comment by fonsp** [comment]
I'm looking for more autocomplete bugs! Did you find any other cases where autocomplete gave an unexpected result? Please send me a video!
