### ISSUE TITLE
Better autocomplete

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#302]
Sorting autocomplete results:

_Right now results are presented in alphabetical (i.e. code index) order. The dream is to have full AI power like kite.com, but perhaps there are some simple improvements to be made first._

- [x] lowercase first, then uppercase?
- [x] for `Module.<TAB>`, first show names that are `export`ed by the module, then the rest. The set of exported names should be everything that you need, and the other names are probably not meant to be used.
- [x] Show basic type info: is it a function, submodule, ...?
- [x] Fuzzy search
- [x] Autocomplete all words in the same CM - https://codemirror.net/demo/anywordhint.html

### Please post other ideas and suggestions!

**Comment by fonsp** [comment]
Those already work inside Pluto - is it broken for you?

**Comment by fonsp** [comment]
Great to hear that you want to contribute! If you want to work with Julia instead of JS, then writing sample notebooks might be the most fun. Ideas [here](https://github.com/lukavdplas/pluto-notebooks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and [here](https://github.com/fonsp/Pluto.jl/projects/2#column-9124852), I'd be happy to have a video call if you have an idea: fonsvdplas@gmail.com

**Comment by cadojo** [comment]
> Those already work inside Pluto - is it broken for you? You might need to press TAB twice.

Ah I must have missed it before, it is working for me! Thanks!

> writing sample notebooks might be the most fun

I'm about to start my last year of grad school, I'll be taking a few aerospace dynamics courses this semester that might offer opportunities for interesting functional programming examples. I'll see what my classes look like - if an assignment fits, two birds with one stone. If not, I'll add an example or two this semester. I'll send an email with ideas once they're more thought out!

**Comment by fonsp** [comment]
Nice! i think a functional programming sample could be really useful - Pluto makes more sense when you program in the functional style

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/111#issuecomment-683432200

**Comment by pbouffard** [comment]
I'm not sure what it's called (fuzzy searching maybe?) but the kind of autocomplete where you are shown results that include not just those that begin with the characters you've typed so far.

I.e. like:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/231346/96934671-7a45f180-1477-11eb-8290-620755b613c7.png">

I use this constantly in various IDE's, including VS Code.

**Comment by fonsp** [comment]
I implemented export info and type info in https://github.com/fonsp/Pluto.jl/pull/606

**Comment by pbouffard** [comment]
Possibly of interest: https://github.com/tkf/InteractiveCodeSearch.jl

**Comment by aviatesk** [comment]
As for "fuzzy search", we can use [FuzzyCompletions.jl](https://github.com/JunoLab/FuzzyCompletions.jl) as a drop-in replacement of `REPLCompletions` module (, which is actually a backend completion engine for Juno).
@fonsp what do you think on this ? If we want to try this out, I'm welcome to make up a PR.

**Comment by fonsp** [comment]
Interesting, if it is really that easy then your PR would be very welcome!

**Comment by FeldrinH** [comment]
Maybe there already is an option for this, but it seems that currently the autocomplete only shows suggestions if you press tab.

In most editors, the autocomplete starts showing suggestions as soon as you start typing, which is a lot more convenient and faster, because you can just type without thinking about autocomplete, and then accept a suggestion if you see the correct one pop up.

**Comment by fonsp** [comment]
Thanks @FeldrinH ! We want to enable autocompletion on every keystroke, but I think we should only enable this if our autocomplete is good enough, otherwise users might get frustrated. The big IDEs generally have a scoring mechanism to judge whether a completion is relevant enough to pop up without prompt.

**Comment by icweaver** [comment]
Would it be possible to list file/directory paths on pressing the tab key first instead of a character that already exists? The [workaround](https://github.com/fonsp/Pluto.jl/issues/717) was to enter `"<some path>/.<TAB>"`, but I don't think that this seems to work anymore?

This feature has been super handy for navigating around directory trees without needing to look up what files already exist in a separate terminal

**Comment by hungpham3112** [comment]
Does Pluto has autocomplete when typing without press `<Tab>` at first?

**Comment by fonsp** [comment]
Everything here is implemented! Last item is #2389 :)
