### ISSUE TITLE
Aggressive Autocomplete, Specific Example

### ISSUE THREAD

**Issue by alecloudenback** [fonsp/Pluto.jl#3021]
ref #3008, opening a new issue as requested

I have also found the autocomplete to be very aggressive. 

Example: I am trying to define a new function called `foo` and I type `foo(` and upon hitting `(` the input autocompletes to `floor(`

https://github.com/user-attachments/assets/f646a1e4-b12d-4f67-b813-1c7ad94bba2a

Pluto 0.19.46
```
Julia Version 1.11.0-rc3
Commit 616e45539db (2024-08-26 15:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m3)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_NUM_THREADS = auto
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by lukeburns** [comment]
Hard to use.

**Comment by fonsp** [comment]
Thanks for the feedback! I disabled the `(` autocomplete commit character in https://github.com/fonsp/Pluto.jl/pull/3055
