### ISSUE TITLE
Markdown text interpolation bug

### ISSUE THREAD

**Issue by haakon-e** [fonsp/Pluto.jl#3028]
In the following example, the variable `y` does not always get interpolated correctly and is instead interpreted as a math environment

```julia
let
	x = 1
	y = 2
	md"""
	This works: x = $x, y = $y
	
	but this doesnt: x = $x, y = ($y)

	adding a space after '(' fixes it: x = $x, y = ( $y)
	"""
end
```
Screenshot:
![image](https://github.com/user-attachments/assets/e9ac50d2-ab68-4c2a-a419-71d9e3b48145)

------
Julia v1.10.5, Pluto v0.19.46

**Comment by Pangoraw** [comment]
This seems to be a problem with the Markdown stdlib as it reproduces in the repl:

```julia
julia> let
               x = 1
               y = 2
               md"""
               This works: x = $x, y = $y

               but this doesnt: x = $x, y = ($y)

               adding a space after '(' fixes it: x = $x, y = ( $y)
               """
       end
  This works: x = 1, y = 2

  but this doesnt: x = x, y = (y)

  adding a space after '(' fixes it: x = 1, y = ( 2)
```

Presumably there is ambiguity around parsing `$y` and inline math equations.

**Comment by haakon-e** [comment]
Thanks, reposted the issue here: https://github.com/JuliaLang/julia/issues/55943
