### ISSUE TITLE
Use of JuliaMono...Latin fonts

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#3029]
I wanted to check about the current usage in Pluto of the JuliaMono-"Latin" fonts, ie:

JuliaMono-RegularLatin.ttf
JuliaMono-BoldLatin.ttf
JuliaMono-RegularLatin.woff2
JuliaMono-BoldLatin.woff2

(The original idea behind making these (https://github.com/cormullion/juliamono/issues/24) was to reduce load times.)

Are you using both the .ttf and the .woff2 versions? Are you using the CSS unicode-range to download a subset of the complete font or a subset of the Latin font? And do you access the Latin fonts in the ZIP file juliamono-ttf.zip at all?

The reason for asking is to find out how the -Latin fonts are used. I've seen a number of (non-Pluto) issues with people accidentally installing the Latin fonts and wondering why they have problems. If I can streamline anything without disturbing Pluto, it would be good.

(from https://github.com/fonsp/Pluto.jl/discussions/3025)

**Comment by fonsp** [comment]
Hey Cormullion! I wrote a reply in https://github.com/fonsp/Pluto.jl/discussions/3025 :)
