### ISSUE TITLE
Pluto cannot be started with Latest Julia 1.11.0-RC4

### ISSUE THREAD

**Issue by donovaly** [fonsp/Pluto.jl#3031]
I am new to Julia and I read that I should start using Pluto for notebooks like JuPyter.

I followed the instructions here:
https://www.youtube.com/watch?v=OOjKEgbt8AI
but cannot get Pluto to run:

1. withing the Julia REPL I execute
`import Pluto`
and get this error:
`ERROR: InitError: MethodError: no method matching
Stacktrace:
  [1] __init__()
    @ REPLExt J:\Julia-1.11\share\julia\stdlib\v1.11\Pkg\ext\REPLExt\REPLExt.jl:305
  [2]
SYSTEM (REPL): showing an error caused an error
ERROR: TypeError:
Stacktrace:
  [1] active_module()
    @ REPL J:\Julia-1.11\share\julia\stdlib\v1.11\REPL\src\REPL.jl:593
  [2] #invokelatest#2
    @ .\essentials.jl:1054 [inlined]
  [3] invokelatest
    @ .\essentials.jl:1051 [inlined]
  [4] active_module
    @ .\show.jl:519 [inlined]
  [5]
SYSTEM (REPL): caught exception of type TypeError while trying to handle a nested exception; giving up`

The strange thing is that when I don't do anything else than to repeat the command, it succeeds. As I am new to Julia I have no clue about the error message and why it only occurs the first time.

Next error:

1. in the linked video they say to run Pluto I should execute this command:
`Pluto.run()`
But no matter what I try, as soon as I enter the opening parentheses, I get tons of garbage output in the REPLS in an endless loop:
```
Base.Dict{Char, Any}(slots=Memory{UInt8}(16, 00000239efe58650)[0x00, 0xa5, 0xd0, 0x00, 0x00, 0x00, 0xd4, 0x00, 0xb5, 0x00, 0x00, 0xb3, 0x00, 0x00, 0x00, 0x00], keys=Memory{Char}(16, 00000239efe51f40)[Char(0x00000000), Char(0x30000000), Char(0x7e000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x68000000), Char(0x00000000), Char(0x6c000000), Char(0x00000000), Char(0x00000000), Char(0xf48f9fbf), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000)], vals=Memory{Any}(16, 00000239f02b1420)[
  #<null>,
  Base.Dict{Char, Any}(slots=Memory{UInt8}(16, 00000239efe58a40)[0x00, 0xa5, 0x00, 0x00, 0x00, 0x00, 0xd4, 0x00, 0xb5, 0x00, 0x00, 0xb3, 0x00, 0x00, 0x00, 0x00], keys=Memory{Char}(16, 00000239efe527e0)[Char(0x00000000), Char(0x30000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x68000000), Char(0x00000000), Char(0x6c000000), Char(0x00000000), Char(0x00000000), Char(0xf48f9fbf), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000)], vals=Memory{Any}(16, 00000239f02b2140)[
  #<null>,
  Base.Dict{Char, Any}(slots=Memory{UInt8}(16, 00000239efe58b00)[0x00, 0x00, 0xd0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], keys=Memory{Char}(16, 00000239efe529c0)[Char(0x00000000), Char(0x00000000), Char(0x7e000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000), Char(0x00000000)], vals=Memory{Any}(16, 00000239f02b23c0)[#<null>, #<null>, REPL.LineEdit.var"#81#112"(), #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>, #<null>], ndel=0, count=1, age=0x0000000000000002, idxfloor=1, maxprobe=0),
```

Even when I try to paste the command
`Pluto.run()`
to the REPL, I get the same.

As last resort,  I first entered the  `)` and then the `Pluto.run(`
This works and Pluto starts and I can use it.

I cost me about an hour to find this trick. Something is definitely wrong.
I am on
`v"1.11.0-rc4"`
under
Windows 10, 64 bit.
Julia was installed for the current Windows user (not for all users of the PC).

**Comment by donovaly** [comment]
In case this is a bug in Julia, please tell me that I can report it there. I am a newbie and lack the knowledge to decide where the bug comes from as looking into the *.jl files doesn't tell me yet anything valuable.

**Comment by cormullion** [comment]
Do you have similar issues with the current Julia release, 1.10? (1.11 has not yet been released.)

**Comment by donovaly** [comment]
> Pluto works best on the **latest julia version** (check https://julialang.org/downloads/ to find out). Future preview versions do not always work well.

I don't understand. The usual way is that a release candidate can become the final version every day. Also release candidates are meant that package maintainers can test on a code that won't be changed, other than bug fixes. (take e.g. LibreOffice or FreeCAD).

Here I use the fourth release candidate, so when I cannot report bugs for a release candidate, but e.g. Julia decides tomorrow that its RC4 is stable and thus becomes the final version, then Pluto does not run with Julia 1.11.

**Comment by cormullion** [comment]
Well I think you’re right, in theory at least, for a single package …. But, there are  over 10,000 Julia packages, and many of the bigger packages have many hundreds of dependencies - so it would be impressive if every single package in the ecosystem was  updated for compatibility at exactly the same instant in time. In open source, that’s less likely 😀

Personally I would always use the current release unless I was specifically testing a package of mine for compatibility.

**Comment by donovaly** [comment]
as a newbie; I read:
https://discourse.julialang.org/t/julia-v1-11-0-rc4-is-now-available/119888

> it’s intended to give users, especially package developers, a chance to try out their code with 1.11.0 prior to a full release

And I think Pluto is only one package, not a set of packages, right?

However, what will Pluto do when Julia decides RC 4 stable and becomes the final release? Then Pluto won't work with a production-ready Julia release.

**Comment by donovaly** [comment]
Anyway, when I use Julia 1.10.5 (on another Won 10 PC), this bug does not occur, so unless there is a bug in Julia, it must be Pluto.

However, the bug only occurs with Pluto. For other packages, I can type in "(" in the REPL and nothing happens, I can type in a closing ")"

**Comment by donovaly** [comment]
> However, what will Pluto do when Julia decides RC 4 stable and becomes the final release? Then Pluto won't work with a production-ready Julia release.

And this happened now. Yesterday Julia set the 1.11 release tag:
https://github.com/JuliaLang/julia/tree/release-1.11
so anytime there might be the announcement.

**Comment by cormullion** [comment]
> >  Pluto won't work with a production-ready Julia release.

By the way, Pluto 0.19 works fine with the current Julia release candidate - on MacOS:

<img width="802" alt="Screenshot 2024-10-02 at 20 10 19" src="https://github.com/user-attachments/assets/bcd86c32-49d7-45fc-9ec4-daaa6c7d17db">

So you may have an installation problem, or perhaps it's a Windows issue - it's less likely to be a general "Pluto doesn't work with the Julia 1.11 Release Candidate issue"...

**Comment by fonsp** [comment]
Thanks for testing @cormullion! Since it happens before you actually run `Pluto.run()`, it's a Julia/REPL/Windows issue. 

@donovaly I recommend making a video screen recording of what you describe, and reporting it to https://github.com/JuliaLang/julia
