### ISSUE TITLE
Pluto cannot change to another notebook.

### ISSUE THREAD

**Issue by donovaly** [fonsp/Pluto.jl#3033]
I run a Pluto notebook and then want to change to another one. Pluto offers in its header to change to another notebook, however, this does not work:
![firefox_eywQ5SpIJF](https://github.com/user-attachments/assets/24a60104-bd40-4586-8344-a0f9fcf403cf)

I tried it several times, it is impossible to change to another notebook. Pluto tells me it succeeded, but I still the old notebook. It is super annoying that I have to close Pluto, then restart it just to get another notebook.

I use Julia 1.11RC4 under Windows 10 64bit and latest Pluto.

**Comment by cstjean** [comment]
It's a bit non-obvious, but you can click (or ctrl-click) on the Pluto.jl icon in the top-left to go back to the main page. From there you can open any notebook.

**Comment by fonsp** [comment]
Normally you get a popup message showing the error when moving into an existing path:

![image](https://github.com/user-attachments/assets/e0a03207-59d1-4d19-b657-9916a3ad8c45)

But this is not working on your computer. @donovaly What browser do you use? Can you try this again with another browser (Chrome vs Firefox) and check if you get the error mesage?

**Comment by donovaly** [comment]
OK, first now I understand what the "Move" feature tries to do - it wants to move the current notebook to a given location.

I thought it will move ME to another notebook, so that I can change to another notebook.

However, as the path i gave leads to an existing file, the move cannot be done. My popup blocker in the browser blocks the error message. Turning off the popup blocker I see the error.

So closing. However, I think the UI could be improved by renaming the "Move" button to "Save as" or "Save under".

**Comment by donovaly** [comment]
FYI. I use Firefox 131.
