### ISSUE TITLE
Pluto crashes on closing

### ISSUE THREAD

**Issue by donovaly** [fonsp/Pluto.jl#3036]
In Julia's REPL I started Pluto, and there I read:

`Info:
│ Press Ctrl+C in this terminal to stop Pluto`

But when I do this, I get this error
```
fatal: error thrown and no exception handler available.
InterruptException()
_jl_mutex_unlock at C:/workdir/src\threading.c:949
jl_mutex_unlock at C:/workdir/src\julia_locks.h:80 [inlined]
ijl_task_get_next at C:/workdir/src\scheduler.c:526
poptask at .\task.jl:1012
wait at .\task.jl:1021
task_done_hook at .\task.jl:694
jfptr_task_done_hook_67126.1 at J:\Julia-1.11\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_finish_task at C:/workdir/src\task.c:319
start_task at C:/workdir/src\task.c:1213
```

This is strange as I am on Windows. There is no such directory `C:/workdir` and it can also not be created as one would need admin permissions to do so. So also the error message is wrong.

I use Julia 1.11RC4 under Windows 10 RC4.

I tried to close Pluto also directly after I started, so no notebook was ever loaded or run but the bug persists.

**Comment by donovaly** [comment]
> Did Pluto exit?

I don't know. The browser tab (Firefox) is still open and does not accept inputs. So the server was shut down but it can be because of the crash.

> What happens when you press Ctrl+C again?

Julia outputs just:
`^C`

> For the C:/workdir issue, you could make an issue in https://github.com/JuliaLang/julia/issues

Done: https://github.com/JuliaLang/julia/issues/55957
It seems the problem is that I use the `JULIA_DEPOT_PATH` environment variable.

**Comment by fonsp** [comment]
Maybe you could record a video the next time this happens! I'm not sure we can improve this without a video.

**Comment by donovaly** [comment]
> Maybe you could record a video the next time this happens! I'm not sure we can improve this without a video.

Here you are:
![julia_uOxdRe2MdP](https://github.com/user-attachments/assets/5a5d1710-bd3e-45a9-b2d3-399516d160c3)

This is with Julia 1.11.1 and I performed an update, gc and instantiate before I started Pluto. Now the crash is gone. Only this message in the REPL sounds weird:

```
fatal: error thrown and no exception handler available.
InterruptException()
```

because there is no fatal error as Pluto is shut don the normal way.

For reference here the full REPL output:

```
julia> Pluto.run()
[ Info: Loading...
┌ Info:
└ Opening http://localhost:1234/?secret=IQNZaohK in your default browser... ~ have fun!
┌ Info:
│ Press Ctrl+C in this terminal to stop Pluto
└
fatal: error thrown and no exception handler available.
InterruptException()


┌ Info:
│ Closing Pluto... Restart Julia for a fresh session.
│
│ Have a nice day! 🎈
└
_jl_mutex_unlock at C:/workdir/src\threading.c:949
jl_mutex_unlock at C:/workdir/src\julia_locks.h:80 [inlined]
ijl_task_get_next at C:/workdir/src\scheduler.c:526
poptask at .\task.jl:1012
wait at .\task.jl:1021
task_done_hook at .\task.jl:694
jfptr_task_done_hook_67171.1 at J:\Julia-1.11\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_finish_task at C:/workdir/src\task.c:319
start_task at C:/workdir/src\task.c:1213

julia>
```

Despite the misleading message about a fatal error, I would say the issue is resolved.
