### ISSUE TITLE
Jump-to-definition for variables

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#304]
Easy to add in, because Pluto already has the list of which variables are defined where, but disproportionally difficult is:

- Shadowed variables, i.e. the second `x` in `f(x) = x` does not refer to the global `x`. 
- Local variables (defined in the same cell).

Pluto understands both cases, but that information is not linked to a line number - it's accumulated at the cell level.

The same shortcut as VS Code: Ctrl+Click.

**Comment by fonsp** [comment]
Needs the same mechanism as #13

**Comment by fonsp** [comment]
@pfitzseb do you have any tips for making the string index available inside the AST? Does that question make sense?

**Comment by pfitzseb** [comment]
The question makes sense, but it's also why CSTParser exists: To get a syntax tree with column/line info available (and one that is round-trippable).

StaticLint.jl has everything you'd need here, I think, but I'm not 100% sure how easy it is to interface with. Juno also supports this just based on CSTParser (see the code [here](https://github.com/JunoLab/Atom.jl/tree/master/src/static)).

**Comment by fonsp** [comment]
Thanks for the Juno link - this looks similar to what I have written so far ([ExpressionExplorer.jl](https://github.com/fonsp/Pluto.jl/blob/v0.11.6/src/analysis/ExpressionExplorer.jl#L244)), with metadata on top of just tracking `Symbol`s. I will look into it more!
