### ISSUE TITLE
Issue with plotting using `PGFPlotsX` package

### ISSUE THREAD

**Issue by Shuvomoy** [fonsp/Pluto.jl#305]
I am having trouble using `PGFPlotsX` in `Pluto.jl`, where `Pluto` is treating the plotting options as variables. For example in the following code, I get the error: `Multiple definitions for color, ylabel, xlabel and style...`, where `color, ylabel, xlabel` and `style` are actually plotting options. Any suggestions will be much appreciated. 

**Code:**
```
### A Pluto.jl notebook ###
# v0.11.6

using Markdown
using InteractiveUtils

# ╔═╡ cd9b4200-df0b-11ea-3a3b-c964e8cf6424
using PGFPlotsX

# ╔═╡ e7cf7ab0-df0b-11ea-392f-39470a7f7aa7
x = range(0.1,stop=5, length = 50)

# ╔═╡ ef13ada0-df0b-11ea-022b-21527f60c34e
y = x.^2

# ╔═╡ 45d044a0-df0c-11ea-319b-39df7aaf2846
z = x.^3

# ╔═╡ f45fba10-df0b-11ea-22b0-919a73ead86c
plot1 = @pgf Axis(
    {
        xlabel = "x",  
        ylabel = "x squared" 
    },
    Plot(
        {
            style = "{ultra thick}",
            color = "blue" 
        },
        Coordinates(x, y)
    )
)


# ╔═╡ 4ca33f30-df0c-11ea-30ee-1f96d633bbdb
plot2 = @pgf Axis(
    {
        xlabel = "x",  
        ylabel = "x cubed" 
    },
    Plot(        
		{
            style = "{ultra thick}",
            color = "blue" 
        },
        Coordinates(x, z)
    )
)


# ╔═╡ Cell order:
# ╠═cd9b4200-df0b-11ea-3a3b-c964e8cf6424
# ╠═e7cf7ab0-df0b-11ea-392f-39470a7f7aa7
# ╠═ef13ada0-df0b-11ea-022b-21527f60c34e
# ╠═45d044a0-df0c-11ea-319b-39df7aaf2846
# ╠═f45fba10-df0b-11ea-22b0-919a73ead86c
# ╠═4ca33f30-df0c-11ea-30ee-1f96d633bbdb

```

**Comment by fonsp** [comment]
Unfortunately you need to use `=>` or `:` instead of `=` inside the `{ ... }` block.

https://kristofferc.github.io/PGFPlotsX.jl/stable/man/options.html#The-@pgf-macro-1

**Comment by fonsp** [comment]
Actually - how does the PGFPlotsX look inside Pluto? Is it nice? Could you post a screenshot?

**Comment by Shuvomoy** [comment]
> Actually - how does the PGFPlotsX look inside Pluto? Is it nice? Could you post a screenshot?

It looks absolutely fantastic, here is a sample screenshot: 

![image](https://user-images.githubusercontent.com/10360118/90447797-0a4f6f80-e0b2-11ea-98df-65422046c51a.png)

**Comment by fonsp** [comment]
Wow indeed! Thanks for sharing

**Comment by fonsp** [comment]
#196
