### ISSUE TITLE
Pluto.jl does not support Julia 1.0.4, only 1.0.5 and up

### ISSUE THREAD

**Issue by ehildebrandtrojo** [fonsp/Pluto.jl#306]
I followed the installation guide for Pluto.jl. Unfortunately, when I try to run the notebook using Pluto.run(1234) I get the following error:
```
ERROR: MethodError: no method matching run(::Int64)
Closest candidates are:
  run(::Base.AbstractCmd, ::Any...; wait) at process.jl:661
Stacktrace:
 [1] top-level scope at none:0
```
Im sure there's an easy fix, but I'm not sure what to do. Any help would be greatly appreciated!

**Comment by fonsp** [comment]
Sorry for the confusion! It's two separate commands:

```julia
julia> using Pluto

julia> Pluto.run(1234)
```

let us know if that worked

**Comment by ehildebrandtrojo** [comment]
Yeah, I tried that before. Sorry should have been more clear about that. By the wya, I'm running Julia 1.0.3. I dont know if that has any influence.

![Screen Shot 2020-08-17 at 5 36 02 PM](https://user-images.githubusercontent.com/22646052/90457392-3cf86880-e0b0-11ea-84ed-f219ab98b0fb.png)

**Comment by fonsp** [comment]
Unfortunately that's not a supported version - you are likely locked to an old version of Pluto that still supported it.

If possible, I recommend that you install Julia `v1.5.0`, or if you need to use `v1.0.*`, then you can install `v1.0.5`, which will work with Pluto.

https://julialang.org/downloads/

**Comment by ehildebrandtrojo** [comment]
I see. Thanks! I download Julia through anaconda, so that's why I had that version. Do you know by any chance when they'll update the anaconda version of julia?

**Comment by fonsp** [comment]
It sounds like they never update Julia.

But try Julia `v1.5`, it's much faster, all packages will work correctly and you will generally have a nicer time. It is very easy to install from the julialang.org/downloads page

**Comment by ehildebrandtrojo** [comment]
Alright, will do! Thank you for your help!

**Comment by fonsp** [comment]
Sure thing, enjoy your time with Julia!
