### ISSUE TITLE
"Multiple definitions" error message on `begin ... end` is misleading

### ISSUE THREAD

**Issue by laggvar** [fonsp/Pluto.jl#3061]
This error message is quite confusing:

![image](https://github.com/user-attachments/assets/3a59104d-f3f3-4f8c-b68c-85a1ed9423e8)

By renaming `a` in one of the two cells, the error disappears, so there is nothing wrong with `Base`. But this can be quite difficult to troubleshoot in more complex scenarios. 

It gets even stranger when renaming the variable to `c` Then the error only mentions `Base` and not the variable with the actual error. This seems to happen when using the names `c` or `e` but not `a`, `b` , `d` or `f`. 

![image](https://github.com/user-attachments/assets/99346b63-0042-49c0-a8b7-90e91644a227)

Tested in Pluto 0.20.0 / Julia 1.11 and partially in Pluto 0.19.40 / Julia 1.9.3.

**Comment by fonsp** [comment]
Woww so weird that it depends on which letter you use!! What is that about 🙈

**Comment by fonsp** [comment]
It looks like the problem is with the `.` in `Base.zero`: here is one message where `cee` shows, and one where `ceee` does not show:

<img width="685" alt="image" src="https://github.com/user-attachments/assets/ab829c2e-3821-4aae-9889-801c553b6c9b">

The randomness is caused by set ordering of the symbol names :)

**Comment by fonsp** [comment]
I fixed the error message display, it now looks like this (no matter the variable name):

<img width="410" alt="image" src="https://github.com/user-attachments/assets/0b5afe69-83b1-4f2d-bc88-3314ec50dbc0">

Now it also shows `Base.zero` instead of just `Base`

**Comment by fonsp** [comment]
I improved the error message in https://github.com/fonsp/Pluto.jl/issues/3061
