### ISSUE TITLE
Within the Pluto notebook `isinteractive()` returns `false`

### ISSUE THREAD

**Issue by vojtamolda** [fonsp/Pluto.jl#3074]
Dear developers here,

First, thanks a lot for creating such a nice package! It's probably my favorite Julia project.

When moving over some of my work from REPL, I noticed that the return value from `isinteractive()` is always `false` within the notebook. I think this is a bug because the standard Julia REPL returns `true` and I believe the Pluto notebooks are very interactive :)

---

I've attached a screenshot and the actual notebook file for reproducing the problem.

<img width="844" alt="interactive_bug" src="https://github.com/user-attachments/assets/43e1f284-d382-4239-a071-76c533fb73e6">

- [`interactive_bug.jl.zip`](https://github.com/user-attachments/files/17498864/interactive_bug.jl.zip)

**Comment by cstjean** [comment]
It's not clear what `isinteractive` is supposed to imply (and what it's meant to be used for), but IMO an interactive session should support `readline`, which Pluto does not.
![{46050D30-2BBF-4A0A-A6A6-45CDDD4DD538}](https://github.com/user-attachments/assets/5e1475d3-a04a-4f2a-adda-859a82153ca0)

**Comment by vojtamolda** [comment]
Thanks for the response. Yeah, you're probably right. I just checked and Jupyter notebooks return the same value. So this probably isn't a bug.

<img width="707" alt="Screenshot 2024-10-23 at 8 28 24 PM" src="https://github.com/user-attachments/assets/8be399b2-1ee5-415b-a5bd-1a3a12abdeca">

---

On a more general level, is there a way for a piece of code to tell that it's running in a Pluto.jl notebook?

**Comment by cstjean** [comment]
Check "Not really hooks but internally very hook-ish" in [PlutoHooks](https://juliapluto.github.io/PlutoHooks.jl/src/notebook.html)

**Comment by pankgeorg** [comment]
Thanks for the report! I'll close this for now, but keep the reports coming; we love hearing from you! ❤️ 🎉

**Comment by vojtamolda** [comment]
Yep. Makes total sense to close this. Thanks for your help gentlemen!

**Comment by fonsp** [comment]
The official API is https://plutojl.org/en/docs/abstractplutodingetjes/#is_inside_pluto

**Comment by fonsp** [comment]
To answer the original question, Pluto is indeed interactive 🐣 but `Base.isinteractive()` is supposed to return: "is this Julia process in a TTY terminal with user input"? And the answer in Pluto is no, since we have no `stdin` (because that is very hard to implement in a sensible way).
