### ISSUE TITLE
redirect worker process stdout to notebook?

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#308]
Currently Pluto use a worker process to execute the notebook's cell, however, the stdout is not redirected as a result, when you run things like `Pkg.status()`, nothing will appear in the notebook (but it will print in jupyter notebook), I'm wondering if it's possible to redirect the stdout to notebook output in some way as plain text?

**Comment by fonsp** [comment]
For simple `Pkg` operations:

```julia
Text(sprint(io -> Pkg.something(; io=io)))
```

If you have multiple lines:

```julia
sprint() do io
	Pkg.status(;io=io)
	println(io, "Hello!")
end |> Text
```

You can probably make something nicer with `redirect_stdout`, maybe someone else can experiment with that?

**Comment by fonsp** [comment]
About making this built-in, see #245

**Comment by Roger-luo** [comment]
I see. Yeah, #245 seems to be what I want, thanks!
