### ISSUE TITLE
Overeager autocomplete for `@.` gives `@__DOT__.`

### ISSUE THREAD

**Issue by haakon-e** [fonsp/Pluto.jl#3086]
Cross-posted from #pluto channel in slack.

I'm on Pluto v0.20.3 (but feel like it's been like this for a few versions), and notice consistently that `@.` autocomplete to `@__DIR__.`, unless I type the `.` very quickly after typing `@.` Has anyone else noticed this?
(in the movie I only type `@` then `.` , but do so either "slowly" or "quickly")

https://github.com/user-attachments/assets/4d26314b-d8b6-480a-926e-80d4bfd42283

-----
ref: #3008, #3055

**Comment by fonsp** [comment]
I'm looking for more autocomplete bugs! Did you find any other cases where autocomplete gave an unexpected result? Please send me a video!
