### ISSUE TITLE
Bundled MathJAX?

### ISSUE THREAD

**Issue by ctessum** [fonsp/Pluto.jl#3094]
Hello,

Apologies for not including a video, I don't want to be that guy, but I really feel like this issue will be explainable without one.

The situation, on which I think everyone can agree, is that Pluto gets its MathJax script from `cdn.jsdelivr.net`. Here is the relevant section from the sources tab of the chrome browser console:

![image](https://github.com/user-attachments/assets/a4fd8c0b-130f-4ac2-82da-501bbc3d5575)

This is, of course, a normal thing to do, but I am currently using Pluto in to teach a class where we have exams in [special computer labs](https://cbtf.illinois.edu/) where the computers have firewalled off most of the internet, to discourage cheating.

As you might guess, the problem is that `cdn.jsdelivr.net` is not on the whitelist, so the equations don't get rendered in the notebooks, which causes the students taking the exam to be very anxious.

So my question is, would it be possible to bundle mathjax in with Pluto, which should solve this firewall problem? (I am told that JupyterLab already does this, and Jupyter notebooks don't have any problems rendering equations in these computer labs.)

Thanks for you consideration!

**Comment by fonsp** [comment]
Hey @ctessum ! This was actually fixed by https://github.com/fonsp/Pluto.jl/pull/3091 recently! So it will be fixed in the next release, should be within 2 weeks :)

**Comment by fonsp** [comment]
When is the exam?

**Comment by ctessum** [comment]
Thanks! The exam is today 😅. But there is also one next week and the week after so the change is appreciated.

**Comment by fonsp** [comment]
Okay! In that case I'll do a release right now

**Comment by ctessum** [comment]
Thanks!

**Comment by fonsp** [comment]
Whoops I need to fix https://github.com/fonsp/Pluto.jl/issues/3095 before I can release, I'll try tomorrow

**Comment by fonsp** [comment]
Sorry for the delay @ctessum! https://github.com/fonsp/Pluto.jl/issues/3095 was more difficult than I expected...

How did the exams go?
