### ISSUE TITLE
Pluto does not delete its temp folders

### ISSUE THREAD

**Issue by donovaly** [fonsp/Pluto.jl#3097]
As also reported in #3035, on every start Pluto creates a Tamp folder. In my case it is a folder like

C:\Users<username>\AppData\Local\Temp\jl_BJkWpS

The bug is that after ending the Pluto server by pressing Ctrl+C in the REPL, this temp folder is not deleted. I have now dozeons of these folders each containing Manifest.toml and a Project.toml

**Comment by fonsp** [comment]
Hey @donovaly ! It sounds like you are learning about Julia and Pluto, which is great! 

When these questions come up, it might be more helpful to ask them in the Julia forums (discourse, zulip, slack) rather than posting them as Issues on Pluto.

**Comment by donovaly** [comment]
Why do you close this? I reported a bug I could reproduce on different PCs. A program must delete its Temp folders when it is closed. Pluto does not do this.

> When these questions come up,

I reported a reproducible bug, and did not ask a question
You also closed my bug report as "not planned". So you it is a planned "feature" that Pluto pollutes the temp folder? I cannot follow your logic.

**Comment by donovaly** [comment]
> Pluto doesn't automatically remove the temp files because for a lot of users this acts like a backup. This is the exact reason why Microsoft also doesn't remove files from %temp% there automatically.

The Windows guidelines say that programs that created files in the user's temp folder should remove it. This is the common "good practice", as you can also find at various places:
[Windows programming guidelines: Does a Program have to delete the files it wrote to the the user's temp folder when it is closed?](https://www.google.com/search?q=Windows+programming+guidelines%3A+Does+a+Program+have+to+delete+the+files+it+wrote+to+the+the+user%27s+temp+folder+when+it+is+closed%3F&sca_esv=ab56b00da05de27d&hl=en&ei=qgg8Z8jYDLSXxc8P_duGmAk&ved=0ahUKEwjI1dzZvOeJAxW0S_EDHf2tAZMQ4dUDCA8&uact=5&oq=Windows+programming+guidelines%3A+Does+a+Program+have+to+delete+the+files+it+wrote+to+the+the+user%27s+temp+folder+when+it+is+closed%3F&gs_lp=Egxnd3Mtd2l6LXNlcnAigQFXaW5kb3dzIHByb2dyYW1taW5nIGd1aWRlbGluZXM6IERvZXMgYSBQcm9ncmFtIGhhdmUgdG8gZGVsZXRlIHRoZSBmaWxlcyBpdCB3cm90ZSB0byB0aGUgdGhlIHVzZXIncyB0ZW1wIGZvbGRlciB3aGVuIGl0IGlzIGNsb3NlZD9IAFAAWABwAHgBkAEAmAEAoAEAqgEAuAEDyAEA-AEBmAIAoAIAmAMAkgcAoAcA&sclient=gws-wiz-serp)

For backups there should be backup folder. For example for FreeCAD we therefore create for backups a dedicated backup folder. The users can set any folder he likes as backup folder. Our default is
`C:/Users/<username>/AppData/Local/cache/FreeCAD/Cache/`

> If you have a different reason you want these files removed

To keep the system clean. All projects I am or was involved in we cleaned the Temp folder on closing the program (or on uninstalling).
As stated above, it is good practice because imagine all the many programs you have installed don't delete their temp folders? I have many programs installed and Pluto is besides Visual Studio (not VS Code) the only one I see that does not remove the folders it created in the the User's Temp folder. For Visual Studio that started with the latest update, is probably a bug

**Comment by pankgeorg** [comment]
I'm aware of what Microsoft asks the developers to do. But let's be honest here, if Microsoft believed the developers, they would clear the `%temp%` folder themselves on every restart, maybe even more often. They don't. We also don't. Everyone is happy with that. Pluto is a frontend project, so this is quite low on our priority list. Feel free to submit a PR though!

**Comment by donovaly** [comment]
> Everyone is happy with that. Pluto is a frontend project,

I came to Pluto because it is a frontend project. And I am not happy about it, otherwise I would not have filed this bug report.

My proposal: Allow users to specify a custom folder as backup folder. This would be more intuitive because then it is clear that

- a backup is made
- where the backup folder is

p.s. saying "we don't care about the common good practice" is not a good behavior. I am a developer too, do this in my spare time and most of my colleagues don't use Windows at all, but we try to follow the best practices. When someone tells us we don't do, we at least evaluate this.

**Comment by pankgeorg** [comment]
> And I am not happy about it, otherwise I would not have filed this bug report.

Thank you for the input. Note that this software is provided as is, without warranty of any kind (see the [license](https://github.com/fonsp/Pluto.jl/blob/main/LICENSE#L15-L21)).

> My proposal: Allow users to specify a custom folder as backup folder.

This is a good proposal. We'll happily evaluate a PR if someone finds the time to implement it. As Fons proposed above, we would expect the fix for the `mkdir()` method to be somewhere in `julia` itself, but we're open to reconsider this if a good, local solution is proposed (in the form of a PR). Unfortunately, we don't have enough bandwidth to focus on this right now.

> p.s. saying "we don't care about the common good practice" is not a good behavior.

If you feel we have insulted you in any way, please feel free to follow the code of conduct provisions both for [this project](https://github.com/fonsp/Pluto.jl/blob/main/CODE_OF_CONDUCT.md) and Julia Community [here](https://julialang.org/community/standards/).

I hope we can resolve the issue soon!
