### ISSUE TITLE
ResumableFunctions don't work in Pluto.jl

### ISSUE THREAD

**Issue by ahjulstad** [fonsp/Pluto.jl#3104]
I want to use the ResumableFunctions package from Pluto in order to do simulations with ConcurrentSim. 

I get error messages 

```
UndefVarError: `##236` not defined in `Main.var"workspace#6"`
Suggestion: check for spelling errors or missing imports.
```

when running the attached script.   

https://github.com/user-attachments/assets/4aef38e4-6a6a-44ca-8e83-f845bbc31b4e

https://gist.github.com/ahjulstad/5e040091ba2e8e7b3b540d3396421456

I can run the script outside of Pluto just fine. 

Mentioned to the developer of the package here: https://github.com/JuliaDynamics/ResumableFunctions.jl/issues/111

**Comment by Krastanov** [comment]
Thanks for posting this in both repos -- the feedback from @fonsp was extremely helpful. I believe it is reasonable to close the issue here and follow their suggestions for the fix (or more of an improvement) to be done in ResumableFunctions

**Comment by ahjulstad** [comment]
Thank you, both of you. For me as a user, getting quality support like this just keeps amazing me. 

Closing the issue.
