### ISSUE TITLE
Featured Heatmap notebook is broken

### ISSUE THREAD

**Issue by abpolym** [fonsp/Pluto.jl#3109]
The [heatmap / 3D plot notebook](https://featured.plutojl.org/plot/heatmap.html) does not work anymore:

https://github.com/user-attachments/assets/22db5be0-8c07-4517-b45c-2d8e5e238d87

Opening the console yields the following error:

<img width="746" alt="1" src="https://github.com/user-attachments/assets/1237a475-58f4-452a-bb25-e95faaced4e2">

**Comment by fonsp** [comment]
Looks like the statefile is corrupt:

![image](https://github.com/user-attachments/assets/c9991257-7e03-4698-98a1-dfaddcda48d1)


This is the same as https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/108, but our state-caching system was not covered by that fix.
