### ISSUE TITLE
LaTeXString in markdown block has extra L" "

### ISSUE THREAD

**Issue by Moelf** [fonsp/Pluto.jl#313]
I tried:
```
using LaTeXString
SC = L"i\hbar\frac{\partial}{\partial t} \Psi(\mathbf{r},t) = \left [ \frac{-\hbar^2}{2m}\nabla^2 + V(\mathbf{r},t)\right ] \Psi(\mathbf{r},t)"

md"""
$SC
"""
```
when interpolated in markdown, there's a slight bug:
![image](https://user-images.githubusercontent.com/5306213/90964323-84ef0500-e48d-11ea-9f4c-9f9d626727af.png)

Notice the extra `L" "`

_Originally posted by @Moelf in https://github.com/fonsp/Pluto.jl/issues/118#issuecomment-678683619_

**Comment by fonsp** [comment]
LaTeXString does not support being included inside Markdown. (You should open an issue with them.) The reason that you still see formatted latex is a lucky glitch in Pluto.
