### ISSUE TITLE
UndefVarError

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#314]
This cell content gives an UndefVarError in Pluto, yet returns the expected 1 in the REPL.
(Is there an alternative way to change a variable like maxOccurences here in a loop? That would be appreciated also.)

     begin
      	dd = Dict{String, Int64}()
     	dd["huhu"] = 1
     	maxOccurences = 0
     	for w in keys(dd)
     		if dd[w] > maxOccurences
     			maxOccurences = dd[w]
     		end
     	end
     	maxOccurences
     end

(Julia 1.5, Pluto 0.11.8)

**Comment by fonsp** [comment]
Or `local`:
```julia
 let
 	dd = Dict{String, Int64}()
 	dd["huhu"] = 1
 	local maxOccurences = 0
 	for w in keys(dd)
  		if dd[w] > maxOccurences
  			maxOccurences = dd[w]
 		end
 	end
 	maxOccurences
 end
```

**Comment by zenon** [comment]
Ah. Thank you :-)
