### ISSUE TITLE
The markdown used in Pluto notebooks doesn't render/support HTML tags

### ISSUE THREAD

**Issue by Masacroso** [fonsp/Pluto.jl#315]
As the title says: the markdown cells doesn't render HTML tags, by example the tag &lt;small&gt; and many others doesn't work, however support for HTML tags is an specification of the [original markdown](https://daringfireball.net/projects/markdown/syntax#html).

P.S.: the markdown used here in GITHUB support HTML tags.

**Comment by Sh4pe** [comment]
This appears to be a limitation of the Markdown package in the Julia stdlib, as you can see in the REPL:

```julia
julia> md"<b>foo</b>"
  <b>foo</b>
```

But note that you could use HTML as a workaround. Something like this works licely in Pluto:

![image](https://user-images.githubusercontent.com/146497/91411572-cfcf9a80-e848-11ea-9753-084f1bd654cb.png)

**Comment by Masacroso** [comment]
> This appears to be a limitation of the Markdown package in the Julia stdlib, as you can see in the REPL:
> 
> ```julia
> julia> md"<b>foo</b>"
>   <b>foo</b>
> ```
> 
> But note that you could use HTML as a workaround. Something like this works licely in Pluto:
> 
> ![image](https://user-images.githubusercontent.com/146497/91411572-cfcf9a80-e848-11ea-9753-084f1bd654cb.png)

Very nice! I will close this. But, can you gives some documentation about the syntax `blablabla |> HTML`, it is maybe a built-in function of Julia? Or there is something of Pluto?

**Comment by Sh4pe** [comment]
Note that `"blablabla" |> HTML` ist synonymous to just `HTML("blablabla")`.
