### ISSUE TITLE
Improper use of splat operator in destructuring assignment causes cell to load indefinitely

### ISSUE THREAD

**Issue by Pocket-titan** [fonsp/Pluto.jl#32]
The input
```julia
arr = [1,2,3]
(a,b...) = arr
```

outputs the syntax error

```diff
- ERROR: syntax: invalid assignment location "b..."
Stacktrace:
 [1] top-level scope at REPL[4]:1
```

in the Julia REPL, but when ran in Pluto causes the notebook cell to get stuck loading indefinitely & never displays an error:

<img width="735" alt="Screenshot 2020-03-23 at 14 21 40" src="https://user-images.githubusercontent.com/4435990/77320929-b1052f00-6d11-11ea-971a-17cbd1055a42.png">

**Comment by fonsp** [comment]
Same for 
```julia
1 = 2
```

**Comment by fonsp** [comment]
This is now [a testset 🦓](https://github.com/fonsp/Pluto.jl/blob/2b45b88335a102e6a9c98b8fbbf61a9ec71dbf3d/test/React.jl#L24-L35)
