### ISSUE TITLE
Types?

### ISSUE THREAD

**Issue by dojt** [fonsp/Pluto.jl#320]
When I type in the 2-line Pluto notebook in the screenshot below then save it, quit Pluto, end Julia, start Julia again, start Pluto again, load the notebook again -- I get the error message shown in the screenshot:

![image](https://user-images.githubusercontent.com/57910358/91319202-c7358080-e7c4-11ea-9302-38732a1f3b8d.png)

Julia console looks like this:
![image](https://user-images.githubusercontent.com/57910358/91319864-8ab65480-e7c5-11ea-93b7-9eedc101bcf2.png)

When I run the 2nd cell again, the problem disappears for this simple notebook. More complex notebooks cannot be fixed.

Julia v1.5.0
Pluto.jl v0.11.8

**Comment by fonsp** [comment]
Fixed in `0.11.9`

**Comment by fonsp** [comment]
This is now [a testset](https://github.com/fonsp/Pluto.jl/commit/f7ec03dbac8d46208cba6e600fd6d513f82b71c3#diff-2089b2016831147491e94b40cf551faaR192-R194) 🐦
