### ISSUE TITLE
Add name to a Bond

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#325]
Now we have the possibility of having the value next to a slider -- great!
It would be useful to have the name of the variable too.

**Comment by fonsp** [comment]
Yeah that's cool

**Comment by stillyslalom** [comment]
Maybe just a `label` field? I've been working around this with
```
begin
	var_slider = @bind var Slider(LinRange(0, 20, 1001), default=10)
	md"""
	A descriptive label for `var` $var_slider
	"""
end
```
![image](https://user-images.githubusercontent.com/4324760/92035004-b2606c00-ed33-11ea-97ff-7641c8293c3e.png)

**Comment by fonsp** [comment]
What do you mean?

**Comment by stillyslalom** [comment]
```
@bind var <binding> label="A descriptive label for `var`"
```

**Comment by fonsp** [comment]
Aha, for that you can use:
```julia
md"A descriptive label for `var` $(@bind var Slider(LinRange(0, 20, 1001), default=10))"
```

**Comment by stillyslalom** [comment]
I understand not wanting to add too much clutter to the `@bind` interface, but `label` is a [common](https://www.w3schools.com/tags/tag_label.asp) HTML tag with universal browser support; it also helps accessibility for screen readers.

**Comment by fonsp** [comment]
Ah now I get it

**Comment by fonsp** [comment]
You can use this:

```julia
# ╔═╡ 3027890b-196b-4a65-9f17-0180d21f6beb
using HypertextLiteral

# ╔═╡ 19da2136-a5e4-476e-95a9-853960e3a50f
macro label_bind(name::Symbol, ex::Expr)
    quote
        @htl("""
        <div style='display: flex;'>
        <code style='font-weight: bold'>$($(String(name)))</code>: $(@bind $(name) $(esc(ex)))
        </div>
        """)
    end
end
```

![image-1652964737328](https://user-images.githubusercontent.com/6933510/169297668-16479fc3-d03b-459d-bb0b-f9397c13ae4d.png)

**Comment by Pangoraw** [comment]
Now that there is https://github.com/JuliaPluto/PlutoUI.jl/pull/305, i am closing this. Feel free to reopen
