### ISSUE TITLE
`Ctrl+C` to copy localhost:1234 in the terminal stops Pluto

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#328]

**Comment by stillyslalom** [comment]
Could add a `clip=true` keyword argument to `Pluto.run` to use [`clipboard`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.clipboard) to send the address to the OS clipboard

**Comment by shashi** [comment]
which terminal emulator uses `Ctrl+C` for copy :scream:

**Comment by fonsp** [comment]
Haha no i meant that people can happily use `Ctrl+C` in every program to copy things around and then they open a terminal to start Pluto and this happens

**Comment by cmcaine** [comment]
Jupyter opens the web interface automatically and prompts if you press ctrl+c. I think that's a decent UX for people unfamiliar with terminals.

**Comment by fonsp** [comment]
Yeah true! This issue would be solved by #190
