### ISSUE TITLE
Add an `x` on the left too

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#331]
It is annoying to have to move the pointer all the way to the other side of the cell to delete it.
Could there be an `x` in the left margin too?

**Comment by fonsp** [comment]
Would a keyboard shortcut also make you happy?

**Comment by fonsp** [comment]
It's `Ctrl+Shift+Delete` right now I think but on Firefox that doesn't work :(

**Comment by dpsanders** [comment]
A keyboard shortcut would make me happy yes. No Delete key on Mac?

**Comment by fonsp** [comment]
The new shortcut is:

`Ctrl+A` or `Cmd+A` to select all code
`Backspace` or `Delete` to delete the code
`Backspace` or `Delete` again to delete the cell and move focus to the previous/next cell

**Comment by fonsp** [comment]
I will release the update soon :)

**Comment by fonsp** [comment]
@dpsanders Close this issue if you are happy with the new shortcuts :)

**Comment by dpsanders** [comment]
I personally don't actually like this. I tend to press backspace many times to delete stuff...

**Comment by evadknarf** [comment]
Yeah...had three four cells gone before I realised this change..

**Comment by fonsp** [comment]
What is `Shift+Del`?

**Comment by cmcaine** [comment]
A vim-inspired workflow might be to type ctrl-o to enter "normal (cell) mode" for one operation, then type Del or Backspace. This extends to other things, like ctrl-o UpArrow to move to the previous cell or whatever.

Shift-del or Shift-BS would work for me, too.

**Comment by fonsp** [comment]
Adding a duplicate button goes against Pluto's design philosophy, and the original issue (too cumbersome to delete a cell) was solved by the new backspace behavior.

Let's continue the criticism/alternatives to this new behavior in #408
