### ISSUE TITLE
Browser compat for min() in CSS

### ISSUE THREAD

**Issue by billw1955** [fonsp/Pluto.jl#332]
In a new cell, type just an equal sign.  A julia help page (live docs) about assignment takes over the whole browser window with no obvious way to go back to the notebook.

I did discover that clicking on the links within the assignment help page either goes back to the notebook directly or opens a help page that might be smaller and uncovers enough of the notebook to click back into it.  Also, continuing to type or hitting an arrow key moves the cursor away from the equal sign and the context sensitive help closes.

So, the main problem is positioning the context sensitive help.  It must never cover the cell being worked on.

Chrome on linux, julia 1.60
Installed Pluto ─────── v0.11.10

**Comment by fonsp** [comment]
It sounds like your browser is not supported. What version of chrome do you use?

https://www.howtogeek.com/299243/which-version-of-chrome-do-i-have/

**Comment by fonsp** [comment]
Issue seems to be this: 

https://developer.mozilla.org/en-US/docs/Web/CSS/max#Browser_compatibility

**Comment by billw1955** [comment]
Version 72.0.3626.121 (Official Build) (64-bit)
I'll find a way to access Pluto from a newer version.

**Comment by fonsp** [comment]
Chrome should auto-update itself. Any idea why this isn't working for you?

**Comment by fonsp** [comment]
Fixed in `0.11.11`

**Comment by fonsp** [comment]
(But those browsers are still not officially supported)
