### ISSUE TITLE
do not change pwd after exiting Pluto

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#342]
I find currently Pluto is using cd directly instead of use it as a context.

https://github.com/fonsp/Pluto.jl/blob/master/src/evaluation/WorkspaceManager.jl#L62

this changes the results of `pwd()` and can cause problems when someone tries to start pluto inside a script (e.g managing pluto instances)

**Comment by fonsp** [comment]
It only `cd`s within the notebook process, right?

**Comment by Roger-luo** [comment]
for this line, I think yes. But I think this somehow affects the main process, when you 

1. execute `Pluto.run`
2. then open a new notebook (don't save it)
3. then Ctrl+C in terminal
4. pwd() will be moved to the tempdir

![Screen Shot 2020-09-03 at 12 36 23 PM](https://user-images.githubusercontent.com/8445510/92142606-1a6d8b80-ede2-11ea-9ab2-0ea73abb76d7.png)

**Comment by Roger-luo** [comment]
this should be fixed in #367
