### ISSUE TITLE
Progress for cells taking longer to execute

### ISSUE THREAD

**Issue by dhanak** [fonsp/Pluto.jl#343]
I've been experimenting with Pluto for some days now, and I like it a lot. Keep up the good work, guys!

I have some cells, which take a significant amount of time to calculate. When running from REPL or the console, I use `ProgressMeter.jl` in these calculations to give me some feedback about the progress. It would be great if Pluto also supported some sort of progress reporting! And it would be a huge bonus if it could somehow piggyback onto ProgressMeter and use the exact same progress reporting API to display progress inside the notebook, such that when I run the notebook from a console, I still get the usual progress bars.

WDYT?

**Comment by fonsp** [comment]
Thanks! Cool idea to make it show progress bars in the console

**Comment by dhanak** [comment]
I was thinking of seeing progress indication on the web page. (Use case: Pluto is hosted, console is not accessible to everyone, only the rendered web pages are.) You are right, though, in thinking that using ProgressMeter currently shows progress bars in the console, this is already working correctly.

**Comment by fonsp** [comment]
I agree! My comment was a bit vague, sorry :)

**Comment by fonsp** [comment]
Also have a look at:
https://www.notion.so/a-cooler-way-to-print-24e1c517c3f64bbbbcb97499e2539611
@c42f

**Comment by Moelf** [comment]
is there a way we can use `ProgressMeter`? it's really nice to use in REPL, script, Jupyter. There must be a way we can get it working right? at least by making `with_terminal()` from PlutoUI work with it?
