### ISSUE TITLE
Move FAQ back to GitHub Wiki

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#344]
Right now it's here:
https://www.notion.so/3ce1c1cff62f4f97815891cdaa3daa7d?v=b5824fb6bc804d2c90d34c4d49a1c295

But this doesn't allow outside contributors. And SEO seems to be bad

**Comment by fonsp** [comment]
If anyone wants to be a hero: we just need to revert the latest commits on the Wiki git of this repository - the FAQ used to be there

There were some small changes to the notion FAQ but it's fine if they are lost

**Comment by shashankp** [comment]
@fonsp not being a hero here, but I dont think wiki repo is setup for contributions. I've tried to push [updated wiki home page](https://gist.github.com/shashankp/2ef4b4e79d83ea9d55f296157be69736) but got 403

**Comment by fonsp** [comment]
Oof do you think there's a way to fix that?

**Comment by shashankp** [comment]
@fonsp https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by fonsp** [comment]
Awesome I did it! Can you try again?

**Comment by fonsp** [comment]
And can you make 4 subpages?

**Comment by shashankp** [comment]
Done. 
Also, [Dev instructions](https://github.com/fonsp/Pluto.jl/blob/master/dev_instructions.md) will feel at home in the wiki.

**Comment by fonsp** [comment]
Haha how did you do without being a co-owner of the repo?

**Comment by fonsp** [comment]
I agree, but it's common for repositories to have a CONTRIBUTING.md:
https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md

So let's actually rename it to that

**Comment by shashankp** [comment]
> Haha how did you do without being a co-owner of the repo?

oops, maybe you would want to revert [permission](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis) once this issue is closed

**Comment by fonsp** [comment]
Nah let's leave it and see what happens :)

**Comment by fonsp** [comment]
Anyway, thanks a lot! 🥇

Feel free to write a PR for that rename since you brought it up
