### ISSUE TITLE
Buttons clickable but not visible on touch screen

### ISSUE THREAD

**Issue by mapclyps** [fonsp/Pluto.jl#348]
Recently, I often find myself hide/show cells which is a really cool feature. However, it is hard to find the cell when it is hidden and has no output. It still takes one line of space, but the hide/show symbol is not shown when a cell is not selected and it cannot be selected when hidden so that the symbol appears. 🐔 🥚 

Luckily it is still clickable even though invisible.

A similar thing applies to the delete button which is not shown when a cell is not selected but it is still clickable, I sometimes deleted cells which I only wanted to select because I clicked in the top right where the invisible delete button is. 

I had the impression that this was working as expected some weeks ago.

This change was probably implemented to have more clutter-free view on the notebook. 
So maybe these symbols can appear on mouse hover over the cell or so?

**Comment by fonsp** [comment]
Can you share a screenshot or gif? I dont know what you mean

**Comment by mapclyps** [comment]
Sure, it looks like this

![GIF 9-4-2020 12-46-36 PM](https://user-images.githubusercontent.com/4501995/92231350-e57a3b00-eeac-11ea-8e6e-82d0b6732048.gif)

**Comment by fonsp** [comment]
Very strange - is that Chrome on Windows 10? What version of Chrome/Firefox do you use? Does it also happen on firefox?

**Comment by mapclyps** [comment]
Oh wow, it is really just in Chrome (85.0.4183.83) and on Microsoft Edge (chromium based) on Windows 10.

It works correctly on Firefox on Windows and on Firefox and Chrome on Manjaro.

**Comment by fonsp** [comment]
Do you have a touch enabled screen?.

**Comment by fonsp** [comment]
Could you go to this page and send me a screenshot?

https://candy-adhesive-salary.glitch.me

**Comment by mapclyps** [comment]
The device has a touchscreen but that screen is disabled and the output is on a normal monitor currently.
I also tried it with deactivated extensions in chrome but that had no effects.

Here is the screenshot:
![image](https://user-images.githubusercontent.com/4501995/92298790-c3d09080-ef4c-11ea-9d47-396ee36993a8.png)

**Comment by fonsp** [comment]
Thanks! That helps

**Comment by fonsp** [comment]
To contributors: you can use browser dev tools to emulate the `pointer: coarse` media type. On `coarse`, all buttons should always be displayed, because these displays have no hover.
