### ISSUE TITLE
Open the standard Open File and Save File dialogs

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#350]
instead of that goofy improvised file picker where you _need to understand how absolute paths on your system work what are you thinking fonsi_

**Comment by fonsp** [comment]
good point fons!

It's because of browser restrictions: we are allowed to open the `Open File` dialog and get a file, but browser security prevents us from _getting the path of that file_. 
But Pluto needs to save your notebook after you modify it - that's why we had to implement our own thing 😥

**Comment by fonsp** [comment]
But!

In the common case that Pluto and the browser are running on the same computer (which is not guaranteed! it works over SSH!), we can **trigger the dialog with Julia** when you click in the browser, and it will feel like a normal dialog?

**Comment by fonsp** [comment]
This is a nice Julia issue for new contributors! Can you pop up the Open File and Save File dialog from the REPL, and get the path back?

**Comment by fonsp** [comment]
Without Gtk.jl

**Comment by cmcaine** [comment]
I think the sanest way to do this would be to use something like https://github.com/mlabbe/nativefiledialog or https://github.com/saurvs/nfd-rs. You'd package one of those in a _jll package and call it with `@ccall`.

That will work well for Windows, OSX and on Linux if GTK is available. Because it won't work on some linuxes, you'll probably want some method that works okay within the browser, too.

**Comment by fonsp** [comment]
Cool! This is not something that I can do myself - maybe you would like to try?

**Comment by cmcaine** [comment]
Realistically, I'm probs not going to be bothered to do this, just sharing a method in case someone can be.

**Comment by fonsp** [comment]
Haha fair enough

**Comment by fonsp** [comment]
Let's not do this - instead, we should focus on improving the existing file picker.

**Comment by nathanrboyer** [comment]
There is a Julia wrapper for [NativeFileDialog ](https://github.com/Suavesito-Olimpiada/NativeFileDialog.jl) now that was really easy to use in my personal package. I am not sure how it interacts with the browser though.

**Comment by fonsp** [comment]
This would also be fixed by https://github.com/JuliaPluto/PlutoDesktop, but this project is currently on hold.
