### ISSUE TITLE
Format docstrings in cells

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#351]
From a suggestion:

When a cell contains a function with a docstring associated it should display it (formatted) in the result. It should also be the case for other definitions types like struct.

**Comment by shashankp** [comment]
Would this be an improvement for Core.@doc ?

![image](https://user-images.githubusercontent.com/498813/92299206-f2ab2e80-ef6d-11ea-80bc-76de2d258505.png)

**Comment by fonsp** [comment]
I don't know what `Code.@doc` is, but the idea was that:
```julia
"""
Return **two times** the orginial _number_.
function f(x)
	x + x
end
"""
Currently prints `Main.workspace123.f`, but it should print the formatted docstring, together with the function name `f`.

**Comment by shashankp** [comment]
Tracking the flow of execution, looking at the code generated which runs in the sandboxed env,
a cell with a function definition and docstring generates

> """amazing function"""
> f1(y) = y+1


```
begin
    (ans, runtime) = try
            Core.eval(workspace6, 
                $(QuoteNode(quote
                    local elapsed_ns = time_ns()
                    local result = Core.@doc("amazing function", 
                                    f1(y) = begin
                                        y + 1
                                    end)
                    elapsed_ns = time_ns() - elapsed_ns
                    (result, elapsed_ns)
                end))
            )
        catch ex
            bt = stacktrace(catch_backtrace())
            (CapturedException(ex, bt), missing)
        end
    setindex!(Main.PlutoRunner.cell_results, WeakRef(ans), UUID("434607e8-eeb0-11ea-0650-bf92f7210a50"))
end


```

a cell with a function definition and no docstring 
> f2(y) = y+2


```
begin
    (ans, runtime) = try
        Core.eval(workspace5, $(QuoteNode(quote
                local elapsed_ns = time_ns()
                local result = (f2(y) = begin
                                y + 2
                            end)
                elapsed_ns = time_ns() - elapsed_ns
                (result, elapsed_ns)
            end))
        )
        catch ex
            bt = stacktrace(catch_backtrace())
            (CapturedException(ex, bt), missing)
        end
    setindex!(Main.PlutoRunner.cell_results, WeakRef(ans), UUID("2b3db9f6-eeb1-11ea-2558-d9e4c841bc4e"))
end
```


So, I was pointing to [Core.@doc macro](https://docs.julialang.org/en/v1/base/base/#Base.Docs) which is setting the documentation; will check it out

**Comment by fonsp** [comment]
Aha, I see!

I think you do not need to know how the macro works, it's just about writing a nice `show` method for the _result_ of that macro. I did an experiment:
```julia
julia> a = begin
           f(x) = x
       end
f (generic function with 1 method)

julia> b = begin
           """
           Awesome!
           """
           g(y) = y
       end
g

julia> typeof(a)
typeof(f)

julia> typeof(b)
Base.Docs.Binding

julia> a isa Function
true

julia> b isa Function
false
```

The display system for Pluto is contained in https://github.com/fonsp/Pluto.jl/blob/master/src/runner/PlutoRunner.jl

**Comment by shashankp** [comment]
```
function show(io::IO, ::MIME"application/vnd.pluto.tree+xml", x::Docs.Binding)
    print(io, """<jltree class="collapsed" onclick="onjltreeclick(this, event)">""")
    # ??
    show(io, x)
    print(io, "</jltree>")
end
```

how do I get `@doc g` from `b`

**Comment by fonsp** [comment]
I found this:

```julia
julia> b = begin
           "hello _world_"
           g(x) = x
       end

julia> Docs.doc(b)
  hello world

julia> Docs.doc(b) |> typeof
Markdown.MD
```

**Comment by fonsp** [comment]
And `jltree` is not related here. This issue might not be very fun to work on from this point on - the Pluto display system is a bit nasty

**Comment by shashankp** [comment]
![image](https://user-images.githubusercontent.com/498813/92335599-da462b80-f0b5-11ea-8d6d-613164e7c4b8.png)

Wasn't this the intended?
with formatting as a next step

**Comment by fonsp** [comment]
470 should be `show(io, MIME"text/html"(), Docs.doc(x))`

**Comment by fonsp** [comment]
Implemented!
