### ISSUE TITLE
Vector(undef, 3) does not show

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#352]
![image](https://user-images.githubusercontent.com/6933510/92229707-2de42980-eeaa-11ea-83ff-ff3ed14e5ea4.png)

but in the REPL

![image](https://user-images.githubusercontent.com/6933510/92229751-418f9000-eeaa-11ea-8ea8-b18d8c0f13f7.png)

**Comment by fonsp** [comment]
Someone needs to figure out how Base Julia does it, i.e. go through what happens when you call

```julia
show(stdout, MIME"text/plain"(), Vector(undef, 3))
```

**Comment by shashankp** [comment]
displaying data does a loop, which is failing; MVE:

![image](https://user-images.githubusercontent.com/498813/92242468-6fda9300-eedd-11ea-9a22-33c31c1ad1d4.png)

**Comment by fonsp** [comment]
I see why Pluto errors, but why wonder why `show(stdout, MIME"text/plain"(), Vector(undef, 3))` _does not error_.

**Comment by shashankp** [comment]
works fine cos it goes to [base implementation](https://github.com/JuliaLang/julia/blob/f896006621414725ac1355fe23a779c50995091d/base/show.jl) which has checks for isassigned & isdefined. As expected, works fine in REPL too
![image](https://user-images.githubusercontent.com/498813/92304411-3ff1c500-ef9b-11ea-865a-8b08ed0e71d2.png)

where as
![image](https://user-images.githubusercontent.com/498813/92305000-b513c900-efa0-11ea-8ac7-7b8526897b88.png)
goes to
`show(io::IO, ::MIME"application/vnd.pluto.tree+xml", x::AbstractArray{<:Any, 1})` [ref](https://github.com/fonsp/Pluto.jl/blob/d943b3863a611e3a64db4534488dc63924504022/src/runner/PlutoRunner.jl#L394)

May be it needs isassigned/isdefined checks?

**Comment by fonsp** [comment]
That sounds good!

**Comment by shashankp** [comment]
this should help with https://github.com/fonsp/Pluto.jl/issues/354 too

**Comment by fonsp** [comment]
No that's unrelated I think

**Comment by fonsp** [comment]
Fixed by @Moelf ! Yayo

Testset is here:
https://github.com/fonsp/Pluto.jl/pull/411/files#diff-57577b94ab5dc9eb946ef0662a875f1dR24

**Comment by fonsp** [comment]
@Moelf 

![image](https://user-images.githubusercontent.com/6933510/93714050-461d9f00-fb60-11ea-8802-913c10e27fab.png)

**Comment by Moelf** [comment]
@fonsp fixed. issue was that we pass `indices` and `x`, so we don't need to slice up `x` before passing.

**Comment by fonsp** [comment]
Awesome, thanks!
