### ISSUE TITLE
sample notebooks: pizza 5 cuts typo?

### ISSUE THREAD

**Issue by zmoon92** [fonsp/Pluto.jl#356]
This part near the end in sample notebook 2:

> To get an extra hint, figure out how many slices we can get from 5 cuts:

With 5 cuts we can get 16 slices, but in order to show the hint we need to put 15. 

The language of the hint itself noted that there should be one additional slice corresponding to the pizza with no cuts, but from wording of the question I am not sure if it is clear that we were supposed to subtract 1. In any case, it seems not consistent with the previous questions about smaller numbers of cuts and the last part with the slider, which agrees that 16 is the number of slices for 5 cuts.

**Comment by fonsp** [comment]
| Cuts | Slices |
|-----|-----|
| 0 | 1 |
| 1 | 2 |
| 2 | 4 |
| 3 | 7 |
| 4 | 11 |
| 5 | 16 |

aha you're right

**Comment by fonsp** [comment]
Thanks for finding the mistake! Since Pluto is open source, you can write the fix yourself!

http://opensource.guide/how-to-contribute/#opening-a-pull-request
