### ISSUE TITLE
#Pluto live doc

### ISSUE THREAD

**Issue by sherlockguan** [fonsp/Pluto.jl#358]
Hi,
I love the live doc idea
sometimes, it behaves weirdly, like I can't type or delete in my send box (right bottom) or it searched automatically yet provide me the too shortsighted result (as the photo attached, I wanted to see how to make an eye(5,5) matrix, but live doc try to teach me what '=' is, I don't think it is very intelligent to know what is important or my intention), why not add a search box ? also it paused or crashed sometimes, yet I run a few application while using it.
Thanks for the efforts!
![issue](https://user-images.githubusercontent.com/46273832/92289487-9c2cf880-ef4b-11ea-9c9b-ccd49d421e3c.png)

**Comment by fonsp** [comment]
It looks like you are using an outdated version of Chrome - do you think you can update to the latest version?

**Comment by sherlockguan** [comment]
Wow,
you are so fast 
Thanks

**Comment by sherlockguan** [comment]
Yes, I updated to Google Chrome 85.0.4183.83 
worked perfect 
Thanks ^^

**Comment by fonsp** [comment]
The issue you mentioned about not being able to type backspace or delete in the bottom right will be fixed in the next update!
