### ISSUE TITLE
Automatically reload from file

### ISSUE THREAD

**Issue by antoine-levitt** [fonsp/Pluto.jl#360]
Hi and thanks for Pluto! I've been periodically trying to get into notebooks for a while now, but just can't get used to it. The main barrier is that I absolutely loathe writing code in a browser - I don't have my nice shortcuts and unicode input from emacs. Jupyter is a no-go because its format sucks, but Pluto has the great idea of saving files as plain text, and has a nice recognizable format for its internal stuff that I can probably tell emacs to ignore. 

One thing I would love is to be able to run a notebook in Pluto, go back to emacs to edit a complicated function, and go back to Pluto and have it reload the file (preferably automatically, but already a manual solution would be nice). Is this possible at all?

**Comment by fonsp** [comment]
#240 - it's not a current goal of this project to support that kind of workflow

**Comment by antoine-levitt** [comment]
OK - a pity but I understand you have different priorities. Back to the REPL for me then.

**Comment by yasirroni** [comment]
So, what is the shortest possible way to refresh from plain text? Simply load using `Open a notebook` is not works. Does I need to restart Pluto (go to terminal, kill, restart)?
