### ISSUE TITLE
Unable to download from URL from behind a corporate proxy server

### ISSUE THREAD

**Issue by tk3369** [fonsp/Pluto.jl#365]
I'm unable to use the open from URL function when running Pluto behind a corporate proxy server. See related issue https://github.com/JuliaLang/julia/issues/27043.

Idea:  can we add a checkbox in the UI to allow user to disable SSL verification check?  If you switch over to `HTTP.download` then you can just set the `ssl_verification_check` flag to `false`.

**Comment by fonsp** [comment]
Sounds like this will be fixed in Julia `1.6.0`! I like the simplicity of `download(url)`. `ssl_verification_flag` sounds like:
1. something that should be _on_
2. something that I do not want to think about

**Comment by fonsp** [comment]
We could also consider downloading using the frontend and sending the notebook via the WS connection. This would also allow for pasting an entire notebook into the main menu and dragging+dropping a notebook to open it _as a template_ (we don't know the path where it came from unfortunately).
We also still need the original feature, to make one-click binder work
