### ISSUE TITLE
Unable to run cell with variable-setting macro twice

### ISSUE THREAD

**Issue by cadojo** [fonsp/Pluto.jl#371]
Some packages (`MATLAB`, `ModelingToolkit`) use macros for setting variables. 

* `MATAB` uses `@mget x` to copy a Matlab workspace variable `x` into a Julia variable called `x`.  

* `ModelingToolkit` uses `@variables x y z` to initialize symbolic variables `x`, `y`, and `z`.

In Pluto v0.11.12 (and all other versions I've used), __you can't run any cell with either of these macros more than once__. 

Take `ModelingToolkit`'s `@variables` as an example. If a cell contains:

> @variables x

It will run correctly once. If the cell is run again, it produces the following error:

> cannot assign a value to variable workspace24.x from module workspace25

The current workaround is to set `x` to `nothing` before calling `@variables x`. It seems that a new module is created every time a cell is run. We probably only care about the latest module, right? Would it be possible to "forget" about modules 1 through 24 in this example?

**Comment by fonsp** [comment]
Thanks! Have a look at #196

**Comment by fonsp** [comment]
You're right that forgetting about all unrecognized variables from previous workspace modules would fix the problem that you can't assign twice, but it will introduce a new problem: the variable only exists for one reactive run, and is forgotten afterward. This makes the macro even less useful 😥
