### ISSUE TITLE
Coloured show

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#374]
I feel it helps adding colours to bit-strings to teach students about finite-precision floating-point number systems. For `Float64`, consider the function:
```julia
function colorbitstring(x::Float64)
    s = bitstring(x)
    print("\"")
    printstyled(string(s[1]); color=:red)
    printstyled(s[2:12]; color=:green)
    printstyled(s[13:end]; color=:blue)
    println("\"")
end
```
In the REPL, the output of `colorbitstring(1.0)` is a colourized version of `bitstring(1.0)`. However, the internals are quite different, given that `Base`'s `bitstring` actually returns a string whereas `colorbitstring` uses multiple print statements.

In Pluto, I tried adapting this by showing a struct, calling print, and specifically use the string modifiers that `printstyled` uses. For example,
```julia
struct DisplayBits{T}
    x::T
end
import Base: show
function show(io::IO, x::DisplayBits{Float64})
    s = bitstring(x.x)
    ret = "\033[31m"*string(s[1])
    ret *= "\033[32m"*s[2:12]
    ret *= "\033[34m"*s[13:end]
    print(io, ret)
end
```
This produces coloured bits in the REPL but not in Pluto. In Pluto, if I type `DisplayBits(1.0)`, I see the raw string:
```julia
[31m0[32m01111111111[34m0000000000000000000000000000000000000000000000000000
```
How can I get coloured text in Pluto's show methods?

**Comment by fonsp** [comment]
With HTML!

**Comment by MikaelSlevinsky** [comment]
Great, so an HTML-based solution looks like this:
```julia
function colorbitstring(x::Float64)
	s = bitstring(x)
	HTML("""<p style="color:red;display:inline">$(string(s[1]))</p><p style="color:green;display:inline">$(s[2:12])</p><p style="color:blue;display:inline">$(s[13:end])</p>""")
end
```

**Comment by fonsp** [comment]
Nice! You could use `<span>` instead of `<p style="display:inline;">`

**Comment by fonsp** [comment]
or `<potato>`
