### ISSUE TITLE
@test macro with rtol

### ISSUE THREAD

**Issue by cnaak** [fonsp/Pluto.jl#383]
In the following, `rtol` is just a parameter of the infix operator `≈` (`approx`), but `Pluto` thinks an `rtol` variable has been created:

`@test A ≈ B rtol = eps(Float64)`

Side effects include not being able to create an `rtol` variable in another cell, which errors with: "**Multiple definitions for rtol:**"

**Comment by fonsp** [comment]
#196 #407

**Comment by jcmkk3** [comment]
I'm not sure if it would be useful, but the [presentation](https://youtu.be/0uzrH2Ee494) for Salsa.jl was referencing some issues very similar to this.

**Comment by fonsp** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/c6fa171b0ee7cbffcd151a982ec92a4b1b22c8f4
