### ISSUE TITLE
Can't use two calls to VegaLite.jl `@vlplot` in different cells if they use the same keywork arguments

### ISSUE THREAD

**Issue by lassepe** [fonsp/Pluto.jl#388]
I am getting a `Multiple definitions` error when invoking the `@vlplot` macro from `VegaLite.jl` in two different cells. I guess this is due the fact that `width = 700` (et al.) is interpreted as a declaration of a local variable rather than a keyword argument.

![image](https://user-images.githubusercontent.com/10076790/92523678-0fbb5800-f221-11ea-83e3-88e815117a5a.png)

**Comment by fonsp** [comment]
That's right - I'm linking this to #196

**Comment by lassepe** [comment]
Thank you for your quick response. Since this is just another instance of the very same problem discussed in the #196 I'll close this issue to avoid duplication.
