### ISSUE TITLE
@bind doesn't update values within the same cell

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#391]
A cell containing both `@bind` and a reference to the binded value does not keep them in sync.
E.g. create this cell:
```
md"""
$(@bind x Slider(0:10))
x = $x
"""
```
and drag the slider around. It always shows "x = 0" on the second line.

**Comment by fonsp** [comment]
Hi @aplavin!
That's on purpose, if the cell would run again with your new value, then it would also _create a new slider_, which is set to its default value. So you wouldn't be able to move the slider.
