### ISSUE TITLE
Markdown syntax inconsistencies

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#392]
1. A simple example of four cells, one of them giving a syntax error:
![image](https://user-images.githubusercontent.com/687995/92541754-9c7d0a80-f24f-11ea-903d-d8db8e5d6a7f.png)
I have no idea how this happens...

2. Putting together two independent parts of markdown gives a very different result:
![image](https://user-images.githubusercontent.com/687995/92541924-009fce80-f250-11ea-8cc8-199ae48d3934.png)
This one, I think, has to do with some escaping issues. Is there a specific escaping model in mind, that allows `$` signs for both interpolation and formulas, and doesn't mix them up?

**Comment by fonsp** [comment]
Markdown is part of Julia, not of Pluto:
https://github.com/JuliaLang/julia/issues/36946
https://github.com/JuliaLang/julia/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Amarkdown
