### ISSUE TITLE
Connect from a remote host?

### ISSUE THREAD

**Issue by blablablerg** [fonsp/Pluto.jl#398]
Hello,

I am new to Julia, and I don't know how to find package documentation (yet), so I might ask a stupid question. 

So I am trying to do the new julia course, but I run julia on a remote host (on the LAN). When I start Pluto.jl with Pluto.run(), I can connect to the server on the host itself but not over the network. 

When I check netstat, I see that the server is listening on 127.0.0.1:1234. I think that I want this to be 0.0.0.0:1234, so that I can connect from a remote host.

Any of you know how to do that? Much appreciated. The host I want to use runs Debian.

**Comment by fonsp** [comment]
Hi! You can do:

`Pluto.run("0.0.0.0", 1234)`

let me know if this works!

**Comment by blablablerg** [comment]
It does! Thank you.

**Comment by fonsp** [comment]
(This syntax will change very soon - sorry in advance :)))))

**Comment by erny123** [comment]
Anyone have an update on this? 

I'm SSH'ing to my computer's HPC and the regular way of getting a jupyter notebook is: 

`jupyter notebook --no-browser --ip=$(hostname -s) --port=8989`

The hostname being something like the compute node: `hpc3-22-04`

And then in putty I would set it as done  [here](https://medium.com/@apbetahouse45/how-to-run-jupyter-notebooks-on-remote-server-part-1-ssh-a2be0232c533)

With
sourceport: `8989`
Destination: `hpc3-22-04:8989`

Any advice?

**Comment by ctrekker** [comment]
If you want a one-liner that works from the terminal, this should do it.
```bash
julia -e "using Pluto; Pluto.run(host=\"0.0.0.0\", port=1234, launch_browser=false)"
```
Then you can open Pluto by going to `hpc3-22-04:1234/?secret=<paste secret here>`

**Comment by erny123** [comment]
> 

@ctrekker Ok looks like rather than pasting the:
`https://hpc3-22-04:1234/?secret=<paste secret here>`
or
`https://0.0.0.0:1234/?secret=<paste secret here>`

I had to use: 
`https://127.0.0.1:1234/?secret=<paste secret here>`
and it worked!

It's interesting that even when I specifically used that ip address:
`Pluto.run(host="127.0.0.1", port=1234, launch_browser=false)`

It didn't work.

**Comment by ctrekker** [comment]
Glad you found a solution! I'm guessing there's something on your computer acting as a proxy, since `127.0.0.1` would normally loopback to a server running locally. VSCode acts as a proxy in this manner if connected via SSH to the remote - maybe PuTTY does something similar.
