### ISSUE TITLE
Don't launch browser over SSH

### ISSUE THREAD

**Issue by aramirezreyes** [fonsp/Pluto.jl#401]
A new version merged #190 .

This brings a  minorly annoying feature when using Pluto through ssh:
After doing Pluto.run()

1.-It first launches a w3m instance that takes over the terminal (So you won't see Pluto's logs)
2.- After closing w3m it tries launching all other browsers.

If you are connected through ssh to a headless system it doesn't really make sense to try opening a graphical browser.

I am not an expert, but maybe somehow checking if the process is running in an ssh session before trying to launch a graphical browser could be better?

**Comment by Immortalin** [comment]
Can we add an argument to Pluto to disable opening browsers in general?

**Comment by goszlanyi** [comment]
Unfortunately, automatic launching of the default browser is a bad user experience.
With a remote server it is a serious problem, but even with a local server 
it is a problem, as it does not allow using a non-default browser.
Therefore, I suggest making it only an option  and set the default to "no automatic browser launching".

**Comment by Moelf** [comment]
I agree, the most annoying thing (happens when you use a new cluster/note/machine) is when it tries to open browser and you had `ssh -Y`. For now you have to:
```
Pluto.run(configuration=Pluto.ServerConfiguration(nothing, false))
```

**Comment by fonsp** [comment]
How do we detect it?

**Comment by goszlanyi** [comment]
@Moelf Thank you for the advice. This solved the automatic browser launching, but unfortunately, my current problem is different and is more serious.

@fonsp Maybe my comment was inaccurate, but I do not understand your question. 

Anyway, my current problem description is the following:
Previously, using ``Pluto v0.11.12`` and the RDP protocol, I could happily use a powerful remote Windows 10 PC from my old and slow Windows 7 PC. As the remote computer was behind a firewall, I needed to open an ssh tunnel,  using PuTTY on the local side and OpenSSH on the server side. Finally the remote Pluto server was started within an RDP session with the command ``using Pluto, PlutoUI; Pluto.run("0.0.0.0")`` and the local computer could access it from the Chrome browser as ``localhost:1234`` .

For some reason, this setup stopped working either at ``Pluto v0.11.13`` or ``Pluto v0.11.14``, the remote PC is now inaccessible.
I don't know what happened in the meantime, as I did not make any changes. So please, any advice would be welcome.
