### ISSUE TITLE
Pluto.run() opens url at "penguin.linux.test"

### ISSUE THREAD

**Issue by dojt** [fonsp/Pluto.jl#404]
With Pluto v0.11.14, after `Pluto.run(1234)`, it seems as if Pluto *automatically* opens a browser window with some URL involving 1234, see screenshot.

![image](https://user-images.githubusercontent.com/57910358/92695550-47292200-f351-11ea-87b8-3f0707eda6c0.png)

Something changed in the interface?

**Comment by fonsp** [comment]
Haha how is this possible 🐧

Which Linux distro are you on?
Could you type:
```
$ xdg-open http://localhost:1234/
```
and see what happens?

**Comment by fonsp** [comment]
I think the solution in your case is just to disable it: https://github.com/fonsp/Pluto.jl/issues/401#issuecomment-690836546

**Comment by Immortalin** [comment]
Can we add a higher level parameter to `Pluto.run` instead of having to type out the entire ServerConfig initializer?

 E.g. `Pluto.run (1234, browser=false)`

**Comment by fonsp** [comment]
Yep that will happen soon

**Comment by fonsp** [comment]
Pluto just opens `http://localhost:1234`, your IP lookup is misconfigured.
