### ISSUE TITLE
Screen centered layout

### ISSUE THREAD

**Issue by adyomin** [fonsp/Pluto.jl#406]
Is there a way to align notebooks to the center by default? If there is none atm, I would like to suggest this as a settings option. With live docs button/tab taking so mush screen space and left horizontal alignment, I would not feel comfortable staring at Pluto all day long.

I realize that this is pretty subjective and idiosyncratic, but I could not submit this via builtin feedback system:

> Whoops, failed to send feedback 😢
> We would really like to hear from you! Please got to https://github.com/fonsp/Pluto.jl/issues to report this failure:
> Error: Promise timed out.

**Comment by fonsp** [comment]
It's centered if your window is large enough, otherwise it shifts the notebook to the left to give more space to the live docs. There is no option to change it. #2

**Comment by adyomin** [comment]
It is indeed centered @ 100%, I zoomed past it pretty quickly. Is there a way to turn off Live docs then?
