### ISSUE TITLE
Backspace to delete cell is not ideal

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#408]
Hi, I several times accidentally deleted code cells by removing code in a cell using the backspace key.
When the cell is empty, the next backspace deletes the cell itself, editing jumps to the cell before, and
backspacing havoc continues.  Re-establishing the code then quickly becomes impossible.

IMHO with the backspace key it should not be possible to delete a cell, neither should it trigger jumping between cells.

**Comment by fonsp** [comment]
Can you split this issue in 2?

**Comment by fonsp** [comment]
See the thread in #331

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/pull/419

**Comment by fonsp** [comment]
Here's a conversation from last week on the Pluto slack about the pros/cons/future of the backspace feature:
https://gist.github.com/fonsp/0911943f27baab81b45c53b1c95044d2

**Comment by dralletje** [comment]
I put a pretty small cooldown on the delete cell backspace, only 300ms, so @j-fu (and anyone who had problems with this issue), let me know if it works for you :)
