### ISSUE TITLE
Dependency on copy isn't detected

### ISSUE THREAD

**Issue by frycast** [fonsp/Pluto.jl#417]
As expected, the below assigns `5` to `v[1]`. 
```julia
# ╔═╡ cc0c1db0-f4dc-11ea-2f85-dd812a3de9b1
v = [1 2 3]

# ╔═╡ d2905c00-f4dc-11ea-367a-a5073a34c7db
begin
w = v
w[1] = 5
v
end
```
But if now we change the second cell above, to make a copy of `v`:
```julia
# ╔═╡ d2905c00-f4dc-11ea-367a-a5073a34c7db
begin
w = copy(v)
w[2] = 5
v
end
```
Then my expectation is that when I run the updated second cell, the first cell should automatically be rerun so that the output of the second cell reflects what it would be if the whole notebook was run from scratch. Instead, after updating and running the second cell, I get
```julia
1×3 Array{Int64,2}:
 5  5  3
```

**Comment by fonsp** [comment]
This is very very difficult. Even the simple task of knowing which functions _mutate_ which arguments is hard:
https://github.com/fonsp/Pluto.jl/issues/316#issuecomment-679907752
