### ISSUE TITLE
f(x).g() not recognised?

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#418]
A minimal example I came up with:
```julia
# cell 1:
x = :x
# cell 2:
f(x) = (g=() -> 1,)
# cell 3:
f(x).g()
```
Everything is fine so far.
Then change cell 1 (e.g. to `x = :y`) or cell 2 (e.g. to `f(x) = (g=() -> 2,)`) - cell 3 is not reexecuted automatically. Running cell 3 manually gives the expected result.

**Comment by fonsp** [comment]
Thanks! Are there any warnings in your terminal?

**Comment by aplavin** [comment]
I don't see any.

**Comment by mcabbott** [comment]
Is this what ought to pass? Or should it not track `getproperty`?
```
julia> testee(:(f(x).g()), [:x], [], [[:f], [:Base, :getproperty]], [])

FAILED TEST
(f(x)).g()

Expr
  head: Symbol call
  args: Array{Any}((1,))
    1: Expr
      head: Symbol .
      args: Array{Any}((2,))
        1: Expr
          head: Symbol call
          args: Array{Any}((2,))
            1: Symbol f
            2: Symbol x
        2: QuoteNode
          value: Symbol g

expected = SymbolsState([x], [], [[:f], [:Base, :getproperty]], [])
resulted = SymbolsState([], [], [[:g]], [])

false
```

**Comment by fonsp** [comment]
🐐 [testset](https://github.com/fonsp/Pluto.jl/commit/5a0940e00a9137453a0be6b1536027a60e895956#diff-2089b2016831147491e94b40cf551faaR203)
