### ISSUE TITLE
VegaLite tooltips not visible

### ISSUE THREAD

**Issue by alphajuliet** [fonsp/Pluto.jl#422]
Tooltips that should pop up when hovering over a chart element are not visible. 

```
df |> @vlplot(
	:bar,
	x = :foo,
	y = :bar,
	color = :baz,
	tooltip = :baz,
	title = "Bar by foo")
```

**Comment by fonsp** [comment]
screenshot?

**Comment by fonsp** [comment]
#253

**Comment by fonsp** [comment]
Should be solved by https://github.com/queryverse/VegaLite.jl/pull/401

**Comment by diegozea** [comment]
Hi @alphajuliet ! 

Until a new version of VegaLite is released, you can use the master branch of the package to have the interactivity behavior in Pluto:

```julia
begin
	using Pkg
	Pkg.activate(temp=true)
	Pkg.add(url="https://github.com/queryverse/VegaLite.jl.git", rev="master")
	
	using VegaLite
end
```

Here I am using the *Pkg cell* explained on [Pluto's wiki](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#pattern-the-pkg-cell)

Cheers,
