### ISSUE TITLE
Visual reordering of cells

### ISSUE THREAD

**Issue by goszlanyi** [fonsp/Pluto.jl#427]
I know that it is the _logical_ order of cells that really counts and that is analyzed.

However, the _visual_ order of cells is also important for the user's comprehension.
During user experiments, the early visual order of cells may become confusing,
and then, it would be nice to have some reordering mechanism to see clearly again.
Even just the option of shifting cells upwards/downwards could be extremely useful.

**Comment by fonsp** [comment]
Hi! You can drag cells around by clicking & holding the gray area to the left of a cell.

**Comment by fonsp** [comment]
#270

**Comment by goszlanyi** [comment]
Great feature! Thank you so much!
I was searching really hard, but could not find it in the documentation.

**Comment by fonsp** [comment]
Thanks for letting me know! I made #428
