### ISSUE TITLE
text not copying to appropriate buffer on linux

### ISSUE THREAD

**Issue by leios** [fonsp/Pluto.jl#431]
On linux, it is possible to copy and paste text by highlighting the text to copy and then clicking the middle button to paste. This buffer is not available in Pluto and is the main buffer used to copy text to and from the terminal.

I'll be honest, I do not know the right terminology to use here, but it was a small frustration I wanted to make known.

**Comment by leios** [comment]
Ok, really embarrassing here. Right when I wanted to show this issue off so someone on stream, it suddenly worked. There must be something else at play then. I'll get you a more definitive report when it happens again.

**Comment by fonsp** [comment]
Hm strange - let me know if you find it again!
