### ISSUE TITLE
Convert Pluto notebooks to plain Julia code

### ISSUE THREAD

**Issue by leios** [fonsp/Pluto.jl#432]
Would it be possible to create a function that strips the Pluto-ness from a Pluto notebook and provides a simple julia file? Sometimes it's hard to get a notebook open to debug code.

As a note, I realize there are PlutoUI bits that might make this difficult.

Also: I realize Pluto notebooks *are* julia files, and can just write the script myself. I am mainly asking to remove the md and comments that look like this `# ╔═╡ 0316b94c-eef6-11ea-19bc-dbc959901bb5`

**Comment by fonsp** [comment]
We were discussing it today: https://github.com/fonsp/PlutoUtils.jl/issues/11

Feel free to write this script yourself! Shouldn't be too tricky - delete any line that starts with [one of the delimiters](https://github.com/fonsp/Pluto.jl/blob/v0.11.14/src/notebook/Notebook.jl#L49-L51), and maybe also the line before it. 

PlutoUI and `@bind` is designed to "work" without Pluto. Notebooks that use `@bind`  include a mock version of the macro, which just assigns the default value of the input element to the variable. The default default value is `missing`, but types can ovverride this. The elements from PlutoUI all have sensible defaults.

For example, if your notebook contains

```julia
@bind x Slider(5:15)
```

and you run the notebook without Pluto, then `x` will be assigned `5`.
