### ISSUE TITLE
Distinction between queued and running cells

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#44]
Like a slower/stationary traffic light for queued cells.

**Comment by fonsp** [comment]
Why?

**Comment by fonsp** [comment]
I can see why

**Comment by shashankp** [comment]
Was giving this a shot

![queued-vs-running (1)](https://user-images.githubusercontent.com/498813/92210278-0e4e0080-eeac-11ea-8fdc-cfb43f5e46db.gif)

Gray: Queued
Green : Running

@fonsp feedback appreciated

**Comment by shashankp** [comment]
https://github.com/fonsp/Pluto.jl/pull/349
