### ISSUE TITLE
Tab key should insert 4 spaces

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#450]
Using `<TAB>` in Markdown breaks indentation.
It should just insert 4 spaces.

**Comment by fonsp** [comment]
These are bugs in Julia that can be fixed! I have already fixed footnotes and admonitions:
https://github.com/JuliaLang/julia/pull/37347

Which other markdown elements are broken?

**Comment by roflmaostc** [comment]
Hm, strangely I encountered the same under Julia 1.6.1 and Pluto v0.14.8.
Pressing tab breaks markdown
[See here](https://imgur.com/a/pPKgbMN)

That PR is in 1.6 included, isn't it?
