### ISSUE TITLE
@which macro shows local path but click through link is broken

### ISSUE THREAD

**Issue by waltsims** [fonsp/Pluto.jl#451]
I was playing with the `@which` macro, which returns the local path of the function in pluto.jl but the click through link forwards to a broken github link.

e.g.
```
(::Type{LinearAlgebra.Diagonal})(A::AbstractArray{T,2} where T) in LinearAlgebra at /{local_path}/julia/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/diagonal.jl:36


@which Diagonal([1 2 3])
```
but the clickthough link forwards to: https://github.com/JuliaLang/julia/tree/96786e22ccabfdafd073122abb1fb69cea921e17//usr/share/julia/stdlib/v1.5/LinearAlgebra/src/diagonal.jl#L36 (a broken link)

**Comment by fonsp** [comment]
Is this not an issue with Julia?

**Comment by waltsims** [comment]
At least for me, Julia in the commandline doesn't offer a hyper link and the path given is the local source file. In pluto, there is a hyperlink.

**Comment by waltsims** [comment]
Alright, I just cross-checked in IJulia and the same happens there. Must be a mistake with Julia. My mistake.

**Comment by fonsp** [comment]
This used to work at some point

**Comment by dralletje** [comment]
Some functions do work, most from base etc show a good lik

**Comment by fonsp** [comment]
So it works for Base, but not for the standard libraries?

**Comment by waltsims** [comment]
That specification isn't made in [the docs](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.@which).

 I think we can close this here at any rate. I will reopen in the Julia repo.

**Comment by fonsp** [comment]
Okay,

```julia
repr(MIME"text/html"(), @which Diagonal([1 2 3]))
```

should reproduce the bug in the REPL
