### ISSUE TITLE
Include `with_terminal` in Pluto or PlutoUI

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#459]
There have been many questions on where to find `with_terminal()` (ref: https://www.youtube.com/watch?v=e6LGMeoQhfs) and I think it would be helpful to include `with_terminal` in Pluto or PlutoUI. Thoughts? 

`with_terminal` gist: https://gist.github.com/fonsp/0b92c7ad849d48180a3cbade0ba99382#file-vintage-jl-L105

**Comment by fonsp** [comment]
Yep! https://github.com/fonsp/PlutoUI.jl/pull/31
