### ISSUE TITLE
Error on Ubuntu 16.04: `NaCl helper process running without a sandbox`

### ISSUE THREAD

**Issue by cadojo** [fonsp/Pluto.jl#465]
When running `Pluto.run()` for `Pluto@0.11.14` on Ubuntu 16.04, I get the following error:

>ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox! Most likely you need to configure your SUID sandbox correctly

Then Pluto  seems to start normally. This doesn't happen with `Pluto@0.11.12`.

**Comment by fonsp** [comment]
Can you update Pluto to the master branch and see if the error is fixed?
```julia
julia> ]
(v1.5) pkg> add Pluto#master
...
julia> import Pluto; Pluto.run()
```

**Comment by cadojo** [comment]
It doesn't seem to be fixed with the master branch. Although, after more Googling, it seems this is a known Chrome/Linux issue.

Setting my default browser to Firefox fixes this issue.

**Comment by fonsp** [comment]
Okay! You can also disable the default browser launch:
```julia
Pluto.run(launch_browser=false)
```
(This syntax works on the master branch, and in the upcoming Pluto 0.12.0)
