### ISSUE TITLE
Problems using pluto.jl in WSL2's docker

### ISSUE THREAD

**Issue by ZenanH** [fonsp/Pluto.jl#468]
I configured `WSL 2` in a windows environment and set up the docker in WSL via [docker desktop for windows](https://www.docker.com/get-started). In my docker container, I started pluto:

```julia
bash > docker run --rm -it -p 1234:1234 -v /d/:/notebooks hrdlzenan/xjulia:latest
julia> using Pluto
julia> Pluto.run("0.0.0.0.0", 1234; configuration=Pluto.ServerConfiguration(launch_browser=false))
```
Then, pluto shows:

```julia
Go to http://0.0.0.0:1234/ in your browser to start writing ~ have fun!

Press Ctrl+C in this terminal to stop Pluto
```

I opened `http://localhost:1234/` in my browser and nothing shows up.

![image](https://user-images.githubusercontent.com/19581645/93767228-46926480-fc4a-11ea-93ae-f58a6a627510.png)

What it means is: `Unable to access this site, localhost denied our connection request.`

What should I do?😅 （If I don't use `WSL`, but use docker directly in a windows environment, there is no problem repeating the above steps.）

**Comment by fonsp** [comment]
@lungben

**Comment by lungben** [comment]
I cannot reproduce your error, for me the container works correctly with WSL 2.

I tested it using Win10, WSL2 (Ubuntu 20.04 LTS) and latest Docker for Windows Edge (with WSL2 backend).
1. Starting the container plutojl/pluto:latest from Powershell with `docker run -p 1234:1234 -d plutojl/pluto`
2. Starting the container in Ubuntu WSL2, using the same command

Could you please double-check that you are using WSL2 by executing `wsl -l -v` in PowerShell?
And please double-check to have WSL2 backend enabled in Docker: Settings -> General -> Use the WSL 2 based engine

**Comment by lungben** [comment]
I just saw that you are using a custom Docker image, not the official Pluto.jl one.

In your example, it may just be one ".0" too many in your IP address ;-)

`julia> Pluto.run("0.0.0.0.0", `

**Comment by ZenanH** [comment]
Thank you for your reply!

#### 1. Detailed information about my computer environment:
![image](https://user-images.githubusercontent.com/19581645/93846051-85213100-fcd5-11ea-84c8-bbaa92cdc719.png)
![image](https://user-images.githubusercontent.com/19581645/93846339-46d84180-fcd6-11ea-9072-47ae8bf8b6fd.png)
![image](https://user-images.githubusercontent.com/19581645/93846290-2f995400-fcd6-11ea-9e53-71072de38a43.png)

#### 2. This time I used the official pluto image.

```bash
docker run -p 1234:1234 -d plutojl/pluto
docker container ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                    NAMES
4a69586dfd37        plutojl/pluto       "julia /home/pluto/s…"   About a minute ago   Up About a minute   0.0.0.0:1234->1234/tcp   romantic_nightingale
```

#### 3. At this time, I opened `http://localhost:1234`my brower
The browser shows the error I mentioned earlier. 😅

**Comment by lungben** [comment]
Strange, I have practically the identical setup and for me it works.
It it possible for you in general to run a service in Docker and access its port in your browser?

**Comment by ZenanH** [comment]
I can use `jupyter` in my dockers container as follows:

```bash
zenan@DESKTOP-LT1J6HO:/mnt/c/Users/zenan$ docker run -it --rm -p 8888:8888 hrdlzenan/xjulia:latest
(base) root@5403afcbf729:/# jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/'

[I 07:04:57.812 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 07:04:58.083 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 07:04:58.171 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
[I 07:04:58.171 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 07:04:58.173 NotebookApp] Serving notebooks from local directory: /
[I 07:04:58.173 NotebookApp] Jupyter Notebook 6.1.1 is running at:
[I 07:04:58.173 NotebookApp] http://5403afcbf729:8888/
[I 07:04:58.173 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 07:06:06.018 NotebookApp] 302 GET / (172.17.0.1) 0.34ms
```

Then, I opened `http://127.0.0.1:8888` in brower:
![image](https://user-images.githubusercontent.com/19581645/93853067-befa3380-fce5-11ea-9a22-3546fc75324d.png)

However, if I type jupyter's `http://5403afcbf729:8888/` in my browser, the browser also gives me the same error:
![image](https://user-images.githubusercontent.com/19581645/93853257-1ef0da00-fce6-11ea-8e35-517dc9097b39.png)

**Comment by ZenanH** [comment]
### Problem solved!

I find that on my computer I just need to set the port to 8888. 😂


![image](https://user-images.githubusercontent.com/19581645/93863596-3f289500-fcf6-11ea-951c-351327b08d9c.png)

In this way, pluto can work well in browser. But I'm still not sure why the port `1234` can cause the problem (I have no server running in `1234`)

**Comment by lungben** [comment]
Maybe a firewall issue?
Anyhow, glad that it works for you now!

**Comment by ZenanH** [comment]
I'll keep checking on this issue and report back if I find anything new. Thanks for your quick reply.☺
