### ISSUE TITLE
Disable auto-running of freshly opened notebooks/Trusting notebooks

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#473]
Jupyter has a "Trust" mechanism which prevents arbitrary code being run by a notebook.

Where is this necessary? Suppose I download a .jl notebook from some website, and the first cell has some malicious code which I definitely don't want to run.

A similar but different issue is when my first cell does something which blocks any changes being made to the notebook.
One contrived example is if there is an infinite loop in the first cell, then opening that book is impossible.

So a simple "Run Whole Book" button should be added which runs the whole book if the user wishes, and when opening, autorun does not happen.

**Comment by fonsp** [comment]
Thanks! Have a look here: #259
