### ISSUE TITLE
Option to have linear cell dependency?

### ISSUE THREAD

**Issue by kapple19** [fonsp/Pluto.jl#481]
Sometimes I *do* want my Pluto notebook to read like a book or article, code-wise. Can we have the option of enforcing a top-to-down cell dependency? It might even make the cell parsing faster (which is already fast though).

**Comment by fonsp** [comment]
Can you post this in the feedback system instead? https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439
