### ISSUE TITLE
"Undo" delete fails when multiple cells are deleted

### ISSUE THREAD

**Issue by ekzhang** [fonsp/Pluto.jl#482]
When more than one cell is deleted at a time, i.e., in `confirm_delete_multiple()`, the "Undo" button that pops up doesn't work. It only restores zero/one of the deleted cells, and it also can sometimes crash the notebook.

### Steps to reproduce

- Select >1 cell at the end of the notebook
- Press delete, confirm delete in the popup
- Press "Undo" in the lower left corner

### Possibly related error logs

![image](https://user-images.githubusercontent.com/7550632/94085193-00b1d980-fdcd-11ea-8598-f448a853b4bf.png)

**Comment by fonsp** [comment]
It can crash the notebook? 😬

**Comment by ekzhang** [comment]
Er, it spewed a bunch of errors in the console, and I wasn't able to interact with the notebook killing the server and restarting. Not sure exactly what went wrong though.

**Comment by fonsp** [comment]
Interesting! Be sure to save those the next time

**Comment by ekzhang** [comment]
Yep, can you reproduce?

I just created this issue because "Undo" seems like its own whole thing separate from the rest of the cut/copy/paste stuff.

**Comment by fonsp** [comment]
Fixed!
