### ISSUE TITLE
Weird syntax highlighting in string interpolation

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#483]
A cell with `"$("abc-def")"` as its content is highlighted like this:
![image](https://user-images.githubusercontent.com/687995/94143928-285e7b80-fe79-11ea-8887-8cdef000eec9.png)
It does not affect any of the functionality, but I would guess this is unexpected.

**Comment by fonsp** [comment]
Can you submit this issue to [CodeMirror](https://github.com/codemirror/CodeMirror/)?
