### ISSUE TITLE
Multiple notebooks installing packages in parallel can break

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#485]
I've seen it happen once 👀

**Comment by shashankp** [comment]
I guess notebook on the right is **worker 3**
![image](https://user-images.githubusercontent.com/498813/94185964-ae9faf80-fec3-11ea-8a9c-fa0a60c9dd6a.png)

**Comment by Moelf** [comment]
https://github.com/simonbyrne/PkgLock.jl
https://discourse.julialang.org/t/distributed-packages-and-race-condition-in-pre-compiling/43340
I guess this is what it is with `Distributed.jl`, not something we can fix here in Pluto.

Maybe advise user to use `PkgLock` at the mean time if they have multi-user situation. (much like HPC use-case, where this error is reported the most)

**Comment by fonsp** [comment]
It caused this error on windows:

SystemError: opening file "C:\\Users\\fonsv\\.julia\\registries\\General\\Registry.toml": No such file or directory

**Comment by fonsp** [comment]
> not something we can fix here in Pluto.

I disagree, we can and should fix it inside Pluto

**Comment by fonsp** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/2219

**Comment by fonsp** [comment]
Solved if you use #844

**Comment by fonsp** [comment]
This has been solved by Pluto's built-in package manager, which uses a global lock to ensure that only one notebook's package environment is being processed at the same time, all other notebook evaluation happens in parallel.

This can still be an issue when you run multiple notebooks in parallel which set up their own package environment using `Pkg.activate`.

**Comment by fonsp** [comment]
I am facing the same problem in PlutoSliderServer, you can follow https://github.com/JuliaPluto/PlutoSliderServer.jl/issues/36 for updates
