### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#49]
Let's do this thing!

CodeMirror side - options: 
- [show-hint.js](https://codemirror.net/doc/manual.html#addon_show-hint)
- DIY

Julia side - options: 
- look at how the REPL does it - _lightweight option_
- integrate the [microsoft Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (used by VS Code, Atom and some others) - _feature complete option_
- run the LSP implementation from Juno or VS Code without using the LSP - _maybe the easier option_

**Comment by malyvsen** [comment]
I also volunteer to make AI autocompletion! For starters, it could just take syntactically viable completions and rank them.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/78401137-582e7400-75f8-11ea-9ec5-a0efcb225288.png)

**Comment by fonsp** [comment]
Much easier than expected! You can use the autocomplete system from the REPL: [Completions.jl](https://github.com/fonsp/Pluto.jl/blob/75dd4db01150bb53bb3d7c83d73e75ffaadc0870/src/webserver/Completions.jl)

**Comment by fonsp** [comment]
It even has latex autocomplete! julia is cool 🌈
