### ISSUE TITLE
Input to cell broken after deleting parenthesis

### ISSUE THREAD

**Issue by RomansWorks** [fonsp/Pluto.jl#491]
Hello, first time user here, so first of all - kudos for the great work!

My setup: Julia 1.5.1, Chrome Version 85.0.4183.83, Pluto version - unknown? Probably latest, any way to tell from within the notebook?

I've came across an issue with broken input functionality while deleting parenthesis in a cell. 

Here's how to reproduce:

1. Create a new cell with the following text: `Something{(other),()}()`
2. Place the cursor before the 'o' of `other` and press backspace once. 
The cell will become stuck.

**Comment by Pocket-titan** [comment]
Thanks for opening an issue! This appears to be the same problem as in https://github.com/fonsp/Pluto.jl/issues/490, so let's maybe track it there.

**Comment by RomansWorks** [comment]
Sure thing, looks the same :) 

Will you close this one as duplicate?
