### ISSUE TITLE
Opening Github /raw links doesn't work

### ISSUE THREAD

**Issue by musabkilic** [fonsp/Pluto.jl#492]
Hi! I was working on this issue on the [18S191 repository](https://github.com/mitmath/18S191/issues/23) and I realized that the links in the form of github.com / *author* / *repo* / raw / ..... , doesn't open. 

I believe the problem can be solved by removing the "/raw" part from the URL path similar to what Pluto already does to /blob links. 
https://github.com/fonsp/Pluto.jl/blob/df1fc957370027f3b459535893798eee4f9637a2/frontend/components/Welcome.js#L55-L58

**Comment by fonsp** [comment]
What is a `/raw` link?

**Comment by musabkilic** [comment]
/blob https://github.com/fonsp/Pluto.jl/blob/master/sample/Basic.jl
/raw https://github.com/fonsp/Pluto.jl/raw/master/sample/Basic.jl

I'm referring the normal Github interface webpage as a /blob link, and the raw file as a /raw link. A /raw link redirects to https://raw.githubusercontent.com. Sorry if my wording/naming is confusing.

**Comment by fonsp** [comment]
If this is already a raw link, then it already works, right? You can paste any link to a `.jl` file, there are just 2 special cases to turn github links into raw links.

**Comment by musabkilic** [comment]
That's what I and I think presumably @zmoon thought, too. And I started changing the links in the 18S191 website to sent a pull request and before sending one I tried and I saw that Pluto doesn't work the way I thought it would.

Here is how Pluto handles https://github.com/fonsp/Pluto.jl/raw/master/sample/Basic.jl .

1- It detects that this is a github.com link
2- Replaces github.com part with raw.githubusercontent.com
3- There is no /blob part so we are done

Then Pluto tries to open https://raw.githubusercontent.com/fonsp/Pluto.jl/raw/master/sample/Basic.jl but Github returns 404 error because this is an invalid link. The correct link is at https://raw.githubusercontent.com/fonsp/Pluto.jl/master/sample/Basic.jl, notice the /raw part missing.

https://github.com/fonsp/Pluto.jl/blob/df1fc957370027f3b459535893798eee4f9637a2/frontend/components/Welcome.js#L55-L58
