### ISSUE TITLE
Race condition when removing cells

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#497]
_Originally posted by @GiggleLiu in https://github.com/fonsp/Pluto.jl/pull/489#issuecomment-699543292_

You can reproduce it by

Step 1: open this notebook in Pluto, you will see a sin curve
https://gist.github.com/GiggleLiu/043e43d47439c36e211ad86f7b3be1d6

Step 2: select the "cos" curve. You will see the curve switching between "sin" and "cos". This is expect, because this cell refreshes itself.

Step 3: error the code. e.g. remove the string "Bond" in the bottom cell, and press "Ctrl-S". Then you will reproduce the freezing moment. If it does not freeze, restore the bottom cell by "Ctrl-Z, Ctrl-S" and repeat steps 2-3 multiple times.

> Does this happen often?

When focusing on some projects with Pluto, I need to restart freezing sessions more than 10 times a day. But not sure all these have the same cause. I will pay more attention to these error messages.

**Comment by GiggleLiu** [comment]
NOTE: In case it is OS related, my OS is Ubuntu 20.04

**Comment by fonsp** [comment]
I can't reproduce this on `main`, @GiggleLiu how about you?

Here is the fixed notebook:
```
# ╔═╡ af79a655-4666-4ba4-99da-1ec897c8a8d4
md"# Pluto as a stateful machine"

# ╔═╡ 3c01b6cc-5a4a-4aec-a2f0-bbf537d1c9de
using Plots, PlutoUI

# ╔═╡ e5ddb52d-73e7-4516-b7d2-d796f6336959
# 1. Define internal states
state = Dict("func"=>"sin");

# ╔═╡ 3bc539fa-87f4-4457-94f3-ab756d9ae83e
# 2. Define widgets
# func_select = @bind do_func Select(["sin", "cos"]; default=state["func"])

# ╔═╡ a6bec471-cb5c-4664-affe-e4d9db7e8716
# 4. rendering layout
function plot_panel()
	z = 1:5
	html(plot(z, eval(Symbol(state["func"])).(z) .+ 0.1*randn(length(z)); label=state["func"]))
end;

# ╔═╡ 65f9a3fe-da7d-436d-918d-af0c06f24e08
let
	if @isdefined(do_func)
		state["func"] = do_func;
	end
	b = @bind do_func Select(["sin", "cos"]; default=state["func"])
	HTML("""
<table style="border:0">
<tr>
<td>function = $((html(b)))</td>
</tr>
</table>
		
<table style="border:0">
<tr>
<td>$(plot_panel())</td>
</tr>
</table>
""")
end

# ╔═╡ 88f5ca49-3977-4af1-9e9c-3a6c2b0deafa


```
