### ISSUE TITLE
Rename notebook file UI

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#50]
A way to change the path of a running notebook.

I suggest that this will **move** the file, not **copy** it.

Needs to report to the user whether the path is legal, and prompt whether they want to override.

**Comment by malyvsen** [comment]
Yes, I agree it should move the file rather than copying it. We could also have a separate "make a copy" feature though, which would work like Google Docs - opening a new copy in a new tab.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/78939663-dbe2d780-7ab4-11ea-8a2f-0d6fb1b09b39.png)
