### ISSUE TITLE
[dev] Cell.js - is_hidden is always false

### ISSUE THREAD

**Issue by pupuis** [fonsp/Pluto.jl#500]
Hi,

while working on Cell.js I realised that it seems that is_hidden for CellInput always evaluates to false as it contains the condition ```class_code_folded && !class_code_folded```. I suppose that this is a typo? However, I wouldn't know how to fix it, as I cannot recognise what was originally intended. I think this was introduced in a recent commit.

Thank you in advance for looking into it.

Best

**Comment by fonsp** [comment]
Oops! Feel free to fix it

**Comment by pupuis** [comment]
Yeah, sure ☺️ Do you know what is intended? There is also ```class_code_differs```, maybe that was also intended to be included in that condition? 

I'll have a look if I maybe can infer from context what was meant and check out the pr that introduced it 👍🏼
