### ISSUE TITLE
Feature request: allow scrolling past last cell

### ISSUE THREAD

**Issue by kzvi** [fonsp/Pluto.jl#503]
First of all I want to say that I absolutely love this software and thanks for making it!

It would be really nice if it were possible to scroll the page down until the bottom of the last cell is at the top of the page, like how text editors such as VSCode work. That way you are not having to type at the very bottom of the screen when editing the last cell.

**Comment by fonsp** [comment]
Thank you the request! Can you post this to the [built in suggestion box](https://github.com/fonsp/Pluto.jl/issues/182) instead? There is no obvious yes or no to this question, but we should come back to it later.
