### ISSUE TITLE
Programmatically export static HTML from Pluto notebook to deploy with docs.

### ISSUE THREAD

**Issue by lassepe** [fonsp/Pluto.jl#506]
Over at [ParticleFilters.jl](https://github.com/JuliaPOMDP/ParticleFilters.jl/) we would like to use Pluto as an "executable documentation" for our repo. Up to now we are using Jupyter notbooks for this which has the benefit that users can view the notebook directly in the browser (of course only the static, non-interactive version) without the need to download or run anything.

Of course a 1-click deploy to project binder would solve this issue, however, for our use case it would be totally sufficient to just programmatically  export the notebook to static HTML.
Ideally, I am envisioning to export the notebook to HTML automatically through the CI job that also builds the documentation (i.e. as part of `docs/make.jl`). Is there any way to do achieve this, or is something like this planned for the future?

**Comment by fonsp** [comment]
Currently not possible, but it is planned:
https://github.com/fonsp/PlutoUtils.jl/issues/8

Could you add your comment about CI?
