### ISSUE TITLE
Run .julia/config/startup.jl at startup

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#509]
In my startup file, I have currently defined a function ```frac(a, b) = /(a, b)```.  This function works in VSCode and in the REPL at startup, but not in pluto. Does that mean that Pluto does not have that file executed at startup? It seems odd, as I launch pluto.jl with a function from my startup.jl file, and I thought that the terminal I launch from is the kernel for my notebook. Does anyone know what might be the case?

**Comment by shashankp** [comment]
The terminal isn't the kernel; Pluto creates a `Workspace` for each notebook to run in.
It does run a startup scripts when creating a new `Workspace`, but `.julia/config/startup.jl` isn't one of those.

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/165#issuecomment-640936613
