### ISSUE TITLE
Problem with similar functor definitions

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#510]
I use function-like objects / functors for stateful controllers in simulations and got what I believe to be an incorrect `Multiple definitions` message. In this MWE, there are two struct definitions and a functor defined for each, but I happened to use the same local variable in the functor definitions. Workaround is to use different local names but I shouldn't have to, right?

```
### A Pluto.jl notebook ###
# v0.11.14

using Markdown
using InteractiveUtils

# ╔═╡ 02ac9270-033b-11eb-354c-6347c53236ad
struct MyStruct1
	value
end

# ╔═╡ 159badce-033b-11eb-2c90-11c743a7e6a7
struct MyStruct2
	value
end

# ╔═╡ 61337c50-033b-11eb-1164-4b5d907cb52c
function(c::MyStruct2)()
	return c.value+2
end

# ╔═╡ 1d0bd2c0-033b-11eb-3b10-cd74f211c983
function(c::MyStruct1)()
	return c.value+1
end

# ╔═╡ Cell order:
# ╠═02ac9270-033b-11eb-354c-6347c53236ad
# ╠═1d0bd2c0-033b-11eb-3b10-cd74f211c983
# ╠═159badce-033b-11eb-2c90-11c743a7e6a7
# ╠═61337c50-033b-11eb-1164-4b5d907cb52c
```

**Comment by fonsp** [comment]
The is the same issue as https://github.com/fonsp/Pluto.jl/issues/288, but you point out some syntax that i did not know about, thanks!
