### ISSUE TITLE
Print function does not display anything in the notebook

### ISSUE THREAD

**Issue by RafailFridman** [fonsp/Pluto.jl#512]
Hello!
I'm on Windows 10, installed Julia on WSL (Ubuntu), and running Pluto notebook via `Pluto.run(1234)` from Julia REPL. But unfortunately, the `print` function apparently does not work:
![image](https://user-images.githubusercontent.com/22198039/94728038-49870680-0368-11eb-82e1-7cbdeea19143.png)
Is it supposed to be like this? If yes, then what should I use for printing something out?

**Comment by j-fu** [comment]
Yes.
You will see the output in the console window where you started Pluto.
With `using PlutoUI` you can write
````
with_terminal() do
    f(123)
end
````
There is the pending PR  https://github.com/fonsp/PlutoUI.jl/pull/40 which adds a height limitation to the output.

The idea behind is to force us to present calculation data in a better way than to just print some ascii strings. For me this is an interesting challenge which may lead to better ways to present results...

**Comment by RafailFridman** [comment]
@j-fu Thanks! It will be an interesting challenge indeed :)
By the way, just to not open another issue:
Is it possible to open a Pluto notebook without running all of the code inside of it?

**Comment by j-fu** [comment]
See e.g. #298 and https://github.com/fonsp/PlutoUI.jl/issues/46
I would say this is being discussed.
What I am doing for the time being is with PlutoUI:
````
@bind  go_for_it CheckBox(false)
````
````
if go_for_it
    run_next_calculation()
end
````

**Comment by fonsp** [comment]
Thanks for the discussion!
