### ISSUE TITLE
Visually shrunken tuples of LaTeXStrings

### ISSUE THREAD

**Issue by stillyslalom** [fonsp/Pluto.jl#513]
When showing a tuple of multiple LaTeXStrings, the output shrinks past the point of legibility for larger expressions.

![image](https://user-images.githubusercontent.com/4324760/94748094-1df32480-0346-11eb-8da8-0cfe07231050.png)

Not sure what the right behavior is - vertical, sequential display?

**Comment by fonsp** [comment]
The right behavior would be the same, but without shrinking, right?

Just like:

```
fn = md"hello ``\frac{\sqrt{1}}{2}``"
```

```
(fn, fn, fn)
```

**Comment by stillyslalom** [comment]
Yes, as long as it wraps onto the next line if the tuple's contents are too small to fit on one line.

**Comment by fonsp** [comment]
It won't wrap, that's not how Pluto's interactive inspector works.

**Comment by stillyslalom** [comment]
That's probably fine - users can destructure the tuple into multiple cells if necessary. The main thing is that math output ought to not shrink.

**Comment by Moelf** [comment]
@fonsp 
![image](https://user-images.githubusercontent.com/5306213/95410399-d8a89700-08f1-11eb-8282-f10e7807c537.png)
we're already not shrinking. It appears so because height

**Comment by fonsp** [comment]
we are if the equation is too wide
