### ISSUE TITLE
How to make a self refreshing cell work?

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#515]
I suppose the following code should memorize the previous choice, but it turns out not.

```julia
using PlutoUI

state = Ref("a");

xb = @bind x Select(["a", "b"], default=state[]);

btnb = @bind btn Button();

state[] = x

let
    btn
    HTML("""
$(html(PlutoRunner.Bond(Select(xb.element.options, state[], xb.element.attributes), :x)))
$(html(btnb))
""")

end
```

![self-refresh](https://user-images.githubusercontent.com/6257240/94762890-e3ee4680-0376-11eb-9407-740cbd3a4d0d.gif)

Is it possible to make it memorize previous choice?

**Comment by dralletje** [comment]
Not yet. Still figuring out a nice way to have this work with Pluto...

Currently for me this example even ends up in an infinite loop just because of the button... hahaha

**Comment by fonsp** [comment]
Here is a summary of what is possible today:

(@GiggleLiu this is what I showed today)

https://github.com/fonsp/disorganised-mess/blob/master/bind_wizardry.jl

**Comment by GiggleLiu** [comment]
Perfect. I also tried my previous self-refreshing script
```julia
julia> using Pluto

julia> Pluto.run(notebook="https://gist.githubusercontent.com/GiggleLiu/7ab57094475d0a496112807d3235b8f5/raw/1e1442a1ffc5631ca8b498255141335ac77bcda9/stateful_pluto.jl")
```

It works too! Thank you for your effort. We can close this issue now I guess?

**Comment by fonsp** [comment]
Yes! There are still some "self refreshing" concepts that we don't support yet but let's discuss that somewhere else

**Comment by GiggleLiu** [comment]
![updateself](https://user-images.githubusercontent.com/6257240/113466991-0fc5b400-940e-11eb-9902-c7835b1ee22e.gif)

Hi, is there a regression in recent versions?

**Comment by fonsp** [comment]
I need a bit more context

**Comment by GiggleLiu** [comment]
Try this
```
# ╔═╡ 956ef6f6-b7c4-460d-8e87-8af6546a895e
using PlutoUI

# ╔═╡ af650bea-94f5-11eb-1ff6-d50dca0c537d
w = @bind x Slider(0:0.1:1);

# ╔═╡ 55fceaf0-7b8c-4dc9-86d8-28f99d0ec329
let
	md"$(2x) $w"
end
```
