### ISSUE TITLE
changing keyboard mappings for personal use

### ISSUE THREAD

**Issue by erentar** [fonsp/Pluto.jl#523]
the project seems reluctant to provide an option change the keyboard shortcuts to the industry standard, i'd like to do it myself. Where are the keyboard shortcuts defined in the code?

**Comment by Pangoraw** [comment]
You can modify the key bindings on your local version by modifying [CellInput.js](https://github.com/fonsp/Pluto.jl/blob/master/frontend/components/CellInput.js#L69-L70)
```diff
-            keys["Shift-Enter"] = () => on_submit(cm.getValue())
-            keys["Ctrl-Enter"] = () => {
+            keys["Ctrl-Enter"] = () => on_submit(cm.getValue())
+            keys["Shift-Enter"] = () => {
```

**Comment by fonsp** [comment]
#56

**Comment by erentar** [comment]
Thanks!
