### ISSUE TITLE
Variable value cannot be changed in other cells

### ISSUE THREAD

**Issue by liuwa666** [fonsp/Pluto.jl#524]
After using Pluto, I like it very much, but there is a problem now that I cannot change the variables defined in other cells before.

For example, if I want to implement the function of automatically increasing the number of a graph, I define a variable $(figSN) at the beginning, and use it later when needed:
```julia
### A Pluto.jl notebook ###
# v0.11.14

using Markdown
using InteractiveUtils

# ╔═╡ ff20bc00-048c-11eb-163a-f92638ffc353
using PlutoUI;

# ╔═╡ 98d0cce0-048e-11eb-3102-cdb3fead1d13
figSN = 0;

# ╔═╡ 9eb15120-048e-11eb-295d-9194e2523559
tableSN = 0;

# ╔═╡ be566f70-04a6-11eb-2513-91d88ed3f1fa
begin
	md"Figure $(figSN+=1)  "
end

# ╔═╡ Cell order:
# ╠═ff20bc00-048c-11eb-163a-f92638ffc353
# ╠═98d0cce0-048e-11eb-3102-cdb3fead1d13
# ╠═9eb15120-048e-11eb-295d-9194e2523559
# ╠═be566f70-04a6-11eb-2513-91d88ed3f1fa
```
This is not working, how do you deal with situations like this

**Comment by Pangoraw** [comment]
Unfortunately, you cannot change a variable value in another cell in cells others than the one it has been assigned in. This would break reactivity (the fact that all cell referencing a variable are re-executed when this variable changes).

For alternate solutions, you can take a look at [the wiki](https://github.com/fonsp/Pluto.jl/wiki/%E2%9A%A1-Writing-and-running-code) where several solutions are proposed :zap: in the section "_How can I modify a variable in a different cell?_"

**Comment by liuwa666** [comment]
> Unfortunately, you cannot change a variable value in another cell in cells others than the one it has been assigned in. This would break reactivity (the fact that all cell referencing a variable are re-executed when this variable changes).
> 
> For alternate solutions, you can take a look at [the wiki](https://github.com/fonsp/Pluto.jl/wiki/%E2%9A%A1-Writing-and-running-code) where several solutions are proposed ⚡ in the section "_How can I modify a variable in a different cell?_"
thanks

**Comment by liuwa666** [comment]
@Pangoraw thanks
