### ISSUE TITLE
Don't assume Plutos deps are available from toplevel

### ISSUE THREAD

**Issue by fredrikekre** [fonsp/Pluto.jl#542]
Running Julia with a custom load path doesn't work since Pluto assumes that it can load stdlibs from toplevel.

**Comment by fonsp** [comment]
If the stdlibs ([listed here](https://github.com/fonsp/Pluto.jl/blob/v0.12.0/src/runner/PlutoRunner.jl#L10-L17)) aren't available to the runner process, then is there any way to load them anyways? Otherwise a custom load path is just not supported.

**Comment by fredrikekre** [comment]
You can presumably load them from the Pluto namespace (see e.g. https://github.com/JuliaLang/IJulia.jl/pull/951)

**Comment by fonsp** [comment]
`Pluto` isn't loaded on the notebook process (Distributed), it only loads one file: https://github.com/fonsp/Pluto.jl/blob/master/src/runner/PlutoRunner.jl

**Comment by fonsp** [comment]
(I don’t know how to fix this.)

**Comment by fonsp** [comment]
@Roger-luo any ideas?

**Comment by Roger-luo** [comment]
I guess the solution is to let Pluto workspace runner use a Pluto specific environment to launch processes, then each process will own their own project? I'm not sure if I understand the problem correctly tho @fredrikekre

**Comment by KristofferC** [comment]
You cannot really start a new process and import a bunch of packages at the top level, the environment system doesn't work like that. Starting a new process, importing Pluto, and accessing everything from that would be the correct way according to how the environment system works.

**Comment by fonsp** [comment]
Thanks everyone!

**Comment by fonsp** [comment]
_(note to self/contributors)_

I tested it like so:

```julia
fons@woof:~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0-rc1.0 (2020-06-26)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> activate --temp
 Activating new environment at `/tmp/jl_a0cvvq/Project.toml`

(jl_a0cvvq) pkg> dev /home/fons/Pluto.jl
...

julia> LOAD_PATH
3-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"

julia> deleteat!(LOAD_PATH, 2)
2-element Array{String,1}:
 "@"
 "@stdlib"

julia> deleteat!(LOAD_PATH, 2)
1-element Array{String,1}:
 "@"

julia> import Pluto; Pluto.run()
```


this gave:
![image](https://user-images.githubusercontent.com/6933510/98255672-f19e7980-1f7d-11eb-93b5-d149f46f8a58.png)

**Comment by fonsp** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/82ed697f2ec593c925567a7af9da6d7dbba2b9d4
