### ISSUE TITLE
blank notebook screen when launching offline

### ISSUE THREAD

**Issue by ixzh** [fonsp/Pluto.jl#552]
I've been using Pluto with Internet with no problem.

Just today I started everything with my laptop offline. the frontpage can still be loaded, but can not create new or open any existing notebook (which opens a blank page).

then I connected to Internet, things are back to normal. the page can be loaded.

so is Internet is required for first launching?  I'm on Windows 10.

**Comment by Moelf** [comment]
> so is Internet is required for first launching?

yes, after the first run the resources should be cached by your browser.

Devs are looking to use [Artifacts](https://julialang.github.io/Pkg.jl/v1/artifacts/) to ship those .js so Pluto can be used offline. (or so I heard)

**Comment by ixzh** [comment]
noted and thanks. Will close.
