### ISSUE TITLE
can't run and add cell

### ISSUE THREAD

**Issue by YTCAI** [fonsp/Pluto.jl#553]
0.12.3 is not stable, sometimes it can't run and add cell or even send out feedback! close it and reopen can solve it, but it happens again sometimes.

**Comment by fonsp** [comment]
I'm sorry to hear that, could you give some more info?

- What browser do you use? What version?

- What do you reopen to solve it? The browser or the Pluto server?

- Maybe you could describe the issue in more detail. What does it look like when you can't run a cell? Are there other things that still work?

**Comment by YTCAI** [comment]
Hi Fons,
Thanks for your reply,
normally I use safari cause it is default one, newest version. sometimes use chrome.


I closed both notebook and server, and reopen them again to solved it.
when I click the plus sign to add or press shift+return button to run a cell, it does not react at all.
Btw,I love Pluto, it is an exceptional product, great job!
When can we export reactive content as video?
Kind regards
Yitao Cai





---Original---

**Comment by fonsp** [comment]
Thanks! Could you try to narrow it down?

- On which of the two browsers does the problem occur?

- Does it happen on every notebook, or a specific one?

- Is the window completely frozen? Can you still type text?

# But most importantly:

It would be really helpful if you could **share the output of the browser developer console after it crashes**:

Press `Command+Option+J` to open the console. For me it looks like this:

![image](https://user-images.githubusercontent.com/6933510/95578851-e450a680-0a34-11eb-9b62-e03eaa3a21cb.png)

Take a screenshot and send it to us.

Similarly, the **output of the terminal where you launched Pluto** would be very helpful. It looks like this:

![image](https://user-images.githubusercontent.com/6933510/95578998-1cf08000-0a35-11eb-95ad-ded721d02b35.png)

**Comment by YTCAI** [comment]
Hi Fons,
The error was in Safari. and until now it does not happen again, I thought it probably is a problem of my computer.&nbsp; the window wasn't frozen,I can type words.


I just run into some new error which is attached here.




and in Julia REPL
there are error messages as following when I opened homework3.jl from MIT computational thinking course.



┌ Warning: Reading WebSocket client stream failed for unknown reason:

│ &nbsp; exception =

│&nbsp; &nbsp; IOError: read: connection reset by peer (ECONNRESET)

│&nbsp; &nbsp; Stacktrace:

│ &nbsp; &nbsp; [1] wait_readnb(::Sockets.TCPSocket, ::Int64) at ./stream.jl:350

│ &nbsp; &nbsp; [2] eof at ./stream.jl:48 [inlined]

│ &nbsp; &nbsp; [3] eof(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}) at /Users/mindy/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:199

│ &nbsp; &nbsp; [4] eof at /Users/mindy/.julia/packages/HTTP/IAI92/src/WebSockets.jl:251 [inlined]

│ &nbsp; &nbsp; [5] (::Pluto.var"#208#215"{Pluto.ServerSession,Base.RefValue{Function}})(::HTTP.WebSockets.WebSocket{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/mindy/.julia/packages/Pluto/R8t0Y/src/webserver/WebServer.jl:139

│ &nbsp; &nbsp; [6] upgrade(::Pluto.var"#208#215"{Pluto.ServerSession,Base.RefValue{Function}}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}; binary::Bool) at /Users/mindy/.julia/packages/HTTP/IAI92/src/WebSockets.jl:160

│ &nbsp; &nbsp; [7] upgrade at /Users/mindy/.julia/packages/HTTP/IAI92/src/WebSockets.jl:142 [inlined]

│ &nbsp; &nbsp; [8] (::Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /Users/mindy/.julia/packages/Pluto/R8t0Y/src/webserver/WebServer.jl:134

│ &nbsp; &nbsp; [9] handle at /Users/mindy/.julia/packages/HTTP/IAI92/src/Handlers.jl:269 [inlined]

│ &nbsp; &nbsp; [10] #4 at /Users/mindy/.julia/packages/HTTP/IAI92/src/Handlers.jl:345 [inlined]

│ &nbsp; &nbsp; [11] macro expansion at /Users/mindy/.julia/packages/HTTP/IAI92/src/Servers.jl:367 [inlined]

│ &nbsp; &nbsp; [12] (::HTTP.Servers.var"#13#14"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:356

└ @ Pluto ~/.julia/packages/Pluto/R8t0Y/src/webserver/WebServer.jl:180

┌ Error: Download failed: curl: (7) Failed to connect to ia800303.us.archive.org port 443: Connection refused

└ @ Base download.jl:43










------------------&nbsp;Original&nbsp;------------------

**Comment by fonsp** [comment]
It looks like you sent the screenshot using an email, but you need to visit github.com to send images. Can you try that?

**Comment by YTCAI** [comment]
I can open it in chrome by copying the link listed in REPL when run Pluto.run().
I used to open it in chrome by typing localhost:1234. but it is ok for me.
![QQ20201010-081343@2x](https://user-images.githubusercontent.com/65641330/95640998-51664980-0ad2-11eb-9bcf-f8b5fb096e23.jpg)

**Comment by fonsp** [comment]
I need to see a screenshot of the error that you talked about: https://github.com/fonsp/Pluto.jl/issues/553#issue-717830729

**Comment by YTCAI** [comment]
It does not happen again, it might be a problem of my computer yesterday.



---Original---
