### ISSUE TITLE
Plotly (and PlotlyJS) don't appear in static HTML

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#555]
^ title 📉

This is related to:
- #108 
- #457 

MWE:
```julia
### A Pluto.jl notebook ###
# v0.12.3

using Markdown
using InteractiveUtils

# ╔═╡ 3c79b212-0a72-11eb-236d-7902a0104d26
using Plots

# ╔═╡ 45d77630-0a72-11eb-3b86-51a988c82855
plotlyjs() # same with plotly()

# ╔═╡ c0250db2-0a74-11eb-0707-49cc70509019
plot(Plots.fakedata(50,5))

# ╔═╡ Cell order:
# ╠═3c79b212-0a72-11eb-236d-7902a0104d26
# ╠═45d77630-0a72-11eb-3b86-51a988c82855
# ╠═c0250db2-0a74-11eb-0707-49cc70509019
```

In notebook:
![image](https://user-images.githubusercontent.com/1592413/95633525-b1121580-0a3c-11eb-8a1b-6d699451406b.png)

Output when saved as static HTML:
![image](https://user-images.githubusercontent.com/1592413/95633496-a0619f80-0a3c-11eb-90c3-58f2c2d7473a.png)

**Comment by fonsp** [comment]
Do you see anything in your browser console? Ctrl+Shift+J or Cmd+Option+J

**Comment by mossr** [comment]
Nothing looks funny to me:

![image](https://user-images.githubusercontent.com/1592413/95638784-baa27a00-0a4a-11eb-8d17-c14b179bc90d.png)

(This is before generating the HTML _and_ after)

**Comment by fonsp** [comment]
And what about the window where you open the static HTML export? Maybe you can send the file?

**Comment by mossr** [comment]
Good point! I get this:
> Not allowed to load local resource: blob:http://localhost:1234/c1c82254-b6dc-43bb-af39-82c2d421532b     plotly.html:154 


(Github doesn't support .html files, so just change this `.log` extension to `.html`)
[plotly.log](https://github.com/fonsp/Pluto.jl/files/5358084/plotly.log)

**Comment by holomorphism** [comment]
I've seen the same problem since commit 7cc235f.
In earlier versions, it worked in the exported html file (I used plotly()).

**Comment by dralletje** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/28202b1cc27708aceef13869a5299e3b04272049
