### ISSUE TITLE
Formatting Live Docs

### ISSUE THREAD

**Issue by kellertuer** [fonsp/Pluto.jl#558]
I love the Live Docs, they are really useful, both when writing a notebook as well as when talking with students, because one can view stuff just live (i.e. without typing `? Sphere`). With `0.12.x` the style has already improved, but I noticed two things that are slightly strange.

In the following screenshot, I am looking at the Live docs of our sphere https://juliamanifolds.github.io/Manifolds.jl/stable/manifolds/sphere.html#Manifolds.Sphere. The Live docs look like (using Pluto `12.3`)

<img width="1119" alt="Bildschirmfoto 2020-10-10 um 11 14 47" src="https://user-images.githubusercontent.com/115566/95651393-68b13100-0aea-11eb-8bd9-00a440dd1df3.png">

There is two things that are a little strange

1. code that is within text seems to be a little too large (see `ArraySphere` and the following `n`) 
2. in the original docs (see link above) `ArraySphere` links to that type. I am not sure this can be automatically linked (that would be awesome!) but a current link to `http://localhost:1234/@ref` is misleading.

**Comment by fonsp** [comment]
@dralletje didn't you break&fix point 2?

**Comment by fonsp** [comment]
as for point 1: we use `font-size: 0.75em` in `pluto-output code` but forgot it in the docs

**Comment by dralletje** [comment]
Point 2 should be fixed, but the url still _looks like_ it points to `/@ref` (because we use onClick and don't change the href)
I'll change the href so it is more clear as well.

**Comment by kellertuer** [comment]
Ah! Clicking on ArraySphere actually loaded ArraySphere-docs – awesome! I was then just confused by th url display in the status bar below (which still displayed the `/@ref` so I did not even bother to click.

**Comment by fonsp** [comment]
I actually don't like the typography in live docs, it looks like a quick hack to reuse the notebook's styles. Maybe we should use Lato and make it look like Documenter docs: https://julialang.github.io/Pkg.jl/v1/getting-started/

**Comment by kellertuer** [comment]
Since I usually check my docs (a lot) how they look in Documenter, I would appreciate the effort to get a look similar to that :)

**Comment by dralletje** [comment]
Don't want to be too strict and stuff, but I'm going to close this issue and point us to one specific about Documenter.jl: https://github.com/fonsp/Pluto.jl/issues/562
