### ISSUE TITLE
Making executable file

### ISSUE THREAD

**Issue by buttercrab** [fonsp/Pluto.jl#560]
I think it would be great if we could run pluto right in terminal

ex) **pluto** in PATH
```julia
#!/usr/bin/env julia

using Pluto
Pluto.run()
```

then we could install this file and run like below.

```bash
> pluto
```

**Comment by fonsp** [comment]
That's great! What is your question/suggestion exactly?

Also have a look here: https://github.com/fonsp/PlutoUtils.jl#pluto-cli

**Comment by buttercrab** [comment]
That was what I needed. Thanks!

**Comment by ndgnuh** [comment]
Sorry for digging this up, now Julia 1.12 supports executable and `PlutoUtils` is unsupported, should we re-open this issue?
