### ISSUE TITLE
Can't re-evaluate cells containing `Sympy.@vars`

### ISSUE THREAD

**Issue by stillyslalom** [fonsp/Pluto.jl#561]
SymPy.jl exports a `@vars` macro to simplify `x, y, z = Sym("x y z")` into `@vars x y z`, but it can't be run more than once because of Pluto's encapsulation of cells into their own modules:
![image](https://user-images.githubusercontent.com/4324760/95661163-d2cdd400-0af2-11eb-9d24-7ccfcbf58254.png)
(first run)

![image](https://user-images.githubusercontent.com/4324760/95661174-e2e5b380-0af2-11eb-8675-10dedbe4a91b.png)
(second run)

**Comment by mcabbott** [comment]
xref https://github.com/fonsp/Pluto.jl/issues/196 . 

Do you know of any other packages using a macro called `@vars`?

**Comment by stillyslalom** [comment]
Not off the top of my head. I'll close this for now - seems like the issue is well-explored in #196.
