### ISSUE TITLE
Remove stale notebooks from "Recent sessions"

### ISSUE THREAD

**Issue by stillyslalom** [fonsp/Pluto.jl#563]
When a new notebook is created, it's stored in a temporary directory by default. Even after the temporary directory is purged, the purged notebooks are still visible within Recent Sessions, which gets cluttered with useless entries:
![image](https://user-images.githubusercontent.com/4324760/95663157-5c38d280-0b02-11eb-9f55-9bce98bf542f.png)

It'd be good to check the recent sessions files with `ispath` upon startup, and remove everything without a valid path.

**Comment by j-fu** [comment]
Once this has been opened - I think  there should be some editing capabilities for this list. A delete button IMHO would suffice for start.

I helped my self so far with browser tools for local storage editing, e.g. https://developers.google.com/web/tools/chrome-devtools/storage/localstorage

**Comment by fonsp** [comment]
Notebooks are no longer stored in a temporary directory :)

**Comment by fonsp** [comment]
A button to clear something from the list would be nice, but I have some ideas to rework the recents list + file system so let's come back to this later.

**Comment by stillyslalom** [comment]
Ah, I see they're now stored in `.julia/pluto_notebooks`. This is getting pretty bikeshedd-y, but I tend to create a lot of new notebooks as scratchpads/calculators, without any intent of saving what's expressed within. I'd like to be able to easily get rid of all my old scratchpads, but that doesn't necessarily have to be automated - maybe something like `Pluto.cleanup(before=Dates.now()-Dates.Day(30))` to delete anything within the default directory that hasn't been touched in a month?

**Comment by fonsp** [comment]
Feel free to submit a PR to PlutoUtils.jl

**Comment by Masacroso** [comment]
Sorry but, how I can delete old entries in "Recent Sessions" of Pluto? I deleted the folder .julia/pluto_notebooks and the cache of the web browser, but it didn't work. Im using the latest version of Pluto right now (v0.15.1).
