### ISSUE TITLE
Cell dependencies not being correctly determined

### ISSUE THREAD

**Issue by pbouffard** [fonsp/Pluto.jl#569]
I don't have a MWE yet but for now here is the notebook that this turned up in: https://gist.github.com/pbouffard/b08cbde763a4b63a19da99c49b49822b

In brief, I developed this notebook more or less top-to-bottom to ultimately wrap things up with a function, `problem54()`, that computes the answer to this Project Euler problem. I moved this function up to the beginning of the notebook and after doing so it will error upon freshly loading the notebook, with `MethodError: no method matching isless(::Main.workspace706.Hand, ::Main.workspace706.Hand)`. At that point if I manually re-run the cell that errors out, then the error goes away and the function completes successfully.

The culprit seems to lie in the `>=` comparison inside the comprehension in the `problem54()` function:

```
p1wins = count([p1 >= p2 for (p1, p2) in zip(p1hands[1:n], p2hands[1:n])])
```

If I change that line to

```
p1wins = count([Base.isless(p2, p1) for (p1, p2) in zip(p1hands[1:n], p2hands[1:n])])
```

then the problem goes away.

**Comment by fonsp** [comment]
Thanks! This looks like the same issue as #327
