### ISSUE TITLE
Move button no longer does anything

### ISSUE THREAD

**Issue by dcurrie** [fonsp/Pluto.jl#570]
Clicking on the Move button in a saved notebook does not seem to do anything. (Platform: macOS, both Chrome and Safai seem to have the problem).

I wonder if it is related to another problem I'm seeing in v.0.12.3, namely that some buttons never seem to get their clicks. Example: PlutoUI.Clock()s don't start in the PlutoUI demo. My custom HTML and JS UI cells don't get their clicks either.

**Comment by dralletje** [comment]
Can you attach an example notebook for me?

**Comment by dcurrie** [comment]
The PlutoUI sample notebook that you get from Pluto’s main page exhibits
the problem.

e

**Comment by fonsp** [comment]
(The issue is referring to the Move button to change the notebook filename.)

It's not broken for me.

Clicking Move does nothing if you did not change the filename. Maybe this caused the confusion?

**Comment by dcurrie** [comment]
Ah, I see now. I expected it to work like Save to construct a new path. It is suboptimal that the button looks identical when disabled or enabled, but I accept that it works as designed.   I had tried to find the simplest thing to explain my real problem, which is that my custom buttons don't work in Pluto v0.12.3, but I'll rely on the Clock example to serve that purpose: https://github.com/fonsp/PlutoUI.jl/issues/57
