### ISSUE TITLE
Time to first notebook open

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#573]
The first notebook of each session takes noticeably longer.
I'm pretty sure that this is due to Julia compilation.
It's not too long (~2-3 secs), and should be considered low priority.

Can we at least show a "loading" bar?

**Comment by fonsp** [comment]
Your browser should have a built-in loading bar

**Comment by fonsp** [comment]
I'm pretty happy with the loading indicators
