### ISSUE TITLE
Issues using name `result` in global scope

### ISSUE THREAD

**Issue by pbouffard** [fonsp/Pluto.jl#574]
Stumbled on this while trying to debug a function.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/231346/96035747-53087800-0e18-11eb-9be8-2ca1b99e8822.png">

Possibly related: When I put the following in a cell and hit Shift+Enter I'm given the split cells/wrap within begin..end prompt.
```
result = 0
i = 2
```

If I click the wrap option it adds the begin/end but the message persists and if I click again the same happens, resulting in nested begin/ends:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/231346/96036534-77b11f80-0e19-11eb-919a-21b115cc672a.png">

Needless to say the same in the REPL works fine. I haven't found any other variable names that seem to act this way, and `result` seems to work OK within functions.

**Comment by fonsp** [comment]
That's a fun bug, thanks!

**Comment by fonsp** [comment]
Another one:

![image](https://user-images.githubusercontent.com/6933510/96056548-29d30080-0e87-11eb-98a5-e61f79e29599.png)

**Comment by fonsp** [comment]
[Testset](https://github.com/fonsp/Pluto.jl/commit/057503d99530de085d7b2b2011120418ab2f2cda#diff-1e4cf2afc4d75fabc14a5e8b87f0f49c72692462056acc18c481903743d805dcR45-R48) 🐈
