### ISSUE TITLE
Pluto doesn't load if firebase did not initialize

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#583]
Also if the firebase CDNs are blocked by google-sceptic browser extensions.

I think this is why we are still getting reports that Pluto does not work offline

**Comment by pankgeorg** [comment]
There is a significant list of assets loaded via CDN (`grep -R "jsdelivr"` plus firebase) - how could Pluto work offline like that?

Regarding the firebase, I could compile a PR that just disables the feedback button if firebase did not load.

**Comment by fonsp** [comment]
> how could Pluto work offline like that

We use a service worker https://github.com/fonsp/Pluto.jl/issues/241#issuecomment-666773112

**Comment by fonsp** [comment]
I'll look at this myself

**Comment by ArrowRaider** [comment]
Why are the dependencies not in the frontend folder?
