### ISSUE TITLE
Pluto frontend doesn't display ligature fonts despite using JuliaMono

### ISSUE THREAD

**Issue by AnselmJeong** [fonsp/Pluto.jl#584]
To my understanding, current Pluto uses `JuliaMono` fonts.
However, the frontend of Pluto does not display ligature fonts properly. May I ask whether there any settings or ways that may enable ligature fonts?

I have been trying to modify several css settings like `font-variant-ligatures` but to no avail.

Always thanks to your contributions. I'm happily using this library.

**Comment by fonsp** [comment]
Thank you for the suggestion! I like ligatures, especially the `|>` is pretty, but they make Julia slightly more difficult for beginners, because you can look at Julia code and not know how to type it yourself.

So we won't enable ligatures by default, subscribe to #2 if you want to enable them.

**Comment by dralletje** [comment]
(I do however have a fix in the works that will allow you to set `font-variant-ligatures`)

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/pull/590
