### ISSUE TITLE
Is macro incompatible with Pluto?

### ISSUE THREAD

**Issue by AnselmJeong** [fonsp/Pluto.jl#585]
I cannot quite fully understand the encapsulation of each cell in Pluto. Due to this complication, very simple macro does not work properly.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/1776524/96360260-7f90fc80-1156-11eb-9aa3-fce639afb36e.png">

Above is a very simple macro modifying the input expression (in this scenario, a variable)

In the second cell, the variable `c` could be modified without any problem.

However, in a newer cell, this macro does not work like this.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/1776524/96360286-c54dc500-1156-11eb-8ee0-f92ddecab550.png">

May be, a variable defined in a certain cell cannot be modified by a macro even though the variable has been escaped with `esc()` in the macro definition.

By the way, this macro works without any problem in Jupyter Notebook.

Thanks.

**Comment by fonsp** [comment]
Have a look here: #196

**Comment by mcabbott** [comment]
Note that `c += 2` when `c` is defined in another cell is already a problem. Even if Pluto could see into the cell, it wouldn't like it:

<img width="437" alt="Screenshot 2020-10-20 at 11 42 57" src="https://user-images.githubusercontent.com/32575566/96569462-75433f80-12c9-11eb-913f-ef0463f751af.png">
`
