### ISSUE TITLE
tabs/indenting

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#586]
Hi, two issues with tabs:

currently, the tab key inserts a tab character (which in the editing widget seems to be equivalent
to 4 spaces). 

- I am a "spaces" guy in the tabs vs spaces flamewar. So I would prefer to have spaces instead of tabs for indenting. Kind of supported also by https://github.com/invenia/BlueStyle  . 

- Once this is settled ;) there is the question of the role of the tab key. In emacs (yes, on that side of the emacs-vs-vi debate :) ), the tab key just indents in the right way according to the surrounding code. Super cool for python, but very nice for all languages. Would this be possible here ?

I understand that these are very personal taste preferences, so there may be reasons that in Pluto preferences should be different from mine. But at  least it would be good to support some automatic indenting of code. May be it is possible to have a hotkey (like C-m for toggling markdown)  which  fixes code indenting in a cell.

**Comment by pbouffard** [comment]
Maybe https://github.com/domluna/JuliaFormatter.jl could be useful?

I for one would happily allow such a tool to auto-format everything.

**Comment by fonsp** [comment]
I don't want to implement a formatter yet (maybe in 6 months), but codemirror has built in auto-indent and you could add a shortcut for that.

**Comment by pbouffard** [comment]
> I don't want to implement a formatter yet (maybe in 6 months), but codemirror has built in auto-indent and you could add a shortcut for that.

Just added #599 🙂

**Comment by fonsp** [comment]
We will revisit this later - we don't do any customization right now.

**Comment by SimonEnsemble** [comment]
following up on this, would be awesome to convert tabs to spaces!
every time I paste a worked out `function` from Pluto into terminal (vim), then push to github, the spacing is messed up! :eye:

**Comment by clarkevans** [comment]
It'd be nice to let Pluto know to use 4 spaces instead of TAB character.

**Comment by scls19fr** [comment]
Same problem here. Copy/paste code from VS Code or directly from Github to Pluto.jl ends up bith spaces/tabs mixed up. Issue opened https://github.com/fonsp/Pluto.jl/issues/2831

**Comment by ederag** [comment]
That would not solve the copy/paste from various sources issue, but
as there is no consensus over tab vs space (I like the current defaults),
it might be nice to honor [`.editorconfig`](https://editorconfig.org/) if possible
(and as most standalone editors support it, it would make concurrent editing in both Pluto and the editor smoother).

**Comment by mbauman** [comment]
It'd be great if we could revisit this default — pretty much every single Julia style guide recommends spaces over tabs.

* https://docs.julialang.org/en/v1/manual/style-guide/#Indentation
* https://docs.sciml.ai/SciMLStyle/stable/#High-Level-Rules
* https://github.com/JuliaDiff/BlueStyle?tab=readme-ov-file#synopsis

**Comment by j-fu** [comment]
bump :)

**Comment by vchuravy** [comment]
I encounter this inside markdown a lot, where it seems to be a semantic difference...

```
md"""
1. Hello
    - No this is not code
"""
```

```
md"""
1. Hello
    - No this is not code
"""
```

Behave differently... I would strongly prefer spaces over tabs as a default, or at least a choice.

**Comment by LinusSch** [comment]
Today I discovered that the notebook I've been working on for a few days has a mix of tabs and four spaces (as I felt the need to open it in a more powerful editor). Very much not intended nor expected!

I have been copying lines from here and there in addtion to writing most lines manually, I am (now) fully aware of how this happened. But I didn't *see* it happening.

I am not strongly for or against either tabs or spaces, but I do think that tabs need to be shown with some way of differentiating them from the 4 spaces expected by Julia style guides. The current situation causes unnecessary confusion and friction, for veterans and beginners both.

**Comment by j-fu** [comment]
I regularly work in parallel with Pluto (with `auto_reload_from_file=true`) and emacs (with (global-auto-revert-mode t) ). I set up emacs with apheleia and runic formatting. This works quite well and helps to format code in notebooks without tabs.

**Comment by ederag** [comment]
To prevent further surprises, one may put a `.editorconfig` file with the following content
in the folder containing the notebook (or a parent folder)
```
root = true

[*]
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf

[*.jl]
indent_style = tab
indent_size = 4
```
Most external editors should honor these settings, thus avoiding tab/space indentation mismatches.
Only the `[*.jl]` is important here; the other can be removed if does not match your style, and
see also other settings in https://editorconfig.org/

**Comment by vchuravy** [comment]
> To prevent further surprises, one may put a .editorconfig file with the following content

It would be wonderful if Pluto would honour that as well and allow for 

```
[*.jl]
indent_style = space
indent_size = 4
```

**Comment by fonsp** [comment]
https://github.com/JuliaPluto/Pluto.jl/pull/3538 might help

**Comment by fonsp** [comment]
https://github.com/JuliaPluto/Pluto.jl/pull/3551 also helps
