### ISSUE TITLE
Output from commands not showing inside Pluto notebook but showing in Julia Terminal

### ISSUE THREAD

**Issue by rleyvasal** [fonsp/Pluto.jl#587]
The notebook has been working but today the output is not showing inside the notebook.

I did close Firefox and restarted Julia, but the output is still still not showing in the notebook.

 
Firefox 81.0.2 (64-bit)
Windows 10 Pro 64bit  Version 2400
Julia 1.5.2

**Comment by fonsp** [comment]
Which commands?

**Comment by rleyvasal** [comment]
All commands are not showing, inside Pluto.

Look at attached picture:
1.I opened Julia and ran Pluto, output of commands was not showing inside
notebook (only in the Julia Terminal)
2. I refreshed the browser, and got al the "Error:....." output
3. After the browser refresh was done, I ran the commands again one more
time and they showed in the Julia Terminal again.

My next step in troubleshooting would be to restart the computer, but I
wanted to share with you the problem I am having first.

Regards
Rigoberto.

**Comment by fonsp** [comment]
It looks like you sent an image via email, can you upload it to https://github.com/fonsp/Pluto.jl/issues/587 instead?

**Comment by dralletje** [comment]
The image, for reference
![PlutoNotShowingCommands](https://user-images.githubusercontent.com/61335136/96501300-0bf9f880-1205-11eb-820f-832e3bc4912b.PNG)

**Comment by dralletje** [comment]
The logs are indeed not showing in Pluto, this is by design.
Simplest way to get the results, is using `PlutoUI.with_terminal`:

```
import PlutoUI

PlutoUI.with_terminal() do
  # Your code that prints to the terminal
end
```

**Comment by murilo** [comment]
we want output to the notebook not to the terminal :-D
