### ISSUE TITLE
Failed to process update Error: BUFFER_SHORTAGE

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#593]
Some rare bug when I close a Pluto notebook. Just post an issue as the message says :P

```
Something went wrong!

Please open an issue on https://github.com/fonsp/Pluto.jl with this info:

Failed to process update
Error: BUFFER_SHORTAGE

[object MessageEvent]
```

**Comment by Pocket-titan** [comment]
Ah now that `[object MessageEvent]` is very useful, thank you JavaScript :P I'll try to make the error display something more helpful so we can actually see it the next time it happens. Thanks for opening an issue!

**Comment by fonsp** [comment]
Which browser do you use?

**Comment by fonsp** [comment]
Oh and one thing @GiggleLiu :

> when I close a Pluto notebook.

Do you mean: 
1. _when you close Pluto using `Ctrl+C`, and the notebook is still open in the browser_ or 
2. _when I close a Pluto tab but leave the server running_?

**Comment by GiggleLiu** [comment]
Sounds good.

I closed the tab most likely in Firefox, then I tried to open a new page in both Firefox and chrome, neither works.

2. when I close a Pluto tab but leave the server running. More accurately the sever dies. But it never happen again since then.
