### ISSUE TITLE
Frontend config

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#6]
Would be very cool if this is done within the reactive environment! I imagine:

there is a _yellow_ cell, before all other cells (which is hidden by default), and whatever the output of that cell is will be used as config `Dict` by Saturn. Like:
```julia
Dict(:interactivearrays => false, 
     :theme => "body: {font-family: 'Comic Sans MS' !important;}")
```

Something very cool is that this cell can also be reactive! Like:

```julia
if @__FILE__ == "bigdata.jl"
    Dict(:theme => read("~/bigdatatheme.css", String))
else
    Dict()
end
```

Needs a config file

**Comment by malyvsen** [comment]
I think it'd be most elegant if this wasn't a designated type of cell - instead, any cell could manipulate `Saturn.style` or some other variable like this, and that would automatically update the display.

**Comment by fonsp** [comment]
True, but that goes against the philosophy of no side effects and pure
functions.

**Comment by malyvsen** [comment]
Au contraire, if we had Saturn.style also be a reactive variable - then you could even have a color picker or something on the website to control it? (I do think that JavScript is better-suited for reactivity in this aspect though - I imagine making HTML sliders in Julia will be a mess).

**Comment by fonsp** [comment]
True! It could be a 'mutable global'. Sliders exist! [Interact.jl](https://github.com/JuliaGizmos/Interact.jl) But I'm not sure how easily their implementation adapts to our system.

**Comment by fonsp** [comment]
There's a `ENV`-like config system now, adding UI for config is something for later 💆‍♂️
