### ISSUE TITLE
Is there a way to detect command line execution?

### ISSUE THREAD

**Issue by leohallier** [fonsp/Pluto.jl#603]
I want to detect whether my code is executed through Pluto or with the command line (ie. >julia notebook.jl) so diagnostic plots and similar things do not get computed unnecessarily. So far I have been using `@bind missingifcmd html"<input type=range min=5 max=5>"` and the `ismissing()` function. The problem is that during Pluto execution it first gets set to missing anyway for a short time causing unwanted behaviour at startup. Is there a better solution?

**Comment by fonsp** [comment]
You can use `isdefined(:PlutoRunner)`, it will always be supported
