### ISSUE TITLE
Possible to autoreload packages which are devoloped in IDE like VS code? (Idea: no cluttering in notebook)

### ISSUE THREAD

**Issue by suiluj** [fonsp/Pluto.jl#604]
Hello i have a question regarding devoloping with an IDE and Pluto notebook at the same time.

In Jupyter Notebooks with Python i often develop a python modules in my IDE (VS Code).

For interactive testing i then use Jupyter notebooks and import my own module with autoreload like this:

```
%load_ext autoreload
%autoreload 1

%aimport myownmoduleidevelopcurrently
```

different cell in python jupyter notebook:
```
#diff
#when i change the dostuff method in my module the notebook automatically uses the new version when executing a cell
myownmoduleidevelopcurrently.dostuff()
```
explanation: https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html  

I am still a beginner with Julia. My question is how i would do something like this in a Julia notebook.

My general idea is that i do not want to clutter my notebooks with long code cells. So I import my "complicated long" code and only call the functions/methods in the notebook and change parameters interactively there.
But at the same time i want to be able to change code in my modules/packages and the notebook should pick up these changes when executing cells next time.

**Comment by lungben** [comment]
This can be done with Revise.jl.
Essentially, you need to add the following cell to your notebook:

```
begin
    using Revise
    using MyPackage
end
```

Important: you must import Revise before the packages you want to auto-reload.

**Comment by suiluj** [comment]
@lungben thanks a lot. Revise.jl is exactly what i need. thanks for the example too. :)
