### ISSUE TITLE
Extra space in nested markdown lists

### ISSUE THREAD

**Issue by ericphanson** [fonsp/Pluto.jl#605]
In Pluto v0.12.4,
<img width="814" alt="nested_list" src="https://user-images.githubusercontent.com/5846501/97009343-4553a080-1544-11eb-81b9-ac90df72b937.PNG">

I think there shouldn't be so much vertical space between `Bullet` and `Subbullet`, and prefer the REPL's vertical spacing (of course Pluto looks nicer overall):

```julia
julia> md"""
       * Bullet
           * Subbullet
           * subbullet 2
       * Second bullet
       """
    •    Bullet

          •    Subbullet

          •    subbullet 2

    •    Second bullet

julia>
```

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/b691385b7344b19b6ab7a71c4c973fa978f091ba

**Comment by fonsp** [comment]
still an issue of `<ol>`
