### ISSUE TITLE
Header font for 0123456789 is too artsy

### ISSUE THREAD

**Issue by Moelf** [fonsp/Pluto.jl#613]
![image](https://user-images.githubusercontent.com/5306213/97114029-7824a280-16c4-11eb-93ce-2381b2de4d24.png)

I personally have 2 "complaints":
1. the `1` is confusing
2. the "baseline" is weird for this font. <--- less of an issue

**Comment by fonsp** [comment]
The complaint is specifically about the arabic numerals, right?

**Comment by fonsp** [comment]
I am going to assume that it is, and otherwise refer to #2

**Comment by fonsp** [comment]
The typeface contains variants that solve these problems:
![image](https://user-images.githubusercontent.com/6933510/97436511-68a29500-1922-11eb-8029-f75049f86d2b.png)

http://vollkorn-typeface.com/

but these are not included in the google-fonts-compiled version, which we get from
https://github.com/fontsource/fontsource/tree/master/packages/vollkorn

The solution could be to use the original fonts:
https://github.com/FAlthausen/Vollkorn-Typeface

but these still need to be compiled to WOFF2:
https://github.com/google/woff2

We can then host them on our own repo, tag a release, and get them from jsdelivr

**Comment by fonsp** [comment]
The fork is here:
https://github.com/fonsp/Vollkorn-Typeface
if anyone wants to contribute

**Comment by pankgeorg** [comment]
@fonsp opened a PR to your fork

**Comment by fonsp** [comment]
Thanks to @pankgeorg for compiling!

Available at:
https://cdn.jsdelivr.net/gh/fonsp/Vollkorn-Typeface@1/fonts/woff2/Vollkorn-Regular.woff2

**Comment by Moelf** [comment]
I'm fine with anything but the first. personally like the second one

**Comment by pankgeorg** [comment]
Opened a PR that uses the second one. I think the third is for tables (kind-of-fixed witdth?)

I love the slashed zero, but it fits in tables/codeblocks (the JuliaMono dotted zero triggers my trypophobia I think)
