### ISSUE TITLE
TaskFailedException:

### ISSUE THREAD

**Issue by ardsatcg** [fonsp/Pluto.jl#614]
Got message like this⤵, 

TaskFailedException:
cannot assign a value to variable IJulia.ans from module Main
Stacktrace:
[1] top-level scope at C:\Users\LENOVO\.julia\packages\Pluto\2pyPe\src\analysis\Parse.jl:153
[2] eval at .\boot.jl:331 [inlined]
[3] (::Distributed.var"#155#156"{Module,Expr})() at .\task.jl:356

#614

**Comment by dralletje** [comment]
Can you provide more info? Like a notebook that you tried to run, or the steps you took. Try to be as complete as possible, if necessary upload the notebook to https://gist.github.com

**Comment by ardsatcg** [comment]
> Can you provide more info? Like a notebook that you tried to run, or the steps you took. Try to be as complete as possible, if necessary upload the notebook to https://gist.github.com

While open pluto notebook project, get displaying like this, but can be solve with ( shift+enter )

![Screenshot 2020-10-27 103657](https://user-images.githubusercontent.com/71117550/97250273-90b9c780-1840-11eb-8690-178826b6902b.png)

**Comment by dralletje** [comment]
Could you upload the full notebook that causes this (https://gist.github.com)? And do you have more info about how you boot Pluto, the rest of your setup etc?

**Comment by ardsatcg** [comment]
even empty cell

![Screenshot 2020-10-27 130041](https://user-images.githubusercontent.com/71117550/97258975-ac2ecd80-1854-11eb-9b17-a0192aaec22e.png)

**Comment by dralletje** [comment]
You really gotta get me some more info about your setup that leads up to this problem.
Closing this until you have some more time to write all the info down.

**Comment by fonsp** [comment]
Did you start Pluto after/inside a Jupyter notebook?

**Comment by ardsatcg** [comment]
> Did you start Pluto after/inside a Jupyter notebook?

It doesn't really matter wheater after/inside jupyter, still doing same thing. I've try both

**Comment by ardsatcg** [comment]
> Did you start Pluto after/inside a Jupyter notebook?

But now it's fine

did'nt do same thing again
