### ISSUE TITLE
Printing using markdown

### ISSUE THREAD

**Issue by UtkarshChemE** [fonsp/Pluto.jl#618]
For the following code:
```julia
begin
	var = 10.0
	md"$(var) value is has newline. But next inline use of $(var) works as expected"
end
```
The output from the same is
```
10.0
value is has newline. But next inline use of 10 works as expected
```

This is a strange behavior where reference of `var` at beginning of string creates a new line, but any other reference doesn't.

**Comment by fonsp** [comment]
Can you report this issue to https://github.com/JuliaLang/julia instead?
