### ISSUE TITLE
Worker crash should be communicated to user

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#62]
(Pointed out by @karlwessel in #61.)

**Comment by karlwessel** [comment]
An intermediate solution would be an option to stop a notebook without having to stop julia. At the moment the worker seems to keep running even when I stop Pluto.

**Comment by fonsp** [comment]
Your suggestion is implemented in `0.5.20` :)

**Comment by fonsp** [comment]
@karlwessel Have you experienced any worker crashes since #61? 

In any case, this issue is still relevant to handle segfaults and such.

**Comment by karlwessel** [comment]
I don't think I experienced any worker crashs, no. But I also didn't use Pluto that heavily during the last two weeks. 

I will use it more in the coming weeks when I try to do our homework assignments with it :).

**Comment by fonsp** [comment]
Awesome! I actually want to work more on Pluto as an educational tool. If you have any ideas that would improve the experience for beginners or teachers, let me know 😊 (GH issues / Pluto feedback / julialang slack)
