### ISSUE TITLE
RangeError: Start offset undefined is outside the bounds of the buffer

### ISSUE THREAD

**Issue by Seelengrab** [fonsp/Pluto.jl#620]
Hi,

when I run my notebook I get the following error:

```
Failed to process update! RangeError: Start offset undefined is outside the bounds of the buffer
    at new Uint8Array (<anonymous>)
    at PlutoConnection.js:126
    at async do_all (PlutoConnection.js:58)
```

I can share the notebook that produces this if that helps, but sadly not all files it depends on :/ Suffice it to say that it's two .csv files of 2.3G and 753M, of the form `String,String,String,Int64,Int64,Int64,Int64,Int64` and `DateTime, Float64, Int64`.

**Comment by fonsp** [comment]
If you remove the `plot(...)` cell, does the problem disappear?

**Comment by Seelengrab** [comment]
I've commented the `plot` cell, it didn't show the error (although I didn't wait 10 minutes or something like that). I've got other notebooks where plotting like that was not a problem though 🤷‍♂️ Should I plot inside a function?

**Comment by Seelengrab** [comment]
Uncommenting and running the cell crashed the browser tab though.

**Comment by fonsp** [comment]
Are you out of memory perhaps?

**Comment by Seelengrab** [comment]
Unlikely - I've got 20GB and the datasets combined are not even 3GB.

That does give me an idea though: The browser is (apparently) just a 32 bit application. Let me check with a 64 bit browser.

**Comment by Seelengrab** [comment]
Well, 64-bit Edge (which is also Chromium based) also dies, with an Out Of Memory 🤔 The dataset is definitely loaded in memory though, the julia process has a whopping 7GB memory footprint. Maybe something during plotting needs a lot more memory and just dies? Maybe I shouldn't plot all of the data at once 😅

**Comment by Seelengrab** [comment]
Hmm I've just caught the crash while looking at my ressource usage and it really does seem to be true Out Of Memory and getting killed due to that. That's unfortunate.

**Comment by fonsp** [comment]
Yes it sounds like you are plotting too much data at once, at least for the JS (plotly) or SVG (GR) based backends. 

If you really need to plot all data, you could switch to the GR backend and force PNG output:

```julia
begin
using Plots
gr()
end
```
```julia
using PlutoUI
```

```julia
plot(...) |> PlutoUI.as_png
```

**Comment by Seelengrab** [comment]
I'm not sure if it's actually a problem of the data I try to plot - I'm loading the big dataset, but not doing anything with it. It's the smaller one I'm trying to plot. I'll try to plot the small one without loading the big dataset.

**Comment by Seelengrab** [comment]
Oooh live rendering copies the data to the browsers memory 😬 That's not good - I guess I'll have to forsake interactivity then :/
