### ISSUE TITLE
End-to-end test improvements and additions

### ISSUE THREAD

**Issue by novoselrok** [fonsp/Pluto.jl#621]
Fix tests failing when they shouldn't:
* https://github.com/fonsp/Pluto.jl/runs/1332947231

Additional functionality to test:
* Key shortcuts

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/runs/1355798132

Downloading Ubuntu gave 402 Payment required ? computers are strange

**Comment by novoselrok** [comment]
@fonsp Not sure how, not sure why, but this commit: https://github.com/fonsp/Pluto.jl/commit/2e561e9ad31aade638ab92125420a5f99f92c407 broke the e2e tests. I also confirmed it locally. e2e tests are working on the previous commit.

**Comment by fonsp** [comment]
It take about 5-10secs for Julia to precompile the autocomplete stuff, which I triggered to happen on page load. So this means that the backend is unresponsive for 10 seconds longer than before after launch
