### ISSUE TITLE
Feature request: Spell check for markdown cells

### ISSUE THREAD

**Issue by Moelf** [fonsp/Pluto.jl#622]
Easy way is to enable spell checking for a cell if the cell contains only markdown.

https://stackoverflow.com/questions/39324039/highlight-typos-in-the-jupyter-notebook-markdown

**Comment by fonsp** [comment]
Thanks! Can you submit this to the [suggestion box](https://github.com/fonsp/Pluto.jl/issues/182) instead?

**Comment by theogf** [comment]
Not sure if there was any follow-up on this? Has this been considered by the Pluto team?
