### ISSUE TITLE
JuMP model display stopped working in 0.12

### ISSUE THREAD

**Issue by hellemo** [fonsp/Pluto.jl#623]
It seems like the display of JuMP models worked beautifully for 0.11, but stopped working in 0.12.

Minimal example:

```julia
begin
	Pkg.add("JuMP")
	using JuMP
	m = Model()
end
```
Expected result (Pluto 0.11):
![image](https://user-images.githubusercontent.com/1584698/97782249-c0463800-1b90-11eb-8dab-34d423a041e6.png)
Result in Pluto 0.12:
![image](https://user-images.githubusercontent.com/1584698/97782299-013e4c80-1b91-11eb-877e-fecd96a4ceb1.png)

**Comment by fonsp** [comment]
Caused by #381, related to #488

**Comment by hellemo** [comment]
Fixed with latest versions of Pluto and JuMP (using JuMP.latex_formulation)

**Comment by fonsp** [comment]
@hellemo Can you elaborate? What is `latex_formulation`, do people need to do something to make JuMP work? In my tests it worked fine out of the box

**Comment by hellemo** [comment]
Sure, it's just that the default display mode of JuMP models has changed, apparently (I haven't followed this too closely), and you have to use the latex_formulation to get the LaTeX-version of the model rather than a summary of properties. Both work out of the box now.
![image](https://user-images.githubusercontent.com/1584698/119781566-74ac0080-becb-11eb-947d-39c7d86abda5.png)
