### ISSUE TITLE
Pluto unusable on one of my installs.

### ISSUE THREAD

**Issue by Qfl3x** [fonsp/Pluto.jl#624]
OS: Arch Linux.

Julia: Latest in Arch Linux repos (1.5.2).

I'm trying to run Pluto on this machine but it doesn't work. It feels like I'm browsing on an extremely slow internet speed, and if I use the default port (1234) no icons show up in the interface. Using a different port loads up (somewhat), but starting a new notebook freezes everything and I get a white screen.

I don't think the issue is with my loopback driver/interface since Jupyter works fine.

**Comment by fonsp** [comment]
Which borwser?

**Comment by Qfl3x** [comment]
Firefox 82.0.2 (64-bit). Will try and use the Official binary and see what happens.

**Comment by Qfl3x** [comment]
Update: Doesn't work with the Official Binary either.

**Comment by Qfl3x** [comment]
So I just reset Firefox entirely (Deleted ~/.mozilla) and it works. It has to be some extension that caused the issue. Good news is the issue is no more. Bad news is I don't know what caused it. Apparently it doesn't like one of my (many) old add-ons so maybe add a note that some addons should be disabled or maybe not. 

Feel free to close this issue.
