### ISSUE TITLE
Packages that inject into Core/Base can't be unimported from a session

### ISSUE THREAD

**Issue by FelixBenning** [fonsp/Pluto.jl#627]
I removed `using Zygote` at some point. Now I am getting an error `_pullback(::Zygote.Context, ::typeof(Main.workspace250.flux), ::Float64)`

Now this error probably do not have anything to do with pluto, but since Pluto aims to be reactive, it should probably stop using dependencies when the using/import statements were removed. So I probably should not get a reference to Zygote in my stacktrace. Well at least as long as Zygote is not in Base.

**Comment by fonsp** [comment]
Can you try to come up with a MWE?

**Comment by FelixBenning** [comment]
![grafik](https://user-images.githubusercontent.com/29106652/97808114-243a3080-1c65-11eb-8c60-a2cda18fa53f.png)

after deletion:

![grafik](https://user-images.githubusercontent.com/29106652/97808129-4764e000-1c65-11eb-9c65-168cd61384e8.png)

copy and paste this: (Note that this is not a normal minus sign, apparently I fatfingered a unicode thing into a minus sign somewhere)
```julia
f(x) = x -̢ 1
```

**Comment by fonsp** [comment]
What happens if you run the last cell again after removing?

**Comment by FelixBenning** [comment]
@fonsp The same error referencing the Zygote (that is what I mean by "after deletion") - could you not reproduce that?

**Comment by fonsp** [comment]
Okay thanks! Haven't tried it yet 😅

**Comment by fonsp** [comment]
I think this can only be solved by restarting the julia process, but we probably don't want to do this automatically when you remove a `using`. Hmm... Maybe keep a list of "dangerous" packages that inject into Base?

**Comment by fonsp** [comment]
Much more important is #24, (which would also be solved by restarting the process).

**Comment by mcabbott** [comment]
This seems to be https://github.com/FluxML/Zygote.jl/issues/260 BTW -- Zygote is committing piracy, not just adding methods.

**Comment by fonsp** [comment]
Not something that we are responsible for fixing, but #844 will recommend restarting the notebook after you remove an import.
