### ISSUE TITLE
Table of Contents/Outline

### ISSUE THREAD

**Issue by BrettKnoss** [fonsp/Pluto.jl#629]
In markdown I can create headings

# This is a heading
### this is a subsubheading

Each one of these shows up in the VS code side bar, and I can go directly to that part of whatever I'm writing.  Likewise I can use the table of contents, when I export a pdf, to find things immediatly.  Does Pluto.jl have such a feature?

**Comment by icweaver** [comment]
I think their is something in the works over at PlutoUI? https://github.com/fonsp/PlutoUI.jl/pull/30
