### ISSUE TITLE
convert notebook to app

### ISSUE THREAD

**Issue by rcherukuri12** [fonsp/Pluto.jl#630]
I am working on multiple notebook files for each section of a book with Julia.
Would like to create package and put some of those notebooks into a chapter package.
Would be great if there is an option for it using pluto dependency tree to figure out and generate package related files ( that have dep. library information as well )

**Comment by fonsp** [comment]
I don't understand. Could you give a small example?

**Comment by rcherukuri12** [comment]
Sorry, I should have framed it better.
I have my children learning - Julia with Pluto.
They build some notebooks with math with plots.
To share or export these notebooks, now they generate a julia files.
But it would be perfect, if there is an option to generate a julia app-package
that has this notebook.
It would allow the right dependencies to go along.
( something similar to app creation options for different types of applications in Genie )

Regards

Raja C.


________________________________

**Comment by fonsp** [comment]
Hi Raja,

I love that you are using Pluto to teach maths, and I would be happy to help!

What I usually do is upload the notebook to GitHub gist:
gist.github.com/

and then i copy the link to my gist, for example:
https://gist.github.com/fonsp/d88b3adc8c958dce780cf7c4df8fa437

You can then go to pluto-on-binder.glitch.me/ and paste the link into the box. It will give you a second link:
https://mybinder.org/v2/gh/fonsp/pluto-on-binder/master?urlpath=pluto/open?url=https%253A%252F%252Fgist.githubusercontent.com%252Ffonsp%252Fd88b3adc8c958dce780cf7c4df8fa437%252Fraw%252F73be9df9ec4f93b09538824da096020f76b7fdb5%252Fturtles.jl

This link will run the notebook in the browser, and you can save/share this link for later.

Does that help?
-fons

**Comment by rcherukuri12** [comment]
Yes, that is perfect. Thank you.

Raja
________________________________

**Comment by fonsp** [comment]
Glad to hear!
