### ISSUE TITLE
High CPU load on client side with long running notebooks

### ISSUE THREAD

**Issue by dhanak** [fonsp/Pluto.jl#631]
It seems that when a notebook takes some time to calculate, even though the calculation itself is taking place on a remote computer, the browser still produces a fairly high CPU load. This is probably caused by the client-server communication in the background, but I'm sure that it should not be that expensive. This is obviously less noticeable when the Pluto server is running locally, but in that case, the above issue means that the browser is actually eating up resources that otherwise would go to Julia, which is a waste.

A fix would be very welcome!

**Comment by fonsp** [comment]
(this is probably the CSS animations)

**Comment by fonsp** [comment]
which browser, which version, how many cells, which CPU, how much CPU usage?

**Comment by dhanak** [comment]
I'm using Chrome 86 on a Debian Linux, running on an Intel Core i7 processor with 4 cores, 8 threads, and it can use as much as 70-80% of the total CPU capacity.

**Comment by fonsp** [comment]
Chrome is using 70% of a single core, or 280% total?

**Comment by dhanak** [comment]
It's more like 600%! 70-80% on average on all eight hyperthreads.

**Comment by fonsp** [comment]
I created this branch with animations disabled:
https://github.com/fonsp/Pluto.jl/tree/no-animations

Can you try this and see if the CPU usage is fixed?

https://github.com/fonsp/Pluto.jl/blob/no-animations/CONTRIBUTING.md#method-2-use-the-package-manager

**Comment by pankgeorg** [comment]
I can confirm that the animation is the issue, on Chrome/Windows 10: 
This cell: 
![image](https://user-images.githubusercontent.com/8681967/97911497-04ce0100-1d54-11eb-9148-fe6662e2067c.png)

has this as result
![image](https://user-images.githubusercontent.com/8681967/97911480-fc75c600-1d53-11eb-8e3c-12cb1a978709.png)

Without the animation:
![image](https://user-images.githubusercontent.com/8681967/97911581-27601a00-1d54-11eb-82ba-cae56283dd90.png)

![image](https://user-images.githubusercontent.com/8681967/97911544-1adbc180-1d54-11eb-86b0-6a84f266574a.png)

**Comment by fonsp** [comment]
crazy

**Comment by pankgeorg** [comment]
If you agre, I'll prepare two fixes, one with stacking context, one with pseudo-elements and top animation. Will add explanation in a PR if I'm happy with the result.

**Comment by dralletje** [comment]
@pankgeorg that would be amazing

However, could you also try implementing the animation with `transform: translateY(...)` inside an `overflow: hidden` container? Browsers don't tend to like animating anything outside of `transform` or `translate`, not sure if adding stacking context will help there.

**Comment by Pocket-titan** [comment]
+1 re: a `transform: translate(...);` solution, you can read [this](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/) for more explanations why, if you want

**Comment by dralletje** [comment]
Thaaanks, also just throwing ideas out there, but we can try stopping the animation when the page is out of focus/invisible? (https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)

**Comment by pankgeorg** [comment]
@dralletje Added a PR with the animation change.

About the Page Visibility API: yes, we can add this, pretty easy.
I didn't add it already because 
- Chrome already does that
- I think using [Intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) on cell level is better (and can also help to alleviate rendering pressure from the browser), but wanted to discuss before implementing (don't want to "touch" cells at this point, while a refactor is ongoing [ #626 ])

Is this the right venue to discuss?

**Comment by fonsp** [comment]
(I would just like to share this hilarious feedback that we got a few months ago:)

> The animation of the play button for a cell button for cells that need updating makes me crazy. I have a shitty noisy power supply which changes frequency in sync with the animation of the button since it seems to consume _that_ much energy xD.So I can hear the periodic animation and it makes me crazy.... had to get that off my soul, sorry

**Comment by Marceline** [comment]
So grateful for the no-animation branch, my battery can't stop raving on about how much more energised its been feeling.

**Comment by dhanak** [comment]
I just tried to new release (0.12.7), which is supposed to contain the fix for my issue, but the animation still consumes a lot of CPU power. Perhaps because there is a long chain of cells depending on one taking longer to calculate, and thus there are many animated progress bars, perhaps for some other reason, but I still see an approx. 70% total power use of my CPU just because of this rendering. I will try to replace the animation with color codes on my side, and report back how it goes.

**Comment by pankgeorg** [comment]
> I just tried to new release (0.12.7), which is supposed to contain the fix for my issue, but the animation still consumes a lot of CPU power. Perhaps because there is a long chain of cells depending on one taking longer to calculate, and thus there are many animated progress bars, perhaps for some other reason, but I still see an approx. 70% total power use of my CPU just because of this rendering. I will try to replace the animation with color codes on my side, and report back how it goes.

Some questions 

1. Is it 70% on each of the 8 hyper threads?
2. Does your laptop have GPU?
3. How many cells are interdependent (to try to reproduce)
4. Can you paste here the animation code to ensure you load the new stuff?

Thank you!
P

**Comment by dhanak** [comment]
> > I just tried to new release (0.12.7), which is supposed to contain the fix for my issue, but the animation still consumes a lot of CPU power. Perhaps because there is a long chain of cells depending on one taking longer to calculate, and thus there are many animated progress bars, perhaps for some other reason, but I still see an approx. 70% total power use of my CPU just because of this rendering. I will try to replace the animation with color codes on my side, and report back how it goes.
> 
> Some questions
> 
> 1. Is it 70% on each of the 8 hyper threads?

Yes, that's right.

> 2. Does your laptop have GPU?

No, it uses an integrated Intel graphics chip.

> 3. How many cells are interdependent (to try to reproduce)

This is a sample notebook which reproduces the error well:

```
### A Pluto.jl notebook ###
# v0.12.7

using Markdown
using InteractiveUtils

# ╔═╡ 4f3c038a-2007-11eb-1035-2f1ae533de03
sleep(10000); a = 1

# ╔═╡ 50d11788-2007-11eb-1643-c1c01a517d87
b = a

# ╔═╡ 51a35de2-2007-11eb-120c-41b14c9eda74
c = b

# ╔═╡ 52f2bdf2-2007-11eb-3d14-875b33360986
d = c

# ╔═╡ 546bcffc-2007-11eb-0cd5-893e11483e70
e = d

# ╔═╡ 558113b6-2007-11eb-2e78-c7ea9fca4357
f = e

# ╔═╡ f95e5d08-2008-11eb-2a38-73e774ca819d
g = f

# ╔═╡ fe0da0d4-2008-11eb-1a96-457f3d515f79
h = g

# ╔═╡ Cell order:
# ╠═4f3c038a-2007-11eb-1035-2f1ae533de03
# ╠═50d11788-2007-11eb-1643-c1c01a517d87
# ╠═51a35de2-2007-11eb-120c-41b14c9eda74
# ╠═52f2bdf2-2007-11eb-3d14-875b33360986
# ╠═546bcffc-2007-11eb-0cd5-893e11483e70
# ╠═558113b6-2007-11eb-2e78-c7ea9fca4357
# ╠═f95e5d08-2008-11eb-2a38-73e774ca819d
# ╠═fe0da0d4-2008-11eb-1a96-457f3d515f79
```

> 4. Can you paste here the animation code to ensure you load the new stuff?

```jl
/* TRAFFIC LIGHT */

pluto-trafficlight {
    /* --patternHeight is derived from the pattern length (16px) div sin(45deg) = 16px * sqrt(2)  */
    --patternHeight: 22.62741699797px;
    box-sizing: content-box;
    margin-right: -1px; /* fix a visual glitch of imperfect alignment */
    width: 4px;
    position: absolute;
    left: -4px;
    top: 0px;
    bottom: 0px;
    pointer-events: none;
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
    border-left-color: rgba(0, 0, 0, 0.1);
    background: rgba(0, 0, 0, 0.1);
    overflow: hidden;
}

pluto-trafficlight::after {
    content: "";
    /* Calc needs units everywhere to work */
    top: calc(0px - 2 * var(--patternHeight));
    left: 0;
    width: 100%;
    height: calc(100% + 2 * var(--patternHeight));
    position: absolute;
}

/* in ascending order of severity: */

pluto-cell.code_folded > pluto-trafficlight {
    background: none;
}

@media screen and (any-pointer: fine) {
    pluto-cell:hover > pluto-trafficlight {
        background: rgba(0, 0, 0, 0.1);
        transition: background 0.05s ease-in;
    }
}

pluto-cell:focus-within > pluto-trafficlight {
    border-left-width: 4px;
    border-left-style: solid;
    margin-left: -4px;
    background-clip: content-box;
    background-color: rgba(0, 0, 0, 0.1);
}

pluto-cell.selected > pluto-trafficlight {
    background: rgba(40, 78, 189, 0.4);
    border-left-color: rgba(40, 78, 189, 0.4);
    background-clip: content-box;
}

pluto-cell.code_differs > pluto-trafficlight {
    background: hsla(46, 70%, 37%, 0.68);
    border-left-color: hsla(46, 70%, 37%, 0.68);
    background-clip: content-box;
}

pluto-cell.errored > pluto-trafficlight {
    background: hsla(0, 70%, 80%, 0.7);
    border-left-color: hsla(0, 70%, 80%, 0.7);
    background-clip: content-box;
}

pluto-cell.queued > pluto-trafficlight::after {
    background: repeating-linear-gradient(-45deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0) 8px, rgba(0, 0, 0, 0.1) 8px, rgba(0, 0, 0, 0.1) 16px);
    background-clip: content-box;
    animation: 1s linear 0s infinite running scrollbackground;
    background-size: 4px var(--patternHeight);
}

pluto-cell.running > pluto-trafficlight::after {
    background: repeating-linear-gradient(-45deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1) 8px, rgba(0, 0, 0, 0.2) 8px, rgba(0, 0, 0, 0.2) 16px);
    background-clip: content-box;
    animation: 1s linear 0s infinite running scrollbackground;
    background-size: 4px var(--patternHeight);
}

pluto-cell.queued.errored > pluto-trafficlight::after {
    background: repeating-linear-gradient(
        -45deg,
        hsla(0, 70%, 80%, 0.7),
        hsla(0, 70%, 80%, 0.7) 8px,
        hsla(0, 70%, 80%, 0.05) 8px,
        hsla(0, 70%, 80%, 0.05) 16px
    );
    background-clip: content-box;
    animation: 1s linear 0s infinite running scrollbackground;
    background-size: 4px var(--patternHeight); /* 16 * sqrt(2) */
}

pluto-cell.running.errored > pluto-trafficlight::after {
    background: repeating-linear-gradient(-45deg, hsla(0, 100%, 80%, 1), hsla(0, 100%, 80%, 1) 8px, hsla(0, 70%, 80%, 0.7) 8px, hsla(0, 70%, 80%, 0.7) 16px);
    background-clip: content-box;
    animation: 1s linear 0s infinite running scrollbackground;
    background-size: 4px var(--patternHeight); /* 16 * sqrt(2) */
}

/* Define --patternHeight for this keyframes animation to work! */
@keyframes scrollbackground {
    0% {
        transform: translateY(0px);
    }
    100% {
        transform: translateY(calc(var(--patternHeight)));
    }
}
```

This seems to be right.

> 
> Thank you!
> P

**Comment by dhanak** [comment]
Using StyleBot, I added the following simple CSS rule to the page:

```css
pluto-trafficlight::after {
  animation: none !important;
}
```

And it "resolves" the issue nicely, CPU usage drops to virtually 0.

**Comment by pankgeorg** [comment]
> PS: An interesting read on the subject: https://medium.com/better-programming/do-not-burn-you-cpu-working-with-css-animations-e4d19069fb0f It basically says: **don't** use CSS animations for this. If you must have a spinner effect, use an animgif.

Very interesting indeed. The thing with a GIF here is that we don't know the height. I will make a PR that will make the animations run only if visible on viewport (with Intersection Observer) and let's see how it goes from there.

**Comment by dhanak** [comment]
> > PS: An interesting read on the subject: https://medium.com/better-programming/do-not-burn-you-cpu-working-with-css-animations-e4d19069fb0f It basically says: **don't** use CSS animations for this. If you must have a spinner effect, use an animgif.
> 
> Very interesting indeed. The thing with a GIF here is that we don't know the height. I will make a PR that will make the animations run only if visible on viewport (with Intersection Observer) and let's see how it goes from there.

1. I don't think you need to know the exact height. The GIF only needs to be as tall as the height of the repeating pattern, and then you need to set the css property background-repeat to "y". But I'm not a CSS expert.
2. Limiting the animation to the viewport is an improvement, but does not solve the issue, because the example notebook above fits fully in my viewport.

**Comment by fonsp** [comment]
Problem with GIF is that I don't want to generate a new GIF just to change the color.

Also I would suspect that browsers already implement the intersection trick, otherwise open a PR to Mozilla :)

**Comment by fonsp** [comment]
Also I will say we should not compromise too much to solve this - most users do not experience a problem here. We have modern hardware for good reason!

**Comment by pankgeorg** [comment]
> Also I will say we should not compromise too much to solve this - most users do not experience a problem here. We have modern hardware for good reason!

I agree; also see my reply above about the Page Visibility trick.

I'm thinking the Intersection observer as it could also be used to avoid calculations in hidden cells - that, if it's identified that a lot of cells slow down the page due to the # of DOM elements.
