### ISSUE TITLE
PDF output does not preserve links

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#632]
The PDF export does not preserve links, external or internal (via footnotes etc.)
The HTML one does maintain it. Can pandoc with wktohtml be used as the default way to make pdfs? Editing HTML is way easier, and it'll also fix pdf export on non-Chromium browsers

**Comment by fonsp** [comment]
No pandoc would be overcomplicating things.

**Comment by dralletje** [comment]
For me on Chrome it does preserve links (https://gist.github.com/dralletje/be1a07a3bb4eb29f8e0c8c6ad9aa1282)
But yeah, if you want more advanced printing you should write a package or something 😁
