### ISSUE TITLE
Out of memory on repeated cell execution

### ISSUE THREAD

**Issue by mikolajpp** [fonsp/Pluto.jl#641]
As in the title. I have been running a simulation; every time I re-run it, gigabytes of memory needed for it never get freed, despite the fact it is the same cell being run. I am sure it is not julia's GC issue, because the exact same code executed repeatedly in the console does not suffer from this issue. 

Is there a way to ensure memory for a cell gets freed when I do a repeated run short of restarting the whole notebook?

**Comment by fonsp** [comment]
Pluto already has code to dereference old results, but maybe it's not working. Can you come up with a MWE?

**Comment by mikolajpp** [comment]
Make a single cell  `A = zeros(1000, 1000, 1000)` (or whatever your memory permits)
Then execute `A =  zeros(10, 10,10)` in the same cell. The memory allocated in the first call never gets freed.
Even deleting the cell does not free the memory, neither replacing the cell with a different variable altogether.

**Comment by dralletje** [comment]
@mikolajpp can you confirm this is fixed for you as well? Currently on master

**Comment by mikolajpp** [comment]
Things have definitely improved; I no longer observe memory exhaustion with the code I had been running, so at my end it is definitely fixed.
