### ISSUE TITLE
Adaptive cell width

### ISSUE THREAD

**Issue by hofmannmartin** [fonsp/Pluto.jl#642]
I have been starting to use Pluto for a lab course and very much like it.

My issue is the fixed cell width, which currently causes an awkwardly large blank space on the left hand side of the notebook. Is it possible to change the layout, such that it adapts the cell width to makes better use of the width of a landscape oriented screen?

**Comment by dietercastel** [comment]
Responsive design would indeed be nice! 👍 :-)

**Comment by fonsp** [comment]
(Pluto's UI is already responsive, the suggestion is to increase the maximum width. The reason we have a relatively small width is to have a natural paragraph width.)

**Comment by fonsp** [comment]
I have added this to our suggestion box: https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439
