### ISSUE TITLE
Attempted to send feedback but got this error. :-) 

### ISSUE THREAD

**Issue by dietercastel** [fonsp/Pluto.jl#643]
I just got this error, thought I'd share it here.

![woops](https://user-images.githubusercontent.com/2487783/98240140-45eb2e80-1f69-11eb-9a99-2f9d669e0265.png)

Julia 1.5.2
Pluto v0.12.6

**Comment by fonsp** [comment]
Oops! What was your feedback?

**Comment by dietercastel** [comment]
See #642, responsive design. :-)
