### ISSUE TITLE
Pluto sometimes does not copy to the right buffer for linux systems

### ISSUE THREAD

**Issue by leios** [fonsp/Pluto.jl#649]
Sometimes when copying and pasting via mouse (highlight and middle-click), Pluto does not paste the appropriate content.

We found that pasting text from within the same cell works and also copying arbitrary text from outside the cell will work; however, copying code from within a cell to another cell does not always work.

This is a linux-specific issue because other OSs do not typically use this copy and paste method.

**Comment by fonsp** [comment]
Since it works within a cell, it seems like codemirror already has a thing for this, but it would need to be adapted to work across cells
