### ISSUE TITLE
Alt+Arrow keys buggy for this cell

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#651]
![altdownbug](https://user-images.githubusercontent.com/6933510/98387688-00566080-2052-11eb-80dc-3930231b8376.gif)

```julia
function step_ray(ray::Photon, objects::Vector{O},
				   num_intersections) where {O <: Object}

	for i = 1:num_intersections
		if !iszero(ray.l)
			next_intersection = closest_hit(ray, object)
			
			aaaa from here aaaa
			bbbb until here bbbb


		end
	end

	return ray
end
```

**Comment by zerefwayne** [comment]
@fonsp Hello! New contributor here! Great job with the package. I would like to take up this issue.

**Comment by fonsp** [comment]
Awesome! Create a draft PR if you get stuck

**Comment by fonsp** [comment]
It looks like `Alt+Up` is fine, `Alt+Down` is broken

**Comment by amoghskulkarni** [comment]
Hello @zerefwayne, thanks for the initiative! Is this resolved? I would like to contribute if it isn't.

I tried to replicate the bug in the current version (v0.12.15), but `Alt+Down` behavior is as expected.

**Comment by fonsp** [comment]
Thanks @amoghskulkarni for the ping! This was indeed fixed by @zerefwayne in https://github.com/fonsp/Pluto.jl/pull/665
