### ISSUE TITLE
Cannot open new notebook 

### ISSUE THREAD

**Issue by srfall** [fonsp/Pluto.jl#655]
Propably related to  #578 and #553

Hey, i just tried to open Pluto for the first time and i get this error message:
````
julia> Pluto.run()

Opening http://localhost:1234/?secret=NpDNvVh9 in your default browser... ~ have fun!

Press Ctrl+C in this terminal to stop Pluto

┌ Error: (Base.IOError("read: connection reset by peer (ECONNRESET)", -4077), Base.StackTraces.StackFrame[wait_readnb(::Sockets.TCPSocket, ::Int64) at stream.jl:350, eof at stream.jl:48 [inlined], read_to_buffer(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Int64) at ConnectionPool.jl:251, readuntil(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Function, ::Int64) at ConnectionPool.jl:271, readuntil at ConnectionPool.jl:269 [inlined], readheaders at Messages.jl:471 [inlined], startread(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at Streams.jl:155, handle_transaction(::HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#212#219"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}}, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}; final_transaction::Bool) at Servers.jl:343, (::HTTP.Servers.var"#handle_transaction##kw")(::NamedTuple{(:final_transaction,),Tuple{Bool}}, ::typeof(HTTP.Servers.handle_transaction), ::Function, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}) at Servers.jl:338, handle_connection(::Function, ::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}, ::Int64, ::Int64) at Servers.jl:299, (::HTTP.Servers.var"#8#9"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#212#219"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}},HTTP.Servers.Server{Nothing,Sockets.TCPServer},Base.RefValue{Int64},Int64,Int64,Bool,HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})() at task.jl:356])
└ @ HTTP.Servers C:\Users\tu_install\.julia\packages\HTTP\IAI92\src\Servers.jl:264
````
I am using the latest version of Firefox 82.0.2 (64-Bit)

**Comment by fonsp** [comment]
Hi!

The logs from the Web Console would be really helpful! Unfortunately, you sent the **Browser Console** output, which is something internal unrelated to Pluto. Can you open the **Web Console** instead (`Ctrl+Shift+K`), and send that output?

Screenshot would also be very useful! Send as much information as possible, it can all be useful

**Comment by fonsp** [comment]
Do you have any adblock/privacy/cookie/VPN browser extensions installed?

**Comment by srfall** [comment]
oh my bad. Here are screenshots of the errors in the Julia console & from the web console.
![julia_errors](https://user-images.githubusercontent.com/65958585/98443316-d01ec880-210a-11eb-8802-b77e59e1c0e1.PNG)

these were the errors for the starting page (which was displayed)

![errors_starting_page](https://user-images.githubusercontent.com/65958585/98443643-d7df6c80-210c-11eb-9f06-3554f30da2e7.PNG)
![errors_part_2](https://user-images.githubusercontent.com/65958585/98443652-dca42080-210c-11eb-9516-ac38d7022b0c.PNG)

these were the errors when i tryed to open a new notebook (which gave me a blank page)

![error_web_console](https://user-images.githubusercontent.com/65958585/98443541-2e987680-210c-11eb-8c9f-617b7b9d7de3.PNG)


And yes i had the "DuckDuckGo Privacy Essentials" installed, which was problem.
After i removed this addon everything works.
![solved](https://user-images.githubusercontent.com/65958585/98443365-1e33cc00-210b-11eb-9b70-e3811e190426.PNG)
