### ISSUE TITLE
Hidden Dependencies - Always Re-Run Directive

### ISSUE THREAD

**Issue by jordanmb** [fonsp/Pluto.jl#657]
I'm absolutely loving the interactivity of Pluto. 

I've been working on audio software akin to Pure Data but with a Rust backend / Julia frontend interface. The problem I'm having is that I have hidden state dependencies in my code from building the underlying audio graph. The notebook cannot tell that my audio output must be re-run when I change a bound input parameter. 

Is there some way to annotate an always-rerun directive so that any changes will result in my final output being regenerated? If not, can someone help or point me towards implementing this feature? Thanks!

**Comment by fonsp** [comment]
Is this helpful? https://github.com/fonsp/Pluto.jl/issues/564#issuecomment-708768065

**Comment by jordanmb** [comment]
Unfortunately no, since the dependencies are external.

**Comment by jordanmb** [comment]
Though creating no-op dependencies is possible, that would become very cumbersome for anything non-trivial.

**Comment by fonsp** [comment]
In that case, Pluto might not be the right tool for your problem. I can't make it work for everyone, sorry

**Comment by jordanmb** [comment]
Fully understand, but it's so close to exactly what I need and mostly an adjustment to the dependency graph. I would love to contribute if you later feel that it could be an appropriate addition to your project.

**Comment by aplavin** [comment]
Not sure if I correctly understand your problem, but looks like something like this could help:
```
# cell with input parameters:
a = 123

# cell with audio output that indirectly depends on "a"
begin
    a
    output_audio()
end
```
That is, just put your parameter somewhere in the output cell so that Pluto recognizes the dependency. I do this from time to time in similar scenarios.

**Comment by jordanmb** [comment]
Actually, that is pretty helpful. I hadn't realized that you could have statements that don't evaluate anything like that. Thanks.
