### ISSUE TITLE
How to handle side effects?

### ISSUE THREAD

**Issue by tk3369** [fonsp/Pluto.jl#658]
For example, I have 3 cells:

```julia
x = [1, 2, 3]
```

```julia
s = sum(x)
```

```julia
x[1] = 4
```

Honestly, I don't know if this should be considered a bug or not. If it changes the second cell to `9` then it would look confusing because it appears before the third cell. But the problem is that if I re-run the second cell then it would display `9` and it's still confusing.

I'm filing this issue just to have a discussion.

**Comment by fonsp** [comment]
#564 #316
