### ISSUE TITLE
Only first letter of NamedTuple keys is shown

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#660]
I get this after updating to 0.12.7:
![image](https://user-images.githubusercontent.com/687995/98717977-d9c05e80-239e-11eb-82c0-df1b6366ae93.png)
Was fine before (at 0.12.5, I think).

**Comment by fonsp** [comment]
Thanks! A fix is underway

**Comment by aplavin** [comment]
Wow, that table viewer screenshots look great!
