### ISSUE TITLE
UndefVarError: Pkg not defined for Pluto v0.12.8

### ISSUE THREAD

**Issue by lungben** [fonsp/Pluto.jl#662]
Hi Fons,

I just upgraded to Pluto v0.12.8 and got the error message `UndefVarError: Pkg not defined` in my notebooks. They have been running fine in Pluto v0.12.7 and until yesterday in the `built-in-tables` branch.

As example, the sample notebook suggested here: #652

![image](https://user-images.githubusercontent.com/52384612/98804363-622e1600-2416-11eb-9303-a7a8c5474255.png)

**Comment by fonsp** [comment]
Very strange, it only happens on master, but not on #646 

It looks like an extra workspace is created without the `using`s:

![image](https://user-images.githubusercontent.com/6933510/98813582-ade7bc00-2424-11eb-939f-c7fb2486e215.png)

**Comment by fonsp** [comment]
It only happens when you run the notebook directly, not when you start running the notebook in the background from the main menu 🤷‍♀️

**Comment by fonsp** [comment]
Ah I think I have it 😚

**Comment by fonsp** [comment]
@hdrake This is probably the same issue that you mentioned yesterday

**Comment by hdrake** [comment]
> @hdrake This is probably the same issue that you mentioned yesterday

Yeah, it looks like it.

**Comment by fonsp** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/acf989502fdca93692d440e8d7769daaee89f50d - you can upgrade to 0.12.9 in 30 minutes

**Comment by lungben** [comment]
Thanks!
