### ISSUE TITLE
PlutoUI features not working without "PlutoUI." in front of them

### ISSUE THREAD

**Issue by casasgomezuribarri** [fonsp/Pluto.jl#663]
Hi, I updated my registry today and suddenly PlutoUI features give back the error `UndefVarError: Slider not defined` (Slide used for the example, but it happens with all the input types). Fortunately, they do work if referred to as `PlutoUI.Slider` rather than `Slider `. This is true also for the PlutoUI.jl sample notebook (see image below)

Is this something that I should be getting used to (and thus, change the code of all my other Pluto notebooks that use PlutoUI), or is this a bug that can be solved?

Thanks!

![image](https://user-images.githubusercontent.com/71462845/98820732-77ab3c00-2426-11eb-8513-b420101ce7d3.png)

**Comment by casasgomezuribarri** [comment]
(By the way, the new display for DataFrame objects is just perfect <3)

**Comment by fonsp** [comment]
Can you share the entire notebook?

**Comment by casasgomezuribarri** [comment]
That screenshot is from the PlutoUI.jl sample notebook, but I opened it again to share the link and It just worked. I haven't restarted julia or my browser, and the time between the two times I opened the notebook was under 15 minutes...

Sorry for panicking and thanks for the superquick reply..

**Comment by fonsp** [comment]
It was probably the same issue as #662
