### ISSUE TITLE
Stop a long Flux.jl call cleanly

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#668]
I got some cells that do long computations (I mean, Flux.jl), and I need a way to tell the cell to stop.

Interrupting the hard way is not what I mean. It shall stop when the next intermediate result is there. So I want, say, to uncheck a PlutoUI checkbox, and when the long running cell is in a sensible state, it can look at the value and behave accordingly.

What I see now is that my new checkbox value is used AFTER the long run is finished.

It there a way to do this?

**Comment by fonsp** [comment]
Hey zenon!

We can't do parallel execution by default, because cells might have side effects. However, we are working on a two-way communication channel, and this would allow a button click to stop execution I think? Let't talk more in a couple of months!

**Comment by zenon** [comment]
Hello Fons!

My hope was for, like, something that doesnt assign a new variable, and thus doesn't interfere with Pluto.  Like

     p.goOn = false

But right. We cannot exclude side effects this way (and actually, we want one :-) )

Hm. So it might need some PlutoUI channel, that is declared safe. Maybe.

Thank you for the answer!

Kind greetings, z.
