### ISSUE TITLE
Editing the .jl file in a separate text editor

### ISSUE THREAD

**Issue by cschloer** [fonsp/Pluto.jl#669]
Hey,

I'm excited to use Pluto for the notebook and visualization features. However, I prefer to write my code in VIM. I see that you have no plans to add any vim keybinding support (https://github.com/fonsp/Pluto.jl/issues/65) and frankly I don't think it's worth it, but I was hoping to be able to edit the Pluto source file using VIM and then have the Pluto UI update in my localhost directly. That doesn't seem to be working. If I exit pluto and reload the file the new code is there, but otherwise it doesn't reload automatically. Can you let me know if this is possible, and if so how? I'm running julia  1.5.2 in interactive mode.

**Comment by fonsp** [comment]
Thanks! You can subscribe to #240
