### ISSUE TITLE
Show line numbers in cells

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#67]
Although most cells are only 1 line long there are some longer cells, for example for function definitions where knowing the line number without counting it would be nice to trace stacktraces.

There is already a little dot printed before each line, that one could be replaced with the line number for cells longer than a few lines.

**Comment by fonsp** [comment]
Replacing line numbers with small `\cdot`s was intentional, to make the editor look more friendly 🎈

But you're right that having to manually count lines is a bit silly, I'll look into showing the line numbers on hover.

Eventually, the ideal solution is to highlight lines directly in the editor from the stacktrace, like most modern IDEs.

**Comment by fonsp** [comment]
(To anyone picking up this issue: this behaviour is defined [here](https://github.com/fonsp/Pluto.jl/blob/10d2b23c109a8dd008f784886573fd9a4c19fcda/assets/editor.js#L52-L54), and can be changed on the fly by setting the `lineFormatter` option of a codemirror to `i => "" + i` and calling `.refresh()` on that codemirror. But it would be nicer to do this just using CSS, perhaps using the `::after` selector or by creating the dot using a `background`.)

**Comment by karlwessel** [comment]
> Replacing line numbers with small `\cdot`s was intentional, to make the editor look more friendly 

In that you succeeded, I really like the style how the notebooks look :). 

Showing the line number only on mouseover will be completely sufficient.

**Comment by fonsp** [comment]
Alright! Great to hear that you have used Pluto enough to find this issue!

**Comment by fonsp** [comment]
Line numbers on hover in `0.5.20` 👆

**Comment by karlwessel** [comment]
I like it!

**Comment by SimonEnsemble** [comment]
many times during pair programming in `Pluto.jl`, can't communicate which line of a long function (in a single cell) to inspect. 😢 would be helpful for communication to have a setting/button where all line numbers are displayed. 😃

**Comment by niltsz** [comment]
I want to pick up on this issue and extend what @SimonEnsemble said. First, I love Pluto, especially the reactivity and the way it looks.
But I really think that having no line numbers should be changed. I use Pluto for teaching and every time I want to talk about the code or students want to ask something, there is this awkward necessity of describing which code snippets we are talking about ("up up up up up up up, down, stop, down, two down, one more, yeah, this line"). The same occurs when I want to show code to colleagues, also in an online meeting where no one can point with the finger at the monitor. Displaying the line numbers on hover does not really help with this issue as only one person can hold the mouse at a time, and the cursor can block the line number. 
Pluto is such a good tool for learning how to program, and having line numbers would make it even better.
In Jupyter Notebooks, one can toggle line numbers and the cells are enumerated, so one can easily refer to something with "cell 17, line 8".
Having a "communication mode" as suggested above would be greatly appreciated (or having line numbers always on as I do not consider them to be intimidating or ugly, but rather extremely useful)

**Comment by trg818** [comment]
Are there news on this one? I have googled for the topic and didn't really find something that told me how to do it. I'm flabbergasted that such a fundamental feature has not been implemented in the first place and is the default.
