### ISSUE TITLE
Assign in a macro should not be analysed as a real assign

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#670]
![image](https://user-images.githubusercontent.com/6257240/98968751-12198700-24dc-11eb-8bff-4de9287907eb.png)

**Comment by mcabbott** [comment]
Xref #196 and #407. 

`@benchmark` and friends aren't included there, but should presumably use `first_then_keywords`.

**Comment by GiggleLiu** [comment]
@mcabbott Thanks for the Xrefs. In this comment
https://github.com/fonsp/Pluto.jl/issues/196#issuecomment-690247347

Option 1 looks like a one for all solution. Wondering why do you choose option 3 later?

**Comment by mcabbott** [comment]
In my limited understanding of the internals here, I think the code which figures out whether cell A depends on cell B runs on a different process to the one actually executing code. So for macros defined in packages, or in the notebook, it can't easily just expand them. #407 is an admittedly crude attempt to teach it what some common macros mean.

**Comment by fonsp** [comment]
The problem isn't communication between processes, it's that _we need to know in which order to run cells before we run them_.

**Comment by fonsp** [comment]
#383

**Comment by fonsp** [comment]
I decided to implement this for the _second_ macro argument and after.

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/c6fa171b0ee7cbffcd151a982ec92a4b1b22c8f4#diff-fc12641be6676624c710d0dfd2459b1919b9020d75322416ac4ae055a99f5626R301
