### ISSUE TITLE
Consider using Scratch.jl instead of storing things in .julia/

### ISSUE THREAD

**Issue by KristofferC** [fonsp/Pluto.jl#676]
The `~/.julia` directory is not really meant as a place for packages to store their stuff in. Imagine if everyone did that and you had hundreds of folders in `.julia`. Really annoying :).

Instead, there is a package specifically for this called Scratch.jl: https://github.com/JuliaPackaging/Scratch.jl. That package gives you a folder where you can store things in and the package manager understands this so when the package hasn't been installed for a long time, it can clean that folder up (instead of it being left indefinitely on the harddrive).

**Comment by fonsp** [comment]
We're not using it because we are Julia 1.0 compatible, but I'll add this to the list of reasons to not support 1.0 anymore :)
