### ISSUE TITLE
Recapture output of an open session

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#679]
A low priority enhancement

I was working on an ssh'd Pluto notebook, when the ssh connection dropped. Interestingly, processes which are running did not stop. So when I started a new Pluto Session, it started it on port 1235.

Is there any way I can recapture the previously running session?

If there isn't, is it possible to implement this? If I'm not wrong, I think it will also allow us to free up the julia session for other commands(why would anyone need this? Idk), and one can join back to the Pluto session. But I suppose the main Pluto thread will itself have to be run on a different thread/worker/something.

**Comment by fonsp** [comment]
This is more of a linux question right?

**Comment by fonsp** [comment]
It's too niche to implement this into Pluto but maybe one day
