### ISSUE TITLE
ylims doesn't show plot correctly.

### ISSUE THREAD

**Issue by isboonto** [fonsp/Pluto.jl#680]
```
begin
       using Plots

	x = -360:0.01:360
	y1 = tan.((x/2)*π/180)
	y2 = -3*tan.((x/2)*π/180)
	plot(x, y1, color = :black, ylims = (-100, 100))
	plot!(x, y2, color = :red)	 
end
```
This block of code shows nothing in Pluto.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/99291017-73748980-283f-11eb-9179-57fdaca2a620.png)

It works, but there are so many point that your browser might run out of memory

**Comment by isboonto** [comment]
Dear Fons van der Plas Thank you for your reply. I discover that it happened only on Chrome and Edge (they use the same engine.) On Firefox, there is no issue. On FirefoxOn Chrome or Edge Best,Sudchai =============================================================Asst. Prof. Dr.-Ing. Sudchai Boonto Head of the Department Department of Control systems and instrumentation engineering King Mongkut's University of Technology Thonburi Phone (+66)2-470-9091 Fax (+66)2-470-9100 Mobile (+66)83-445-1138============================================================= From: Fons van der PlasSent: Tuesday, November 17, 2020 1:11 AMTo: fonsp/Pluto.jlCc: isboonto; AuthorSubject: Re: [fonsp/Pluto.jl] ylims doesn't show plot correctly. (#680) It works, but there are so many point that your browser might run out of memory—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by isboonto** [comment]
It does not work with Chrome and Edge. 
on Firefox
![image](https://user-images.githubusercontent.com/59634198/99622928-aac08180-2a5d-11eb-8b94-a7e237361544.png)

on Chrome and Edge
![image](https://user-images.githubusercontent.com/59634198/99622836-7ea50080-2a5d-11eb-965b-7a04f1a76403.png)

**Comment by fonsp** [comment]
It's too many points causing a bug in Chome
