### ISSUE TITLE
Plots rotation=90 doesn't show ticks

### ISSUE THREAD

**Issue by joaogui1** [fonsp/Pluto.jl#681]
When using the `rotation=90` keyword in Plots Pluto crops the ticks
```Julia
using StatsPlots
a = rand(10, 2)
boxplot(a, x_ticks=(1:3, ["cat a", "cat b"]), xrotation = 90)
```
![image](https://user-images.githubusercontent.com/13261989/99191605-6f1b7400-274c-11eb-9c06-d77cf05da54f.png)

**Comment by fonsp** [comment]
Is this caused by Pluto?

**Comment by joaogui1** [comment]
No, it seems to be a problem with StatsPlots, didn't think of that, sorry!
