### ISSUE TITLE
Calling a notebook as a function from command line or REPL?

### ISSUE THREAD

**Issue by cooknl** [fonsp/Pluto.jl#684]
Is it possible to call a notebook file with input arguments from the command line or REPL?

I could not find any mention of such functionality in the documentation or articles written about Pluto.

**Comment by fonsp** [comment]
https://github.com/fonsp/PlutoUtils.jl

**Comment by cooknl** [comment]
Thank you for taking the time!

**Comment by fonsp** [comment]
🌈
