### ISSUE TITLE
Authentication issue with VS Codespaces, ipadOS

### ISSUE THREAD

**Issue by scottsteph** [fonsp/Pluto.jl#687]
Trying to use in Safari on iPad Pro, on online.visualstudeio.com.

First page opens, but when I click on option to either open a sample notebook or create a new one, I just get stuck on the page:

——

Not yet authenticated
Open the link that was printed in the terminal where you launched Pluto. It includes a secret, which is needed to access this server.

If you are running the server yourself and want to change this configuration, have a look at the keyword arguments to Pluto.run. 

Please report this error if you did not expect it!

Go back

—-

:(

**Comment by Pocket-titan** [comment]
Hi!
Do you happen to see a link in the terminal where you launched Pluto, as the message states? If so, try pressing the `Ctrl` key and clicking on it, that should launch the proper url in a new tab.
If that doesn't work, you can try running `Pluto.run(;require_secret_for_access=false)` instead of `Pluto.run()`, after which the normal url should work fine.

(Looks like Codespaces will automatically detect a service running on a specified port & offer to navigate to it, but this will just go to the root & not include the secret provided.)

**Comment by scottsteph** [comment]
Cntl+click opens a new browser window no prob. I can get to the welcome page but get no further.

Your second solution looked great in principle but when I tried it I indeed got a link without the secret code however the exact same issue occured.  When I then click open a sample or create a new file I end up back being asked for a secret code. Ugh


Not yet authenticated

Open the link that was printed in the terminal where you launched Pluto. It includes a secret, which is needed to access this server.

If you are running the server yourself and want to change this configuration, have a look at the keyword arguments to Pluto.run.

Please report this error<https://github.com/fonsp/Pluto.jl/issues> if you did not expect it!


Go back<https://17d649f1-a66b-402b-a98b-c87e0e3234e4-1235.app.online.visualstudio.com/>

________________________________

**Comment by fonsp** [comment]
Even if this is fixed, we don't support iOS yet: https://github.com/fonsp/Pluto.jl/issues/688

**Comment by scottsteph** [comment]
Ok, thanks.

Hope you do get around to fixing it. Not many options for programing on an iPad, but if it does get fixed, this would be one!

Cheers
________________________________

**Comment by fonsp** [comment]
And to answer this question:

VS Codespaces has its own authentication system, so you should disable Pluto's authentication:
```julia
import Pluto; Pluto.run(require_secret_for_access=false, require_secret_for_open_links=false)
```
