### ISSUE TITLE
Store user config/data on server instead of client

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#690]
Data like _recent notebooks_ etc should be stored on the server, not in the browser.
MOST of the time, this isn't an issue, but if you switch from a local instance to an ssh instance, you'd expect the local nbs to not show.

I suppose you should use Scratch.jl as in #676, but like noted, thats a Julia v1.0 thing. Until then, maybe use `~/.julia/pluto/recents.json` or something like that?

**Comment by fonsp** [comment]
Can you post this suggestion to the [feedback box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) instead?
