### ISSUE TITLE
Display parent dirs for notebooks with same names

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#691]
Suppose you have
```
rt
|- labs
|    |- l1
|    |    |- notebook.jl
|    |
|    |- l2
|    |    |- notebook.jl
|    |
|    |- notebook.jl
|
|- labsnew
     |- l1
          |- notebook.jl
```
Then recent notebooks will have 4 `notebook.jl` entries, which is not illustrative at all.
Instead, it would be better to display the shortest path without ambiguity

```
labs\l1\notebook.jl
l2\notebook.jl
labs\notebook.jl
labsnew\l1\notebook.jl
```

**Comment by fonsp** [comment]
We have the full path as hover text as a "fix"

**Comment by DhruvaSambrani** [comment]
https://github.com/fonsp/Pluto.jl/blob/0da6d5853e761ffdf777dded5a463b7ec0bc2637/frontend/components/Welcome.js#L15

This needs to be changed to 
```js
const shortestpath = (path, otherpaths) => {
    level = 1
    for (one_other_path in otherpaths) {
        while split_to_level(path, level) == split_to_level(one_other_path, level) {
            level+=1
        }
    }
    return split_to_level(path, level)
}
```
This isn't the most efficient way, because you check the same set of paths twice, and you can branch prune it, but eh, this is fast enough for even like 20 files.

**Comment by DhruvaSambrani** [comment]
Also, as a related note, see https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.Path for better path manip? But it'll add a dependency 😢

**Comment by fonsp** [comment]
The browser OS can be different from the server OS

**Comment by DhruvaSambrani** [comment]
If no one picks it up quickly, I'll try implementing this in a few days 😄

**Comment by DhruvaSambrani** [comment]
Since PR is merged, close the issue?

**Comment by fonsp** [comment]
Thanks again!
