### ISSUE TITLE
Printing variables defined through SymPy

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#692]
Below is a screenshot of a MWE of the issue:
![image](https://user-images.githubusercontent.com/61620837/99505898-b50d4d80-2981-11eb-8bfa-2feb7fb632b8.png)

Initially, the yellow box is tiny. When clicked, it becomes larger and one can see the unrendered LaTeX inside:
![image](https://user-images.githubusercontent.com/61620837/99506181-0fa6a980-2982-11eb-9259-d44fdd6ef5ef.png)

 Is this an issue with how Pluto handles the displaying of `Sym` objects, or with how SymPy chooses to display `Sym` objects? Can it be fixed/improved?

**Comment by fonsp** [comment]
#488
