### ISSUE TITLE
Live docs tokenizing issues

### ISSUE THREAD

**Issue by yuhan0** [fonsp/Pluto.jl#694]
Some operators are not tokenized correctly, eg. `|>`,  `&&` and `||` .
When placing the cursor over them, the live docs treats it as single-character operators and shows documentation for  `|`, `>` and `&`.  
Other 2-character operators that I tried like += or << don't have this issue.

Types are also parsed incorrectly in when directly following `::` without a space between, eg.
```julia
x::Array{Int64}
```
With cursor over Array or Int64,  it displays docs for the close curly bracket `}` instead of the types themselves.

**Comment by dralletje** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/d5499c37bffce1f45dc1c3892c5135d809f2a260
Too bad `Array{Int64}` doesn't yet show any smart docs... will look into that later
