### ISSUE TITLE
Cannot see content of nested namedtuple vectors

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#697]
Generally nested vectors display fine (1st cell in the screenshot), but not when they contain namedtuples (2nd cell):
![image](https://user-images.githubusercontent.com/687995/99744786-68dd1d00-2ae9-11eb-9fc8-a708cbcfccf0.png)
A minimal example: type `[[(a=1,)]]` into a cell.

**Comment by fonsp** [comment]
Related to #706
