### ISSUE TITLE
Run Pluto on jost but work on Local over SSH

### ISSUE THREAD

**Issue by Flock1** [fonsp/Pluto.jl#698]
Hello,

I work on Mac but the GPU and heavy-duty stuff is done on the server-side. So I wanted to know if I can run Pluto on the server machine but use the browser on my local machine? Will it be possible?

**Comment by SyxP** [comment]
Yes this is possible. See the remote work section in https://juliahub.com/docs/Pluto/OJqMt/0.7.6/ .

**Comment by Flock1** [comment]
Thanks. I don't know why Google didn't point me to this link?

**Comment by fonsp** [comment]
Let us know how it goes!

**Comment by Flock1** [comment]
Hi,

So it works. But I think there are some changes, probably because of the updates. 

This line `Pluto.run(1234)` should be `Pluto.run(port = 1234)`

In this line `ssh user@ipaddress -LN 1234:localhost:1234`, I got a `Bad local forwarding specification 'N'` error. 

So am I missing something or is it just the updates?

**Comment by fonsp** [comment]
Thanks! Could you update the wiki?

**Comment by Flock1** [comment]
Sure

**Comment by Flock1** [comment]
Hi,

I am new to this. So I don't know exactly how to edit the wiki. So can you help me with it?
