### ISSUE TITLE
Service Worker: only cache CDN requests if it is fixed version

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#701]
We also cache CDN requests that are not part of Pluto's internals, which is a great feature! This allows packages like plotly to work offline, after you have used them once inside Pluto.

However, we should not cache:
https://cdn.jsdelivr.net/npm/d3-scale@latest/dist/d3-scale.min.js

Because it is not a fixed version. We **should** cache:
https://cdn.jsdelivr.net/npm/d3-scale@3.2.3/dist/d3-scale.min.js

This one I'm not sure about:
https://cdn.jsdelivr.net/npm/d3-scale@3/dist/d3-scale.min.js

---

A possible solution is to search for a full version specification in the URL. Another (better) solution could be to respect the response headers -- it looks like jsdelivr gives a much higher max-age to fully specified versions.

**Comment by pranjanpr** [comment]
Hello @fonsp . Please tell me more about Pluto's internals and what exactly the CDN requests are caching more.

**Comment by fonsp** [comment]
Not necessary because of #1948
