### ISSUE TITLE
Modules defined at separate cells got evaluated into different workspaces

### ISSUE THREAD

**Issue by chigiryov** [fonsp/Pluto.jl#702]
1. Create a new pluto notebook
2. add a "module A" to a first cell
```julia
module A
end
```
3. evaluate the first cell
4. add a "module B" to a second cell
```julia
module B
end
```
5. evaluate the second cell
6. observe that modules are added to different workspaces
![image](https://user-images.githubusercontent.com/578729/99856747-f112ff00-2b89-11eb-9ddf-6517539dcee5.png)

Environment:
- julia version 1.5.3
- Pluto v0.12.11 🎈

**Comment by fonsp** [comment]
This is unavoidable -- it's how Pluto works: https://youtu.be/IAF8DjrQSSk?t=588

**Comment by chigiryov** [comment]
Thank you for explanation.

I'm new to Pluto and I find that its interactivity is really amazing.

Regarding the situation with modules, I have found that if I go to start screen, shut there the notebook down and start it again then modules get evaluated to the same workspace. But this requires 4 mouse clicks and some mouse moves.

Is there a way to restart a notebook without leaving a notebook's screen?

**Comment by fonsp** [comment]
There is not. Maybe you can explain why this workspace system is a problem for your use case?

**Comment by chigiryov** [comment]
I'm trying to interactively develop a small utility module to use in my Pluto notebooks while I'm reading the ISLR book and trying to apply what I've learned.

The module is really simple: given a dataset it projects it onto a structure that defines predictors and label of the model.
```julia
struct ModelData
    X
    Y
    Predictors
    Label
end

function compose_modelLabeledData(data, predictors, label)
    X = Float64[]
    Predictors = Dict{Symbol, Int64}()

    index = 1
    for predictor in predictors
        for d in data
            push!(X, d[predictor])
        end
        Predictors[predictor] = index
        index = index + 1
    end

    Y = Float64[]
    for d in data
        push!(Y, d[label])
    end
    ModelData(reshape(X, size(data)[1], size(predictors)[1]), Y, Predictors, label)
end
```

**Comment by fonsp** [comment]
You use `Predictors` instead of `predictors` in some places. Is that the problem?

**Comment by chigiryov** [comment]
Thank you for your replies. Now I can see that this is not a bug, but a feature. I wrongly attributed a problem in design of my code to the fact that modules are sometimes placed in different workspaces.

I defined two modules. ModelDescription:
```julia
module ModelDescription
	struct ModelData
		X
		Y
		Predictors
		Label
	end

	function compose_modelLabeledData(data, predictors, label)
		X = Float64[]
		Predictors = Dict{Symbol, Int64}()

		index = 1
		for predictor in predictors
			for d in data
				push!(X, d[predictor])
			end
			Predictors[predictor] = index
			index = index + 1
		end

		Y = Float64[]
		for d in data
			push!(Y, d[label])
		end
		ModelData(reshape(X, size(data)[1], size(predictors)[1]), Y, Predictors, label)
	end

	function get_predictor_value(data ::ModelDescription.ModelData, index, predictor)
		return model.X[index][model.Predictors[predictor]]
	end
end
```

and the second one - LinearRegression:
```julia
module LinearRegression
	using LinearAlgebra;
	using Statistics;

	function calculate_parameters(modelData)
		X = [ones(size(modelData.X)[1])  modelData.X]
		X_t = transpose(X)

		return LinearAlgebra.inv(X_t * X) * X_t * modelData.Y
	end

	function calculate_SME(model, modelData)
		X = modelData.X
		Y = modelData.Y
		Ŷ = [calculate_hypothesis(model, x) for x in eachrow(X)]
		return mean((Ŷ - Y) .^ 2)
	end

	function calculate_hypothesis(model, x)
		return model[1] + model[2:end]⋅x'
	end
end
```

and the error was that I was trying to reference `ModelDescription` module from `LinearRegression` module. It confused me a bit because I was able to reference modules I have installed with Pkg but not a module from a cell in notebook. But it turned out to be a a good thing and helped to avoid unnecessary coupling between modules.
