### ISSUE TITLE
Plots won't load

### ISSUE THREAD

**Issue by BrettKnoss** [fonsp/Pluto.jl#703]
Plots.jl cycles but never loads or gives an error.

**Comment by SyxP** [comment]
I decided to comment on this. @BrettKnoss has given more information on this problem on discourse: https://discourse.julialang.org/t/pluto-fails-to-compile-plots/50886

I believe this is related to https://github.com/JuliaLang/julia/issues/35663 . Pluto creates an environment for each notebook, and thus the proposed mitigation of of opening the environment directly from a fresh Julia run does not work.

**Comment by m-yaghini** [comment]
This fixed my issue (note that you have to run this inside a Pluto cell):
```
import Pkg; Pkg.build("Plots")
```
