### ISSUE TITLE
Confusion Between Latex and Variable

### ISSUE THREAD

**Issue by koaning** [fonsp/Pluto.jl#704]
I'm started playing with Julia again because of Pluto. So first off: well done! You're really on to something here. 

I think I have found a bug though. It seems like the markdown parser is having a bit of trouble detecting when something is referring to a variable and when something is meant to be rendered as Latex. See screenshot.

![image](https://user-images.githubusercontent.com/1019791/99900823-5b26c380-2cb2-11eb-8880-89d279252f78.png)

My guess is that it might be due to the fact that `start_size` is inside of a markdown list? It renders it fine at the bottom. 

The code for this can be found below. 

```julia
begin
	@bind start_size Slider(60 : 1 : 1000, show_value=true)
	@bind y Slider(60 : 1 : 1000, show_value=true)
	@bind prob Slider(60 : 1 : 1000, show_value=true)
end

md"""
# Let's do a simulation! 

Let's say that there are some folks who cheat a little bit while doing research. Normally you would collect a set of data and then you'd perform a hypothesis test. You'd do this exactly once! 

Let's say that instead of doing this, you'd go a step further.

1. Collect some data of a minimum size $start_size. Check if it yields a significant result (p=$prob). 
2. If it does, publish! 
3. If it doesn't we'll collect one more sample and check if it yields a siginificant result.
4. We keep on doing this until we've collect so many that we've become tired (upper limit = $limit).
The value of `start_size` is $start_size.
"""
```

**Comment by SyxP** [comment]
For this specific case, if you don't mind, you can change it to `p= $prob` (Note the space!), I think the markdown treats anything of the form `r"\$[^ ].*[^ ]\$"` as LaTeX.

**Comment by fonsp** [comment]
Unfortunately `md"""` is part of julia itself, not of Pluto. https://github.com/JuliaLang/julia/labels/markdown
