### ISSUE TITLE
Support AxisKeys and friends

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#708]
```
using AxisKeys
KeyedArray([1 2; 3 4]; i=2:3, j=["a", "b"])
```
![image](https://user-images.githubusercontent.com/687995/99952862-66045580-2d91-11eb-8d4f-acdfc6302ab1.png)

If I'm not mistaken, those displayed fine before recent Pluto updates. Also I confirmed that everything works in Julia REPL and IJulia.
Looks like issues lie somewhere in the Pluto "magic" trying to show the arrays as rich as possible.

**Comment by fonsp** [comment]
Thanks! You can subscribe to #458

**Comment by fonsp** [comment]
Sorry, I edited your comment to remove the duplicate issue #458, but AxisKeys is new

**Comment by aplavin** [comment]
I guess I missed that issue you link.

**Comment by aplavin** [comment]
Do you think it's possible to make the fix more general than "support AxisKeys"? Surely there are other packages, more or less popular, that define various array types, and some of those types may suffer from similar issues.
E.g., maybe just fallback to "regular" plain-text rendering if the "rich" one errors?

**Comment by mcabbott** [comment]
So the problem appears to be that it's going through the Tables.jl interface, which AxisKeys.jl provides in case it's a useful way to get data out into something else. But the structure isn't principally a table. It's an N-dim array, with labels along each axis. 

It overloads the basic REPL printing heavily. I haven't really looked into providing an HTML version. (Last time I looked at PrettyTables.jl, which I think does so, it did not seem easy to hook up --- it seemed quite focused on tabular data, headings & columns. But that was a while ago.)

**Comment by fonsp** [comment]
The error is fixed in https://github.com/fonsp/Pluto.jl/pull/726

Pluto now displays it as a table:

![image](https://user-images.githubusercontent.com/6933510/100480232-fa075180-30f0-11eb-8690-fc02b0cb46fb.png)

You can open a new issue if this is not what we want
