### ISSUE TITLE
File picker - recent files

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#71]
The new file choser is nice!
There are two improvements I would like:
1. Ignore case for suggestions: when typing `~/w` it should also suggest `~/WWW` (maybe sorted after matching case suggestions).
2. Before the autocompletion feature was implemented, chromium suggested values I previously entered into that box, which allowed to access previously opened notebooks very easyly. This doesn't work anymore, therefore some support for faster access to previously used notebooks would be nice.

**Comment by fonsp** [comment]
1. I agree that case insensitive suggestion would be better. Unfortunately we are using Julia's [built-in path completion from the REPL](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/REPLCompletions.jl#L194), which is always case-sensitive. So we might need to define our modified version of it. (Which makes Pluto more messy...). Or perhaps there's a workaround.
1. I'll look into it! I quite like _not_ having a config file anywhere on you computer, and instead using cookies on the client-side. Let's wait with this until #6 is figured out.

**Comment by karlwessel** [comment]
1. Ok, than I would also keep it like it is. I'm in huge favor of reusing as much existing libraries as possible and they will have their reason to be case-sensitive.
2. Sounds like the best would be if chromium suggestions would work with the new file picker.

**Comment by fonsp** [comment]
Hm good point, the input box suggestions were actually quite nice without using cookies. Maybe they can be revived.

**Comment by fonsp** [comment]
What about cookie laws? @dralletje

**Comment by fonsp** [comment]
Would be cool if the _recent files list_ and the _running notebooks list_ are one and the same! Running notebooks are the most recent anyways :) 

Each filename would have an on/off switch next to it - this way you can start Pluto, turn on today's notebooks, and start making tea. This would also be the _restart notebook_ UI.

**Comment by karlwessel** [comment]
That sounds very good.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/82483803-4ede6580-9ad9-11ea-9e6f-8f1105a09211.png)

**Comment by fonsp** [comment]
You can also stop notebook processes here, or start running notebooks in the background.
