### ISSUE TITLE
Option to increase cell width to display tables

### ISSUE THREAD

**Issue by rleyvasal** [fonsp/Pluto.jl#715]
I understand the cells in Pluto are narrow to center markdown paragraphs, but it would be a good idea to have the option to increase the cell width to be able to display tables.

Having long cells to display tables is specially helpful when working with multiple datasets, because it makes it easier to compare the columns on multiple tables.

![Pluto_table](https://user-images.githubusercontent.com/61335136/100289962-fb891c00-2f2e-11eb-80c8-80c52d4152ce.PNG)
![Jupyter_table](https://user-images.githubusercontent.com/61335136/100289967-fdeb7600-2f2e-11eb-917a-b3885cb12b0b.PNG)

**Comment by fonsp** [comment]
Thanks! You should **update Pluto**, and if the new table viewer does not solve your problem, let us know using the built-in feedback system: https://github.com/fonsp/Pluto.jl/issues/182
