### ISSUE TITLE
Pluto not playing nice with Queryverse

### ISSUE THREAD

**Issue by rleyvasal** [fonsp/Pluto.jl#716]
I am going through David Anthoff's Queryverse tutorial with Pluto and I found I cannot run the following line of code.

cars |> @groupby(_.Origin) |> @map({Origin=key(_), Count=length(_)})

I am not sure what the problem is or what the workaround would be. 

The table cars is from: 
using Queryverse, VegaDatasets
cars = dataset("cars")

Link to the tutorial: https://www.youtube.com/watch?v=OFPNph-WxLM

The same line of code runs fine in Jupyter Notebook:

![Queryverse_Pluto](https://user-images.githubusercontent.com/61335136/100291104-b4505a80-2f31-11eb-81e0-67108cce3a2b.PNG)
![Queryverse_Jupyter](https://user-images.githubusercontent.com/61335136/100291110-b6b2b480-2f31-11eb-8705-e741658f2d47.PNG)

**Comment by rikhuijzer** [comment]
I got this all the time too when using Queryverse. An easy workaround is to wrap each query in a separate function. Note that "write functions, not just scripts" is the first item in the [Julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions,-not-just-scripts).

**Comment by mcabbott** [comment]
I think Pluto doesn't really handle macros at the moment, see #196 . 

You might be able to fool it by doing things in a `let` block?

**Comment by fonsp** [comment]
Since `{}` is not part of vanilla julia, we can add a rule to fix queryverse without affecting normal use

**Comment by mcabbott** [comment]
Maybe that would be enough. It might also solve PgfPlotsX & Vegalite? My list from long ago: https://github.com/fonsp/Pluto.jl/issues/196#issuecomment-691721773

**Comment by rikhuijzer** [comment]
For completeness: it seems that the LINQ Style Query Commands are not considered. For example,
```
using Query, DataFrames

df = DataFrame(a=[2,1,1,2,1,3],b=[2,2,1,1,3,2])

x = @from i in df begin
    @orderby descending(i.a), i.b
    @let foo = i.b
    @select { c = i.a, d = foo }
    @collect DataFrame
end
```
 c | d
-- | --
3 | 2
2 | 1
2 | 2
1 | 1
1 | 2
1 | 3

This currently reports "Multiple definitions for ..." when trying to define `foo`, `c` or `d` in another block.

**Comment by mcabbott** [comment]
Interesting. I think there's a rule that assignments after the first macro argument are viewed as keywords, so that `@test a ≈ b atol=0.01` works. But perhaps that doesn't recurse into this `begin end` block... should it? Would it cause problems with e.g. 
```
@views @inbounds begin
    a = b[1:10]
    c = b[11:20]
end
```
Another possibility: maybe Query should accept `x = @from i in df let` instead of `begin`?

**Comment by aplavin** [comment]
Is it considered possible that at some point Pluto will be able to run arbitrary Julia code? I mean general macros, independent on their structure. Or this is likely infeasible within the Pluto execution model?

**Comment by aplavin** [comment]
By the way, there is another piece of Query syntax not mentioned here that causes the same issues when used in Pluto:
`[(a=1,)] |> @mutate(b=2) |> collect`

**Comment by mcabbott** [comment]
@aplavin It's a bit tricky, some discussion here: https://github.com/fonsp/Pluto.jl/issues/670
