### ISSUE TITLE
TAB-completion inside a string (inside quotes) is different from normal

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#717]
When writing a string, e.g. with the cursor where the star is in `md"my_text* "`, the autocompletion is different compared to when not in a string. When trying to autocomplete `\omega` to get the greek symbol, it is autocompleted to `\Documents and Settings\\`. 

This is annoying in general, but especially when defining a unit like Ohm. I then have to close the string macro with an extra `"`, write `\Omega<TAB>`, and erase the extra `"`. It is not a major problem at all, but annoying. Anyone else experiencing this, and does anyone know of a way to fix it?

**Comment by fonsp** [comment]
Thank you for the report!

This is supposed to be a 'feature' of Julia: autocompleting paths inside strings, but I'm not sure that I agree with this feature. Especially because (in the future) I want to motivate authors to write notebooks that are standalone, i.e. do not depend on local files. 

@aviatest What do you think? Can/Should we disable path autocomplete inside strings?

**Comment by aviatesk** [comment]
> Can/Should we disable path autocomplete inside strings?

you can filter our path completions:
https://github.com/fonsp/Pluto.jl/blob/9bea6ea7418fbf6e73ae8e7b5da21b751f450dc3/src/runner/PlutoRunner.jl#L684-L690
with something like
```julia
filter!(!Base.Fix2(isa, FuzzyCompletions.PathCompletion), result)
```

And `query` parameter there allows up further fine tuning like filtering path completions only within string-macro scope, etc:
```julia
# suppress path completions only within string-macro scope
x = Meta.parse(query)
if isa(x, Expr) && x.head === :macrocall
     filter!(!Base.Fix2(isa, FuzzyCompletions.PathCompletion), result)
end
```

Well, I'm not sure if we _should_ disable path completions or not. Even within a notebook context, it's sometimes useful e.g. when we want to load local CSV data when using Pluto in a data science context.

**Comment by aviatesk** [comment]
> I then have to close the string macro with an extra ", write \Omega<TAB>, and erase the extra "

Well, separate from the path completion discussion, FuzzyCompletions somehow doesn't seem to provide latex completions within a string scope. I will dug into this this weekend or so.

**Comment by KronosTheLate** [comment]
> > I then have to close the string macro with an extra ", write \Omega, and erase the extra "
> 
> Well, separate from the path completion discussion, FuzzyCompletions somehow doesn't seem to provide latex completions within a string scope. I will dug into this this weekend or so.

Amazing, thanks a lot <3. This package and team are amazing - I have recently swiched to Pluto as my main IDE/place to do programming ^_^

**Comment by aviatesk** [comment]
bump FuzzyCompletion to v0.4.0 will fix this issue.

**Comment by fonsp** [comment]
Can you make a PR? Is there a breaking change?

**Comment by aviatesk** [comment]
Nothing breaking, but here is: https://github.com/fonsp/Pluto.jl/pull/727

**Comment by fonsp** [comment]
Thanks! Next time, you could register it as a patch (0.4.0 -> 0.4.1) instead of a breaking release (0.4.0 -> 0.5.0). This means that Atom and Pluto get the latest FuzzyCompletion features without doing anything :)

**Comment by aviatesk** [comment]
I hesitated to do patch release and silently fix this issue , but yeah, it certainly doesn't follow the semantic versioning..

**Comment by icweaver** [comment]
Hi, sorry if this is the wrong place to ask this. Has the file completion for paths already started to be removed? I think I am still able to complete paths if I type a character that is present:

```julia
"em<TAB>
```
completes to:

```julia
"emma.txt
```

but attempting to complete from nothing just inserts the tab:

```julia
"<TAB>
```

completes to:

```julia
"    |<-- cursor now here
```

I totally see your point about trying to nudge people towards writing standalone notebooks, but I personally happen to fall in the data science context brought up by @aviatesk:

> Well, I'm not sure if we should disable path completions or not. Even within a notebook context, it's sometimes useful imho e.g. when we want to load local CSV data when using Pluto in a data science context.

and would absolutely love to retain this feature if it's not too late

**Comment by icweaver** [comment]
Hey Fons, thanks for getting back to me so quickly! Unfortunately not. It seems to just insert a single space instead

**Comment by icweaver** [comment]
Oh, but doing it without the forward slash does the trick! I'm happy to just stick with that =]
