### ISSUE TITLE
File picker completion is weird

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#719]
The screenshot basically explains this issue:
![image](https://user-images.githubusercontent.com/687995/100365345-6a8a7180-3010-11eb-931a-83a1322f2853.png)
I typed `wo` and that's the completions list I got. Isn't it a little strange that `work` is not on top? I'm pretty sure it was, before a recent Pluto update...

**Comment by fonsp** [comment]
@aviatesk

**Comment by aviatesk** [comment]
Removing the `sort` at this line will solve this:
https://github.com/fonsp/Pluto.jl/blob/9bea6ea7418fbf6e73ae8e7b5da21b751f450dc3/src/webserver/REPLTools.jl#L45

<img width="385" alt="Screen Shot 2020-11-27 at 0 39 08" src="https://user-images.githubusercontent.com/40514306/100370072-12bc2c80-3049-11eb-8e2e-4124782a6811.png">

**Comment by fonsp** [comment]
Thanks @aviatesk ! Implemented in [`c03bea6` (#699)](https://github.com/fonsp/Pluto.jl/pull/699/commits/c03bea6b0bf0d887d84cb9fc698fc47e1326bb58)
