### ISSUE TITLE
Add features to navigate big notebooks

### ISSUE THREAD

**Issue by feanor12** [fonsp/Pluto.jl#721]
When writing notebooks with multiple topics/chapters it would be nice to have a table of contents or a way to collapse sections of the notebook.

This could be based on markdown header levels.

This could also be used to generate additional ways in the exported file formats like html or pdf.

**Comment by fonsp** [comment]
A table of contents is in the works: https://github.com/fonsp/PlutoUI.jl/pull/30

You can post additional suggestions to the feedback box: https://github.com/fonsp/Pluto.jl/issues/182
