### ISSUE TITLE
Copy Closes Pluto

### ISSUE THREAD

**Issue by BrettKnoss** [fonsp/Pluto.jl#730]
The Command to end Pluto is Ctrl C, which is also copy, even if I'm in the REPL trying to grab an error code, or working in another tab of my browser, or even an unrelated app, Copy doesn't work and instead closes Pluto.

**Comment by SyxP** [comment]
Often terminals support `Ctrl + Shift + C` and `Ctrl + Shift + V` to copy and paste. I believe it is a little unidiomatic to not have `Ctrl + C` as the send kill signal in this context.

**Comment by fonsp** [comment]
`Ctrl+C` in a terminal shuts down the process. This is due to an unfortunate tradition, I wish I could change it, but I can't.
