### ISSUE TITLE
A bug on Markdown equation

### ISSUE THREAD

**Issue by isboonto** [fonsp/Pluto.jl#731]
![image](https://user-images.githubusercontent.com/59634198/100522804-2fd63400-31de-11eb-8505-fe4ad6bbbce8.png)

**Comment by fonsp** [comment]
Unfortunately this is an issue with Julia itself (`md"` is part of Julia), not with Pluto, so we can't fix it.

Try removing the spaces after the `$`

**Comment by isboonto** [comment]
Thank you for your help. I find one method by using a slash before the subscript.
![image](https://user-images.githubusercontent.com/59634198/100739086-28df3980-3409-11eb-8edc-d1df3b85c22b.png)

**Comment by fonsp** [comment]
Again, try removing the spaces around `$`

so `$f(...)$` instead of `$ f(...) $`
