### ISSUE TITLE
Pluto doesn't like adding constructors to structs

### ISSUE THREAD

**Issue by MasonProtter** [fonsp/Pluto.jl#732]
Compare

![image](https://user-images.githubusercontent.com/29157027/100526109-2b306200-3183-11eb-9360-0e23fe1a8778.png)

versus

![image](https://user-images.githubusercontent.com/29157027/100526137-4e5b1180-3183-11eb-8136-f3139911db88.png)

Seems like a bug in the algorithm for detecting multiple incompatible definitions of something.

**Comment by fonsp** [comment]
This is on purpose, handling a mix of structs definitions and methods is very very difficult.

**Comment by MasonProtter** [comment]
I get that it's difficult, but I feel this issue should stay open (whether or not anyone is actively working on it). This is certainly an issue other people will run into at some point so it'd be good for them to see that there's already an open issue.

If you want, you can even use the 'Won't Fix' label.

**Comment by SyxP** [comment]
If you want a workaround somehow, the following works.
```
struct Temp
	x
end

Temp(4)

for i in [:Temp]
	@eval ($i)() = Temp(42)
end

Temp()
```

**Comment by MasonProtter** [comment]
Yeah, one can also just do 
```julia
@eval $(:Temp)() = Temp(42)
```
Still pretty unsightly, but a bit better.

**Comment by fonsp** [comment]
**I don't recommend this to general users -- it will lead to lots of hidden issues later. Use a `begin` block.**
