### ISSUE TITLE
Pluto does not precompile in julia REPL 

### ISSUE THREAD

**Issue by Kingston802** [fonsp/Pluto.jl#733]
After ```using Pluto```, the Julia REPL (and my terminal instance) crashes. I get no output and I can't find any logs. Julia otherwise works fine on my Manjaro Linux (Kernel 5.9.10) install and I can precompile other packages (checked with JSON). Pluto worked fine in the past but after coming back to it after a few weeks it doesn't precompile anymore. I updated Julia from the arch repo but that didn't fix anything and then I built Julia from the git repo (v1.5.3) and the behaviour did not change.

**Comment by fonsp** [comment]
I can't reproduce, and there is not enough information here for us to fix it. Some notes:
- We test Pluto precompilation on Julia 1.5.3 with Ubuntu regularly (and it works)
- Try the recommended way to install Julia: https://julialang.org/downloads/platform/#linux_and_freebsd
- The fact that the REPL crashes tells me that this is probably not an issue with Pluto but with your window manager/OS/Julia install

Finally, try launching Pluto without a browser:
```
Pluto.run(launch_browser=false)
```
