### ISSUE TITLE
MS Codespaces - Safari on iPad fail

### ISSUE THREAD

**Issue by scottsteph** [fonsp/Pluto.jl#736]
Hi,

I just can’t get notebooks to load on an iPad in codespaces. First issue appeared to be authentication related, which seemed to be workaroundable with:

`Pluto.run(require_secret_for_access=false, require_secret_for_open_links=false)
`

When I start Pluto with this I can at least get to the start page, however, when I click on any sample notebook or create a new one, it just gets stuck loading. I can see the Pluto header and “Loading....” but never get to see a Pluto code block :)

(Sidenote, Ctrl - C doesn’t work on iPad to close Pluto either)

Any tips hugely appreciated....

**Comment by fonsp** [comment]
Whic iOS version do you have? We only support iOS 14 and up.

**Comment by scottsteph** [comment]
I tried it unsuccessfully on 14.2. Latest iPad pro with magic keyboard. :(



Dr B. Scott Stephens | Research Officer, Emissions Reduction Pathways

Climate Branch

NSW Department of Primary Industries | Agriculture

10 Valentine Ave, Paramatta | NSW 2800

T: +61 2 9842 8062 | E: scott.stephens@dpi.nsw.gov.au<mailto:scott.stephens@dpi.nsw.gov.au>

________________________________

**Comment by fonsp** [comment]
I tested it and it works for me!

Short description of what I did:
- Run github codespaces on my computer (it did not work on my iOS 14 phone, but this should not make a difference)
- Update Pluto to the latest version (today it's `0.12.17`) and run using the command you sent.
- Cmd+Click on `http://localhost:1234/` in the terminal, I get redirected to Pluto in a new tab
- I copy the long URL (looks like `https://700f8d71-fbb2-40a8-9e91-517dc9624fc6-1234.apps.codespaces.githubusercontent.com/`) and send it to myself
- I sign in to github on safari on my phone
- Open the link

Let's call to look at your setup together, you can share your ipad screen using the zoom app, right? fons@mit.edu

**Comment by scottsteph** [comment]
Hi,

Thank you for the message.

I am still waiting on Github codespaces access.  Been waiting a while, so hopefully not too much longer. The MS Codespaces account I was complaining about is about to die, so I remain in limbo and can’t really try anything atm, but thanks for the offer.

Keep up the fantastic work with Pluto! Hopefully I can get it working on this machine when I have an account.



Dr B. Scott Stephens | Research Officer, Emissions Reduction Pathways
Climate Branch
NSW Department of Primary Industries | Agriculture
4 Parramatta Square, 12 Darcy St, Parramatta, NSW 2150.
T: +61 2 9842 8062 | E: scott.stephens@dpi.nsw.gov.au
________________________________
