### ISSUE TITLE
Shift + Enter behavior

### ISSUE THREAD

**Issue by shashi** [fonsp/Pluto.jl#74]
`Shift + Enter` runs the cell and creates a new cell below it.

In Jupyter it runs the cell and selects the next cell, unless the cell being run is the last cell in the notebook in which case it creates a new cell at the end and selects that.

I think this would be great to have, I always want to run something and go to the next cell to edit (or run it -- but Pluto takes care of that for me anyway).

**Comment by fonsp** [comment]
Thanks for the feedback! This is implemented in Pluto `0.5.21` (live in about 30 mins). 🌈
