### ISSUE TITLE
Changing and rerunning cells returns wrong results

### ISSUE THREAD

**Issue by roflmaostc** [fonsp/Pluto.jl#741]
Hey,

I encountered a critical bug in Pluto v0.12.15:

First cell:
```julia
function foo(x, y)
	@show x, y
	return x, y
end
```
Second cell:
```julia
foo(10, 20)
```
If I now swap the arguments in the second cell and run it again, the output stays the same. However, the cells are executed (terminal shows a new @show message with old result).

Here two screenshots:
[First run](https://imgur.com/hPqfR7s)
[Second run](https://imgur.com/1dN7kqU)

I'll  report back which versions are still working.

Cheers,

Felix

Update: v0.12.14 works flawless, v0.12.15 seems to be broken.

**Comment by fonsp** [comment]
Thanks! Sorry for the trouble, I have written a fix and will release an update soon

**Comment by roflmaostc** [comment]
Cool, thanks!
I just questioned my Julia skills for a moment :D

**Comment by fonsp** [comment]
Yeah this must have been very confusing, thanks for narrowing it down and reporting an issue!

**Comment by fonsp** [comment]
You can update to Pluto 0.12.16 in about 30 minutes, when this PR is merged: https://github.com/JuliaRegistries/General/pull/25687
