### ISSUE TITLE
standard output is not flushed

### ISSUE THREAD

**Issue by ess3sq** [fonsp/Pluto.jl#742]
**Description of my issue:**

Apparently, standard output is not flushed immediately after the `print`/`println` or `@show` call.
Of course, flushing a couple characters at a time can slow the performance by a significant amount if done repeatedly, instead of at the end.
However, for some reason it ~sometimes~ often happens that output is not flushed even after cell execution finishes, which can be annoying if one is attempting to test something before continuing. This can be even more annoying if one re-executes the same cell  several times after performing changes, and the output has still not been flushed.
Then, at some point, it does get flushed (all at once, of course), which may be difficult to deal with if one changed a bunch of things and re-executed the cell over and over to test things out.

**Question:**

Is this a problem caused by Pluto or does it lie with Julia? (When working with the REPL or with source files, `stdout` gets flushed quick enough).
Is there some way to force flushing of `stdout`?

Ty in advance

**Comment by dralletje** [comment]
I'll have a try at reproducing this.
We can force flush the output after every cell run, but there is some special care we need to take because it can also be buffered in the main Pluto process.
Do you have a specific example notebook that you experience this with?

**Comment by fonsp** [comment]
This is an issue with Distributed, a standard library part of Julia

**Comment by RaulDurand** [comment]
Is there any chance to have the std output in an additional box above the results box?
