### ISSUE TITLE
MLJBase prevents macro @bind from working

### ISSUE THREAD

**Issue by casasgomezuribarri** [fonsp/Pluto.jl#743]
Hello,

I've spotted that if the package `MLJBase` is added to the environment, the `@bind` macro from `PlutoUI` stops working.

To replicate this behaviour, create a new Pluto notebook and add the following two cells:

```
begin
	import Pkg
	Pkg.add(["PlutoUI", "MLJBase"])
	using PlutoUI
	using MLJBase
end
```

```
begin
	numbers = ["1", "2", "3", "4", "5"]
	num_list = @bind number Select(numbers)
end
```

And the second cell gives out the following error:
`LoadError: UndefVarError: @bind not defined`

Note that if the line `using MLJBase` is deleted, the second cell runs normally.

**Comment by fonsp** [comment]
Can you try if `PlutoRunner.@bind number Slider(1:5)` is a workaround?

**Comment by casasgomezuribarri** [comment]
It is :) I

I had tried `PlutoUI.@bind` because I thought `@bind` was part of `PlutoUI`

Thanks!

**Comment by casasgomezuribarri** [comment]
Sorry for keeping up with this issue, but when you change `@bind` for `PlutoRunner.@bind`, the changes made to the variable (in the example case `numbers`) don't change the value of the variable in subsequent cells. 

For replication, add the following three cells to a new notebook:

> begin
> 	import Pkg
> 	Pkg.add(["PlutoUI", "MLJBase"])
> 	using PlutoUI
> 	using MLJBase
> end

> begin
> 	numbers = ["1", "2", "3", "4", "5"]
> 	num_list = PlutoRunner.@bind number Select(numbers)
> end

> number

Now, if I select the string `"3"` in the drop-down menu, the third cell doesn't re-evaluate and still returns `"1"`. If I run again the second cell, then I get the following error:

> cannot assign a value to variable workspace17.number from module workspace27
> 
> top-level scope@PlutoRunner.jl:1070
> top-level scope@Local: 3

**Comment by fonsp** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/ba76ac0a932b93f87a36bdca7ecc3b13020eadf7
