### ISSUE TITLE
image display using ImageShow

### ISSUE THREAD

**Issue by johnnychen94** [fonsp/Pluto.jl#747]
Now that https://github.com/JuliaIO/ImageIO.jl/issues/6 is fixed and probably Pluto can offload the image displaying work to ImageShow.

In JuliaImages, any colorant array, i.e., `AbstractArray{<:Colorant}`, should be recognized and displayed as an image. It seems like Pluto doesn't exactly follow this convention. For example, `PaddedView` were not rendered as an image in Pluto but it is in IJulia: https://github.com/JuliaImages/juliaimages.github.io/pull/167#issuecomment-739254972

**Comment by johnnychen94** [comment]
> It seems like Pluto doesn't exactly follow this convention. For example, PaddedView were not rendered as an image in Pluto but it is in IJulia: JuliaImages/juliaimages.github.io#167 (comment)

Oh wait, it seems actually works on `PaddedView`.

![image](https://user-images.githubusercontent.com/8684355/101245680-644f7000-3749-11eb-9c2d-84d24c095b1e.png)

**Comment by ashwani-rathee** [comment]
I hadn't used ImageShow in my example which could have created the issue.
