### ISSUE TITLE
Layout: Make use of full screen width

### ISSUE THREAD

**Issue by AndiMD** [fonsp/Pluto.jl#748]
Hi,
Output like inline plots seem to be confined to the width of the cells. I would like to use the full width of my screen for plots and tabular output.

Some suggestions mention the hack
`html"""<style>main {max-width: 900px;}"""`
but in my maximized Chromium browser window, this completely breaks the layout: The "Live docs" do not hover over the cells, but instead take a huge amount of the screen, while the cells move out of the visible screen area to the left.

**Comment by dralletje** [comment]
You can do
```
html"""<style>
main {
    max-width: 900px;
    align-self: flex-start;
    margin-left: 50px;
}
"""
```

**Comment by fonsp** [comment]
Thanks for your input! Could you post this to Pluto's built-in suggestion box instead?

https://github.com/fonsp/Pluto.jl/issues/182

**Comment by complyue** [comment]
I have no idea, but something is imposing a `margin-right: 500px`, rendering the workaround ineffective.

![image](https://github.com/fonsp/Pluto.jl/assets/15646573/9ba23cba-0e30-43bc-9a51-530865a0598f)

How this `css` get into coming?

![image](https://github.com/fonsp/Pluto.jl/assets/15646573/08dd8643-0728-4563-9cb2-492c9566affd)

**Comment by ymaltsman** [comment]
I have tried all of these suggestions and they expand the cells to fullscreen, but not plots. How would I get my plots to be the same size as the cells?
