### ISSUE TITLE
Bug with FilePicker and ~

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#75]
Filepicker is able to correctly autocomplete paths starting with `~` in the home directory like `~/mynotebook.jl`.
However Pluto itself doesn't seem to be able to handle that path since it only displays
```
Can't find a file here.

<a href="/">Go back</a>
```
when opening the notebook.

Using the full path `/home/user/mynotebook.jl` works correctly.

**Comment by fonsp** [comment]
Good catch 👍 Fixed in `0.6.1`
