### ISSUE TITLE
Bug with simple variable assignment

### ISSUE THREAD

**Issue by yurivish** [fonsp/Pluto.jl#751]
The two lines in the screenshot below should assign `x` the value `:identity`, but Pluto treats it as if the assigned value was the `identity` function instead.

![image](https://user-images.githubusercontent.com/114388/101435859-15d1db00-38db-11eb-9c8a-f3664f318fb4.png)

This happens on Pluto version `[c3e4b0f8] Pluto v0.12.16`.

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by fonsp** [comment]
neat!

**Comment by fonsp** [comment]
Fixed! Test set here: https://github.com/fonsp/Pluto.jl/commit/af3eb766b516309948e6afd8906f84190eb961cc#diff-8beb9b826e38c913d27b5b05fe5ac03df15a97d3a2dba1011422b7f5ed7cf8fdR882-R883

**Comment by yurivish** [comment]
Thank you!
