### ISSUE TITLE
[improvement] XeTeX, rtf cells

### ISSUE THREAD

**Issue by BrettKnoss** [fonsp/Pluto.jl#752]
I realize this is a way off, but I would like to have XeTeX cells, instead of Markdown, for more editing options.  RTF or a WYSIWYM editor would be cool.  Again...Someday.

**Comment by SyxP** [comment]
XeTeX is hard because there are only two renderers for TeX on the web, MathJax and KaTeX.

**Comment by fonsp** [comment]
Yes would be cool, and absolutely possible inside Pluto! Markdown happens to be included in Julia itself, but you can use packages with string macros (like `md"` for markdown) to use any other templating library ☺️

So the request is more of a request to the general Julia community, not so much to Pluto.

I agree that WSISYDWIYIYG would be awesome, it's on our radar
