### ISSUE TITLE
Pluto fails to run Julia 1.5.3 on Windows Server 2016, Windows 10

### ISSUE THREAD

**Issue by AmitXShukla** [fonsp/Pluto.jl#753]
I did a fresh Julia 1.5.3 install on two different different windows machine, added Pluto, and Pluto.run() fails to run Julia.

It opens a new notebook but pwd() or any julia command spins forever
Pkg.instantiate() didn't make any difference either.

```
[c3e4b0f8] Pluto v0.12.16
Stacktrace:
┌ Warning: Reading WebSocket client stream failed for unknown reason: TaskFailedException:
│    On worker 2:
│    LoadError: LoadError: ArgumentError: Package FuzzyCompletions [fb4132e2-a121-4a70-b8a1-d5b831dcdcc2] is required but does not seem to be installed:
│     - Run `Pkg.instantiate()` to install all recorded dependencies.
│
│    _require at .\loading.jl:999
│    require at .\loading.jl:928
│    require at .\loading.jl:923
│    include at .\client.jl:457
│    top-level scope at C:\Users\amit\packages\Pluto\2aIAB\src\runner\Loader.jl:7
```

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by fonsp** [comment]
Thanks for the report! Just to be clear:

> on two different different windows machine

These are Windows 10 and Windows Server 2016, both did not have Julia or Pluto installed before, and both failed?

**Comment by AmitXShukla** [comment]
Right, two different windows machine, fresh Julia download, never had Pluto before, throw similar error when Pluto.run().

> These are Windows 10 and Windows Server 2016, both did not have Julia or Pluto installed before, and both failed with this same error?

**Comment by SteffenPL** [comment]
I had exactly the same issue a few days ago. In my case, it was Julia 1.5.2 portable on Windows 10. It didn't work with Pluto v0.12.16 with exactly the same error. I went back to Julia 1.5.2 (portable) and Pluto v0.12.9.

**Comment by AmitXShukla** [comment]
> 
> 
> I had exactly the same issue a few days ago with Julia 1.5.2 portable on Windows 10 and Pluto v0.12.16. I went back to Pluto v0.12.9. (v0.12.15 also didn't work.)

Thanks @SteffenPL, I will downgrade to v0.12.9 until this issue is resolved.

**Comment by fonsp** [comment]
I tried to reproduce this but didn't manage:
https://github.com/fonsp/Pluto.jl/runs/1533631275?check_suite_focus=true

**Comment by AndiMD** [comment]
Hi there,
I had the same issue when starting Pluto within an activated project. Pluto was added just to this active project, but not in to the default v1.5 environment.
Once I added Pluto to the default environment as well, the error was gone.

Environment: Windows 10, Pluto v0.12.17, Julia 1.5.3

Cheers

**Comment by AmitXShukla** [comment]
> 
> 
> Hi there,
> I had the same issue when starting Pluto within an activated project. Pluto was added just to this active project, but not in to the default v1.5 environment.
> Once I added Pluto to the default environment as well, the error was gone.
> 
> Environment: Windows 10, Pluto v0.12.17, Julia 1.5.3
> 
> Cheers

Genius.. It worked. Closing this issue.

**Comment by fonsp** [comment]
It's fixed in the next release

**Comment by dpo** [comment]
It still seems to be the case for me on macOS that Pluto doesn't work (evaluating a cell never terminates) unless installed in the global environment.
