### ISSUE TITLE
code block dark mode disappear after clicking hide and show!

### ISSUE THREAD

**Issue by Roger-luo** [fonsp/Pluto.jl#754]
so there is DarkMode.jl which is awesome, but if you type something, then click hide

![image](https://user-images.githubusercontent.com/8445510/101583355-5730bc00-39a9-11eb-9802-bc28f46c3f1a.png)

then click show

![image](https://user-images.githubusercontent.com/8445510/101583375-5dbf3380-39a9-11eb-81c5-ebb67651c293.png)

the dark mode of code blocks disappear. And you can fix it by manually re-run the dark mode cell

![image](https://user-images.githubusercontent.com/8445510/101583495-9959fd80-39a9-11eb-944b-4574cf274f16.png)

I guess this is because part of the style sheet is reloaded or overwritten by each other somehow, not a js expert don't know to fix it... I guess have to ask for help here.

**Comment by pankgeorg** [comment]
This seems to be an issue with [DarkMode](https://github.com/Pocket-titan/DarkMode/issues/2), not Pluto.jl!
It may needs Pluto support though @Pocket-titan, fyi

**Comment by fonsp** [comment]
Let's move it there 😋
