### ISSUE TITLE
`Base.getpass` raises an error in Pluto notebooks

### ISSUE THREAD

**Issue by gcalderone** [fonsp/Pluto.jl#755]
In Jupyter I can use `Base.getpass` to interactively ask a password:
![Jupyter](https://user-images.githubusercontent.com/12463718/101642625-7f64fd00-3a33-11eb-9848-a256e2261df2.png)

While in Pluto an error is raised:
![Pluto](https://user-images.githubusercontent.com/12463718/101642653-8ab82880-3a33-11eb-97a8-85201480389e.png)

Is there a way to use `Base.getpass` in Pluto?

**Comment by fonsp** [comment]
Thanks for the suggestion! I did not know about `Base.getpass`. In the meantime you can use `@bind pass_string PlutoUI.PasswordField()` (or something similar). (This is insecure in the sense that other running Julia packages could read the value.)
