### ISSUE TITLE
Discussion: storage of notebook assets

### ISSUE THREAD

**Issue by lungben** [fonsp/Pluto.jl#760]
There are several use cases for storing assets (non-notebook files) alongside Pluto notebooks:
- included data #707
- Project and Manifest files (maybe, see #142)
- Serialized notebook state (maybe, see [link](https://www.notion.so/Pluto-jl-a9982e79b7bb4c658e6216c15a9d4cab?p=a4a878b7dec44f668f160e5d371f572c))

Possibilities to store assets:

## a) Base64 encoded inside the notebook.jl file
Pro: 
* The notebook including assets is a single file
* Easy to share by e-mail (if not too large)

Contra:
* Does not work so nicely together with version control (git) - changes in assets cause not really easy to understand git diffs of the notebook file
* It is not easily possible to extract or modify the asset files

## b) Make each notebook a zip (or tar) archive
Pro: 
* The notebook including assets is a single file
* Easy to share by e-mail (if not too large)
* Easy to extract or modify asset files

Contra:
* Does not work so nicely together with version control (git) - git only sees if the archive has changed, but not what parts of it. Thus, code modifications inside the notebook.jl file cannot be tracked.

## c) Make each notebook a folder
Pro: 
* Works nicely with version control (git)
* Easy to extract or modify asset files

Contra:
* Folders cannot be directly sent per e-mail but must be zipped beforehand. This point could be mitigated by offering a "download as zip" export option in Pluto, plus the option of opening a zip archive (compressed notebook directory) in Pluto.

Currently, my favorite is option c), but maybe there is a different option we have not thought about yet?
Happy to discuss!

**Comment by fonsp** [comment]
Would it be alright to move this to our notion page? That way we can all edit the pros and cons

**Comment by lungben** [comment]
Sure 😄

**Comment by lungben** [comment]
Moved to Notion:

https://www.notion.so/Storage-of-notebook-assets-9b41d6e668ba4edcb28347a98e1ef245
