### ISSUE TITLE
When running in Linux, but a Windows path given, try to map to Linux path and strip quote marks

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#763]
I'm running Pluto in WSL on Windows, and encountering an issue with interoperability.

In File Explorer, Shift+Right Click => "Copy as path" produces the path in quotation marks, e.g. `"C:\Users\nicho\Documents\Pluto\notebook.jl"`.

To use that, I have to manually convert it to `/mnt/c/Users/nicho/Documents/Pluto/notebook.jl`.

It would be a nice quality-of-life feature if it would perform this transformation for me.

**Comment by fonsp** [comment]
Thanks! 

This would be easyish to implement, WSL comes with a tool for that: https://devblogs.microsoft.com/commandline/windows10v1803/#interoperability

See my comments here:
https://github.com/tpapp/DefaultApplication.jl/issues/13

**Comment by fonsp** [comment]
Yes, yes, and you can start in `src/webserver/Static.jl`, search for `open`
