### ISSUE TITLE
A nicer filenotfound error page

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#77]
Not great:

![image](https://user-images.githubusercontent.com/6933510/79081576-118af900-7d1f-11ea-9282-a2852a1ecb77.png)

**Comment by fonsp** [comment]
Tips:

Write a basic `error.html` file (I already started), and write something like `{{ error message here }}` inside the .HTML script. When there is an error (`Static.jl`), open the file, and use string replace to put the error in.

**Comment by TheCedarPrince** [comment]
Question: just to confirm, is the error file you are referencing this one: [`assets/error.jl.html`](https://github.com/fonsp/Pluto.jl/blob/master/assets/error.jl.html)? Thanks for clarifying @fonsp

**Comment by TheCedarPrince** [comment]
Started working on draft PR #148
