### ISSUE TITLE
Cannot access Pkg REPL by pressing ]

### ISSUE THREAD

**Issue by rleyvasal** [fonsp/Pluto.jl#771]
I want to be check the status of packages and add packages directly from Pluto, but I cannot do it. 

For example:

 ] status

] add Queryverse

Note: The above commands do not work on Pluto but they do work with Jupyter notebooks.

**Comment by fonsp** [comment]
Thanks! Can you post this to our suggestion box instead? https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439
