### ISSUE TITLE
Move the x that removes a cell to make it more intuitive

### ISSUE THREAD

**Issue by tskarhed** [fonsp/Pluto.jl#773]
Having the x inside the input box makes unclear that it removes the cell. It feels like it removes the content of the input box.

My suggestion would to be to put it next to the entire cell - like this:
![image](https://user-images.githubusercontent.com/1438972/102000453-e14d8d00-3ce7-11eb-8926-71ddb0abd7f8.png)

Then you know that the action is on the cell, rather than the content of the input box.

Share any additional thoughts that you might have on this!

**Comment by fonsp** [comment]
Can you be clear about which problem you want to solve?

> It feels like it removes the content of the input box.

That's close to what it does, but the problem is...
