### ISSUE TITLE
Try to show random image

### ISSUE THREAD

**Issue by boroboro77** [fonsp/Pluto.jl#782]
Hello! Very great work with Pluto! 
Unfortunately sometimes i get very strange problems.
This is one of them:
![image](https://user-images.githubusercontent.com/15941106/102281353-054edf80-3f2f-11eb-8880-f5a79af834f2.JPG)

Can someone tell me what goes wrong?

**Comment by fonsp** [comment]
Can you copy paste the error? It got cropped in the image

**Comment by boroboro77** [comment]
`img

Failed to show value:

MethodError: no method matching save(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Array{ColorTypes.RGB{Float32},2}, ::Pair{Symbol,ImageShow.var"#14#16"})

Closest candidates are:

save(::IO, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\Manuel Stathis\.julia\packages\PNGFiles\3VoQP\src\io.jl:300

save(!Matched::String, ::S; compression_level, compression_strategy, filters, palette) where {T, S<:Union{AbstractArray{T,3}, AbstractArray{T,2} where T}} at C:\Users\Manuel Stathis\.julia\packages\PNGFiles\3VoQP\src\io.jl:268

    handle_error(::MethodError, ::FileIO.Stream{FileIO.DataFormat{:PNG},IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}})@error_handling.jl:82
    handle_exceptions(::Array{Any,1}, ::String)@error_handling.jl:77
    #save#33(::Base.Iterators.Pairs{Symbol,ImageShow.var"#14#16",Tuple{Symbol},NamedTuple{(:mapi,),Tuple{ImageShow.var"#14#16"}}}, ::typeof(FileIO.save), ::FileIO.Formatted, ::Any)@loadsave.jl:238
    #show#13(::Int64, ::Int64, ::Function, ::typeof(show), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGB{Float32},2})@showmime.jl:43
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/png")}, ::Array{ColorTypes.RGB{Float32},2})@showmime.jl:28
    show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:380
    #sprint_withreturned#23(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Array{ColorTypes.RGB{Float32},2})@PlutoRunner.jl:333
    #format_output_default#13(::Pair{Symbol,Dict{Tuple{UInt64,Int64},Int64}}, ::typeof(Main.PlutoRunner.format_output_default), ::Any)@PlutoRunner.jl:268
    #format_output#14@PlutoRunner.jl:285[inlined]
    formatted_result_of(::Base.UUID, ::Bool, ::Nothing)@PlutoRunner.jl:76
    top-level scope@none:1`

**Comment by fonsp** [comment]
Fixed in https://github.com/JuliaIO/PNGFiles.jl/pull/29 , try updating your packages

**Comment by boroboro77** [comment]
thank you a lot!
