### ISSUE TITLE
code cells not rendering properly on Android via github

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#785]
The bottom line of a code cell is being cut off when viewed in Chrome or Firefox on Android.

See https://klaff.github.io/android_display_bug_MWE.html for simple test page.

**Comment by klaff** [comment]
A not-too-obnoxious workaround is to include a blank line at the end of each code cell. I updated my MWE above to have a cell without and a cell with the extra line.

**Comment by pankgeorg** [comment]
Well, I've opened a PR #805 with a possible solution (loads CodeMirror in again in the export to do the height management correctly)

Happy holidays!

**Comment by fonsp** [comment]
linked to #823

**Comment by pankgeorg** [comment]
@fonsp for the HTML export part, this PR exists https://github.com/fonsp/Pluto.jl/pull/805.
If we go another way we should close it!

**Comment by pankgeorg** [comment]
also seems to handle the linked issue (823)

**Comment by fonsp** [comment]
Fixed by the wonderful @pankgeorg  !!!! Will be released in the next version
