### ISSUE TITLE
Pluto is too fast for its own good!

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#787]
Sometimes `Pluto.run()` opens up the tab in the browser before the server is fully up and running. It's not a big deal, but it may be worth adding a slight pause before trying to open up the web browser to give the server a chance to get fired up and ready to go.

<img width="1272" alt="Screen Shot 2020-12-17 at 7 20 30 PM" src="https://user-images.githubusercontent.com/226872/102570776-f423e100-409c-11eb-8bc1-3a768dea786e.png">

**Comment by fonsp** [comment]
Maybe we should do a GET request to our own server and await the response. This would also make Pluto 'feel more snappy' because compilation time is moved up

**Comment by samuela** [comment]
Yeah, that would be nice in the sense that it would get back to the user as fast as possible.
