### ISSUE TITLE
disabling the context menu on right-click

### ISSUE THREAD

**Issue by gszep** [fonsp/Pluto.jl#789]
Apparently you can disable it [using a little bit of Javascript](https://stackoverflow.com/questions/51958065/prevent-context-menu-from-opening-on-a-right-click-over-element/51958093). How do I disable it globally in Pluto? It is interfering with the plot panning interaction in ```WGLMakie.jl```.
![Screenshot from 2020-12-19 18-00-32](https://user-images.githubusercontent.com/17977117/102694892-3af01300-4224-11eb-9943-c2b2dbf7cd82.png)

**Comment by fonsp** [comment]
Maybe this is something that WGLMakie should do?

_Did you fix WGLMakie support or is this an old version?_

**Comment by gszep** [comment]
the newest version still does not work. I'm using the previous version `WGLMakie v0.2.9`

**Comment by gszep** [comment]
but yes I think you are right it would rather be a `WGLMakie` issue

**Comment by fonsp** [comment]
Yep! But it might already be fixed in the latest version :)
