### ISSUE TITLE
Cannot display 2d structarray

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#792]
1d structarray works fine:
![image](https://user-images.githubusercontent.com/687995/102742657-7c88d700-4366-11eb-89c0-12b4bad8a6c8.png)
2d doesn't:
![image](https://user-images.githubusercontent.com/687995/102742685-92969780-4366-11eb-9034-aa92bedde0a0.png)
The error message totally makes sense, in a way: there is no single correct way to represent such a 2d array as a "table". Even more so for n-dim arrays, btw.
But I just wanted to see the array content as a, well, array, and not present it as a table...

Code:
```
using StructArrays
StructArray(a=[1, 2], b=[3, 4])
StructArray(a=[1 2; 3 4], b=[3 4; 5 6])
```

**Comment by mcabbott** [comment]
xref #708, which also needs to be displayed as an array, but (slightly less mysteriously) also gets treated as a table.

**Comment by klaff** [comment]
A 1D StructArray of a custom struct also fails to print correctly.
```
### A Pluto.jl notebook ###
# v0.12.20

using Markdown
using InteractiveUtils

# ╔═╡ 48380550-65e1-11eb-3959-55744dce2512
begin
	import Pkg
	Pkg.activate(mktempdir())
	Pkg.add("StructArrays"); using StructArrays
end

# ╔═╡ 5e082090-65e1-11eb-0285-25917ae1d42c
struct MyStruct
	a::Int
	b::Float64
end

# ╔═╡ 698912d0-65e1-11eb-3c4f-db0ce950ed54
a = [MyStruct(1,2), MyStruct(3,4)]

# ╔═╡ 797faeb0-65e1-11eb-307f-991200cabe8d
StructArray(a)

# ╔═╡ Cell order:
# ╠═797faeb0-65e1-11eb-307f-991200cabe8d
# ╠═698912d0-65e1-11eb-3c4f-db0ce950ed54
# ╠═5e082090-65e1-11eb-0285-25917ae1d42c
# ╠═48380550-65e1-11eb-3959-55744dce2512
```
gives
```
Failed to show value:

MethodError: no method matching length(::Main.workspace216.MyStruct)
...
```
message, but the same code prints reasonably at the REPL:
```
julia> StructArray(a)
2-element StructArray(::Vector{Int64}, ::Vector{Float64}) with eltype MyStruct:
 MyStruct(1, 2.0)
 MyStruct(3, 4.0)

```

**Comment by aplavin** [comment]
Bump... This is still an issue in the latest Pluto version.
