### ISSUE TITLE
Feature Proposal: Exported HTML can be passed to a static site generator

### ISSUE THREAD

**Issue by FelixBenning** [fonsp/Pluto.jl#794]
# Short Intro to Static Site Generators

I recently experimented with static site generators (e.g. [Jekyll](https://jekyllrb.com/), [Hugo](https://gohugo.io/), ...) as you can easily host static websites on [github pages](https://pages.github.com/) for free and with static site generators you can simply write content in markdown instead of having to learn html. And using a layout template you get a good looking website without much effort.

In case of Hugo you would add the following yaml heading at the top of your markdown document:

```markdown
---
title: "A page"
date: "2020-12-21"
tags: [static-site, julia]
---

## Start of the actual markdown document

```

And you would put that markdown `document.md` into the `/content/rel/path/to/the/markdown` folder and the static site generator would generate a html document from it and put it into the index pages such that its link is `https://domain/rel/path/to/the/markdown/document`

In other words you can easily generate a content-only page without any html/css/js knowledge

# Pluto Notebooks

Now while you can use markdown, you can also use html and add the same headers as in markdown documents to include them in the templates.

I tried this with a Pluto html output and it worked surprisingly well. But it still distorts the page (the width becomes really small) and for some reason changed the font of the table of contents to bold.

Manually removing the `<link rel="stylesheet" ...>` and `<style>` tags in the header did not seem to do anything. So it seems that a ton of the styling is done in the body of the html document.

What I think would be necessary to make this a smooth experience, would be to somehow make a clean separation between the content and styling such that the content can be passed to a static site generator for it to do its thing. (This could also be used to enables themes for the pluto editor itself with custom stylesheets)

Another problem might be, that the site generator wraps the html document into a box and the html document assumes this box is the entire screen so it puts in additional boxes/margins. So it might also be necessary to separate out a content html page from a layout template.

But I might have missed a ton of other points with my shallow understanding of html and css. I have never really written any html by myself.

**Comment by fonsp** [comment]
Hi, thanks for the feedback!

> Manually removing the <link rel="stylesheet" ...> and <style> tags in the header did not seem to do anything. So it seems that a ton of the styling is done in the body of the html document.

This is false, there is no inline styling. Try it again? Or perhaps you meant the cell inputs? These are snapshots of the CodeMirror-generated HTML, we probably want to do something more flexible. (Would fix some responsive layout issues)

> Another problem might be, that the site generator wraps the html document into a box and the html document assumes this box is the entire screen so it puts in additional boxes/margins. So it might also be necessary to separate out a content html page from a layout template.

A screenshot would be very useful to explain what you mean. Note that you can override Pluto's styling, including layout.

**Comment by FelixBenning** [comment]
@fonsp Oh, right - another stupid mistake for the day: used the comment shortcut `Ctrl+/` in VSCode and apparently the hugo extension messed things up, so it "commented it out" but didn't really.

So after fixing that I get the following results:

```
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.12.17/frontend/editor.css"
    type="text/css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.12.17/frontend/treeview.css"
    type="text/css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.12.17/frontend/hide-ui.css"
    type="text/css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/codemirror@5.58.1/lib/codemirror.min.css" type="text/css" />
```

everything commented out:

![grafik](https://user-images.githubusercontent.com/29106652/102807557-2b590180-43bf-11eb-9fa5-eeff0c190ffe.png)

Keeping the last sheet:
![grafik](https://user-images.githubusercontent.com/29106652/102807636-53e0fb80-43bf-11eb-9a9b-bc6928d885da.png)

Keeping the second last as well:
![grafik](https://user-images.githubusercontent.com/29106652/102807687-6bb87f80-43bf-11eb-80c5-86f41df28f94.png)
(also removed the entire header)

Keeping the second:
![grafik](https://user-images.githubusercontent.com/29106652/102807775-90acf280-43bf-11eb-8fd5-3dce50d40066.png)
(no change)
Keeping the first:
![grafik](https://user-images.githubusercontent.com/29106652/102807837-ad492a80-43bf-11eb-8aab-baf624ea7b8e.png)

**Comment by pankgeorg** [comment]
I think you need a dark theme of CodeMirror for that to look okey-ish.

**Comment by rikhuijzer** [comment]
Just bumped into this issue. See https://github.com/rikhuijzer/PlutoStaticHTML.jl.
