### ISSUE TITLE
Wrong parsing of ; in comments

### ISSUE THREAD

**Issue by oskarddfa** [fonsp/Pluto.jl#797]
```
a = 10 #;
```
doesn't render as expected. The `;` is parsed as if it was part of the code. This happens only if `;` is at the end of the line.

**Comment by fonsp** [comment]
Thanks! In fact, this is an issue with the julia REPL (Pluto uses the same function). Can you submit this to https://github.com/JuliaLang/julia instead?

**Comment by oskarddfa** [comment]
Oh didn't notice that! I will!

**Comment by fonsp** [comment]
No worries, thanks!
