### ISSUE TITLE
tab completion on struct shows extra entries

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#800]
Given this Pluto file:
```
### A Pluto.jl notebook ###
# v0.12.17

using Markdown
using InteractiveUtils

# ╔═╡ b841901e-44a1-11eb-1aa7-1d00819e6cc8
struct MyStruct
	a
	b
end

# ╔═╡ 8f2a0050-44a1-11eb-084a-ad96eff9dd3d
ms = MyStruct(1,2)

# ╔═╡ ff782230-44b3-11eb-2f75-65bae5df7205


# ╔═╡ Cell order:
# ╠═b841901e-44a1-11eb-1aa7-1d00819e6cc8
# ╠═8f2a0050-44a1-11eb-084a-ad96eff9dd3d
# ╠═ff782230-44b3-11eb-2f75-65bae5df7205

```

Entering the text `ms.` into the third cell and pressing tab gives five choices: '`a`, `b`, (as expected), but also `macro`, `module`, and `mutable struct` (see image below).

![image](https://user-images.githubusercontent.com/6796478/102944923-e0ec8900-4481-11eb-9789-9d11f7fe6ecc.png)

**Comment by fonsp** [comment]
@aviatesk

**Comment by fonsp** [comment]
@aviatesk Does this also happen in Atom?
