### ISSUE TITLE
compile notebook to binary or app to minimise startup time

### ISSUE THREAD

**Issue by gszep** [fonsp/Pluto.jl#810]
Would this be possible using `PackageCompiler.jl`?
https://julialang.github.io/PackageCompiler.jl/dev/

**Comment by fonsp** [comment]
Yes, use the notebook file as a representative workload to generate a custom sysimage, then launch Pluto with that sysimage set for notebooks:
```julia
Pluto.run(sysimage="path/to/sysimage.so")
```
