### ISSUE TITLE
Latex code not appropriately displayed

### ISSUE THREAD

**Issue by likanzhan** [fonsp/Pluto.jl#817]
Suppose I intend to create a matrix with the `SymPy` package

- Load the package
```
using SymPy
```

- Create a matrix
```
Sym[1 2; 2 4]
```

- The obtained output is:
```
\text{\[\left[ \begin{array}{rr}1&2\\2&4\end{array}\right]\]}

```
- The intended output is something like this:

<img width="184" alt="matrix" src="https://user-images.githubusercontent.com/10531698/103431948-4d4e5180-4c13-11eb-9ddf-d74a1a76ebdf.png">

**Comment by DhruvaSambrani** [comment]
See #488, may be a duplicate

**Comment by likanzhan** [comment]
It works now. Thanks.
