### ISSUE TITLE
add pluto - pluto not found - Julia 1.5.3 macOS

### ISSUE THREAD

**Issue by bobfoster** [fonsp/Pluto.jl#819]
This kinda says it:

(@v1.5) pkg> add pluto
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * pluto (not found in project, manifest or registry)

**Comment by bobfoster** [comment]
Dumbest error ever. Capital P Pluto. Sorry.

**Comment by woshidama323** [comment]
> Dumbest error ever. Capital P Pluto. Sorry.

Same mistake 😂
