### ISSUE TITLE
Cannot copy from code cells in static export html

### ISSUE THREAD

**Issue by klaff** [fonsp/Pluto.jl#823]
For example see https://klaff.github.io/friction_state_machine.jl.html.

Text from Markdown cells may be selected and copied, but attempting to select code from a code cell results in the display of an icon (similar to 🚫) indicating a prohibited action. Copying code should be allowed.

**Comment by fonsp** [comment]
I am working on the new (automatic) HTML export right now, it will be done this month! 

https://github.com/fonsp/pluto-static-render-test

**Comment by fonsp** [comment]
Fixed in the upcoming release!
