### ISSUE TITLE
"Run all modified" button / keyboard shortcut

### ISSUE THREAD

**Issue by kolia** [fonsp/Pluto.jl#83]
"Run all modified" would be the fastest way to get the code in sync with the outputs, without having to re-run all cells.

(If keyboard shortcuts will be customizable, the choice of shortcut doesn't matter, but I suspect I would use the "run all modified" action all the time, instead of running individual cells, and only use "run all" if it looks like execution is in an inconsistent state.)

**Comment by fonsp** [comment]
Yep! I think that this should actually replace the "run all" button - or the button can be "synchronise" if there are changed cells, and "restart all" otherwise.

**Comment by kolia** [comment]
Per #89, it would be good to make sure that "Run all modified" considers global variables that have been updated asynchronously as having been modified.

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/81125066-62b19580-8f37-11ea-9f93-6ac155364222.png)

and

![image](https://user-images.githubusercontent.com/6933510/81125081-7230de80-8f37-11ea-857d-54e633d8e104.png)
