### ISSUE TITLE
Popup docs don't work for some symbols

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#832]
For example, typing `?+=` into a cell shows help for `+`, and not for `+=`. Typing `?:`, surprisingly, gives help for `Any` instead of `:`. Julia REPL is correct in these cases, so looks like the issue is Pluto-specific.

**Comment by fonsp** [comment]
Try typing this directly in the Live Docs search bar

**Comment by aplavin** [comment]
First, I didn't know about docs search bar at all! Now I see that the header is "editable".
But typing `+=` there still gives me docs for `+`, and typing `:` - for `Any`. Something else I miss there? Screenshots:
![image](https://user-images.githubusercontent.com/687995/104246424-0532f880-5477-11eb-89e6-ad579c106d4e.png)
![image](https://user-images.githubusercontent.com/687995/104246436-0d8b3380-5477-11eb-9f31-57b21493f5fb.png)
Pluto 0.12.18 if that's important.

**Comment by aplavin** [comment]
Also, typing some fancy unicode symbol there doesn't show any help at all. In contrast, regular julia REPL prints e.g. `"⇒" can be typed by \Rightarrow<tab>`. So every time one wonders how to type something outside of ASCII he needs to open a separate REPL.
