### ISSUE TITLE
Edit or remove default header and footer in exported static PDF

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#837]
Currently, by default, I am getting theese headers and footers by default:
Header:
![image](https://user-images.githubusercontent.com/61620837/104185308-14815a00-5415-11eb-85ea-44b1e74bdee6.png)
Footer:
![image](https://user-images.githubusercontent.com/61620837/104185166-e3088e80-5414-11eb-9be3-8bf38d79f246.png)

Is it possible to customize or remove these? I want to use a notebook as a certificate generator, potentially for a real customer. As the header and footer do a lot to ruin any professional look, having them there is not really an option. Manual removal is possible, but that seems harder than things should be.

PS. The notebook rocks. Using conditionals and PlutoUI really makes me capable of creating some nice documents without any HTML knowledge at all <3

**Comment by fonsp** [comment]
Hey! Take a look at 
https://superuser.com/a/1418824
or
https://docs.evergreen-ils.org/reorg/3.1/serials/_turning_off_print_headers_and_footers_in_firefox.html
