### ISSUE TITLE
Add instructions to welcome text

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#84]
I suggest adding the instruction to call `Pluto.run(1234)` to the welcome text when the package is loaded.

Alternatively, could that be run automatically just by loading the package?

**Comment by fonsp** [comment]
I will implement the first suggestion - thanks!

The second one won't work - calling `using Pluto` only executes `Pluto.jl` if the package is not already loaded/cached (that's why you don't always see the welcome message), so this would lead to unpredictable behaviour.

**Comment by fonsp** [comment]
```
┌ Info:
│     Welcome to Pluto v0.6.4 🎈
│     Start a notebook server using:
│
│   julia> Pluto.run(1234)
│
│     Have a look at the FAQ:
│     https://github.com/fonsp/Pluto.jl/wiki
└
```
