### ISSUE TITLE
Feature request: Open URL from terminal

### ISSUE THREAD

**Issue by yuhan0** [fonsp/Pluto.jl#840]
Sometimes I run into a situation where the browser tab(s) running Pluto are closed, and the original message in the terminal has been lost to debugging / output messages:
```
Opening http://localhost:1234/?secret=******** in your default browser... ~ have fun!

Press Ctrl+C in this terminal to stop Pluto

... 
100s of lines of output
...
```

Recovering the URL from the browser history is a hassle because there are many similar URLs with different "secret" keys in the history.

It would be great if some keypress (Enter/ Ctrl-Enter?) in the terminal automatically opens the URL in the browser, the same way as it does during initial startup.

**Comment by fonsp** [comment]
You can just open `localhost:1234` again without a secret, because your browser is already authenticated.

**Comment by fonsp** [comment]
I think reopening closed tabs is a productivity feature that should be implemented by your browser, not by us
