### ISSUE TITLE
Release 0.12.19 with backported updates

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#845]
I don't know how to git, so I need help with the following:

1. Fork off https://github.com/fonsp/Pluto.jl/tree/v0.12.18 to create a new `release-0.12.19` branch
2. Merge/rebase these commits onto the 0.12.19 branch:
    - https://github.com/fonsp/Pluto.jl/pull/842
    - https://github.com/fonsp/Pluto.jl/pull/843
    - https://github.com/fonsp/Pluto.jl/commit/6b6a1fd73ac349e9039b84df20ae5909183b4f91

More info here: https://gist.github.com/fonsp/6676f64b81ba10b756c1219c09e8a68b

**Comment by pankgeorg** [comment]
Added https://github.com/fonsp/Pluto.jl/pull/847
Take a look at this one
