### ISSUE TITLE
Command-C doesn't do anything?

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#85]
The instructions say "Press Command+C to stop Pluto" but that key combination doesn't seem to have any effect either in the terminal window or in the browser.d

**Comment by fonsp** [comment]
It should be in the terminal - HTTP.jl is strange and sometimes it takes a few times before it closes. What OS and Julia version do you have?

**Comment by fonsp** [comment]
In Julia, pressing `Ctrl+C` **five times within one second** will always shut down the process - does that work for you?

**Comment by dpsanders** [comment]
So it turns out that `Ctrl-C` works, but `Command-C`, which is what is suggested in the text, does not. I guess it's just a typo?

**Comment by dpsanders** [comment]
And the text should maybe say that `Ctrl-C` needs to be done from the terminal window (as opposed to from within the Pluto web session). Thanks!

**Comment by fonsp** [comment]
Aha! I wrongly assumed that `Ctrl` is just replaced by `Command` on MacOS - I'll fix it.

Are there any other shortcuts on the web interface that should be different on MacOS? (`F1` or `Ctrl+Shift+?` gives the list)
