### ISSUE TITLE
Weird output from a mix of MathJax, Markdown and PlutoUI

### ISSUE THREAD

**Issue by schneiderfelipe** [fonsp/Pluto.jl#856]
Is the following expected? It looks like a bug to me. 🙈

![Screenshot from 2021-01-16 14-05-33](https://user-images.githubusercontent.com/37125/104818081-0f9d1b80-5804-11eb-8918-8ce4652d7bba.png)

(EDIT: I was expecting a Markdown list with a single item, namely a slider preceded by some inline math.)
The slider doesn't get rendered, and I would expect `$...$` to produce inline math. Seeing display mode here is surprising to me.

**Comment by pankgeorg** [comment]
It's not a bug - it's a feature of the Markdown interpolation rules, that are specific to julia markdown, I think.
The single `$..$` are something else - you want the double ticks ` `` `.

![image](https://user-images.githubusercontent.com/8681967/104820816-1e092880-5840-11eb-87b9-51d955392120.png)

```
md"""
- ``\alpha``: $(@bind a Slider(1:100))
"""
```

**Comment by schneiderfelipe** [comment]
> It's not a bug - it's a feature of the Markdown interpolation rules, that are specific to julia markdown, I think.
> The single `$..$` are something else - you want the double ticks `` `` ``.
> 
> ![image](https://user-images.githubusercontent.com/8681967/104820816-1e092880-5840-11eb-87b9-51d955392120.png)
> 
> ```
> md"""
> - ``\alpha``: $(@bind a Slider(1:100))
> """
> ```
> 
> (And it's subject to change I think)

Thanks for the explanation and the example, @pankgeorg. I'm closing this as the issue is solved.
