### ISSUE TITLE
Catlab.jl hangs possibly due to display bug

### ISSUE THREAD

**Issue by epatters** [fonsp/Pluto.jl#860]
Thanks for this innovative project! I am having trouble using Pluto with [Catlab.jl](https://github.com/AlgebraicJulia/Catlab.jl). For example, when I run this notebook:

```julia
### A Pluto.jl notebook ###
# v0.12.18

using Markdown
using InteractiveUtils

# ╔═╡ da073400-59d8-11eb-3607-d37ed4ee0515
using Catlab.CategoricalAlgebra, Catlab.Graphs

# ╔═╡ 6f180472-59d9-11eb-2681-bb1875b68611
begin
	g = Graph(4)
	add_edges!(g, [1,2,3], [2,3,4])
	g
end

# ╔═╡ 9b24eb0c-59d9-11eb-1746-bfca92fb55ce
coproduct(g, g)

# ╔═╡ Cell order:
# ╠═da073400-59d8-11eb-3607-d37ed4ee0515
# ╠═6f180472-59d9-11eb-2681-bb1875b68611
# ╠═9b24eb0c-59d9-11eb-1746-bfca92fb55ce
```

the first two cells execute successfully and then the last cell seems to hang: I kill it after a minute or two, but it should take at most a few seconds, even accounting for JIT compilation.

Catlab uses a fair amount of metaprogramming, specifically `@generated` functions, behind the scenes. Perhaps this interacting badly with Pluto?

**Comment by epatters** [comment]
Update: When I replace the cell

```julia
# ╔═╡ 9b24eb0c-59d9-11eb-1746-bfca92fb55ce
coproduct(g, g)
```

with

```julia
# ╔═╡ 9b24eb0c-59d9-11eb-1746-bfca92fb55ce
begin
    coproduct(g, g)
    "Computed coproduct"
end
```

the problem goes away. So my revised guess is that there is a bug in the Pluto's display that is causing the hang.

**Comment by fonsp** [comment]
What is the output supposed to look like? Can you run it in Jupyter/VSCode?
