### ISSUE TITLE
Pluto.run(notebook=path) does not open browser in Windows 10

### ISSUE THREAD

**Issue by gszep** [fonsp/Pluto.jl#862]
Has something to do with the `&` character?
![Screenshot from 2021-01-19 12-51-18](https://user-images.githubusercontent.com/17977117/105166194-82b1d500-5b17-11eb-8ac6-80e21acf9414.png)

**Comment by pankgeorg** [comment]
Can you provide some more information?
Windows version?
Are you using WSL(2)?
How are you running pluto?

**Comment by gszep** [comment]
Not using WSL or anything fance. Installed Julia under the default path given by the binary installer. Running julia script from command prompt
```
julia run.jl
```
where `run.jl` contains
```
using Pluto
Pluto.run(notebook="notebook.jl")
```
This is a screenshot from a collaborator's machine, I do not have access to a windows machine so can follow up in our next meeting

**Comment by pankgeorg** [comment]
Can you try to do `Pluto.run()` without a link to the notebook file and open Pluto from the GUI?
I think you have an issue with Window Paths but let's see if the normal case works

**Comment by gszep** [comment]
yeah me too. a classic where windows parses `\\` instead of `/`. will probably report back on this next week
