### ISSUE TITLE
Blank screen on fresh install

### ISSUE THREAD

**Issue by ranjanan** [fonsp/Pluto.jl#87]
Hi, this looks like a great package. However, when I install this, do `run` and then open a sample notebook. I seem to get a blank screen. When I open my firefox console, I find the following error too. 

 
![pluto](https://user-images.githubusercontent.com/9101377/79503914-f7436a80-7fff-11ea-9118-d6780c23b663.png)

Let me know what additional debugging steps I should do or if you need more information. I'm on Julia 1.4 with Pluto 0.7.3

**Comment by fonsp** [comment]
Thanks for sharing the dev console! I'll look into it :)

**Comment by fonsp** [comment]
Whoops it's broken for me too on FireFox - I will try to fix this as soon as possible!

**Comment by fonsp** [comment]
Got it! 🐛 It will be fixed in `0.7.4`, you can update in about 30 minutes.

Sorry for the trouble, and thanks for letting me know!

**Comment by fonsp** [comment]
You also seem to have Firefox version <= 68, which caused a second issue that is hopefully also fixed, but I don't have an old version of Firefox to test it on.

**Comment by ranjanan** [comment]
Awesome, thank you for your prompt response, I’ll check in a bit!

**Comment by fonsp** [comment]
The `0.7.4` update is live 👍

**Comment by ranjanan** [comment]
It works now, thanks!
