### ISSUE TITLE
Give better error message when two packages export the same function

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#890]
Loading two packages that export a function with the same name gives a "not defined" error message in Pluto.
Only in the terminal is the warning shown that they export the same function name and it should be qualified.

**Comment by fonsp** [comment]
Do you have an example for us to test?

**Comment by dpsanders** [comment]
The actual example is IntervalRootFinding.jl and IntervalConstraintProgramming.jl, which both (unfortunately) export `Contractor`.  But ICP takes a while to load, so maybe not the best example.

**Comment by fonsp** [comment]
Fixed by #1957 !

![Schermafbeelding 2022-04-22 om 14 05 56](https://user-images.githubusercontent.com/6933510/164711041-166c8d85-9927-4bbb-873a-6ed2e22d86c2.png)
