### ISSUE TITLE
Truncate long strings

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#892]
_This is a "Good first issue", but a relatively difficult one._

If you have a cell that outputs a long `String`, e.g.:

```julia
repeat('a', 100_000)
```

Then the entire string will be displayed in the browser. This has two problems:
1. The entire string is sent from the pluto server to the client, in cloud setups this can be too much data to download.
2. The page becomes slow

Therefore, we want to **truncate** the string to a maximum number of characters (with a button to show the rest). Because of 1., this truncation needs to happen in the backend.

Suggestions to look into:
- How does Pluto use a custom display for arrays?
- Exactly how are strings displayed right now?
- How does #638 work?

I am not sure whether we only want to truncate `String`s, or any `text/plain` output.

**Comment by vladflore** [comment]
Hey @fonsp ,

I would like to work on this next!

Could you visually depict what would you want to see for very long strings ?
If visually not possible, then textual should be fine too.

Some questions:
What's the accepted max length of such an output?
Where should the cut happen inside a long text, exactly after X chars, hard-cut, or at the first white-space before reaching the limit, or...?
E.g. cutting after 6 chars:
"This i **|** s a long text."
"This **|** is a long text."

Cheers,
Vlad

**Comment by fonsp** [comment]
Hey @vladflore !

I am not sure about these design choices, I have not thought about it yet. I suggest to just get started and see what is possible! Try to come up with real-life use cases where long strings would come up, and iterate your design with those in mind. Like your last PR, screenshots are really helpful!

Also note that you could separate some of these design problems into later PRs. For example, just the ability to lazy load long strings, without changing the current line-break-behaviour, would be a great addition!

**Comment by fonsp** [comment]
Julia 1.7 does this automatically!

![image](https://user-images.githubusercontent.com/6933510/144336933-84912146-1566-4ff0-82e7-d8fa680a6f05.png)
