### ISSUE TITLE
Built-in array viewer for `Set`

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#893]
For `AbstractArray`, `AbstractDict`, tuples, and more, we use Pluto's built-in interactive tree viewer:

![image](https://user-images.githubusercontent.com/6933510/106891759-7323b600-66eb-11eb-80d4-b3a5db9cc44f.png)

We should also use it for `Set`:

![image](https://user-images.githubusercontent.com/6933510/106891959-b54cf780-66eb-11eb-96ea-da63f62a5ac5.png)

**Comment by vladflore** [comment]
Hey @fonsp ,

I'd like to have a got at this (I've already worked a bit on it and managed to get some results) :).

P.S. beginner here, Julia, Pluto and OS contributing so please bear with me :)

Best,
Vlad
