### ISSUE TITLE
Plots are very tiny in Pluto >= 0.12.17

### ISSUE THREAD

**Issue by Guillawme** [fonsp/Pluto.jl#896]
Hello,

I noticed that the same notebook run with different versions of Pluto gives different plot sizes. See screenshots below:

<img width="1392" alt="Screen Shot 2021-02-05 at 11 54 08" src="https://user-images.githubusercontent.com/9656546/107029164-e3474000-67ae-11eb-8a97-a1157158ca55.png">

<img width="1392" alt="Screen Shot 2021-02-05 at 12 08 51" src="https://user-images.githubusercontent.com/9656546/107029192-ed693e80-67ae-11eb-86cd-acf2bc569be1.png">

The smaller plot size is completely unreadable without having to use the browser's zoom functionality. Trying to adjust the plot size with the `plot()` function is not a good solution, because it will only adjust the height and width of the figure but will leave a tiny line width, symbol size, font size and legend size.

I used a minimal environment sufficient to run this notebook, defined as:

```toml
[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Pluto = "= 0.12.16"
```

By adjusting the `compat` entry, updating the environment, restarting Julia to get a fresh session and rerunning the notebook, I figured out that the Pluto version that introduced this problem is 0.12.17. The plots look normal with Pluto 0.12.16 and earlier versions, but tiny with Pluto 0.12.17 and newer versions.

I noticed that a bunch of other packages got reinstalled when downgrading from Pluto 0.12.17 to 0.12.16 (see log below), so maybe it's not a problem within Pluto but rather the removal of one of these packages that could cause these tiny plots?

```
Updating `~/github/julia-curve-fitting/Project.toml`
  [c3e4b0f8] ↓ Pluto v0.12.17 ⇒ v0.12.16
Updating `~/github/julia-curve-fitting/Manifest.toml`
  [83423d85] + Cairo_jll v1.16.0+6
  [2e619515] + Expat_jll v2.2.7+6
  [a3f928ae] + Fontconfig_jll v2.13.1+14
  [0656b61e] + GLFW_jll v3.3.2+1
  [28b8d3ca] ↑ GR v0.49.1 ⇒ v0.53.0
  [d2c73de3] + GR_jll v0.53.0+0
  [78b55507] + Gettext_jll v0.20.1+7
  [7746bdde] + Glib_jll v2.59.0+4
  [cd3eb016] ↓ HTTP v0.9.0 ⇒ v0.8.19
  [aacddb02] + JpegTurbo_jll v2.0.1+3
  [dd4b983a] + LZO_jll v2.10.0+3
  [e9f186c6] + Libffi_jll v3.2.1+4
  [d4300ac3] + Libgcrypt_jll v1.8.5+4
  [7e76a0d4] + Libglvnd_jll v1.3.0+3
  [7add5ba3] + Libgpg_error_jll v1.36.0+3
  [94ce4f54] + Libiconv_jll v1.16.0+7
  [4b2f31a3] + Libmount_jll v2.34.0+3
  [89763e89] + Libtiff_jll v4.1.0+2
  [38a345b3] + Libuuid_jll v2.34.0+7
  [2f80f16e] + PCRE_jll v8.42.0+4
  [30392449] + Pixman_jll v0.40.0+0
  [c3e4b0f8] ↓ Pluto v0.12.17 ⇒ v0.12.16
  [ede63266] + Qt_jll v5.15.2+1
  [5c2747f8] - URIs v1.2.0
  [a2964d1f] + Wayland_jll v1.17.0+4
  [2381bf8a] + Wayland_protocols_jll v1.18.0+4
  [02c8fc9c] + XML2_jll v2.9.10+3
  [aed1982a] + XSLT_jll v1.1.33+4
  [4f6342f7] + Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] + Xorg_libXau_jll v1.0.9+4
  [935fb764] + Xorg_libXcursor_jll v1.2.0+4
  [a3789734] + Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] + Xorg_libXext_jll v1.3.4+4
  [d091e8ba] + Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] + Xorg_libXi_jll v1.7.10+4
  [d1454406] + Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] + Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] + Xorg_libXrender_jll v0.9.10+4
  [14d82f49] + Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] + Xorg_libxcb_jll v1.13.0+3
  [cc61e674] + Xorg_libxkbfile_jll v1.1.0+4
  [12413925] + Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] + Xorg_xcb_util_jll v0.4.0+1
  [975044d2] + Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] + Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] + Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] + Xorg_xkbcomp_jll v1.4.2+4
  [33bec58e] + Xorg_xkeyboard_config_jll v2.27.0+4
  [c5fb5394] + Xorg_xtrans_jll v1.4.0+3
  [3161d3a3] + Zstd_jll v1.4.8+0
  [b53b4c65] + libpng_jll v1.6.37+6
  [d8fb68d0] + xkbcommon_jll v0.9.1+5
```

This was all done with Julia 1.5.3 on macOS 10.15.7.

I attached the notebook and data file that should be sufficient to replicate these observations (I had to append .txt to the file names because GitHub would not upload a .jl or .csv file; simply remove the extra .txt and it should work).

[curve-fitting.jl.txt](https://github.com/fonsp/Pluto.jl/files/5932280/curve-fitting.jl.txt)

[dataset_003.csv.txt](https://github.com/fonsp/Pluto.jl/files/5932282/dataset_003.csv.txt)

**Comment by mthelm85** [comment]
I've experienced the same, but only with the GR backend. If I call `plotly()`, it works fine.

**Comment by pankgeorg** [comment]
Try to add `dpi=460` as a keyword argument - can you tell us if that works/

**Comment by Guillawme** [comment]
Thank you for pointing out this issue in the Plots repository (I did a quick search before posting here, but did not find it).

I will try setting `;dpi=460` when I have a moment this coming week, and I will let you know what it does (so far, I have simply pinned the Pluto version to 0.12.16 in my notebook's environment).

**Comment by Guillawme** [comment]
So, I just had time to try it now. I removed the pin to Pluto version 0.12.16 and updated the environment, but it turned out it also upgraded GR to 0.54.0 and HTTP to 0.9.2, and the problem just went away. So, I am closing this issue.

**Comment by pankgeorg** [comment]
Great! Happy to help!

**Comment by adannenberg** [comment]
the issue appears to be back.  i'm using pluto on a linux box and have tiny graphs until i add the ;dpi = 460 argument to my plot commands.  here's what i have (along with julia 1.6.1)

     Status `~/.julia/environments/v1.6/Project.toml`
  [c52e3926] Atom v0.12.32
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.1.1
  [31c24e10] Distributions v0.25.2
  [e5e0dc1b] Juno v0.8.4
  [442fdcdd] Measures v0.3.1
  [429524aa] Optim v1.3.0
  [a03496cd] PlotlyBase v0.5.3
  [f0f68f2c] PlotlyJS v0.14.1
  [91a5bcdd] Plots v1.15.2
  [c3e4b0f8] Pluto v0.14.7
  [7f904dfe] PlutoUI v0.7.9
  [d330b81b] PyPlot v2.9.0
  [ade2ca70] Dates
  [10745b16] Statistics

**Comment by pankgeorg** [comment]
Hey! take a look here: #1207
