### ISSUE TITLE
Export html API

### ISSUE THREAD

**Issue by yuehhua** [fonsp/Pluto.jl#899]
Thank you so much for this great reactive notebook.

After I use it, I usually export my notebook as a html file for a fixed version. That way I can present my work as a report format.
Besides exporting html file manually, is there any way to export a html file automatically? A html file is generated based on a specified notebook file and a Pluto command can be used to export it automatically.

Thank you

**Comment by pankgeorg** [comment]
There is something work in progress, stay tuned!!!
