### ISSUE TITLE
File I/O

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#9]
One of the reasons to write a notebook system from scratch is to change the default file format. Our wishes are:
- Output is saved separately, optionally.
- The file has nothing but legal Julia syntax.
- The file must be readable in plain form.
- Notebooks are git merge-friendly. This includes:
  - Minimal changes in code are minimal diffs.
  - A merge conflict where two people added a cell can be merged automatically.
- The file should not change when you:
  - Open the file, run cells, save and close the file.
- If your notebook runs without errors on "Run all", it should run when you do `julia mynotebook.jl`
  - You should be able to `include("./yournotebook.jl")` in another script/notebook, and use the globally defined variables and functions.
  - This creates a problem with arbitrary cell order.
- Cells that are disconnected dependency-wise, should keep their order.
- Any legal Julia script can be interpreted as a Pluto notebook.

**Comment by malyvsen** [comment]
My suggestion for saving pure Julia files:
Before each cell there would be a comment with its UUID, and at the beginning/end of the file, together with a "made with Pluto.jl" notice, we'd include the UUIDs in notebook order, each in its own line.
This is Git merge-friendly: if one person added a cell and another reordered some cells, they can still do an automatic merge

**Comment by fonsp** [comment]
We now have file I/O, but cells are not yet saved in execution order. For this, we first need to implement "run all" functionality.

**Comment by fonsp** [comment]
Should Pluto have a built-in file manager? I would say no.

**Comment by malyvsen** [comment]
I think a compromise is best - just launch the default file explorer to "save as"/load notebooks, with "save" ovewriting the current file. New notebooks could start up a new instance of Pluto if that's possible?

**Comment by fonsp** [comment]
Oh true! We can use the browser implementation for opening and saving :)

**Comment by malyvsen** [comment]
Perhaps serve_notebook could start up a container of sorts, optionally running in parallel to the main process? I think this would make for elegant management of multiple notebooks

**Comment by fonsp** [comment]
I think that different notebooks should be able to use the same port (so that you only need to open one port for remote access), so starting a new Pluto instance with a new HTTP server doesn't work - the HTTP server needs to handle multiple notebooks. 

We could use the Notebook struct as this container, containing a reference to its modulemanager and update channel.
