### ISSUE TITLE
small interactive table

### ISSUE THREAD

**Issue by Egidiusz** [fonsp/Pluto.jl#900]
I was wondering if it is possible to create a small interactive table using PlutoUI.

This
```
using DataFrames, PlutoUI
rows = 10
df = DataFrame(dag = fill(DateField(), rows), fruit = fill(Select(["🍎", "🍌"]), rows), stuks = fill(NumberField(0:10), rows))
```
returns something like what I'm looking for, but it doesn't let you access the entered values. `df.stuks[1]` just returns the widget, and not the value the user has entered. Is there a way to create something that looks similar, i.e. an array of widgets, while binding variables to the widgets?
![df](https://user-images.githubusercontent.com/78638722/107113275-db8ea680-6855-11eb-8c85-a46c793d824f.PNG)

**Comment by fonsp** [comment]
Hoi @Egidiusz !

This is possible!

You will have a better chance of getting help with coding this if you post your question to the Pluto zulip chat:
https://gist.github.com/fonsp/db7d00fd3fe5bc0b379b4af9ec6674b6
