### ISSUE TITLE
Give information about duplicate definitions

### ISSUE THREAD

**Issue by dpsanders** [fonsp/Pluto.jl#903]
Pluto errors when there are duplicate definitions, but they are hard to find in the file.
It would be useful to have e.g. clickable links to the cells where the definitions are in some kind of floating list.

Or e.g. have an option to remove all the other duplicate definitions except for the current cell.

**Comment by fonsp** [comment]
Hi David!

Thank you, but can you submit feature requests to our built in suggestion box instead? https://github.com/fonsp/Pluto.jl/issues/182

This helps to keep me sane 💆
