### ISSUE TITLE
failed to resolve notebook boot environment

### ISSUE THREAD

**Issue by floswald** [fonsp/Pluto.jl#906]
hi there
Im having issues with students being unable to run [this notebook](https://github.com/floswald/NumericalMethods/blob/master/homework/homework1/discrete_lockdown.jl). I tried to keep to the structure in your MIT course notebooks, but it seems there is something failing when they want to create the new environment. Did I mess up the cell order?  Here is the console output of the student in question:

```
Press Ctrl+C in this terminal to stop Pluto
┌ Error: Failed to resolve notebook boot environment
│   exception =
│    Unsatisfiable requirements detected for package Artifacts [56f22d72]:
│     Artifacts [56f22d72] log:
│     ├─Artifacts [56f22d72] has no known versions!
│     └─restricted to versions 1.3.0 by an explicit requirement — no versions left
│    Stacktrace:
│     [1] check_constraints(::Pkg.Resolve.Graph) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Resolve/graphtype.jl:935
```

thanks for any help!

**Comment by fonsp** [comment]
This issue is already fixed, they need to update Pluto.
