### ISSUE TITLE
Autocompletionsuggestions of Filepicker blocks Return

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#91]
This is a minor one but probably easy to fix.

If the autocompletions of filepicker are shown you can not load a notebook by pressing the Return-key, since it selects the current autocompletion selection instead of running the notebook, even if the selected autocompletion is already the same as the content of path input widget.

An easy solution would be: when return is pressed, check if the selected autocompletion path is the same as the current content of the path-lineedit and load the notebook in that case otherwise update the content of the lineedit.

**Comment by fonsp** [comment]
Will do! Out of curiosity: does this only occur in the "Open notebook" file picker (and not the rename file picker) when trying to open a file _that is the suffix of another file_? Like `/a/b.jl` if `/a/b.jl.backup1` also exists? For me that's the only situation where this happens.

**Comment by karlwessel** [comment]
It happens in both file pickers and only for the case you describe, yes.

**Comment by karlwessel** [comment]
Hmm, this still doesn't seem to work with Pluto 0.7.9 :(

**Comment by fonsp** [comment]
it's fixed for me. Can you clear cache, try again, and send me your browser and os version?

A MWE of two filenames and a query to type in would also be helpful 🐭

**Comment by karlwessel** [comment]
It still occurs with cache cleared for Firefox 75.0 and Chromium 81.0.4044.129 on Arch Linux.

The problem occurs for example when there are two files `a.jl` and `a.jl.backup` in my home directory. When I enter `~/a.` in the file picker and then select the first available option `~/a.jl` from the suggestions by pressing `Return` and than try to open the file with another press to `Return`. The last press to `Return` just selects again the same file from the suggested files instead of opening the file.

**Comment by fonsp** [comment]
Thanks for the detailed description, it should be fixed now.

**Comment by karlwessel** [comment]
Now it works, thank you!
