### ISSUE TITLE
[FR] Make @bind Bind to non global variables

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/Pluto.jl#910]
Since only global variables can be bound in a Bond, one cannot compose previously defined UI elements into more complex elements.

While I am not sure about how exactly Bonds work, I don't believe this is easy.

This also has associated issues in PlutoUI -
fonsp/PlutoUI.jl#60 and fonsp/PlutoUI.jl#17 which could be greatly simplified if this was done.

**Comment by fonsp** [comment]
Can you post this feature request to our suggestion box instead? https://github.com/fonsp/Pluto.jl/issues/182
