### ISSUE TITLE
SVG output from Plots can cause browser tab to consume large amounts of memory

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#911]
If you try to plot thousands of points, the browser tab can accumulate massive amounts of memory for each plot, using the default SVG output. This can lead to a poor experience for people trying to naively plot data.

One idea could be to try to globally set the default for Plots to PNG instead of SVG. I don't know if that's possible.

Another is that Pluto could warn when evaluating a cell leads to massive allocations on the browser side and could slow down the notebook; and/or notice that specifically a large svg is being returned and Pluto could suggest the format be changed to raster for better performance.

**Comment by fonsp** [comment]
@tbreloff What is your experience with this subject? Can we ask Plots.jl whether svg or png is preferred for a particular plot?

**Comment by sosiristseng** [comment]
Does `Plots.gr(fmt=:png)` prior to plotting work?
