### ISSUE TITLE
Server shutdown during save can corrupt file

### ISSUE THREAD

**Issue by strangehurst** [fonsp/Pluto.jl#913]
I got this:
The file /frank/nfs4/Jules/hw9/hw9.jl could not be loaded. Please report this error!

BoundsError: attempt to access String
  at index [0]
Stacktrace:
 [1] prevind(::String, ::Int64, ::Int64) at ./strings/basic.jl:482
...
[nb_load_error.txt](https://github.com/fonsp/Pluto.jl/files/5973676/nb_load_error.txt)

Am using Debian testing, and have Julia packages updated to latest.
This notebook was used yesterday without error. Today, after updates to OS/Julia, it fails to load.
The Untouched MIT Fall20 18S191 hw9.jl notebook loads. 

My hw9.jl [hw9.zip](https://github.com/fonsp/Pluto.jl/files/5973740/hw9.zip)

Pkg status [status.txt](https://github.com/fonsp/Pluto.jl/files/5973769/status.txt)

**Comment by fonsp** [comment]
It looks like the Pluto shut down while writing the file:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/6933510/108571072-a41d0100-730f-11eb-97be-63c4569ee04b.png">

**Comment by fonsp** [comment]
@strangehurst Here is the recovered file, in case you want to keep learning about snowball earth! [hw9_mostly_recovered.jl.zip](https://github.com/fonsp/Pluto.jl/files/6013574/hw9_mostly_recovered.jl.zip)

**Comment by strangehurst** [comment]
Thanks, I thought the root cause was likely a corrupted file. 
Hopefully this report helps improve diagnostics.
