### ISSUE TITLE
An unexpected cylic reference error when using kwargs

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#915]
The kwargs search for args first, then the global variables.

![image](https://user-images.githubusercontent.com/6257240/107840139-5556f080-6d7e-11eb-8975-4c1c30e0b327.png)

```julia
julia> x = 3
3

julia> function f(x; y=3x)
       return y
       end
f (generic function with 1 method)

julia> f(9)
27
```

So, the correct expression explore should detect no cyclic reference.

For testing:
```julia
begin
	using LinearAlgebra
	function f(x;
		y=LinearAlgebra.mul!(3, x)
	)
	end
end

x = LinearAlgebra.mul!(3, 4)
```

**Comment by fonsp** [comment]
This is because:
the first cell **defines** `LinearAlgebra` and **references** `x`. 
The second cell **defines** `x` and **references** `LinearAlgebra`.

The solution is to split the first cell in two.

**Comment by GiggleLiu** [comment]
> the first cell defines LinearAlgebra and references x.

This is not true, the first cell does not reference `x`. The `x` is an input argument.

**Comment by fonsp** [comment]
Aha! I didn't know about that syntax, thanks for correcting me and for the bug report!
