### ISSUE TITLE
Do not run all cells when opening notebook

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#92]
The title of the issue does not quite capture what I want, but is a prerequisite for it. Here is what I really want and the use-case for it:

It sometimes happens that I have a really convoluted exploratory notebook where not all cells depend on each other. It further happens that after loading that notebook, that I don't wan't to run all of it but only a certain cell, because I need only that cells output.

If I execute that cell after opening the notebook, would it be possible for Pluto to detect which other cells that cell depends on and only run those? Without having to run all cells once beforehand?

**Comment by fonsp** [comment]
Thanks for posting these issues!

You can disable auto-run by setting a flag before starting the server:
```julia
julia> using Pluto
julia> Pluto.CONFIG["PLUTO_RUN_NOTEBOOK_ON_LOAD"] = "false"
julia> Pluto.run(1234)
```
This should use `ENV` instead, (but I had some trouble getting the latest ENV variables from the worker processes) so this syntax might change at some point. You should then be able to set the `ENV` variable in your startup julia file to make it permanent.

**Comment by fonsp** [comment]
What you are suggesting is a creative solution, but it means implementing _downstream_ evaluation (and disabling _upstream_ evaluation?) during the first run - this would make the effect of clicking "run cell" ambiguous. 

Implementing auto-run (and adding an option to disable it) was very intentional. It means that the notebook is reactive right away, instead of all cells starting out in a limbo state of having synchronised code but not yet being part of the reactivity graph. 

I think the current solution is much more in line with the philosophy of the project - your notebook is a _descriptive_ program, not an imperative one.

**Comment by karlwessel** [comment]
I think I understand what you mean: I should consider a notebook as one whole reactive object which happens to be extendable incrementally cell-wise. It is not a collection of more or less separate cells. The latter is probably what Jupyter is there for.

With that in mind I can totally accept the coffee-time forced upon me when a notebook starts :-). 
And I think your proposal from issue #71 - to be able to enable and disable notebooks from Pluto's home screen - makes even more sense now and would underline the fact that a notebook is a whole thing. Being able to enable and load it off-screen would somewhat hide the current "Although you can see me, I'm not quite ready yet"-unresponsive-feeling when the notebook is loaded.

**Comment by Moelf** [comment]
update:
`Pluto.ENV_DEFAULTS["PLUTO_RUN_NOTEBOOK_ON_LOAD"] = "false"`

**Comment by fonsp** [comment]
The environment variable you mentioned is a 'hidden' feature, and it will be removed soon.

I am working on a solution that is much more friendly:
https://github.com/fonsp/Pluto.jl/issues/259#issuecomment-670097886

**Comment by libensvivit** [comment]
Pluto.CONFIG["PLUTO_RUN_NOTEBOOK_ON_LOAD"] = "false"
Pluto.ENV_DEFAULTS["PLUTO_RUN_NOTEBOOK_ON_LOAD"] = "false"

Neither of these works for me. what is the updated code? And please disable autorun by default, why is it enabled by the way what use does it have? It is just annoying!!

**Comment by teamclouday** [comment]
For the recent version, looks like the following works:  
```julia
Pluto.run(Pluto.Configuration.from_flat_kwargs(;run_notebook_on_load=false))
```
More options can be found here:  
https://github.com/fonsp/Pluto.jl/blob/def9d0e874aa0dd23394996b51b489947d13fd46/src/Configuration.jl#L235

**Comment by filchristou** [comment]
> For the recent version, looks like the following works:
> 
> `Pluto.run(Pluto.Configuration.from_flat_kwargs(;run_notebook_on_load=false))`

Doesn't work for me now in Julia 1.8.1 and Pluto v0.19.11
I agree that it's disturbing and that it should be easier to process a notebook before running it.

**Comment by teamclouday** [comment]
> Doesn't work for me now in Julia 1.8.1 and Pluto v0.19.11

Interesting, I just checked it again with Julia v1.7.0 and Pluto v0.19.9, and it still works for me.\
Did you run the line from terminal, replacing `Pluto.run()`?

**Comment by kevindirect** [comment]
I normally launch pluto from a shell alias: `plo='julia -e "using Pluto; Pluto.run()"'`
I tried running `julia -e "using Pluto; Pluto.run(Pluto.Configuration.from_flat_kwargs(;run_notebook_on_load=false))"`
I'll running it from the REPL manually to see if it makes a difference.

**Comment by teamclouday** [comment]
> Update: Running from the REPL gives the same behavior as `julia -e ...`

How about `using Pluto; Pluto.run(;run_notebook_on_load=false)`\
I looked at the code at: https://github.com/fonsp/Pluto.jl/blob/b9158e0bd84e3394829ae3391decddd9f0fe5be9/src/webserver/WebServer.jl#L59

So `run_notebook_on_load` option can be passed in like that

**Comment by kevindirect** [comment]
> How about `using Pluto; Pluto.run(;run_notebook_on_load=false)` I looked at the code at:
> 
> https://github.com/fonsp/Pluto.jl/blob/b9158e0bd84e3394829ae3391decddd9f0fe5be9/src/webserver/WebServer.jl#L59
> 
> So `run_notebook_on_load` option can be passed in like that

It didn't work, wonder why. I'm using Julia v1.8 and Pluto v0.19.9

**Comment by AlfredSAM** [comment]
> > How about `using Pluto; Pluto.run(;run_notebook_on_load=false)` I looked at the code at:
> > https://github.com/fonsp/Pluto.jl/blob/b9158e0bd84e3394829ae3391decddd9f0fe5be9/src/webserver/WebServer.jl#L59
> > 
> > So `run_notebook_on_load` option can be passed in like that
> 
> It didn't work, wonder why. I'm using Julia v1.8 and Pluto v0.19.9

Is there any update? It also didn't work for me. I am using Julia v1.8 and Pluto v0.19.12

**Comment by teamclouday** [comment]
Please follow https://github.com/fonsp/Pluto.jl/issues/259 for discussions of this feature.
