### ISSUE TITLE
Pluto.run(notebook = "test.jl") -> `&` is reserved

### ISSUE THREAD

**Issue by VEZY** [fonsp/Pluto.jl#936]
Hello, 

first thank you so much for this great tool ! 
I have an issue when I try to open a notebook from the command line in Pluto `0.12.20`, using *e.g.*:

```julia
Pluto.run(notebook = "test.jl")
```

It returns me an error that comes from powershell (I'm on Windows 10) saying that the ampersand character is reserved. Could we put the whole generated link after the `Start` between quotes on windows ? I tested it and it fixes the issue, this:

```
Start "http://localhost:1234/open?secret=53beBrQS&path=test.jl"
```

Instead of this:

```
Start http://localhost:1234/open?secret=53beBrQS&path=test.jl
```

The error is the following (in French):

```
Au caractère Ligne:1 : 49
+ Start http://localhost:1234/open?secret=53beBrQS&path=test.jl
+                                                 ~
Le caractère perluète n’est pas autorisé. L’opérateur & est réservé à une utilisation future. Placez un caractère perluète entre guillemets doubles ("&") pour que ce symbole soit considéré comme une chaîne.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Which would translate to:

```
At character line:1 : 49
+ Start http://localhost:1234/open?secret=53beBrQS&path=test.jl
+                                                 ~
The ampersand character is forbiden. The operator & is reserved to a future usage. Place an ampersand between double quotes ("&") if you want it to be considered a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

Here is my configuration:

- Julia 1.5.0
- Pluto 0.12.20
- Powershell 5.1.19041  revision 610.

**Comment by VEZY** [comment]
Sorry, just found out about  #862.

**Comment by VEZY** [comment]
#862 didn't fix the issue surprisingly. I don't know why but quotes are removed when the call is made by `Base.run()`. Adding one more set of single quotes between the double quotes seems to work though.

**Comment by KronosTheLate** [comment]
Sorry to highjack this issue, but where would I find documentation the keyword-argument `notebook`? Is there anything to say about it, other than to provide a string with the location of a notebook-script?

**Comment by VEZY** [comment]
> 
> 
> Sorry to highjack this issue, but where would I find documentation the keyword-argument `notebook`? Is there anything to say about it, other than to provide a string with the location of a notebook-script?

I personally found out about the `notebook` argument here in the issues when searching about something like it (as I assume you did). 
@fonsp is this documented somewhere ? Maybe it would be usefull to let people know in the doc of `Pluto.run()`?
