### ISSUE TITLE
`Pluto.Configuration` documentation

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/Pluto.jl#940]
Searching the documentation for `Pluto.run()` should document the `notebook` and `sysimage` kwarg, and possibly other kwargs I don't myself know of.

The current documentation says to look in the Pluto.Configuration module, but I could not find anything when scrolling through, and it is much too long and technical for me to be able to read through and understand it all.

**Comment by fonsp** [comment]
I don't want to include it in the documentation of `Pluto.run` to prevent an intimidating first experience. Feel free to open a PR to improve the documentation of `Pluto.Configuration`

**Comment by KronosTheLate** [comment]
>  Feel free to open a PR to improve the documentation of `Pluto.Configuration`

Well that is kind of the problem, right? _I_ don't know the details of the kwargs, because I can't find documentation. How can I then _write_ documentation?

**Comment by feanor12** [comment]
Would a pointer in the documentation of Pluto.run be ok?

Like:

`For further options see Pluto.Configuration `

I don't now what the best options for references in documentation is at the moment.
Can it be linked or do we need a line like `? Pluto.Configuration`

Also  `Pluto.ServerOptions` might be the better reference here.

**Comment by fonsp** [comment]
@feanor12 We already have that pointer

I already wrote documentation at the individual categories: https://github.com/fonsp/Pluto.jl/blob/main/src/Configuration.jl but I couldn't figure out how to combine those four docstrings into a single docstring for Pluto.Configuration without copy-pasting. But maybe we can just copy-paste

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/commit/b5b6cb03e9e438e3a5f31f62c86ca3e4c3ca2d89
