### ISSUE TITLE
Markdown / Latex / in-string expression parsing is extremely sensitive to spacing

### ISSUE THREAD

**Issue by jlewis91** [fonsp/Pluto.jl#945]
Thank you for this package, it is incredibly exciting and fun to use; it may be a little rough around the edges, but yet it is already fully functional. I keep on running into various little markdown / mathjax / in-string expression issues and wanted to flag this with a couple of reprex examples:

## Reprex:

```julia
a = 1
```

```julia
md" $(a) $ \epsilon $ $(a)"
```

<img width="401" alt="Screen Shot 2021-02-24 at 11 25 58" src="https://user-images.githubusercontent.com/4462211/108987133-39fbb780-7693-11eb-8807-63a070f54524.png">

```julia
md"$(a) $\epsilon$ $(a)"
```
<img width="650" alt="Screen Shot 2021-02-24 at 11 26 08" src="https://user-images.githubusercontent.com/4462211/108987094-310ae600-7693-11eb-9d0c-052327e1a8e8.png">

```julia
md" $(a) $\epsilon$ $(a)"
```
<img width="365" alt="Screen Shot 2021-02-24 at 11 26 29" src="https://user-images.githubusercontent.com/4462211/108987091-2ea88c00-7693-11eb-868f-79f753c81ec0.png">

**Comment by fonsp** [comment]
Markdown is part of Julia itself, take a look at the existing issues and considering opening a new issue at https://github.com/JuliaLang/julia/issues?q=is%3Aopen+is%3Aissue+label%3Amarkdown

**Comment by jlewis91** [comment]
@fonsp Thanks for the heads up here, hard to tell within Pluto how much of the heavy lifting takes place within the library and how much within the base language. Given Pluto's unique heavy use of base markdown, especially with combinations of markdown & latex & interpolation, I wouldn't be surprised if similar issues pop up now and again, given the mysterious rules by which Julia seems to parse these strings. I've developed a PR to the main repo that documents some of this behavior, just so the status quo is explicit:

https://github.com/JuliaLang/julia/pull/39817
