### ISSUE TITLE
import inside let block is global

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#949]
Confusingly, this code:
```julia
let
	x = 123
	import Dates
end
```

does not define a global `x`, but is **does** define a global `Dates`. Our ExpressionExplorer should detect this correctly.

**Comment by fonsp** [comment]
I added a test that should pass when this is fixed: https://github.com/fonsp/Pluto.jl/blob/54d90aae88c05988f6c29629e624ab8327ad0c83/test/ExpressionExplorer.jl#L322

**Comment by Pangoraw** [comment]
hey!
the same seems to be true for any scope like `for`, `while` and `try`/`catch`/`finally`:
```julia
module A
  let
    import Dates
  end
  @assert Dates.October == 10 # no problem
end

module B
  for i = 1:2
    import Dates
  end
  @assert Dates.October == 10 # no problem
end

module C
  try
    import Dates
  catch
  end
  @assert Dates.October == 10 # no problem
end

module D
  while true
    import Dates
    break
  end
  @assert Dates.October == 10 # no problem
end
```
Perhaps, we could just drop the condition in [ExpressionExplorer](https://github.com/fonsp/Pluto.jl/blob/main/src/analysis/ExpressionExplorer.jl#L596). However some imports can be conditional but it's hard to detect during the static analysis:
```julia
module E
  try
  catch
    import Dates # not executed since there are no error in the try block
  end
  @assert Dates.October == 10 # will fail: UndefVarError: Dates not defined
end
```

**Comment by fonsp** [comment]
@Pangoraw Good catch!

The conditional is not a problem. It's similar to:
```julia
if rand(Bool)
	x = 1
end
```

which turns out to not be a problem with our system.

**Comment by Pangoraw** [comment]
> Let's skip the scope check altogether for import and using?

Yes, I think the only problem would be if someone was to write a module declaration, but since the [module's content is not explored](https://github.com/fonsp/Pluto.jl/blob/main/src/analysis/ExpressionExplorer.jl#L613-L616), we are fine.

**Comment by fonsp** [comment]
Nice, add a test for `module A; import B; end` so we don’t miss it later.
