### ISSUE TITLE
Don't autoscroll on cell update

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#95]
Sorry, I will elaborate on this problem a bit more later when I have the time, but for now I want to record it here:

My browser automatically and rather nondeterministic scrolls/jumps away from the current position when cells are updated. I wonder if there is a case where this jumping is actually useful and if it would not be better if it just always stays where it is except when manually scrolling.

This is especially noticeable when using widgets that update large other cells.

**Comment by fonsp** [comment]
If you have time to write a MWE, could you also include two screenshots with the before and after scroll positions, and your browser version?

**Comment by karlwessel** [comment]
Here is an MWE anyway:
```
### A Pluto.jl notebook ###
# v0.7.6

using Markdown
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.peek, el) ? Base.peek(el) : missing
        el
    end
end
# ╔═╡ e0a3f982-8a1a-11ea-2d07-a3d53c9ba23f
function grabframe(relativeframepos)
	t = relativeframepos * 2 * π
	ω = 2π
	c = 4.
	frame = [sin(ω*t - √(x^2 + y^2)/300*c) for y in -200:399, x in -300:499]
	return Gray.(frame .^ 2)
end

# ╔═╡ 6b85dc6e-8a1b-11ea-09d5-172c70405b02
@bind x Slider(0:0.01:1)

# ╔═╡ 2f448160-8a1b-11ea-1181-f1fda429aa71
grabframe(x)

# ╔═╡ bbe7a79c-8a1a-11ea-2aa6-cd98feb2cb47
begin
	using Images
	using PlutoUI
end

# ╔═╡ Cell order:
# ╠═bbe7a79c-8a1a-11ea-2aa6-cd98feb2cb47
# ╠═e0a3f982-8a1a-11ea-2d07-a3d53c9ba23f
# ╠═2f448160-8a1b-11ea-1181-f1fda429aa71
# ╠═6b85dc6e-8a1b-11ea-09d5-172c70405b02
```
You might have to zoom in with your browser so that there actually is something to scroll.

When I scroll, so that I see the image and the slider nicely together, the browser scrolls away as soon as I change the slider the first time.

**Comment by fonsp** [comment]
Ooh thanks for that funky MWE

**Comment by karlwessel** [comment]
Thanks for fixing!
