### ISSUE TITLE
File drag&drop issues

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#950]
I thought it might be nice to have a central place for drag&drop TODOs:

- [ ] Video and audio mime types should also become a PlutoUI.LocalResource.
- [ ] I would definitely like small files to be embedded in the notebook file directly, be that base64 encoded or raw, inserted inside code or hidden somewhere else in the file. Alternatively, we come up with a different file type. We have to make sure that sharing the notebook means sharing a single file/folder.
- [ ] If a file type is not recognized, we should still upload it and make the variable name available as a variable.
- [ ] Deleting the last asset should delete the asset folder
- [ ] (Can you delete assets?)
- [ ] I don't like the "`let` block package import" hack -- we should generate nice code, with toplevel package imports

About the design: it still looks a bit messy and hacky, some ideas:
- [x] Use a sans font
- [ ] Don't show the drop handle on top of a cell, but between cells, at the place where it will go
<img width="571" alt="Schermafbeelding 2021-02-26 om 09 28 43" src="https://user-images.githubusercontent.com/6933510/109275788-7f47f280-7815-11eb-9d0e-fcf46ba36d3e.png">
- [ ] We could have dedicated UI to show the presence of an "asset", instead of referring to it by its filename string. We could also have a sidebar with all assets, instead of placing them inline.

**Comment by pankgeorg** [comment]
This looks like a nice idea for small data:
https://github.com/JuliaComputing/DataSets.jl/pull/15

**Comment by c42f** [comment]
Cool :)

I'm happy to answer any questions about DataSets.jl. I've been hoping we can have some nice Pluto integration at some stage, and this was one piece in the puzzle.

**Comment by fonsp** [comment]
"Fixed" by https://github.com/fonsp/Pluto.jl/pull/1780 , a GUI for DataSets.jl would be a good way to pick this up again!

**Comment by pankgeorg** [comment]
oh my god this has been a year :|
