### ISSUE TITLE
Frontend tests are broken

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#951]
Check our recent commits to master and the PRs

**Comment by fonsp** [comment]
I clicked "Disable workflow" on https://github.com/fonsp/Pluto.jl/actions/workflows/FrontendTest.yml to 'fix' it

**Comment by pankgeorg** [comment]
https://github.com/fonsp/Pluto.jl/runs/1979363951
This run, after I updated the version string, run successfully; the previous ones failed most likely due to the unhit `Alert, newer version available`.

**Comment by fonsp** [comment]
ooooh nice!

**Comment by fonsp** [comment]
Can you update the master version to `0.14.0` and merge that into PRs?

**Comment by pankgeorg** [comment]
YES!

**Comment by fonsp** [comment]
I guess a more permanent fix would be to have a server config to disable the version popup?

**Comment by pankgeorg** [comment]
Either that or tell puppeteer to click the alert

**Comment by pankgeorg** [comment]
Fixed in #963
