### ISSUE TITLE
Use CommonMark instead of Markdown in sample notebooks

### ISSUE THREAD

**Issue by jlewis91** [fonsp/Pluto.jl#957]
## Problem

Julia's current markdown library has numerous [unresolved issues](https://github.com/JuliaLang/julia/issues?q=is%3Aopen+is%3Aissue+label%3Amarkdown) and the heavy use of the library in `Pluto.jl` is creating numerous follow on issues in the Pluto.jl project for what is an integral, but unrelated dependency:

- https://github.com/fonsp/Pluto.jl/issues/162
- https://github.com/fonsp/Pluto.jl/issues/856
- https://github.com/fonsp/Pluto.jl/issues/731
- https://github.com/fonsp/Pluto.jl/issues/704
- https://github.com/fonsp/Pluto.jl/issues/678

## Proposed Solution

Fortunately, there is a new, nicely architected (and well-tested) library, [CommonMark.jl](https://github.com/MichaelHatherly/CommonMark.jl) which can be used as a (nearly) drop-in replacement in the sample notebooks (ignoring for the moment the particular use cases for `Pluto.jl` internals. This library is [under consideration for inclusion in Julia's stdlib](https://github.com/JuliaLang/julia/issues/37337) and forms an easier to reason about basis for making notebook computing 'simpler and more accessible'.

## Note

As far as I can tell, the CommonMark is missing a macro to make strings 'just work' as markdown text. If this proposal is accepted, this macro could potentially be added to the `Pluto.jl` project and then eventually integrated into the `CommonMark.jl` package.

I have converted one notebook in a PR as an example so that you can assess the overall impact of this change.

https://github.com/fonsp/Pluto.jl/pull/956

**Comment by fonsp** [comment]
Discussion continued in https://github.com/fonsp/Pluto.jl/pull/956#issuecomment-787823526
