### ISSUE TITLE
Reactivity breaks with Cmd string Interpolation

### ISSUE THREAD

**Issue by pankgeorg** [fonsp/Pluto.jl#961]
https://user-images.githubusercontent.com/8681967/109659945-f01e4000-7b70-11eb-8d56-4204a32a97f3.mp4

Consider the above example:

Reactivity doesn't take into consideration interpolation done in backtick strings.

This is used in @c42f 's https://github.com/JuliaComputing/SQLStrings.jl

Any ideas/am I missing something?

**Comment by fonsp** [comment]
This issue was posted and fixed before but I can't find it... hmmmmm

**Comment by c42f** [comment]
Would it work to just macro expand everything and inspect the resulting expressions for symbols rather than having a whitelist? A naive version of this could be spoiled by macros which have side effects, but perhaps that could be solved by saving the expanded expressions and sending those for evaluation, rather than the original source?

Oh, I see there's https://github.com/fonsp/Pluto.jl/issues/196 which shows this is a somewhat tricky problem in general. Seems solvable to me though.

**Comment by pankgeorg** [comment]
Fons, the whitelisting doesn't seem to exactly work out of the box; I'll keep digging!

@c42f it feels it's out of my league, tbh :( 
Pluto+SQL is a ✨🌟🌠charm🥰🤯 to nest SQL queries, filters, due to reactivity, so I'd love to get reactivity to work with SQLString too!

**Comment by c42f** [comment]
Yeah it's tricky. Nothing wrong with a bit of whitelisting until someone has the time to do something more comprehensive!

**Comment by fonsp** [comment]
@pankgeorg My guess is that the whitelisting didn't work because the "macro" name is neither a `Symbol` nor a "`.` expression":

```julia
julia> dump(:(`123`))
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: GlobalRef
      mod: Module Core
      name: Symbol @cmd
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[9]
    3: String "123"

julia> dump(:(A.b"123"))
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Expr
      head: Symbol .
      args: Array{Any}((2,))
        1: Symbol A
        2: QuoteNode
          value: Symbol @b_str
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[10]
    3: String "123"

julia> dump(:(a"123"))
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Symbol @a_str
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[11]
    3: String "123"
```

@c42f If you want to help with #196, that would be amazing! We should definitely call sometime!
