### ISSUE TITLE
Paste notebook file contents to open it

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#964]
It would be nice if you could paste the contents of a notebook file into the main menu to open it.

We might want to:
- add an HTTP endpoint for "open notebook contents", or even better: use the existing "open notebook URL" with a base64 data uri, if julia can easily support that
- trim whitespace at the ends of the paste content 
- EDIT: perhaps we should trim not just whitespace, but anything before the `### A Pluto.jl notebook ###` and anything after the last cell. (We don't need to 'trim' the end, we just make sure that our parser ignores anything after the last cell.) The motivation here is that someone sent notebook contents as an email, and you just press `Ctrl+A` on the gmail page (which also copies the gmail logo etc).
- also support drag-dropping a .jl file onto the main menu. The problem here is that users might falsely assume that this will _edit_ that file (unless #833 is working)
- also support drag-dropping notebook file contents into the main menu, i.e. not a file but its selected contents
- also support pasting it into the blue box

@ctrekker @pankgeorg Can you either self-assign or make this a Good First Issue?

**Comment by pankgeorg** [comment]
I got this, had the same issue at work (I expose a pluto on a jupyterlab on the 'cloud' and people are like 'where are my notebooks').

What about also supporting drag and drop --> open notebook?

**Comment by fonsp** [comment]
@paradocs

**Comment by paradocs** [comment]
Yes, we need Pasting Notebooks.  It is excellent to:
* Distinguish Pluto as the easiest to use notebook
* Let un-trained teachers/users run Pluto in a moment
* Fit in with Pluto's outstanding readable  .jl  file   
* E-mail for fast sharing and searching of notebooks
* Allow a binder session to start several notebooks

Fixing or warning of a faulty copy is good.
Clean up both start ### A Pluto.jl  and end   # ╠═
 
To select a complete notebook at the end of
a g-mail, a web-page, or a text file just 
place the cursor on the line above the 2nd #,
left click and move diagonally to the margin. 
This method requires a blank line above.
If we start after the first #, we only miss
one #.  Just correct this pragmatically.

**Comment by fonsp** [comment]
@paradocs This has been implemented, update Pluto to try it out!
