### ISSUE TITLE
Allow user-specified authentication secret

### ISSUE THREAD

**Issue by david-macmahon** [fonsp/Pluto.jl#969]
I've recently started using my local browser with SSH port forwarding to access remote Pluto notebooks running on remote servers.  Some of the remote servers are very remote and this results in an amazingly more responsive experience compared to how I was doing things before (i.e. firefox in a VNC session on the remote servers).  Unfortunately, I now realize that all the Pluto servers have different authentication "secrets", which makes it difficult/inconvenient to work on notebooks on different servers (and impossible to do so simultaneously).  For my setup, it's OK to run Pluto with `require_secret_for_access=false` (for now), but it would be nice if I could specify the secret that Pluto uses.  Then I could use a common secret across all my Pluto servers so I can access them all seamlessly and still use an authentication secret.

**Comment by fonsp** [comment]
Since your connection is already secured by SSH, `require_secret_for_access=false` is a good solution. This does **not** disable authentication, it still protects against XSS. 

The purpose of `require_secret_for_access=true` is to protect against other people who have access to your `localhost`. This includes:
- people logged in on the same computer
- anyone on the internet, if you forwarded your port (not recommended)

**Comment by fonsp** [comment]
We can discuss the original issue ("Allow user-specified authentication secret ") if there is new reason to do so

**Comment by david-macmahon** [comment]
I'm not the only person logging onto these systems so without the authentication "secret" it seems too easy to accidentally connect to someone else's server.  We're all on the same team, but the potential for confusion and the inadvertent "oops, sorry!" remains. This could be mitigated by assigning specific ports to specific users, but that doesn't scale very well.

Another thing that could help (but is really a separate feature request) is to have some visual indicator unique to the Pluto server process.  For example, the ability to specify background color on a per Pluto server basis or the ability to include a custom string that the Pluto server would display in the "header" at the top of each notebook.  I find myself working on different instances of the same notebook on multiple remote servers and frequently lose track of which notebook is on which remote server.

**Comment by david-macmahon** [comment]
I think a basic level of allowing a user-specified authentication secret could be accomplished by changing [this line](https://github.com/fonsp/Pluto.jl/blob/b8398b01272a5c583b664359ccbb52064dd224af/src/webserver/Session.jl#L47):
```
secret::String = String(rand(('a':'z') ∪ ('A':'Z') ∪ ('0':'9'), 8))
```
to
```
secret::String = get(ENV, "PLUTO_SECRET", String(rand(('a':'z') ∪ ('A':'Z') ∪ ('0':'9'), 8)))
```

Then the user could launch Pluto with something like, for example:
```
env PLUTO_SECRET=`cat ~/.pluto_secret` julia -e 'import Pluto; Pluto.run()'
```

**Comment by fonsp** [comment]
Okay, in that case you can do it like so:
```julia
julia> import Pluto

julia> s = Pluto.ServerSession(secret="hello");

julia> Pluto.run(s)

Opening http://localhost:1235/?secret=hello in your default browser... ~ have fun!

Press Ctrl+C in this terminal to stop Pluto

```

**Comment by KingBoomie** [comment]
I still wanted to share access to my (secret) notebooks with people I know, without needing to update the link every time I need to restart julia. I still wish that the secret could be defined like all the other configuration options, but since it isn't, I currently have to run pluto like this: 
```bash
julia -O3 --eval 'using Pluto; Pluto.run(Pluto.ServerSession(secret="very-secret-dont-tell-anyone-pls", options=Pluto.Configuration.from_flat_kwargs(host="0.0.0.0", port=1234)))'

```
