### ISSUE TITLE
Automatic sorting of notebook cells?

### ISSUE THREAD

**Issue by oschulz** [fonsp/Pluto.jl#974]
Just an idea (not fully thought out either, I'll admit) - sorry if this has already been discussed.

Pluto's non-linear evaluation order let's users have cells in basically any order - while a notebook evolves (users jumping around and inserting things here and there), that can potentially lead to notebooks that are very non-linear and hard to read (since humans kinda to tend to read in a top-down fashion), even though they'll be functioning perfectly fine.

Would it be helpful to have a "sort my notebook" button that performs a [topological sort](https://en.wikipedia.org/wiki/Topological_sorting) of the cells according to the dependency DAG?

The problem is, what to do with text cells? One could treat all text cells before a code cell as "attached" to it, and move them when the code cell get's moved during sort - but is this what the user would want?

**Comment by fonsp** [comment]
Can you post this suggestion to our built in feature request system? https://github.com/fonsp/Pluto.jl/issues/182

**Comment by oschulz** [comment]
Uh, I tried, but I get this

```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```
