### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by cscherrer** [fonsp/Pluto.jl#979]
Hi,

Pluto's static analysis is having some problems with this:
![pluto-error](https://user-images.githubusercontent.com/1184449/110251988-245e7b80-7f38-11eb-915c-9b1a3b8384d2.png)

The `x` in the first expression should be considered as a local variable. There are a few ways to check this, for example that `g` evaluates successfully when `x` is not in scope.

Is there a way I could nudge Pluto in the right direction to correct its analysis?

**Comment by pankgeorg** [comment]
Unfortunately, that's a known issue #196 
![image](https://user-images.githubusercontent.com/8681967/110255419-4be72f80-7f9c-11eb-85a5-0a84426e6b42.png)
The code doesn't seem to work - do you have a working example?
Also can you paste the cell output (along with the image please!)

This is a hack, but _may_ work for your case:

```
# ╔═╡ c40e053b-8666-4686-8368-16118b1ced72
using Soss

# ╔═╡ dee63abc-9bd8-4cb0-8f40-b87ff544255b
g = let
	@model begin
		x ~ Normal() |> iid(10)
		α ~ Normal()
		β ~ Normal()
		y ~ For(x) do xj
			Normal(μ = α + β*xj)
		end
	end;
end

# ╔═╡ 0abd4d1e-3ce2-4bf5-9bb3-8a806f147dde
truth = rand(g())

# ╔═╡ 5073790b-c28c-4aa9-9040-01cc5d780b8c
x = thuth.x
```

**Comment by cscherrer** [comment]
I'm not sure I understand, do you mean like this?
```julia
### A Pluto.jl notebook ###
# v0.12.21

using Markdown
using InteractiveUtils

# ╔═╡ 936828d0-7f4e-11eb-0e65-85b3dfa34afa
using Soss

# ╔═╡ 6c5fd266-7f7a-11eb-0c40-0fd86f9e667a
x = truth.x

# ╔═╡ ff6ff3f4-7f4f-11eb-3cd4-0b054c16fbc2
truth = rand(g())

# ╔═╡ 9e1cd4ec-7f4e-11eb-0b16-31453072ae05
g = let
	@model begin
		x ~ Normal() |> iid(10)
		α ~ Normal()
		β ~ Normal()
		y ~ For(x) do xj
			Normal(μ = α + β*xj)
		end
	end;
end

# ╔═╡ Cell order:
# ╠═936828d0-7f4e-11eb-0e65-85b3dfa34afa
# ╠═9e1cd4ec-7f4e-11eb-0b16-31453072ae05
# ╠═ff6ff3f4-7f4f-11eb-3cd4-0b054c16fbc2
# ╠═6c5fd266-7f7a-11eb-0c40-0fd86f9e667a
```

The only change I see is wrapping it in a `let`, is that right? That didn't seem to work :(

Oh, and this is using the master branch of Soss.jl. So it uses MeasureTheory.jl instead of Distributions.jl

**Comment by dralletje** [comment]
For now, however inconvenient, you can use this small fix

```julia
# ╔═╡ 45ac9f8f-8261-47a6-a7be-813f0135b338
macro plutofix(block)
	transform(block) do expr
		if expr.head == :local && expr.args[1].head == :(=)
			Expr(:call, :(~), expr.args[1].args...)
		else
			expr
		end
	end
end

# ╔═╡ 0815cfff-ee4a-4018-b47d-786a1c078bd5
function transform(fn::Function, x) x end

# ╔═╡ 9b8c277a-5b70-4d35-9175-da165ec4226e
function transform(fn::Function, ast::Expr)
	local new_ast = Expr(ast.head, transform.(fn, ast.args)...)
	return fn(new_ast)
end
```

Then wrap the whole @model call in this @plutofix
```julia
g = @plutofix @model begin
	local x = Normal() |> iid(10)
	α ~ Normal()
	β ~ Normal()
	y ~ For(x) do xj
		Normal(μ = α + β*xj)
	end
end
```

It "just" transforms `local $(something) = $(somethingelse)` into `$(something) ~ $(somethingelse)`.
Keep thinking about a better solution too, but for now you can at least run your models.

Also let me know if it conflicts with something else in the syntax, could make a more explicit version if needed.

**Comment by cscherrer** [comment]
I'll try this, thank you @dralletje
