### ISSUE TITLE
Switch CTRL+Enter and Shift+Enter behaviour?

### ISSUE THREAD

**Issue by crstnbr** [fonsp/Pluto.jl#980]
Currently, Shift+Enter evaluates a cell while CTRL+Enter evaluates the cell and creates a new cell below. Jupyter notebooks (and some IDEs with cell support) use the same key combinations for these features but exactly the other way around, i.e. Shift+Enter to evaluate plus create a new cell. Wouldn't it make sense to align the behaviour to existing tools? If there is a deeper meaning to why the shortcuts have been chosen as they are I would appreciate it to be enlightened.

(Personally, I always get annoyed when new tools come around and confuse me by only slightly different keyboard shortcuts.)

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/pull/363
