### ISSUE TITLE
Logo in README in DarkMode on Github

### ISSUE THREAD

**Issue by cormullion** [fonsp/Pluto.jl#982]
Now that Github has a dark mode, logos in black are pretty hard to see:

<img width="1243" alt="Screenshot 2021-03-08 at 15 17 42" src="https://user-images.githubusercontent.com/52289/110352232-99f84380-802d-11eb-9726-8488137756a7.png">

If you make a version with an outline in white, it looks better:

<img width="811" alt="Screenshot 2021-03-08 at 16 49 16" src="https://user-images.githubusercontent.com/52289/110352790-3f131c00-802e-11eb-9c59-d33f4cd9e850.png">

which looks OK on a white github too:

<img width="812" alt="Screenshot 2021-03-08 at 16 52 47" src="https://user-images.githubusercontent.com/52289/110353255-c06aae80-802e-11eb-83b8-5de3e3d23dfc.png">

**Comment by fonsp** [comment]
Thanks @cormullion ! I just updated the readme, have a look!

**Comment by cormullion** [comment]
Perfect! 😃
