### ISSUE TITLE
Hide hide/show code button

### ISSUE THREAD

**Issue by ixzh** [fonsp/Pluto.jl#984]
Hi,

not an issue but more of a feature request.

Is there a way to activate cell editing by key shortcut and hide these "tiny eye" completely? not very nice in a presentation.

Similarly not very nice is the scroll bar when displaying a large dataframe :)

![image](https://user-images.githubusercontent.com/14981695/110433045-ee152d80-80ea-11eb-9a63-0c58febc010f.png)

**Comment by fonsp** [comment]
If I understand your request correctly, the option to hide all UI will be added by https://github.com/fonsp/Pluto.jl/pull/811

I am closing this for now because it is a [feature request or usage question](https://github.com/fonsp/Pluto.jl/issues/182)
