### ISSUE TITLE
Immer patch error messages are too scary

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#987]
> "Cannot recover from broken state. Please open an issue!"

and

> "PlutoState failed to sync with the browser!
Please report this: https://github.com/fonsp/Pluto.jl/issues
adding the info you can find in the JS Console (F12)"

This contains lots of Pluto dev jargon, and the real message should be:

> "Oopsie, **refresh your browser** and everything will be alright."

**Comment by pankgeorg** [comment]
😱😱😱
ok fixing 😇😇

**Comment by pankgeorg** [comment]
Note that the first alert was dev only - doesn't make sense for normal users, so I removed it at all. The message will be at console if anyone wants to share tickets
