### ISSUE TITLE
`subtypes(AbstractType)` is not reactive

### ISSUE THREAD

**Issue by joshday** [fonsp/Pluto.jl#989]
As the title says, `subtypes(AbstractType)` does not get updated if I add a new cell with a `struct New <: AbstractType end` definition.

**Comment by Pangoraw** [comment]
hi!
Unfortunately, Pluto's syntax analysis *currently* only references dependencies between cells, not objects. This means that both `struct New <: AbstractType end` and `subtypes(AbstractType)` are children of `abstract type New end` at the same level.
One workaround would be to group the abstract type declaration and the child struct declaration in the same cell with a `begin` block:
![example](https://user-images.githubusercontent.com/9824244/111062868-f33bf900-84ab-11eb-8ec4-f635e515043b.png)

**Comment by fonsp** [comment]
(Similar to `methods(function)`)
