### ISSUE TITLE
Horizontal scrolling for interactive arrays

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#99]
The new interactive arrays are extremely useful, especially for nested dicts like JSON data!

For really deep nested data, or entries with long texts the lines are longer than the notebook width and scrolling would be necessary. However there is no horizontal scrollbar for me.

**Comment by fonsp** [comment]
Oh whoops I disabled the scrollbar for interactive arrays without considering deeply nested objects, thanks!
It will be fixed in `0.8.4`
